# -*- coding: utf-8 -*-
"""Food & Culinary Category - 200 Real Clues"""

def get_food_data():
    def q(val, clue, ans, acc=None, src="Wikipedia - Gastronomy"):
        return {"value": val, "clue": clue, "answer": ans, "accepted": acc or [], "source": src}

    f_100 = [
        q(100, "The Italian dish consisting of a flat round base of leavened dough topped with tomato sauce, cheese, and toppings.", "Pizza", ["pizza pie"]),
        q(100, "The sweet food made from roasted and ground cacao seeds, available in dark, milk, and white varieties.", "Chocolate", ["cacao", "cocoa"]),
        q(100, "The primary fruit ingredient in traditional Mexican guacamole dip.", "Avocado", ["alligator pear"]),
        q(100, "The fermented spicy cabbage side dish that is a national staple of South Korea.", "Kimchi", ["gimchi"]),
        q(100, "The staple grain that feeds over half of the world's population, grown in flooded paddies.", "Rice", ["oryza sativa"]),
        q(100, "The traditional Japanese soup made from fermented soybean paste dissolved in dashi stock.", "Miso soup", ["misoshiru"]),
        q(100, "The French leavened crescent-shaped pastry made from layered laminated yeast dough with butter.", "Croissant", ["croissants"]),
        q(100, "The Italian pasta shape whose name translates from Italian to English as 'little worms'.", "Vermicelli", ["vermicelli pasta"]),
        q(100, "The citrus fruit that produces juice commonly mixed with water and sugar to make lemonade.", "Lemon", ["citrus limon"]),
        q(100, "The Mexican food consisting of a rolled maize tortilla filled with meat, cheese, beans, or vegetables.", "Taco", ["tacos"]),
        q(100, "The popular hot beverage brewed from roasted coffea beans, native to Ethiopia.", "Coffee", ["espresso"]),
        q(100, "The staple Italian hard granular cheese with protected designation originating from Parma and Reggio Emilia.", "Parmesan", ["parmigiano reggiano"]),
        q(100, "The condiment made from fermented soybeans, roasted grain, water, and salt, fundamental to East Asian cuisine.", "Soy sauce", ["shoyu"]),
        q(100, "The sweet viscous food substance made by bees from the floral nectar of plants.", "Honey", ["bee honey"]),
        q(100, "The staple food made of dough from flour and water, baked in loaves throughout world history.", "Bread", ["loaf of bread"]),
        q(100, "The Japanese dish consisting of vinegared rice combined with raw seafood, vegetables, and nori.", "Sushi", ["nigiri", "maki"]),
        q(100, "The cold dessert made from dairy products like milk and cream combined with fruits and flavorings.", "Ice cream", ["gelato"]),
        q(100, "The common table spice ground from dried unripe drupes of Piper nigrum, paired with salt.", "Black pepper", ["peppercorn", "pepper"]),
        q(100, "The dairy product made by churning fermented or fresh cream into a semi-solid fat spread.", "Butter", ["dairy butter"]),
        q(100, "The Italian dessert made of ladyfingers dipped in espresso layered with whipped mascarpone cream and cocoa.", "Tiramisu", ["tiramisù"]),
        q(100, "The pungent bulb related to onions used as a flavoring across world cuisines, famous for warding off vampires.", "Garlic", ["allium sativum"]),
        q(100, "The popular beverage made by infusing cured leaves of the Camellia sinensis plant in boiling water.", "Tea", ["camellia sinensis"]),
        q(100, "The French bread characterized by its long, thin loaf with a crisp golden crust.", "Baguette", ["french bread"]),
        q(100, "The sweet crystalline carbohydrate substance obtained primarily from sugar cane and sugar beet.", "Sugar", ["sucrose", "cane sugar"]),
        q(100, "The green herb with aromatic leaves widely used in Italian pesto sauce along with pine nuts.", "Basil", ["sweet basil"]),
        q(100, "The fast food sandwich consisting of a cooked patty of ground meat inside a sliced bun.", "Hamburger", ["burger"]),
        q(100, "The fruit of the olive tree from which extra virgin oil is cold-pressed for Mediterranean cooking.", "Olive", ["olives"]),
        q(100, "The Indian bread baked inside a cylindrical clay tandoor oven, often brushed with garlic butter.", "Naan", ["naan bread"]),
        q(100, "The cured meat made from the hind leg of a pig, preserved through salting, smoking, or wet curing.", "Ham", ["prosciutto", "jamon"]),
        q(100, "The creamy emulsion of oil, egg yolk, and an acid like vinegar or lemon juice, used as a sandwich spread.", "Mayonnaise", ["mayo"]),
        q(100, "The thick red condiment made from tomatoes, vinegar, sugar, and seasonings.", "Ketchup", ["catsup"]),
        q(100, "The Greek dip made from salted strained yogurt mixed with cucumbers, garlic, olive oil, and dill.", "Tzatziki", ["tzatziki sauce"]),
        q(100, "The yellow dairy cheese originating in the English village of the same name in Somerset.", "Cheddar cheese", ["cheddar"]),
        q(100, "The underground edible tuber native to the Andes that became a global food staple, fried as chips.", "Potato", ["solanum tuberosum"]),
        q(100, "The breakfast dish made by beating eggs and cooking them in a frying pan folded over cheese or vegetables.", "Omelette", ["omelet"]),
        q(100, "The Japanese green tea powder whisked into water in traditional Japanese tea ceremonies.", "Matcha", ["matcha powder"]),
        q(100, "The thick Mexican sauce containing chilies, spices, fruit, and bitter chocolate served over turkey or chicken.", "Mole", ["mole poblano"]),
        q(100, "The cured meat sausage of Italian origin seasoned with paprika and chili peppers, popular pizza topping.", "Pepperoni", ["pepperoni sausage"]),
        q(100, "The sweet, thick syrup made from the xylem sap of sugar maple trees.", "Maple syrup", ["maple"]),
        q(100, "The round deep-fried pastry dough snack with a ring shape or filled center, often glazed.", "Doughnut", ["donut"])
    ]

    f_200 = [
        q(200, "The prized and most expensive spice in the world by weight, hand-harvested from the stigmas of the purple crocus flower.", "Saffron", ["crocus sativus"]),
        q(200, "The brined curd white cheese traditionally made in Greece from sheep's milk or a blend with goat's milk.", "Feta cheese", ["feta"]),
        q(200, "The Japanese delicacy prepared from poisonous pufferfish that can be fatal if the tetrodotoxin is not removed.", "Fugu", ["blowfish", "pufferfish"]),
        q(200, "The rare subterranean fungus hunted with trained pigs or dogs, with white varieties commanding thousands per pound.", "Truffle", ["truffles", "tartufo"]),
        q(200, "The Spanish rice dish originating in Valencia traditionally cooked in a shallow flat round pan over an open fire.", "Paella", ["paella valenciana"]),
        q(200, "The cured unsmoked Italian pork cold cut made from thinly sliced pork neck/shoulder (coppa) or jowl.", "Guanciale", ["pancetta"]),
        q(200, "The French culinary technique of cooking food submerged in oil or fat at low temperature for preservation.", "Confit", ["duck confit"]),
        q(200, "The fermented tea drink produced by fermenting sweetened tea with a symbiotic culture of bacteria and yeast (SCOBY).", "Kombucha", ["kombucha tea"]),
        q(200, "The Italian coffee beverage prepared with equal parts espresso, steamed milk, and milk froth.", "Cappuccino", ["cappuccino"]),
        q(200, "The Middle Eastern dip made from cooked, mashed chickpeas blended with tahini, lemon juice, and garlic.", "Hummus", ["hummus dip"]),
        q(200, "The delicate French confection made with almond flour, egg whites, and sugar, sandwiched with ganache.", "Macaron", ["french macaron"]),
        q(200, "The spicy paste made from ground rhizomes of Eutrema japonicum served alongside sushi and sashimi.", "Wasabi", ["japanese horseradish"]),
        q(200, "The French technique of coating a piece of meat with flour, browning it in butter, and braising in broth and wine.", "Fricassee", ["fricassée"]),
        q(200, "The North African dish consisting of steamed semolina granules traditionally served with stew spooned on top.", "Couscous", ["kuskus"]),
        q(200, "The Italian rice dish cooked gradually in broth to a creamy consistency, typically made with Arborio rice.", "Risotto", ["risotto alla milanese"]),
        q(200, "The soft cow's-milk cheese named after the French historic region where it originated, featuring a bloomy edible rind.", "Brie", ["brie de meaux"]),
        q(200, "The scale used to measure the pungency and heat of chili peppers based on capsaicin concentration.", "Scoville scale", ["scoville heat units"]),
        q(200, "The Vietnamese noodle soup consisting of broth, rice noodles, herbs, and thinly sliced beef or chicken.", "Pho", ["phở"]),
        q(200, "The traditional Hungarian stew of meat and vegetables seasoned with sweet paprika and caraway seeds.", "Goulash", ["gulyas"]),
        q(200, "The cooking technique where food is placed in a plastic pouch and cooked in a water bath at a precisely controlled temperature.", "Sous-vide", ["sous vide"]),
        q(200, "The Greek meat dish cooked on a vertical rotisserie, served wrapped in pita bread with tomato and tzatziki.", "Gyros", ["gyro"]),
        q(200, "The blue-veined Italian cheese produced in the northern region of Lombardy from unskimmed cow's milk.", "Gorgonzola", ["gorgonzola cheese"]),
        q(200, "The fermented dough leavened naturally by wild lactic acid bacteria and yeasts without commercial baker's yeast.", "Sourdough", ["sourdough bread"]),
        q(200, "The French mother sauce made from a roux of butter and flour cooked with milk, foundation of white sauces.", "Bechamel", ["béchamel sauce"]),
        q(200, "The traditional Japanese grilled meat skewers of bite-sized chicken parts cooked over binchotan charcoal.", "Yakitori", ["kushiyaki"]),
        q(200, "The dark brown yeast extract paste produced as a byproduct of beer brewing, popular as a breakfast spread in the UK.", "Marmite", ["vegemite"]),
        q(200, "The Peruvian national dish consisting of fresh raw fish cured in fresh citrus juice spiced with aji chilies.", "Ceviche", ["cebiche"]),
        q(200, "The hard, pale yellow Swiss cheese with distinctive holes ('eyes') caused by carbon dioxide-producing bacteria.", "Emmental cheese", ["swiss cheese", "emmentaler"]),
        q(200, "The Italian pasta sauce made with egg yolks, hard cheese (Pecorino Romano), cured pork (guanciale), and black pepper.", "Carbonara", ["pasta alla carbonara"]),
        q(200, "The sweet paste made of ground almonds and sugar or honey, often shaped into miniature fruits.", "Marzipan", ["marzapane"]),
        q(200, "The traditional Jewish bread made from braided enriched dough, traditionally eaten on Shabbat and holidays.", "Challah", ["challah bread"]),
        q(200, "The French culinary vegetable base mixture composed of two parts onion, one part carrot, and one part celery.", "Mirepoix", ["french mirepoix"]),
        q(200, "The spicy Thai soup flavored with fragrant lemongrass, kaffir lime leaves, galangal, lime juice, and chili peppers.", "Tom Yum", ["tom yam"]),
        q(200, "The hard Spanish cheese made in the La Mancha region from the whole milk of Manchega sheep.", "Manchego cheese", ["queso manchego"]),
        q(200, "The cooking method involving searing food at high heat and then finishing it covered at lower temperature with liquid.", "Braising", ["braise"]),
        q(200, "The Greek filo pastry pie layered with chopped spinach, feta cheese, onions, and seasonings.", "Spanakopita", ["spinach pie"]),
        q(200, "The Mexican spirit distilled from the fermented blue agave plant, produced primarily in the state of Jalisco.", "Tequila", ["blue agave tequila"]),
        q(200, "The soft Italian whey cheese made from the whey left over from the production of other cheeses.", "Ricotta", ["ricotta cheese"]),
        q(200, "The French mother sauce made from an emulsion of egg yolks, melted clarified butter, and lemon juice.", "Hollandaise sauce", ["hollandaise"]),
        q(200, "The pungent, creamy blue cheese from south-central France aged in natural Combalou caves, made from sheep's milk.", "Roquefort", ["roquefort cheese"])
    ]

    f_300 = [
        q(300, "The Japanese culinary concept of high-end, multi-course seasonal dining that originated in traditional tea ceremony meals.", "Kaiseki", ["kaiseki-ryori"]),
        q(300, "The Italian cured meat made from unsmoked pork belly rolled into a tight cylinder and seasoned with pepper and herbs.", "Pancetta", ["pancetta arrotolata"]),
        q(300, "The French term for the organized preparation and staging of ingredients and utensils before starting to cook.", "Mise en place", ["misenplace"]),
        q(300, "The chemical reaction between amino acids and reducing sugars that produces the browned, savory flavor of seared meat and bread crust.", "Maillard reaction", ["maillard browning"]),
        q(300, "The fermented Korean chili paste made from chili powder, glutinous rice, fermented soybeans, and salt.", "Gochujang", ["hot pepper paste"]),
        q(300, "The French mother sauce made from browned veal or beef stock thickened with a brown roux, tomato paste, and mirepoix.", "Espagnole sauce", ["brown sauce"]),
        q(300, "The intensely flavored cured dried roe pouch of grey mullet or bluefin tuna, sliced thinly over pasta in Mediterranean cuisine.", "Bottarga", ["poutargue", "karasumi"]),
        q(300, "The North African clay cooking pot with a distinctive conical lid that traps condensation to return moisture to simmering stews.", "Tagine", ["tajine"]),
        q(300, "The Italian pasta sauce originating in Naples made with tomatoes, black olives, capers, garlic, and anchovies.", "Puttanesca", ["alla puttanesca"]),
        q(300, "The cooking process of briefly submerging vegetables into boiling water and then immediately plunging them into ice water to halt cooking.", "Blanching", ["blanch and shock"]),
        q(300, "The Georgian baked cheese-filled bread topped with a raw egg yolk and butter, eaten by tearing the crust to dip.", "Khachapuri", ["adjaruli khachapuri"]),
        q(300, "The traditional Mexican soup made from nixtamalized hominy corn, pork, and dried red chiles like guajillo.", "Pozole", ["posole"]),
        q(300, "The delicate French clarified butter preparation where milk solids settle and are skimmed away to achieve a higher smoke point.", "Clarified butter", ["ghee", "drawn butter"]),
        q(300, "The Italian hard cheese made from whole sheep's milk, sharper and saltier than Parmigiano, used in Carbonara and Cacio e Pepe.", "Pecorino Romano", ["pecorino"]),
        q(300, "The process of treating whole corn kernels in an alkaline lime solution (calcium hydroxide) to make masa for tortillas.", "Nixtamalization", ["nixtamal"]),
        q(300, "The cold Spanish soup made of blended ripe tomatoes, cucumbers, bell peppers, garlic, olive oil, and stale bread.", "Gazpacho", ["andalusian gazpacho"]),
        q(300, "The French culinary preparation of chopped raw beef served with capers, onions, Worcestershire sauce, and a raw egg yolk.", "Steak tartare", ["tartare"]),
        q(300, "The Middle Eastern spice blend typically composed of dried thyme, sumac, toasted sesame seeds, and sea salt.", "Za'atar", ["zaatar"]),
        q(300, "The classic French cold sauce made from hollandaise emulsion flavored with reduced white wine, shallots, and tarragon.", "Bearnaise sauce", ["béarnaise"]),
        q(300, "The traditional Japanese charcoal made from ubame oak that burns cleanly at extremely high temperatures with no smoke.", "Binchotan", ["white charcoal"]),
        q(300, "The French savory open-faced tart with an egg-and-cream custard filling featuring bacon lardons, originating in Lorraine.", "Quiche Lorraine", ["quiche"]),
        q(300, "The traditional method of making sparkling champagne where secondary fermentation takes place inside the individual bottle.", "Methode Champenoise", ["traditional method"]),
        q(300, "The North African poached egg dish cooked in a spiced skillet stew of tomatoes, bell peppers, onions, and cumin.", "Shakshuka", ["shakshouka"]),
        q(300, "The French culinary thickener made of equal parts raw flour and softened butter kneaded together, whisked into simmering liquids.", "Beurre manie", ["beurre manié"]),
        q(300, "The rich liver pâté produced from the liver of a duck or goose that has been specially fattened by gavage feeding.", "Foie gras", ["foie-gras"]),
        q(300, "The Italian pasta sauce made from crushed garlic gently sauteed in olive oil, traditionally tossed with spaghetti.", "Aglio e olio", ["spaghetti aglio e olio"]),
        q(300, "The Japanese culinary term for the savory fifth taste mediated by glutamate receptors, identified by Kikunae Ikeda in 1908.", "Umami", ["the fifth taste"]),
        q(300, "The traditional French fish stew originating from the port city of Marseille featuring at least three varieties of Mediterranean fish.", "Bouillabaisse", ["bouillabaisse marseillaise"]),
        q(300, "The culinary process of cooking sugar until it decomposes into a golden-brown liquid with rich complex flavors around 340 degrees F.", "Caramelization", ["caramelizing"]),
        q(300, "The Italian dry-cured ham originating in Parma, salted and air-dried for at least 12 months, served thinly sliced.", "Prosciutto di Parma", ["prosciutto"]),
        q(300, "The South American herbal tea infusion prepared from the dried leaves of Ilex paraguariensis sipped through a metal bombilla straw.", "Yerba mate", ["mate tea"]),
        q(300, "The French culinary emulsion sauce made by whisking cold cubes of butter into a reduced mixture of white wine and shallots.", "Beurre blanc", ["white butter sauce"]),
        q(300, "The Greek layered baked casserole consisting of eggplant, spiced minced lamb or beef, and a thick bechamel custard topping.", "Moussaka", ["mousaka"]),
        q(300, "The Latin American confection made by slowly heating sweetened milk until it thickens and browns into a rich caramel spread.", "Dulce de leche", ["arequipe", "manjar"]),
        q(300, "The classic French mother sauce made from a light white stock (veal, chicken, fish) thickened with a blond roux.", "Veloute sauce", ["velouté"]),
        q(300, "The traditional Spanish cold almond and garlic soup originating in Malaga, garnished with green grapes.", "Ajo blanco", ["ajoblanco"]),
        q(300, "The traditional Indian clarified butter made by simmering butter until all moisture evaporates and milk solids lightly brown.", "Ghee", ["usli ghee"]),
        q(300, "The classic cocktail made with bourbon or rye whiskey, aromatic bitters, sugar, and an orange twist garnish.", "Old Fashioned", ["old fashioned cocktail"]),
        q(300, "The French dough made by cooking flour with boiling water and butter before beating in eggs, used for eclairs and profiteroles.", "Choux pastry", ["pate a choux"]),
        q(300, "The Italian pasta shape that resembles small rice grains, frequently used in soups and salads.", "Orzo", ["risoni"])
    ]

    f_400 = [
        q(400, "The traditional balsamic vinegar of Modena produced under strict PDO regulations must be aged for a minimum of this many years in barrels.", "12 years", ["twelve years", "12"]),
        q(400, "The dried fermented skipjack tuna loin shaved into tissue-thin savory flakes to make dashi stock in Japanese cuisine.", "Katsuobushi", ["bonito flakes"]),
        q(400, "The French culinary technique of covering a piece of meat with strips of pork fat before roasting to prevent it from drying out.", "Barding", ["larding"]),
        q(400, "The pungent southeast Asian fruit with a spiky exterior banned in public transit and hotels due to its overpowering sulfurous odor.", "Durian", ["durio"]),
        q(400, "The Spanish dry-cured ham made from free-range acorn-fed (bellota) Iberian black-hoofed pigs.", "Jamon Iberico de Bellota", ["pata negra", "jamon iberico"]),
        q(400, "The culinary hydrocolloid texturizing agent extracted from brown seaweed used in molecular gastronomy for spherification.", "Sodium alginate", ["alginate"]),
        q(400, "The traditional French dish of pressed duck (Canard a la presse) where the carcass is squeezed in a silver press to extract this sauce base.", "Duck blood and marrow", ["duck press sauce"]),
        q(400, "The rare, highly prized mushroom of the genus Morchella characterized by a distinctive honeycomb-like appearance.", "Morel", ["morel mushroom", "morchella"]),
        q(400, "The Japanese cut of tuna taken from the fattiest underbelly of the bluefin tuna, prized for melting texture.", "Otoro", ["o-toro", "toro"]),
        q(400, "The French mother sauce consisting of bechamel sauce enriched with grated Gruyere cheese and Parmesan.", "Mornay sauce", ["mornay"]),
        q(400, "The unpasteurized cow's milk French cheese from Franche-Comte aged in subterranean stone forts for up to 36 months.", "Comte cheese", ["comté"]),
        q(400, "The traditional Italian bitter digestive liqueur flavored with artichoke leaf extract among 13 herbs.", "Cynar", ["cynar liqueur"]),
        q(400, "The traditional Mexican fermented ceremonial alcoholic beverage made from the fermented sap (aguamiel) of maguey agave.", "Pulque", ["octli"]),
        q(400, "The ancient Roman fermented fish condiment used ubiquitous in antiquity as a source of salt and umami.", "Garum", ["liquamen"]),
        q(400, "The enzyme found in papayas used in culinary applications as an industrial natural meat tenderizer.", "Papain", ["papaya enzyme"]),
        q(400, "The French dish made from calf's pancreas or thymus gland, soaked, blanched, pressed, and sauteed.", "Sweetbreads", ["ris de veau"]),
        q(400, "The high-end Japanese beef characterized by intense intramuscular fat marbling, from Tajima-gyu cattle in Hyogo Prefecture.", "Kobe beef", ["wagyu"]),
        q(400, "The traditional Swedish fermented Baltic herring known for its pungent, overpowering rotten smell, eaten outdoors.", "Surstromming", ["surströmming"]),
        q(400, "The French culinary sauce made by deglazing a roasting pan with stock, reducing it, and enriching with blood and red wine, created by Escoffier.", "Sauce Bordelaise", ["bordelaise"]),
        q(400, "The wild herb also known as 'ramsons' harvested in European woodlands in early spring, smelling strongly of garlic.", "Wild garlic", ["allium ursinum", "bear's garlic"]),
        q(400, "The hard, brine-cured Italian sheep's milk cheese studded with whole black peppercorns from Sicily.", "Pepato", ["pecorino pepato"]),
        q(400, "The Spanish sparkling wine produced primarily in Catalonia using the traditional method, made from Macabeo, Xarel-lo, and Parellada grapes.", "Cava", ["cava wine"]),
        q(400, "The culinary process in chocolate making of continuously kneading, grinding, and aerating warm liquid chocolate to refine texture and flavor.", "Conching", ["conche"]),
        q(400, "The traditional Indonesian side dish made of fermented soybean cakes fermented with the fungal culture Rhizopus oligosporus.", "Tempeh", ["tempe"]),
        q(400, "The classic cocktail made with gin, Campari, and sweet red vermouth in equal parts, garnished with an orange peel.", "Negroni", ["negroni cocktail"]),
        q(400, "The French pastry cream enriched by folding in whipped heavy cream, used to fill fruit tarts.", "Creme diplomate", ["diplomat cream"]),
        q(400, "The spicy paste used in North African cooking made from roasted red peppers, Baklouti peppers, garlic, caraway seeds, and coriander.", "Harissa", ["harissa paste"]),
        q(400, "The Portuguese salt cod dish baked with thinly sliced potatoes, onions, and cream, named after its Lisbon creator.", "Bacalhau a Gomes de Sa", ["bacalhau"]),
        q(400, "The culinary term for the white pith membrane lying between the colored zest and the juicy flesh of a citrus fruit.", "Albedo", ["mesocarp", "pith"]),
        q(400, "The traditional Japanese tea-ceremony confectionery sweets made from sweet bean paste and rice flour.", "Wagashi", ["nerikiri"]),
        q(400, "The traditional Icelandic dish consisting of fermented sleeper shark meat that has been cured and hung to dry for four to five months.", "Hakarl", ["hákarl"]),
        q(400, "The Greek and Middle Eastern spice made from ground seeds of the wild St. Lucie cherry, lending an almond-vanilla flavor to breads.", "Mahleb", ["mahlab", "mahlepi"]),
        q(400, "The French term for clarified stock that has been refined using egg whites to produce a crystal-clear, intensely flavored soup.", "Consomme", ["consommé"]),
        q(400, "The Italian sparkling red wine from Emilia-Romagna produced from the grape variety of the same name.", "Lambrusco", ["lambrusco wine"]),
        q(400, "The traditional Georgian walnut sauce prepared with crushed walnuts, garlic, vinegar, and blue fenugreek, served cold over poultry.", "Satsivi", ["bazha"]),
        q(400, "The process of preserving meat by salting, seasoning, and curing it in natural animal casings without smoking.", "Salumi", ["charcuterie"]),
        q(400, "The Japanese mountain yam that turns into a thick, viscous, slimy paste when grated, eaten raw over soba noodles.", "Yamaimo", ["nagaimo", "tororo"]),
        q(400, "The traditional Mexican spirit produced in Oaxaca by pit-roasting agave hearts underground with volcanic rocks and mesquite wood.", "Mezcal", ["mezcal artesanal"]),
        q(400, "The classic French mother sauce made from fish veloute reduced with white wine, shallots, and heavy cream.", "Sauce Bercy", ["suprême sauce"]),
        q(400, "The hard pressed Italian cheese made from raw sheep's milk on the island of Sardinia, often smoked.", "Fiore Sardo", ["pecorino sardo"])
    ]

    f_500 = [
        q(500, "The ultra-rare, endangered white truffle species harvested almost exclusively in the Langhe hills around Alba in the Piedmont region.", "Tuber magnatum", ["tuber magnatum pico", "alba white truffle"]),
        q(500, "The traditional Sardinian sheep milk cheese that contains live insect larvae of the cheese fly (Piophila casei) to accelerate decomposition.", "Casu marzu", ["casu martzu", "rotten cheese"]),
        q(500, "The culinary process developed by Chef Ferran Adria at elBulli that uses calcium chloride and sodium alginate to encapsulate liquids in gel membranes.", "Direct spherification", ["reverse spherification", "spherification"]),
        q(500, "The 18th-century French culinary master considered the 'King of Chefs and the Chef of Kings' who codified the grand cuisine and designed elaborate sugar piéces montées.", "Marie-Antoine Careme", ["carême"]),
        q(500, "The ancient Roman cookbook collection compiled in the late 4th or early 5th century AD, commonly attributed to this Marcus Gavius.", "Apicius", ["de re coquinaria"]),
        q(500, "The highly prized cut of Iberian pork situated between the shoulder blade and loin, whose name in Spanish means 'secret'.", "Secreto iberico", ["secreto"]),
        q(500, "The Japanese culinary knife style with a single-bevel blade used specifically by sushi chefs to slice boneless fish fillets in razor-thin sheets.", "Yanagiba", ["yanagi ba"]),
        q(500, "The extremely toxic polypeptide found in the death cap mushroom (Amanita phalloides) that inhibits RNA polymerase II, fatal in tiny doses.", "Alpha-amanitin", ["amanitin"]),
        q(500, "The traditional Chinese culinary delicacy produced by preserving duck eggs in a mixture of clay, ash, salt, quicklime, and rice hulls for several months.", "Century egg", ["pidan", "thousand-year egg"]),
        q(500, "The Italian red wine from the Valpolicella zone made by fermenting partially dried Corvina, Rondinella, and Molinara grapes using the appassimento method.", "Amarone della Valpolicella", ["amarone"]),
        q(500, "The French culinary preparation technique where a whole fowl is stuffed inside another progressively smaller bird, known by this portmanteau.", "Roti sans pareil", ["ballotine", "turducken"]),
        q(500, "The fermented and dried skate fish delicacy native to the South Jeolla province of South Korea, notorious for emitting strong ammonia fumes.", "Hongeo-hoe", ["hongeo"]),
        q(500, "The wild mushroom of the genus Cortinarius containing the deadly toxin orellanine, which causes irreversible kidney failure up to three weeks after ingestion.", "Fool's webcap", ["cortinarius orellanus"]),
        q(500, "The traditional Mexican spirit produced from the wild agave Agave cupreata in the states of Guerrero and Michoacan, distinct from mezcal.", "Raicilla", ["bacanora"]),
        q(500, "The French chef who modernized and simplified Careme's grand cuisine, establishing the kitchen brigade system and writing Le Guide Culinaire.", "Auguste Escoffier", ["escoffier"]),
        q(500, "The rare edible Japanese bird's nest soup delicacy formed from the hardened salivary secretions of this specific avian species.", "Edible-nest swiftlet", ["aerodramus fuciphagus"]),
        q(500, "The traditional cheese-making coagulant enzyme historically extracted from the fourth stomach chamber (abomasum) of unweaned ruminant calves.", "Chymosin", ["rennet"]),
        q(500, "The indigenous Mexican preparation where whole dried agave hearts are buried in underground pits lined with volcanic stones and slow-roasted for days.", "Palenque pit roasting", ["tatemado"]),
        q(500, "The Portuguese wine from the Douro valley fortified with aguardente grape spirit mid-fermentation to halt yeast activity and retain residual sugar.", "Port wine", ["porto"]),
        q(500, "The 17th-century French master chef and maître d'hôtel to Prince de Conde who committed suicide in 1671 when the fish delivery was delayed at a royal banquet.", "Francois Vatel", ["vatel"]),
        q(500, "The traditional fermented fish paste produced in the Philippines by fermenting salted silver carp or shrimp, seasoned with roasted rice.", "Bagoong", ["bagoong monamon"]),
        q(500, "The French pastry component consisting of almond paste and sugar whipped with butter, invented by a Florentine nobleman who accompanied Catherine de' Medici.", "Frangipane", ["frangipani"]),
        q(500, "The classic cocktail developed at the Harry's New York Bar in Paris in 1923 combining equal parts gin, Cointreau, and Lillet Blanc with a dash of absinthe.", "Corpse Reviver No. 2", ["corpse reviver"]),
        q(500, "The Japanese fermentation mold fungus (Aspergillus oryzae) used to inoculate steamed rice to initiate brewing of sake, miso, and soy sauce.", "Koji", ["koji-kin"]),
        q(500, "The Mexican wild green herb belonging to the genus Porophyllum with an aromatic, citrusy flavor eaten raw with street tacos.", "Papalo", ["papaloquelite"]),
        q(500, "The traditional French confit-style specialty consisting of pork intestines, tripe, and seasonings packed inside natural casings and gently simmered.", "Andouillette", ["chitterling sausage"]),
        q(500, "The culinary process in candy making where sucrose is split into glucose and fructose by boiling with acid or adding the enzyme invertase.", "Inversion", ["invert sugar"]),
        q(500, "The Spanish dessert wine produced from dried grapes in the Montilla-Moriles region, characterized by deep mahogany color and raisin aroma.", "Pedro Ximenez", ["px sherry"]),
        q(500, "The traditional fermented dairy drink of Central Asian nomadic horse cultures produced by fermenting raw mare's milk.", "Kumis", ["airag"]),
        q(500, "The specialized Japanese knife with a heavy, thick spine used to cleanly chop the heads off fish and slice poultry bones without chipping.", "Deba bocho", ["deba knife"]),
        q(500, "The French dessert consisting of a tall cone of cream puffs (profiteroles) bound together with threads of spun caramel, created by Careme.", "Croquembouche", ["croque en bouche"]),
        q(500, "The traditional Mexican fermented corn dough beverage dating to the pre-Columbian Olmecs, flavored with cacao, epazote, and chili.", "Tejate", ["pozhoc"]),
        q(500, "The culinary hydrocolloid texturizer derived from the fermentation of glucose by the bacterium Xanthomonas campestris.", "Xanthan gum", ["xanthomonas"]),
        q(500, "The ancient Roman master chef who committed suicide by drinking poison after spending all but 10 million sesterces of his fortune on culinary extravagances.", "Marcus Gavius Apicius", ["apicius"]),
        q(500, "The traditional green Japanese citrus fruit with rough rind and acidic juice containing twice the vitamin C of lemons, prized in ponzu sauces.", "Sudachi", ["citrus sudachi"]),
        q(500, "The rare, highly prized coffee beans harvested from the droppings of the Asian palm civet that digests the coffee cherries.", "Kopi Luwak", ["civet coffee"]),
        q(500, "The French culinary sauce created for King Louis XVIII's chef made from veloute, white wine, shallots, bone marrow, and lemon juice.", "Sauce Chateaubriand", ["chateaubriand"]),
        q(500, "The unpasteurized sheep's milk cheese produced in Corsica whose exterior is washed with marc de raisin, having an intensely pungent aroma.", "Brocciu", ["casgiu merzu"]),
        q(500, "The traditional Peruvian underground earth-oven cooking pit lined with heated stones used to cook meats and tubers during festivals.", "Pachamanca", ["huatia"]),
        q(500, "The French master chef who founded the prestigious Bocuse d'Or international culinary competition in Lyon in 1987.", "Paul Bocuse", ["bocuse"])
    ]

    return f_100 + f_200 + f_300 + f_400 + f_500

if __name__ == "__main__":
    data = get_food_data()
    print(f"Food generated: {len(data)} clues")
