# -*- coding: utf-8 -*-
"""Geography Category - 200 Real Clues"""

def get_geography_data():
    def q(val, clue, ans, acc=None, src="Wikipedia - Geography"):
        return {"value": val, "clue": clue, "answer": ans, "accepted": acc or [], "source": src}

    g_100 = [
        q(100, "The longest river in the world, flowing through northeastern Africa into the Mediterranean Sea.", "Nile River", ["nile"]),
        q(100, "The capital city of France, famous for the Eiffel Tower and Louvre Museum.", "Paris", ["city of paris"]),
        q(100, "The highest mountain on Earth above sea level, located in the Himalayas.", "Mount Everest", ["everest", "mt everest"]),
        q(100, "The largest hot desert in the world, covering over 9 million square kilometers of North Africa.", "Sahara Desert", ["sahara"]),
        q(100, "The capital city of the United Kingdom, situated on the River Thames.", "London", ["city of london"]),
        q(100, "The largest ocean on Earth by surface area, covering more than 30% of the globe.", "Pacific Ocean", ["pacific"]),
        q(100, "The capital of Japan, known as the most populous metropolitan area in the world.", "Tokyo", ["city of tokyo"]),
        q(100, "The South American country famous for the Amazon rainforest and speaking Portuguese.", "Brazil", ["brasil"]),
        q(100, "The second largest country in the world by total land area, located north of the United States.", "Canada", ["dominion of canada"]),
        q(100, "The European nation shaped like a boot that surrounds Vatican City and San Marino.", "Italy", ["italian republic"]),
        q(100, "The capital of the United States, situated between Maryland and Virginia on the Potomac River.", "Washington D.C.", ["washington", "dc"]),
        q(100, "The island nation located southeast of Australia whose capital is Wellington.", "New Zealand", ["aotearoa"]),
        q(100, "The vast continent that contains the South Pole and is covered almost entirely in ice.", "Antarctica", ["south pole"]),
        q(100, "The capital city of Italy, home to the Colosseum and Trevi Fountain.", "Rome", ["roma"]),
        q(100, "The transcontinental country that spans Eastern Europe and Northern Asia, the largest country in the world.", "Russia", ["russian federation"]),
        q(100, "The capital of Egypt, situated near the ancient Giza pyramid complex.", "Cairo", ["al qahirah"]),
        q(100, "The canal connecting the Mediterranean Sea to the Red Sea, opened in 1869.", "Suez Canal", ["suez"]),
        q(100, "The capital city of Spain, home to the Prado Museum and Royal Palace.", "Madrid", ["city of madrid"]),
        q(100, "The Great Barrier Reef, the world's largest coral reef system, lies off the coast of this nation.", "Australia", ["commonwealth of australia"]),
        q(100, "The European mountain range that stretches across Switzerland, France, Italy, Austria, and Germany.", "The Alps", ["alps"]),
        q(100, "The capital of Germany, reunited following the fall of its famous Wall in 1989.", "Berlin", ["city of berlin"]),
        q(100, "The second most populous continent on Earth after Asia, containing 54 recognized sovereign countries.", "Africa", ["african continent"]),
        q(100, "The capital of China, home to the Forbidden City and Tiananmen Square.", "Beijing", ["peking"]),
        q(100, "The ocean separating the Americas from Europe and Africa.", "Atlantic Ocean", ["atlantic"]),
        q(100, "The capital city of Greece, regarded as the birthplace of Western democracy.", "Athens", ["athina"]),
        q(100, "The deep canyon carved by the Colorado River in northern Arizona.", "Grand Canyon", ["the grand canyon"]),
        q(100, "The capital of India, housing the Rashtrapati Bhavan and India Gate.", "New Delhi", ["delhi"]),
        q(100, "The country known as the 'Land of Fire and Ice' due to its glaciers and active volcanoes.", "Iceland", ["republic of iceland"]),
        q(100, "The world's largest island that is not classified as a continent, belonging to Denmark.", "Greenland", ["kalaallit nunaat"]),
        q(100, "The capital city of Russia, home to the Red Square and Saint Basil's Cathedral.", "Moscow", ["moskva"]),
        q(100, "The narrow body of water separating southern Spain from northern Morocco.", "Strait of Gibraltar", ["gibraltar"]),
        q(100, "The river that flows through New York City and separates it from New Jersey.", "Hudson River", ["hudson"]),
        q(100, "The capital city of South Korea, bisected by the Han River.", "Seoul", ["seoul special city"]),
        q(100, "The deepest lake in the world by volume, containing 20% of Earth's unfrozen surface freshwater in Siberia.", "Lake Baikal", ["baikal"]),
        q(100, "The capital of Mexico, built on the historic ruins of the Aztec capital Tenochtitlan.", "Mexico City", ["ciudad de mexico", "cdmx"]),
        q(100, "The tallest freestanding mountain in Africa, located in Tanzania.", "Mount Kilimanjaro", ["kilimanjaro"]),
        q(100, "The capital city of Canada, located in the province of Ontario.", "Ottawa", ["city of ottawa"]),
        q(100, "The archipelago nation consisting of over 17,000 islands whose capital is Jakarta.", "Indonesia", ["republic of indonesia"]),
        q(100, "The capital city of Ireland, famed for St Patrick's Cathedral and Temple Bar.", "Dublin", ["baile atha cliath"]),
        q(100, "The massive inland sea that borders Iran, Russia, Kazakhstan, Turkmenistan, and Azerbaijan.", "Caspian Sea", ["caspian"])
    ]

    g_200 = [
        q(200, "The purpose-built planned capital city of Australia, situated between Sydney and Melbourne.", "Canberra", ["city of canberra"]),
        q(200, "The longest mountain range in the world, running along the entire western coast of South America.", "The Andes", ["andes"]),
        q(200, "The landlocked country in Central Europe famous for its chocolate, watches, banks, and alpine neutrality.", "Switzerland", ["swiss confederation"]),
        q(200, "The capital of Portugal, situated on the Tagus River estuary where it enters the Atlantic.", "Lisbon", ["lisboa"]),
        q(200, "The highest active volcano in Europe, located on the eastern coast of Sicily.", "Mount Etna", ["etna"]),
        q(200, "The Southeast Asian nation formerly known as Siam that was never colonized by European powers.", "Thailand", ["kingdom of thailand"]),
        q(200, "The capital city of Sweden, built across an archipelago of fourteen islands.", "Stockholm", ["city of stockholm"]),
        q(200, "The river with the largest discharge volume of water in the world, flowing through northern Brazil.", "Amazon River", ["amazon"]),
        q(200, "The smallest independent sovereign state in the world by area and population, an enclave of Rome.", "Vatican City", ["the vatican", "holy see"]),
        q(200, "The capital city of Austria, celebrated as the historic 'City of Music' on the Danube.", "Vienna", ["wien"]),
        q(200, "The East African body of water that is the largest tropical lake in the world, shared by Uganda, Kenya, and Tanzania.", "Lake Victoria", ["victoria nyanza"]),
        q(200, "The capital city of the Netherlands, known for its extensive canal system and bikes.", "Amsterdam", ["city of amsterdam"]),
        q(200, "The landlocked desert country bordered by South Africa, Namibia, and Zimbabwe, home to the Kalahari.", "Botswana", ["republic of botswana"]),
        q(200, "The capital city of Norway, located at the head of the Oslofjord.", "Oslo", ["city of oslo"]),
        q(200, "The longest river in Europe, flowing entirely through Russia into the Caspian Sea.", "Volga River", ["volga"]),
        q(200, "The capital city of Poland, rebuilt after extensive destruction in World War II.", "Warsaw", ["warszawa"]),
        q(200, "The largest bay in the world by area, forming the northeastern part of the Indian Ocean.", "Bay of Bengal", ["bengal bay"]),
        q(200, "The capital city of Argentina, celebrated as the birthplace of the tango dance.", "Buenos Aires", ["buenos aires"]),
        q(200, "The mountain range that traditionally forms the boundary between Europe and Asia in Russia.", "Ural Mountains", ["the urals", "urals"]),
        q(200, "The capital city of Denmark, famous for Tivoli Gardens and the Little Mermaid statue.", "Copenhagen", ["kobenhavn"]),
        q(200, "The great desert spanning southern Mongolia and northern China, known for the ancient Silk Road.", "Gobi Desert", ["gobi"]),
        q(200, "The capital of Turkey, chosen to replace Istanbul when the republic was founded in 1923.", "Ankara", ["angora"]),
        q(200, "The longest river in Asia, flowing 6,300 km through China from the Tibetan Plateau to Shanghai.", "Yangtze River", ["yangtze", "chang jiang"]),
        q(200, "The capital city of Finland, situated on the shore of the Gulf of Finland.", "Helsinki", ["helsingfors"]),
        q(200, "The world's highest uninterrupted waterfall, dropping 979 meters in Venezuela.", "Angel Falls", ["salto angel"]),
        q(200, "The capital city of Belgium, which also serves as the de facto capital of the European Union.", "Brussels", ["bruxelles"]),
        q(200, "The island nation off the southeast coast of India, historically known as Ceylon until 1972.", "Sri Lanka", ["ceylon"]),
        q(200, "The capital city of Hungary, formed in 1873 by the unification of two historic cities on the Danube.", "Budapest", ["buda and pest"]),
        q(200, "The deepest oceanic trench in the world, plunging nearly 11,000 meters in the western North Pacific.", "Mariana Trench", ["challenger deep"]),
        q(200, "The capital city of Chile, nestled in a valley surrounded by the snow-capped Andes mountains.", "Santiago", ["santiago de chile"]),
        q(200, "The African lake that is the second-oldest, second-deepest, and longest freshwater lake in the world.", "Lake Tanganyika", ["tanganyika"]),
        q(200, "The capital city of the Czech Republic, known as the 'City of a Hundred Spires' on the Vltava River.", "Prague", ["praha"]),
        q(200, "The large peninsula in Southwest Asia that includes Saudi Arabia, Yemen, Oman, UAE, Qatar, and Kuwait.", "Arabian Peninsula", ["arabia"]),
        q(200, "The capital city of Peru, founded in 1535 by Spanish conquistador Francisco Pizarro.", "Lima", ["city of the kings"]),
        q(200, "The narrow strait that connects the Black Sea to the Sea of Marmara, dividing Istanbul.", "Bosphorus", ["bosporus strait"]),
        q(200, "The capital city of Colombia, situated at an altitude of 2,640 meters in the Andes.", "Bogota", ["bogotá"]),
        q(200, "The great African river that flows through Zambia and Mozambique into the Indian Ocean, home to Victoria Falls.", "Zambezi River", ["zambezi"]),
        q(200, "The capital city of the Philippines, situated on the eastern shore of Manila Bay on Luzon island.", "Manila", ["city of manila"]),
        q(200, "The island group belonging to Ecuador where Charles Darwin studied finches and tortoises.", "Galapagos Islands", ["galapagos"]),
        q(200, "The capital city of Cuba, famed for its colonial architecture and vintage American cars.", "Havana", ["la habana"])
    ]

    g_300 = [
        q(300, "The only country in the world that borders both the Caspian Sea and the Persian Gulf.", "Iran", ["islamic republic of iran", "persia"]),
        q(300, "The capital of New Zealand, recognized as the world's southernmost national capital city.", "Wellington", ["te whanganui-a-tara"]),
        q(300, "The river that forms much of the international border between the United States and Mexico.", "Rio Grande", ["rio bravo", "rio bravo del norte"]),
        q(300, "The capital city of Morocco, situated on the Atlantic Ocean at the mouth of the Bou Regreg River.", "Rabat", ["city of rabat"]),
        q(300, "The arid plateau region in southern Argentina and Chile extending from the Colorado River to Tierra del Fuego.", "Patagonia", ["patagonian desert"]),
        q(300, "The capital city of Vietnam, located on the banks of the Red River.", "Hanoi", ["ha noi"]),
        q(300, "The second-longest river in Europe, flowing from Germany's Black Forest into the Black Sea.", "Danube River", ["danube", "donau"]),
        q(300, "The capital city of Kenya, known as the 'Green City in the Sun'.", "Nairobi", ["city of nairobi"]),
        q(300, "The tiny European principality located in the Pyrenees mountains between France and Spain.", "Andorra", ["principality of andorra"]),
        q(300, "The capital city of Jordan, built on seven hills and one of the oldest continuously inhabited cities.", "Amman", ["city of amman"]),
        q(300, "The strait that separates the island of Sumatra from the Malay Peninsula, one of the world's busiest shipping lanes.", "Strait of Malacca", ["malacca"]),
        q(300, "The capital city of Ukraine, situated on the Dnieper River.", "Kyiv", ["kiev"]),
        q(300, "The great salt lake located in the Great Rift Valley between Jordan and Israel with salinity of over 34%.", "Dead Sea", ["yam hamelakh"]),
        q(300, "The capital city of Iceland, the northernmost capital of a sovereign state.", "Reykjavik", ["reykjavík"]),
        q(300, "The desert in northern Chile regarded as the driest non-polar desert in the world.", "Atacama Desert", ["atacama"]),
        q(300, "The capital city of Lebanon, historically dubbed the 'Paris of the Middle East'.", "Beirut", ["bayrut"]),
        q(300, "The mountain pass in the Alps connecting Austria and Italy, one of the principal passes of the Eastern Alps.", "Brenner Pass", ["passo del brennero"]),
        q(300, "The capital city of Croatia, situated on the slopes of Medvednica mountain along the Sava River.", "Zagreb", ["city of zagreb"]),
        q(300, "The Canadian bay that is the second-largest bay in the world, named after an English explorer.", "Hudson Bay", ["hudson's bay"]),
        q(300, "The capital city of Ecuador, situated at 2,850 meters altitude just south of the equator.", "Quito", ["san francisco de quito"]),
        q(300, "The sea surrounded by the Scandinavian Peninsula, Finland, the Baltic states, and Northern European plains.", "Baltic Sea", ["baltic"]),
        q(300, "The capital city of Romania, historically known as 'Little Paris' or 'Paris of the East'.", "Bucharest", ["bucuresti"]),
        q(300, "The highest mountain in North America, located in the Alaska Range, formerly named Mount McKinley.", "Denali", ["mount mckinley", "denali"]),
        q(300, "The capital city of Ethiopia, which also serves as the headquarters of the African Union.", "Addis Ababa", ["finfinne"]),
        q(300, "The island in the Mediterranean Sea that is partitioned between Greek Cypriots and Turkish Cypriots.", "Cyprus", ["republic of cyprus"]),
        q(300, "The capital city of Malaysia, famous for the 88-story Petronas Twin Towers.", "Kuala Lumpur", ["kl"]),
        q(300, "The sea located between Australia and New Zealand, named after a Dutch explorer.", "Tasman Sea", ["tasman"]),
        q(300, "The capital city of Uruguay, located on the northeastern bank of the Rio de la Plata.", "Montevideo", ["san felipe y santiago de montevideo"]),
        q(300, "The landlocked European country surrounded entirely by South Africa.", "Lesotho", ["kingdom of lesotho"]),
        q(300, "The capital city of Nepal, situated in a valley surrounded by four major mountains.", "Kathmandu", ["yen"]),
        q(300, "The strait that connects the Atlantic Ocean to the Pacific Ocean around the tip of South America.", "Strait of Magellan", ["magellan strait"]),
        q(300, "The capital city of Senegal, situated on the Cap-Vert peninsula on the Atlantic coast.", "Dakar", ["ville de dakar"]),
        q(300, "The body of water separating Great Britain from the European mainland, linking the North Sea and Atlantic.", "English Channel", ["la manche"]),
        q(300, "The capital city of Serbia, located at the confluence of the Sava and Danube rivers.", "Belgrade", ["beograd"]),
        q(300, "The high-altitude plateau in Central Asia often referred to as the 'Roof of the World'.", "Pamir Mountains", ["pamir plateau", "tibetan plateau"]),
        q(300, "The capital city of Nigeria, which replaced Lagos as the official capital in 1991.", "Abuja", ["federal capital territory"]),
        q(300, "The largest lake completely within Canada and the eighth-largest in the world, in the Northwest Territories.", "Great Bear Lake", ["great bear"]),
        q(300, "The capital city of Uzbekistan, the most populous city in Central Asia.", "Tashkent", ["toshkent"]),
        q(300, "The coral sea located off the northeastern coast of Australia, site of a famous 1942 naval battle.", "Coral Sea", ["mer de corail"]),
        q(300, "The capital city of Bolivia that serves as the constitutional seat, while La Paz is the seat of government.", "Sucre", ["charcas"])
    ]

    g_400 = [
        q(400, "The only doubly landlocked country in Europe, surrounded entirely by Switzerland and Austria.", "Liechtenstein", ["principality of liechtenstein"]),
        q(400, "The second doubly landlocked country in the world, located in Central Asia.", "Uzbekistan", ["republic of uzbekistan"]),
        q(400, "The narrow strip of land in northeastern Afghanistan extending to China, separating Tajikistan from Pakistan.", "Wakhan Corridor", ["wakhan"]),
        q(400, "The capital city of Bhutan, situated in the Himalayas with no traffic lights.", "Thimphu", ["thimpu"]),
        q(400, "The island shared by three sovereign countries: Indonesia, Malaysia, and Brunei.", "Borneo", ["kalimantan"]),
        q(400, "The capital city of Mongolia, the coldest national capital city in the world by average temperature.", "Ulaanbaatar", ["ulan bator"]),
        q(400, "The endorheic lake on the border between Kazakhstan and Uzbekistan that has lost over 90% of its volume since 1960.", "Aral Sea", ["lake aral"]),
        q(400, "The capital city of Kazakhstan, known as Astana, briefly renamed Nur-Sultan from 2019 to 2022.", "Astana", ["nur-sultan"]),
        q(400, "The deepest gorge in the world, located along the Brahmaputra River in Tibet, deeper than the Grand Canyon.", "Yarlung Tsangpo Grand Canyon", ["yarlung tsangpo"]),
        q(400, "The capital city of Suriname, situated on the banks of the Suriname River.", "Paramaribo", ["par'bo"]),
        q(400, "The geographic strait between Siberia and Alaska that connects the Arctic Ocean with the Bering Sea.", "Bering Strait", ["bering"]),
        q(400, "The capital city of Madagascar, built across twelve sacred hills.", "Antananarivo", ["tana"]),
        q(400, "The archipelago in the Arctic Ocean belonging to Norway whose largest settlement is Longyearbyen.", "Svalbard", ["spitsbergen"]),
        q(400, "The capital city of Namibia, situated in the Khomas Highland plateau area.", "Windhoek", ["windhuk"]),
        q(400, "The volcanic island in the South Atlantic that is the most remote inhabited archipelago in the world.", "Tristan da Cunha", ["tristan"]),
        q(400, "The capital city of Azerbaijan, located on the Absheron Peninsula on the Caspian Sea, 28 meters below sea level.", "Baku", ["baki"]),
        q(400, "The vast wetland ecosystem in southwestern Brazil that is the world's largest tropical wetland area.", "Pantanal", ["the pantanal"]),
        q(400, "The capital city of Malta, built on a peninsula between two natural harbors.", "Valletta", ["il-belt valletta"]),
        q(400, "The sovereign enclave country surrounded entirely by the Italian region of Emilia-Romagna and Marche.", "San Marino", ["republic of san marino"]),
        q(400, "The capital city of Georgia, situated on the banks of the Kura River.", "Tbilisi", ["tiflis"]),
        q(400, "The point on Earth farthest from any ocean, located in northwestern China near the Kazakhstan border.", "Eurasian pole of inaccessibility", ["continental pole of inaccessibility"]),
        q(400, "The capital city of Papua New Guinea, situated on the Gulf of Papua.", "Port Moresby", ["pot mosbi"]),
        q(400, "The strait between Iran and Oman through which approximately 20% of global petroleum passes.", "Strait of Hormuz", ["hormuz"]),
        q(400, "The capital city of Armenia, one of the world's oldest continuously inhabited cities, founded in 782 BC.", "Yerevan", ["erebuni"]),
        q(400, "The African lake shared by Chad, Cameroon, Niger, and Nigeria that shrank by 95% from 1963 to 1998.", "Lake Chad", ["lac tchad"]),
        q(400, "The capital city of Laos, situated on the bend of the Mekong River near the border with Thailand.", "Vientiane", ["viangchan"]),
        q(400, "The second-highest mountain peak on Earth, located in the Karakoram range on the China-Pakistan border.", "K2", ["mount godwin-austen", "qogir"]),
        q(400, "The capital city of Mauritania, located on the Atlantic coast of the Sahara Desert.", "Nouakchott", ["nawaksyut"]),
        q(400, "The mountain range along the border between France and Spain, home to the Basque and Catalan cultures.", "Pyrenees", ["pyrenees mountains"]),
        q(400, "The capital city of Eritrea, situated at an altitude of over 2,300 meters, famed for modernist Italian architecture.", "Asmara", ["asmera"]),
        q(400, "The world's highest navigable lake for large commercial vessels, situated in the Andes between Peru and Bolivia.", "Lake Titicaca", ["titicaca"]),
        q(400, "The capital city of Sierra Leone, situated on the mountainous peninsula on the Atlantic Ocean.", "Freetown", ["free town"]),
        q(400, "The desert in southern Israel that covers more than half the country's total land area.", "Negev Desert", ["negev"]),
        q(400, "The capital city of Moldova, located on the Bic River.", "Chisinau", ["kishinev"]),
        q(400, "The river that flows through Baghdad, joining the Euphrates to form the Shatt al-Arab.", "Tigris River", ["tigris", "dijla"]),
        q(400, "The capital city of Turkmenistan, known for its dense collection of white marble buildings.", "Ashgabat", ["askabat"]),
        q(400, "The sea between the east coast of Great Britain and the European mainland (Norway, Denmark, Germany, Netherlands).", "North Sea", ["mer du nord"]),
        q(400, "The capital city of Guyana, situated on the Atlantic coast at the mouth of the Demerara River.", "Georgetown", ["george town"]),
        q(400, "The active volcano located on the French Caribbean island of Martinique whose 1902 eruption destroyed Saint-Pierre.", "Mount Pelee", ["montagne pelee"]),
        q(400, "The capital city of Tajikistan, whose name means 'Monday' in Tajik because it grew from a Monday market village.", "Dushanbe", ["dyushambe"])
    ]

    g_500 = [
        q(500, "The oceanic point of inaccessibility, located in the South Pacific Ocean 2,688 km from the nearest land, named after Jules Verne's captain.", "Point Nemo", ["pole of inaccessibility"]),
        q(500, "The Spanish exclave city located on the north coast of Africa sharing a land border with Morocco, along with Melilla.", "Ceuta", ["ceuta and melilla"]),
        q(500, "The disputed region between Egypt and Sudan that is one of the few unclaimed habitable land areas on Earth (terra nullius).", "Bir Tawil", ["bi'r tawil"]),
        q(500, "The capital of the Federated States of Micronesia, located on the island of Pohnpei.", "Palikir", ["palikir pohnpei"]),
        q(500, "The uninhabited Norwegian volcanic island in the South Atlantic that is the most remote island on Earth.", "Bouvet Island", ["bouvetoya"]),
        q(500, "The capital city of Palau, which replaced Koror as the seat of government in 2006.", "Ngerulmud", ["melekeok"]),
        q(500, "The second-largest island in the world, located north of Australia, divided between Indonesia and Papua New Guinea.", "New Guinea", ["papua"]),
        q(500, "The capital city of Tuvalu, located on an atoll in the Polynesian subregion of Oceania.", "Funafuti", ["vaiaku"]),
        q(500, "The international border crossing point where the borders of Botswana, Namibia, Zambia, and Zimbabwe meet within a few hundred meters.", "Kazungula", ["quadripoint"]),
        q(500, "The capital city of Nauru; while Nauru has no official capital, this district contains the parliament and government offices.", "Yaren", ["yaren district"]),
        q(500, "The highest mountain in the British Isles, located at the western end of the Grampian Mountains in Scotland.", "Ben Nevis", ["the ben"]),
        q(500, "The capital city of Kiribati, located on the atoll of Tarawa.", "South Tarawa", ["tarawa", "teinainano"]),
        q(500, "The Russian exclave situated on the Baltic Sea between Poland and Lithuania, home to the Russian Baltic Fleet.", "Kaliningrad", ["konigsberg"]),
        q(500, "The capital of Comoros, situated on the island of Grande Comore.", "Moroni", ["moroni comoros"]),
        q(500, "The mountain that forms the highest peak in the Western and Southern Hemispheres, situated in Mendoza, Argentina.", "Aconcagua", ["cerro aconcagua"]),
        q(500, "The capital city of Vanuatu, situated on the island of Efate.", "Port Vila", ["port-vila"]),
        q(500, "The deep lake in Oregon formed around 7,700 years ago by the collapse of the volcano Mount Mazama.", "Crater Lake", ["crater lake oregon"]),
        q(500, "The capital city of Sao Tome and Principe, situated on Ana Chaves Bay.", "Sao Tome", ["são tomé"]),
        q(500, "The salt pan in northern Botswana that is one of the largest salt flats in the world, remnants of ancient Lake Makgadikgadi.", "Makgadikgadi Pan", ["makgadikgadi"]),
        q(500, "The capital city of the Marshall Islands, built on a coral atoll of 64 islands.", "Majuro", ["majuro atoll"]),
        q(500, "The deepest submarine canyon in the world, located off the coast of Western Australia in the Indian Ocean.", "Perth Canyon", ["perth submarine canyon"]),
        q(500, "The capital city of Cape Verde, located on the southern coast of Santiago island.", "Praia", ["porto da praia"]),
        q(500, "The highest mountain peak in the Alps and Western Europe, rising 4,809 meters on the French-Italian border.", "Mont Blanc", ["monte bianco"]),
        q(500, "The capital city of Saint Kitts and Nevis, located on the island of Saint Kitts.", "Basseterre", ["basseterre st kitts"]),
        q(500, "The active stratovolcano on Ross Island, Antarctica, that is the southernmost active volcano on Earth, possessing a persistent lava lake.", "Mount Erebus", ["erebus"]),
        q(500, "The capital city of Dominica, situated on the southwest coast of the Caribbean island nation.", "Roseau", ["roseau dominica"]),
        q(500, "The narrow body of water between Greenland and Ellesmere Island in Canada, forming the northern part of Nares Strait.", "Robeson Channel", ["nares strait"]),
        q(500, "The capital city of Seychelles, situated on the northeastern side of Mahe island.", "Victoria", ["port victoria"]),
        q(500, "The deepest cave in the world, descending over 2,212 meters in the Arabika Massif in Abkhazia, Georgia.", "Veryovkina Cave", ["krubera cave", "veryovkina"]),
        q(500, "The capital city of Saint Vincent and the Grenadines, the nation's main commercial center and port.", "Kingstown", ["kingstown st vincent"]),
        q(500, "The geological depression in northeastern Ethiopia where three tectonic plates are pulling apart, home to Erta Ale.", "Afar Depression", ["afar triangle", "danakil depression"]),
        q(500, "The capital city of Saint Lucia, named in honor of the French statesman Charles Eugene Gabriel de La Croix.", "Castries", ["castries st lucia"]),
        q(500, "The lake in Cameroon where a limnic eruption in 1986 released a massive cloud of carbon dioxide, suffocating 1,746 people.", "Lake Nyos", ["nyos"]),
        q(500, "The capital city of Antigua and Barbuda, situated on the island of Antigua.", "St. John's", ["saint johns"]),
        q(500, "The large peninsula in eastern Siberia extending into the Pacific Ocean between the Sea of Okhotsk and Bering Sea, rich in volcanoes.", "Kamchatka Peninsula", ["kamchatka"]),
        q(500, "The capital city of Grenada, situated in an amphitheater-shaped extinct volcanic crater surrounded by hills.", "St. George's", ["saint georges"]),
        q(500, "The desert in southern Africa that features the highest sand dunes in the world at Sossusvlei.", "Namib Desert", ["namib"]),
        q(500, "The capital city of Tonga, situated on the north coast of the island of Tongatapu.", "Nuku'alofa", ["nukualofa"]),
        q(500, "The highest mountain in Africa outside the Kilimanjaro massif, located in Kenya near the equator.", "Mount Kenya", ["kirinyaga"]),
        q(500, "The capital city of Equatorial Guinea, located on the island of Bioko rather than on the African mainland.", "Malabo", ["santa isabel"])
    ]

    return g_100 + g_200 + g_300 + g_400 + g_500

if __name__ == "__main__":
    data = get_geography_data()
    print(f"Geography generated: {len(data)} clues")
