# -*- coding: utf-8 -*-
"""History Category - 200 Real Clues"""

def get_history_data():
    def q(val, clue, ans, acc=None, src="Wikipedia - History"):
        return {"value": val, "clue": clue, "answer": ans, "accepted": acc or [], "source": src}

    h_100 = [
        q(100, "The first President of the United States and Commander-in-Chief of the Continental Army.", "George Washington", ["washington"]),
        q(100, "The ancient wonder of the world built for Pharaoh Khufu around 2560 BC at Giza.", "Great Pyramid of Giza", ["great pyramid", "pyramid of giza"]),
        q(100, "In 1969, this Apollo 11 astronaut became the first human to step onto the surface of the Moon.", "Neil Armstrong", ["armstrong"]),
        q(100, "The year Christopher Columbus completed his first transatlantic voyage from Spain to the Caribbean.", "1492", ["year 1492"]),
        q(100, "The concrete barrier dividing Berlin from 1961 until its historic opening in November 1989.", "The Berlin Wall", ["berlin wall"]),
        q(100, "The English Tudor monarch famous for having six wives and breaking with the Roman Catholic Church.", "Henry VIII", ["king henry viii", "henry the eighth"]),
        q(100, "The 16th President of the United States who issued the Emancipation Proclamation during the Civil War.", "Abraham Lincoln", ["lincoln", "honest abe"]),
        q(100, "The ancient empire whose capital was Rome, which conquered the Mediterranean basin.", "Roman Empire", ["ancient rome"]),
        q(100, "The British passenger liner that struck an iceberg and sank on its maiden voyage in April 1912.", "Titanic", ["rms titanic"]),
        q(100, "The French military leader who rose during the French Revolution and crowned himself Emperor in 1804.", "Napoleon Bonaparte", ["napoleon"]),
        q(100, "The document signed on July 4, 1776, announcing the American colonies' independence from Great Britain.", "Declaration of Independence", ["us declaration of independence"]),
        q(100, "The ancient queen of Egypt famed for her relationships with Julius Caesar and Mark Antony.", "Cleopatra", ["cleopatra vii"]),
        q(100, "The major global conflict that lasted from 1939 to 1945 involving the Axis and Allied powers.", "World War II", ["ww2", "second world war"]),
        q(100, "The civil rights leader who delivered the historic 'I Have a Dream' speech at the March on Washington in 1963.", "Martin Luther King Jr.", ["mlk", "martin luther king"]),
        q(100, "The ancient city-state that created democracy and is home to the Acropolis and Parthenon.", "Athens", ["ancient athens"]),
        q(100, "The Japanese naval surprise attack on December 7, 1941, that drew the United States into WWII.", "Pearl Harbor", ["attack on pearl harbor"]),
        q(100, "The South African anti-apartheid leader who served 27 years in prison before becoming president in 1994.", "Nelson Mandela", ["mandela", "madiba"]),
        q(100, "The massive fortified wall built across the northern borders of ancient Chinese empires to ward off invaders.", "Great Wall of China", ["the great wall"]),
        q(100, "The queen who ruled the British Empire from 1837 to 1901, defining an era named after her.", "Queen Victoria", ["victoria"]),
        q(100, "The Indian independence leader who practiced non-violent civil disobedience through the Salt March.", "Mahatma Gandhi", ["gandhi", "mohandas gandhi"]),
        q(100, "The Russian royal dynasty that ruled for over 300 years until the abdication of Nicholas II in 1917.", "Romanov", ["house of romanov"]),
        q(100, "The ancient civilization between the Tigris and Euphrates rivers, often called the 'Cradle of Civilization'.", "Mesopotamia", ["mesopotamian"]),
        q(100, "The code name for the secret American research project during WWII that developed the first atomic bombs.", "Manhattan Project", ["the manhattan project"]),
        q(100, "The ancient Roman gladiator who led a major slave uprising against the Roman Republic from 73 to 71 BC.", "Spartacus", ["spartacus revolt"]),
        q(100, "The treaty signed in 1919 in the Hall of Mirrors that formally ended World War I.", "Treaty of Versailles", ["versailles"]),
        q(100, "The French peasant teenager who led French armies during the Hundred Years' War and was burned at the stake in 1431.", "Joan of Arc", ["jeanne d'arc"]),
        q(100, "The 1944 Allied amphibious invasion of Normandy on June 6, 1944, commonly known by this letter.", "D-Day", ["d day", "operation overload"]),
        q(100, "The first woman to fly solo nonstop across the Atlantic Ocean, who vanished over the Pacific in 1937.", "Amelia Earhart", ["earhart"]),
        q(100, "The deadly pandemic caused by the bacterium Yersinia pestis that devastated Europe in the mid-14th century.", "Black Death", ["bubonic plague", "the plague"]),
        q(100, "The Italian polymath who painted the Mona Lisa and The Last Supper during the Renaissance.", "Leonardo da Vinci", ["da vinci", "leonardo"]),
        q(100, "The political confrontation between the US and Soviet Union from October 16-29, 1962, over nuclear missiles in the Caribbean.", "Cuban Missile Crisis", ["october crisis"]),
        q(100, "The German monk whose Ninety-five Theses in 1517 launched the Protestant Reformation.", "Martin Luther", ["luther"]),
        q(100, "The Soviet cosmonaut who became the first human in space on April 12, 1961, aboard Vostok 1.", "Yuri Gagarin", ["gagarin"]),
        q(100, "The Mesoamerican civilization that built monumental step pyramids like El Castillo at Chichen Itza.", "Maya", ["mayan civilization", "mayans"]),
        q(100, "The 1773 protest in Boston Harbor where American colonists dumped 342 chests of British East India tea into the sea.", "Boston Tea Party", ["tea party"]),
        q(100, "The Mongol founder and Khagan who united nomadic tribes and founded the largest contiguous empire in history.", "Genghis Khan", ["temujin", "chinggis khan"]),
        q(100, "The period of geopolitical tension between the United States and the Soviet Union following World War II.", "The Cold War", ["cold war"]),
        q(100, "The queen of France executed by guillotine in 1793, famously but apocryphally associated with 'Let them eat cake'.", "Marie Antoinette", ["antoinette"]),
        q(100, "The 1969 gathering in New York City where LGBT patrons of a Greenwich Village tavern protested police harassment.", "Stonewall riots", ["stonewall rebellion"]),
        q(100, "The ancient Greek king of Macedon who created one of the largest empires in the ancient world by age thirty.", "Alexander the Great", ["alexander iii"])
    ]

    h_200 = [
        q(200, "Signed on June 15, 1215 at Runnymede, this English charter limited royal power under King John.", "Magna Carta", ["the great charter"]),
        q(200, "The ancient Roman dictator assassinated on the Ides of March in 44 BC by a conspiracy of Roman senators.", "Julius Caesar", ["caesar"]),
        q(200, "The 1803 territorial purchase from Napoleonic France that doubled the geographical size of the United States.", "Louisiana Purchase", ["louisiana territory"]),
        q(200, "The famous naval engagement in 1805 where British Admiral Lord Nelson defeated the combined French and Spanish fleets.", "Battle of Trafalgar", ["trafalgar"]),
        q(200, "The last active tsar of Russia whose entire family was executed by Bolshevik troops in Yekaterinburg in 1918.", "Nicholas II", ["tsar nicholas ii"]),
        q(200, "The ancient Mesopotamian king of Babylon known for his early written legal code based on 'an eye for an eye'.", "Hammurabi", ["code of hammurabi"]),
        q(200, "The pivotal 1863 American Civil War battle in Pennsylvania regarded as the military turning point of the war.", "Battle of Gettysburg", ["gettysburg"]),
        q(200, "The British Prime Minister who rallied his nation with defiant speeches throughout the Battle of Britain in 1940.", "Winston Churchill", ["churchill"]),
        q(200, "The 1815 battle in modern Belgium where the Duke of Wellington and Gebhard von Blucher defeated Napoleon.", "Battle of Waterloo", ["waterloo"]),
        q(200, "The first democratically elected President of South Africa after the dismantling of apartheid in 1994.", "Nelson Mandela", ["mandela"]),
        q(200, "The young Egyptian pharaoh whose nearly intact tomb in the Valley of the Kings was discovered by Howard Carter in 1922.", "Tutankhamun", ["king tut", "tutankhamen"]),
        q(200, "The 1848 political pamphlet authored by Karl Marx and Friedrich Engels outlining socialist theory.", "The Communist Manifesto", ["communist manifesto"]),
        q(200, "The Ottoman sultan known as 'The Magnificent' under whose reign the empire reached its cultural and military zenith in the 16th century.", "Suleiman the Magnificent", ["suleiman i"]),
        q(200, "The 1930 protest march led by Mahatma Gandhi across Gujarat to produce salt in defiance of British salt monopoly laws.", "Salt March", ["dandi march", "salt satyagraha"]),
        q(200, "The decisive 1066 battle where William the Conqueror of Normandy defeated King Harold Godwinson of England.", "Battle of Hastings", ["hastings 1066"]),
        q(200, "The long-distance overland network of Eurasian trade routes linking China and the Mediterranean from the Han dynasty.", "The Silk Road", ["silk route"]),
        q(200, "The 1914 assassination of this Archduke of Austria in Sarajevo by Gavrilo Princip ignited World War I.", "Franz Ferdinand", ["archduke franz ferdinand"]),
        q(200, "The Byzantine capital formerly known as Byzantium, transformed by Constantine and conquered by Ottomans in 1453.", "Constantinople", ["istanbul"]),
        q(200, "The Portuguese explorer who led the first European naval expedition around the Cape of Good Hope to India in 1498.", "Vasco da Gama", ["da gama"]),
        q(200, "The Spanish conquistador who led the expedition that caused the fall of the Aztec Empire between 1519 and 1521.", "Hernan Cortes", ["cortes", "cortez"]),
        q(200, "The period of political purges and mass executions orchestrated by Maximilien Robespierre during the French Revolution.", "Reign of Terror", ["the terror"]),
        q(200, "The primary author of the United States Declaration of Independence who became the 3rd US President.", "Thomas Jefferson", ["jefferson"]),
        q(200, "The ancient library in Egypt, established under the Ptolemaic dynasty, that was one of the largest libraries in the ancient world.", "Library of Alexandria", ["alexandria library"]),
        q(200, "The 1868 political event that restored practical imperial rule to Japan under Emperor Meiji, ending the Tokugawa shogunate.", "Meiji Restoration", ["meiji ishin"]),
        q(200, "The French castle stormed by Parisian revolutionaries on July 14, 1789, marking the start of the French Revolution.", "The Bastille", ["bastille"]),
        q(200, "The legendary English king associated with the Knights of the Round Table and Camelot.", "King Arthur", ["arthur pendragon"]),
        q(200, "The 1898 war between the US and Spain that resulted in American control over Puerto Rico, Guam, and the Philippines.", "Spanish-American War", ["war of 1898"]),
        q(200, "The Roman emperor who legalized Christianity throughout the Roman Empire with the Edict of Milan in 313 AD.", "Constantine the Great", ["constantine i"]),
        q(200, "The German blimp that caught fire and was destroyed while attempting to dock at Lakehurst, New Jersey, in 1937.", "The Hindenburg", ["lz 129 hindenburg"]),
        q(200, "The 1863 speech delivered by Abraham Lincoln dedicating a national cemetery at a Pennsylvania battlefield.", "Gettysburg Address", ["four score and seven years ago"]),
        q(200, "The Scottish queen beheaded at Fotheringhay Castle in 1587 on the orders of her cousin, Queen Elizabeth I.", "Mary, Queen of Scots", ["mary stuart"]),
        q(200, "The secret anti-foreign, anti-colonial uprising that occurred in northern China between 1899 and 1901.", "Boxer Rebellion", ["yihetuan movement"]),
        q(200, "The Japanese cities targeted by American atomic bombs on August 6 and August 9, 1945.", "Hiroshima and Nagasaki", ["hiroshima", "nagasaki"]),
        q(200, "The Venetian merchant explorer who traveled along the Silk Road to China and served in Kublai Khan's court.", "Marco Polo", ["polo"]),
        q(200, "The historic 1781 Virginia siege where General Cornwallis surrendered British forces to George Washington, effectively ending the Revolutionary War.", "Siege of Yorktown", ["battle of yorktown"]),
        q(200, "The 1974 political scandal involving a break-in at the DNC headquarters that forced President Richard Nixon to resign.", "Watergate", ["watergate scandal"]),
        q(200, "The West African ruler of the Mali Empire whose legendary 1324 pilgrimage to Mecca spent so much gold it depressed Mediterranean gold prices.", "Mansa Musa", ["musa i of mali"]),
        q(200, "The 1917 political revolutions in Russia that dismantled the Tsarist autocracy and led to the rise of the Soviet Union.", "Russian Revolution", ["october revolution", "bolshevik revolution"]),
        q(200, "The South American general known as 'El Libertador' who led the independence of Venezuela, Colombia, Ecuador, Peru, and Bolivia.", "Simon Bolivar", ["bolivar"]),
        q(200, "The 1804 slave revolt on Saint-Domingue that led to the establishment of the world's first independent Black-led republic.", "Haitian Revolution", ["haiti revolution"])
    ]

    h_300 = [
        q(300, "The series of military conflicts fought from 1337 to 1453 between England and France over the French throne.", "Hundred Years' War", ["100 years war"]),
        q(300, "The 1648 series of peace treaties that ended the Thirty Years' War and established modern concepts of sovereign nation-states.", "Peace of Westphalia", ["treaty of westphalia"]),
        q(300, "The battle in 732 AD where Frankish leader Charles Martel halted the northward Umayyad advance into Western Europe.", "Battle of Tours", ["battle of poitiers"]),
        q(300, "The ancient Persian king who issued a clay cylinder in 539 BC declared by many as the first declaration of human rights.", "Cyrus the Great", ["cyrus ii"]),
        q(300, "The decisive naval battle of 31 BC where Octavian defeated the combined fleets of Mark Antony and Cleopatra.", "Battle of Actium", ["actium"]),
        q(300, "The Italian city-state ruled by the wealthy Medici family that served as the primary cradle of the Renaissance.", "Florence", ["firenze"]),
        q(300, "The 1936 to 1939 civil war that served as a testing ground for WWII weapons, resulting in the dictatorship of Francisco Franco.", "Spanish Civil War", ["guerra civil espanola"]),
        q(300, "The English philosopher whose 1651 treatise 'Leviathan' argued for a strong social contract to escape a life that is 'nasty, brutish, and short'.", "Thomas Hobbes", ["hobbes"]),
        q(300, "The ancient battle in 490 BC where outnumbered Athenians defeated invading Persian forces, inspiring a distance run.", "Battle of Marathon", ["marathon"]),
        q(300, "The French fortress city that withstood a grueling 302-day German siege in 1916 with over 700,000 casualties.", "Verdun", ["battle of verdun"]),
        q(300, "The Portuguese prince known as 'The Navigator' who launched the Age of Discovery and early maritime exploration in the 15th century.", "Prince Henry the Navigator", ["henrique the navigator"]),
        q(300, "The 1853 to 1856 conflict pitting Russia against an alliance of Britain, France, and the Ottoman Empire on the Black Sea peninsula.", "Crimean War", ["crimea war"]),
        q(300, "The first written constitution of the United States, ratified in 1781 and later superseded by the 1787 Constitution.", "Articles of Confederation", ["articles of confederation and perpetual union"]),
        q(300, "The Roman general and consul who instituted military reforms in 107 BC that professionalized the Roman legions.", "Gaius Marius", ["marius"]),
        q(300, "The 1989 Romanian dictator overthrown and executed alongside his wife Elena on Christmas Day during the anti-communist revolution.", "Nicolae Ceausescu", ["ceausescu"]),
        q(300, "The 1571 naval clash in the Gulf of Patras where the Holy League fleet decisively defeated the Ottoman navy.", "Battle of Lepanto", ["lepanto"]),
        q(300, "The ancient Indian emperor of the Maurya dynasty who converted to Buddhism and renounced violence after the bloody Kalinga War.", "Ashoka", ["ashoka the great", "asoka"]),
        q(300, "The Prussian statesman known as the 'Iron Chancellor' who masterminded the unification of Germany in 1871.", "Otto von Bismarck", ["bismarck"]),
        q(300, "The 1942 naval battle near Midway Atoll where the US Navy sank four Japanese aircraft carriers, turning the Pacific War.", "Battle of Midway", ["midway"]),
        q(300, "The 1598 edict signed by King Henry IV of France granting French Calvinist Protestants (Huguenots) substantial religious rights.", "Edict of Nantes", ["nantes"]),
        q(300, "The 1756 to 1763 worldwide conflict known in the American theater as the French and Indian War.", "Seven Years' War", ["seven years war"]),
        q(300, "The battle in 1879 where a Zulu army equipped with traditional assegais annihilated a British military force.", "Battle of Isandlwana", ["isandlwana"]),
        q(300, "The Russian empress who ruled from 1762 to 1796, expanding the empire through partition of Poland and annexation of Crimea.", "Catherine the Great", ["catherine ii"]),
        q(300, "The 1943 tank battle in the Soviet Union that was the largest armored clash in military history.", "Battle of Kursk", ["kursk"]),
        q(300, "The Byzantine emperor who codified Roman law into the Corpus Juris Civilis and built the Hagia Sophia.", "Justinian I", ["justinian the great"]),
        q(300, "The 1836 battle in San Antonio where Mexican troops under General Santa Anna overran Texan defenders including Davy Crockett.", "The Alamo", ["battle of the alamo"]),
        q(300, "The ancient Greek conflict fought between the Delian League led by Athens and the Peloponnesian League led by Sparta.", "Peloponnesian War", ["peloponnesian wars"]),
        q(300, "The Polish-born astronomer whose 1543 book De revolutionibus orbium coelestium proposed the heliocentric solar system.", "Nicolaus Copernicus", ["copernicus"]),
        q(300, "The 1968 military offensive launched by North Vietnamese and Viet Cong forces on the Lunar New Year across South Vietnam.", "Tet Offensive", ["tet"]),
        q(300, "The ancient trade city in North Africa founded by Phoenician settlers that fought three Punic Wars against Rome.", "Carthage", ["carthaginian"]),
        q(300, "The 1916 naval battle between the British Royal Navy's Grand Fleet and the Imperial German Navy's High Seas Fleet in the North Sea.", "Battle of Jutland", ["skagerrakschlacht"]),
        q(300, "The 17th-century philosopher and jurist Hugo Grotius is widely regarded as the founding father of this legal discipline.", "International law", ["law of nations"]),
        q(300, "The 1945 conference in Crimea where Churchill, Roosevelt, and Stalin met to plan the post-WWII reorganization of Europe.", "Yalta Conference", ["yalta"]),
        q(300, "The Aztec ruler who met Hernan Cortes when the Spanish conquistadors entered Tenochtitlan in November 1519.", "Moctezuma II", ["montezuma", "motecuhzoma"]),
        q(300, "The 1956 nationalization of an international shipping canal by Egyptian President Gamal Abdel Nasser triggered this invasion crisis.", "Suez Crisis", ["second arab-israeli war"]),
        q(300, "The 1381 rebellion in England led by Wat Tyler in response to high poll taxes and serfdom.", "Peasants' Revolt", ["wat tyler's rebellion"]),
        q(300, "The 1870-1871 conflict that resulted in the defeat of Napoleon III, the fall of the Second French Empire, and German unification.", "Franco-Prussian War", ["franco german war"]),
        q(300, "The Carthaginian general who led war elephants and an army across the Alps into Italy during the Second Punic War.", "Hannibal Barca", ["hannibal"]),
        q(300, "The 1923 failed coup d'etat launched by Adolf Hitler and the Nazi Party in a Bavarian beer hall in Munich.", "Beer Hall Putsch", ["munich putsch"]),
        q(300, "The 1948 airlift operation by Western Allies that flew supplies into West Berlin during a Soviet road and rail blockade.", "Berlin Airlift", ["operation vittles"])
    ]

    h_400 = [
        q(400, "The 1683 Ottoman siege of this Habsburg capital city that was broken by a massive Polish cavalry charge led by King John III Sobieski.", "Siege of Vienna", ["battle of vienna"]),
        q(400, "The 1857 Indian rebellion against British East India Company rule that began with sepoy mutineers in Meerut.", "Indian Mutiny", ["sepoy mutiny", "first war of indian independence"]),
        q(400, "The peace treaty of 1783 signed in Paris that officially recognized American independence from Great Britain.", "Treaty of Paris", ["treaty of paris 1783"]),
        q(400, "The 1071 battle in Anatolia where the Seljuk Turks under Alp Arslan decisively defeated the Byzantine Empire and captured Emperor Romanos IV.", "Battle of Manzikert", ["manzikert"]),
        q(400, "The 1688 revolution in England that deposed Catholic King James II and replaced him with William III and Mary II.", "Glorious Revolution", ["bloodless revolution"]),
        q(400, "The ancient battle in 216 BC where Hannibal used a double-envelopment tactic to destroy eight Roman legions, killing over 50,000 Romans.", "Battle of Cannae", ["cannae"]),
        q(400, "The 1860 military expedition of one thousand volunteers led by Giuseppe Garibaldi that overthrew the Bourbon Kingdom of the Two Sicilies.", "Expedition of the Thousand", ["spedizione dei mille"]),
        q(400, "The 1526 battle in northern India where Babur defeated Ibrahim Lodi, marking the foundation of the Mughal Empire.", "First Battle of Panipat", ["battle of panipat"]),
        q(400, "The 1794 coup that arrested and guillotined Maximilien Robespierre, ending the Reign of Terror in revolutionary France.", "Thermidorian Reaction", ["9 thermidor"]),
        q(400, "The 1905 naval battle in the Korea Strait where the Imperial Japanese Navy obliterated the Russian Baltic Fleet, shocking the Western world.", "Battle of Tsushima", ["tsushima"]),
        q(400, "The 1389 battle fought on the 'Field of Blackbirds' where Ottoman Sultan Murad I fought a Serbian-led Christian coalition.", "Battle of Kosovo", ["kosovo polje"]),
        q(400, "The 1839 to 1842 war fought between the Qing Dynasty of China and Great Britain over the British illicit opium trade, ending with Treaty of Nanking.", "First Opium War", ["opium war"]),
        q(400, "The Italian humanist poet of the 14th century whose rediscovery of Cicero's letters is credited with initiating the Renaissance.", "Petrarch", ["francesco petrarca"]),
        q(400, "The 1937 Japanese massacre and mass atrocities committed against Chinese civilians and disarmed combatants in the capital of Nanjing.", "Nanjing Massacre", ["rape of nanking"]),
        q(400, "The French cardinal and chief minister to King Louis XIII who centralized royal power and entered the Thirty Years' War.", "Cardinal Richelieu", ["richelieu", "armand jean du plessis"]),
        q(400, "The 1916 revolt against the Ottoman Empire in the Middle East supported by the British officer T.E. Lawrence ('Lawrence of Arabia').", "Arab Revolt", ["great arab revolt"]),
        q(400, "The 1241 battle where the Mongol army under Subutai and Batu Khan annihilated the combined chivalric forces of Hungary.", "Battle of Mohi", ["battle of the sajo river"]),
        q(400, "The 1864 Geneva Convention was established following the horrific aftermath of this 1859 battle witnessed by Henry Dunant.", "Battle of Solferino", ["solferino"]),
        q(400, "The English parliament convened by King Charles I in November 1640 that sat through the English Civil War until Pride's Purge.", "The Long Parliament", ["long parliament"]),
        q(400, "The 1928 international treaty renouncing war as an instrument of national policy, signed by 62 nations in Paris.", "Kellogg-Briand Pact", ["pact of paris"]),
        q(400, "The ancient Persian king who invaded Greece in 480 BC, ordered the Hellespont whipped, and fought King Leonidas at Thermopylae.", "Xerxes I", ["xerxes the great"]),
        q(400, "The 1848 series of republican revolts that swept across Europe (France, Germany, Austria, Italy, Hungary), known as this 'Spring'.", "Spring of Nations", ["revolutions of 1848", "people's spring"]),
        q(400, "The 1494 treaty between Spain and Portugal that divided the newly discovered non-European lands along a meridian 370 leagues west of Cape Verde.", "Treaty of Tordesillas", ["tordesillas"]),
        q(400, "The ancient battle in 331 BC where Alexander the Great decisively defeated Darius III of Persia, leading to the collapse of the Achaemenid Empire.", "Battle of Gaugamela", ["battle of arbela"]),
        q(400, "The secret police organization established in 1917 by Felix Dzerzhinsky under Lenin to eliminate political counter-revolutionaries.", "Cheka", ["vecheka"]),
        q(400, "The 16th-century Spanish Dominican friar and historian who advocated for the rights of indigenous Americans in his 'A Short Account of the Destruction of the Indies'.", "Bartolome de las Casas", ["las casas"]),
        q(400, "The 1805 battle known as the 'Battle of the Three Emperors' where Napoleon decisively defeated Tsar Alexander I and Emperor Francis II.", "Battle of Austerlitz", ["austerlitz"]),
        q(400, "The 1572 targeted assassination and mob violence against French Huguenots in Paris, sanctioned by King Charles IX and Catherine de' Medici.", "St. Bartholomew's Day massacre", ["st bartholomew's massacre"]),
        q(400, "The 1938 crisis where Britain and France appeased Hitler by signing an agreement permitting the German annexation of Czechoslovakia's Sudetenland.", "Munich Agreement", ["munich pact"]),
        q(400, "The 1415 battle in northern France during the Hundred Years' War where English longbowmen under King Henry V defeated a larger French army.", "Battle of Agincourt", ["agincourt"]),
        q(400, "The late 19th-century political scandal in France involving the wrongful treason conviction of a Jewish artillery captain.", "Dreyfus Affair", ["alfred dreyfus"]),
        q(400, "The 1204 sack of this Christian Byzantine capital by Western European Crusaders during the Fourth Crusade that shattered the Byzantine Empire.", "Constantinople", ["sack of constantinople 1204"]),
        q(400, "The 1798 naval battle in Aboukir Bay where British Admiral Horatio Nelson destroyed the French fleet, trapping Napoleon in Egypt.", "Battle of the Nile", ["battle of aboukir bay"]),
        q(400, "The 1961 failed CIA-sponsored invasion of southwestern Cuba by Cuban exiles attempting to overthrow Fidel Castro's government.", "Bay of Pigs Invasion", ["playa giron"]),
        q(400, "The 1642 to 1651 conflicts between Parliamentarians ('Roundheads') and Royalists ('Cavaliers') in the British Isles.", "English Civil War", ["the english civil war"]),
        q(400, "The 1823 US foreign policy declaration warning European nations against further colonization or intervention in the Americas.", "Monroe Doctrine", ["james monroe doctrine"]),
        q(400, "The ancient Roman civil war battle in 48 BC where Julius Caesar decisively defeated Pompey the Great in Greece.", "Battle of Pharsalus", ["pharsalus"]),
        q(400, "The 1920 peace treaty signed between the victorious Entente Powers and Hungary that stripped Hungary of 71% of its pre-war territory.", "Treaty of Trianon", ["trianon"]),
        q(400, "The 1709 battle in Ukraine where Tsar Peter the Great crushed King Charles XII of Sweden, ending Sweden's era as a European great power.", "Battle of Poltava", ["poltava"]),
        q(400, "The 1979 political crisis where Iranian university students seized the American embassy in Tehran, holding 52 diplomats hostage for 444 days.", "Iran hostage crisis", ["tehran embassy crisis"])
    ]

    h_500 = [
        q(500, "The 1444 battle in eastern Bulgaria where Ottoman Sultan Murad II crushed a European Crusader coalition, killing King Wladyslaw III of Poland.", "Battle of Varna", ["varna"]),
        q(500, "The 1618 event where Bohemian Protestant nobles threw three Catholic Habsburg governors out a top-floor window of Prague Castle.", "Defenestration of Prague", ["second defenestration of prague"]),
        q(500, "The 1704 battle during the War of the Spanish Succession where the Duke of Marlborough and Prince Eugene of Savoy saved Vienna from Franco-Bavarian forces.", "Battle of Blenheim", ["blindheim"]),
        q(500, "The 1260 battle in the Galilee where the Mamluks of Egypt inflicted the first permanent battlefield defeat on the Mongol Empire.", "Battle of Ain Jalut", ["ain jalut"]),
        q(500, "The 1527 sack of Rome by mutinous unpaid troops of Holy Roman Emperor Charles V that marked the end of the High Renaissance.", "Sack of Rome", ["sack of rome 1527"]),
        q(500, "The 1813 'Battle of the Nations' near Leipzig where coalition forces inflicted a crushing defeat on Napoleon, leading to his first abdication.", "Battle of Leipzig", ["battle of the nations"]),
        q(500, "The 1346 battle during the Hundred Years' War where English longbowmen under Edward III annihilated the French chivalry.", "Battle of Crecy", ["crecy"]),
        q(500, "The 1555 treaty within the Holy Roman Empire that established the principle 'cuius regio, eius religio' ('whose realm, his religion').", "Peace of Augsburg", ["augsburg"]),
        q(500, "The 1673 to 1681 rebellion of three Chinese feudatory lords in southern China against the early Qing dynasty under the Kangxi Emperor.", "Revolt of the Three Feudatories", ["sanfan"]),
        q(500, "The 1921 naval conference in Washington that set warship tonnage ratios at 5:5:3 for the United States, Great Britain, and Japan.", "Washington Naval Conference", ["five-power treaty"]),
        q(500, "The 1402 battle near modern Ankara where Turco-Mongol conqueror Timur captured Ottoman Sultan Bayezid I, plunging the Ottomans into civil war.", "Battle of Ankara", ["battle of angora"]),
        q(500, "The 1757 battle in Bengal where British East India Company troops under Robert Clive defeated Nawab Siraj-ud-Daulah, beginning British dominion in India.", "Battle of Plassey", ["palashi"]),
        q(500, "The 1830 revolution in France known as the 'Three Glorious Days' (Les Trois Glorieuses) that overthrew Bourbon King Charles X for Louis-Philippe.", "July Revolution", ["french revolution of 1830"]),
        q(500, "The 1214 battle in northern France where King Philip II Augustus defeated a combined English-Flemish-German coalition, confirming French royal hegemony.", "Battle of Bouvines", ["bouvines"]),
        q(500, "The 1515 battle near Milan where Francis I of France defeated the feared Swiss pikemen, forcing Switzerland into perpetual neutrality.", "Battle of Marignano", ["marignano"]),
        q(500, "The 1792 cannonade in northeastern France where revolutionary French troops under Kellermann and Dumouriez turned back a Prussian-Austrian invasion.", "Battle of Valmy", ["cannonade of valmy"]),
        q(500, "The 1866 battle (also known as Koniggratz) where Helmuth von Moltke's Prussian army routed the Austrian Empire in seven weeks.", "Battle of Sadowa", ["koniggratz", "battle of sadowa"]),
        q(500, "The 1380 battle on the Snip River where Grand Prince Dmitry Donskoy of Moscow defeated Mamai's Golden Horde, an early blow against Mongol suzerainty.", "Battle of Kulikovo", ["kulikovo"]),
        q(500, "The 1782 naval engagement off Dominica where Admiral Sir George Rodney broke the French line, securing British dominance in the Caribbean.", "Battle of the Saintes", ["the saintes"]),
        q(500, "The 1545 to 1563 ecumenical council of the Catholic Church held in northern Italy that articulated the Counter-Reformation doctrine.", "Council of Trent", ["concilium tridentinum"]),
        q(500, "The 1812 battle fought 110 km west of Moscow that was the bloodiest single-day battle of the Napoleonic Wars, with over 70,000 casualties.", "Battle of Borodino", ["borodino"]),
        q(500, "The 1242 battle fought on the frozen surface of Lake Peipus where Prince Alexander Nevsky defeated the Livonian branch of the Teutonic Knights.", "Battle on the Ice", ["battle of lake peipus"]),
        q(500, "The 1707 legislative acts that merged the Kingdom of England and Kingdom of Scotland into a single sovereign Kingdom of Great Britain.", "Acts of Union 1707", ["act of union"]),
        q(500, "The 1500 discovery of Brazil by this Portuguese noble military commander en route to India.", "Pedro Alvares Cabral", ["cabral"]),
        q(500, "The 1918 treaty between the new Bolshevik government of Soviet Russia and the Central Powers that exited Russia from WWI at massive territorial cost.", "Treaty of Brest-Litovsk", ["brest litovsk"]),
        q(500, "The 1477 battle near the capital of Lorraine where Charles the Bold, Duke of Burgundy, was killed, dissolving the independent Valois-Burgundian state.", "Battle of Nancy", ["nancy"]),
        q(500, "The 1631 battle during the Thirty Years' War where Swedish King Gustavus Adolphus shattered the Catholic Imperial army under Count Tilly.", "Battle of Breitenfeld", ["first breitenfeld"]),
        q(500, "The 1920 battle outside the Polish capital dubbed the 'Miracle on the Vistula' where Polish forces under Jozef Pilsudski routed the Red Army.", "Battle of Warsaw", ["miracle on the vistula"]),
        q(500, "The 1713-1714 series of peace treaties ending the War of the Spanish Succession, recognizing Philip V as king of Spain while barring union with France.", "Treaty of Utrecht", ["peace of utrecht"]),
        q(500, "The 1205 battle where Tsar Kaloyan of Bulgaria ambushed and crushed the Fourth Crusade's Latin Empire, capturing Latin Emperor Baldwin I.", "Battle of Adrianople", ["adrianople 1205"]),
        q(500, "The 1807 treaties signed on a raft in the Neman River between Napoleon and Tsar Alexander I establishing a Franco-Russian alliance.", "Treaties of Tilsit", ["peace of tilsit"]),
        q(500, "The 1600 decisive battle in central Japan where Tokugawa Ieyasu defeated Ishida Mitsunari, leading to the 260-year Tokugawa shogunate.", "Battle of Sekigahara", ["sekigahara"]),
        q(500, "The 1763 treaty that ended the Seven Years' War, under which France ceded New France (Canada) and claims east of the Mississippi to Great Britain.", "Treaty of Paris 1763", ["peace of paris"]),
        q(500, "The 1176 battle where the Lombard League citizen militias defeated Holy Roman Emperor Frederick I Barbarossa's imperial knights.", "Battle of Legnano", ["legnano"]),
        q(500, "The 1827 naval battle in the Ionian Sea where an allied British-French-Russian fleet destroyed an Ottoman-Egyptian armada, securing Greek independence.", "Battle of Navarino", ["navarino"]),
        q(500, "The 1535 Spanish conquest and expedition led by Charles V that captured the pirate stronghold of Tunis from Hayreddin Barbarossa.", "Conquest of Tunis", ["tunis 1535"]),
        q(500, "The 1939 border clash along the border of Manchuria and Mongolia where General Georgy Zhukov's Soviet-Mongolian force crushed the Japanese Sixth Army.", "Battle of Khalkhin Gol", ["nomonhan incident"]),
        q(500, "The 1450 battle during the final stages of the Hundred Years' War where French bureaucratized artillery broke English archers in Normandy.", "Battle of Formigny", ["formigny"]),
        q(500, "The 1759 battle on a plateau outside Quebec City where British General James Wolfe defeated French General Montcalm, both dying in combat.", "Battle of the Plains of Abraham", ["battle of quebec 1759"]),
        q(500, "The 1904 assassination of Russian Governor-General Nikolai Bobrikov in Helsinki by Finnish nationalist civil servant Eugen Schauman.", "Nikolai Bobrikov assassination", ["bobrikov"])
    ]

    return h_100 + h_200 + h_300 + h_400 + h_500

if __name__ == "__main__":
    data = get_history_data()
    print(f"History generated: {len(data)} clues")
