# -*- coding: utf-8 -*-
"""Literature & Lore Category - 200 Real Clues"""

def get_literature_data():
    def q(val, clue, ans, acc=None, src="Wikipedia - Literature"):
        return {"value": val, "clue": clue, "answer": ans, "accepted": acc or [], "source": src}

    l_100 = [
        q(100, "The Bard of Avon who wrote Romeo and Juliet, Hamlet, Macbeth, and Othello.", "William Shakespeare", ["shakespeare"]),
        q(100, "The author who created the magical wizarding world of Hogwarts and Harry Potter.", "J.K. Rowling", ["rowling"]),
        q(100, "The dystopian 1949 novel by George Orwell that introduced 'Big Brother' and 'Thought Police'.", "1984", ["nineteen eighty-four", "nineteen eighty four"]),
        q(100, "In Greek mythology, the king of the gods who rules Mount Olympus and wields lightning bolts.", "Zeus", ["jupiter"]),
        q(100, "The 1851 Herman Melville novel about Captain Ahab's obsessive pursuit of a white sperm whale.", "Moby-Dick", ["moby dick"]),
        q(100, "The author of Pride and Prejudice, Sense and Sensibility, and Emma.", "Jane Austen", ["austen"]),
        q(100, "The mythological Greek hero who performed Twelve Labors and was known for incredible strength.", "Heracles", ["hercules"]),
        q(100, "The epic high fantasy novel by J.R.R. Tolkien featuring the One Ring and Middle-earth.", "The Lord of the Rings", ["lotr", "lord of the rings"]),
        q(100, "The supreme Norse god who gave up one of his eyes to drink from Mimir's well of wisdom.", "Odin", ["woden", "allfather"]),
        q(100, "The 1925 novel by F. Scott Fitzgerald chronicling Jay Gatsby's passion for Daisy Buchanan.", "The Great Gatsby", ["great gatsby"]),
        q(100, "The Danish fairytale author who penned 'The Little Mermaid', 'The Ugly Duckling', and 'The Snow Queen'.", "Hans Christian Andersen", ["andersen"]),
        q(100, "In Greek mythology, the winged horse that sprang from the neck of Medusa.", "Pegasus", ["the winged horse"]),
        q(100, "The Russian novelist who wrote the monumental historical epics War and Peace and Anna Karenina.", "Leo Tolstoy", ["tolstoy"]),
        q(100, "The 1845 narrative poem by Edgar Allan Poe featuring a mysterious talking bird repeating 'Nevermore'.", "The Raven", ["nevermore"]),
        q(100, "The Norse god of thunder who wields the enchanted hammer Mjolnir.", "Thor", ["donar"]),
        q(100, "The Victorian novelist who wrote Oliver Twist, A Christmas Carol, and Great Expectations.", "Charles Dickens", ["dickens"]),
        q(100, "In Greek mythology, the woman whose box (pithos) released all evils into the world, leaving only hope.", "Pandora", ["pandora's box"]),
        q(100, "The 1960 novel by Harper Lee set in Maycomb, Alabama, featuring lawyer Atticus Finch.", "To Kill a Mockingbird", ["to kill a mockingbird"]),
        q(100, "The monster with snakes for hair whose gaze could turn onlookers into stone.", "Medusa", ["gorgon medusa"]),
        q(100, "The 1818 gothic novel by Mary Shelley subtitled 'The Modern Prometheus'.", "Frankenstein", ["frankenstein"]),
        q(100, "The Greek god of the sea, earthquakes, and horses who carries a three-pronged trident.", "Poseidon", ["neptune"]),
        q(100, "The author of The Adventures of Tom Sawyer and Adventures of Huckleberry Finn.", "Mark Twain", ["samuel clemens", "twain"]),
        q(100, "The ancient Greek epic poem attributed to Homer recounting the wrath of Achilles during the Trojan War.", "The Iliad", ["iliad"]),
        q(100, "The Norse trickster god who fathered Fenrir the wolf, the Midgard Serpent, and Hel.", "Loki", ["loke"]),
        q(100, "The 1954 dystopian allegory by William Golding about schoolboys stranded on an uninhabited island.", "Lord of the Flies", ["lord of the flies"]),
        q(100, "The mythological Greek creature with the head of a bull and the body of a man kept in a labyrinth.", "Minotaur", ["the minotaur"]),
        q(100, "The author of The Catcher in the Rye featuring disillusioned teenager Holden Caulfield.", "J.D. Salinger", ["salinger"]),
        q(100, "The Greek goddess of wisdom, warfare, and handicraft who sprang fully grown from Zeus's forehead.", "Athena", ["minerva"]),
        q(100, "The 1847 Emily Bronte gothic novel set on the Yorkshire moors featuring Heathcliff and Catherine.", "Wuthering Heights", ["wuthering heights"]),
        q(100, "The ancient Greek epic poem recounting the ten-year journey home of the king of Ithaca.", "The Odyssey", ["odyssey"]),
        q(100, "In Egyptian mythology, the jackal-headed god associated with mummification and the afterlife.", "Anubis", ["anpu"]),
        q(100, "The 1952 novella by Ernest Hemingway about an aging Cuban fisherman named Santiago catching a giant marlin.", "The Old Man and the Sea", ["old man and the sea"]),
        q(100, "The mythological bird that cyclically regenerates or is otherwise born again from the ashes of its predecessor.", "Phoenix", ["bennu"]),
        q(100, "The English poet who wrote Paradise Lost, recounting the Fall of Man and expulsion from Eden.", "John Milton", ["milton"]),
        q(100, "The Greek hero who dipped in the River Styx except for his heel, making that his sole vulnerability.", "Achilles", ["achilles heel"]),
        q(100, "The 1897 vampire novel by Bram Stoker set in Transylvania and England.", "Dracula", ["count dracula"]),
        q(100, "The Roman god of love and desire, son of Venus, depicted as a winged boy with a bow and arrow.", "Cupid", ["amor", "eros"]),
        q(100, "The 1937 fantasy novel by J.R.R. Tolkien following Bilbo Baggins on a quest to reclaim the Lonely Mountain.", "The Hobbit", ["there and back again"]),
        q(100, "The Greek goddess of love, beauty, and passion born from sea foam near Cyprus.", "Aphrodite", ["venus"]),
        q(100, "The 1932 dystopian novel by Aldous Huxley set in a genetically stratified World State centered on soma.", "Brave New World", ["brave new world"])
    ]

    l_200 = [
        q(200, "The 14th-century Florentine poet who journeyed through the Inferno, Purgatorio, and Paradiso in The Divine Comedy.", "Dante Alighieri", ["dante", "alighieri"]),
        q(200, "The ancient Mesopotamian epic poem, the earliest surviving great literary masterpiece, chronicling a Uruk king.", "Epic of Gilgamesh", ["gilgamesh"]),
        q(200, "The 19th-century Russian author who penned Crime and Punishment, The Brothers Karamazov, and The Idiot.", "Fyodor Dostoevsky", ["dostoevsky"]),
        q(200, "In Greek mythology, the Titan condemned to hold up the celestial heavens on his shoulders for eternity.", "Atlas", ["titan atlas"]),
        q(200, "The 1605 Spanish novel by Miguel de Cervantes about a delusional nobleman who attacks windmills.", "Don Quixote", ["el quijote", "cervantes"]),
        q(200, "The Irish author whose 1922 landmark modernist novel Ulysses chronicles Leopold Bloom's day in Dublin.", "James Joyce", ["joyce"]),
        q(200, "In Norse mythology, the catastrophic end-of-the-world battle between gods and giants.", "Ragnarok", ["ragnarök", "twilight of the gods"]),
        q(200, "The 1847 Charlotte Bronte novel following an orphaned governess who falls in love with Mr. Rochester.", "Jane Eyre", ["jane eyre"]),
        q(200, "The mythological Greek musician who descended to the Underworld to rescue his deceased wife Eurydice.", "Orpheus", ["orpheus and eurydice"]),
        q(200, "The French philosopher and writer who authored Candide, satirizing Leibnizian optimism in 1759.", "Voltaire", ["francois-marie arouet"]),
        q(200, "The 1967 Colombian magical realist epic novel by Gabriel Garcia Marquez chronicling seven generations of the Buendia family.", "One Hundred Years of Solitude", ["cien anos de soledad"]),
        q(200, "In Greek mythology, the son of Daedalus who flew too close to the Sun, melting the wax holding his wings.", "Icarus", ["flight of icarus"]),
        q(200, "The 1862 French historical novel by Victor Hugo following Jean Valjean's redemption and pursuit by Javert.", "Les Miserables", ["les misérables", "les mis"]),
        q(200, "The German literary genius who spent decades writing the two-part tragic play Faust.", "Johann Wolfgang von Goethe", ["goethe"]),
        q(200, "In Greek mythology, the ferryman of Hades who carries the souls of the newly deceased across the River Styx.", "Charon", ["charon ferryman"]),
        q(200, "The 1925 modernist novel by Virginia Woolf chronicling a single day in the life of Clarissa Dalloway in London.", "Mrs Dalloway", ["mrs. dalloway"]),
        q(200, "The 1953 Arthur Miller play allegorizing the Salem witch trials to critique McCarthyism.", "The Crucible", ["the crucible"]),
        q(200, "In Greek mythology, the king punished in Tartarus by being forced to roll an immense boulder up a hill for eternity.", "Sisyphus", ["myth of sisyphus"]),
        q(200, "The 1890 Oscar Wilde philosophical novel about a hedonistic man whose painted portrait ages while he stays young.", "The Picture of Dorian Gray", ["dorian gray"]),
        q(200, "The ancient Roman epic poem written by Virgil between 29 and 19 BC telling the legendary story of Aeneas fleeing Troy.", "The Aeneid", ["aeneid"]),
        q(200, "In Egyptian mythology, the falcon-headed god of the sky and kingship who avenged the murder of his father Osiris.", "Horus", ["heru"]),
        q(200, "The 1939 John Steinbeck novel following the Joad family's migration from the Oklahoma Dust Bowl to California.", "The Grapes of Wrath", ["grapes of wrath"]),
        q(200, "The Titan who stole fire from the gods on Mount Olympus to give to humanity, punished by having his liver eaten daily.", "Prometheus", ["titan prometheus"]),
        q(200, "The 1915 Franz Kafka novella where traveling salesman Gregor Samsa awakens transformed into a giant insect.", "The Metamorphosis", ["die verwandlung"]),
        q(200, "In Norse mythology, the supreme hall in Asgard ruled by Odin where fallen warriors (Einherjar) feast.", "Valhalla", ["valholl"]),
        q(200, "The 1953 Ray Bradbury sci-fi novel set in an American society where books are outlawed and firemen burn them.", "Fahrenheit 451", ["fahrenheit 451"]),
        q(200, "The Greek queen of the Underworld and wife of Hades, daughter of Demeter who spends part of each year below.", "Persephone", ["kore", "proserpina"]),
        q(200, "The 1884 Mark Twain novel that Ernest Hemingway declared all modern American literature comes from.", "Adventures of Huckleberry Finn", ["huckleberry finn"]),
        q(200, "In Greek mythology, the three-headed hound that guards the entrance to the Underworld to prevent the dead from escaping.", "Cerberus", ["kerberos", "hound of hades"]),
        q(200, "The 1726 Jonathan Swift prose satire recounting voyages to Lilliput, Brobdingnag, Laputa, and the land of the Houyhnhnms.", "Gulliver's Travels", ["gullivers travels"]),
        q(200, "The Greek hero who solved the riddle of the Sphinx and unwittingly killed his father and married his mother.", "Oedipus", ["oedipus rex"]),
        q(200, "The 1985 Margaret Atwood dystopian novel set in the Republic of Gilead where fertile women are forced into reproductive servitude.", "The Handmaid's Tale", ["handmaids tale"]),
        q(200, "In Norse mythology, the rainbow bridge that connects Midgard (the world of humans) with Asgard (realm of gods).", "Bifrost", ["bilrost", "bifröst"]),
        q(200, "The French philosopher and author of The Stranger (L'Etranger) who formulated the concept of Absurdism.", "Albert Camus", ["camus"]),
        q(200, "In Greek mythology, the hunter who fell in love with his own reflection in a pool of water and wasted away.", "Narcissus", ["narkissos"]),
        q(200, "The 1958 Chinua Achebe debut novel set in colonial Nigeria that is the most widely read book in modern African literature.", "Things Fall Apart", ["things fall apart"]),
        q(200, "In Greek mythology, the fleece of the golden-haired winged ram sought by Jason and the Argonauts in Colchis.", "The Golden Fleece", ["golden fleece"]),
        q(200, "The 1844 adventure novel by Alexandre Dumas telling the revenge story of Edmond Dantes after his wrongful imprisonment in Chateau d'If.", "The Count of Monte Cristo", ["count of monte cristo"]),
        q(200, "The Hindu prince in the Bhagavad Gita who receives spiritual counsel from Krishna on the battlefield of Kurukshetra.", "Arjuna", ["arjun"]),
        q(200, "The 1927 Hermann Hesse novel exploring the dual nature of Harry Haller as half-man and half-wolf of the steppes.", "Steppenwolf", ["der steppenwolf"])
    ]

    l_300 = [
        q(300, "The seven-volume French modernist novel by Marcel Proust, translated into English as In Search of Lost Time.", "A la recherche du temps perdu", ["in search of lost time", "remembrance of things past"]),
        q(300, "The Anglo-Saxon epic poem consisting of 3,182 alliterative lines where a Geatish hero slays the monster Grendel.", "Beowulf", ["beowulf epic"]),
        q(300, "The ancient Roman poet exiled to Tomis by Augustus who wrote Metamorphoses and Ars Amatoria.", "Ovid", ["publius ovidius naso"]),
        q(300, "In Norse mythology, the guardian of the Bifrost bridge who possesses acute senses and sounds the Gjallarhorn.", "Heimdall", ["heimdallr"]),
        q(300, "The 1929 William Faulkner southern gothic novel utilizing multiple interior monologues, titled from a Macbeth soliloquy.", "The Sound and the Fury", ["sound and the fury"]),
        q(300, "The Japanese author of The Tale of Genji, written in the early 11th century, widely considered the world's first novel.", "Murasaki Shikibu", ["lady murasaki"]),
        q(300, "In Greek mythology, the youth beloved by Apollo who was accidentally killed by Apollo's discus and turned into a flower.", "Hyacinthus", ["hyacinth"]),
        q(300, "The 1938 Samuel Beckett French-language play in which Vladimir and Estragon endlessly wait for an elusive figure.", "Waiting for Godot", ["en attendant godot"]),
        q(300, "The ancient Greek lyric poet from the island of Lesbos celebrated for her passionate poetry about women.", "Sappho", ["sappho of lesbos"]),
        q(300, "In Norse mythology, the immense ash tree that connects the nine worlds in Norse cosmology.", "Yggdrasil", ["world tree"]),
        q(300, "The 1973 Thomas Pynchon postmodern encyclopedic novel centered on the V-2 rocket during World War II.", "Gravity's Rainbow", ["gravitys rainbow"]),
        q(300, "In Greek mythology, the river of forgetfulness in the Underworld from which souls drink to erase earthly memories.", "Lethe", ["river lethe"]),
        q(300, "The 1922 landmark poem by T.S. Eliot that opens with the famous line 'April is the cruellest month'.", "The Waste Land", ["waste land"]),
        q(300, "The epic Sanskrit poem attributed to Sage Vyasa containing over 100,000 shlokas, recounting the Kurukshetra War.", "Mahabharata", ["the mahabharata"]),
        q(300, "In Greek mythology, the daughter of King Priam of Troy cursed by Apollo so that her true prophecies would never be believed.", "Cassandra", ["kassandra"]),
        q(300, "The 1902 novella by Joseph Conrad following Charles Marlow's journey up the Congo River to find ivory trader Kurtz.", "Heart of Darkness", ["heart of darkness"]),
        q(300, "The Babylonian goddess of fertility, love, war, and sex who descends into the Underworld in ancient myth.", "Ishtar", ["inanna"]),
        q(300, "The 1981 Salman Rushdie novel about children born at the exact moment of India's independence, winning the Booker of Bookers.", "Midnight's Children", ["midnights children"]),
        q(300, "In Norse mythology, the monstrous wolf bound by the gods with the magical ribbon Gleipnir, fated to slay Odin at Ragnarok.", "Fenrir", ["fenris wolf"]),
        q(300, "The 1886 Robert Louis Stevenson gothic novella examining the duality of man's nature through chemical potions.", "Strange Case of Dr Jekyll and Mr Hyde", ["dr jekyll and mr hyde", "jekyll and hyde"]),
        q(300, "In Greek mythology, the princess of Colchis who helped Jason acquire the Golden Fleece and later killed their children in revenge.", "Medea", ["medea play"]),
        q(300, "The 1969 Kurt Vonnegut satirical anti-war novel based on his survival of the Allied firebombing of Dresden.", "Slaughterhouse-Five", ["slaughterhouse five"]),
        q(300, "The 13th-century Icelandic historian and poet who authored the Prose Edda and Heimskringla.", "Snorri Sturluson", ["snorri"]),
        q(300, "The 1971 John Gardner novel that retells the Beowulf epic from the perspective of the monster.", "Grendel", ["grendel novel"]),
        q(300, "In Greek mythology, the god of sleep and father of Morpheus, twin brother of Thanatos (death).", "Hypnos", ["somnus"]),
        q(300, "The 1924 E.M. Forster novel examining racial tensions and colonial rule in the British Raj centered on the Marabar Caves.", "A Passage to India", ["passage to india"]),
        q(300, "The Celtic mythological land of eternal youth, beauty, and joy, reachable by entering ancient mounds or across the sea.", "Tir na nOg", ["tír na n-óg"]),
        q(300, "The 1957 Jack Kerouac beat generation novel based on spontaneous road trips across America with Neal Cassady.", "On the Road", ["on the road"]),
        q(300, "In Greek mythology, the three goddesses of vengeance and retribution who torment those who commit severe crimes against natural order.", "The Furies", ["erinyes", "eumenides"]),
        q(300, "The 1855 collection of twelve untitled poems by Walt Whitman celebrating democracy, nature, and the human spirit.", "Leaves of Grass", ["leaves of grass"]),
        q(300, "The Egyptian god of chaos, storms, violence, and deserts who murdered his brother Osiris.", "Set", ["seth", "suetekh"]),
        q(300, "The 1946 John Hersey journalistic masterpiece documenting the stories of six survivors of the atomic bombing.", "Hiroshima", ["hiroshima book"]),
        q(300, "In Norse mythology, the goddess of love, beauty, fertility, and gold who receives half of all fallen warriors in Folkvangr.", "Freyja", ["freya"]),
        q(300, "The 1903 Jack London adventure novel about a domesticated St. Bernard/Scotch Collie named Buck abducted to the Klondike.", "The Call of the Wild", ["call of the wild"]),
        q(300, "In Greek mythology, the daughter of Minos who gave Theseus a ball of thread to escape the Cretan Labyrinth.", "Ariadne", ["ariadne thread"]),
        q(300, "The 1927 Thornton Wilder novel about the collapse of an Inca rope bridge in Peru and the intertwined lives of five victims.", "The Bridge of San Luis Rey", ["bridge of san luis rey"]),
        q(300, "In Greek mythology, the legendary sculptor from Cyprus who fell in love with a statue he had carved from ivory, brought to life by Aphrodite.", "Pygmalion", ["pygmalion and galatea"]),
        q(300, "The 1947 Arthur Miller play about a manufacturing father who shipped defective aircraft cylinder heads during WWII.", "All My Sons", ["all my sons"]),
        q(300, "The ancient Finnish national epic compiled in the 19th century by Elias Lonnrot from traditional oral ballads.", "Kalevala", ["the kalevala"]),
        q(300, "The 1905 O. Henry short story about a young married couple who secretly sacrifice their most prized possessions for Christmas gifts.", "The Gift of the Magi", ["gift of the magi"])
    ]

    l_400 = [
        q(400, "The 1939 James Joyce avant-garde novel renowned for its experimental stream-of-consciousness dream language, opening 'riverrun'.", "Finnegans Wake", ["finnegans wake"]),
        q(400, "The ancient Sanskrit treatise on performing arts, theater, and dramaturgy attributed to sage Bharata Muni, defining rasa.", "Natya Shastra", ["natyashastra"]),
        q(400, "The 18th-century French author of Dangerous Liaisons (Les Liaisons dangereuses), an epistolary novel of cynical seduction.", "Pierre Choderlos de Laclos", ["laclos"]),
        q(400, "In Norse mythology, the ship made entirely from the unpared fingernails and toenails of the dead, crewed by giants at Ragnarok.", "Naglfar", ["nail ship"]),
        q(400, "The 1974 Ursula K. Le Guin sci-fi masterpiece contrasting the anarcho-syndicalist moon Anarres with capitalist Urras.", "The Dispossessed", ["the dispossessed"]),
        q(400, "The ancient Roman historian who wrote the Annals and Histories, detailing the reigns of Tiberius, Claudius, and Nero.", "Tacitus", ["publius cornelius tacitus"]),
        q(400, "In Greek mythology, the Titaness of divine law and order who mothered the Fates and the Hours with Zeus.", "Themis", ["titaness themis"]),
        q(400, "The 1912 Thomas Mann novella about an aging writer, Gustav von Aschenbach, who falls obsessively in love in cholera-ridden Venice.", "Death in Venice", ["der tod in venedig"]),
        q(400, "In Japanese mythology, the creator gods who stirred the primeval ocean with the jeweled spear Amenonuhoko to create Japan.", "Izanagi and Izanami", ["izanagi", "izanami"]),
        q(400, "The 1928 Virginia Woolf feminist essay series arguing that 'a woman must have money and a room of her own if she is to write fiction'.", "A Room of One's Own", ["room of one's own"]),
        q(400, "The Portuguese national epic poem written in ottava rima by Luis de Camoes in 1572 celebrating Vasco da Gama's voyage.", "Os Lusiadas", ["the lusiads"]),
        q(400, "In Greek mythology, the monster with the body of a woman and the head of six ravenous barking dogs inhabiting the Strait of Messina.", "Scylla", ["scylla and charybdis"]),
        q(400, "The 1955 Argentine novel by Juan Rulfo where Juan Preciado travels to the ghost-town of Comala to find his father.", "Pedro Paramo", ["pedro páramo"]),
        q(400, "In Norse mythology, the dark elves or dwarfs who forged Thor's hammer, Odin's ring Draupnir, and Freyr's ship.", "Sons of Ivaldi", ["dwarves", "brokkr and eitri"]),
        q(400, "The 1943 French existentialist philosophical treatise by Jean-Paul Sartre subtitled 'An Essay on Phenomenological Ontology'.", "Being and Nothingness", ["l'etre et le neant"]),
        q(400, "In Persian mythology, the heroic warrior who unwittingly slays his own son Sohrab in single combat in the Shahnameh.", "Rostam", ["rustam"]),
        q(400, "The 1901 Thomas Mann generational family saga tracing the decline of a wealthy Lubeck grain merchant family.", "Buddenbrooks", ["buddenbrooks: the decline of a family"]),
        q(400, "In Greek mythology, the subterranean realm deeper than Hades where Uranus and Cronus imprisoned the Cyclopes and Titans.", "Tartarus", ["tartaros"]),
        q(400, "The 1978 Georges Perec Oulipo masterpiece consisting of 99 chapters structured around the Knight's Tour across a Parisian apartment block.", "Life: A User's Manual", ["la vie mode d'emploi"]),
        q(400, "The ancient Egyptian funerary text collection known as the 'Spells for Coming Forth by Day' placed in tombs.", "The Book of the Dead", ["book of the dead"]),
        q(400, "The 1931 Virginia Woolf poetic experimental novel composed of soliloquies by six characters: Bernard, Susan, Rhoda, Neville, Jinny, and Louis.", "The Waves", ["the waves"]),
        q(400, "In Celtic mythology, the hero of Ulster who enters the berserk rage called the 'warp-spasm' (riastrad) and wields the barbed spear Gae Bulg.", "Cu Chulainn", ["cuchulainn", "cú chulainn"]),
        q(400, "The 1913 Alain-Fournier French novel recounting Augustin Meaulnes' discovery of a magical, dream-like lost manor during a festival.", "Le Grand Meaulnes", ["the lost estate"]),
        q(400, "In Greek mythology, the King of Thebes torn to pieces by his own mother Agave during a Bacchic frenzy in Euripides' The Bacchae.", "Pentheus", ["king pentheus"]),
        q(400, "The 1980 Umberto Eco medieval mystery novel where Franciscan friar William of Baskerville investigates monastic murders.", "The Name of the Rose", ["il nome della rosa"]),
        q(400, "The 10th-century national epic of Greater Iran composed by the poet Ferdowsi over three decades, containing 50,000 couplets.", "Shahnameh", ["the book of kings"]),
        q(400, "In Norse mythology, the giant who guards the well of wisdom beneath the root of Yggdrasil, from which Odin drank.", "Mimir", ["mímir"]),
        q(400, "The 1926 Mikhail Bulgakov satirical masterpiece involving the Devil (Woland) visiting 1930s Moscow alongside a demonic talking cat.", "The Master and Margarita", ["master and margarita"]),
        q(400, "In Greek mythology, the river of fire in the Underworld that leads into the depths of Tartarus.", "Phlegethon", ["pyriphlegethon"]),
        q(400, "The 1969 Vladimir Nabokov novel written as a pseudo-academic commentary and index on a 999-line poem by John Shade.", "Pale Fire", ["pale fire"]),
        q(400, "The ancient Roman scholar who wrote the encyclopedic Naturalis Historia in 37 books and died during the eruption of Mount Vesuvius in 79 AD.", "Pliny the Elder", ["gaius plinius secundus"]),
        q(400, "In Japanese folklore, the shape-shifting raccoon dog known for carrying a bottle of sake and having comical supernatural powers.", "Tanuki", ["japanese raccoon dog"]),
        q(400, "The 1934 Henry Miller semi-autobiographical erotic novel published in Paris by the Obelisk Press and banned in the US until 1961.", "Tropic of Cancer", ["tropic of cancer"]),
        q(400, "In Greek mythology, the king of Corinth who chained Thanatos (Death) so no one could die, later tricking Persephone to escape Hades.", "Sisyphus", ["king sisyphus"]),
        q(400, "The 1949 Alejo Carpentier historical novel set during the Haitian Revolution that introduced the term 'lo real maravilloso' (the marvelous real).", "The Kingdom of This World", ["el reino de este mundo"]),
        q(400, "The Mesoamerican feathered serpent deity worshipped by the Maya (as Kukulkan) and Aztecs as creator god of wind and learning.", "Quetzalcoatl", ["kukulkan"]),
        q(400, "The 1904 Anton Chekhov play revolving around an aristocratic Russian landowner forced to auction her family estate to pay mortgage debts.", "The Cherry Orchard", ["vishnyovyi sad"]),
        q(400, "In Norse mythology, the golden boar forged by the dwarf brothers Brokkr and Eitri that pulls the chariot of the god Freyr.", "Gullinbursti", ["golden bristles"]),
        q(400, "The 1963 Julio Cortazar Argentine boom novel structured so that readers can read it linearly or follow an alternative chapter hopscotch route.", "Hopscotch", ["rayuela"]),
        q(400, "In Greek mythology, the Greek mythological river of pain and lamentation in the Underworld.", "Acheron", ["river acheron"])
    ]

    l_500 = [
        q(500, "The 1621 Robert Burton encyclopedic treatise analyzing the causes, symptoms, and cures of melancholy through philosophical digressions.", "The Anatomy of Melancholy", ["anatomy of melancholy"]),
        q(500, "The ancient Ugaritic poetic cycle discovered on clay tablets at Ras Shamra detailing the storm god Baal's conflict with Mot (Death) and Yam (Sea).", "Baal Cycle", ["epic of baal"]),
        q(500, "The 1931 French surrealist novel by Raymond Roussel where sentences generated from homophonic wordplay construct an African spectacle.", "Impressions of Africa", ["impressions d'afrique"]),
        q(500, "In Norse mythology, the giant rooster whose crow awakens the warriors of Odin when Ragnarok arrives, contrasted with the red rooster Fjalar.", "Gullinkambi", ["golden comb"]),
        q(500, "The 1970 French Oulipo constraint novel by Georges Perec written entirely without the letter 'e' (a lipogram).", "A Void", ["la disparition"]),
        q(500, "The 2nd-century Greek author who wrote A True Story (Vera Historia), featuring travel to the Moon, regarded as the earliest science fiction.", "Lucian of Samosata", ["lucian"]),
        q(500, "In Japanese mythology, the storm and sea god who was banished from heaven after defiling Amaterasu's weaving hall and later slew the Yamata no Orochi.", "Susanoo", ["susanoo-no-mikoto"]),
        q(500, "The 1930 Robert Musil unfinished philosophical novel spanning over 1,700 pages exploring the intellectual climate of Austro-Hungary before WWI.", "The Man Without Qualities", ["der mann ohne eigenschaften"]),
        q(500, "In Greek mythology, the spring on Mount Helicon sacred to the Muses created when Pegasus's hooves struck the rock.", "Hippocrene", ["the hippocrene spring"]),
        q(500, "The 1835 Georg Buchner revolutionary German drama depicting the final days of Georges Danton during the Reign of Terror.", "Danton's Death", ["dantons tod"]),
        q(500, "The medieval Georgian epic poem of roughly 1,600 stanzas composed by Shota Rustaveli in the 12th century, the national epic of Georgia.", "The Knight in the Panther's Skin", ["vepkhistkaosani"]),
        q(500, "In Celtic mythology, the supernatural cauldron belonging to the Dagda that could restore the dead to life or satisfy the hunger of any company.", "Cauldron of the Dagda", ["undry"]),
        q(500, "The 1978 Austrian novel by Thomas Bernhard consisting of a single unbroken rant by an art historian seated on an antique settee in the Kunsthistorisches Museum.", "Old Masters", ["alte meister"]),
        q(500, "In Aztec mythology, the goddess of earth and fertility who gave birth to the Moon, stars, and Huitzilopochtli, depicted with a skirt of serpents.", "Coatlicue", ["coatlicue goddess"]),
        q(500, "The 1907 Irish peasant comedy by J.M. Synge that caused riots at Dublin's Abbey Theatre over its irreverence and mention of feminine shifts.", "The Playboy of the Western World", ["playboy of the western world"]),
        q(500, "The 13th-century German epic poem by Wolfram von Eschenbach that became the definitive medieval Grail romance.", "Parzival", ["parzival epic"]),
        q(500, "In Greek mythology, the monstrous subterranean serpentine dragon appointed by Hera to guard the golden apples of the Hesperides.", "Ladon", ["dragon ladon"]),
        q(500, "The 1974 Hungarian postmodern novel by Peter Esterhazy constructed entirely of quotations from classical Hungarian literature.", "Production Novel", ["termelesi regeny"]),
        q(500, "In Norse mythology, the subterranean hall where the dragon Nidhogg chews upon corpses, situated in the frozen realm of Niflheim.", "Nastrond", ["náströnd"]),
        q(500, "The 1928 Russian formalist study by Vladimir Propp that broke down the structural morphology of 100 Russian folktales into 31 functions.", "Morphology of the Folktale", ["propp morphology"]),
        q(500, "The 1st-century Roman satirical novel by Petronius featuring the flamboyant, vulgar banquet hosted by the wealthy freedman Trimalchio.", "Satyricon", ["petronius satyricon"]),
        q(500, "In West African Yoruba mythology, the fiery Orisha of thunder, lightning, and justice who carries a double-bladed axe.", "Shango", ["sango", "chango"]),
        q(500, "The 1966 Polish absurd novel by Witold Gombrowicz centered on two young men investigating hanging sparrows and geometric arrows.", "Cosmos", ["kosmos"]),
        q(500, "In Greek mythology, the Athenian craftsman who murdered his nephew Perdix out of jealousy before fleeing to Crete to build the Labyrinth.", "Daedalus", ["daidalos"]),
        q(500, "The 1952 essay collection by Walter Benjamin containing 'The Work of Art in the Age of Mechanical Reproduction'.", "Illuminations", ["walter benjamin illuminations"]),
        q(500, "The 12th-century French poetess who wrote twelve Breton lais including Lanval, Chevrefoil, and Bisclavret (the werewolf lai).", "Marie de France", ["marie de france"]),
        q(500, "In Norse mythology, the nine daughters of the sea god Aegir and Ran who personify the ocean waves.", "Nine daughters of Aegir", ["billow maidens"]),
        q(500, "The 1975 Italian experimental novel by Italo Calvino consisting of tarot card readings dictating the fates of travelers stranded in a forest castle.", "The Castle of Crossed Destinies", ["il castello dei destini incrociati"]),
        q(500, "The ancient Egyptian mythological concept of cosmic order, balance, truth, and harmony, personified as a goddess with an ostrich feather.", "Ma'at", ["maat", "feather of maat"]),
        q(500, "The 1968 William Gaddis post-modern satire about an eleven-year-old Long Island boy who secretly builds a Wall Street corporate empire.", "JR", ["j r novel"]),
        q(500, "In Greek mythology, the daughter of Minos and Pasiphae who was seduced by a bull and gave birth to the Minotaur.", "Pasiphae", ["queen pasiphae"]),
        q(500, "The 1932 Louis-Ferdinand Celine semi-autobiographical anti-heroic novel following Ferdinand Bardamu through WWI, colonial Africa, and Detroit.", "Journey to the End of the Night", ["voyage au bout de la nuit"]),
        q(500, "In Polynesian mythology, the trickster hero who fished up the North Island of New Zealand using the magic jawbone of his grandmother.", "Maui", ["māui"]),
        q(500, "The 1807 political satire by Washington Irving that popularized the term 'Gotham' as a nickname for New York City.", "Salmagundi", ["salmagundi papers"]),
        q(500, "In Norse mythology, the dwarf who forged the ring Andvaranaut, which carried a curse of doom for any possessor after Loki stole it.", "Andvari", ["andvaranaut"]),
        q(500, "The 1962 French nouveau roman novel by Alain Robbe-Grillet set on a colonial banana plantation observing a wife named A...", "Jealousy", ["la jalousie"]),
        q(500, "In Greek mythology, the Queen of Corinth who gave her name to the Isthmian Games after drowning herself and her son Melicertes.", "Ino", ["leucothea"]),
        q(500, "The 1983 Austrian novel by Thomas Bernhard fictionalizing the real-life Canadian pianist Glenn Gould's recording of the Goldberg Variations.", "The Loser", ["der untergeher"]),
        q(500, "The ancient Persian compilation of Zoroastrian sacred scriptures written in the ancient Eastern Iranian Avestan language.", "Avesta", ["zend avesta"]),
        q(500, "The 1974 Austrian novel by Ingeborg Bachmann examining the psychological destruction of female identity in patriarchal Vienna.", "Malina", ["malina novel"])
    ]

    return l_100 + l_200 + l_300 + l_400 + l_500

if __name__ == "__main__":
    data = get_literature_data()
    print(f"Literature generated: {len(data)} clues")
