# -*- coding: utf-8 -*-
"""Music & Pop Culture Category - 200 Real Clues"""

def get_music_data():
    def q(val, clue, ans, acc=None, src="Wikipedia - Music"):
        return {"value": val, "clue": clue, "answer": ans, "accepted": acc or [], "source": src}

    m_100 = [
        q(100, "Known as the 'King of Pop', his 1982 album Thriller remains the best-selling album of all time.", "Michael Jackson", ["jackson", "mj"]),
        q(100, "The British quartet from Liverpool composed of John Lennon, Paul McCartney, George Harrison, and Ringo Starr.", "The Beatles", ["beatles", "fab four"]),
        q(100, "Her record-shattering 'Eras Tour' became the first concert tour in history to gross over $1 billion.", "Taylor Swift", ["swift"]),
        q(100, "The flamboyant lead singer of rock band Queen who performed 'Bohemian Rhapsody' and dazzled at Live Aid.", "Freddie Mercury", ["mercury"]),
        q(100, "Known as the 'King of Rock and Roll', he lived at Graceland in Memphis, Tennessee.", "Elvis Presley", ["elvis"]),
        q(100, "The British singer whose soulful albums are titled after her ages: 19, 21, 25, and 30.", "Adele", ["adele adkins"]),
        q(100, "The Canadian rapper and former Degrassi actor known for hits like 'Hotline Bling' and 'God's Plan'.", "Drake", ["aubrey graham"]),
        q(100, "The 1969 music and peace festival held on Max Yasgur's dairy farm in Bethel, New York.", "Woodstock", ["woodstock festival"]),
        q(100, "The legendary Jamaican reggae pioneer who recorded 'One Love', 'No Woman, No Cry', and 'Buffalo Soldier'.", "Bob Marley", ["marley"]),
        q(100, "The instrument with 88 black and white keys played by Mozart, Chopin, and Elton John.", "Piano", ["grand piano", "pianoforte"]),
        q(100, "The artist formerly known as a member of Destiny's Child whose fans are called the 'BeyHive'.", "Beyonce", ["beyoncé", "queen bey"]),
        q(100, "The Austrian musical prodigy who composed over 600 works before dying at age 35 in 1791.", "Wolfgang Amadeus Mozart", ["mozart"]),
        q(100, "The Seattle grunge band fronted by Kurt Cobain that exploded with 'Smells Like Teen Spirit' in 1991.", "Nirvana", ["nirvana band"]),
        q(100, "The American folk rock singer-songwriter born Robert Zimmerman who won the 2016 Nobel Prize in Literature.", "Bob Dylan", ["dylan"]),
        q(100, "The musical symbol placed at the beginning of a musical staff, commonly Treble or Bass.", "Clef", ["treble clef", "bass clef"]),
        q(100, "The English rock band that released The Dark Side of the Moon and The Wall.", "Pink Floyd", ["pink floyd band"]),
        q(100, "The pop star known for eccentric fashion like her meat dress and hits like 'Bad Romance' and 'Poker Face'.", "Lady Gaga", ["gaga", "stefani germanotta"]),
        q(100, "The German classical composer who composed his epic Ninth Symphony while completely deaf.", "Ludwig van Beethoven", ["beethoven"]),
        q(100, "The stringed instrument associated with Jimi Hendrix, Eric Clapton, and Eddie Van Halen.", "Electric guitar", ["guitar"]),
        q(100, "The hip-hop trio consisting of Quavo, Offset, and the late Takeoff from Georgia.", "Migos", ["the migos"]),
        q(100, "The Irish rock band fronted by Bono and The Edge that released The Joshua Tree.", "U2", ["u2 band"]),
        q(100, "The American pop icon who performed 'Like a Virgin', 'Vogue', and 'Material Girl'.", "Madonna", ["madonna ciccone"]),
        q(100, "The Australian hard rock band formed by brothers Malcolm and Angus Young, famous for 'Highway to Hell'.", "AC/DC", ["acdc"]),
        q(100, "The Grammy Award trophy is shaped in the design of this early musical sound recording device.", "Gramophone", ["phonograph"]),
        q(100, "The Barbadian singer who performed at the 2023 Super Bowl and founded the Fenty Beauty brand.", "Rihanna", ["robyn fenty"]),
        q(100, "The Italian tenor who became a global classical crossover superstar with 'Con te partiro'.", "Andrea Bocelli", ["bocelli"]),
        q(100, "The English rock band fronted by Mick Jagger with guitarist Keith Richards.", "The Rolling Stones", ["rolling stones"]),
        q(100, "The Swedish pop supergroup behind hits like 'Dancing Queen', 'Mamma Mia', and 'Waterloo'.", "ABBA", ["abba"]),
        q(100, "The Detroit rapper born Marshall Mathers who starred in 8 Mile and recorded 'Lose Yourself'.", "Eminem", ["slim shady", "marshall mathers"]),
        q(100, "The percussion instrument consisting of a hollow cylinder with a stretched membrane struck with sticks.", "Drum", ["snare drum", "drums"]),
        q(100, "The country music icon famous for 'Jolene', '9 to 5', and funding the Moderna COVID vaccine.", "Dolly Parton", ["parton"]),
        q(100, "The British singer who skyrocketed to fame as a member of One Direction and released 'Watermelon Sugar'.", "Harry Styles", ["styles"]),
        q(100, "The genre of African American music that originated in New Orleans, celebrated by Louis Armstrong.", "Jazz", ["new orleans jazz"]),
        q(100, "The high-pitched woodwind instrument played horizontally by blowing across an embouchure hole.", "Flute", ["concert flute"]),
        q(100, "The legendary R&B record company founded by Berry Gordy Jr. in Detroit in 1959.", "Motown", ["motown records"]),
        q(100, "The American rock band fronted by Steven Tyler with guitarist Joe Perry, behind 'Dream On'.", "Aerosmith", ["aerosmith band"]),
        q(100, "The 2012 Korean pop music video by Psy that became the first YouTube video to reach 1 billion views.", "Gangnam Style", ["gangnam style psy"]),
        q(100, "The large bowed stringed instrument pitched lower than the viola and higher than the double bass.", "Cello", ["violoncello"]),
        q(100, "The annual European television song contest organized by the EBU since 1956.", "Eurovision Song Contest", ["eurovision"]),
        q(100, "The British alternative rock band fronted by Chris Martin, famous for 'Yellow' and 'Fix You'.", "Coldplay", ["coldplay band"])
    ]

    m_200 = [
        q(200, "The Italian violin maker of the 17th and 18th centuries whose handcrafted instruments are worth tens of millions.", "Antonio Stradivari", ["stradivarius", "stradivari"]),
        q(200, "The pioneering 1973 hip-hop DJ who hosted a back-to-school party at 1520 Sedgwick Avenue in the Bronx.", "DJ Kool Herc", ["kool herc", "clive campbell"]),
        q(200, "The 1975 epic rock single by Queen that features an operatic section mentioning Scaramouche and Galileo.", "Bohemian Rhapsody", ["bohemian rhapsody"]),
        q(200, "The German Baroque composer who wrote the Brandenburg Concertos and The Well-Tempered Clavier.", "Johann Sebastian Bach", ["bach", "j.s. bach"]),
        q(200, "The 1969 Beatles album whose cover features the band walking across a zebra crossing outside their studio.", "Abbey Road", ["abbey road album"]),
        q(200, "The pioneering heavy metal band formed in Birmingham in 1968 fronted by Ozzy Osbourne.", "Black Sabbath", ["black sabbath"]),
        q(200, "The American jazz trumpeter who recorded the best-selling jazz album of all time, Kind of Blue, in 1959.", "Miles Davis", ["davis"]),
        q(200, "The musical tempo marking in Italian that indicates a fast, quickly, and bright tempo.", "Allegro", ["allegro tempo"]),
        q(200, "The singer known as the 'Queen of Soul' who demanded 'R-E-S-P-E-C-T' in her 1967 smash hit.", "Aretha Franklin", ["franklin"]),
        q(200, "The Led Zeppelin masterpiece released on their untitled fourth studio album in 1971 featuring a famous guitar solo.", "Stairway to Heaven", ["stairway to heaven"]),
        q(200, "The Italian opera composer of La traviata, Rigoletto, Aida, and Nabucco.", "Giuseppe Verdi", ["verdi"]),
        q(200, "The 1997 hip hop track by The Notorious B.I.G. featuring Puff Daddy that popularized the phrase 'Mo Money Mo Problems'.", "Mo Money Mo Problems", ["mo money mo problems"]),
        q(200, "The English singer-songwriter who performed 'Rocket Man' and a rewritten 'Candle in the Wind' for Princess Diana.", "Elton John", ["sir elton john", "reginald dwight"]),
        q(200, "The musical interval between two notes where one has twice the frequency of the other (12 semitones).", "Octave", ["an octave"]),
        q(200, "The 1991 Metallica self-titled studio album commonly known by this color due to its dark minimalist cover.", "The Black Album", ["metallica black album", "black album"]),
        q(200, "The American jazz singer known as the 'First Lady of Song' celebrated for her virtuosic scat singing.", "Ella Fitzgerald", ["fitzgerald"]),
        q(200, "The French composer who created the orchestral work Bolero, characterized by an unrelenting snare rhythm.", "Maurice Ravel", ["ravel"]),
        q(200, "The 1967 landmark concept album by The Beatles featuring an alter-ego military band on the cover.", "Sgt. Pepper's Lonely Hearts Club Band", ["sgt pepper", "sgt peppers"]),
        q(200, "The artist born Prince Rogers Nelson who recorded 'Purple Rain' and performed at the 2007 Super Bowl in downpour.", "Prince", ["the artist formerly known as prince"]),
        q(200, "The Russian composer of the famous ballet scores for Swan Lake, The Sleeping Beauty, and The Nutcracker.", "Pyotr Ilyich Tchaikovsky", ["tchaikovsky"]),
        q(200, "The 1977 punk rock album by the Sex Pistols featuring 'God Save the Queen' and 'Anarchy in the U.K.'.", "Never Mind the Bollocks", ["never mind the bollocks, here's the sex pistols"]),
        q(200, "The jazz style developed in the 1940s characterized by fast tempos and complex chord progressions, pioneered by Charlie Parker.", "Bebop", ["bop"]),
        q(200, "The 1987 album by Michael Jackson that produced five consecutive Billboard Hot 100 number-one singles.", "Bad", ["bad album"]),
        q(200, "The brass instrument that uses a telescoping slide mechanism to alter pitch rather than valves.", "Trombone", ["slide trombone"]),
        q(200, "The Welsh rock band fronted by James Dean Bradfield known for 'A Design for Life'.", "Manic Street Preachers", ["manics"]),
        q(200, "The Italian opera composer of La Boheme, Tosca, and Madama Butterfly.", "Giacomo Puccini", ["puccini"]),
        q(200, "The 1994 Green Day punk rock breakthrough album featuring 'Basket Case' and 'When I Come Around'.", "Dookie", ["dookie album"]),
        q(200, "The legendary Memphis record label founded by Sam Phillips in 1952 that discovered Elvis Presley, Johnny Cash, and Carl Perkins.", "Sun Records", ["sun studio"]),
        q(200, "The term for singing without any instrumental accompaniment, Italian for 'in the style of the chapel'.", "A cappella", ["acappella"]),
        q(200, "The Polish-French Romantic composer and virtuoso pianist celebrated for his nocturnes, mazurkas, and polonaises.", "Frederic Chopin", ["chopin"]),
        q(200, "The 1984 concept album by Bruce Springsteen that sold 30 million copies worldwide featuring 'Dancing in the Dark'.", "Born in the U.S.A.", ["born in the usa"]),
        q(200, "The innovative electric bass pioneer of Weather Report who popularized harmonics and fretless bass on albums like Heavy Weather.", "Jaco Pastorius", ["pastorius"]),
        q(200, "The 1971 John Lennon anthem imagining a world without borders or religion.", "Imagine", ["imagine john lennon"]),
        q(200, "The female vocal range positioned below soprano and above contralto.", "Mezzo-soprano", ["mezzo"]),
        q(200, "The 1979 debut studio album by The Clash that included 'White Riot' and 'I Fought the Law'.", "The Clash", ["the clash debut"]),
        q(200, "The 1924 George Gershwin concert composition that brilliantly synthesized classical symphonic music with jazz elements.", "Rhapsody in Blue", ["rhapsody in blue"]),
        q(200, "The 1993 debut album by the Wu-Tang Clan subtitled 'Enter the Wu-Tang'.", "36 Chambers", ["enter the wu-tang 36 chambers"]),
        q(200, "The woodwind instrument made of brass with a single-reed mouthpiece, invented by Belgian Adolphe Sax in the 1840s.", "Saxophone", ["sax"]),
        q(200, "The 1980 AC/DC hard rock album recorded with new lead singer Brian Johnson following Bon Scott's death.", "Back in Black", ["back in black"]),
        q(200, "The term in music theory for a three-note chord consisting of a root, third, and fifth.", "Triad", ["major triad", "minor triad"])
    ]

    m_300 = [
        q(300, "The 1913 Igor Stravinsky avant-garde ballet whose Paris premiere at the Theatre des Champs-Elysees famously triggered a riot.", "The Rite of Spring", ["le sacre du printemps"]),
        q(300, "The legendary recording console and studio on Music Row in Nashville where Bob Dylan recorded Blonde on Blonde.", "Columbia Studio A", ["quonset hut studio"]),
        q(300, "The 1966 Beach Boys album masterminded by Brian Wilson that revolutionized studio recording with orchestral arrangements.", "Pet Sounds", ["pet sounds"]),
        q(300, "The German composer of The Ring of the Nibelung cycle, who built the Bayreuth Festspielhaus specifically for his operas.", "Richard Wagner", ["wagner"]),
        q(300, "The 1998 Lauryn Hill solo masterpiece that became the first hip hop album to win the Grammy Award for Album of the Year.", "The Miseducation of Lauryn Hill", ["miseducation of lauryn hill"]),
        q(300, "The medieval system of musical pitch organization consisting of Dorian, Phrygian, Lydian, and Mixolydian scales.", "Modes", ["church modes", "musical modes"]),
        q(300, "The 1977 Fleetwood Mac album recorded amidst internal romantic breakups that became one of the best-selling albums in history.", "Rumours", ["rumours"]),
        q(300, "The American composer of 4'33\", a three-movement composition in which musicians perform no sound at all for 4 minutes and 33 seconds.", "John Cage", ["cage"]),
        q(300, "The 1989 Beastie Boys album produced by the Dust Brothers renowned for its dense layering of hundreds of uncredited samples.", "Paul's Boutique", ["pauls boutique"]),
        q(300, "The Baroque musical form featuring a subject introduced in one voice and developed contrapuntally by other voices.", "Fugue", ["fuga"]),
        q(300, "The 1976 multi-platinum debut album by Boston that Tom Scholz recorded largely in his basement studio using equipment he built.", "Boston", ["boston debut"]),
        q(300, "The 1959 Ornette Coleman free jazz landmark album whose liner notes declared it was breaking all conventional bebop chord structures.", "The Shape of Jazz to Come", ["shape of jazz to come"]),
        q(300, "The 1983 New Order dance-rock single that became the best-selling 12-inch vinyl single of all time.", "Blue Monday", ["blue monday"]),
        q(300, "The 18th-century tuning system that divides an octave into twelve equal parts, championed by J.S. Bach.", "Equal temperament", ["12-tet"]),
        q(300, "The 1975 Bruce Springsteen album featuring 'Thunder Road' that saved his recording contract with Columbia Records.", "Born to Run", ["born to run"]),
        q(300, "The Finnish late-Romantic composer who wrote seven symphonies and the nationalistic tone poem Finlandia.", "Jean Sibelius", ["sibelius"]),
        q(300, "The 1994 debut album by Nas, universally hailed as one of the greatest lyrical hip-hop albums ever recorded.", "Illmatic", ["illmatic"]),
        q(300, "The Italian musical term indicating that a passage should be played with gradually increasing volume.", "Crescendo", ["crescendo"]),
        q(300, "The 1979 double concept album by The Clash that incorporated reggae, rockabilly, ska, and jazz, featuring an iconic Pennie Smith cover photo.", "London Calling", ["london calling"]),
        q(300, "The 19th-century Hungarian virtuoso pianist and composer who created the symphonic poem and provoked 'Lisztomania'.", "Franz Liszt", ["liszt"]),
        q(300, "The 1997 Radiohead album featuring 'Paranoid Android' that critiqued consumer alienation and 21st-century technological dread.", "OK Computer", ["ok computer"]),
        q(300, "The jazz saxophonist whose 1965 spiritual modal jazz suite was titled A Love Supreme.", "John Coltrane", ["coltrane", "trane"]),
        q(300, "The 1973 Stevie Wonder masterpiece album featuring 'Living for the City' and 'Higher Ground' that won Album of the Year.", "Innervisions", ["innervisions"]),
        q(300, "The Renaissance vocal music style written for small ensembles singing polyphonic secular poetry without accompaniment.", "Madrigal", ["madrigals"]),
        q(300, "The 1978 punk-new wave album by Blondie featuring the worldwide disco-crossover hit 'Heart of Glass'.", "Parallel Lines", ["parallel lines"]),
        q(300, "The Czech composer who integrated American folk songs into his 1893 Symphony No. 9 'From the New World'.", "Antonin Dvorak", ["dvorak"]),
        q(300, "The 1988 N.W.A album that pioneered West Coast gangsta rap and brought national scrutiny from the FBI.", "Straight Outta Compton", ["straight outta compton"]),
        q(300, "The curved line connecting two musical notes of the same pitch indicating they should be played as a single held note.", "Tie", ["musical tie"]),
        q(300, "The 1971 Marvin Gaye socially conscious concept album addressing the Vietnam War, ecology, and poverty.", "What's Going On", ["whats going on"]),
        q(300, "The Austrian composer who bridged late-Romanticism and modernism, known for monumental symphonies including the 'Symphony of a Thousand'.", "Gustav Mahler", ["mahler"]),
        q(300, "The 1991 shoegaze masterpiece album by My Bloody Valentine recorded by Kevin Shields over two agonizing years.", "Loveless", ["loveless album"]),
        q(300, "The American jazz bassist and composer who recorded the 1959 post-bop masterpiece Mingus Ah Um.", "Charles Mingus", ["mingus"]),
        q(300, "The 1980 post-punk album by Joy Division released two months after lead singer Ian Curtis's suicide.", "Closer", ["closer album"]),
        q(300, "The musical technique of playing notes in a detached, separated, and short manner, symbolized by a dot.", "Staccato", ["staccato"]),
        q(300, "The 1968 double album by The Beatles officially named The Beatles, but universally known by this monochromatic title.", "The White Album", ["white album"]),
        q(300, "The 20th-century French composer who created the Turangalila-Symphonie and transcribed bird songs into orchestral works.", "Olivier Messiaen", ["messiaen"]),
        q(300, "The 1996 double album by 2Pac released on Death Row Records, the first double-disc hip hop album in history.", "All Eyez on Me", ["all eyez on me"]),
        q(300, "The ancient Greek string instrument resembling a small harp, associated with the god Apollo and poetry.", "Lyre", ["kithara"]),
        q(300, "The 1978 art-punk album by Wire featuring 15 minimalist tracks that influenced post-punk and Britpop.", "Chairs Missing", ["pink flag"]),
        q(300, "The German composer of the Baroque era who wrote Water Music and Music for the Royal Fireworks for British royalty.", "George Frideric Handel", ["handel"])
    ]

    m_400 = [
        q(400, "The 1959 free jazz landmark recording by Ornette Coleman featuring Don Cherry playing a pocket trumpet.", "The Shape of Jazz to Come", ["shape of jazz to come"]),
        q(400, "The 1974 German electronic music landmark album by Kraftwerk whose title track spans the entire first side.", "Autobahn", ["autobahn album"]),
        q(400, "The Second Viennese School composer who developed the revolutionary twelve-tone serial technique in the 1920s.", "Arnold Schoenberg", ["schoenberg"]),
        q(400, "The 1967 garage rock single by The Kingsmen that was investigated by the FBI for over two years for allegedly obscene lyrics.", "Louie Louie", ["louie louie"]),
        q(400, "The 1976 minimalist opera composed by Philip Glass and directed by Robert Wilson consisting of four interconnected acts.", "Einstein on the Beach", ["einstein on the beach"]),
        q(400, "The legendary female blues singer of the 1920s known as the 'Empress of the Blues' who recorded 'Downhearted Blues'.", "Bessie Smith", ["smith"]),
        q(400, "The 1972 double album by The Rolling Stones recorded in the damp basement of the Villa Nellcote in southern France.", "Exile on Main St.", ["exile on main street"]),
        q(400, "The 14th-century French composer and poet who was the central figure of the Ars Nova musical style and composed the Messe de Nostre Dame.", "Guillaume de Machaut", ["machaut"]),
        q(400, "The 1985 post-hardcore album by Minutemen featuring 45 short songs across two vinyl records.", "Double Nickels on the Dime", ["double nickels on the dime"]),
        q(400, "The 20th-century Russian composer whose Symphony No. 5 in D minor was subtitled 'A Soviet Artist's Response to Just Criticism'.", "Dmitri Shostakovich", ["shostakovich"]),
        q(400, "The 1977 electronic ambient album by Brian Eno that marked the beginning of his four-part Ambient series.", "Ambient 1: Music for Airports", ["music for airports"]),
        q(400, "The 1938 jazz concert organized by John Hammond at Carnegie Hall that brought Black gospel, blues, and boogie-woogie to white audiences.", "From Spirituals to Swing", ["spirituals to swing"]),
        q(400, "The 1994 post-rock album by Bark Psychosis that led music critic Simon Reynolds to coin the term 'post-rock'.", "Hex", ["hex album"]),
        q(400, "The Italian Renaissance composer whose Missa Papae Marcelli was said to have saved polyphonic church music from being banned by the Council of Trent.", "Giovanni Pierluigi da Palestrina", ["palestrina"]),
        q(400, "The 1980 English post-punk single by Bauhaus featuring a descending bassline that is widely recognized as the foundation of gothic rock.", "Bela Lugosi's Dead", ["bela lugosi is dead"]),
        q(400, "The early electronic musical instrument invented in 1928 by Maurice Martenot, played with a ring on a wire.", "Ondes Martenot", ["ondes"]),
        q(400, "The 1971 acoustic folk masterpiece album by Joni Mitchell featuring 'A Case of You' and 'Carey'.", "Blue", ["blue joni mitchell"]),
        q(400, "The 18th-century Italian composer and violin virtuoso who wrote the 'Devil's Trill Sonata' after claiming the Devil played it to him in a dream.", "Giuseppe Tartini", ["tartini"]),
        q(400, "The 1969 debut studio album by Captain Beefheart & His Magic Band, masterminded under eccentric seclusion in Woodland Hills.", "Trout Mask Replica", ["trout mask replica"]),
        q(400, "The 20th-century Austrian composer of Wozzeck and Lulu who combined late-Romantic lyricism with Schoenberg's twelve-tone technique.", "Alban Berg", ["berg"]),
        q(400, "The 1981 hardcore punk compilation album released by Dischord Records that defined the Washington D.C. straight-edge scene.", "Flex Your Head", ["flex your head"]),
        q(400, "The microtonal musical instrument invented by Harry Partch consisting of 44 brass strings tuned to a 43-tone equal temperament scale.", "Kithara", ["harmonic canon", "chromelodeon"]),
        q(400, "The 1973 German krautrock album by Faust that Virgin Records sold for the price of a single (48 pence) to build a fanbase.", "The Faust Tapes", ["faust tapes"]),
        q(400, "The late Renaissance Italian composer and Prince of Venosa notorious for murdering his adulterous wife and writing chromatic madrigals.", "Carlo Gesualdo", ["gesualdo"]),
        q(400, "The 1991 dub-techno album by Basic Channel that pioneered the Berlin minimal techno sound.", "Basic Channel", ["cybersonik"]),
        q(400, "The Polish avant-garde composer of Threnody to the Victims of Hiroshima (1960) utilizing 52 string instruments with extended techniques.", "Krzysztof Penderecki", ["penderecki"]),
        q(400, "The 1965 jazz record by Albert Ayler featuring brother Donald on trumpet that pioneered extreme free improvisation.", "Spiritual Unity", ["spiritual unity"]),
        q(400, "The German Baroque organist and composer whose Canon in D major has become one of the most frequently played wedding processionals.", "Johann Pachelbel", ["pachelbel"]),
        q(400, "The 1977 British punk single by The Damned that was the first UK punk single ever released, beating the Sex Pistols.", "New Rose", ["new rose"]),
        q(400, "The French composer who coined the term 'Musique concrete' in 1948 for electronic music constructed from recorded raw environmental sounds.", "Pierre Schaeffer", ["schaeffer"]),
        q(400, "The 1982 noise rock album by Swans recorded at basement decibels in New York City.", "Filth", ["swans filth"]),
        q(400, "The 17th-century English composer of the opera Dido and Aeneas and the incidental music to Abdelazer.", "Henry Purcell", ["purcell"]),
        q(400, "The 1969 experimental jazz-fusion double album by Miles Davis that abandoned traditional swing for funk rhythms and electric keyboards.", "Bitches Brew", ["bitches brew"]),
        q(400, "The medieval musical notation system of marks placed above text syllables to indicate pitch contour before modern staves.", "Neumes", ["neume"]),
        q(400, "The 1983 alternative rock album by R.E.M. recorded at Reflection Sound Studios with producer Mitch Easter that launched jangle pop.", "Murmur", ["murmur r.e.m."]),
        q(400, "The 20th-century American avant-garde composer of the string quartet Black Angels (1970) scored for electric string quartet and water glasses.", "George Crumb", ["crumb"]),
        q(400, "The 1974 funk album by Parliament featuring 'Up for the Down Stroke' that established the P-Funk mythology.", "Up for the Down Stroke", ["up for the down stroke"]),
        q(400, "The Renaissance French composer widely regarded as the central master of Franco-Flemish polyphony, known as the 'Prince of Music'.", "Josquin des Prez", ["josquin"]),
        q(400, "The 1992 UK jungle/drum-and-bass track by A Guy Called Gerald that helped define the early breakbeat hardcore sound.", "28 Gun Bad Boy", ["voodoo ray"]),
        q(400, "The French Impressionist composer of Pelleas et Melisande and Prelude to the Afternoon of a Faun.", "Claude Debussy", ["debussy"])
    ]

    m_500 = [
        q(500, "The 1952 composition by Karlheinz Stockhausen that was the first electronic music piece synthesized entirely from pure sine wave generators.", "Studie I", ["studie ii", "elektronische studien"]),
        q(500, "The 1570 forty-voice Renaissance motet composed by English composer Thomas Tallis for eight choirs of five voices each.", "Spem in alium", ["spem in alium nunquam habui"]),
        q(500, "The 1967 avant-garde free jazz album by Peter Brotzmann featuring an eight-piece European ensemble noted for unprecedented acoustic fury.", "Machine Gun", ["machine gun"]),
        q(500, "The ancient Hurrian Hymn to Nikkal, inscribed on cuneiform clay tablets excavated at Ugarit, Syria, dating to 1400 BC, is the oldest known this.", "Complete musical melody", ["hurrian hymn", "oldest melody"]),
        q(500, "The 1975 microtonal piano masterpiece composed by La Monte Young spanning over six hours, played on an imperial Bosendorfer in just intonation.", "The Well-Tuned Piano", ["well-tuned piano"]),
        q(500, "The 14th-century rhythmic polyphonic technique in Ars Nova motets where a repeating rhythmic pattern (talea) interacts with a melodic pattern (color).", "Isorhythm", ["isorhythmic"]),
        q(500, "The 1960 Romanian-French spectralist composer who founded the Ensemble l'Itineraire and analyzed acoustic sound spectra with computers.", "Gerard Grisey", ["grisey", "spectral music"]),
        q(500, "The 1981 industrial/power-electronics album by Whitehouse that established the extreme British power electronics subgenre.", "Dedicated to Peter Kurten", ["buchenwald"]),
        q(500, "The 16th-century Italian composer and theorist who published L'antica musica ridotta alla moderna prattica in 1555 and built the 31-tone archicembalo.", "Nicola Vicentino", ["vicentino"]),
        q(500, "The 1958 composition for 58 solo strings by Iannis Xenakis that was the first to use stochastic mathematical probability in music.", "Pithoprakta", ["xenakis stochastic"]),
        q(500, "The 1970 private-press British acid folk album by Mark Fry recorded in Italy, which became one of the most sought-after psych-folk rarities.", "Dreaming with Alice", ["dreaming with alice"]),
        q(500, "The 12th-century German Benedictine abbess, mystic, and composer of the liturgical drama Ordo Virtutum and 77 sacred chants.", "Hildegard of Bingen", ["hildegard von bingen"]),
        q(500, "The 1979 Japanese synth-pop landmark album by Yellow Magic Orchestra featuring 'Rydeen' that pioneered video game and chiptune sounds.", "Solid State Survivor", ["solid state survivor"]),
        q(500, "The Russian composer who developed the 'mystic chord' (C-F#-Bb-E-A-D) and designed the synesthetic multi-sensory work Mysterium.", "Alexander Scriabin", ["scriabin"]),
        q(500, "The 1968 piece by Alvin Lucier where a spoken text is played into a room, re-recorded, and played back until resonant frequencies destroy the words.", "I Am Sitting in a Room", ["alvin lucier"]),
        q(500, "The French troubadour of the 12th century who was Duke of Aquitaine and is recognized as the earliest recorded troubadour lyric poet.", "William IX of Aquitaine", ["guillaume ix"]),
        q(500, "The 1984 Japanese ambient environmental masterpiece album by Hiroshi Yoshimura released as part of the Soundscape series.", "Green", ["music for nine post cards", "yoshimura"]),
        q(500, "The 17th-century German organist and composer in Lubeck whose Abendmusiken concerts were so famous that J.S. Bach walked 250 miles to hear him.", "Dieterich Buxtehude", ["buxtehude"]),
        q(500, "The 1971 free improvisation guitar recording by Derek Bailey, Han Bennink, and Evan Parker that established the Incus Records label.", "The Topography of the Lungs", ["topography of the lungs"]),
        q(500, "The 15th-century Franco-Flemish composer who wrote the Missa prolationum, completely constructed of simultaneous mensuration canons.", "Johannes Ockeghem", ["ockeghem"]),
        q(500, "The 1968 electronic composition by Morton Subotnick composed on the Buchla 100 modular synthesizer, the first electronic piece commissioned by a record label.", "Silver Apples of the Moon", ["silver apples of the moon"]),
        q(500, "The 16th-century Spanish blind composer and organist at the court of Philip II who wrote the Obras de musica.", "Antonio de Cabezon", ["cabezon"]),
        q(500, "The 1986 Japanese experimental noise album by Merzbow released as part of the Pornoise series.", "Batztoutai with Material Gadgets", ["merzbow"]),
        q(500, "The 11th-century Italian Benedictine monk who invented modern four-line staff musical notation and the solfege syllables Ut-Re-Mi-Fa-Sol-La.", "Guido of Arezzo", ["guido d'arezzo"]),
        q(500, "The 1972 private press cosmic jazz album by The Pyramids recorded after traveling across Africa to study traditional drumming.", "Lalibela", ["the pyramids lalibela"]),
        q(500, "The 18th-century French composer who wrote the Traite de l'harmonie in 1722, establishing modern harmonic theory and fundamental bass.", "Jean-Philippe Rameau", ["rameau"]),
        q(500, "The 1969 British progressive rock album by Comus featuring acoustic guitars, violins, and dark pagan imagery.", "First Utterance", ["comus"]),
        q(500, "The 13th-century Spanish compilation of 420 poems with musical notation in honor of the Virgin Mary, commissioned by King Alfonso X of Castile.", "Cantigas de Santa Maria", ["cantigas"]),
        q(500, "The 1974 private-press ambient minimalist album by Franco Battiato exploring repetitive synthesizer loops, titled Clic.", "Clic", ["franco battiato"]),
        q(500, "The Renaissance Venetian composer who developed the polychoral style (cori spezzati) at St. Mark's Basilica.", "Giovanni Gabrieli", ["gabrieli"]),
        q(500, "The 1980 New York No Wave compilation produced by Brian Eno that documented DNA, The Contortions, Mars, and Teenage Jesus and the Jerks.", "No New York", ["no new york"]),
        q(500, "The 16th-century Italian court composer and lutenist who wrote the lute tutorial Il Fronimo in 1568 and was the father of astronomer Galileo.", "Vincenzo Galilei", ["vincenzo galilei"]),
        q(500, "The 1967 British psychedelic underground compilation by The Deviants featuring Mick Farren, titled Ptooff!.", "Ptooff!", ["ptooff"]),
        q(500, "The late 14th-century complex, highly mannered musical style in southern France and northern Italy characterized by extreme rhythmic complexity.", "Ars subtilior", ["more subtle art"]),
        q(500, "The 1978 electro-acoustic composition by Bernard Parmegiani consisting of 12 movements exploring the transformation of sounds.", "De Natura Sonorum", ["parmegiani"]),
        q(500, "The 17th-century Italian castrato and composer of the nine-voice Miserere mei, Deus, which was forbidden to be copied outside the Sistine Chapel.", "Gregorio Allegri", ["allegri"]),
        q(500, "The 1974 American private press spiritual jazz album by Phil Cohran and the Artistic Heritage Ensemble.", "The Malcolm X Memorial", ["phil cohran"]),
        q(500, "The 15th-century English composer whose cyclic masses based on the Caput melisma influenced continental composers Dufay and Ockeghem.", "John Dunstable", ["dunstable", "dunstaple"]),
        q(500, "The 1981 tape-loop experimental album by Nurse with Wound and Whitehouse collaborator Steven Stapleton, titled Insect and Individual Silenced.", "Insect and Individual Silenced", ["nurse with wound"]),
        q(500, "The 17th-century French court composer to Louis XIV who dominated French Baroque opera and died of gangrene after striking his own foot with his conducting staff.", "Jean-Baptiste Lully", ["lully"])
    ]

    return m_100 + m_200 + m_300 + m_400 + m_500

if __name__ == "__main__":
    data = get_music_data()
    print(f"Music generated: {len(data)} clues")
