# -*- coding: utf-8 -*-
"""Nature & Wildlife Category - 200 Real Clues"""

def get_nature_data():
    def q(val, clue, ans, acc=None, src="Wikipedia - Zoology"):
        return {"value": val, "clue": clue, "answer": ans, "accepted": acc or [], "source": src}

    n_100 = [
        q(100, "The largest living mammal on Earth, whose heart alone can weigh as much as an automobile.", "Blue whale", ["balaenoptera musculus"]),
        q(100, "The fastest land animal on Earth, capable of accelerating from 0 to 60 mph in three seconds.", "Cheetah", ["acinonyx jubatus"]),
        q(100, "The eucalyptus-eating marsupial native to eastern Australia whose fingerprints are nearly identical to humans'.", "Koala", ["koala bear"]),
        q(100, "The black-and-white flightless seabird native to Antarctica that withstands freezing temperatures in colonies.", "Penguin", ["emperor penguin"]),
        q(100, "The only mammals capable of true, sustained flight through flapping wings.", "Bats", ["bat", "chiroptera"]),
        q(100, "The tallest living terrestrial animal, characterized by an exceptionally long neck and legs.", "Giraffe", ["giraffa"]),
        q(100, "The large black-and-white bear native to south-central China that subsists almost entirely on bamboo.", "Giant panda", ["panda bear", "panda"]),
        q(100, "The marine mammal known for playful acrobatics, complex clicks, and high intelligence.", "Dolphin", ["bottlenose dolphin"]),
        q(100, "The large apex predator cat native to the Americas, recognizable by its spotted coat with rosettes.", "Jaguar", ["panthera onca"]),
        q(100, "The tiny bird capable of flying backward and hovering in mid-air by beating its wings up to 80 times per second.", "Hummingbird", ["trochilidae"]),
        q(100, "The cold-blooded marine reptile with a hard bony shell that navigates back to natal beaches to lay eggs.", "Sea turtle", ["cheloniidae"]),
        q(100, "The largest living species of tortoise, native to an isolated archipelago in the Pacific Ocean.", "Galapagos tortoise", ["chelonoidis niger"]),
        q(100, "The carnivorous marine cephalopod with eight arms, two tentacles, and an ink sac.", "Squid", ["giant squid"]),
        q(100, "The nocturnal bird of prey known for silent flight and the ability to rotate its head up to 270 degrees.", "Owl", ["strigiformes"]),
        q(100, "The semi-aquatic Australian mammal with a duck-like bill, beaver-like tail, and venomous ankle spurs.", "Platypus", ["duck-billed platypus"]),
        q(100, "The large herbivorous mammal with one or two keratin horns on its snout, heavily poached for its horn.", "Rhinoceros", ["rhino"]),
        q(100, "The social insect that lives in highly organized colonies with a queen, drones, and workers that produce honey.", "Honeybee", ["bee", "apis mellifera"]),
        q(100, "The orange-and-black migratory butterfly famous for its multi-generational journey between Canada and Mexico.", "Monarch butterfly", ["danaus plexippus"]),
        q(100, "The largest living species of cat, recognizable by its reddish-orange coat with dark vertical stripes.", "Tiger", ["panthera tigris"]),
        q(100, "The flightless bird native to Australia that is the second-tallest living bird after the ostrich.", "Emu", ["dromaius novaehollandiae"]),
        q(100, "The ocean predator known for multiple rows of teeth and keen electroreception via ampullae of Lorenzini.", "Shark", ["great white shark"]),
        q(100, "The slow-moving South American arboreal mammal known for spending its life hanging upside down in trees.", "Sloth", ["three-toed sloth"]),
        q(100, "The Australian marsupial with powerful hind legs, large feet, and a pouch for carrying joeys.", "Kangaroo", ["red kangaroo"]),
        q(100, "The apex predator of the Arctic sea ice that feeds primarily on ringed and bearded seals.", "Polar bear", ["ursus maritimus"]),
        q(100, "The colorful tropical bird known for its extraordinarily large and brightly colored bill.", "Toucan", ["ramphastidae"]),
        q(100, "The semi-aquatic mammal native to North America and Eurasia famous for constructing wooden dams and lodges.", "Beaver", ["castor"]),
        q(100, "The small rodent known for gathering and caching nuts for winter, possessing a bushy tail.", "Squirrel", ["sciuridae"]),
        q(100, "The sea mammal often called a 'sea cow' that grazes on shallow seagrass beds in warm coastal waters.", "Manatee", ["trichechus"]),
        q(100, "The large predatory bird of prey that serves as the national bird and symbol of the United States.", "Bald eagle", ["haliaeetus leucocephalus"]),
        q(100, "The armored mammal native to the Americas covered in bony plates, known for rolling into a ball.", "Armadillo", ["dasypodidae"]),
        q(100, "The bioluminescent winged beetle that uses enzymatic chemical light flashes to attract mates at dusk.", "Firefly", ["lightning bug", "lampyridae"]),
        q(100, "The small marine fish where the male carries eggs in a specialized brood pouch until birth.", "Seahorse", ["hippocampus"]),
        q(100, "The large wild dog native to Australia with a reddish-sandy coat that howls rather than barks.", "Dingo", ["canis dingo"]),
        q(100, "The pink wading bird that gets its vibrant plumage coloration from carotenoids in the crustaceans it eats.", "Flamingo", ["phoenicopteridae"]),
        q(100, "The prickly rodent covered in sharp defensive quills that detach easily upon contact with predators.", "Porcupine", ["hystricidae"]),
        q(100, "The large marine mammal with elongated upper canine teeth forming long ivory tusks.", "Walrus", ["odobenus rosmarus"]),
        q(100, "The aquatic amphibian with a long tail and four limbs that can regenerate lost limbs and organs.", "Axolotl", ["mexican walking fish", "salamander"]),
        q(100, "The venomous arachnid with eight legs and a pair of pincers, famous for a curled tail with a stinger.", "Scorpion", ["scorpiones"]),
        q(100, "The bird of prey that dives at speeds exceeding 200 mph to strike quarry, the fastest animal on Earth.", "Peregrine falcon", ["falco peregrinus"]),
        q(100, "The striped African equine mammal whose black-and-white pattern dazzles biting flies and predators.", "Zebra", ["equus quagga"])
    ]

    n_200 = [
        q(200, "The ocean mollusk with eight sucker-lined arms, blue copper-based blood, and three pumping hearts.", "Octopus", ["octopoda"]),
        q(200, "The largest living reptile on Earth, native to saltwater habitats and river deltas in Southeast Asia and northern Australia.", "Saltwater crocodile", ["crocodylus porosus"]),
        q(200, "The carnivorous plant native to the wetlands of North and South Carolina that snaps shut on insects.", "Venus flytrap", ["dionaea muscipula"]),
        q(200, "The micro-animal also known as the 'water bear' that can survive extreme radiation, freezing, and the vacuum of space.", "Tardigrade", ["water bear"]),
        q(200, "The world's largest living bird, native to Africa, capable of sprinting at speeds over 40 mph.", "Ostrich", ["struthio camelus"]),
        q(200, "The predatory cetacean also known as the killer whale, the largest member of the oceanic dolphin family.", "Orca", ["orcinus orca"]),
        q(200, "The Australian marsupial known for dropping cubic feces due to specialized intestinal contractions.", "Wombat", ["vombatidae"]),
        q(200, "The nocturnal Madagascar lemur with rodent-like teeth and an elongated middle finger used for tapping tree trunks.", "Aye-aye", ["daubentonia madagascariensis"]),
        q(200, "The world's heaviest living bony fish, with an unusual flattened oval shape and prominent dorsal and anal fins.", "Ocean sunfish", ["mola mola"]),
        q(200, "The social African mammal of the mongoose family that stands upright on its hind legs as a lookout.", "Meerkat", ["suricata suricatta"]),
        q(200, "The predatory cat native to the high mountain ranges of Central and South Asia, camouflaged by thick smoky-gray fur.", "Snow leopard", ["panthera uncia"]),
        q(200, "The large flightless parrot endemic to New Zealand that is nocturnal and critically endangered.", "Kakapo", ["strigops habroptilus"]),
        q(200, "The largest species of deer in the world, recognizable by the broad palmate antlers grown by males.", "Moose", ["alces alces", "elk"]),
        q(200, "The marine mammal of the Arctic with a long, spiraled tusk that is actually an elongated canine tooth.", "Narwhal", ["monodon monoceros"]),
        q(200, "The tree-dwelling Old World lizard known for its independently mobile eyes, prehensile tail, and color-changing skin.", "Chameleon", ["chamaeleonidae"]),
        q(200, "The critically endangered marine porpoise endemic to the northern Gulf of California, the rarest marine mammal.", "Vaquita", ["phocoena sinus"]),
        q(200, "The predatory freshwater fish of South America with powerful jaws and razor-sharp interlocking teeth.", "Piranha", ["serrasalmidae"]),
        q(200, "The mammal completely covered in large, protective keratin scales that curls into a tight ball when threatened.", "Pangolin", ["scaly anteater", "manidae"]),
        q(200, "The poisonous amphibian native to Central and South America whose bright skin secretions were used by indigenous hunters.", "Poison dart frog", ["dendrobatidae"]),
        q(200, "The massive Arctic pinniped that can dive to depths of 1,000 meters and spends months at sea hunting squid.", "Elephant seal", ["mirounga"]),
        q(200, "The Australian bird capable of imitating almost any sound, including chainsaws, car alarms, and camera shutters.", "Lyrebird", ["superb lyrebird"]),
        q(200, "The largest species of lizard on Earth, endemic to several Indonesian islands in the Lesser Sundas.", "Komodo dragon", ["varanus komodoensis"]),
        q(200, "The marine invertebrate whose hard calcium carbonate exoskeleton builds massive undersea barrier reefs.", "Coral polyp", ["coral", "stony coral"]),
        q(200, "The African mammal related to the giraffe with zebra-like striped hindquarters and a long dark tongue.", "Okapi", ["okapia johnstoni"]),
        q(200, "The semi-aquatic South American rodent that is the largest living rodent species on Earth.", "Capybara", ["hydrochoerus hydrochaeris"]),
        q(200, "The bird of the southern oceans with the longest wingspan of any living bird, exceeding 11 feet.", "Wandering albatross", ["diomedea exulans"]),
        q(200, "The desert canine with extraordinarily large ears that radiate heat to regulate body temperature in the Sahara.", "Fennec fox", ["vulpes zerda"]),
        q(200, "The bioluminescent jellyfish whose green fluorescent protein (GFP) won its discoverers the 2008 Nobel Prize.", "Aequorea victoria", ["crystal jelly"]),
        q(200, "The semi-fossorial burrowing animal native to sub-Saharan Africa with a long snout used to eat ants and termites.", "Aardvark", ["orycteropus afer"]),
        q(200, "The large predatory shark species easily recognized by the laterally expanded hammer-like lobes of its head.", "Hammerhead shark", ["sphyrnidae"]),
        q(200, "The marine mammal of the North Pacific that uses rocks as tools to crack open sea urchins and mollusks while floating.", "Sea otter", ["enhydra lutris"]),
        q(200, "The venomous snake native to central and eastern Australia possessing the most toxic venom of any land reptile.", "Inland taipan", ["oxyuranus microlepidotus"]),
        q(200, "The blind subterranean salamander native to underwater limestone caves in the Dinaric Alps of Europe.", "Olm", ["proteus anguinus"]),
        q(200, "The flightless aquatic bird that lives exclusively on the Galapagos Islands and dries its stunted wings in the sun.", "Flightless cormorant", ["phalacrocorax harrisi"]),
        q(200, "The venomous Australian cephalopod characterized by glowing blue rings that appear when agitated.", "Blue-ringed octopus", ["hapalochlaena"]),
        q(200, "The North American marsupial famous for playing dead ('playing possum') when confronted by predators.", "Virginia opossum", ["didelphis virginiana"]),
        q(200, "The small marine crustacean whose claw snap produces a cavitation bubble hotter than the surface of the Sun.", "Pistol shrimp", ["snapping shrimp", "alpheidae"]),
        q(200, "The African scavenger mammal with immensely powerful bone-crushing jaws that lives in matriarchal clans.", "Spotted hyena", ["crocuta crocuta"]),
        q(200, "The marine mammal that migrates over 10,000 miles round-trip between Arctic feeding grounds and Mexican lagoons.", "Gray whale", ["eschrichtius robustus"]),
        q(200, "The flightless bird endemic to New Zealand with nostrils located at the tip of its long bill.", "Kiwi", ["apteryx"])
    ]

    n_300 = [
        q(300, "The egg-laying mammals belonging to the order Monotremata include the platypus and four species of this spiny creature.", "Echidna", ["spiny anteater", "tachyglossidae"]),
        q(300, "The marine cnidarian often called the 'immortal jellyfish' because it can revert from medusa back to polyp stage.", "Turritopsis dohrnii", ["immortal jellyfish"]),
        q(300, "The Australian lizard with a defensive neck frill that unfurls to frighten predators while hissing loudly.", "Frilled-neck lizard", ["chlamydosaurus kingii"]),
        q(300, "The deep-sea anglerfish where tiny dwarf males fuse their circulatory systems permanently to the female's body.", "Sexual parasitism", ["parasitic male", "anglerfish"]),
        q(300, "The nocturnal tree-dwelling marsupial of Australia that glides from tree to tree using a membrane called a patagium.", "Sugar glider", ["petaurus breviceps"]),
        q(300, "The solitary feline native to the Americas that holds the Guinness record for the animal with the highest number of common names.", "Cougar", ["mountain lion", "puma", "panther"]),
        q(300, "The marine flatfish that begins life swimming upright with eyes on both sides before one eye migrates across its skull.", "Flounder", ["halibut", "pleuronectiformes"]),
        q(300, "The Southeast Asian mammal that uses its specialized prehensile tail as a fifth limb, also called the 'bearcat'.", "Binturong", ["arctictis binturong"]),
        q(300, "The social mammal native to sub-Saharan Africa that hunts in packs with an exceptional hunting success rate near 80%.", "African wild dog", ["lycaon pictus", "painted dog"]),
        q(300, "The ancient marine arthropod whose blue, copper-rich amoebocyte blood is harvested to test pharmaceuticals for endotoxins.", "Horseshoe crab", ["limulus polyphemus"]),
        q(300, "The New Zealand reptile that is the sole surviving member of the ancient order Rhynchocephalia, possessing a third parietal eye.", "Tuatara", ["sphenodon punctatus"]),
        q(300, "The microscopic freshwater rotifers that have reproduced exclusively via parthenogenesis without males for 40 million years.", "Bdelloid rotifers", ["bdelloidea"]),
        q(300, "The deep-sea cephalopod with massive eyes up to 10 inches across and rotating hooks on its tentacles.", "Colossal squid", ["mesonychoteuthis hamiltoni"]),
        q(300, "The Australian marsupial that went extinct on the mainland and whose last known captive individual died in Hobart Zoo in 1936.", "Thylacine", ["tasmanian tiger", "tasmanian wolf"]),
        q(300, "The bird of paradise known for its elaborate black-and-neon-blue shape-shifting courtship dance.", "Vogelkop superb bird-of-paradise", ["superb bird of paradise"]),
        q(300, "The tropical tree species with prop roots and pneumatophores that protects tropical coastlines from storm surges.", "Mangrove", ["rhizophora"]),
        q(300, "The flightless giant bird native to New Zealand hunted to extinction by the Maori around 1440 AD.", "Moa", ["dinornithiformes"]),
        q(300, "The deep-sea fish that lives at depths of 8,000 meters in the Mariana Trench, the deepest recorded living fish.", "Mariana snailfish", ["pseudoliparis swirei"]),
        q(300, "The marine gastropod mollusk also known as the 'blue dragon' that floats upside down and consumes Portuguese man o' war.", "Glaucus atlanticus", ["blue angel", "sea swallow"]),
        q(300, "The parasitic fungus that infects carpenter ants, hijacking their central nervous systems to climb vegetation before fruiting.", "Ophiocordyceps unilateralis", ["cordyceps", "zombie ant fungus"]),
        q(300, "The deep-sea crustacean with an extraordinarily powerful claw that produces a cavitation flash of light (sonoluminescence).", "Alpheus", ["pistol shrimp"]),
        q(300, "The African antelope that engages in 'pronking', bounding high into the air with an arched back when alarmed.", "Springbok", ["antidorcas marsupialis"]),
        q(300, "The parasitic flatworm that uses freshwater snails and humans as hosts, causing the debilitating disease schistosomiasis.", "Schistosoma", ["blood fluke"]),
        q(300, "The marine mammal of the Bering Sea discovered in 1741 and hunted to complete extinction within just 27 years.", "Steller's sea cow", ["hydrodamalis gigas"]),
        q(300, "The venomous Australian jellyfish with cuboidal medusae whose venom can cause cardiac arrest within minutes.", "Box jellyfish", ["chironex fleckeri"]),
        q(300, "The social insect whose soldier caste defends the colony by violently rupturing their own abdomens, spraying sticky toxic secretions.", "Exploding ant", ["colobopsis explodens"]),
        q(300, "The South American freshwater fish that can generate electric discharges of over 800 volts using three abdominal electric organs.", "Electric eel", ["electrophorus electricus"]),
        q(300, "The marine mammal that forms 'superpods' of thousands of individuals and uses cooperative bubble-net feeding.", "Humpback whale", ["megaptera novaeangliae"]),
        q(300, "The Indonesian island bird known for incubating its eggs in burrows using geothermal volcanic heat rather than body heat.", "Maleo", ["macrocephalon maleo"]),
        q(300, "The mammal that sleeps with only one cerebral hemisphere at a time while keeping one eye open, known as unihemispheric sleep.", "Dolphin", ["cetaceans", "whales"]),
        q(300, "The flightless extinct pigeon endemic to the island of Mauritius that was wiped out by sailors and invasive animals in the 17th century.", "Dodo", ["raphus cucullatus"]),
        q(300, "The marine iguana of the Galapagos Islands that is unique among modern lizards for feeding on this marine substance.", "Algae", ["seaweed", "marine algae"]),
        q(300, "The Madagascar tree that stores thousands of liters of water in its massive swollen trunk to survive seasonal droughts.", "Baobab", ["adansonia"]),
        q(300, "The Australian marsupial carnivore with the strongest bite relative to body size of any living mammalian carnivore.", "Tasmanian devil", ["sarcophilus harrisii"]),
        q(300, "The colonial marine organism belonging to the order Siphonophorae consisting of specialized individual zooids that is often mistaken for a jellyfish.", "Portuguese man o' war", ["physalia physalis"]),
        q(300, "The desert plant of the Namib Desert consisting of only two leaves that grow continuously from a basal meristem throughout its 1,000-year life.", "Welwitschia", ["welwitschia mirabilis"]),
        q(300, "The deep-sea siphonophore that can reach lengths of over 40 meters, making it one of the longest organisms on Earth.", "Apolemia", ["giant siphonophore"]),
        q(300, "The European bird that lays its eggs in the nests of other bird species (brood parasitism), famous for its call.", "Common cuckoo", ["cuculus canorus"]),
        q(300, "The large North American rodent that constructs lodges with underwater entrances and creates extensive wetland habitats.", "North American beaver", ["castor canadensis"]),
        q(300, "The parasitic plant native to Southeast Asia that produces the largest individual flower on Earth, smelling of rotting meat.", "Rafflesia arnoldii", ["corpse flower", "monster flower"])
    ]

    n_400 = [
        q(400, "The deep-sea anglerfish utilizes this biological light-emitting process powered by symbiotic bioluminescent bacteria in its esca.", "Bioluminescence", ["symbiotic bioluminescence"]),
        q(400, "The predatory marine snail that shoots a venomous barbed harpoon loaded with hundreds of conotoxins to paralyze fish.", "Cone snail", ["conus"]),
        q(400, "The ant species that raids other ant nests, stealing pupae to raise them as specialized slave workers in its own colony.", "Slave-making ant", ["polyergus", "dulosis"]),
        q(400, "The flightless Australian cassowary possesses a sharp dagger-like claw on this specific inner toe measuring up to 12 centimeters.", "Second toe", ["inner toe", "digit ii"]),
        q(400, "The freshwater cnidarian that does not undergo senescence and has been described as biologically immortal.", "Hydra", ["hydra vulgaris"]),
        q(400, "The unique sensory organ found in pit vipers between the eye and nostril that detects infrared thermal radiation from warm-blooded prey.", "Pit organ", ["loreal pit"]),
        q(400, "The South American frog species where the male swallows fertilized eggs into his vocal sac, where tadpoles develop until leaping out of his mouth.", "Darwin's frog", ["rhinoderma darwinii"]),
        q(400, "The marine worm that lives at deep-sea hydrothermal vents up to 400 degrees Celsius, possessing no mouth or gut, sustained by chemosynthetic bacteria.", "Giant tube worm", ["riftia pachyptila"]),
        q(400, "The insect order containing beetles that comprises roughly 40% of all described insect species on Earth.", "Coleoptera", ["beetles"]),
        q(400, "The marine mammal of the North Pacific whose males have teeth shaped like giant tusks protruding outside their lips to fight for mates.", "Beaked whale", ["strap-toothed whale", "mesoplodon"]),
        q(400, "The Australian marsupial mole that spends almost its entire life underground in desert sand dunes, possessing vestigial lens-less eyes.", "Marsupial mole", ["notoryctes"]),
        q(400, "The deep-sea cephalopod that can invert its webbed arms to form a spiny umbrella-like cloak when threatened, producing glowing mucus.", "Vampire squid", ["vampyroteuthis infernalis"]),
        q(400, "The African ant that conducts nomadic predatory swarm raids involving millions of individuals, having no permanent stationary nest.", "Driver ant", ["dorylus", "safari ant"]),
        q(400, "The venomous lizard native to the southwestern United States and northwestern Mexico that stores fat in its tail.", "Gila monster", ["heloderma suspectum"]),
        q(400, "The marine teleost fish with transparent skull tissue through which its upward-pointing tubular green eyes rotate.", "Barreleye", ["macropinna microstoma"]),
        q(400, "The subterranean rodent that lives in eusocial colonies with a single breeding queen and sterile workers in East Africa, resistant to cancer.", "Naked mole-rat", ["heterocephalus glaber"]),
        q(400, "The predatory insect that turns its head 180 degrees and is famous for occasional sexual cannibalism of the male by the female.", "Praying mantis", ["mantodea"]),
        q(400, "The marine polychaete worm known as the 'Christmas tree worm' that lives anchored in live stony coral heads, displaying twin spiral plumes.", "Spirobranchus giganteus", ["christmas tree worm"]),
        q(400, "The flightless giant New Zealand rail bird that was believed extinct for 50 years until its rediscovery in the Murchison Mountains in 1948.", "Takahe", ["porphyrio hochstetteri"]),
        q(400, "The small marine mollusk that incorporates photosynthetic chloroplasts from the algae it eats into its own cells, performing photosynthesis.", "Elysia chlorotica", ["solar-powered sea slug"]),
        q(400, "The African mammal that secretes a reddish-orange oily fluid commonly referred to as 'blood sweat' that acts as sunscreen and antiseptic.", "Hippopotamus", ["hippopotamus amphibius"]),
        q(400, "The North American bird that caches up to 30,000 seeds every autumn across hundreds of square miles and recalls 90% of their locations.", "Clark's nutcracker", ["nucifraga columbiana"]),
        q(400, "The deep-sea xenophyophore that is a single-celled multinucleate protozoan reaching sizes of up to 20 centimeters in the Mariana Trench.", "Xenophyophore", ["syringammina fragilissima"]),
        q(400, "The Southeast Asian primate that possesses specialized elongated ankle bones allowing it to leap 40 times its body length.", "Tarsier", ["tarsiidae"]),
        q(400, "The Australian plant whose seed capsules only open to release seeds following exposure to extreme wildfire heat, known as serotiny.", "Banksia", ["banksia seed cone"]),
        q(400, "The marine mammal of the Southern Ocean that feeds on krill by filtering seawater through specially notched interlocking teeth.", "Crabeater seal", ["lobodon carcinophaga"]),
        q(400, "The small South American frog that carries its developing tadpoles on its back inside subcutaneous pockets under its skin until they emerge as froglets.", "Surinam toad", ["pipa pipa"]),
        q(400, "The bird of the Sahara Desert whose males fly miles to watering holes to soak their modified breast feathers to carry water to chicks.", "Sandgrouse", ["pteroclidae"]),
        q(400, "The venomous marine cephalopod that produces tetrodotoxin from endosymbiotic salivary bacteria, fatal to humans within minutes.", "Greater blue-ringed octopus", ["hapalochlaena lunulata"]),
        q(400, "The deep-sea isopod crustacean that can grow up to 50 centimeters in length, exhibiting deep-sea gigantism on the abyssal plains.", "Giant isopod", ["bathynomus giganteus"]),
        q(400, "The South American ant species that farms underground fungal cultivars inside massive subterranean chambers, feeding them freshly cut leaves.", "Leafcutter ant", ["atta cephalotes"]),
        q(400, "The Australian bird whose male constructs elaborate avenue bowers decorated with blue plastic pegs, berries, and shells to attract mates.", "Satin bowerbird", ["ptilonorhynchus violaceus"]),
        q(400, "The venomous mammal of the Caribbean that resembles a large shrew, producing toxic saliva channeled through grooves in its incisors.", "Solenodon", ["hispaniolan solenodon"]),
        q(400, "The deep-sea shark species with elongated paddle-like snouts covered in electrosensory pores and protruding jaws with needle teeth.", "Goblin shark", ["mitsukurina owstoni"]),
        q(400, "The African bird that leads human honey-hunters to wild beehives through specific vocal calls, feeding on wax left behind.", "Greater honeyguide", ["indicator indicator"]),
        q(400, "The marine polychaete worm known as the 'Bobbit worm' that burrows into ocean substrate and ambushes passing fish with scissor-like jaws.", "Eunice aphroditois", ["bobbit worm"]),
        q(400, "The Arctic seabird that undertakes the longest annual migration of any animal on Earth, flying from the Arctic to Antarctica and back.", "Arctic tern", ["sterna paradisaea"]),
        q(400, "The venomous Australian fish with dorsal spines containing lethal neurotoxins, perfectly camouflaged as a piece of reef rock.", "Reef stonefish", ["synanceia verrucosa"]),
        q(400, "The subterranean termite species whose mounds feature self-regulating convective ventilation chimneys that maintain internal humidity and temperature.", "Compass termite", ["magnetic termite", "amitermes meridionalis"]),
        q(400, "The critically endangered New Zealand wattlebird that went extinct in the early 20th century, notable for extreme sexual dimorphism in bill shape.", "Huia", ["heteralocha acutirostris"])
    ]

    n_500 = [
        q(500, "The microscopic marine invertebrate belonging to the phylum Cycliophora discovered in 1995 that lives exclusively on the mouthparts of the Norway lobster.", "Symbion pandora", ["cycliophora"]),
        q(500, "The deep-sea anglerfish whose symbiotic bioluminescent bacteria are housed in an organ called this, situated at the tip of the illicium.", "Esca", ["the esca"]),
        q(500, "The unique extinct mammal of South America related to ungulates that had nasal openings on the top of its head, resembling a camel without a hump.", "Macrauchenia", ["macrauchenia patachonica"]),
        q(500, "The Australian solitary wasp that paralyzes funnel-web spiders and drags them into burrows to serve as live food for its developing larvae.", "Spider wasp", ["cryptocheilus bicolor"]),
        q(500, "The microscopic marine animal belonging to the phylum Loricifera discovered in 2010 that spends its entire life cycle in permanently anoxic sediments without mitochondria.", "Spinoloricus cinziae", ["loricifera"]),
        q(500, "The deep-sea xenophyophore discovered in the Mariana Trench that secretes a cemented shell-like test made of foreign sediment grains called this.", "Xenophyophore test", ["agglutinated test"]),
        q(500, "The Malaysian carpenter ant species whose workers violently self-destruct via autothysis, expelling corrosive glue from hypertrophied mandibular glands.", "Colobopsis saundersi", ["exploding ant"]),
        q(500, "The fossil jaw of this massive Miocene apex predator shark from South America, with teeth measuring over 7 inches and estimated bite force exceeding 180,000 newtons.", "Megalodon", ["otodus megalodon"]),
        q(500, "The subterranean New Zealand glowworm whose bioluminescent snares are composed of glowing silk threads suspended from cave ceilings.", "Arachnocampa luminosa", ["new zealand glowworm"]),
        q(500, "The marine nematode worm that lives inside deep gold mines in South Africa at depths of over 3.6 kilometers below the surface, the deepest-living multicellular organism.", "Halicephalobus mephisto", ["devil worm"]),
        q(500, "The extinct flightless bird of Madagascar that reached heights of 10 feet and weights over 1,500 pounds, producing the largest eggs of any vertebrate.", "Elephant bird", ["aepyornis maximus"]),
        q(500, "The Australian sea slug that feeds exclusively on venomous Portuguese man o' war and sequesters their unfired nematocysts in its own cerata for defense.", "Glaucus atlanticus", ["blue sea slug"]),
        q(500, "The ancient Devonian lobe-finned fish discovered in 2004 on Ellesmere Island that possessed wrist joints, neck, and ribs, bridging fish and tetrapods.", "Tiktaalik", ["tiktaalik roseae"]),
        q(500, "The deep-sea glass sponge found in the western Pacific whose intricate silica skeleton serves as a lifelong cage for a mating pair of spongicolid shrimp.", "Venus' flower basket", ["euplectella aspergillum"]),
        q(500, "The Madagascar moth predicted by Charles Darwin in 1862 based solely on the 12-inch nectar spur of the orchid Angraecum sesquipedale, discovered 41 years later.", "Morgan's sphinx moth", ["xanthopan morganii praedicta"]),
        q(500, "The unique primitive segmented mollusk belonging to the class Monoplacophora, discovered alive in 1952 in a deep-sea trench off Costa Rica after being thought extinct since the Devonian.", "Neopilina galatheae", ["neopilina"]),
        q(500, "The specialized organ located in the inner ear of bony fish consisting of calcium carbonate stones that records daily growth rings like tree trunks.", "Otolith", ["otoliths", "ear stone"]),
        q(500, "The North American salamander species that reproduces through kleptogenesis, stealing genomes from males of related species to create all-female unisexual lineages.", "Ambystoma unisexual", ["mole salamander"]),
        q(500, "The marine polychaete worm whose bioluminescent mating swarm in Bermuda waters was recorded by Christopher Columbus on the night before landing in 1492.", "Bermuda fireworm", ["odontosyllis enopla"]),
        q(500, "The Australian jewel beetle whose males famously attempt to copulate with discarded brown stubby beer bottles due to their similar dimpled texture and color.", "Julodimorpha bakewelli", ["jewel beetle"]),
        q(500, "The extinct giant arthropod of the Carboniferous period that resembled a six-foot-long millipede, the largest known terrestrial invertebrate in history.", "Arthropleura", ["arthropleura armata"]),
        q(500, "The deep-sea hydrothermal vent gastropod snail whose shell is covered in scales reinforced with iron sulfide minerals (greigite).", "Scaly-foot snail", ["chrysomallon squamiferum"]),
        q(500, "The freshwater bryozoan that forms massive gelatinous blob-like colonies up to a meter across in lakes and reservoirs during late summer.", "Pectinatella magnifica", ["magnificent bryozoan"]),
        q(500, "The extinct late Cretaceous giant pterosaur with an estimated wingspan of 36 feet discovered in Big Bend National Park, Texas.", "Quetzalcoatlus", ["quetzalcoatlus northropi"]),
        q(500, "The specialized heat-producing organ found in deep-diving swordfish behind the eyes that keeps brain and eye temperatures warm in frigid depths.", "Cranial endothermy", ["brain heater organ"]),
        q(500, "The subterranean blind fish from Somalia that lacks a functional circadian clock and does not respond to light after millions of years of cave evolution.", "Phreatichthys andruzzii", ["somalian cavefish"]),
        q(500, "The microscopic marine crustacean whose males are dwarfed and live attached inside the genital duct of the female.", "Rhizocephalan barnacle", ["sacculina"]),
        q(500, "The ancient Paleozoic jawless fish group that was the earliest vertebrate with mineralized cellular bone tissue, dating to the Ordovician.", "Ostracoderms", ["ostracodermi"]),
        q(500, "The desert ant of the Sahara that navigates back to its nest across featureless sand dunes using celestial polarization and an internal step-counting odometer.", "Cataglyphis fortis", ["saharan silver ant"]),
        q(500, "The deep-sea ctenophore (comb jelly) discovered in the Puerto Rico Trench that possesses two long tentacular anchors tethering it to the seabed.", "Duobrachium sparksae", ["duobrachium"]),
        q(500, "The extinct giant short-faced kangaroo of Pleistocene Australia that weighed up to 500 pounds and walked with a striding bipedal gait rather than hopping.", "Procoptodon", ["procoptodon goliah"]),
        q(500, "The tiny marine placozoan organism discovered in an aquarium in 1883 that has the simplest known animal body plan, having only six cell types.", "Trichoplax adhaerens", ["placozoa"]),
        q(500, "The African spitting cobra that accurately aims its neurotoxic venom directly at the eyes of attackers from up to six feet away.", "Black-necked spitting cobra", ["naja nigricollis"]),
        q(500, "The prehistoric giant armored jawed fish of the Devonian period that grew up to 30 feet long with shearing bony plate blades instead of teeth.", "Dunkleosteus", ["dunkleosteus terrelli"]),
        q(500, "The marine tapeworm whose intermediate host is a copepod and primary host is an elasmobranch shark, forming complex life cycles across ocean food webs.", "Tetraphyllidea", ["elasmobranch tapeworm"]),
        q(500, "The specialized vocal organ unique to birds, located at the base of the trachea where it branches into the bronchi, capable of dual-voice singing.", "Syrinx", ["avian syrinx"]),
        q(500, "The deep-sea carnivorous sponge of the northeast Pacific that resembles a multi-stringed harp, trapping tiny crustaceans on vertical filaments.", "Chondrocladia lyra", ["harp sponge"]),
        q(500, "The fossil jawless fish from the Scottish Silurian that was among the first known vertebrates to possess dynamic pectoral fin stabilizers.", "Birkenia", ["anaspida"]),
        q(500, "The tiny parasitic barnacle that castrates its crab host and modifies the crab's behavior to care for the barnacle's eggs as its own.", "Sacculina carcini", ["sacculina"]),
        q(500, "The unique New Caledonian geckos that lack eyelids and wipe their eyes clean using their broad tongues, belonging to the genus Rhacodactylus.", "Crested gecko", ["correlophus ciliatus"])
    ]

    return n_100 + n_200 + n_300 + n_400 + n_500

if __name__ == "__main__":
    data = get_nature_data()
    print(f"Nature generated: {len(data)} clues")
