# -*- coding: utf-8 -*-
"""Sports & Champions Category - 200 Real Clues"""

def get_sports_data():
    def q(val, clue, ans, acc=None, src="Wikipedia - Sports"):
        return {"value": val, "clue": clue, "answer": ans, "accepted": acc or [], "source": src}

    s_100 = [
        q(100, "The global quadrennial men's soccer tournament organized by FIFA, won by Argentina in Qatar in 2022.", "FIFA World Cup", ["world cup"]),
        q(100, "The Jamaican sprinter who holds the world records in both the 100m (9.58s) and 200m (19.19s).", "Usain Bolt", ["bolt"]),
        q(100, "The American swimmer who holds the all-time Olympic record with 23 gold medals.", "Michael Phelps", ["phelps"]),
        q(100, "The basketball legend who won six NBA championships with the Chicago Bulls in the 1990s.", "Michael Jordan", ["jordan", "air jordan"]),
        q(100, "The annual championship game of the National Football League in the United States.", "Super Bowl", ["the super bowl"]),
        q(100, "The legendary heavyweight boxing champion known as 'The Greatest' who float like a butterfly and stung like a bee.", "Muhammad Ali", ["ali", "cassius clay"]),
        q(100, "The Argentine soccer legend who captained his nation to World Cup victory in 2022 and won eight Ballon d'Or awards.", "Lionel Messi", ["messi"]),
        q(100, "The Grand Slam tennis tournament played on outdoor grass courts in London every summer.", "Wimbledon", ["the championships wimbledon"]),
        q(100, "The New York Yankees slugger known as 'The Sultan of Swat' who hit 714 career home runs.", "Babe Ruth", ["ruth", "george herman ruth"]),
        q(100, "The Canadian NHL superstar known as 'The Great One' who holds the record for most career goals and assists.", "Wayne Gretzky", ["gretzky"]),
        q(100, "The Los Angeles Lakers star who surpassed Kareem Abdul-Jabbar in 2023 to become the NBA's all-time scoring leader.", "LeBron James", ["lebron", "king james"]),
        q(100, "The Portuguese soccer icon who has scored over 850 career goals and won five UEFA Champions League titles.", "Cristiano Ronaldo", ["cr7", "ronaldo"]),
        q(100, "The American tennis icon who won 23 Grand Slam singles titles in the Open Era.", "Serena Williams", ["serena"]),
        q(100, "The Brazilian soccer prodigy who won three FIFA World Cups in 1958, 1962, and 1970.", "Pele", ["pelé", "edson arantes do nascimento"]),
        q(100, "The major American golf tournament held annually at Augusta National Golf Club where winners receive a green jacket.", "The Masters", ["masters tournament"]),
        q(100, "The NFL quarterback who won seven Super Bowl titles with the New England Patriots and Tampa Bay Buccaneers.", "Tom Brady", ["brady"]),
        q(100, "The Swiss tennis maestro who won 20 Grand Slam singles titles and eight Wimbledon crowns.", "Roger Federer", ["federer"]),
        q(100, "The world's most famous multi-stage cycling race held in France every July.", "Tour de France", ["le tour"]),
        q(100, "The Jamaican-American sprinter who won four gold medals at the 1936 Berlin Olympics, defying Adolf Hitler.", "Jesse Owens", ["owens"]),
        q(100, "The Spanish tennis star known as the 'King of Clay' who won 14 French Open (Roland Garros) titles.", "Rafael Nadal", ["nadal"]),
        q(100, "The American gymnast who won seven Olympic medals, including four golds at the 2016 Rio Games.", "Simone Biles", ["biles"]),
        q(100, "The 26.2-mile long-distance road running event inspired by the legend of an ancient Greek messenger.", "Marathon", ["marathon race"]),
        q(100, "The combat sport where competitors win by knockout or decision inside a squared ring wearing padded gloves.", "Boxing", ["pugilism"]),
        q(100, "The sport where competitors slide stones on a sheet of ice towards a target area called the 'house'.", "Curling", ["curling on ice"]),
        q(100, "The Serbian tennis champion who holds the all-time men's record for most Grand Slam singles titles.", "Novak Djokovic", ["djokovic"]),
        q(100, "The term in bowling for knocking down all ten pins with the first ball of a frame.", "Strike", ["a strike"]),
        q(100, "The baseball player who broke MLB's color line in 1947 with the Brooklyn Dodgers wearing jersey number 42.", "Jackie Robinson", ["robinson"]),
        q(100, "The quadrennial international multi-sport winter event featuring skiing, bobsleigh, and figure skating.", "Winter Olympic Games", ["winter olympics"]),
        q(100, "The American golfer who won 15 major championships and 82 PGA Tour events, dominating the 2000s.", "Tiger Woods", ["woods"]),
        q(100, "The term in soccer when a single player scores three goals in a single match.", "Hat-trick", ["hat trick"]),
        q(100, "The Japanese baseball phenom who plays as both an elite pitcher and designated hitter for the LA Dodgers.", "Shohei Ohtani", ["ohtani"]),
        q(100, "The maximum score in a standard single frame of bowling (three consecutive strikes) or a perfect game.", "300", ["300 game"]),
        q(100, "The Olympic sport involving rings, pommel horse, parallel bars, balance beam, and vault.", "Gymnastics", ["artistic gymnastics"]),
        q(100, "The 100-yard field game played with an oblong pigskin ball, downs, and field goals.", "American football", ["football"]),
        q(100, "The track and field event where athletes sprint and leap over a high horizontal bar without knocking it off.", "High jump", ["high jumping"]),
        q(100, "The Brazilian Formula 1 legend who won three world championships before his tragic death at Imola in 1994.", "Ayrton Senna", ["senna"]),
        q(100, "The track event where four sprinters each run one leg of a race, passing a cylindrical baton.", "Relay race", ["4x100m relay", "relay"]),
        q(100, "The sport where two teams of six players hit a ball back and forth over a net using their hands without letting it bounce.", "Volleyball", ["beach volleyball"]),
        q(100, "The prestigious international sailing trophy contested since 1851, the oldest international trophy in world sport.", "America's Cup", ["americas cup"]),
        q(100, "The martial art and Olympic sport developed in Japan by Jigoro Kano in 1882 based on throws and pins.", "Judo", ["kodokan judo"])
    ]

    s_200 = [
        q(200, "The baseball achievement where a batter hits a single, double, triple, and home run in a single game.", "Hitting for the cycle", ["the cycle", "cycle"]),
        q(200, "The British Formula 1 driver who has won a record-equaling seven World Drivers' Championship titles.", "Lewis Hamilton", ["hamilton"]),
        q(200, "The Philadelphia Warriors center who scored an astonishing 100 points in a single NBA game on March 2, 1962.", "Wilt Chamberlain", ["chamberlain"]),
        q(200, "The legendary 1974 heavyweight boxing match in Zaire where Muhammad Ali defeated George Foreman using the 'rope-a-dope'.", "Rumble in the Jungle", ["rumble in the jungle"]),
        q(200, "The Australian cricket batsman whose career Test batting average of 99.94 is regarded as the greatest statistical achievement in sports.", "Don Bradman", ["sir donald bradman", "the don"]),
        q(200, "The Grand Slam tennis tournament played on red clay courts at Stade Roland Garros in Paris.", "French Open", ["roland garros"]),
        q(200, "The Dutch soccer pioneer who developed 'Total Football' with Ajax and Barcelona, winning three Ballons d'Or.", "Johan Cruyff", ["cruyff"]),
        q(200, "The American swimmer who won seven gold medals at the 1972 Munich Olympics, setting world records in all seven.", "Mark Spitz", ["spitz"]),
        q(200, "The historic 1980 Olympic ice hockey game where the underdog US men's team defeated the four-time defending champion Soviet Union.", "Miracle on Ice", ["miracle on ice 1980"]),
        q(200, "The Italian motorcycle road racer who won nine Grand Prix World Championships, nicknamed 'The Doctor'.", "Valentino Rossi", ["rossi"]),
        q(200, "The Romanian gymnast who scored the first perfect 10.0 in modern Olympic gymnastics history at Montreal 1976.", "Nadia Comaneci", ["comaneci"]),
        q(200, "The Argentine soccer legend who scored the infamous 'Hand of God' goal and the 'Goal of the Century' against England in 1986.", "Diego Maradona", ["maradona"]),
        q(200, "The German Formula 1 legend who won seven World Drivers' Championships, including five consecutive with Ferrari (2000-2004).", "Michael Schumacher", ["schumacher"]),
        q(200, "The term in golf for completing a hole in three strokes under par (e.g. 2 on a par 5).", "Albatross", ["double eagle"]),
        q(200, "The MLB pitcher who holds the all-time career strikeout record with 5,714 strikeouts across 27 seasons.", "Nolan Ryan", ["ryan"]),
        q(200, "The Czech distance runner known as the 'Czech Locomotive' who won gold in the 5,000m, 10,000m, and Marathon at Helsinki 1952.", "Emil Zatopek", ["zatopek"]),
        q(200, "The term in rugby when an attacking player touches the ball down in the opponent's in-goal area for 5 points.", "Try", ["scoring a try"]),
        q(200, "The Boston Celtics center who won 11 NBA championships in 13 seasons and has the Finals MVP trophy named after him.", "Bill Russell", ["russell"]),
        q(200, "The multi-stage endurance race consisting of swimming, cycling, and long-distance running.", "Triathlon", ["ironman triathlon"]),
        q(200, "The English soccer club that completed a historic treble in 1999 under manager Sir Alex Ferguson.", "Manchester United", ["man utd"]),
        q(200, "The 1971 heavyweight boxing bout between Joe Frazier and Muhammad Ali at Madison Square Garden billed as this 'Fight'.", "Fight of the Century", ["ali frazier 1"]),
        q(200, "The Czech-American tennis legend who won a record 9 Wimbledon singles titles and 18 Grand Slam singles championships.", "Martina Navratilova", ["navratilova"]),
        q(200, "The MLB outfielder who holds the all-time consecutive games played streak with 2,632 straight games for the Orioles.", "Cal Ripken Jr.", ["ripken", "iron man"]),
        q(200, "The martial art and combat sport characterized by eight points of contact (punches, kicks, elbows, knees), native to Thailand.", "Muay Thai", ["thai boxing"]),
        q(200, "The term in basketball when a player accumulates double digits in three of five statistical categories in one game.", "Triple-double", ["triple double"]),
        q(200, "The German tennis player who completed the only 'Golden Slam' in tennis history in 1988 by winning all four majors and Olympic gold.", "Steffi Graf", ["graf"]),
        q(200, "The annual 500-mile automobile race held over Memorial Day weekend at the Indianapolis Motor Speedway.", "Indianapolis 500", ["indy 500"]),
        q(200, "The MLB slugger who hit 755 career home runs for the Milwaukee/Atlanta Braves, breaking Babe Ruth's record in 1974.", "Hank Aaron", ["aaron", "hammerin hank"]),
        q(200, "The track and field discipline consisting of ten distinct events contested over two consecutive days.", "Decathlon", ["decathlon"]),
        q(200, "The 24-hour sports car endurance race held annually near the town of Le Mans in France since 1923.", "24 Hours of Le Mans", ["le mans 24"]),
        q(200, "The West Indian cricket batsman who scored 400 not out in a single Test match innings against England in 2004.", "Brian Lara", ["lara"]),
        q(200, "The term in soccer when a goalkeeper completes an entire match without conceding a single goal.", "Clean sheet", ["shutout"]),
        q(200, "The American tennis star who won 8 Grand Slam titles and an Olympic gold medal, famous for his colorful rivalry with Pete Sampras.", "Andre Agassi", ["agassi"]),
        q(200, "The NHL trophy awarded annually to the most valuable player of the regular season, voted by the PHWA.", "Hart Memorial Trophy", ["hart trophy"]),
        q(200, "The traditional sport of Japanese full-contact wrestling where a rikishi attempts to force his opponent out of the dohyo.", "Sumo wrestling", ["sumo"]),
        q(200, "The American track star who won nine Olympic gold medals from 1984 to 1996 in 100m, 200m, 4x100m, and long jump.", "Carl Lewis", ["lewis"]),
        q(200, "The Spanish soccer club that won five consecutive European Cup titles from 1956 to 1960 led by Alfredo Di Stefano.", "Real Madrid", ["los blancos"]),
        q(200, "The distance in yards between the wickets on a cricket pitch.", "22 yards", ["twenty two yards", "22"]),
        q(200, "The college basketball single-elimination tournament held every spring by the NCAA featuring 68 teams.", "March Madness", ["ncaa tournament"]),
        q(200, "The traditional Scottish athletic contest where competitors toss a tapered log measuring roughly 19 feet.", "Caber toss", ["tossing the caber"])
    ]

    s_300 = [
        q(300, "The 1954 race where British medical student Roger Bannister became the first person to run a mile under this time.", "Four minutes", ["4 minutes", "sub-four-minute"]),
        q(300, "The 1936 Summer Olympics host city where African-American athlete Jesse Owens won four gold medals, embarrassing Nazi racial dogma.", "Berlin", ["berlin 1936"]),
        q(300, "The Italian road bicycle race established in 1909 whose overall race leader wears the distinctive pink jersey (maglia rosa).", "Giro d'Italia", ["giro"]),
        q(300, "The NFL head coach who led the Miami Dolphins to the only undefeated, untied perfect season in NFL history in 1972.", "Don Shula", ["shula"]),
        q(300, "The legendary 1975 heavyweight championship trilogy bout in the Philippines between Muhammad Ali and Joe Frazier.", "Thrilla in Manila", ["thrilla in manila"]),
        q(300, "The Hungarian soccer striker who scored 84 goals in 85 international matches for the 'Mighty Magyars' in the 1950s.", "Ferenc Puskas", ["puskas"]),
        q(300, "The Australian city that hosted the 1956 Summer Olympics, the first Olympic Games held in the Southern Hemisphere.", "Melbourne", ["melbourne 1956"]),
        q(300, "The MLB pitcher who pitched a perfect game in Game 5 of the 1956 World Series for the Yankees, the only one in World Series history.", "Don Larsen", ["larsen"]),
        q(300, "The French barman who founded the modern Olympic Games in 1894 and established the International Olympic Committee.", "Pierre de Coubertin", ["coubertin"]),
        q(300, "The Portuguese soccer manager who dubbed himself 'The Special One' after winning the Champions League with Porto in 2004.", "Jose Mourinho", ["mourinho"]),
        q(300, "The 1968 Olympic long jumper who shattered the world record by 55 cm with a leap of 8.90 meters in the thin air of Mexico City.", "Bob Beamon", ["beamon"]),
        q(300, "The annual men's golf team tournament contested biennially between teams from Europe and the United States.", "Ryder Cup", ["the ryder cup"]),
        q(300, "The Soviet gymnast who won 18 total Olympic medals between 1956 and 1964, a record that stood for 48 years until Michael Phelps.", "Larisa Latynina", ["latynina"]),
        q(300, "The Brazilian soccer club from Sao Paulo where Pele spent nearly two decades scoring over 1,000 goals.", "Santos FC", ["santos"]),
        q(300, "The 1973 exhibition tennis match where 30-year-old Billie Jean King defeated 55-year-old Bobby Riggs in the Houston Astrodome.", "Battle of the Sexes", ["battle of the sexes tennis"]),
        q(300, "The Austrian alpine ski racer who won the downhill, giant slalom, and slalom at the 1956 Cortina d'Ampezzo Winter Olympics.", "Toni Sailer", ["sailer"]),
        q(300, "The English cricket series played biennially between England and Australia, named after an obituary in The Sporting Times in 1882.", "The Ashes", ["ashes series"]),
        q(300, "The MLB player who holds the single-season record for hits with 262 hits in 2004, surpassing George Sisler.", "Ichiro Suzuki", ["ichiro"]),
        q(300, "The Dutch speed skater who won three gold medals at the 1972 Sapporo Winter Olympics, dominating men's speed skating.", "Ard Schenk", ["schenk"]),
        q(300, "The American tennis player who won 14 Grand Slam singles titles and held the world No. 1 ranking for 286 weeks in the 1990s.", "Pete Sampras", ["sampras"]),
        q(300, "The Italian soccer defender who captained Italy to World Cup victory in 2006 and won the Ballon d'Or that same year.", "Fabio Cannavaro", ["cannavaro"]),
        q(300, "The Swedish tennis superstar who won five consecutive Wimbledon titles (1976-1980) and six French Open titles before retiring at 26.", "Bjorn Borg", ["borg"]),
        q(300, "The legendary Cuban heavyweight boxer who won three consecutive Olympic gold medals in 1972, 1976, and 1980.", "Teofilo Stevenson", ["stevenson"]),
        q(300, "The 1960 Winter Olympics in California where computer scoring was first used, held at a Lake Tahoe ski resort.", "Squaw Valley", ["palisades tahoe"]),
        q(300, "The Russian pole vault superstar who set 28 world records and became the first woman to clear the 5.0-meter barrier.", "Yelena Isinbayeva", ["isinbayeva"]),
        q(300, "The NFL running back who rushed for 2,105 yards in 1984 for the LA Rams, a single-season record that still stands.", "Eric Dickerson", ["dickerson"]),
        q(300, "The British rower who won gold medals at five consecutive Olympic Games from 1984 to 2000.", "Sir Steve Redgrave", ["redgrave"]),
        q(300, "The traditional Irish full-contact field team sport played with a wooden stick called a hurley and an ash ball called a sliotar.", "Hurling", ["iomanaiocht"]),
        q(300, "The Formula 1 racing team founded by Frank Williams that won nine World Constructors' Championships.", "Williams Racing", ["williams f1"]),
        q(300, "The American high jumper who revolutionized the sport at the 1968 Mexico City Olympics with his backward curved Fosbury technique.", "Dick Fosbury", ["fosbury flop"]),
        q(300, "The Finnish javelin thrower who won gold at the 1932 Los Angeles Olympics, part of Finland's javelin heritage.", "Matti Jarvinen", ["jarvinen"]),
        q(300, "The African distance runner from Ethiopia who won the 1960 Rome Olympic marathon running completely barefoot.", "Abebe Bikila", ["bikila"]),
        q(300, "The professional golf tour organizing the major tournaments in Europe, rebranded as the DP World Tour in 2022.", "European Tour", ["dp world tour"]),
        q(300, "The Soviet chess grandmaster who became the youngest undisputed World Chess Champion in history in 1985 at age 22.", "Garry Kasparov", ["kasparov"]),
        q(300, "The MLB pitcher who holds the record for most career complete game shutouts with 110 for the Washington Senators.", "Walter Johnson", ["the big train"]),
        q(300, "The sport of competitive target archery using recurve bows that has been on the Olympic program since 1972.", "Archery", ["target archery"]),
        q(300, "The English football manager who led underdog Nottingham Forest to consecutive European Cup triumphs in 1979 and 1980.", "Brian Clough", ["clough"]),
        q(300, "The multi-stage bicycle race held across Spain every autumn, the third of cycling's Grand Tours.", "Vuelta a Espana", ["la vuelta"]),
        q(300, "The Canadian track sprinter stripped of his 100m gold medal at the 1988 Seoul Olympics after testing positive for stanozolol.", "Ben Johnson", ["johnson"]),
        q(300, "The term in equestrian show jumping for knocking down a rail or touching the water jump.", "Fault", ["jumping fault"])
    ]

    s_400 = [
        q(400, "The 1904 Summer Olympic marathon in St. Louis was won by Fred Lorz before he was disqualified for doing this for 11 miles.", "Riding in a car", ["rode in an automobile", "car ride"]),
        q(400, "The Finnish distance runner known as the 'Flying Finn' who won nine Olympic gold medals and three silvers across 1920 to 1928.", "Paavo Nurmi", ["nurmi"]),
        q(400, "The 1966 FIFA World Cup final ball dispute centered on whether Geoff Hurst's second goal crossed the goal line at this London stadium.", "Wembley Stadium", ["wembley"]),
        q(400, "The American decathlete who set a world record winning gold at the 1976 Montreal Olympics, later coming out as Caitlyn.", "Bruce Jenner", ["caitlyn jenner"]),
        q(400, "The French soccer forward who holds the record for most goals scored in a single FIFA World Cup tournament, with 13 goals in 1958.", "Just Fontaine", ["fontaine"]),
        q(400, "The legendary 1953 soccer match where Hungary defeated England 6-3 at Wembley, England's first-ever home loss to a continental team.", "Match of the Century", ["hungary 6 england 3"]),
        q(400, "The Formula 1 driver from Austria who won the 1970 World Drivers' Championship posthumously after dying at Monza.", "Jochen Rindt", ["rindt"]),
        q(400, "The American high jumper who set an unprecedented 1973 world record of 2.30 meters using the straddle technique, not the flop.", "Dwight Stones", ["stones"]),
        q(400, "The 1896 Athens Olympic 100m sprint champion, an American student from Boston who also won the 400m.", "Tom Burke", ["burke 1896"]),
        q(400, "The Czechoslovak distance runner who was the only athlete to win the 5,000m, 10,000m, and Marathon in the same Olympic Games.", "Emil Zatopek", ["zatopek"]),
        q(400, "The Soviet weightlifter who set 80 world records in the super heavyweight division and won two Olympic golds (1972, 1976).", "Vasily Alekseyev", ["alekseyev"]),
        q(400, "The MLB manager who led the Oakland Athletics to three consecutive World Series titles from 1972 to 1974.", "Dick Williams", ["al dark"]),
        q(400, "The 1968 Olympic 200m medal ceremony protest where Tommie Smith and John Carlos raised black-gloved fists on the podium occurred in this city.", "Mexico City", ["mexico city 1968"]),
        q(400, "The English cricketer who captained England during the controversial 1932-33 'Bodyline' Ashes series against Australia.", "Douglas Jardine", ["jardine"]),
        q(400, "The Australian middle-distance runner who carried the Olympic flame into the stadium at Melbourne 1956 and set world records in the mile.", "John Landy", ["landy"]),
        q(400, "The first winter sport ever contested at the Summer Olympic Games, introduced at the 1908 London Games.", "Figure skating", ["ice skating"]),
        q(400, "The Uruguayan soccer stadium built in Montevideo specifically to host the inaugural 1930 FIFA World Cup.", "Estadio Centenario", ["centenario"]),
        q(400, "The American tennis player who won three Wimbledon titles in the 1930s and pioneered the modern tennis serve-and-volley style.", "Ellsworth Vines", ["vines"]),
        q(400, "The Italian road cyclist nicknamed 'Il Campionissimo' (The Champion of Champions) who won five Giros d'Italia and two Tours de France.", "Fausto Coppi", ["coppi"]),
        q(400, "The 1932 Lake Placid Winter Olympic speed skater who won both the 500m and 1,500m golds and took the Olympic oath.", "Jack Shea", ["shea"]),
        q(400, "The German heavyweight boxer who became the first German world champion in 1930 and famously defeated Joe Louis in 1936.", "Max Schmeling", ["schmeling"]),
        q(400, "The American track coach at Oregon who co-founded Nike with Phil Knight and invented the waffle shoe sole using a waffle iron.", "Bill Bowerman", ["bowerman"]),
        q(400, "The Argentine Formula 1 driver who won five World Drivers' Championships in the 1950s with four different constructors.", "Juan Manuel Fangio", ["fangio"]),
        q(400, "The Swedish tennis player who won the 1988 Australian, French, and US Opens, missing the Grand Slam only at Wimbledon.", "Mats Wilander", ["wilander"]),
        q(400, "The 1958 FIFA World Cup final host city in Sweden where 17-year-old Pele scored two goals in Brazil's 5-2 win.", "Solna", ["rasunda stadium", "stockholm"]),
        q(400, "The distance in meters of an Olympic-standard sprint canoe racing sprint course, standard Olympic distance.", "1000 meters", ["500m", "1000m"]),
        q(400, "The American basketball coach who led UCLA to 10 NCAA national championships in a 12-year period, nicknamed the 'Wizard of Westwood'.", "John Wooden", ["wooden"]),
        q(400, "The British middle-distance runner who won the 800m and 1,500m double at the 1924 Paris Olympics, portrayed in Chariots of Fire.", "Harold Abrahams", ["abrahams"]),
        q(400, "The Scottish devout Christian sprinter who won the 400m gold at Paris 1924 after refusing to run the 100m on a Sunday.", "Eric Liddell", ["liddell"]),
        q(400, "The 1950 World Cup match at the Maracana Stadium where Uruguay stunned Brazil 2-1 before 200,000 spectators, known as this 'blow'.", "Maracanazo", ["maracana shock"]),
        q(400, "The MLB pitcher who pitched two consecutive no-hitters for the Cincinnati Reds in June 1938, a feat never duplicated.", "Johnny Vander Meer", ["vander meer"]),
        q(400, "The Italian cross-country skier who won the grueling 50km race at the 1968 Grenoble Winter Olympics by 16.7 seconds.", "Franco Nones", ["nones"]),
        q(400, "The English soccer referee who invented red and yellow penalty cards in 1966 after driving past traffic lights in London.", "Ken Aston", ["aston"]),
        q(400, "The American diver who swept both the 3m springboard and 10m platform gold medals at both the 1984 and 1988 Olympics.", "Greg Louganis", ["louganis"]),
        q(400, "The Japanese marathon runner who disappeared during the 1912 Stockholm Olympic marathon and finished his race 54 years later in 1967.", "Shizo Kanakuri", ["kanakuri"]),
        q(400, "The Soviet high jumper who set six world records between 1960 and 1963 and won Olympic gold at Tokyo 1964 using the straddle style.", "Valeriy Brumel", ["brumel"]),
        q(400, "The first player drafted in the inaugural 1936 NFL Draft, a Heisman Trophy-winning halfback from Chicago.", "Jay Berwanger", ["berwanger"]),
        q(400, "The French figure skating couple who won four world titles and 1932 Olympic gold performing innovative pair spins.", "Andree and Pierre Brunet", ["brunet"]),
        q(400, "The Australian swimmer who won three consecutive Olympic gold medals in the 100m freestyle in 1956, 1960, and 1964.", "Dawn Fraser", ["fraser"]),
        q(400, "The term in sailing for steering a sailboat so that its stern passes through the eye of the wind, changing tack.", "Gybe", ["jibing", "jibe"])
    ]

    s_500 = [
        q(500, "The 1900 Paris Summer Olympics featured this live animal shooting event, the only time living animals were intentionally killed in Olympic history.", "Pigeon shooting", ["live pigeon shooting"]),
        q(500, "The ancient Greek pankratiast who was crowned Olympic champion in 564 BC despite dying during the final match from strangulation.", "Arrhichion of Phigalia", ["arrichion"]),
        q(500, "The 1928 Amsterdam Olympic rowing gold medalist for Australia who famously stopped mid-race to allow a family of ducks to pass.", "Bobby Pearce", ["henry pearce"]),
        q(500, "The French cyclist who won the inaugural 1903 Tour de France by nearly three hours over second place Lucien Pothier.", "Maurice Garin", ["garin"]),
        q(500, "The 1912 Olympic decathlon and pentathlon champion who was stripped of his gold medals in 1913 for playing minor league baseball for $25 a week.", "Jim Thorpe", ["wa-tho-huk"]),
        q(500, "The Italian gymnast who won gold in five different events at the 1920 Antwerp Summer Olympics, including individual all-around.", "Giorgio Zampori", ["nedo nadi"]),
        q(500, "The 1908 London Olympic marathon runner from Italy who collapsed five times near the finish line and was disqualified after officials helped him across.", "Dorando Pietri", ["pietri"]),
        q(500, "The American track athlete who set a world record in the 100-yard dash of 9.4 seconds in 1929 and was known as the 'World's Fastest Human'.", "Frank Wykoff", ["wykoff"]),
        q(500, "The ancient Greek wrestler from Croton who won six consecutive Olympic wrestling titles between 540 BC and 516 BC.", "Milo of Croton", ["milo"]),
        q(500, "The 1936 Berlin Olympic 800m gold medalist from the US who won wearing an ordinary white felt painter's cap to hide his bald spot.", "John Woodruff", ["woodruff"]),
        q(500, "The British figure skater who won Olympic gold at Lake Placid 1932 at age 11, remaining the youngest individual Winter Olympic champion for 66 years.", "Cecilia Colledge", ["colledge"]),
        q(500, "The Hungarian pistol shooter whose shooting hand was shattered by a grenade in 1938, who taught himself to shoot left-handed and won Olympic gold in 1948 and 1952.", "Karoly Takacs", ["takacs"]),
        q(500, "The French marathon runner who won the 1900 Paris Olympic marathon after competitors claimed he took shortcuts through Paris alleyways.", "Michel Theato", ["theato"]),
        q(500, "The 1924 Paris Olympic steeplechase champion from Finland who also won gold in the 3,000m team race alongside Paavo Nurmi.", "Ville Ritola", ["ritola"]),
        q(500, "The first champion of the modern Olympic Games in 1896, an American triple jumper from Harvard who won the hop, step, and jump.", "James Connolly", ["connolly 1896"]),
        q(500, "The 1928 Winter Olympics 50km cross-country skiing champion who won by over an hour in blizzard conditions at St. Moritz.", "Per-Erik Hedlund", ["hedlund"]),
        q(500, "The American swimmer who won three golds at the 1924 Paris Olympics and later achieved worldwide fame playing Tarzan in twelve films.", "Johnny Weissmuller", ["weissmuller"]),
        q(500, "The 1896 Olympic fencing champion from Greece who was the only Greek athlete to win an Olympic fencing event at the first modern Games.", "Leonidas Pyrgos", ["pyrgos"]),
        q(500, "The 1936 Garmisch-Partenkirchen Winter Olympics Norwegian ski jumper who won gold with a leap of 75 meters.", "Birger Ruud", ["ruud"]),
        q(500, "The British runner who won the 1908 London Olympic 1,500m race and later became a prominent member of Parliament and Nobel Peace Prize laureate.", "Philip Noel-Baker", ["noel baker"]),
        q(500, "The Finnish athlete who won the pentathlon, javelin, and shot put at the 1920 Antwerp Summer Olympics.", "Eero Lehtonen", ["lehtonen"]),
        q(500, "The 1932 Los Angeles Olympic 800m champion from the UK who set an Olympic record of 1:49.7, later becoming an Olympic official.", "Tommy Hampson", ["hampson"]),
        q(500, "The Italian bobsledder who won Olympic gold in both two-man and four-man bobsleigh at Cortina 1956.", "Lamberto Dalla Costa", ["dalla costa"]),
        q(500, "The 1904 St. Louis Olympic gymnast who won six medals in a single day despite competing with a wooden peg leg.", "George Eyser", ["eyser"]),
        q(500, "The Estonian wrestler who won Olympic gold in Greco-Roman heavyweight wrestling at Berlin 1936.", "Kristjan Palusalu", ["palusalu"]),
        q(500, "The 1928 Amsterdam Olympic 100m gold medalist from Canada who died in tragic circumstances in 1940.", "Percy Williams", ["percy williams"]),
        q(500, "The French middle-distance runner who won the 1,500m gold at the 1956 Melbourne Olympics, defeating John Landy.", "Alain Mimoun", ["mimoun"]),
        q(500, "The Japanese triple jumper who won Olympic gold at Amsterdam 1928 with a leap of 15.21 meters, Japan's first-ever Olympic gold medalist.", "Mikio Oda", ["oda"]),
        q(500, "The 1912 Stockholm Olympic decathlon competitor from Sweden who finished second to Jim Thorpe and was awarded gold after Thorpe's disqualification.", "Hugo Wieslander", ["wieslander"]),
        q(500, "The American high jumper who cleared 1.90 meters to win gold at Paris 1900 while wearing a formal tweed cap.", "Irving Baxter", ["baxter"]),
        q(500, "The 1932 Lake Placid Winter Olympics figure skating gold medalist from Norway who won three consecutive Olympic singles golds (1928, 1932, 1936).", "Sonja Henie", ["henie"]),
        q(500, "The Swedish shooter who won Olympic gold in 100m running deer single shots at Antwerp 1920 at age 72, the oldest Olympic medalist in history.", "Oscar Swahn", ["swahn"]),
        q(500, "The 1908 Olympic heavyweight boxing champion from Great Britain who was also an accomplished cricketer and rugby player.", "Albert Oldman", ["oldman"]),
        q(500, "The American swimmer who won five gold medals at Antwerp 1920, setting world records in the 100m and 400m freestyle.", "Duke Kahanamoku", ["kahanamoku", "the duke"]),
        q(500, "The 1936 Berlin Olympic Marathon winner from Korea, forced by the Japanese colonial government to compete under the Japanese name Kitei Son.", "Sohn Kee-chung", ["son kitei", "sohn"]),
        q(500, "The French polo team that won the first Olympic polo tournament at Paris 1900, composed of French and British players.", "Foxhunters Hurlingham", ["foxhunters"]),
        q(500, "The 1920 Antwerp Olympic Greco-Roman light heavyweight wrestling champion from Finland who wrestled for over three hours in the semifinal.", "Adolf Lindfors", ["lindfors"]),
        q(500, "The American gymnast who won gold in the club swinging event at the 1932 Los Angeles Games.", "George Roth", ["roth"]),
        q(500, "The 1900 Paris Olympic croquet tournament was historical because it was the first Olympic event that allowed this group of competitors.", "Women", ["female athletes"]),
        q(500, "The German javelin thrower who won gold at Berlin 1936 by just two centimeters on his final throw, setting an Olympic record of 71.84m.", "Gerhard Stock", ["stock"])
    ]

    return s_100 + s_200 + s_300 + s_400 + s_500

if __name__ == "__main__":
    data = get_sports_data()
    print(f"Sports generated: {len(data)} clues")
