# -*- coding: utf-8 -*-
"""Technology & Inventions Category - 200 Real Clues"""

def get_technology_data():
    def q(val, clue, ans, acc=None, src="Wikipedia - Technology"):
        return {"value": val, "clue": clue, "answer": ans, "accepted": acc or [], "source": src}

    t_100 = [
        q(100, "The Apple co-founder who unveiled the original iPhone at Macworld in January 2007.", "Steve Jobs", ["jobs"]),
        q(100, "The universal computer networking abbreviation for 'HyperText Transfer Protocol'.", "HTTP", ["http protocol"]),
        q(100, "The world's most popular search engine, founded by Larry Page and Sergey Brin in 1998.", "Google", ["google search"]),
        q(100, "The social media platform founded by Mark Zuckerberg in 2004 in his Harvard dorm room.", "Facebook", ["meta"]),
        q(100, "The operating system developed by Microsoft that debuted with a GUI in 1985.", "Microsoft Windows", ["windows"]),
        q(100, "The portable communication device invented by Martin Cooper at Motorola in 1973.", "Mobile phone", ["cell phone", "cellular phone"]),
        q(100, "The open-source operating system created by Linus Torvalds in 1991.", "Linux", ["linux kernel"]),
        q(100, "The billionaire CEO of Tesla and SpaceX who purchased Twitter in 2022, renaming it X.", "Elon Musk", ["musk"]),
        q(100, "The global computer network that connects billions of computers worldwide using TCP/IP.", "The Internet", ["internet"]),
        q(100, "The popular video-sharing platform created in 2005 by Chad Hurley, Steve Chen, and Jawed Karim.", "YouTube", ["youtube.com"]),
        q(100, "The wireless networking technology named after a 10th-century Danish Viking king.", "Bluetooth", ["harald bluetooth"]),
        q(100, "The company founded by Bill Gates and Paul Allen in 1975.", "Microsoft", ["msft"]),
        q(100, "The primary brain/chip of a computer that performs calculations and instructions.", "CPU", ["central processing unit", "processor"]),
        q(100, "The short-range wireless technology that allows mobile payments like Apple Pay and Google Pay.", "NFC", ["near field communication"]),
        q(100, "The electronic mail message system invented by Ray Tomlinson in 1971, who introduced the '@' symbol.", "Email", ["e-mail"]),
        q(100, "The online retail giant founded by Jeff Bezos in 1994 as an online bookstore.", "Amazon", ["amazon.com"]),
        q(100, "The computer peripheral pointing device invented by Douglas Engelbart in 1964, carved from wood.", "Computer mouse", ["mouse"]),
        q(100, "The photo and video sharing app featuring Stories, acquired by Facebook in 2012 for $1 billion.", "Instagram", ["ig"]),
        q(100, "The standard digital audio format developed by the Fraunhofer Society in 1993 for compressed music.", "MP3", ["mpeg-1 audio layer iii"]),
        q(100, "The popular microblogging platform with a bird logo founded in 2006 by Jack Dorsey and others.", "Twitter", ["x", "twitter.com"]),
        q(100, "The high-definition multimedia cable interface standard used to connect TVs, monitors, and consoles.", "HDMI", ["high-definition multimedia interface"]),
        q(100, "The AI chatbot developed by OpenAI released in November 2022 that reached 100M users in two months.", "ChatGPT", ["chat gpt", "openai chatgpt"]),
        q(100, "The storage component in computers where operating system and active program data is temporarily held.", "RAM", ["random access memory"]),
        q(100, "The short-form video platform owned by Chinese technology company ByteDance.", "TikTok", ["douyin"]),
        q(100, "The optical disc format introduced by Sony and Philips in 1982 that replaced vinyl records and cassettes.", "Compact Disc", ["cd", "compact disk"]),
        q(100, "The electric vehicle company founded in 2003 named after an inventor of the alternating current motor.", "Tesla", ["tesla motors"]),
        q(100, "The popular ride-sharing app founded in 2009 by Travis Kalanick and Garrett Camp.", "Uber", ["uber technologies"]),
        q(100, "The free, collaborative online encyclopedia launched by Jimmy Wales and Larry Sanger in 2001.", "Wikipedia", ["wikipedia.org"]),
        q(100, "The satellite navigation system developed by the US Department of Defense providing geolocation.", "GPS", ["global positioning system"]),
        q(100, "The device that converts chemical energy into electrical energy to power portable gadgets.", "Battery", ["electric battery"]),
        q(100, "The technology company behind the Macintosh, iPod, iPad, Apple Watch, and Vision Pro.", "Apple", ["apple inc"]),
        q(100, "The standard markup language used to structure web pages and documents for display in browsers.", "HTML", ["hypertext markup language"]),
        q(100, "The universal serial bus interface standard found on modern phones, laptops, and chargers.", "USB", ["universal serial bus", "usb-c"]),
        q(100, "The voice-activated digital assistant introduced by Apple in 2011 on the iPhone 4S.", "Siri", ["apple siri"]),
        q(100, "The wireless local networking protocol family based on the IEEE 802.11 standards.", "Wi-Fi", ["wifi", "wireless fidelity"]),
        q(100, "The software application used to access and display content on the World Wide Web like Chrome and Safari.", "Web browser", ["browser"]),
        q(100, "The Swedish audio streaming service founded by Daniel Ek and Martin Lorentzon in 2006.", "Spotify", ["spotify.com"]),
        q(100, "The solid-state non-volatile storage technology that replaced spinning magnetic hard drives in modern laptops.", "SSD", ["solid state drive"]),
        q(100, "The computer graphic display screen composed of millions of red, green, and blue tiny illuminated dots.", "Pixels", ["pixel"]),
        q(100, "The popular open-source version control system created by Linus Torvalds in 2005.", "Git", ["git vcs"])
    ]

    t_200 = [
        q(200, "The English mathematician and computing pioneer who broke the Enigma cipher and formulated theoretical computer science.", "Alan Turing", ["turing"]),
        q(200, "The British scientist who invented the World Wide Web at CERN in 1989.", "Tim Berners-Lee", ["berners-lee"]),
        q(200, "The revolutionary three-terminal semiconductor device invented at Bell Labs in 1947 that replaced vacuum tubes.", "Transistor", ["the transistor"]),
        q(200, "The programming language created by Guido van Rossum in 1991, named after a British comedy troupe.", "Python", ["python language"]),
        q(200, "The pseudonym of the unknown person or group who created Bitcoin and published its whitepaper in 2008.", "Satoshi Nakamoto", ["satoshi"]),
        q(200, "The observation made in 1965 stating that the number of transistors on a microchip doubles roughly every two years.", "Moore's Law", ["moore law", "gordon moore"]),
        q(200, "The daughter of Lord Byron who wrote an algorithm for Babbage's Analytical Engine, hailed as the first programmer.", "Ada Lovelace", ["lovelace"]),
        q(200, "The graphical user interface operating system introduced by Apple in 1984 featuring a 9-inch monochrome monitor.", "Macintosh", ["apple macintosh", "mac"]),
        q(200, "The programming language created by James Gosling at Sun Microsystems in 1995 with the slogan 'Write Once, Run Anywhere'.", "Java", ["java language"]),
        q(200, "The high-level programming language created by Dennis Ritchie at Bell Labs between 1969 and 1973, ancestor of C++.", "C", ["c language"]),
        q(200, "The mechanical computing machine designed by Charles Babbage in the 1830s that anticipated the architecture of modern computers.", "Analytical Engine", ["babbage analytical engine"]),
        q(200, "The open-source mobile operating system based on a modified Linux kernel, purchased by Google in 2005.", "Android", ["android os"]),
        q(200, "The research laboratory in Palo Alto, California, where Ethernet, laser printing, and GUI desktop icons were invented.", "Xerox PARC", ["parc"]),
        q(200, "The high-voltage electrical transformer circuit invented by Nikola Tesla in 1891 producing resonant alternating current.", "Tesla coil", ["tesla resonant transformer"]),
        q(200, "The distributed ledger technology that maintains a decentralized, immutable record of transactions in Bitcoin.", "Blockchain", ["distributed ledger"]),
        q(200, "The 1945 general-purpose electronic digital computer built at the University of Pennsylvania, one of the earliest computers.", "ENIAC", ["electronic numerical integrator and computer"]),
        q(200, "The style sheet language used to describe the presentation and layout of a document written in HTML.", "CSS", ["cascading style sheets"]),
        q(200, "The American inventor who accumulated 1,093 US patents, including the phonograph, motion picture camera, and practical light bulb.", "Thomas Edison", ["edison"]),
        q(200, "The internet addressing protocol with 32-bit addresses written as four numbers separated by periods (e.g. 192.168.1.1).", "IPv4", ["internet protocol version 4"]),
        q(200, "The high-level programming language designed by Brendan Eich in just 10 days in 1995 for Netscape Navigator.", "JavaScript", ["js"]),
        q(200, "The pioneer of computer compilation and rear admiral in the US Navy who popularized the term 'debugging' after finding a moth.", "Grace Hopper", ["hopper"]),
        q(200, "The company that released the first commercial microprocessor, the 4-bit 4004 chip, in 1971.", "Intel", ["intel corporation"]),
        q(200, "The mathematical function that maps input data of arbitrary size to a fixed-size bit string (e.g., SHA-256, MD5).", "Hash function", ["cryptographic hash"]),
        q(200, "The 1977 personal computer manufactured by Commodore that, along with the Apple II and TRS-80, formed the 1977 Trinity.", "Commodore PET", ["pet 2001"]),
        q(200, "The telecommunications networking generation introduced around 2019 that offers high bandwidth and low latency over 4G LTE.", "5G", ["fifth generation"]),
        q(200, "The American telecommunications engineer who invented the optical fiber that revolutionized long-distance data transmission.", "Charles Kao", ["kao"]),
        q(200, "The relational database management query language standardized by ANSI in 1986.", "SQL", ["structured query language", "sequel"]),
        q(200, "The first commercial video game, an electronic arcade table tennis game released by Atari in 1972.", "Pong", ["atari pong"]),
        q(200, "The company founded in 1911 as the Computing-Tabulating-Recording Company, nicknamed 'Big Blue'.", "IBM", ["international business machines"]),
        q(200, "The packet-switching network funded by the US Department of Defense in 1969 that became the technical foundation of the Internet.", "ARPANET", ["arpa net"]),
        q(200, "The multi-user computer operating system developed at Bell Labs in 1969 by Ken Thompson, Dennis Ritchie, and others.", "Unix", ["unix os"]),
        q(200, "The 3.5-inch magnetic storage medium invented by Sony in 1981 with a storage capacity of 1.44 megabytes.", "Floppy disk", ["floppy diskette", "3.5 inch disk"]),
        q(200, "The optical disc standard introduced in 1995 that could hold 4.7 GB of data, succeeding the Compact Disc for movies.", "DVD", ["digital video disc", "digital versatile disc"]),
        q(200, "The cryptographic communication protocol that replaced SSL to provide secure end-to-end transport encryption over the web.", "TLS", ["transport layer security"]),
        q(200, "The company behind the pioneering web browser Mosaic and subsequent commercial Navigator browser.", "Netscape", ["netscape communications"]),
        q(200, "The British inventor who patented the commercial incandescent light bulb in 1878, independently of Edison.", "Joseph Swan", ["swan"]),
        q(200, "The software architecture model where clients communicate with centralized cloud servers rather than peer-to-peer.", "Client-server model", ["client server"]),
        q(200, "The open-source web server software released in 1995 that played a key role in the initial growth of the World Wide Web.", "Apache", ["apache http server"]),
        q(200, "The type of semiconductor memory that retains stored data even after the power supply is turned off.", "Non-volatile memory", ["flash memory", "rom"]),
        q(200, "The mathematical problem or puzzle where a machine must exhibit intelligent behavior indistinguishable from a human.", "Turing test", ["imitation game"])
    ]

    t_300 = [
        q(300, "The 1973 Xerox computer that was the first to use a mouse, desktop GUI, and Ethernet networking.", "Xerox Alto", ["the alto"]),
        q(300, "The inventor of the World Wide Web released the first web browser, named this, on a NeXT computer in 1990.", "WorldWideWeb", ["nexus"]),
        q(300, "The asymmetric public-key cryptosystem invented in 1977 named after Rivest, Shamir, and Adleman.", "RSA", ["rsa encryption"]),
        q(300, "The Canadian computer scientist known as the 'Father of Java' who led its design at Sun Microsystems.", "James Gosling", ["gosling"]),
        q(300, "The theoretical computer science model introduced by Alan Turing in 1936 consisting of an infinite tape and read-write head.", "Turing machine", ["universal turing machine"]),
        q(300, "The 1982 home computer created by Sir Clive Sinclair in the UK that helped launch the British software industry.", "ZX Spectrum", ["sinclair zx spectrum"]),
        q(300, "The programming paradigm based on the concept of 'objects' containing data fields and code procedures.", "Object-oriented programming", ["oop"]),
        q(300, "The company that developed the first commercial spreadsheet software, VisiCalc, for the Apple II in 1979.", "Software Arts", ["visicalc"]),
        q(300, "The founder of the Free Software Foundation who launched the GNU Project in 1983 and created the GPL license.", "Richard Stallman", ["rms"]),
        q(300, "The computer network layer protocol that maps an IP network address to a physical MAC machine address.", "ARP", ["address resolution protocol"]),
        q(300, "The pioneer of relational databases who introduced the relational model of data management at IBM in 1970.", "Edgar F. Codd", ["ted codd"]),
        q(300, "The popular open-source relational database created by Michael Widenius in 1995, named after his daughter My.", "MySQL", ["my sql"]),
        q(300, "The design pattern in software engineering where an object notifies multiple dependent observers of state changes.", "Observer pattern", ["publish-subscribe"]),
        q(300, "The Danish computer scientist who created the C++ programming language at Bell Labs in 1979 as 'C with Classes'.", "Bjarne Stroustrup", ["stroustrup"]),
        q(300, "The memory management process that automatically frees memory occupied by objects that are no longer referenced.", "Garbage collection", ["gc"]),
        q(300, "The American computer scientist who coined the term 'artificial intelligence' in his 1955 Dartmouth proposal.", "John McCarthy", ["mccarthy"]),
        q(300, "The protocol developed by Phil Zimmermann in 1991 that provides cryptographic privacy and authentication for data communication.", "PGP", ["pretty good privacy"]),
        q(300, "The earliest electronic digital programmable calculating device, built at Bletchley Park in 1943 by Tommy Flowers.", "Colossus", ["colossus computer"]),
        q(300, "The Dutch computer scientist who developed shortest-path algorithms and wrote the paper 'Go To Statement Considered Harmful'.", "Edsger Dijkstra", ["dijkstra"]),
        q(300, "The standard character encoding scheme published in 1963 using 7 bits to represent 128 English characters.", "ASCII", ["american standard code for information interchange"]),
        q(300, "The open-source container virtualization platform launched by Solomon Hykes in 2013.", "Docker", ["docker containers"]),
        q(300, "The mathematical concept formalized by Claude Shannon in 1948 that quantifies information content in bits.", "Information entropy", ["shannon entropy"]),
        q(300, "The first internet worm to cause significant disruption across ARPANET, released by a Cornell student in 1988.", "Morris worm", ["robert tappan morris worm"]),
        q(300, "The microkernel operating system written by Andrew Tanenbaum in 1987 that inspired Linus Torvalds to write Linux.", "MINIX", ["minix os"]),
        q(300, "The high-level programming language developed at IBM in 1957 by John Backus, the oldest high-level language still in use.", "Fortran", ["formula translation"]),
        q(300, "The data serialization format based on JavaScript object syntax that largely replaced XML for web APIs.", "JSON", ["javascript object notation"]),
        q(300, "The computer scientist who designed the Python programming language while working at CWI in the Netherlands.", "Guido van Rossum", ["van rossum"]),
        q(300, "The non-volatile storage technology using floating-gate transistors, invented by Fujio Masuoka at Toshiba in 1980.", "Flash memory", ["nand flash"]),
        q(300, "The distributed version control platform founded by Tom Preston-Werner, Chris Wanstrath, and PJ Hyett in 2008.", "GitHub", ["github.com"]),
        q(300, "The data structure consisting of a collection of nodes where each node contains a value and a pointer to the next node.", "Linked list", ["singly linked list"]),
        q(300, "The American electrical engineer who invented Ethernet networking in 1973 while working at Xerox PARC.", "Robert Metcalfe", ["metcalfe"]),
        q(300, "The cryptographic key exchange protocol developed in 1976 that allows two parties to share a secret over an insecure channel.", "Diffie-Hellman", ["diffie hellman key exchange"]),
        q(300, "The American software engineer who developed the BitTorrent peer-to-peer file sharing protocol in 2001.", "Bram Cohen", ["cohen"]),
        q(300, "The computer hardware bus interface that connects motherboards to mass storage devices like hard drives, succeeding PATA.", "SATA", ["serial ata"]),
        q(300, "The computer science concept where a function calls itself directly or indirectly to solve smaller instances of a problem.", "Recursion", ["recursive function"]),
        q(300, "The graphics chip manufacturer founded in 1993 by Jensen Huang, Chris Malachowsky, and Curtis Priem.", "NVIDIA", ["nvidia corporation"]),
        q(300, "The architectural style for distributed hypermedia systems introduced by Roy Fielding in his 2000 doctoral dissertation.", "REST", ["representational state transfer"]),
        q(300, "The American computer scientist who designed the Unix shell sh in 1977 for Version 7 Unix.", "Stephen Bourne", ["bourne shell"]),
        q(300, "The mathematical principle stating that any computable function can be calculated by a Turing machine, formulated in the 1930s.", "Church-Turing thesis", ["church turing"]),
        q(300, "The open-source operating system distribution created by Ian Murdock in 1993 upon which Ubuntu is built.", "Debian", ["debian gnu linux"])
    ]

    t_400 = [
        q(400, "The 1968 landmark computer demonstration by Douglas Engelbart showing the mouse, hypermedia, and video conferencing.", "The Mother of All Demos", ["mother of all demos"]),
        q(400, "The American mathematician and computer scientist who invented Hamming codes for error detection and correction in 1950.", "Richard Hamming", ["hamming"]),
        q(400, "The first computer microprocessor to implement the x86 architecture, released by Intel in 1978.", "Intel 8086", ["8086"]),
        q(400, "The formal semantics verification concept formulated by C.A.R. Hoare in 1969 based on preconditions and postconditions.", "Hoare logic", ["hoare triples"]),
        q(400, "The 1981 quantum computing keynote delivered by this Nobel physicist proposing quantum simulators.", "Richard Feynman", ["feynman"]),
        q(400, "The algorithmic complexity class consisting of decision problems that can be solved by a quantum computer in polynomial time.", "BQP", ["bounded-error quantum polynomial"]),
        q(400, "The microcomputer introduced on the cover of Popular Electronics in January 1975 that launched the microcomputer revolution.", "Altair 8800", ["mits altair"]),
        q(400, "The computer scientist who won the 2011 Turing Award for developing Bayesian networks and causal calculus.", "Judea Pearl", ["pearl"]),
        q(400, "The memory architecture that stores computer program instructions and data in the same physical memory space.", "von Neumann architecture", ["von neumann"]),
        q(400, "The 1965 programming language created by John Kemeny and Thomas Kurtz at Dartmouth to give non-science students computer access.", "BASIC", ["beginners all-purpose symbolic instruction code"]),
        q(400, "The cryptographic hash function designed by the NSA in 1995 that produces a 160-bit hash value, later found collision-vulnerable.", "SHA-1", ["secure hash algorithm 1"]),
        q(400, "The first commercial object-oriented programming language, developed by Adele Goldberg and Alan Kay at Xerox PARC in 1980.", "Smalltalk-80", ["smalltalk"]),
        q(400, "The computer architecture technique where a processor executes instructions before knowing if they are needed (e.g. branch prediction).", "Speculative execution", ["speculation"]),
        q(400, "The American mathematician who formulated Information Theory in his landmark 1948 paper 'A Mathematical Theory of Communication'.", "Claude Shannon", ["shannon"]),
        q(400, "The distributed consensus algorithm published by Leslie Lamport in 1998, famously explained using a fictional Greek island parliament.", "Paxos", ["paxos consensus"]),
        q(400, "The 1976 microprocessor developed by Federico Faggin and Masatoshi Shima at Zilog that powered the ZX Spectrum, ColecoVision, and Game Boy.", "Zilog Z80", ["z80"]),
        q(400, "The fundamental theorem in distributed systems proving that a distributed data store can only provide two of Consistency, Availability, and Partition tolerance.", "CAP theorem", ["brewer's theorem"]),
        q(400, "The functional programming language created in 1958 by John McCarthy based on the lambda calculus, known for parentheses.", "Lisp", ["list processing"]),
        q(400, "The hardware security vulnerability discovered in 2018 in modern CPUs that exploits out-of-order execution to read kernel memory.", "Meltdown", ["meltdown and spectre"]),
        q(400, "The British computer pioneer who designed the Manchester Mark 1 and wrote the first software routine for calculating chess moves.", "Alan Turing", ["turing"]),
        q(400, "The high-performance non-relational database developed at Google using a multi-dimensional sorted map, described in a 2006 paper.", "Bigtable", ["google bigtable"]),
        q(400, "The consensus algorithm introduced by Diego Ongaro and John Ousterhout in 2014 as an understandable alternative to Paxos.", "Raft", ["raft consensus"]),
        q(400, "The 1974 packet-switching protocol specification co-authored by Vint Cerf and Bob Kahn that formed the TCP foundation.", "TCP", ["transmission control protocol"]),
        q(400, "The first widely popular graphical web browser, released by Marc Andreessen and Eric Bina at the NCSA in 1993.", "NCSA Mosaic", ["mosaic browser"]),
        q(400, "The self-balancing binary search tree named after Soviet mathematicians Georgy Adelson-Velsky and Evgenii Landis.", "AVL tree", ["avl"]),
        q(400, "The distributed real-time event streaming platform originally developed by LinkedIn and open-sourced in 2011, named after a writer.", "Apache Kafka", ["kafka"]),
        q(400, "The computer architecture concept where instruction execution is broken down into a series of independent sequential stages.", "Instruction pipelining", ["pipeline"]),
        q(400, "The security model in computer operating systems where processes only have access to resources explicitly granted by cryptographic tokens.", "Capability-based security", ["object capability"]),
        q(400, "The American mathematician who proved the Undecidability of the Halting Problem in 1936 independently of Alan Turing.", "Alonzo Church", ["church"]),
        q(400, "The fast matrix multiplication algorithm published by Volker Strassen in 1969 that broke the O(n^3) barrier with an O(n^2.81) complexity.", "Strassen algorithm", ["strassen"]),
        q(400, "The open-source operating system developed by the University of California, Berkeley that pioneered TCP/IP in Unix.", "BSD", ["berkeley software distribution"]),
        q(400, "The 1994 quantum algorithm developed by an MIT mathematician that can factor large integers in polynomial time on a quantum computer.", "Shor's algorithm", ["peter shor algorithm"]),
        q(400, "The dynamic programming algorithm developed in 1967 for finding the most likely sequence of hidden states in a Hidden Markov Model.", "Viterbi algorithm", ["andrew viterbi"]),
        q(400, "The memory caching algorithm that replaces the cache line that was accessed furthest in the past.", "LRU", ["least recently used"]),
        q(400, "The 1963 interactive computer graphics program created by Ivan Sutherland for his PhD thesis, the ancestor of CAD.", "Sketchpad", ["ivan sutherland sketchpad"]),
        q(400, "The data structure introduced by Burton Bloom in 1970 that provides fast probabilistic set membership testing with zero false negatives.", "Bloom filter", ["bloom filters"]),
        q(400, "The compiler optimization technique that replaces a function call site with the body of the called function to eliminate call overhead.", "Inline expansion", ["function inlining"]),
        q(400, "The first fully automatic digital computer built by Konrad Zuse in Berlin in 1941, destroyed during WWII.", "Zuse Z3", ["z3 computer"]),
        q(400, "The cryptographic zero-knowledge protocol where a prover proves knowledge of a secret to a verifier without revealing the secret itself.", "ZK-SNARK", ["zero knowledge proof", "zkp"]),
        q(400, "The Canadian computer scientist known as the 'Father of Deep Learning' who won the 2018 Turing Award along with LeCun and Bengio.", "Geoffrey Hinton", ["hinton"])
    ]

    t_500 = [
        q(500, "The 1936 formal system in mathematical logic invented by Alonzo Church that uses function abstraction and variable binding, foundation of functional programming.", "Lambda calculus", ["λ-calculus"]),
        q(500, "The memory consistency model in concurrent computing where operations appear to take place instantaneously at a single point in time.", "Linearizability", ["linearizable consistency"]),
        q(500, "The quantum search algorithm developed by Lov Grover in 1996 that can search an unsorted database of N items in O(sqrt(N)) time.", "Grover's algorithm", ["grover search"]),
        q(500, "The 1989 interactive proof system theorem in computational complexity proving that IP equals this complexity class.", "PSPACE", ["ip=pspace"]),
        q(500, "The first operational stored-program computer, developed at the University of Manchester, which successfully ran its first program on June 21, 1948.", "Manchester Baby", ["small-scale experimental machine", "ssem"]),
        q(500, "The theorem in distributed computing published by Fischer, Lynch, and Paterson in 1985 proving that consensus is impossible in an asynchronous network with one faulty node.", "FLP impossibility", ["flp theorem"]),
        q(500, "The pure functional programming language named after an American logician, featuring non-strict lazy evaluation and strong static typing.", "Haskell", ["haskell language", "haskell curry"]),
        q(500, "The structural subtyping system formalized by Luca Cardelli and Peter Wegner in 1985 used in languages like TypeScript.", "System F-sub", ["system f"]),
        q(500, "The computational complexity class of decision problems solvable by a non-deterministic Turing machine in polynomial time.", "NP", ["nondeterministic polynomial"]),
        q(500, "The 1968 paper by Edsger Dijkstra that introduced the semaphore synchronization primitive for concurrent programming.", "Cooperating Sequential Processes", ["semaphores paper"]),
        q(500, "The quantum mechanical principle stating that it is impossible to create an identical copy of an arbitrary unknown quantum state.", "No-cloning theorem", ["no cloning"]),
        q(500, "The type theory developed by Per Martin-Lof in 1972 that establishes the Curry-Howard correspondence between constructive proofs and computer programs.", "Intuitionistic type theory", ["constructive type theory"]),
        q(500, "The 1971 Cook-Levin theorem proved that this specific problem was the very first known NP-complete problem.", "Boolean satisfiability problem", ["sat", "3-sat"]),
        q(500, "The concurrent programming actor model formalized by Carl Hewitt, Peter Bishop, and Richard Steiger in 1973.", "Actor model", ["actor model of concurrent computation"]),
        q(500, "The algorithm designed by Donald Knuth, James Morris, and Vaughan Pratt in 1977 for linear-time string searching.", "KMP algorithm", ["knuth-morris-pratt"]),
        q(500, "The randomized primality testing algorithm published by Michael O. Rabin in 1980 based on Gary Miller's hypothesis.", "Miller-Rabin primality test", ["miller rabin"]),
        q(500, "The self-adjusting binary search tree data structure invented by Daniel Sleator and Robert Tarjan in 1985 with O(log n) amortized cost.", "Splay tree", ["splay trees"]),
        q(500, "The lock-free concurrent data structure technique using Compare-And-Swap (CAS) to achieve wait-free progress guarantees.", "Compare-and-swap", ["cas", "lock-free"]),
        q(500, "The theoretical computer model invented by Emil Post in 1936 independently of Alan Turing's paper.", "Post-Turing machine", ["formulation 1"]),
        q(500, "The 1979 algorithm developed by Soviet mathematician Leonid Khachiyan that proved linear programming is solvable in polynomial time.", "Ellipsoid method", ["khachiyan algorithm"]),
        q(500, "The graph algorithm developed by Robert Tarjan in 1972 for finding strongly connected components in linear time O(V + E).", "Tarjan's algorithm", ["tarjan scc"]),
        q(500, "The persistent data structure introduced by Neil Sarnak and Robert Tarjan in 1986 that preserves previous versions of itself when modified.", "Persistent data structure", ["fully persistent"]),
        q(500, "The computational geometry algorithm published by Ronald Graham in 1972 for computing the convex hull of a finite set of planar points in O(n log n) time.", "Graham scan", ["graham's scan"]),
        q(500, "The mathematical paradox in distributed systems where two generals fail to agree on a time to attack over an unreliable communications link.", "Two Generals' Problem", ["two generals paradox"]),
        q(500, "The 1984 polynomial-time interior point algorithm developed by Narendra Karmarkar for solving linear programming problems.", "Karmarkar's algorithm", ["interior point method"]),
        q(500, "The spatial data structure introduced by Jon Bentley in 1975 for organizing points in a k-dimensional space.", "k-d tree", ["kd-tree"]),
        q(500, "The probabilistic data structure introduced by Philippe Flajolet in 2007 for estimating the cardinality of a multiset with high accuracy.", "HyperLogLog", ["hll"]),
        q(500, "The shortest-path algorithm for graphs with arbitrary edge weights developed by Richard Bellman and Lester Ford in 1958.", "Bellman-Ford algorithm", ["bellman ford"]),
        q(500, "The concurrency control protocol in database management systems that guarantees serializability using read/write locks.", "Two-phase locking", ["2pl"]),
        q(500, "The compiler register allocation algorithm invented by Gregory Chaitin in 1981 based on graph coloring.", "Chaitin's algorithm", ["graph coloring register allocation"]),
        q(500, "The memory management algorithm developed by Donald Knuth that maintains free memory blocks of sizes that are powers of two.", "Buddy memory allocation", ["buddy allocator"]),
        q(500, "The 1974 formal proof technique in programming language theory by Gordon Plotkin that defines language semantics via transition rules.", "Structural operational semantics", ["sos"]),
        q(500, "The tree data structure invented by Rudolf Bayer in 1971 that maintains balanced search keys with variable fan-out, ubiquitous in filesystems and databases.", "B-tree", ["b tree", "b+ tree"]),
        q(500, "The formal method language and interactive theorem prover developed at Inria based on the Calculus of Inductive Constructions, used to verify CompCert.", "Coq", ["coq theorem prover"]),
        q(500, "The quantum error-correcting code developed by Peter Shor in 1995 that encodes one logical qubit into nine physical qubits.", "Shor code", ["9-qubit shor code"]),
        q(500, "The 1982 distributed agreement algorithm developed by Lamport, Shostak, and Pease dealing with components that fail arbitrarily.", "Byzantine Fault Tolerance", ["bft"]),
        q(500, "The universal hash function family introduced by Larry Carter and Mark Wegman in 1979 guaranteeing low collision probability.", "Universal hashing", ["carter wegman"]),
        q(500, "The amortized analysis technique introduced by Robert Tarjan that assigns virtual credits to data structure operations.", "Potential method", ["physicist's method"]),
        q(500, "The algorithmic complexity class introduced by Christos Papadimitriou in 1994 containing total search problems with guaranteed solutions via parity arguments.", "PPA", ["polynomial parity argument"]),
        q(500, "The network flow algorithm developed by Jack Edmonds and Richard Karp in 1972 that implements the Ford-Fulkerson method in O(V E^2) time.", "Edmonds-Karp algorithm", ["edmonds karp"])
    ]

    return t_100 + t_200 + t_300 + t_400 + t_500

if __name__ == "__main__":
    data = get_technology_data()
    print(f"Technology generated: {len(data)} clues")
