"""
Science & Cosmos - 200 Curated Trivia Questions
40 items per tier: $100, $200, $300, $400, $500
"""

def get_questions():
    q = []

    # Value $100 (40 questions)
    v100 = [
        ("The largest planet in our solar system, famous for its Great Red Spot.", "Jupiter", ["planet jupiter"], "Wikipedia - Solar System"),
        ("This gas, chemical symbol O, is essential for human breathing and makes up 21% of Earth's atmosphere.", "Oxygen", ["o2", "oxygen gas"], "Wikipedia - Atmospheric Chemistry"),
        ("The closest star to planet Earth.", "The Sun", ["sun", "sol"], "Wikipedia - Astronomy"),
        ("The boiling point of pure water at standard sea level in degrees Celsius.", "100", ["100 c", "100 degrees", "100 celsius"], "Wikipedia - Thermodynamics"),
        ("The force that pulls objects toward the center of the Earth.", "Gravity", ["gravitation"], "Wikipedia - Classical Mechanics"),
        ("The center part of an atom, containing protons and neutrons.", "Nucleus", ["atomic nucleus"], "Wikipedia - Atomic Physics"),
        ("The green pigment in plants that absorbs light energy for photosynthesis.", "Chlorophyll", ["chlorophil"], "Wikipedia - Plant Biology"),
        ("The hardest known natural mineral on Earth, ranking 10 on the Mohs scale.", "Diamond", ["diamonds"], "Wikipedia - Mineralogy"),
        ("The third planet from the Sun in our solar system.", "Earth", ["planet earth", "the earth"], "Wikipedia - Planetary Science"),
        ("Water in its solid state of matter.", "Ice", ["water ice"], "Wikipedia - Phases of Matter"),
        ("The organ in the human body responsible for pumping blood through the circulatory system.", "Heart", ["the heart", "human heart"], "Wikipedia - Human Anatomy"),
        ("The natural satellite that orbits planet Earth.", "The Moon", ["moon", "luna"], "Wikipedia - Lunar Science"),
        ("The layer of gases surrounding the Earth.", "Atmosphere", ["the atmosphere"], "Wikipedia - Earth Science"),
        ("The two chemical elements that make up a molecule of water.", "Hydrogen and Oxygen", ["hydrogen oxygen", "h and o"], "Wikipedia - Water Molecule"),
        ("The skeleton of the human head that encloses and protects the brain.", "Skull", ["cranium"], "Wikipedia - Human Skeleton"),
        ("The planet known as the 'Red Planet' due to iron oxide on its surface.", "Mars", ["planet mars"], "Wikipedia - Planetary Science"),
        ("The process where liquid water turns into water vapor due to heat.", "Evaporation", ["evaporating"], "Wikipedia - Hydrology"),
        ("The invisible line around the center of the Earth at 0 degrees latitude.", "The Equator", ["equator"], "Wikipedia - Earth Geometry"),
        ("The study of living organisms and life.", "Biology", ["biological sciences"], "Wikipedia - Science"),
        ("The smallest unit of life that can replicate independently.", "Cell", ["the cell", "cells"], "Wikipedia - Cell Biology"),
        ("The large celestial body that revolves around a star and does not produce light itself.", "Planet", ["planets"], "Wikipedia - Astronomy"),
        ("The organ humans use to breathe air into their bodies.", "Lungs", ["lung", "human lungs"], "Wikipedia - Respiratory System"),
        ("The temperature at which pure water freezes in degrees Celsius.", "0", ["0 c", "0 celsius", "zero"], "Wikipedia - Physical Chemistry"),
        ("The galaxy containing our Solar System, visible as a band of light in the night sky.", "The Milky Way", ["milky way", "milky way galaxy"], "Wikipedia - Galactic Astronomy"),
        ("The chemical symbol for table salt, composed of sodium and chlorine.", "NaCl", ["sodium chloride"], "Wikipedia - Common Compounds"),
        ("The basic physical and functional unit of heredity in all living organisms.", "Gene", ["genes", "dna gene"], "Wikipedia - Genetics"),
        ("The instrument used to view distant celestial objects like stars and planets.", "Telescope", ["optical telescope"], "Wikipedia - Observational Astronomy"),
        ("The instrument used to see extremely tiny objects like bacteria and cells.", "Microscope", ["optical microscope"], "Wikipedia - Microscopy"),
        ("The part of the human eye that gives it its color.", "Iris", ["the iris"], "Wikipedia - Ophthalmology"),
        ("The outermost layer of the Earth, resting above the mantle.", "Crust", ["earth crust", "the crust"], "Wikipedia - Geology"),
        ("The molten rock expelled by a volcano during an eruption.", "Lava", ["magma"], "Wikipedia - Volcanology"),
        ("The electrical charge carried by an electron.", "Negative", ["negative charge", "minus"], "Wikipedia - Electromagnetism"),
        ("The electrical charge carried by a proton.", "Positive", ["positive charge", "plus"], "Wikipedia - Subatomic Particles"),
        ("The speed of sound in dry air at room temperature, roughly 343 meters per second, is known as Mach this number.", "Mach 1", ["1", "mach one", "one"], "Wikipedia - Fluid Dynamics"),
        ("The largest organ of the human body by surface area.", "Skin", ["the skin", "integument"], "Wikipedia - Dermatology"),
        ("The phenomenon where the Moon passes directly between the Sun and Earth.", "Solar Eclipse", ["solar eclipse", "eclipse of the sun"], "Wikipedia - Eclipses"),
        ("The phenomenon where the Earth passes directly between the Sun and Moon.", "Lunar Eclipse", ["lunar eclipse"], "Wikipedia - Eclipses"),
        ("The color of visible light with the longest wavelength.", "Red", ["red light"], "Wikipedia - Optics"),
        ("The color of visible light with the shortest wavelength.", "Violet", ["violet light", "purple"], "Wikipedia - Optics"),
        ("The giant storm on Jupiter that has raged for at least 300 years.", "Great Red Spot", ["red spot", "the great red spot"], "Wikipedia - Jupiter")
    ]
    for c, a, acc, s in v100: q.append({"value": 100, "clue": c, "answer": a, "accepted": acc, "source": s})

    # Value $200 (40 questions)
    v200 = [
        ("The process by which green plants convert light energy into chemical energy.", "Photosynthesis", ["photosynthesizing"], "Wikipedia - Plant Physiology"),
        ("The subatomic particle with no electrical charge found in the nucleus of an atom.", "Neutron", ["neutrons"], "Wikipedia - Nuclear Physics"),
        ("The chemical symbol for Gold on the periodic table.", "Au", ["aurum"], "Wikipedia - Elements"),
        ("The chemical symbol for Silver on the periodic table.", "Ag", ["argentum"], "Wikipedia - Elements"),
        ("The chemical symbol for Iron on the periodic table.", "Fe", ["ferrum"], "Wikipedia - Elements"),
        ("The closest planet to the Sun in our solar system.", "Mercury", ["planet mercury"], "Wikipedia - Solar System"),
        ("The hottest planet in our solar system due to a runaway greenhouse effect.", "Venus", ["planet venus"], "Wikipedia - Planetary Science"),
        ("The powerhouse organelle of the eukaryotic cell that produces ATP.", "Mitochondria", ["mitochondrion"], "Wikipedia - Cell Biology"),
        ("The molecule that carries genetic instructions for the development and functioning of all known organisms.", "DNA", ["deoxyribonucleic acid"], "Wikipedia - Molecular Biology"),
        ("The number of chromosomes found in a typical human body cell.", "46", ["23 pairs", "46 chromosomes"], "Wikipedia - Cytogenetics"),
        ("The boundary separating the Earth's crust from the underlying mantle.", "Moho", ["mohorovicic discontinuity", "moho discontinuity"], "Wikipedia - Geophysics"),
        ("The scientific theory that Earth's outer shell is divided into several gliding plates.", "Plate Tectonics", ["continental drift"], "Wikipedia - Geology"),
        ("The law of physics stating that energy cannot be created or destroyed, only transformed.", "Conservation of Energy", ["first law of thermodynamics", "law of conservation of energy"], "Wikipedia - Thermodynamics"),
        ("The SI unit used to measure electrical resistance.", "Ohm", ["ohms"], "Wikipedia - SI Units"),
        ("The SI unit used to measure electric potential difference or electromotive force.", "Volt", ["volts"], "Wikipedia - Electricity"),
        ("The SI unit used to measure electrical current.", "Ampere", ["amp", "amps"], "Wikipedia - Electromagnetism"),
        ("The SI unit used to measure frequency, named after a German physicist.", "Hertz", ["hz"], "Wikipedia - Acoustics"),
        ("The SI unit of force, named after the English mathematician who formulated laws of motion.", "Newton", ["newtons", "n"], "Wikipedia - Classical Mechanics"),
        ("The noble gas that is lighter than air and used to inflate party balloons.", "Helium", ["he", "helium gas"], "Wikipedia - Noble Gases"),
        ("The element with atomic number 1, the most abundant chemical substance in the universe.", "Hydrogen", ["h", "hydrogen gas"], "Wikipedia - Periodic Table"),
        ("The second most abundant element in Earth's crust, widely used in computer microchips.", "Silicon", ["si"], "Wikipedia - Semiconductor Chemistry"),
        ("The primary gas responsible for the greenhouse effect on Venus and global warming on Earth.", "Carbon Dioxide", ["co2"], "Wikipedia - Atmospheric Science"),
        ("The planet famous for its prominent and extensive system of planetary rings.", "Saturn", ["planet saturn"], "Wikipedia - Planetary Astronomy"),
        ("The dwarf planet in the Kuiper belt that was considered the ninth planet until 2006.", "Pluto", ["134340 pluto"], "Wikipedia - Kuiper Belt"),
        ("The branch of science that deals with the composition, structure, and properties of substances.", "Chemistry", ["chemical science"], "Wikipedia - Science"),
        ("The three bones of the human middle ear, known collectively as the ossicles.", "Malleus, Incus, and Stapes", ["hammer anvil stirrup", "malleus incus stapes"], "Wikipedia - Auditory System"),
        ("The longest and strongest bone in the human body, located in the thigh.", "Femur", ["thigh bone"], "Wikipedia - Human Anatomy"),
        ("The pigment that gives human hair, skin, and eyes their color.", "Melanin", ["melanine"], "Wikipedia - Dermatology"),
        ("The term for an animal that feeds exclusively on plants.", "Herbivore", ["herbivorous"], "Wikipedia - Zoology"),
        ("The term for an animal that feeds on both plants and animals.", "Omnivore", ["omnivorous"], "Wikipedia - Zoology"),
        ("The term for an animal that feeds primarily on meat.", "Carnivore", ["carnivorous"], "Wikipedia - Zoology"),
        ("The atmospheric layer that contains the protective ozone layer.", "Stratosphere", ["stratospheric layer"], "Wikipedia - Atmospheric Layers"),
        ("The lowest layer of Earth's atmosphere, where almost all weather occurs.", "Troposphere", ["tropospheric layer"], "Wikipedia - Meteorology"),
        ("The bending of light as it passes from one transparent substance into another.", "Refraction", ["light refraction"], "Wikipedia - Optics"),
        ("The bouncing back of a light wave or sound wave when it hits a surface.", "Reflection", ["light reflection"], "Wikipedia - Optics"),
        ("The state of matter characterized by ionized gas containing free electrons and ions.", "Plasma", ["plasma state"], "Wikipedia - Physics"),
        ("The scale used to measure the acidity or alkalinity of an aqueous solution.", "pH scale", ["ph", "ph value"], "Wikipedia - Analytical Chemistry"),
        ("A substance with a pH less than 7 is classified as this.", "Acid", ["acidic"], "Wikipedia - Chemistry"),
        ("A substance with a pH greater than 7 is classified as this.", "Base", ["alkaline", "basic"], "Wikipedia - Chemistry"),
        ("The type of rock formed by the cooling and solidification of magma or lava.", "Igneous", ["igneous rock"], "Wikipedia - Petrology")
    ]
    for c, a, acc, s in v200: q.append({"value": 200, "clue": c, "answer": a, "accepted": acc, "source": s})

    # Value $300 (40 questions)
    v300 = [
        ("The letter representing the speed of light in vacuum in Albert Einstein's equation E=mc².", "c", ["the letter c", "speed of light"], "Wikipedia - Theory of Relativity"),
        ("The English physician who discovered penicillin in 1928.", "Alexander Fleming", ["fleming"], "Wikipedia - Medical History"),
        ("The English naturalist who published 'On the Origin of Species' in 1859.", "Charles Darwin", ["darwin"], "Wikipedia - Evolutionary Biology"),
        ("The Polish-French physicist who was the first woman to win a Nobel Prize and won in both Physics and Chemistry.", "Marie Curie", ["curie", "madame curie"], "Wikipedia - Nobel Laureates"),
        ("The German theoretical physicist who originated quantum theory and has a fundamental constant named after him.", "Max Planck", ["planck"], "Wikipedia - Quantum Mechanics"),
        ("The Austrian monk considered the father of modern genetics for his hybridization experiments on pea plants.", "Gregor Mendel", ["mendel"], "Wikipedia - Genetics"),
        ("The Danish physicist who introduced the model of the atom with electrons orbiting in discrete energy levels.", "Niels Bohr", ["bohr"], "Wikipedia - Quantum Physics"),
        ("The element with atomic number 6, which forms the basis for all known organic life.", "Carbon", ["c"], "Wikipedia - Organic Chemistry"),
        ("The dense celestial remnant of a massive star that collapsed under gravity where not even light can escape.", "Black Hole", ["black holes", "stellar black hole"], "Wikipedia - Astrophysics"),
        ("The spiral galaxy closest to the Milky Way, expected to collide with our galaxy in about 4.5 billion years.", "Andromeda Galaxy", ["andromeda", "m31"], "Wikipedia - Galactic Astronomy"),
        ("The theoretical temperature at which all molecular motion ceases, equivalent to 0 Kelvin or -273.15 °C.", "Absolute Zero", ["zero kelvin"], "Wikipedia - Cryogenics"),
        ("The radioactive element named after the Greek Titan who stole fire from Mount Olympus.", "Promethium", ["pm"], "Wikipedia - Periodic Table"),
        ("The process of cell division that results in four genetically diverse daughter cells with half the original chromosomes.", "Meiosis", ["meiotic division"], "Wikipedia - Cytology"),
        ("The process of cell division that results in two genetically identical daughter cells.", "Mitosis", ["mitotic division"], "Wikipedia - Cytology"),
        ("The type of chemical bond formed by the electrostatic attraction between oppositely charged ions.", "Ionic Bond", ["electrovalent bond"], "Wikipedia - Chemical Bonds"),
        ("The type of chemical bond where pairs of electrons are shared between atoms.", "Covalent Bond", ["covalent bonding"], "Wikipedia - Chemical Bonds"),
        ("The Russian chemist who formulated the Periodic Law and created the first Periodic Table of Elements.", "Dmitri Mendeleev", ["mendeleev"], "Wikipedia - Chemistry Pioneers"),
        ("The point in an orbit where a celestial body is closest to the Earth.", "Perigee", ["periapsis"], "Wikipedia - Orbital Mechanics"),
        ("The point in an orbit where a celestial body is farthest from the Earth.", "Apogee", ["apoapsis"], "Wikipedia - Orbital Mechanics"),
        ("The point in an orbit around the Sun where a planet is closest to the Sun.", "Perihelion", ["perihelion point"], "Wikipedia - Celestial Mechanics"),
        ("The point in an orbit around the Sun where a planet is farthest from the Sun.", "Aphelion", ["aphelion point"], "Wikipedia - Celestial Mechanics"),
        ("The medical imaging technique that uses strong magnetic fields and radio waves to generate images of organs.", "MRI", ["magnetic resonance imaging"], "Wikipedia - Medical Imaging"),
        ("The blood vessels that carry oxygenated blood away from the heart to the rest of the body.", "Arteries", ["artery"], "Wikipedia - Circulatory System"),
        ("The blood vessels that return deoxygenated blood back toward the heart.", "Veins", ["vein"], "Wikipedia - Cardiovascular System"),
        ("The microscopic blood vessels where the exchange of water, oxygen, and nutrients occurs between blood and tissues.", "Capillaries", ["capillary"], "Wikipedia - Microcirculation"),
        ("The region of the solar system beyond the orbit of Neptune filled with icy bodies and dwarf planets.", "Kuiper Belt", ["edgeworth-kuiper belt"], "Wikipedia - Planetary Astronomy"),
        ("The hypothetical spherical cloud of predominantly icy planetesimals surrounding the solar system.", "Oort Cloud", ["the oort cloud"], "Wikipedia - Solar System Outer Limits"),
        ("The unit of astronomical distance equal to approximately 3.26 light-years.", "Parsec", ["parsecs", "pc"], "Wikipedia - Astrometry"),
        ("The measure of disorder or randomness in a closed thermodynamic system.", "Entropy", ["thermodynamic entropy"], "Wikipedia - Second Law of Thermodynamics"),
        ("The English scientist who discovered the electromagnetic induction law and built the first electric dynamo.", "Michael Faraday", ["faraday"], "Wikipedia - Electromagnetism"),
        ("The Scottish mathematician and physicist who formulated the classical theory of electromagnetic radiation.", "James Clerk Maxwell", ["maxwell"], "Wikipedia - Classical Physics"),
        ("The elementary particle that is the quantum of the electromagnetic field, including light.", "Photon", ["photons"], "Wikipedia - Quantum Electrodynamics"),
        ("The subatomic particle that experiences the strong force, composed of quarks (such as protons and neutrons).", "Hadron", ["hadrons"], "Wikipedia - Particle Physics"),
        ("The elementary particles of matter that combine in groups of three to form protons and neutrons.", "Quarks", ["quark"], "Wikipedia - Standard Model"),
        ("The Italian scientist who used a telescope to discover four large moons of Jupiter in 1610.", "Galileo Galilei", ["galileo"], "Wikipedia - Scientific Revolution"),
        ("The German astronomer who formulated three laws of planetary motion describing elliptical orbits.", "Johannes Kepler", ["kepler"], "Wikipedia - Astronomy"),
        ("The ancient Greek mathematician who famously shouted 'Eureka!' after discovering the principle of buoyancy in a bath.", "Archimedes", ["archimedes of syracuse"], "Wikipedia - Classical Physics"),
        ("The radioactive isotope of carbon used by archaeologists to date organic materials up to 50,000 years old.", "Carbon-14", ["c-14", "carbon 14", "radiocarbon"], "Wikipedia - Radiometric Dating"),
        ("The geological era known as the 'Age of Reptiles' that spanned from 252 to 66 million years ago.", "Mesozoic Era", ["mesozoic"], "Wikipedia - Geologic Time Scale"),
        ("The geological epoch in which we currently live, beginning approximately 11,700 years ago after the last Ice Age.", "Holocene", ["holocene epoch"], "Wikipedia - Geochronology")
    ]
    for c, a, acc, s in v300: q.append({"value": 300, "clue": c, "answer": a, "accepted": acc, "source": s})

    # Value $400 (40 questions)
    v400 = [
        ("The principle in quantum mechanics formulated by Werner Heisenberg stating that position and momentum cannot both be measured precisely.", "Uncertainty Principle", ["heisenberg uncertainty principle"], "Wikipedia - Quantum Physics"),
        ("The theoretical boundary surrounding a black hole beyond which nothing, not even light, can escape.", "Event Horizon", ["the event horizon"], "Wikipedia - General Relativity"),
        ("The radius of the event horizon for a non-rotating black hole, named after a German astronomer.", "Schwarzschild Radius", ["schwarzschild radius"], "Wikipedia - Black Hole Physics"),
        ("The only metallic element on the periodic table that is liquid at standard room temperature and pressure.", "Mercury", ["quicksilver", "hg"], "Wikipedia - Elements"),
        ("The non-metallic halogen element that is a reddish-brown liquid at room temperature.", "Bromine", ["br"], "Wikipedia - Halogens"),
        ("The rare noble gas with atomic number 86 that is a radioactive health hazard in home basements.", "Radon", ["rn"], "Wikipedia - Radiation Protection"),
        ("The organelle responsible for sorting, modifying, and packaging proteins within eukaryotic cells.", "Golgi Apparatus", ["golgi body", "golgi complex"], "Wikipedia - Cellular Biology"),
        ("The enzyme that unzips the double-stranded DNA helix during DNA replication.", "DNA Helicase", ["helicase"], "Wikipedia - Biochemistry"),
        ("The enzyme that synthesizes new DNA molecules by assembling nucleotides complementary to the template strand.", "DNA Polymerase", ["polymerase"], "Wikipedia - Genetics"),
        ("The constant ratio of a circle's circumference to its diameter, approximately 3.14159.", "Pi", ["pi number", "3.14"], "Wikipedia - Mathematics"),
        ("The base of the natural logarithm, an irrational mathematical constant approximately equal to 2.71828.", "e", ["eulers number", "constant e"], "Wikipedia - Mathematical Constants"),
        ("The fundamental constant symbolized by 'G' in Isaac Newton's law of universal gravitation.", "Gravitational Constant", ["big g", "newton gravitational constant"], "Wikipedia - Gravitation"),
        ("The value of acceleration due to gravity at Earth's surface in meters per second squared.", "9.8", ["9.8 m/s2", "9.81", "9.8 m/s^2"], "Wikipedia - Earth Gravity"),
        ("The American astronomer who demonstrated in 1929 that the universe is expanding, and has a space telescope named after him.", "Edwin Hubble", ["hubble"], "Wikipedia - Observational Cosmology"),
        ("The space observatory launched on Christmas Day 2021 that orbits the Sun at the Second Lagrange Point (L2).", "James Webb Space Telescope", ["jwst", "james webb"], "Wikipedia - Space Telescopes"),
        ("The point in space where the gravitational forces of two large bodies balance the centrifugal force felt by a third smaller object.", "Lagrange Point", ["lagrangian point", "l-point"], "Wikipedia - Orbital Mechanics"),
        ("The law stating that the volume of a given mass of gas is inversely proportional to its pressure at constant temperature.", "Boyle's Law", ["boyle law"], "Wikipedia - Gas Laws"),
        ("The law stating that the volume of a gas is directly proportional to its absolute temperature at constant pressure.", "Charles's Law", ["charles law"], "Wikipedia - Gas Laws"),
        ("The ideal gas law equation relating pressure, volume, amount of substance, gas constant, and temperature.", "PV=nRT", ["pv = nrt", "ideal gas law"], "Wikipedia - Thermodynamics"),
        ("The number of elementary entities in one mole of a substance, approximately 6.022 x 10²³.", "Avogadro's Number", ["avogadro constant"], "Wikipedia - Physical Constants"),
        ("The effect where an observer perceives a shift in frequency of a wave due to relative motion between source and observer.", "Doppler Effect", ["doppler shift"], "Wikipedia - Wave Mechanics"),
        ("The redshift observed in light from distant galaxies that provides primary evidence for the expansion of the universe.", "Cosmological Redshift", ["hubble redshift", "redshift"], "Wikipedia - Cosmology"),
        ("The electromagnetic radiation left over from the Big Bang that permeates the entire universe with a temperature of 2.7 Kelvin.", "Cosmic Microwave Background", ["cmb", "cmbr"], "Wikipedia - Physical Cosmology"),
        ("The hypothetical form of matter that does not interact with light but accounts for approximately 85% of matter in the universe.", "Dark Matter", ["dark matter"], "Wikipedia - Astrophysics"),
        ("The mysterious force hypothesized to account for the accelerating expansion of the universe, comprising 68% of the universe.", "Dark Energy", ["dark energy"], "Wikipedia - Cosmology"),
        ("The property of certain materials to conduct electrical current with zero resistance when cooled below a critical temperature.", "Superconductivity", ["superconductor"], "Wikipedia - Solid State Physics"),
        ("The quantum mechanical phenomenon where a particle passes through a potential energy barrier higher than its kinetic energy.", "Quantum Tunneling", ["tunneling effect"], "Wikipedia - Quantum Mechanics"),
        ("The phenomenon where quantum states of two or more particles become intertwined regardless of distance between them.", "Quantum Entanglement", ["entanglement"], "Wikipedia - Quantum Information"),
        ("The thought experiment involving a cat in a box that is simultaneously alive and dead until observed.", "Schrödinger's Cat", ["schrodinger cat", "schrodingers cat"], "Wikipedia - Quantum Paradoxes"),
        ("The Austrian physicist who formulated the wave equation that won him the 1933 Nobel Prize in Physics.", "Erwin Schrödinger", ["schrodinger", "schroedinger"], "Wikipedia - Quantum Theory"),
        ("The British theoretical physicist who formulated relativistic quantum mechanics and predicted the existence of antimatter.", "Paul Dirac", ["dirac"], "Wikipedia - Theoretical Physics"),
        ("The antiparticle corresponding to the electron, having the same mass but a positive electric charge.", "Positron", ["anti-electron"], "Wikipedia - Antimatter"),
        ("The fundamental boson discovered at CERN's Large Hadron Collider in 2012 that gives mass to other elementary particles.", "Higgs Boson", ["god particle", "higgs"], "Wikipedia - Particle Physics"),
        ("The British physicist after whom the Higgs boson particle is named.", "Peter Higgs", ["higgs"], "Wikipedia - Nobel Laureates in Physics"),
        ("The largest particle physics laboratory in the world, located near Geneva on the Franco-Swiss border.", "CERN", ["european organization for nuclear research"], "Wikipedia - Particle Accelerators"),
        ("The underground 27-kilometer ring particle collider at CERN.", "Large Hadron Collider", ["lhc"], "Wikipedia - Experimental Physics"),
        ("The specialized organ in snakes and lizards located in the roof of the mouth used for detecting airborne chemical scents.", "Jacobson's Organ", ["vomeronasal organ"], "Wikipedia - Reptile Anatomy"),
        ("The type of symbiotic relationship where one organism benefits while the other is neither helped nor harmed.", "Commensalism", ["commensal"], "Wikipedia - Ecology"),
        ("The type of symbiotic relationship where both participating organisms benefit mutually.", "Mutualism", ["mutualistic symbiosis"], "Wikipedia - Symbiosis"),
        ("The type of symbiotic relationship where one organism benefits at the direct expense and detriment of the host.", "Parasitism", ["parasitic"], "Wikipedia - Ecology")
    ]
    for c, a, acc, s in v400: q.append({"value": 400, "clue": c, "answer": a, "accepted": acc, "source": s})

    # Value $500 (40 questions)
    v500 = [
        ("The maximum mass of a stable white dwarf star, approximately 1.44 solar masses, above which it collapses into a neutron star or black hole.", "Chandrasekhar Limit", ["chandrasekhar mass"], "Wikipedia - Stellar Evolution"),
        ("The Indian-American astrophysicist who was awarded the 1983 Nobel Prize for determining the white dwarf mass limit.", "Subrahmanyan Chandrasekhar", ["chandrasekhar"], "Wikipedia - Nobel Laureates"),
        ("A rapidly rotating magnetized neutron star that emits beams of electromagnetic radiation out of its magnetic poles.", "Pulsar", ["pulsars"], "Wikipedia - Neutron Stars"),
        ("The British astrophysicist who discovered the first radio pulsar in 1967 as a graduate student.", "Jocelyn Bell Burnell", ["bell burnell", "jocelyn bell"], "Wikipedia - Radio Astronomy"),
        ("The extremely luminous active galactic nucleus powered by a supermassive black hole at the center of a distant galaxy.", "Quasar", ["quasars", "quasi-stellar radio source"], "Wikipedia - High-Energy Astrophysics"),
        ("The supermassive black hole situated at the galactic center of the Milky Way galaxy.", "Sagittarius A*", ["sagittarius a star", "sgr a*"], "Wikipedia - Galactic Center"),
        ("The first black hole ever directly imaged by the Event Horizon Telescope collaboration in 2019, located in this galaxy.", "Messier 87", ["m87", "m87 galaxy"], "Wikipedia - Event Horizon Telescope"),
        ("The process in stellar nucleosynthesis by which helium nuclei fuse to form carbon-12 in red giant stars.", "Triple-Alpha Process", ["triple alpha"], "Wikipedia - Nuclear Astrophysics"),
        ("The English astronomer who predicted the existence of an excited resonance state of Carbon-12 to explain its abundance.", "Fred Hoyle", ["hoyle"], "Wikipedia - Nucleosynthesis"),
        ("The transition zone in the ocean where temperature decreases rapidly with increasing depth.", "Thermocline", ["thermal layer"], "Wikipedia - Oceanography"),
        ("The transition zone in water bodies where salinity changes sharply with depth.", "Halocline", ["salinity gradient"], "Wikipedia - Oceanography"),
        ("The transition zone in water bodies where density changes drastically with depth.", "Pycnocline", ["density gradient"], "Wikipedia - Oceanography"),
        ("The cell organelle that contains digestive enzymes to break down waste materials and cellular debris.", "Lysosome", ["lysosomes"], "Wikipedia - Cell Biology"),
        ("The organelle that contains catalase and oxidases to break down hydrogen peroxide and fatty acids.", "Peroxisome", ["peroxisomes"], "Wikipedia - Cell Biology"),
        ("The five nitrogenous bases that form the genetic code: Adenine, Guanine, Cytosine, Thymine, and this one found only in RNA.", "Uracil", ["u"], "Wikipedia - Nucleic Acids"),
        ("The nitrogenous base that pairs with Cytosine in DNA via three hydrogen bonds.", "Guanine", ["g"], "Wikipedia - DNA Base Pairing"),
        ("The nitrogenous base that pairs with Adenine in DNA via two hydrogen bonds.", "Thymine", ["t"], "Wikipedia - DNA Base Pairing"),
        ("The Dutch scientist who discovered bacteria, protozoa, and spermatozoa using single-lens microscopes he built himself.", "Antonie van Leeuwenhoek", ["leeuwenhoek"], "Wikipedia - Microbiology Pioneers"),
        ("The German physician recognized as the founder of modern bacteriology who identified the causative agents of tuberculosis, cholera, and anthrax.", "Robert Koch", ["koch"], "Wikipedia - Bacteriology"),
        ("The set of four criteria established in 1884 to establish a causative relationship between a microbe and a disease.", "Koch's Postulates", ["kochs postulates"], "Wikipedia - Medical Microbiology"),
        ("The rare heavy metal element with atomic number 76 that is the densest naturally occurring element on Earth.", "Osmium", ["os"], "Wikipedia - Chemical Elements"),
        ("The second densest naturally occurring element, with atomic number 77, found in high concentrations at the K-Pg boundary layer.", "Iridium", ["ir"], "Wikipedia - Alvarez Hypothesis"),
        ("The father-son scientific duo who proposed in 1980 that an asteroid impact caused the extinction of the dinosaurs based on iridium anomalies.", "Luis and Walter Alvarez", ["alvarez", "alvarez team"], "Wikipedia - Cretaceous Extinction"),
        ("The massive 180-kilometer impact crater buried underneath the Yucatán Peninsula associated with the dinosaur extinction event.", "Chicxulub Crater", ["chicxulub"], "Wikipedia - Impact Craters"),
        ("The geological boundary layer marking the mass extinction 66 million years ago separating the Cretaceous and Paleogene periods.", "K-Pg Boundary", ["k-t boundary", "cretaceous paleogene boundary"], "Wikipedia - Stratigraphy"),
        ("The principle stating that no two identical fermions may occupy the same quantum state simultaneously.", "Pauli Exclusion Principle", ["pauli exclusion"], "Wikipedia - Quantum Mechanics"),
        ("The Austrian theoretical physicist who formulated the Exclusion Principle and won the 1945 Nobel Prize.", "Wolfgang Pauli", ["pauli"], "Wikipedia - Nobel Laureates"),
        ("The class of particles that obey Fermi-Dirac statistics and have half-integer spin (like electrons and quarks).", "Fermions", ["fermion"], "Wikipedia - Particle Physics"),
        ("The class of particles that obey Bose-Einstein statistics and have integer spin (like photons and gluons).", "Bosons", ["boson"], "Wikipedia - Particle Physics"),
        ("The state of matter formed when bosons are cooled to temperatures near absolute zero and occupy the same ground quantum state.", "Bose-Einstein Condensate", ["bec"], "Wikipedia - States of Matter"),
        ("The gauge bosons that act as the exchange particles for the strong interaction between quarks.", "Gluons", ["gluon"], "Wikipedia - Quantum Chromodynamics"),
        ("The three types of neutrinos in the Standard Model: electron neutrino, muon neutrino, and this third flavor.", "Tau Neutrino", ["tau"], "Wikipedia - Leptons"),
        ("The phenomenon where neutrinos spontaneously change their flavor as they propagate through space.", "Neutrino Oscillation", ["neutrino flavor oscillation"], "Wikipedia - Particle Physics"),
        ("The massive underground neutrino observatory located in an abandoned zinc mine in Hida, Gifu, Japan.", "Super-Kamiokande", ["super-k", "kamioka"], "Wikipedia - Neutrino Detection"),
        ("The equation that governs the rate of chemical reactions as a function of temperature and activation energy.", "Arrhenius Equation", ["arrhenius"], "Wikipedia - Chemical Kinetics"),
        ("The theoretical point in a substance's phase diagram where liquid, vapor, and solid phases coexist in thermodynamic equilibrium.", "Triple Point", ["the triple point"], "Wikipedia - Phase Diagrams"),
        ("The temperature and pressure beyond which a gas cannot be liquefied, resulting in a supercritical fluid.", "Critical Point", ["critical temperature and pressure"], "Wikipedia - Thermodynamics"),
        ("The biological clock mechanism controlled by the suprachiasmatic nucleus in the brain that oscillates on a ~24-hour cycle.", "Circadian Rhythm", ["circadian clock"], "Wikipedia - Chronobiology"),
        ("The master neuroendocrine gland located at the base of the brain that regulates other endocrine glands.", "Pituitary Gland", ["hypophysis"], "Wikipedia - Endocrinology"),
        ("The small endocrine gland in the brain that produces melatonin to modulate sleep patterns.", "Pineal Gland", ["epiphysis cerebri"], "Wikipedia - Human Neuroanatomy")
    ]
    for c, a, acc, s in v500: q.append({"value": 500, "clue": c, "answer": a, "accepted": acc, "source": s})

    return q

if __name__ == "__main__":
    qs = get_questions()
    print("Science questions:", len(qs))
