"""
Pop Culture & Music - 200 Curated Trivia Questions
40 items per tier: $100, $200, $300, $400, $500
"""

def get_questions():
    q = []
    # $100 tier (40 items)
    items_100 = [
        ("The 'King of Pop' whose 1982 album Thriller remains the best-selling studio album of all time.", "Michael Jackson", ["jackson", "mj"], "Wikipedia - Pop Music"),
        ("The Liverpool rock quartet composed of John Lennon, Paul McCartney, George Harrison, and Ringo Starr.", "The Beatles", ["beatles", "the fab four"], "Wikipedia - British Rock"),
        ("The pop superstar whose record-breaking 'Eras Tour' became the first tour in history to gross over $1 billion.", "Taylor Swift", ["swift"], "Wikipedia - Contemporary Pop"),
        ("The flamboyant Queen frontman who sang 'Bohemian Rhapsody' and captivated Live Aid in 1985.", "Freddie Mercury", ["mercury", "farrokh bulsara"], "Wikipedia - Rock Legends"),
        ("The 'King of Rock and Roll' famous for his swivel hips, blue suede shoes, and Graceland mansion in Memphis.", "Elvis Presley", ["elvis"], "Wikipedia - Rock and Roll Pioneers"),
        ("The pop star known for hits like 'Bad Romance', 'Poker Face', and starring in 'A Star Is Born'.", "Lady Gaga", ["gaga", "stefani germanotta"], "Wikipedia - Modern Pop"),
        ("The Barbadian singer who performed the 2023 Super Bowl halftime show and founded the Fenty Beauty empire.", "Rihanna", ["robyn rihanna fenty"], "Wikipedia - Contemporary R&B"),
        ("The Canadian rapper and former Degrassi star known for 'Hotline Bling', 'God's Plan', and OVO Sound.", "Drake", ["aubrey drake graham"], "Wikipedia - Hip Hop"),
        ("The legendary British singer-songwriter known as the 'Rocket Man' who performed 'Candle in the Wind 1997'.", "Elton John", ["sir elton john"], "Wikipedia - Pop Rock"),
        ("The Seattle grunge band fronted by Kurt Cobain that defined 1990s alternative rock with 'Smells Like Teen Spirit'.", "Nirvana", ["nirvana band"], "Wikipedia - Grunge Rock"),
        ("The British singer-songwriter with soulful hits like 'Rolling in the Deep', 'Someone Like You', and 'Hello'.", "Adele", ["adele adkins"], "Wikipedia - Soul Pop"),
        ("The 'Queen of Pop' who topped charts with 'Like a Virgin', 'Material Girl', and 'Vogue'.", "Madonna", ["madonna ciccone"], "Wikipedia - 1980s Pop"),
        ("The Jamaican reggae icon behind universal anthems like 'No Woman, No Cry', 'One Love', and 'Could You Be Loved'.", "Bob Marley", ["marley"], "Wikipedia - Reggae Heritage"),
        ("The legendary guitarist who played an incendiary feedback-laden rendition of 'The Star-Spangled Banner' at Woodstock.", "Jimi Hendrix", ["hendrix"], "Wikipedia - Rock Guitarists"),
        ("The hip-hop icon and business mogul married to Beyoncé, with 24 Grammy Awards and hits like 'Empire State of Mind'.", "Jay-Z", ["jay z", "shawn carter"], "Wikipedia - Hip Hop Royalty"),
        ("The 'Queen Bey' who rose to fame with Destiny's Child before releasing solo masterpieces like 'Lemonade' and 'Renaissance'.", "Beyoncé", ["beyonce", "beyonce knowles"], "Wikipedia - Contemporary R&B"),
        ("The 1969 music festival in upstate New York that drew 400,000 peaceful attendees under the slogan '3 Days of Peace & Music'.", "Woodstock", ["woodstock festival"], "Wikipedia - Music Festivals"),
        ("The Swedish pop sensation group composed of Agnetha, Björn, Benny, and Anni-Frid that won Eurovision with 'Waterloo'.", "ABBA", ["abba group"], "Wikipedia - Eurovision & Pop"),
        ("The young pop prodigy who became a global sensation with 'Ocean Eyes', 'Bad Guy', and multiple Album of the Year Grammys.", "Billie Eilish", ["eilish"], "Wikipedia - Alternative Pop"),
        ("The British rock band led by Mick Jagger and Keith Richards known as 'The World's Greatest Rock and Roll Band'.", "The Rolling Stones", ["rolling stones"], "Wikipedia - Classic Rock"),
        ("The multi-instrumentalist Minneapolis icon who created 'Purple Rain', 'When Doves Cry', and the Minneapolis sound.", "Prince", ["prince rogers nelson"], "Wikipedia - Pop Funk"),
        ("The musical instrument with 88 black and white keys, hammers, and strings, categorized as both stringed and percussion.", "Piano", ["pianoforte"], "Wikipedia - Musical Instruments"),
        ("The American folk-rock poet who won the 2016 Nobel Prize in Literature for songs like 'Blowin' in the Wind'.", "Bob Dylan", ["dylan", "robert zimmerman"], "Wikipedia - Folk Rock"),
        ("The Detroit music record label founded in 1959 by Berry Gordy that launched Stevie Wonder, Diana Ross, and Marvin Gaye.", "Motown", ["motown records", "hitsville usa"], "Wikipedia - Soul Music"),
        ("The English rock band composed of Robert Plant, Jimmy Page, John Paul Jones, and John Bonham who recorded 'Stairway to Heaven'.", "Led Zeppelin", ["zeppelin"], "Wikipedia - Hard Rock"),
        ("The musical theater composer behind mega-musicals The Phantom of the Opera, Cats, and Evita.", "Andrew Lloyd Webber", ["lloyd webber"], "Wikipedia - Musical Theatre"),
        ("The country music legend known as the 'Man in Black' who recorded live prison albums at Folsom and San Quentin.", "Johnny Cash", ["cash"], "Wikipedia - Country Music"),
        ("The brass instrument with three piston valves commonly played by Louis Armstrong and Miles Davis in jazz.", "Trumpet", ["trumpets"], "Wikipedia - Jazz Instruments"),
        ("The annual European international song competition that launched ABBA, Céline Dion, and Måneskin.", "Eurovision Song Contest", ["eurovision"], "Wikipedia - Eurovision"),
        ("The Latin pop star from Puerto Rico whose 2017 collaboration 'Despacito' with Daddy Yankee tied the Billboard Hot 100 record.", "Luis Fonsi", ["fonsi"], "Wikipedia - Latin Pop"),
        ("The musical instrument played with a horsehair bow that has four strings tuned in perfect fifths (G, D, A, E).", "Violin", ["fiddle"], "Wikipedia - String Instruments"),
        ("The American pop superstar who wore a notorious dress made of raw beef at the 2010 MTV Video Music Awards.", "Lady Gaga", ["gaga"], "Wikipedia - MTV VMAs"),
        ("The English virtual cartoon band created in 1998 by Damon Albarn and comic artist Jamie Hewlett, with characters 2-D and Murdoc.", "Gorillaz", ["gorillas"], "Wikipedia - Alternative Rock"),
        ("The heavy metal band fronted by Ozzy Osbourne that recorded 'Paranoid' and 'Iron Man', pioneering the heavy metal genre.", "Black Sabbath", ["sabbath"], "Wikipedia - Heavy Metal"),
        ("The 1970s dance music genre characterized by four-on-the-floor beats, synthesizers, and mirror balls at Studio 54.", "Disco", ["disco music"], "Wikipedia - Dance Music"),
        ("The American singer-songwriter behind hits like 'Just the Way You Are', 'Uptown Funk', and Silk Sonic.", "Bruno Mars", ["mars", "peter hernandez"], "Wikipedia - Contemporary Pop"),
        ("The iconic guitar brand created by Leo Fender that produced the Stratocaster and Telecaster electric guitars.", "Fender", ["fender musical instruments"], "Wikipedia - Guitars"),
        ("The southern hip-hop duo composed of André 3000 and Big Boi that recorded 'Hey Ya!' and 'Ms. Jackson'.", "Outkast", ["outkast duo"], "Wikipedia - Southern Hip Hop"),
        ("The Australian hard rock band formed by brothers Malcolm and Angus Young, famous for 'Back in Black' and 'Highway to Hell'.", "AC/DC", ["acdc"], "Wikipedia - Hard Rock"),
        ("The female rapper who broke out with 'Bodak Yellow', 'WAP', and became the first solo female rapper with multiple Hot 100 #1s.", "Cardi B", ["belcalis marlenis almánzar"], "Wikipedia - Hip Hop"),
    ]
    for clue, ans, acc, src in items_100:
        q.append({"value": 100, "clue": clue, "answer": ans, "accepted": acc, "source": src})

    # $200 tier (40 items)
    items_200 = [
        ("The Austrian classical child prodigy who composed over 600 works including 'The Magic Flute' and 'Requiem' before dying at age 35.", "Wolfgang Amadeus Mozart", ["mozart"], "Wikipedia - Classical Music"),
        ("The German composer who composed his monumental Ninth Symphony (featuring 'Ode to Joy') while almost completely deaf.", "Ludwig van Beethoven", ["beethoven"], "Wikipedia - Western Classical Music"),
        ("Pink Floyd's 1973 concept album featuring a light prism on its iconic black album sleeve cover.", "The Dark Side of the Moon", ["dark side of the moon"], "Wikipedia - Progressive Rock"),
        ("The 18th-century Italian violin maker whose handcrafted string instruments like the 'Messiah' sell for tens of millions of dollars.", "Antonio Stradivari", ["stradivari", "stradivarius"], "Wikipedia - Master Luthiers"),
        ("The jazz trumpet pioneer nicknamed 'Satchmo' who sang 'What a Wonderful World' with his raspy gravel voice.", "Louis Armstrong", ["armstrong", "satchmo"], "Wikipedia - Jazz Greats"),
        ("The British rock band led by Freddie Mercury that performed a seamless 21-minute set at Wembley Stadium during Live Aid.", "Queen", ["queen band"], "Wikipedia - Live Aid 1985"),
        ("The legendary trumpeter who recorded the 1959 best-selling jazz album of all time, 'Kind of Blue'.", "Miles Davis", ["davis"], "Wikipedia - Modal Jazz"),
        ("The Welsh singer with powerhouse vocals on James Bond themes 'Goldfinger', 'Diamonds Are Forever', and 'Moonraker'.", "Shirley Bassey", ["dame shirley bassey"], "Wikipedia - Bond Themes"),
        ("The Brooklyn-born rapper Christopher Wallace, famously known as Biggie Smalls, who recorded 'Juicy' and 'Ready to Die'.", "The Notorious B.I.G.", ["biggie", "biggie smalls", "notorious big"], "Wikipedia - East Coast Hip Hop"),
        ("The West Coast rapper and poet behind 'Changes', 'Dear Mama', and 'All Eyez on Me', killed in a 1996 drive-by shooting in Las Vegas.", "Tupac Shakur", ["2pac", "tupac", "makaveli"], "Wikipedia - West Coast Hip Hop"),
        ("The Italian opera tenor who formed The Three Tenors with Plácido Domingo and José Carreras, famous for 'Nessun dorma'.", "Luciano Pavarotti", ["pavarotti"], "Wikipedia - Opera Tenors"),
        ("The iconic 1969 Abbey Road album cover by The Beatles features the four band members walking across this.", "A Zebra Crossing", ["crosswalk", "pedestrian crossing", "abbey road crosswalk"], "Wikipedia - The Beatles"),
        ("The legendary singer known as the 'Queen of Soul' who demanded 'R-E-S-P-E-C-T' in her 1967 feminist soul anthem.", "Aretha Franklin", ["franklin"], "Wikipedia - Soul Music"),
        ("The Canadian singer-songwriter who composed the poetic, spiritual ballad 'Hallelujah' in 1984.", "Leonard Cohen", ["cohen"], "Wikipedia - Folk Rock"),
        ("The pioneering German electronic band formed in Düsseldorf in 1970 that used vocoders and synthesizers on 'Autobahn' and 'Computer World'.", "Kraftwerk", ["kraftwerk band"], "Wikipedia - Electronic Music Pioneers"),
        ("The 1985 charity single written by Michael Jackson and Lionel Richie that raised tens of millions for African famine relief.", "We Are the World", ["usa for africa"], "Wikipedia - Charity Singles"),
        ("The Irish rock band fronted by Bono and guitarist The Edge that recorded 'The Joshua Tree' and 'Sunday Bloody Sunday'.", "U2", ["u2 band"], "Wikipedia - Rock Bands"),
        ("The legendary blind singer-songwriter and multi-instrumentalist who recorded 'Superstition', 'Sir Duke', and 'Songs in the Key of Life'.", "Stevie Wonder", ["wonder", "stevland morris"], "Wikipedia - Soul & Funk"),
        ("The iconic Memphis recording studio founded by Sam Phillips where Elvis Presley, Johnny Cash, and Jerry Lee Lewis recorded.", "Sun Studio", ["sun records"], "Wikipedia - Rockabilly"),
        ("The composer and keyboardist who formed the progressive rock band Yes and composed 'Six Wives of Henry VIII'.", "Rick Wakeman", ["wakeman"], "Wikipedia - Progressive Rock"),
        ("The British singer-songwriter whose 1971 album 'Tapestry' became one of the best-selling pop albums of all time.", "Carole King", ["king"], "Wikipedia - Singer-Songwriters"),
        ("The French electronic music duo consisting of Guy-Manuel de Homem-Christo and Thomas Bangalter who wore robot helmets.", "Daft Punk", ["daft punk duo"], "Wikipedia - French House"),
        ("The English gothic rock band fronted by Robert Smith that recorded melancholy hits like 'Boys Don't Cry' and 'Friday I'm in Love'.", "The Cure", ["the cure band"], "Wikipedia - Post-Punk"),
        ("The American singer-songwriter behind 'Piano Man', 'Uptown Girl', and a record-breaking residency at Madison Square Garden.", "Billy Joel", ["joel"], "Wikipedia - Pop Rock"),
        ("The pioneering female rock musician and poet known as the 'Godmother of Punk' whose 1975 debut album was 'Horses'.", "Patti Smith", ["smith"], "Wikipedia - Punk Rock"),
        ("The musical term indicating that a passage should be played very softly, abbreviated as 'pp'.", "Pianissimo", ["pp"], "Wikipedia - Musical Dynamics"),
        ("The musical term indicating that a passage should be played very loudly, abbreviated as 'ff'.", "Fortissimo", ["ff"], "Wikipedia - Musical Dynamics"),
        ("The iconic New York City punk club in the Bowery that nurtured the Ramones, Blondie, and Talking Heads.", "CBGB", ["cbgb & omfug"], "Wikipedia - Punk Venues"),
        ("The Puerto Rican superstar who became the most streamed artist globally on Spotify three consecutive years with albums like 'Un Verano Sin Ti'.", "Bad Bunny", ["benito antonio martínez ocasio"], "Wikipedia - Reggaeton"),
        ("The American singer-songwriter who recorded 'Born in the U.S.A.' and 'Born to Run', nicknamed 'The Boss'.", "Bruce Springsteen", ["springsteen", "the boss"], "Wikipedia - Heartland Rock"),
        ("The British soul singer whose troubled life and 2006 album 'Back to Black' yielded hits like 'Rehab' before her death at 27.", "Amy Winehouse", ["winehouse"], "Wikipedia - Contemporary Soul"),
        ("The legendary jazz saxophonist who recorded 'Giant Steps' and 'A Love Supreme', pioneering free jazz and modal jazz.", "John Coltrane", ["coltrane", "trane"], "Wikipedia - Jazz Masters"),
        ("The English post-punk band from Manchester fronted by Ian Curtis that evolved into New Order after Curtis's death.", "Joy Division", ["joy division band"], "Wikipedia - Post-Punk"),
        ("The country music icon who wrote both 'Jolene' and 'I Will Always Love You' on the very same day in 1973.", "Dolly Parton", ["parton"], "Wikipedia - Country Legends"),
        ("The musical term for gradually speeding up the tempo of a piece of music.", "Accelerando", ["accel."], "Wikipedia - Musical Tempo"),
        ("The musical term for gradually slowing down the tempo of a piece of music.", "Ritardando", ["rallentando", "rit."], "Wikipedia - Musical Tempo"),
        ("The British glam rock artist who created the flamboyant, extraterrestrial rock star alter-ego Ziggy Stardust in 1972.", "David Bowie", ["bowie", "david robert jones"], "Wikipedia - Glam Rock"),
        ("The landmark 1991 album by Metallica featuring a plain black cover with a coiled snake that yielded 'Enter Sandman'.", "The Black Album", ["metallica self-titled", "metallica black album"], "Wikipedia - Heavy Metal"),
        ("The innovative American record producer behind Michael Jackson's Off the Wall, Thriller, and Bad.", "Quincy Jones", ["q", "quincy jones jr"], "Wikipedia - Record Producers"),
        ("The 1980s English synth-pop duo composed of Neil Tennant and Chris Lowe that recorded 'West End Girls'.", "Pet Shop Boys", ["psb"], "Wikipedia - Synth-Pop"),
    ]
    for clue, ans, acc, src in items_200:
        q.append({"value": 200, "clue": clue, "answer": ans, "accepted": acc, "source": src})

    # $300 tier (40 items)
    items_300 = [
        ("The 1913 Paris premiere of this Igor Stravinsky ballet caused a legendary riot due to its avant-garde rhythms and dissonances.", "The Rite of Spring", ["le sacre du printemps"], "Wikipedia - Classical Ballets"),
        ("The German composer of the Baroque era who composed the Brandenburg Concertos and The Well-Tempered Clavier.", "Johann Sebastian Bach", ["bach", "j.s. bach"], "Wikipedia - Baroque Music"),
        ("The 1959 Miles Davis masterpiece album that features John Coltrane, Bill Evans, and Cannonball Adderley.", "Kind of Blue", ["kind of blue album"], "Wikipedia - Jazz Masterpieces"),
        ("The Polish-French Romantic composer and virtuoso pianist who wrote almost exclusively for solo piano, including nocturnes and polonaises.", "Frederic Chopin", ["chopin", "fryderyk chopin"], "Wikipedia - Romantic Music"),
        ("The Beach Boys' 1966 sonic masterpiece album produced by Brian Wilson featuring 'God Only Knows' and 'Wouldn't It Be Nice'.", "Pet Sounds", ["pet sounds 1966"], "Wikipedia - Pop History"),
        ("The Italian baroque composer and Catholic priest nicknamed 'The Red Priest' who composed 'The Four Seasons' violin concertos.", "Antonio Vivaldi", ["vivaldi"], "Wikipedia - Baroque Composers"),
        ("The pioneering female blues singer crowned the 'Empress of the Blues' who recorded 'Downhearted Blues' in 1923.", "Bessie Smith", ["smith"], "Wikipedia - Classic Blues"),
        ("The German opera composer who conceived the concept of the Gesamtkunstwerk ('total work of art') and wrote the epic 'Ring Cycle'.", "Richard Wagner", ["wagner"], "Wikipedia - German Opera"),
        ("The 1977 punk rock single by the Sex Pistols that reached #2 in the UK despite being banned by the BBC during Queen Elizabeth II's Jubilee.", "God Save the Queen", ["no future"], "Wikipedia - Punk Rock"),
        ("The British rock band whose 1979 double album 'The Wall' chronicled rock star Pink's psychological isolation from society.", "Pink Floyd", ["floyd"], "Wikipedia - Progressive Rock"),
        ("The French impressionist composer who wrote 'Clair de Lune' and the orchestral prelude 'Prélude à l'après-midi d'un faune'.", "Claude Debussy", ["debussy"], "Wikipedia - Impressionism in Music"),
        ("The 1971 Marvin Gaye socially conscious concept album addressing the Vietnam War, poverty, and environmental decay.", "What's Going On", ["whats going on"], "Wikipedia - Soul Albums"),
        ("The English singer-songwriter behind 'Wuthering Heights' and the landmark 1985 art-pop album 'Hounds of Love'.", "Kate Bush", ["bush"], "Wikipedia - Art Pop"),
        ("The jazz piano icon and composer who led his orchestra for over 50 years and wrote classics like 'Take the A Train' and 'Mood Indigo'.", "Duke Ellington", ["ellington", "edward kennedy ellington"], "Wikipedia - Big Band Jazz"),
        ("The Russian composer who wrote the ballets Swan Lake, The Sleeping Beauty, and The Nutcracker.", "Pyotr Ilyich Tchaikovsky", ["tchaikovsky"], "Wikipedia - Russian Classical"),
        ("The 1967 Beatles album that is widely regarded as one of the earliest and most influential concept albums in rock history.", "Sgt. Pepper's Lonely Hearts Club Band", ["sgt pepper", "sgt. peppers"], "Wikipedia - The Beatles"),
        ("The legendary blind rhythm and blues pioneer who combined gospel, blues, and jazz in 1950s hits like 'I Got a Woman' and 'What'd I Say'.", "Ray Charles", ["charles", "brother ray"], "Wikipedia - Soul Pioneers"),
        ("The Austrian composer who wrote nine symphonies including the 'Resurrection' Symphony and bridged late Romanticism with early modernism.", "Gustav Mahler", ["mahler"], "Wikipedia - Symphonic Music"),
        ("The New York hip-hop group composed of RZA, GZA, Method Man, Raekwon, and Ol' Dirty Bastard who released 'Enter the Wu-Tang (36 Chambers)'.", "Wu-Tang Clan", ["wu tang", "wutang"], "Wikipedia - Hip Hop"),
        ("The Italian opera composer of the Romantic era who wrote La Traviata, Rigoletto, Aida, and Nabucco.", "Giuseppe Verdi", ["verdi"], "Wikipedia - Italian Opera"),
        ("The pioneering delta blues guitarist who according to legend sold his soul to the Devil at a Mississippi crossroads for guitar virtuosity.", "Robert Johnson", ["johnson"], "Wikipedia - Delta Blues"),
        ("The 1975 epic six-minute rock opera suite by Queen from the album 'A Night at the Opera' that incorporates opera parodies.", "Bohemian Rhapsody", ["bohemian rhapsody song"], "Wikipedia - Queen"),
        ("The American minimalist composer who wrote the opera 'Einstein on the Beach' and music utilizing repetitive structures with subtle variations.", "Philip Glass", ["glass"], "Wikipedia - Minimalist Music"),
        ("The legendary jazz singer nicknamed 'Lady Day' who gave a haunting recording of the anti-lynching poem 'Strange Fruit' in 1939.", "Billie Holiday", ["holiday", "eleanora fagan"], "Wikipedia - Jazz Vocalists"),
        ("The Finnish national Romantic composer who composed the patriotic symphonic poem 'Finlandia' and seven symphonies.", "Jean Sibelius", ["sibelius"], "Wikipedia - Classical Composers"),
        ("The 1965 Bob Dylan folk-rock single featuring an explosive snare crack that changed pop music radio by clocking in at over six minutes.", "Like a Rolling Stone", ["like a rolling stone 1965"], "Wikipedia - Folk Rock"),
        ("The classical musical form consisting of three main sections: exposition, development, and recapitulation.", "Sonata Form", ["sonata-allegro form"], "Wikipedia - Musical Forms"),
        ("The groundbreaking 1988 rap album by N.W.A. from Compton, California that launched the commercial gangsta rap genre.", "Straight Outta Compton", ["straight outta compton album"], "Wikipedia - West Coast Hip Hop"),
        ("The American composer who merged classical symphonic music with American jazz idioms in 'Rhapsody in Blue' (1924).", "George Gershwin", ["gershwin"], "Wikipedia - American Music"),
        ("The legendary Canadian singer-songwriter behind the poignant 1971 confessional folk masterpiece album 'Blue'.", "Joni Mitchell", ["mitchell"], "Wikipedia - Folk Music"),
        ("The Norwegian Romantic composer who incorporated folk melodies into music for Henrik Ibsen's play 'Peer Gynt' (In the Hall of the Mountain King).", "Edvard Grieg", ["grieg"], "Wikipedia - Romantic Era"),
        ("The 1997 Radiohead album featuring dystopian themes of consumerism and technological alienation, often cited as one of the 1990s' best albums.", "OK Computer", ["ok computer radiohead"], "Wikipedia - Alternative Rock"),
        ("The jazz bebop saxophonist nicknamed 'Bird' who revolutionized modern jazz improvisation alongside Dizzy Gillespie in the 1940s.", "Charlie Parker", ["parker", "bird"], "Wikipedia - Bebop"),
        ("The 1976 multi-platinum album by the Eagles that features the eerie, metaphorical title track about a luxury hotel you can never leave.", "Hotel California", ["hotel california album"], "Wikipedia - Classic Rock"),
        ("The French composer who wrote the orchestral masterpiece 'Boléro', characterized by a single relentless crescendo over an ostinato rhythm.", "Maurice Ravel", ["ravel"], "Wikipedia - French Classical"),
        ("The post-punk British band fronted by Mark Hollis that pioneered post-rock with their 1988 and 1991 albums 'Spirit of Eden' and 'Laughing Stock'.", "Talk Talk", ["talk talk band"], "Wikipedia - Post-Rock"),
        ("The musical interval composed of three whole tones, historically dubbed 'the Devil in music' (Diabolus in musica) due to its dissonance.", "Tritone", ["augmented fourth", "diminished fifth"], "Wikipedia - Music Theory"),
        ("The 1982 album by The Clash that yielded 'Rock the Casbah' and 'Should I Stay or Should I Go', their most commercially successful record.", "Combat Rock", ["combat rock the clash"], "Wikipedia - Punk Rock"),
        ("The American jazz bassist and composer who recorded the 1959 hard-bop and post-bop masterpiece 'Mingus Ah Um'.", "Charles Mingus", ["mingus"], "Wikipedia - Jazz Masters"),
        ("The legendary 1971 album by The Who featuring synth loops on 'Baba O'Riley' and the screaming climax of 'Won't Get Fooled Again'.", "Who's Next", ["whos next"], "Wikipedia - Hard Rock"),
    ]
    for clue, ans, acc, src in items_300:
        q.append({"value": 300, "clue": clue, "answer": ans, "accepted": acc, "source": src})

    # $400 tier (40 items)
    items_400 = [
        ("The 1952 musical composition by American avant-garde composer John Cage consisting of four minutes and thirty-three seconds of silence.", "4'33\"", ["4 minutes 33 seconds", "four thirty-three", "four minutes and thirty-three seconds"], "Wikipedia - Avant-Garde Music"),
        ("The German Baroque composer who wrote the oratorio 'Messiah' in 1741, featuring the famous 'Hallelujah' chorus.", "George Frideric Handel", ["handel", "händel"], "Wikipedia - Baroque Oratorio"),
        ("The pioneering Jamaican sound engineer and producer who invented dub music by stripping vocals and manipulating echoes and reverb.", "King Tubby", ["osbourne ruddock"], "Wikipedia - Dub Music"),
        ("The Russian composer whose 1936 opera 'Lady Macbeth of Mtsensk' was denounced by Pravda under Stalin as 'Muddle Instead of Music'.", "Dmitri Shostakovich", ["shostakovich"], "Wikipedia - Soviet Music"),
        ("The 1998 French house track by Stardust (featuring Thomas Bangalter) built around a sample of Chaka Khan's 'Fate'.", "Music Sounds Better with You", ["music sounds better with you 1998"], "Wikipedia - French Touch"),
        ("The 18th-century Austrian composer known as the 'Father of the Symphony' and 'Father of the String Quartet' who mentored Mozart and Beethoven.", "Joseph Haydn", ["haydn", "franz joseph haydn"], "Wikipedia - Classical Era"),
        ("The legendary 1960 free jazz album by Ornette Coleman featuring a double quartet that gave the entire movement its name.", "Free Jazz: A Collective Improvisation", ["free jazz"], "Wikipedia - Free Jazz"),
        ("The 1970 Miles Davis double album that pioneered jazz fusion by incorporating electric guitars, funk rhythms, and rock improvisation.", "Bitches Brew", ["bitches brew album"], "Wikipedia - Jazz Fusion"),
        ("The Italian opera composer of 'La Bohème', 'Tosca', and 'Madama Butterfly', a leading figure of the verismo movement.", "Giacomo Puccini", ["puccini"], "Wikipedia - Verismo Opera"),
        ("The influential 1980 alternative rock band from Athens, Georgia fronted by Michael Stipe that released 'Murmur' in 1983.", "R.E.M.", ["rem", "r.e.m. band"], "Wikipedia - College Rock"),
        ("The Czech Romantic composer who spent three years in the United States, composing his Symphony No. 9 'From the New World' in 1893.", "Antonin Dvorak", ["dvořák", "antonín dvořák"], "Wikipedia - Classical Music"),
        ("The 1977 Brian Eno ambient music album with green airport maps that established the term 'ambient music'.", "Ambient 1: Music for Airports", ["music for airports"], "Wikipedia - Ambient Music"),
        ("The French multi-instrumentalist who recorded the pioneering 1976 electronic ambient music album 'Oxygène' on synthesizers in his kitchen.", "Jean-Michel Jarre", ["jarre"], "Wikipedia - Electronic Music"),
        ("The 1977 David Bowie Berlin Trilogy album produced with Brian Eno that featured the anthemic title track recorded in Hansa Studios near the Wall.", "Heroes", ["heroes album"], "Wikipedia - David Bowie"),
        ("The pioneering British electronic duo composed of brothers Paul and Phil Hartnoll that recorded 'Chime' and 'Halcyon on and on'.", "Orbital", ["orbital duo"], "Wikipedia - Electronic Dance Music"),
        ("The Hungarian composer and ethnomusicologist who traveled through Eastern Europe with a phonograph recording authentic folk songs.", "Bela Bartok", ["bartók", "béla bartók"], "Wikipedia - Ethnomusicology"),
        ("The English rock band led by Mark E. Smith that released over 30 studio albums of abrasive, literate post-punk between 1979 and 2017.", "The Fall", ["the fall band"], "Wikipedia - Post-Punk"),
        ("The 1973 Miles Davis concert recording recorded in Osaka, Japan alongside 'Agharta' that showcased extreme electric funk-rock jazz.", "Pangaea", ["agharta and pangaea"], "Wikipedia - Electric Miles"),
        ("The Soviet composer of Armenian descent who composed the high-energy 'Sabre Dance' as part of his 1942 ballet Gayane.", "Aram Khachaturian", ["khachaturian"], "Wikipedia - Soviet Classical"),
        ("The Scottish dream-pop band formed by Robin Guthrie, Elizabeth Fraser, and Simon Raymonde, pioneers of the ethereal wave sound.", "Cocteau Twins", ["the cocteau twins"], "Wikipedia - Dream Pop"),
        ("The Italian composer who wrote 'The Barber of Seville' and 'William Tell' before retiring from opera composition at age 37.", "Gioachino Rossini", ["rossini"], "Wikipedia - Bel Canto Opera"),
        ("The 1976 punk debut album by the Ramones, recorded in just seven days for $6,400, that opened with 'Blitzkrieg Bop'.", "Ramones", ["ramones debut"], "Wikipedia - American Punk"),
        ("The English Renaissance composer of sacred choral music and consort music who served under four monarchs from Henry VIII to James I.", "William Byrd", ["byrd"], "Wikipedia - Renaissance Polyphony"),
        ("The 1991 shoegaze masterwork album by My Bloody Valentine, famous for Kevin Shields's 'glide guitar' whammy bar technique.", "Loveless", ["loveless album"], "Wikipedia - Shoegaze"),
        ("The German Romantic composer who married pianist Clara Wieck and composed four symphonies and 'Carnaval' before suffering mental collapse.", "Robert Schumann", ["schumann"], "Wikipedia - Romantic Music"),
        ("The French female singer and composer whose iconic 1962 yé-yé ballad 'Tous les garçons et les filles' sold millions across Europe.", "Françoise Hardy", ["hardy"], "Wikipedia - French Pop"),
        ("The American avant-garde composer who developed 'conduction' (conducted improvisation) using a structured lexicon of hand gestures.", "Butch Morris", ["lawrence butch morris"], "Wikipedia - Avant-Garde Jazz"),
        ("The 1994 debut album by Queens rapper Nas, widely regarded as one of the greatest lyrical hip-hop albums of all time.", "Illmatic", ["nas illmatic"], "Wikipedia - East Coast Hip Hop"),
        ("The Russian composer and pianist whose Rach 3 (Piano Concerto No. 3) is notorious as one of the most technically demanding piano concertos ever written.", "Sergei Rachmaninoff", ["rachmaninoff", "rachmaninov"], "Wikipedia - Late Romanticism"),
        ("The multi-instrumentalist producer behind Madvillainy, Donuts, and classic underground hip-hop, known for unquantized MPC drum beats.", "J Dilla", ["dilla", "james yancey", "jay dee"], "Wikipedia - Hip Hop Producers"),
        ("The 18th-century French composer who wrote the influential 1722 'Treatise on Harmony' that established fundamental bass theory.", "Jean-Philippe Rameau", ["rameau"], "Wikipedia - Music Theory"),
        ("The 1989 Pixies album produced by Gil Norton featuring 'Debaser' and 'Monkey Gone to Heaven' that influenced Nirvana.", "Doolittle", ["doolittle pixies"], "Wikipedia - Indie Rock"),
        ("The German modernist composer who pioneered total serialism and electronic music, composing 'Gesang der Jünglinge' and 'Gruppen'.", "Karlheinz Stockhausen", ["stockhausen"], "Wikipedia - Modernist Music"),
        ("The 1998 drum and bass album by Goldie that helped bring the underground jungle sound into mainstream critical acclaim.", "Timeless", ["goldie timeless"], "Wikipedia - Drum and Bass"),
        ("The Spanish Renaissance composer of sacred polyphony who composed the monumental 1605 Requiem (Officium Defunctorum).", "Tomás Luis de Victoria", ["victoria"], "Wikipedia - Renaissance Choral"),
        ("The influential 1991 trip-hop debut album by Bristol collective Massive Attack that featured 'Unfinished Sympathy'.", "Blue Lines", ["blue lines massive attack"], "Wikipedia - Trip-Hop"),
        ("The late-Romantic Austrian composer who wrote the monumental choral work 'Gurre-Lieder' before developing 12-tone technique.", "Arnold Schoenberg", ["schoenberg", "schönberg"], "Wikipedia - Second Viennese School"),
        ("The pioneering American techno trio from Belleville, Michigan (Juan Atkins, Derrick May, and Kevin Saunderson) known as this.", "The Belleville Three", ["belleville three"], "Wikipedia - Detroit Techno"),
        ("The 1974 German progressive krautrock album by Neu! produced by Conny Plank that popularized the steady 4/4 'motorik' beat.", "Neu! 75", ["neu! motorik"], "Wikipedia - Krautrock"),
        ("The 1995 British ambient techno double album by The Future Sound of London featuring organic environmental soundscapes.", "ISDN", ["lifeforms"], "Wikipedia - Ambient Techno"),
    ]
    for clue, ans, acc, src in items_400:
        q.append({"value": 400, "clue": clue, "answer": ans, "accepted": acc, "source": src})

    # $500 tier (40 items)
    items_500 = [
        ("The compositional technique developed by Arnold Schoenberg in the 1920s where all 12 notes of the chromatic scale are treated with equal importance.", "Twelve-Tone Technique", ["dodecaphony", "serialism", "12-tone technique"], "Wikipedia - Serialism"),
        ("The 14th-century French Ars Nova musical and poetic treatise by Philippe de Vitry that gave the entire musical era its name.", "Ars Nova", ["ars nova treatise"], "Wikipedia - Medieval Music"),
        ("The 1976 opera by Philip Glass and Robert Wilson that has no linear plot and lasts approximately five continuous hours without intermission.", "Einstein on the Beach", ["einstein on the beach opera"], "Wikipedia - Minimalist Opera"),
        ("The Polish avant-garde composer whose 1960 orchestral work 'Threnody to the Victims of Hiroshima' utilizes 52 microtonal string instruments.", "Krzysztof Penderecki", ["penderecki"], "Wikipedia - Microtonal Music"),
        ("The 1958 electronic music composition by Edgard Varèse designed to be diffused through 425 loudspeakers inside the Philips Pavilion at the Brussels World's Fair.", "Poème Électronique", ["poeme electronique"], "Wikipedia - Electronic Music"),
        ("The collection of two books of preludes and fugues in all 24 major and minor keys composed by J.S. Bach in 1722 and 1742.", "The Well-Tempered Clavier", ["das wohltemperierte klavier", "wtc"], "Wikipedia - Baroque Keyboard"),
        ("The British avant-garde improvisational group formed in 1965 featuring Cornelius Cardew, Keith Rowe, and Eddie Prévost.", "AMM", ["amm group"], "Wikipedia - Free Improvisation"),
        ("The 1968 electronic and vocal work by Karlheinz Stockhausen based on 24 overtone tunings of a low B-flat, sung by six amplified vocalists.", "Stimmung", ["stockhausen stimmung"], "Wikipedia - Modern Classical"),
        ("The 16th-century Italian Renaissance composer of the Roman School whose 'Missa Papae Marcelli' was credited with saving polyphonic church music.", "Giovanni Pierluigi da Palestrina", ["palestrina"], "Wikipedia - Renaissance Music"),
        ("The Japanese noise music pioneer behind albums like 'Pulse Demon' who has released over 400 recordings under this moniker.", "Merzbow", ["masami akita"], "Wikipedia - Noise Music"),
        ("The French composer who developed the 20th-century concept of 'Musique Concrète' by manipulating recorded tape samples in 1948.", "Pierre Schaeffer", ["schaeffer"], "Wikipedia - Musique Concrète"),
        ("The 1969 Terry Riley minimalist masterpiece composed for an indefinite number of performers playing 53 short musical modules.", "In C", ["terry riley in c"], "Wikipedia - Minimalist Music"),
        ("The Renaissance tuning system where major thirds are tuned purely in a 5:4 frequency ratio, compromising the fifths.", "Quarter-Comma Meantone", ["meantone temperament"], "Wikipedia - Musical Tuning"),
        ("The French-Greek avant-garde composer and architect who applied stochastic mathematical models and game theory to orchestral works like 'Metastaseis'.", "Iannis Xenakis", ["xenakis"], "Wikipedia - Stochastic Music"),
        ("The 1957 electronic piece by Luciano Berio created at the Studio di Fonologia Musicale in Milan using recordings of James Joyce's Ulysses read by Cathy Berberian.", "Thema (Omaggio a Joyce)", ["omaggio a joyce"], "Wikipedia - Electroacoustic Music"),
        ("The 12th-century German Benedictine abbess, mystic, and composer who wrote the morality play 'Ordo Virtutum'.", "Hildegard of Bingen", ["hildegard von bingen", "saint hildegard"], "Wikipedia - Medieval Choral"),
        ("The 1974 ambient drone masterpiece 'The Sinking of the Titanic' was composed by this English experimental composer.", "Gavin Bryars", ["bryars"], "Wikipedia - British Experimental Music"),
        ("The radical Japanese avant-garde art movement of the early 1960s involving Takehisa Kosugi and Yoko Ono that performed 'event scores'.", "Group Ongaku", ["fluxus japan"], "Wikipedia - Experimental Music"),
        ("The monumental 1970 8-hour piano cycle 'The Well-Tuned Piano' tuned in just intonation was composed by this American minimalist.", "La Monte Young", ["young"], "Wikipedia - Minimalist Music"),
        ("The French 14th-century composer and poet who composed the 'Messe de Nostre Dame', the earliest complete polyphonic Mass by a single identified composer.", "Guillaume de Machaut", ["machaut"], "Wikipedia - Medieval Polyphony"),
        ("The 1964 multi-channel electronic tape composition by Pauline Oliveros that introduced the concept of 'Deep Listening'.", "Bye Bye Butterfly", ["deep listening"], "Wikipedia - Experimental Music"),
        ("The Austrian composer who wrote the monumental orchestral song cycle 'Das Lied von der Erde' based on German translations of Tang dynasty poetry.", "Gustav Mahler", ["mahler"], "Wikipedia - Symphonic Song Cycles"),
        ("The pioneering free jazz pianist whose dense, percussive clusters and physical piano attack were documented on the 1973 live solo album 'Silent Tongues'.", "Cecil Taylor", ["taylor"], "Wikipedia - Free Jazz"),
        ("The 1912 expressionist song cycle by Arnold Schoenberg setting 21 poems by Albert Giraud for voice and chamber ensemble using Sprechstimme.", "Pierrot Lunaire", ["pierrot lunaire op. 21"], "Wikipedia - Expressionist Music"),
        ("The 16th-century Italian Prince of Venosa famous for his chromatic Renaissance madrigals who famously murdered his unfaithful wife and her lover in 1590.", "Carlo Gesualdo", ["gesualdo"], "Wikipedia - Renaissance Madrigals"),
        ("The English experimental composer whose 1975 piece 'Jesus' Blood Never Failed Me Yet' loops an unhoused man's singing over orchestral chords.", "Gavin Bryars", ["bryars"], "Wikipedia - Experimental Music"),
        ("The German Baroque collection of 14 canons and 2 ricercars based on a single musical theme given to J.S. Bach by King Frederick the Great.", "The Musical Offering", ["musikalisches opfer", "bwv 1079"], "Wikipedia - J.S. Bach"),
        ("The American composer who created microtonal musical scales dividing the octave into 43 unequal intervals and built his own instruments like the Chromelodeon.", "Harry Partch", ["partch"], "Wikipedia - Microtonal Music"),
        ("The Russian symbolist composer who died in 1915 leaving unfinished 'Mysterium', a synesthetic week-long multimedia ritual to be performed in the Himalayas.", "Alexander Scriabin", ["scriabin"], "Wikipedia - Synesthesia in Art"),
        ("The 1975 German electronic ambient album 'In Den Gärten Pharaos' was recorded by this seminal krautrock and ambient group led by Florian Fricke.", "Popol Vuh", ["popol vuh band"], "Wikipedia - Krautrock"),
        ("The Franco-Flemish Renaissance composer whose 40-voice motet 'Spem in alium' was answered by Thomas Tallis in England.", "Josquin des Prez", ["josquin"], "Wikipedia - Franco-Flemish School"),
        ("The 1971 minimalist tape piece by Steve Reich composed of two speech loops gradually shifting out of phase, titled 'It's Gonna Rain'.", "It's Gonna Rain", ["its gonna rain", "phase shifting"], "Wikipedia - Phase Music"),
        ("The French 20th-century composer who transcribed birdsong from across the world into complex orchestral works like 'Catalogue d'oiseaux'.", "Olivier Messiaen", ["messiaen"], "Wikipedia - French Modernism"),
        ("The 1976 pioneering ambient drone album 'Discreet Music' by Brian Eno was inspired by listening to harp music in a hospital bed with a faulty amplifier.", "Discreet Music", ["discreet music 1975"], "Wikipedia - Ambient Music"),
        ("The English Renaissance choral composer whose monumental 40-part Latin motet 'Spem in alium' is scored for eight distinct five-voice choirs.", "Thomas Tallis", ["tallis"], "Wikipedia - Renaissance Polyphony"),
        ("The American avant-garde jazz saxophonist and composer who founded the M-Base collective and released 'The Tao of Mad Phat' in 1993.", "Steve Coleman", ["coleman"], "Wikipedia - M-Base Jazz"),
        ("The 1958 work for 3 orchestras and percussion 'Gruppen' was composed by this German serialist master.", "Karlheinz Stockhausen", ["stockhausen"], "Wikipedia - Modernist Orchestral"),
        ("The 1979 Japanese ambient electronic landmark album 'Through the Looking Glass' was recorded by this percussionist using marimbas and natural sounds.", "Midori Takada", ["takada"], "Wikipedia - Japanese Ambient"),
        ("The Renaissance compositional practice of inserting chromatic accidentals not written in the musical score during performance.", "Musica Ficta", ["ficta"], "Wikipedia - Early Music Performance"),
        ("The multi-movement organ masterpiece 'Apparition de l'Église éternelle' composed in 1932 was an early breakthrough for this French titan.", "Olivier Messiaen", ["messiaen"], "Wikipedia - Organ Works"),
    ]
    for clue, ans, acc, src in items_500:
        q.append({"value": 500, "clue": clue, "answer": ans, "accepted": acc, "source": src})

    return q

if __name__ == "__main__":
    q = get_questions()
    print("Music questions count:", len(q))
    from collections import Counter
    print("Tier counts:", Counter(x["value"] for x in q))
