"""
Literature & Lore - 200 Curated Trivia Questions
40 items per tier: $100, $200, $300, $400, $500
"""

def get_questions():
    q = []
    # $100 tier (40 items)
    items_100 = [
        ("The Bard of Avon who penned iconic tragedies including Hamlet, Othello, and Romeo and Juliet.", "William Shakespeare", ["shakespeare"], "Wikipedia - English Literature"),
        ("The British author who created the magical world of Harry Potter and Hogwarts.", "J.K. Rowling", ["rowling", "jk rowling", "joanne rowling"], "Wikipedia - Contemporary Literature"),
        ("In Greek mythology, the King of the Olympian gods who wields a mighty thunderbolt.", "Zeus", ["jupiter"], "Wikipedia - Greek Mythology"),
        ("The 1949 dystopian novel by George Orwell introducing 'Big Brother', 'Doublethink', and 'Room 101'.", "1984", ["nineteen eighty-four", "nineteen eighty four"], "Wikipedia - Dystopian Fiction"),
        ("The English author who wrote Pride and Prejudice, Sense and Sensibility, and Emma.", "Jane Austen", ["austen"], "Wikipedia - British Authors"),
        ("In Norse mythology, the mighty war hammer wielded by Thor that can summon lightning.", "Mjolnir", ["mjölnir", "thor's hammer"], "Wikipedia - Norse Mythology"),
        ("The epic 1851 novel by Herman Melville recounting Captain Ahab's obsessive quest for a great white whale.", "Moby-Dick", ["moby dick", "the whale"], "Wikipedia - American Literature"),
        ("The legendary English folk hero and outlaw who stole from the rich to give to the poor in Sherwood Forest.", "Robin Hood", ["robin of loxley"], "Wikipedia - English Folklore"),
        ("The British author who created the eccentric master detective Sherlock Holmes and Dr. John Watson.", "Arthur Conan Doyle", ["conan doyle", "sir arthur conan doyle"], "Wikipedia - Detective Fiction"),
        ("The monster created from reanimated corpse parts by scientist Victor in Mary Shelley's 1818 gothic novel.", "Frankenstein's Monster", ["frankenstein", "the creature", "frankensteins monster"], "Wikipedia - Gothic Fiction"),
        ("The fantasy author who created Middle-earth, authoring The Hobbit and The Lord of the Rings.", "J.R.R. Tolkien", ["tolkien", "john ronald reuel tolkien"], "Wikipedia - High Fantasy"),
        ("In Greek mythology, the hero of the Trojan War who was invincible except for his heel.", "Achilles", ["akhilleus"], "Wikipedia - Greek Mythology"),
        ("The American author who wrote The Adventures of Tom Sawyer and Adventures of Huckleberry Finn.", "Mark Twain", ["twain", "samuel clemens"], "Wikipedia - American Literature"),
        ("The 1847 Victorian novel by Charlotte Brontë featuring the gothic romance between the title governess and Mr. Rochester.", "Jane Eyre", ["jane eyre novel"], "Wikipedia - Victorian Literature"),
        ("In Greek mythology, the winged horse that sprang from the neck of Medusa when she was slain by Perseus.", "Pegasus", ["pegasos"], "Wikipedia - Mythological Creatures"),
        ("The 1925 novel by F. Scott Fitzgerald set in Long Island during the Roaring Twenties depicting millionaire Jay Gatsby.", "The Great Gatsby", ["great gatsby"], "Wikipedia - Modernist Literature"),
        ("The mythical king of Camelot who pulled the sword Excalibur from the stone and led the Knights of the Round Table.", "King Arthur", ["arthur pendragon"], "Wikipedia - Arthurian Legend"),
        ("The Charles Dickens novella where miserly Ebenezer Scrooge is visited by three ghosts on Christmas Eve.", "A Christmas Carol", ["christmas carol"], "Wikipedia - Charles Dickens"),
        ("In Roman mythology, the god of love who carries a bow and golden arrows that cause people to fall deeply in love.", "Cupid", ["amor"], "Wikipedia - Roman Mythology"),
        ("The epic ancient Greek poem attributed to Homer describing the Trojan War and the wrath of Achilles.", "The Iliad", ["iliad"], "Wikipedia - Homeric Epics"),
        ("The companion epic poem to the Iliad detailing the ten-year journey home of Odysseus to Ithaca.", "The Odyssey", ["odyssey"], "Wikipedia - Ancient Epics"),
        ("In Greek mythology, the mortal woman who opened a jar releasing all the evils into the world, leaving only Hope inside.", "Pandora", ["pandoras box"], "Wikipedia - Greek Myth"),
        ("The Irish author who wrote the 1897 gothic horror novel Dracula introducing the Transylvanian vampire Count.", "Bram Stoker", ["stoker"], "Wikipedia - Vampire Literature"),
        ("The French author who wrote The Count of Monte Cristo and The Three Musketeers.", "Alexandre Dumas", ["dumas"], "Wikipedia - French Literature"),
        ("In Norse mythology, the trickster god known for his shape-shifting abilities and parentage of the wolf Fenrir.", "Loki", ["loke"], "Wikipedia - Norse Myth"),
        ("The 1937 fantasy novel by J.R.R. Tolkien following Bilbo Baggins's quest with thirteen dwarves to reclaim the Lonely Mountain.", "The Hobbit", ["the hobbit or there and back again"], "Wikipedia - Children's Fantasy"),
        ("The classic fable author from ancient Greece credited with moral tales like 'The Tortoise and the Hare'.", "Aesop", ["aesop's fables"], "Wikipedia - Ancient Fables"),
        ("In Greek mythology, the beautiful woman whose abduction by Paris of Troy launched a thousand ships.", "Helen of Troy", ["helen"], "Wikipedia - Trojan War"),
        ("The Russian author who wrote the epic panoramic novels War and Peace and Anna Karenina.", "Leo Tolstoy", ["tolstoy"], "Wikipedia - Russian Literature"),
        ("The children's novel by Lewis Carroll where young Alice falls down a rabbit hole into a nonsensical fantasy realm.", "Alice's Adventures in Wonderland", ["alice in wonderland"], "Wikipedia - Nonsense Literature"),
        ("In Arthurian legend, the powerful court wizard and adviser who guided the young King Arthur.", "Merlin", ["myrddin"], "Wikipedia - Arthurian Myth"),
        ("The 1845 narrative poem by Edgar Allan Poe featuring a talking bird that repeatedly croaks 'Nevermore'.", "The Raven", ["edgar allan poe the raven"], "Wikipedia - American Poetry"),
        ("The Greek hero who completed Twelve Labors, including slaying the Nemean Lion and the Hydra.", "Heracles", ["hercules"], "Wikipedia - Greek Mythology"),
        ("The American novelist who wrote The Old Man and the Sea, A Farewell to Arms, and For Whom the Bell Tolls.", "Ernest Hemingway", ["hemingway"], "Wikipedia - Lost Generation"),
        ("In Egyptian mythology, the jackal-headed god associated with mummification and the afterlife.", "Anubis", ["inepu"], "Wikipedia - Egyptian Pantheon"),
        ("The collection of Middle Eastern folk tales told by Scheherazade to King Shahryar over 1,001 nights.", "One Thousand and One Nights", ["arabian nights", "1001 nights"], "Wikipedia - Arabian Folklore"),
        ("The tragic Shakespearean Danish prince who famously ponders 'To be, or not to be: that is the question'.", "Hamlet", ["prince hamlet"], "Wikipedia - Shakespeare Tragedies"),
        ("The American poet who wrote 'The Road Not Taken' and 'Stopping by Woods on a Snowy Evening'.", "Robert Frost", ["frost"], "Wikipedia - American Poetry"),
        ("The Greek goddess of wisdom, warfare, and handicrafts, who sprang fully armed from the head of Zeus.", "Athena", ["athene", "minerva"], "Wikipedia - Olympian Deities"),
        ("The 1960 Pulitzer Prize-winning novel by Harper Lee set in Alabama dealing with racial injustice, featuring lawyer Atticus Finch.", "To Kill a Mockingbird", ["to kill a mockingbird novel"], "Wikipedia - American Classics"),
    ]
    for clue, ans, acc, src in items_100:
        q.append({"value": 100, "clue": clue, "answer": ans, "accepted": acc, "source": src})

    # $200 tier (40 items)
    items_200 = [
        ("The 14th-century Italian epic poem in three parts (Inferno, Purgatorio, Paradiso) written by Dante Alighieri.", "Divine Comedy", ["la divina commedia", "the divine comedy"], "Wikipedia - Medieval Poetry"),
        ("The Russian author of Crime and Punishment, The Idiot, and The Brothers Karamazov.", "Fyodor Dostoevsky", ["dostoevsky", "dostoievsky"], "Wikipedia - Russian Classics"),
        ("In Greek mythology, the Titan who was punished by Zeus to hold up the celestial heavens for all eternity.", "Atlas", ["the titan atlas"], "Wikipedia - Greek Titans"),
        ("The 1850 classic novel by Nathaniel Hawthorne where Hester Prynne is forced to wear a red letter 'A' for adultery.", "The Scarlet Letter", ["scarlet letter"], "Wikipedia - American Romanticism"),
        ("The ancient Mesopotamian epic poem, widely regarded as the earliest surviving great work of world literature.", "Epic of Gilgamesh", ["gilgamesh"], "Wikipedia - Ancient Literature"),
        ("In Norse mythology, the apocalyptic series of events including a great battle leading to the death of major gods.", "Ragnarok", ["ragnarök", "twilight of the gods"], "Wikipedia - Norse Eschatology"),
        ("The English author who wrote the classic gothic romance novel Wuthering Heights under the pen name Ellis Bell.", "Emily Bronte", ["emily brontë", "bronte"], "Wikipedia - English Literature"),
        ("The 1605 Spanish novel by Miguel de Cervantes chronicling the misadventures of a deluded knight and his squire Sancho Panza.", "Don Quixote", ["el ingenioso hidalgo don quijote"], "Wikipedia - Spanish Golden Age"),
        ("In Greek mythology, the musician who descended into the Underworld to rescue his deceased bride Eurydice.", "Orpheus", ["orpheus and eurydice"], "Wikipedia - Greek Myth"),
        ("The 1954 dystopian novel by William Golding about British schoolboys stranded on an uninhabited island who descend into savagery.", "Lord of the Flies", ["the lord of the flies"], "Wikipedia - Allegorical Novels"),
        ("The French philosopher and writer who wrote the satirical novella 'Candide' in 1759 mocking Leibnizian optimism.", "Voltaire", ["francois-marie arouet"], "Wikipedia - Enlightenment Literature"),
        ("In Roman mythology, the twins who founded the city of Rome and were suckled by a she-wolf (Lupa).", "Romulus and Remus", ["remus and romulus"], "Wikipedia - Roman Myth"),
        ("The 1818 English romantic poet who wrote 'Ozymandias' and was the husband of Frankenstein author Mary Shelley.", "Percy Bysshe Shelley", ["shelley", "percy shelley"], "Wikipedia - Romantic Poetry"),
        ("The 1862 French historical epic novel by Victor Hugo following the redeemed ex-convict Jean Valjean.", "Les Miserables", ["les misérables"], "Wikipedia - French Romantics"),
        ("In Greek mythology, the three-headed hound that guards the gates of the Underworld to prevent the dead from leaving.", "Cerberus", ["kerberos"], "Wikipedia - Mythological Beasts"),
        ("The 1953 play by Arthur Miller using the 1692 Salem witch trials as an allegory for McCarthyite anti-communist hysteria.", "The Crucible", ["the crucible play"], "Wikipedia - American Theatre"),
        ("The Irish author who wrote Gulliver's Travels and the satirical essay 'A Modest Proposal'.", "Jonathan Swift", ["swift"], "Wikipedia - Satirical Literature"),
        ("In Greek mythology, the labyrinth on Crete designed by Daedalus housed this monstrous half-man, half-bull creature.", "The Minotaur", ["minotaur", "asterius"], "Wikipedia - Cretan Mythology"),
        ("The 1886 novella by Robert Louis Stevenson exploring the dual nature of man through a mild-mannered doctor and evil alter ego.", "Strange Case of Dr Jekyll and Mr Hyde", ["jekyll and hyde"], "Wikipedia - Victorian Novellas"),
        ("The Roman epic poem written by Virgil telling the legendary story of a Trojan prince who traveled to Italy and became an ancestor of Rome.", "The Aeneid", ["aeneid"], "Wikipedia - Latin Epics"),
        ("In Norse mythology, the great hall located in Asgard where warriors who die heroically in battle are welcomed by Odin.", "Valhalla", ["valholl"], "Wikipedia - Norse Afterlife"),
        ("The 1922 modernist poem by T.S. Eliot that famously begins: 'April is the cruellest month, breeding / Lilacs out of the dead land'.", "The Waste Land", ["waste land"], "Wikipedia - Modernist Poetry"),
        ("The English romantic poet who wrote 'Ode to a Grecian Urn' and 'Ode to a Nightingale' before dying of tuberculosis at 25.", "John Keats", ["keats"], "Wikipedia - Romantic Poets"),
        ("In Egyptian mythology, the falcon-headed god of the sky and kingship whose eye was restored after battle with Set.", "Horus", ["heru"], "Wikipedia - Egyptian Deities"),
        ("The 1932 dystopian novel by Aldous Huxley depicting a technologically advanced World State driven by conditioning and the drug soma.", "Brave New World", ["brave new world novel"], "Wikipedia - Dystopian Classics"),
        ("The 19th-century American poet known as the 'Belle of Amherst' who lived in isolation and wrote nearly 1,800 reclusive poems.", "Emily Dickinson", ["dickinson"], "Wikipedia - American Poets"),
        ("In Greek mythology, the king punished in Tartarus by being forced to roll an immense boulder up a hill, only to watch it roll back down.", "Sisyphus", ["sisyphos"], "Wikipedia - Greek Myth"),
        ("The 1939 John Steinbeck novel following the Joad family as they migrate from the Oklahoma Dust Bowl to California.", "The Grapes of Wrath", ["grapes of wrath"], "Wikipedia - Great Depression Fiction"),
        ("The mythological bird that periodically burns itself on a funeral pyre and rises reborn from its own ashes.", "Phoenix", ["bennu", "firebird"], "Wikipedia - Mythological Birds"),
        ("The Scottish poet celebrated as the national bard of Scotland who wrote 'Auld Lang Syne' and 'To a Mouse'.", "Robert Burns", ["rabbie burns"], "Wikipedia - Scottish Poetry"),
        ("In Norse mythology, the cosmic world tree that connects the nine realms of the Norse mythological universe.", "Yggdrasil", ["yggdrasill", "world tree"], "Wikipedia - Norse Cosmology"),
        ("The 1951 J.D. Salinger novel following the alienated teenager Holden Caulfield over three days in New York City.", "The Catcher in the Rye", ["catcher in the rye"], "Wikipedia - American Fiction"),
        ("The Italian Renaissance author who wrote The Decameron, a collection of 100 tales told by youths sheltering from the Black Death.", "Giovanni Boccaccio", ["boccaccio"], "Wikipedia - Italian Renaissance"),
        ("In Greek mythology, the titan who stole fire from Mount Olympus and gave it to humanity, punished by having an eagle eat his liver daily.", "Prometheus", ["the titan prometheus"], "Wikipedia - Greek Myth"),
        ("The 1928 Virginia Woolf novel featuring an immortal poet who lives for centuries and mysteriously changes sex from man to woman.", "Orlando", ["orlando: a biography"], "Wikipedia - Virginia Woolf"),
        ("The mythological female monsters whose enchanting singing lured passing sailors to shipwreck on rocky coasts.", "Sirens", ["siren"], "Wikipedia - Greek Myth"),
        ("The 19th-century French poet who wrote 'Les Fleurs du mal' (The Flowers of Evil) and pioneered modernist symbolist poetry.", "Charles Baudelaire", ["baudelaire"], "Wikipedia - French Symbolism"),
        ("In Hindu mythology, the blue-skinned eighth avatar of Vishnu who delivers the philosophical sermon of the Bhagavad Gita.", "Krishna", ["lord krishna"], "Wikipedia - Hindu Deities"),
        ("The 1958 debut novel by Nigerian author Chinua Achebe depicting pre-colonial Igbo life and the arrival of European colonizers.", "Things Fall Apart", ["things fall apart novel"], "Wikipedia - African Literature"),
        ("In Greek mythology, the youth who flew too close to the Sun with wings made of feathers and beeswax, falling into the sea.", "Icarus", ["ikaros"], "Wikipedia - Greek Mythology"),
    ]
    for clue, ans, acc, src in items_200:
        q.append({"value": 200, "clue": clue, "answer": ans, "accepted": acc, "source": src})

    # $300 tier (40 items)
    items_300 = [
        ("The 1922 landmark modernist novel by James Joyce chronicling the Dublin encounters of Leopold Bloom on June 16, 1904.", "Ulysses", ["ulysses joyce"], "Wikipedia - Modernist Novels"),
        ("The French philosopher and novelist who wrote The Stranger and The Myth of Sisyphus, pioneering absurdism.", "Albert Camus", ["camus"], "Wikipedia - Absurdism"),
        ("The Old English epic poem surviving in a single manuscript where a Geatish hero slays the monster Grendel.", "Beowulf", ["beowulf epic"], "Wikipedia - Old English Literature"),
        ("The 17th-century English epic poem in blank verse by John Milton recounting the biblical Fall of Man and Lucifer's rebellion.", "Paradise Lost", ["paradise lost milton"], "Wikipedia - Epic Poetry"),
        ("The French modernist author whose monumental seven-volume novel 'In Search of Lost Time' features the famous madeleine memory.", "Marcel Proust", ["proust"], "Wikipedia - French Literature"),
        ("In Norse mythology, the monstrous serpent that encircles the Earth (Midgard) and battles Thor during Ragnarok.", "Jormungandr", ["jörmungandr", "midgard serpent"], "Wikipedia - Norse Mythology"),
        ("The 1927 modernist novel by Virginia Woolf focusing on the Ramsay family and their visits to the Isle of Skye over ten years.", "To the Lighthouse", ["to the lighthouse woolf"], "Wikipedia - Virginia Woolf"),
        ("The Colombian author who won the Nobel Prize and pioneered magical realism in 'One Hundred Years of Solitude'.", "Gabriel Garcia Marquez", ["marquez", "garcía márquez", "gabo"], "Wikipedia - Magical Realism"),
        ("The Czech-born German-language author who wrote The Metamorphosis, depicting Gregor Samsa transforming into an insect.", "Franz Kafka", ["kafka"], "Wikipedia - Modernist Classics"),
        ("In Greek mythology, the subterranean river of hatred across which souls of the dead are ferried into Hades by Charon.", "River Styx", ["styx"], "Wikipedia - Greek Underworld"),
        ("The 14th-century collection of stories in Middle English by Geoffrey Chaucer told by pilgrims traveling to Canterbury Cathedral.", "The Canterbury Tales", ["canterbury tales"], "Wikipedia - Middle English"),
        ("The 1831 gothic novel by Victor Hugo starring the deformed bell-ringer Quasimodo and the Romani dancer Esmeralda.", "The Hunchback of Notre-Dame", ["notre-dame de paris", "hunchback of notre dame"], "Wikipedia - Victor Hugo"),
        ("In Hindu mythology, the ancient Sanskrit epic that contains the Bhagavad Gita, the longest epic poem ever written.", "Mahabharata", ["the mahabharata"], "Wikipedia - Indian Epics"),
        ("The 1929 novel by William Faulkner utilizing stream-of-consciousness narrative through four viewpoints including Benjy Compson.", "The Sound and the Fury", ["sound and the fury"], "Wikipedia - Southern Gothic"),
        ("In Greek mythology, the queen of the underworld and wife of Hades who spends half the year above ground, creating the seasons.", "Persephone", ["proserpina", "kore"], "Wikipedia - Greek Myth"),
        ("The German philosopher and polymath who wrote the tragedy 'Faust', where a scholar makes a pact with Mephistopheles.", "Johann Wolfgang von Goethe", ["goethe"], "Wikipedia - Weimar Classicism"),
        ("The 1952 semi-autobiographical novel by Ralph Ellison exploring the social and intellectual invisibilities of an African American man.", "Invisible Man", ["invisible man ellison"], "Wikipedia - American Literature"),
        ("In Egyptian mythology, the god of the afterlife and resurrection who was murdered and dismembered by his brother Set.", "Osiris", ["wsr"], "Wikipedia - Egyptian Pantheon"),
        ("The 1981 Salman Rushdie novel about children born at the exact moment of India's independence, winning the Booker of Bookers.", "Midnight's Children", ["midnights children"], "Wikipedia - Postcolonial Literature"),
        ("The Roman poet who wrote Metamorphoses, an epic mythological chronicle containing over 250 myths.", "Ovid", ["publius ovidius naso"], "Wikipedia - Roman Poetry"),
        ("The Japanese author whose 11th-century work 'The Tale of Genji' is widely celebrated as the world's first novel.", "Murasaki Shikibu", ["lady murasaki"], "Wikipedia - Heian Literature"),
        ("In Norse mythology, the female figures who choose who lives and dies in battle and escort slain heroes to Valhalla.", "Valkyries", ["valkyrie", "valkyrja"], "Wikipedia - Norse Myth"),
        ("The 1969 novel by Kurt Vonnegut following Billy Pilgrim, an American soldier who becomes 'unstuck in time' during the Dresden bombing.", "Slaughterhouse-Five", ["slaughterhouse five"], "Wikipedia - Satirical Novels"),
        ("In Greek mythology, the winged monster with the body of a lion and the face of a human who strangled those who could not answer her riddle.", "The Sphinx", ["sphinx"], "Wikipedia - Theban Myth"),
        ("The 19th-century Russian playwright who wrote The Cherry Orchard, Uncle Vanya, The Seagull, and Three Sisters.", "Anton Chekhov", ["chekhov"], "Wikipedia - Russian Drama"),
        ("The 1955 novel by Vladimir Nabokov following middle-aged literature professor Humbert Humbert's obsession with young Dolores Haze.", "Lolita", ["lolita nabokov"], "Wikipedia - Nabokov"),
        ("In Celtic mythology, the mystical otherworldly island where King Arthur's sword Excalibur was forged and where he was taken to heal.", "Avalon", ["isle of avalon", "ynys afallon"], "Wikipedia - Arthurian Legend"),
        ("The 1987 Pulitzer Prize-winning novel by Toni Morrison inspired by enslaved African-American woman Margaret Garner.", "Beloved", ["beloved novel"], "Wikipedia - Toni Morrison"),
        ("In Greek mythology, the river of forgetfulness in the Underworld from which dead souls drank to forget their earthly lives.", "Lethe", ["river lethe"], "Wikipedia - Greek Myth"),
        ("The 19th-century French author of Madame Bovary whose clinical, realistic depiction of provincial adultery led to obscenity charges in 1857.", "Gustave Flaubert", ["flaubert"], "Wikipedia - French Realism"),
        ("The 1947 existentialist philosophical novel by Albert Camus about a plague outbreak in the French Algerian city of Oran.", "The Plague", ["la peste"], "Wikipedia - Albert Camus"),
        ("In Aztec mythology, the feathered-serpent deity associated with wind, Venus, the dawn, and wisdom.", "Quetzalcoatl", ["quetzalcoātl"], "Wikipedia - Mesoamerican Myth"),
        ("The 1890 philosophical novel by Oscar Wilde where a decadent young aristocrat remains youthful while his portrait ages hideously.", "The Picture of Dorian Gray", ["dorian gray"], "Wikipedia - Oscar Wilde"),
        ("The foundational text of Taoism traditionally attributed to the ancient philosopher Laozi.", "Tao Te Ching", ["daodejing", "lao tzu"], "Wikipedia - Taoism"),
        ("The 1938 gothic novel by Daphne du Maurier opening with the famous line: 'Last night I dreamt I went to Manderley again.'", "Rebecca", ["rebecca du maurier"], "Wikipedia - Gothic Mystery"),
        ("In Greek mythology, the daughter of King Minos who gave Theseus a ball of thread to escape the Cretan Labyrinth.", "Ariadne", ["ariadne's thread"], "Wikipedia - Greek Legends"),
        ("The 1930 poem by Hart Crane structured as an epic modernist hymn to Brooklyn Bridge and the American landscape.", "The Bridge", ["the bridge hart crane"], "Wikipedia - Modernist Poetry"),
        ("The Swedish author of Pippi Longstocking who championed children's rights and became a global literary treasure.", "Astrid Lindgren", ["lindgren"], "Wikipedia - Children's Literature"),
        ("In Norse mythology, the bridge made of a burning rainbow that connects the mortal realm Midgard with the divine realm Asgard.", "Bifrost", ["bifröst", "rainbow bridge"], "Wikipedia - Norse Cosmology"),
        ("The 1962 meta-fictional novel by Vladimir Nabokov consisting of a 999-line poem by John Shade with obsessive commentary by Charles Kinbote.", "Pale Fire", ["pale fire nabokov"], "Wikipedia - Metafiction"),
    ]
    for clue, ans, acc, src in items_300:
        q.append({"value": 300, "clue": clue, "answer": ans, "accepted": acc, "source": src})

    # $400 tier (40 items)
    items_400 = [
        ("The 1939 experimental comic novel by James Joyce written in an idiosyncratic dream language blending over forty languages.", "Finnegans Wake", ["finnegans wake joyce"], "Wikipedia - Modernist Literature"),
        ("The German-language Austrian author of 'The Man Without Qualities', an unfinished satirical modernist epic set in pre-WWI Vienna.", "Robert Musil", ["musil"], "Wikipedia - Austrian Literature"),
        ("In Greek mythology, the wife of King Agamemnon who conspired with her lover Aegisthus to murder her husband upon his return from Troy.", "Clytemnestra", ["klytaimnestra"], "Wikipedia - Greek Tragedy"),
        ("The 1924 novel by Thomas Mann set in a sanatorium in Davos, Switzerland dealing with European intellectual decay before WWI.", "The Magic Mountain", ["der zauberberg"], "Wikipedia - German Literature"),
        ("The 13th-century Icelandic chieftain and scholar who preserved Norse mythology in the Prose Edda.", "Snorri Sturluson", ["snorri", "sturluson"], "Wikipedia - Norse Sagas"),
        ("The 1973 postmodern masterwork novel by Thomas Pynchon following Tyrone Slothrop across post-WWII Europe hunting V-2 rockets.", "Gravity's Rainbow", ["gravitys rainbow"], "Wikipedia - Postmodern Fiction"),
        ("The Portuguese national epic poem published in 1572 by Luís de Camões celebrating Vasco da Gama's voyage to India.", "The Lusiads", ["os lusíadas"], "Wikipedia - Portuguese Literature"),
        ("The 1927 novel by Hermann Hesse tracing the spiritual crisis of Harry Haller, caught between human rationality and wolfish instinct.", "Steppenwolf", ["steppenwolf hesse"], "Wikipedia - German Classics"),
        ("In Sumerian mythology, the terrifying bull of heaven sent by goddess Inanna to punish Gilgamesh and Enkidu.", "Gugalanna", ["bull of heaven"], "Wikipedia - Epic of Gilgamesh"),
        ("The 1963 Argentine counter-novel by Julio Cortázar that can be read either sequentially or following an alternative 'hopscotch' chapter order.", "Hopscotch", ["rayuela"], "Wikipedia - Latin American Boom"),
        ("The ancient Sanskrit drama by Kalidasa about a king who marries a hermit maiden, loses her through a curse, and later reclaims her with a signet ring.", "The Recognition of Shakuntala", ["shakuntala", "abhijnanasakuntalam"], "Wikipedia - Sanskrit Drama"),
        ("The 19th-century French symbolist poet who wrote 'A Season in Hell' and 'Illuminations' before abruptly giving up poetry at age 20 to become a gunrunner.", "Arthur Rimbaud", ["rimbaud"], "Wikipedia - French Poetry"),
        ("The 1953 tragic novel by James Baldwin about a fourteen-year-old boy in 1930s Harlem grappling with his Pentecostal church and stepfather.", "Go Tell It on the Mountain", ["go tell it on the mountain novel"], "Wikipedia - African American Literature"),
        ("In Norse mythology, the magical ship built by dwarves that always has a favorable wind and can be folded up into a small pocket pouch.", "Skidbladnir", ["skíðblaðnir"], "Wikipedia - Norse Myth"),
        ("The 1985 dark epic Western novel by Cormac McCarthy tracing the violent scalp-hunting Glanton gang along the Texas-Mexico border, led by Judge Holden.", "Blood Meridian", ["blood meridian mccarthy"], "Wikipedia - American Masterpieces"),
        ("The Italian author who wrote 'Invisible Cities' and 'If on a winter's night a traveler', master of postmodern fabulism.", "Italo Calvino", ["calvino"], "Wikipedia - Postmodernism"),
        ("In Greek mythology, the three sisters who spin, measure, and cut the thread of human life (Clotho, Lachesis, and Atropos).", "The Fates", ["moirai", "the moirai"], "Wikipedia - Greek Myth"),
        ("The 1930 southern gothic novel by William Faulkner narrated by 15 different characters on a wagon journey to bury Addie Bundren.", "As I Lay Dying", ["as i lay dying faulkner"], "Wikipedia - Southern Gothic"),
        ("The ancient Finnish epic poem compiled from oral folklore and mythology in the 19th century by Elias Lönnrot.", "The Kalevala", ["kalevala"], "Wikipedia - National Epics"),
        ("The 19th-century Russian author of 'Dead Souls' and the short story 'The Overcoat', a pioneer of Russian surrealism and satire.", "Nikolai Gogol", ["gogol"], "Wikipedia - Russian Classics"),
        ("In Egyptian mythology, the goddess of truth, balance, cosmic order, and justice, symbolized by an ostrich feather on the Scales of Judgment.", "Ma'at", ["maat"], "Wikipedia - Egyptian Religion"),
        ("The 1974 sci-fi novel by Ursula K. Le Guin depicting the contrasting anarcho-syndicalist world of Anarres and capitalist Urras.", "The Dispossessed", ["the dispossessed le guin"], "Wikipedia - Science Fiction"),
        ("The Polish-British author who explored colonial exploitation and moral isolation in 'Heart of Darkness', 'Lord Jim', and 'Nostromo'.", "Joseph Conrad", ["conrad", "teodor jozef konrad korzeniowski"], "Wikipedia - English Modernism"),
        ("In Greek mythology, the ancient prophet of Thebes who was transformed into a woman for seven years and blinded by Hera, appearing in Oedipus Rex.", "Tiresias", ["teiresias"], "Wikipedia - Greek Legends"),
        ("The 1979 feminist sci-fi novel by Octavia Butler where modern African-American writer Dana is repeatedly pulled back in time to an antebellum Maryland plantation.", "Kindred", ["kindred octavia butler"], "Wikipedia - Afro-Futurism"),
        ("The 17th-century Japanese poet who elevated haiku poetry and penned the travel diary 'The Narrow Road to the Deep North'.", "Matsuo Basho", ["basho", "matsuo bashō"], "Wikipedia - Japanese Poetry"),
        ("The 1948 collection of stories by Jorge Luis Borges containing 'The Aleph', 'The Immortal', and labyrinths of infinity.", "The Aleph", ["el aleph"], "Wikipedia - Argentine Literature"),
        ("In Persian mythology, the supernatural benevolent gigantic mythical bird that raised the albino hero Zāl in the Shahnameh.", "Simurgh", ["simorgh"], "Wikipedia - Persian Folklore"),
        ("The 1968 postmodern historical novel by John Fowles featuring two alternate endings set in Victorian Lyme Regis.", "The French Lieutenant's Woman", ["french lieutenants woman"], "Wikipedia - Metafiction"),
        ("The Roman satirical work written during the reign of Nero by Petronius, famous for the extravagant banquet scene 'Trimalchio's Feast'.", "Satyricon", ["the satyricon"], "Wikipedia - Roman Literature"),
        ("In Norse mythology, the giant wolf fathered by Loki who bites off the right hand of god Tyr before being bound until Ragnarok.", "Fenrir", ["fenrisulfr", "fenris wolf"], "Wikipedia - Norse Monsters"),
        ("The 1946 epic psychological novel by Robert Penn Warren tracing the rise and political corruption of Louisiana governor Willie Stark.", "All the King's Men", ["all the kings men"], "Wikipedia - Political Novels"),
        ("The Irish playwright who wrote Waiting for Godot and Endgame, pioneering the Theatre of the Absurd and winning the 1969 Nobel Prize.", "Samuel Beckett", ["beckett"], "Wikipedia - Theatre of the Absurd"),
        ("In Greek mythology, the Queen of Thebes whose pride in her fourteen children angered Leto, leading Artemis and Apollo to slaughter all her children.", "Niobe", ["the weeping stone"], "Wikipedia - Greek Myth"),
        ("The 1978 post-colonial historical novel by Edward Said that critically examined Western scholarly constructions of the Arab-Islamic world.", "Orientalism", ["orientalism book"], "Wikipedia - Critical Theory"),
        ("The 19th-century French author of the monumental 90-novel sequence 'La Comédie Humaine' depicting post-Napoleonic French society.", "Honore de Balzac", ["balzac", "honoré de balzac"], "Wikipedia - French Realism"),
        ("In Welsh mythology, the foundational collection of eleven medieval prose stories preserved in the Red Book of Hergest and White Book of Rhydderch.", "The Mabinogion", ["mabinogion"], "Wikipedia - Welsh Mythology"),
        ("The 1966 post-modern mystery novella by Thomas Pynchon centered on Oedipa Maas investigating an underground postal conspiracy called Tristero.", "The Crying of Lot 49", ["crying of lot 49"], "Wikipedia - Postmodern Literature"),
        ("In Chinese mythology, the monkey king born from a stone who acquires supernatural powers and accompanies monk Tang Sanzang in Journey to the West.", "Sun Wukong", ["monkey king"], "Wikipedia - Chinese Folklore"),
        ("The Austrian poet whose 'Duino Elegies' and 'Sonnets to Orpheus' are considered among the pinnacles of 20th-century German lyric poetry.", "Rainer Maria Rilke", ["rilke"], "Wikipedia - Lyric Poetry"),
    ]
    for clue, ans, acc, src in items_400:
        q.append({"value": 400, "clue": clue, "answer": ans, "accepted": acc, "source": src})

    # $500 tier (40 items)
    items_500 = [
        ("The 10th-century Persian national epic poem composed of over 50,000 couplets written by Ferdowsi, chronicling mythical kings and Rustam.", "Shahnameh", ["the book of kings", "shahnama"], "Wikipedia - Persian Literature"),
        ("The ancient Ugaritic Bronze Age mythological cycle describing the weather god Baal's triumph over Yam (Sea) and Mot (Death).", "The Baal Cycle", ["baal cycle"], "Wikipedia - Canaanite Religion"),
        ("The 1933 French surrealist novel sequence by Raymond Roussel composed using complex phonemic wordplay and puns, titled 'Impressions of Africa'.", "Impressions of Africa", ["impressions d'afrique"], "Wikipedia - Surrealist Literature"),
        ("In Norse mythology, the rooster whose crowing awakens the gods and giants to commence the final battle of Ragnarok.", "Gullincombi", ["gullinkambi"], "Wikipedia - Norse Myth"),
        ("The 1931 Austrian modernist novel trilogy 'The Sleepwalkers' (Die Schlafwandler) exploring value disintegration in Europe was written by this philosopher.", "Hermann Broch", ["broch"], "Wikipedia - Modernist Novels"),
        ("The obscure 1869 French prose poem masterpiece 'Les Chants de Maldoror' was written by Isidore Ducasse under this aristocratic pseudonym.", "Comte de Lautreamont", ["lautréamont", "isidore ducasse"], "Wikipedia - Decadent Literature"),
        ("In Greek mythology, the obscure Titaness of memory and mother of the nine Muses by Zeus over nine nights.", "Mnemosyne", ["mnemosyne titaness"], "Wikipedia - Greek Mythology"),
        ("The 1978 monumental novel 'Life: A User's Manual' by French Oulipo member Georges Perec structured around a Paris apartment block via a knight's tour.", "Life: A User's Manual", ["la vie mode d'emploi", "life a users manual"], "Wikipedia - Oulipo"),
        ("The 14th-century Sir Gawain and the Green Knight poet is also universally attributed with authoring this tender Middle English alliterative dream elegy.", "Pearl", ["the pearl poem", "pearl poet"], "Wikipedia - Middle English Alliterative"),
        ("In Mayan mythology, the sacred foundational narrative preserved by K'iche' Maya depicting the heroic adventures of the Hero Twins Hunahpu and Xbalanque.", "Popol Vuh", ["popol wuj"], "Wikipedia - Mesoamerican Mythology"),
        ("The 1928 German novel 'Berlin Alexanderplatz' utilizing cinematic montage and radio collages to chronicle Franz Biberkopf was written by this physician.", "Alfred Doblin", ["döblin"], "Wikipedia - Weimar Republic Literature"),
        ("The 16th-century Italian Renaissance epic poem 'Jerusalem Delivered' (Gerusalemme liberata) depicting the First Crusade was composed by this troubled poet.", "Torquato Tasso", ["tasso"], "Wikipedia - Italian Epic"),
        ("In Egyptian mythology, the primordial primeval ocean and watery abyss from which the creation mound emerged.", "Nun", ["nu", "primordial nun"], "Wikipedia - Egyptian Creation Myths"),
        ("The 1957 7-volume Austrian epic novel 'The Demons' (Die Dämonen) depicting 1920s Vienna class society was written by this novelist.", "Heimito von Doderer", ["doderer"], "Wikipedia - Austrian Literature"),
        ("The 13th-century Icelandic mythological manuscript Codex Regius (Konungsbók) is the primary historical source for this collection of mythological poems.", "Poetic Edda", ["elder edda", "codex regius"], "Wikipedia - Norse Eddas"),
        ("The 1939 Mexican novel 'Under the Volcano' chronicling the final day of alcoholic British consul Geoffrey Firmin on the Day of the Dead was written by him.", "Malcolm Lowry", ["lowry"], "Wikipedia - Modernist Masterpieces"),
        ("In Greek mythology, the winged monster born of Medusa's blood whose son Geryon possessed three heads and was slain by Heracles.", "Chrysaor", ["chrysaor brother of pegasus"], "Wikipedia - Greek Monsters"),
        ("The 1970 French postmodern novel 'The Erasers' and 'Jealousy' by Alain Robbe-Grillet pioneered this radical objective narrative movement.", "Nouveau Roman", ["new novel", "nouveau roman movement"], "Wikipedia - French Avant-Garde"),
        ("The 12th-century French romance author who introduced Lancelot, the Holy Grail, and the Round Table romance into Arthurian literature.", "Chretien de Troyes", ["chrétien de troyes"], "Wikipedia - Arthurian Romance"),
        ("In Norse mythology, the squirrel who scurries up and down Yggdrasil carrying malicious insults between the eagle and dragon Nidhogg.", "Ratatoskr", ["ratatosk"], "Wikipedia - Norse Creatures"),
        ("The massive 1938 British historical novel sequence 'The Story of the Stone' (also known as Dream of the Red Chamber) by Cao Xueqin forms one of these.", "Four Great Classical Novels", ["four great classic novels of china"], "Wikipedia - Chinese Literature"),
        ("The Roman Stoic philosopher and playwright whose violent tragedies Phaedra, Medea, and Thyestes deeply influenced Elizabethan revenge tragedy.", "Seneca the Younger", ["seneca"], "Wikipedia - Roman Tragedy"),
        ("In Mesopotamian mythology, the primeval freshwater abyss associated with Enki, underlying the earth from which springs emerge.", "Abzu", ["apsu"], "Wikipedia - Sumerian Religion"),
        ("The 1929 surrealist French collaborative novel 'L'Immaculée Conception' simulating mental illnesses was co-authored by André Breton and this poet.", "Paul Eluard", ["éluard"], "Wikipedia - Surrealism"),
        ("The 10th-century Byzantine encyclopedia containing 30,000 entries on classical history, literature, and grammar, preserved under this four-letter name.", "Suda", ["the suda lexicon", "suidas"], "Wikipedia - Byzantine Scholarship"),
        ("In Irish mythology, the heroic spear of fiery light wielded by Lugh Lamhfada, one of the Four Treasures of the Tuatha Dé Danann.", "Spear of Lugh", ["sleagh lúin", "gae assail"], "Wikipedia - Celtic Treasures"),
        ("The 1975 Italian historical novel 'The Castle of Crossed Destinies' where travelers struck mute tell their life stories using this device.", "Tarot Cards", ["tarot deck", "tarots"], "Wikipedia - Italo Calvino"),
        ("The ancient Sanskrit verse treatise on performing arts, dramaturgy, dance, and music traditionally attributed to sage Bharata Muni.", "Natya Shastra", ["nāṭya śāstra"], "Wikipedia - Ancient Sanskrit Treatises"),
        ("In Greek mythology, the primordial deity of darkness who was the brother and consort of Nyx (Night), born of Chaos.", "Erebus", ["erebos"], "Wikipedia - Greek Primordials"),
        ("The 1907 Irish play by J.M. Synge whose opening night in Dublin sparked nationalist riots over perceived insults to Irish morality.", "The Playboy of the Western World", ["playboy of the western world"], "Wikipedia - Irish Theatre"),
        ("The 13th-century German Middle High German epic poem recounting the tragic dragon-slaying hero Siegfried and the Burgundian court.", "Nibelungenlied", ["song of the nibelungs"], "Wikipedia - Germanic Epics"),
        ("In Norse mythology, the blind god who was tricked by the malicious Loki into shooting his beloved brother Baldr with a mistletoe dart.", "Hodr", ["höðr", "hod"], "Wikipedia - Norse Deities"),
        ("The 1955 Polish novel 'The Trans-Atlantyk' written in archaic 17th-century Polish baroque prose style by this exiled master.", "Witold Gombrowicz", ["gombrowicz"], "Wikipedia - Polish Avant-Garde"),
        ("The ancient Greek poetess of Lesbos whose surviving fragments of lyric poetry were celebrated by Plato as the 'Tenth Muse'.", "Sappho", ["sappho of lesbos"], "Wikipedia - Ancient Lyric Poetry"),
        ("In Slavic mythology, the witch who lives deep in the forest in a hut standing on dancing chicken legs surrounded by human bones.", "Baba Yaga", ["baba yaga the witch"], "Wikipedia - Slavic Folklore"),
        ("The 1928 French surrealist novel 'Nadja' chronicling the author's real-life obsessive relationship with an eccentric, clairvoyant woman.", "Andre Breton", ["breton"], "Wikipedia - Surrealist Novels"),
        ("In Japanese mythology, the eight-forked gigantic dragon serpent slain by storm god Susanoo, who discovered the sword Kusanagi in its tail.", "Yamata no Orochi", ["orochi"], "Wikipedia - Shinto Mythology"),
        ("The 1910 English novel by E.M. Forster featuring the Schlegel sisters with the famous epigraph: 'Only connect...'", "Howards End", ["howards end novel"], "Wikipedia - E.M. Forster"),
        ("In Norse mythology, the golden boar forged by the dwarf brothers Brokkr and Sindri that could run through air and sea faster than any horse.", "Gullinbursti", ["gullinbursti boar"], "Wikipedia - Norse Treasures"),
        ("The monumental 19th-century compilation of Scottish and English popular ballads in five volumes compiled by Harvard scholar Francis James Child.", "Child Ballads", ["the child ballads"], "Wikipedia - Folk Ballads"),
    ]
    for clue, ans, acc, src in items_500:
        q.append({"value": 500, "clue": clue, "answer": ans, "accepted": acc, "source": src})

    return q

if __name__ == "__main__":
    q = get_questions()
    print("Literature questions count:", len(q))
    from collections import Counter
    print("Tier counts:", Counter(x["value"] for x in q))
