"""
World Geography - 200 Curated Trivia Questions
40 items per tier: $100, $200, $300, $400, $500
"""

def get_questions():
    q = []
    # $100 tier (40 items)
    items_100 = [
        ("The longest river in the world, flowing through northeastern Africa into the Mediterranean Sea.", "Nile River", ["nile", "the nile"], "Wikipedia - Physical Geography"),
        ("The capital city of France, home to the Eiffel Tower and the Louvre Museum.", "Paris", ["city of paris"], "Wikipedia - Capitals of Europe"),
        ("The largest ocean on Earth, covering more than 30% of the planet's surface.", "Pacific Ocean", ["pacific"], "Wikipedia - World Oceans"),
        ("The highest mountain peak above sea level on Earth, located in the Himalayas.", "Mount Everest", ["everest", "mt everest"], "Wikipedia - Mountain Peaks"),
        ("The country with the largest total land area in the world, spanning eleven time zones.", "Russia", ["russian federation"], "Wikipedia - Countries by Area"),
        ("The capital city of the United Kingdom, situated on the River Thames.", "London", ["greater london"], "Wikipedia - World Capitals"),
        ("The continent that is also a single sovereign country.", "Australia", ["commonwealth of australia"], "Wikipedia - Continents"),
        ("The colossal ancient defensive stone wall stretching across thousands of miles in northern China.", "The Great Wall of China", ["great wall", "great wall of china"], "Wikipedia - World Landmarks"),
        ("The South American country famous for the Amazon rainforest and Christ the Redeemer in Rio de Janeiro.", "Brazil", ["brasil"], "Wikipedia - South America"),
        ("The capital city of Japan, the world's most populous metropolitan area.", "Tokyo", ["greater tokyo"], "Wikipedia - Asian Capitals"),
        ("The large island continent that is almost entirely covered by a thick ice sheet at the South Pole.", "Antarctica", ["antarctic continent"], "Wikipedia - Polar Regions"),
        ("The United States state known as the 'Sunshine State', home to the Everglades and Miami.", "Florida", ["fl"], "Wikipedia - US States"),
        ("The deepest lake in the world, located in Siberia, holding 20% of Earth's unfrozen surface freshwater.", "Lake Baikal", ["baikal"], "Wikipedia - World Lakes"),
        ("The capital city of Italy, surrounding the independent sovereign city-state of Vatican City.", "Rome", ["roma"], "Wikipedia - European Capitals"),
        ("The largest hot desert in the world, stretching across North Africa.", "Sahara Desert", ["sahara", "the sahara"], "Wikipedia - Deserts"),
        ("The canal in Central America that connects the Atlantic and Pacific Oceans.", "Panama Canal", ["the panama canal"], "Wikipedia - Waterways"),
        ("The city in the United States famous for the Golden Gate Bridge and Alcatraz Island.", "San Francisco", ["sf"], "Wikipedia - US Cities"),
        ("The famous river that flows through the Grand Canyon in the American Southwest.", "Colorado River", ["colorado"], "Wikipedia - US Geography"),
        ("The North American country located directly north of the continental United States.", "Canada", ["dominion of canada"], "Wikipedia - North America"),
        ("The European country shaped like a boot jutting into the Mediterranean Sea.", "Italy", ["italian republic"], "Wikipedia - Geography of Europe"),
        ("The mountain range that forms the natural border between Europe and Asia in Russia.", "Ural Mountains", ["the urals", "urals"], "Wikipedia - Mountain Ranges"),
        ("The city known as the 'Big Apple', home to Central Park and the Statue of Liberty.", "New York City", ["nyc", "new york"], "Wikipedia - US Cities"),
        ("The largest freshwater lake in the world by surface area, shared by the US and Canada.", "Lake Superior", ["superior"], "Wikipedia - Great Lakes"),
        ("The capital city of Egypt, situated near the ancient Giza pyramid complex.", "Cairo", ["al-qahira"], "Wikipedia - African Capitals"),
        ("The iconic waterfall on the border of New York State and Ontario, Canada.", "Niagara Falls", ["niagara"], "Wikipedia - Waterfalls"),
        ("The world's smallest sovereign nation, entirely enclosed within the city of Rome.", "Vatican City", ["the vatican", "holy see"], "Wikipedia - Microstates"),
        ("The country known for its thousands of fjords and midnight sun along the Scandinavian coast.", "Norway", ["kingdom of norway"], "Wikipedia - Scandinavia"),
        ("The prominent clock tower at the north end of the Houses of Parliament in London.", "Big Ben", ["elizabeth tower"], "Wikipedia - Landmarks"),
        ("The capital city of Spain, home to the Prado Museum and the Royal Palace.", "Madrid", ["city of madrid"], "Wikipedia - European Capitals"),
        ("The famous mountain in Japan, a symmetrical snow-capped volcanic cone near Tokyo.", "Mount Fuji", ["fuji", "fujisan"], "Wikipedia - Japanese Geography"),
        ("The sea that separates Europe from Africa.", "Mediterranean Sea", ["the mediterranean"], "Wikipedia - Seas"),
        ("The tropical rainforest basin that produces roughly 20% of Earth's oxygen.", "Amazon Rainforest", ["the amazon", "amazon basin"], "Wikipedia - Rainforests"),
        ("The body of water into which the Mississippi River empties at New Orleans.", "Gulf of Mexico", ["the gulf of mexico"], "Wikipedia - North America"),
        ("The country with the second-largest population in the world, home to the Taj Mahal.", "India", ["republic of india", "bharat"], "Wikipedia - Asian Geography"),
        ("The capital city of Germany, reunited in 1990 after the fall of the Wall.", "Berlin", ["city of berlin"], "Wikipedia - European Capitals"),
        ("The largest island in the Caribbean Sea, located just 90 miles south of Key West, Florida.", "Cuba", ["republic of cuba"], "Wikipedia - Caribbean"),
        ("The vast frozen ocean surrounding the North Pole.", "Arctic Ocean", ["arctic"], "Wikipedia - Oceans"),
        ("The South American mountain range that is the longest continental mountain chain on Earth.", "The Andes", ["andes", "andes mountains"], "Wikipedia - Mountain Chains"),
        ("The capital city of the United States, located along the Potomac River.", "Washington D.C.", ["washington dc", "dc", "district of columbia"], "Wikipedia - National Capitals"),
        ("The country famous for its windmills, wooden clogs, tulip fields, and Amsterdam canals.", "The Netherlands", ["netherlands", "holland"], "Wikipedia - Western Europe"),
    ]
    for clue, ans, acc, src in items_100:
        q.append({"value": 100, "clue": clue, "answer": ans, "accepted": acc, "source": src})

    # $200 tier (40 items)
    items_200 = [
        ("The capital city of Australia, purpose-built in the ACT between Sydney and Melbourne.", "Canberra", ["city of canberra"], "Wikipedia - World Capitals"),
        ("The South American country that is the only one on the continent whose official language is Portuguese.", "Brazil", ["brasil"], "Wikipedia - Demographics"),
        ("The largest island in the world that is not considered a continent, belonging to Denmark.", "Greenland", ["kalaallit nunaat"], "Wikipedia - Island Geography"),
        ("The strait separating the southern tip of the Iberian Peninsula from Morocco.", "Strait of Gibraltar", ["gibraltar"], "Wikipedia - World Straits"),
        ("The capital city of Canada, located in the province of Ontario on the border with Quebec.", "Ottawa", ["city of ottawa"], "Wikipedia - Canadian Geography"),
        ("The African country completely encircled by South Africa.", "Lesotho", ["kingdom of lesotho"], "Wikipedia - Enclaves"),
        ("The capital city of China, previously romanized in English as Peking.", "Beijing", ["peking"], "Wikipedia - Asian Capitals"),
        ("The European country that has four official languages: German, French, Italian, and Romansh.", "Switzerland", ["swiss confederation"], "Wikipedia - European Nations"),
        ("The river that flows through Baghdad, forming Mesopotamia alongside the Euphrates.", "Tigris River", ["tigris"], "Wikipedia - Middle East"),
        ("The world's highest uninterrupted waterfall, dropping 979 meters in Canaima National Park, Venezuela.", "Angel Falls", ["salto ángel", "kerepakupai meru"], "Wikipedia - Waterfalls"),
        ("The European island nation located on the Mid-Atlantic Ridge, famous for geysers and volcanoes.", "Iceland", ["republic of iceland"], "Wikipedia - Nordic Countries"),
        ("The capital city of Russia, centered on the Red Square and the Kremlin.", "Moscow", ["moskva"], "Wikipedia - World Capitals"),
        ("The narrow sea canal in Egypt connecting the Mediterranean Sea to the Red Sea.", "Suez Canal", ["the suez canal"], "Wikipedia - Maritime Canals"),
        ("The capital city of South Korea, bisected by the Han River.", "Seoul", ["seoul special city"], "Wikipedia - East Asia"),
        ("The largest lake in Africa by surface area, named after a British queen.", "Lake Victoria", ["victoria nyanza"], "Wikipedia - African Great Lakes"),
        ("The island country off the southeastern coast of India, formerly known as Ceylon.", "Sri Lanka", ["ceylon"], "Wikipedia - South Asia"),
        ("The capital city of Argentina, famous for tango in the La Boca neighborhood.", "Buenos Aires", ["ciudad de buenos aires"], "Wikipedia - South American Capitals"),
        ("The mountain range that separates the Indian subcontinent from the Tibetan Plateau.", "The Himalayas", ["himalaya", "himalayas"], "Wikipedia - Mountain Ranges"),
        ("The capital city of Greece, regarded as the cradle of Western civilization and democracy.", "Athens", ["athina"], "Wikipedia - Ancient Cities"),
        ("The US state that is an archipelago of volcanic islands in the central Pacific Ocean.", "Hawaii", ["state of hawaii"], "Wikipedia - US Geography"),
        ("The sea completely bordered by land that is the lowest point of elevation on Earth's dry land surface.", "Dead Sea", ["the dead sea"], "Wikipedia - Salt Lakes"),
        ("The capital city of Mexico, built on the ruins of the Aztec capital Tenochtitlan.", "Mexico City", ["ciudad de méxico", "cdmx"], "Wikipedia - North America"),
        ("The massive coral reef system stretching over 1,400 miles off the coast of Queensland, Australia.", "Great Barrier Reef", ["the great barrier reef"], "Wikipedia - Marine Wonders"),
        ("The capital city of Sweden, built on 14 islands connected by more than 50 bridges.", "Stockholm", ["city of stockholm"], "Wikipedia - Scandinavia"),
        ("The country with the longest coastline in the world, measuring over 243,000 kilometers.", "Canada", ["dominion of canada"], "Wikipedia - Coastlines"),
        ("The river that forms much of the border between the US state of Texas and Mexico.", "Rio Grande", ["río bravo", "rio bravo del norte"], "Wikipedia - Border Rivers"),
        ("The African peak in Tanzania that is the highest free-standing mountain in the world.", "Mount Kilimanjaro", ["kilimanjaro"], "Wikipedia - African Peaks"),
        ("The capital city of Ireland, through which the River Liffey flows.", "Dublin", ["baile átha cliath"], "Wikipedia - European Capitals"),
        ("The long mountain chain in eastern North America running from Georgia to Newfoundland.", "Appalachian Mountains", ["appalachians"], "Wikipedia - US Mountain Ranges"),
        ("The European country that has won more Winter Olympic medals than any other nation.", "Norway", ["kingdom of norway"], "Wikipedia - Winter Sports"),
        ("The capital city of Portugal, situated where the Tagus River empties into the Atlantic Ocean.", "Lisbon", ["lisboa"], "Wikipedia - Iberian Peninsula"),
        ("The desert that covers much of southern Israel.", "Negev Desert", ["the negev", "negev"], "Wikipedia - Middle East"),
        ("The strait separating mainland Australia from the island of Tasmania.", "Bass Strait", ["bass"], "Wikipedia - Australian Geography"),
        ("The capital city of Turkey, located in central Anatolia.", "Ankara", ["angora"], "Wikipedia - Middle East Capitals"),
        ("The largest island in the Mediterranean Sea, located off the southern toe of Italy.", "Sicily", ["sicilia"], "Wikipedia - Mediterranean Islands"),
        ("The body of water separating Great Britain from France, connected underneath by the Channel Tunnel.", "English Channel", ["la manche"], "Wikipedia - European Waterways"),
        ("The capital city of Thailand, famous for its ornate Grand Palace and floating markets.", "Bangkok", ["krung thep"], "Wikipedia - Southeast Asia"),
        ("The river that flows through Vienna, Bratislava, Budapest, and Belgrade into the Black Sea.", "Danube River", ["danube", "donau"], "Wikipedia - European Rivers"),
        ("The sea that borders Turkey, Ukraine, Russia, Georgia, Romania, and Bulgaria.", "Black Sea", ["the black sea"], "Wikipedia - Inland Seas"),
        ("The capital city of Austria, celebrated for its classical music heritage along the Danube.", "Vienna", ["wien"], "Wikipedia - European Capitals"),
    ]
    for clue, ans, acc, src in items_200:
        q.append({"value": 200, "clue": clue, "answer": ans, "accepted": acc, "source": src})

    # $300 tier (40 items)
    items_300 = [
        ("The deepest known oceanic trench on Earth, plunging nearly 11,000 meters in the western Pacific.", "Mariana Trench", ["marianas trench", "challenger deep"], "Wikipedia - Oceanography"),
        ("The only country in the world that borders both the Caspian Sea and the Persian Gulf.", "Iran", ["islamic republic of iran", "persia"], "Wikipedia - Middle East"),
        ("The capital city of New Zealand, the southernmost national capital city in the world.", "Wellington", ["te whanganui-a-tara"], "Wikipedia - World Capitals"),
        ("The African country formed in July 2011, making it the youngest internationally recognized sovereign state.", "South Sudan", ["republic of south sudan"], "Wikipedia - Geopolitics"),
        ("The strait that connects the Black Sea to the Sea of Marmara, dividing European and Asian Istanbul.", "Bosphorus", ["bosporus", "istanbul strait"], "Wikipedia - World Straits"),
        ("The inland lake shared by Kazakhstan and Uzbekistan that has lost over 90% of its volume since 1960.", "Aral Sea", ["the aral sea"], "Wikipedia - Environmental Geography"),
        ("The capital city of Norway, situated at the head of the Oslofjord.", "Oslo", ["kristiania"], "Wikipedia - Nordic Capitals"),
        ("The landlocked country in South America bordered by Brazil, Bolivia, and Argentina.", "Paraguay", ["republic of paraguay"], "Wikipedia - Landlocked Countries"),
        ("The capital city of Kenya, known as the 'Green City in the Sun'.", "Nairobi", ["city of nairobi"], "Wikipedia - African Capitals"),
        ("The group of islands in the North Atlantic that are a self-governing archipelago of Denmark, known for puffins.", "Faroe Islands", ["faeroe islands", "føroyar"], "Wikipedia - North Atlantic"),
        ("The capital city of Colombia, situated on a high plateau in the Andes at 2,640 meters elevation.", "Bogota", ["bogotá", "bogota d.c."], "Wikipedia - South American Capitals"),
        ("The body of water that separates Saudi Arabia from Egypt and Sudan.", "Red Sea", ["the red sea"], "Wikipedia - Middle East"),
        ("The country that has the highest number of natural lakes in the world, with over 879,000.", "Canada", ["dominion of canada"], "Wikipedia - Limnology"),
        ("The capital city of Poland, rebuilt after extensive destruction in World War II along the Vistula River.", "Warsaw", ["warszawa"], "Wikipedia - European Capitals"),
        ("The peninsula in Northeast Asia that is divided along the 38th parallel.", "Korean Peninsula", ["korea"], "Wikipedia - East Asia"),
        ("The capital city of the Czech Republic, known as the 'City of a Hundred Spires' along the Vltava River.", "Prague", ["praha"], "Wikipedia - Central Europe"),
        ("The arid desert plateau in northern Chile that is considered the driest non-polar desert in the world.", "Atacama Desert", ["atacama"], "Wikipedia - Deserts"),
        ("The capital city of Finland, situated on the shore of the Gulf of Finland.", "Helsinki", ["helsingfors"], "Wikipedia - Nordic Capitals"),
        ("The active stratovolcano on the island of Sicily that is Europe's highest and most active volcano.", "Mount Etna", ["etna"], "Wikipedia - Volcanology"),
        ("The capital city of Saudi Arabia, situated in the center of the Arabian Peninsula.", "Riyadh", ["ar-riyad"], "Wikipedia - Middle East Capitals"),
        ("The narrow waterway connecting the Persian Gulf to the Gulf of Oman, vital for global oil transit.", "Strait of Hormuz", ["hormuz"], "Wikipedia - Strategic Waterways"),
        ("The African river that crosses the Equator twice, the second-longest river in Africa.", "Congo River", ["the congo", "zaire river"], "Wikipedia - African Rivers"),
        ("The capital city of Peru, founded by Spanish conquistador Francisco Pizarro in 1535.", "Lima", ["city of the kings"], "Wikipedia - South America"),
        ("The mountainous microstate situated between France and Spain in the Pyrenees.", "Andorra", ["principality of andorra"], "Wikipedia - Microstates"),
        ("The capital city of the Philippines, situated on the eastern shore of Manila Bay on Luzon.", "Manila", ["maynila"], "Wikipedia - Southeast Asian Capitals"),
        ("The mountain range running north-to-south down the entire spine of peninsular Italy.", "The Apennines", ["apennine mountains", "apennines"], "Wikipedia - Italian Geography"),
        ("The capital city of Cuba, famous for vintage 1950s American cars and the Malecón promenade.", "Havana", ["la habana"], "Wikipedia - Caribbean Capitals"),
        ("The second-largest country by land area entirely within Europe, with capital at Kyiv.", "Ukraine", ["ukrayina"], "Wikipedia - Eastern Europe"),
        ("The capital city of Scotland, dominated by a historic castle perched atop an extinct volcanic plug.", "Edinburgh", ["dùn èideann"], "Wikipedia - British Geography"),
        ("The gulf that separates Sweden and Finland in the northernmost arm of the Baltic Sea.", "Gulf of Bothnia", ["bothnia"], "Wikipedia - Baltic Geography"),
        ("The capital city of Denmark, famous for the Tivoli Gardens and the Little Mermaid statue.", "Copenhagen", ["københavn"], "Wikipedia - Nordic Capitals"),
        ("The body of water separating the Arabian Peninsula from the Horn of Africa, entering the Red Sea via Bab-el-Mandeb.", "Gulf of Aden", ["aden"], "Wikipedia - Maritime Geography"),
        ("The capital city of Hungary, split into two historic halves by the Danube River.", "Budapest", ["buda and pest"], "Wikipedia - European Capitals"),
        ("The high-altitude salt flat in southwest Bolivia that is the world's largest salt flat (over 10,000 km²).", "Salar de Uyuni", ["uyuni salt flat"], "Wikipedia - Landforms"),
        ("The capital city of Morocco, situated on the Atlantic coast at the mouth of the Bou Regreg River.", "Rabat", ["ar-ribat"], "Wikipedia - North Africa"),
        ("The strait that separates the South Island of New Zealand from the North Island.", "Cook Strait", ["cook"], "Wikipedia - New Zealand Geography"),
        ("The capital city of Iceland, the northernmost capital of a sovereign state in the world.", "Reykjavik", ["reykjavík"], "Wikipedia - Nordic Capitals"),
        ("The mountain range that forms the backbone of the Italian, French, Swiss, and Austrian highlands.", "The Alps", ["alps", "alpen"], "Wikipedia - European Mountain Ranges"),
        ("The capital city of Chile, nestled in a valley surrounded by the snow-capped Andes.", "Santiago", ["santiago de chile"], "Wikipedia - South American Capitals"),
        ("The world's highest navigable body of water for commercial craft, shared by Peru and Bolivia.", "Lake Titicaca", ["titicaca"], "Wikipedia - High Altitude Lakes"),
    ]
    for clue, ans, acc, src in items_300:
        q.append({"value": 300, "clue": clue, "answer": ans, "accepted": acc, "source": src})

    # $400 tier (40 items)
    items_400 = [
        ("The capital city of Kazakhstan, which was renamed Nur-Sultan from 2019 to 2022 before reverting.", "Astana", ["nur-sultan", "tselinograd"], "Wikipedia - Central Asia"),
        ("The disputed desert territory in North Africa claimed by both Morocco and the Polisario Front.", "Western Sahara", ["sahrawi arab democratic republic"], "Wikipedia - Disputed Territories"),
        ("The island in the Indian Ocean divided between three sovereign nations: Indonesia, Malaysia, and Brunei.", "Borneo", ["kalimantan"], "Wikipedia - Southeast Asian Islands"),
        ("The southernmost continental point of Africa, marking the dividing line between Atlantic and Indian Oceans.", "Cape Agulhas", ["agulhas"], "Wikipedia - African Geography"),
        ("The capital city of Mongolia, the coldest national capital city in the world by average temperature.", "Ulaanbaatar", ["ulan bator"], "Wikipedia - Central Asia"),
        ("The narrow strip of land in northeastern Namibia that extends east to the Zambezi River.", "Caprivi Strip", ["zambezi region"], "Wikipedia - African Geopolitics"),
        ("The capital city of Azerbaijan, situated on the Caspian Sea on the Absheron Peninsula.", "Baku", ["baki"], "Wikipedia - Caucasus"),
        ("The island nation in the Persian Gulf connected to Saudi Arabia by the King Fahd Causeway.", "Bahrain", ["kingdom of bahrain"], "Wikipedia - Middle East"),
        ("The capital city of Georgia, nestled in the Mtkvari River valley in the Caucasus.", "Tbilisi", ["tiflis"], "Wikipedia - Caucasus Capitals"),
        ("The strait that separates the island of Sumatra from the Malay Peninsula, one of the world's busiest shipping lanes.", "Strait of Malacca", ["malacca strait", "melaka"], "Wikipedia - Maritime Chokepoints"),
        ("The capital city of Bolivia that is the constitutional capital, while La Paz is the seat of government.", "Sucre", ["charcas"], "Wikipedia - South American Capitals"),
        ("The desert in southern Africa that covers much of Botswana and parts of Namibia and South Africa.", "Kalahari Desert", ["kalahari"], "Wikipedia - African Deserts"),
        ("The capital city of Armenia, one of the world's oldest continuously inhabited cities, overlooking Mount Ararat.", "Yerevan", ["erebuni"], "Wikipedia - Ancient Capitals"),
        ("The French overseas department and island in the Indian Ocean east of Madagascar, known for Piton de la Fournaise.", "Reunion", ["réunion", "la réunion"], "Wikipedia - French Overseas"),
        ("The capital city of Ecuador, situated at 2,850 meters on the slopes of the Pichincha volcano.", "Quito", ["san francisco de quito"], "Wikipedia - Andean Capitals"),
        ("The archipelago off the southern tip of South America separated from the mainland by the Strait of Magellan.", "Tierra del Fuego", ["land of fire"], "Wikipedia - Southern Cone"),
        ("The capital city of Uzbekistan, the most populous city in Central Asia.", "Tashkent", ["toshkent"], "Wikipedia - Silk Road"),
        ("The autonomous region of Portugal consisting of nine volcanic islands in the North Atlantic.", "The Azores", ["azores", "açores"], "Wikipedia - Atlantic Islands"),
        ("The capital city of Jordan, built on seven hills and famous for the Roman Theater and Citadel.", "Amman", ["philadelphia"], "Wikipedia - Middle East Capitals"),
        ("The river in Southeast Asia that flows through China, Myanmar, Laos, Thailand, Cambodia, and Vietnam.", "Mekong River", ["mekong", "lancang"], "Wikipedia - Asian Rivers"),
        ("The capital city of Cyprus, the only divided capital city remaining in Europe.", "Nicosia", ["lefkosia"], "Wikipedia - European Capitals"),
        ("The inland drainage basin in Central Asia that is the largest cold desert in Asia, covering southern Mongolia and northern China.", "Gobi Desert", ["the gobi"], "Wikipedia - Deserts"),
        ("The capital city of Malta, a fortified UNESCO World Heritage city built on a peninsula by the Knights of St. John.", "Valletta", ["il-belt"], "Wikipedia - Mediterranean Capitals"),
        ("The volcanic island in the South Atlantic that is considered the most remote permanently inhabited archipelago on Earth.", "Tristan da Cunha", ["tristan"], "Wikipedia - Remote Islands"),
        ("The capital city of Belarus, known for its extensive Soviet Stalinist Empire-style architecture.", "Minsk", ["mensk"], "Wikipedia - Eastern Europe"),
        ("The mountain pass that connects Pakistan and Afghanistan through the Hindu Kush range.", "Khyber Pass", ["the khyber pass"], "Wikipedia - Historic Passes"),
        ("The capital city of Mozambique, located on the natural harbor of Maputo Bay on the Indian Ocean.", "Maputo", ["lourenço marques"], "Wikipedia - African Capitals"),
        ("The high plateau in southern Argentina between the Andes and the Atlantic Ocean.", "Patagonia", ["patagonian steppe"], "Wikipedia - South America"),
        ("The capital city of Slovakia, situated on the borders with Austria and Hungary.", "Bratislava", ["pressburg"], "Wikipedia - Central Europe"),
        ("The group of three rocky promontories at the southern tip of the Baja California Peninsula in Mexico.", "Land's End", ["el arco", "cabo san lucas"], "Wikipedia - Mexican Geography"),
        ("The capital city of Lithuania, celebrated for its Baroque Old Town along the Neris River.", "Vilnius", ["wilno"], "Wikipedia - Baltic Capitals"),
        ("The world's highest active volcano, standing at 6,893 meters on the border of Argentina and Chile.", "Ojos del Salado", ["nevado ojos del salado"], "Wikipedia - Volcanology"),
        ("The capital city of Latvia, situated at the mouth of the Daugava River on the Gulf of Riga.", "Riga", ["rīga"], "Wikipedia - Baltic Capitals"),
        ("The salt lake in Djibouti that is the lowest point on the African continent at 155 meters below sea level.", "Lake Assal", ["assal"], "Wikipedia - African Geography"),
        ("The capital city of Estonia, famous for its exceptionally preserved medieval cobblestone Old Town.", "Tallinn", ["reval"], "Wikipedia - Baltic Capitals"),
        ("The uninhabited coral atoll in the central Pacific that is the largest coral atoll by land area in the world.", "Kiritimati", ["christmas island kiribati"], "Wikipedia - Pacific Atolls"),
        ("The capital city of Slovenia, through which the Ljubljanica River flows below a medieval hilltop castle.", "Ljubljana", ["laibach"], "Wikipedia - Balkan Capitals"),
        ("The body of water between northern Australia and New Guinea connecting the Indian Ocean to the Coral Sea.", "Arafura Sea", ["arafura"], "Wikipedia - Oceanography"),
        ("The capital city of Albania, known for its colorful Ottoman and Italian-era architecture around Skanderbeg Square.", "Tirana", ["tiranë"], "Wikipedia - Balkan Capitals"),
        ("The massive sandstone monolith in central Australia sacred to the indigenous Anangu people, also known as Ayers Rock.", "Uluru", ["ayers rock"], "Wikipedia - Australian Landmarks"),
    ]
    for clue, ans, acc, src in items_400:
        q.append({"value": 400, "clue": clue, "answer": ans, "accepted": acc, "source": src})

    # $500 tier (40 items)
    items_500 = [
        ("The only two doubly landlocked countries in the world (surrounded exclusively by other landlocked nations).", "Liechtenstein and Uzbekistan", ["uzbekistan and liechtenstein"], "Wikipedia - Landlocked Countries"),
        ("The capital city of Bhutan, the only national capital in the world with no traffic lights.", "Thimphu", ["thimbu"], "Wikipedia - Himalayan Kingdoms"),
        ("The remote volcanic island in the South Atlantic owned by Norway, considered the most isolated uninhabited island on Earth.", "Bouvet Island", ["bouvetøya", "bouvet"], "Wikipedia - Antarctic Geography"),
        ("The capital city of Tuvalu, an atoll that is among the most vulnerable low-lying nations to sea-level rise.", "Funafuti", ["vaiaku"], "Wikipedia - Pacific Island Nations"),
        ("The sovereign microstate that is the world's oldest surviving constitutional republic, founded in 301 AD atop Mount Titano.", "San Marino", ["most serene republic of san marino"], "Wikipedia - Microstates"),
        ("The point in the Pacific Ocean that is the oceanic pole of inaccessibility, furthest from any land (~2,688 km).", "Point Nemo", ["pole of inaccessibility"], "Wikipedia - Extreme Points"),
        ("The capital city of Palau, which replaced Koror in 2006 as the national capital.", "Ngerulmud", ["melekeok"], "Wikipedia - Pacific Capitals"),
        ("The unique condominium border arrangement on Pheasant Island on the Bidasoa River, alternating sovereignty every six months between these two nations.", "France and Spain", ["spain and france"], "Wikipedia - International Borders"),
        ("The capital city of Suriname, situated on the banks of the Suriname River near the Atlantic coast.", "Paramaribo", ["par'bo"], "Wikipedia - Guianas"),
        ("The high-altitude plateau in Central Asia known as the 'Roof of the World', where several major mountain ranges converge.", "The Pamir Mountains", ["pamir knot", "pamirs"], "Wikipedia - Asian Geography"),
        ("The capital city of Mauritania, which grew from a small fishing village to a desert metropolis after 1957 independence.", "Nouakchott", ["nwakchot"], "Wikipedia - Sahel Geography"),
        ("The semi-autonomous Russian republic located in southern Siberia containing the geographical center of Asia.", "Tuva", ["tyva", "tuvan republic"], "Wikipedia - Russian Republics"),
        ("The capital city of Eritrea, celebrated for its well-preserved Italian modernist and Art Deco architecture.", "Asmara", ["asmara art deco"], "Wikipedia - Horn of Africa"),
        ("The sovereign state with the highest average elevation in the world, where the entire territory lies above 1,400 meters.", "Lesotho", ["kingdom of lesotho", "kingdom in the sky"], "Wikipedia - Elevation Extremes"),
        ("The capital city of Vanuatu, situated on the island of Efate in the southwestern Pacific.", "Port Vila", ["vila"], "Wikipedia - Melanesia"),
        ("The disputed region between Egypt and Sudan that neither country claims, remaining one of Earth's few unclaimed terra nullius territories.", "Bir Tawil", ["bir tawil triangle"], "Wikipedia - Terra Nullius"),
        ("The capital city of the Comoros, situated on the western coast of the volcanic island of Grande Comore.", "Moroni", ["moroni comoros"], "Wikipedia - Indian Ocean Capitals"),
        ("The natural gas crater in the Karakum Desert of Turkmenistan that has been burning continuously since 1971, nicknamed 'Door to Hell'.", "Darvaza Gas Crater", ["door to hell", "gates of hell", "darvaza"], "Wikipedia - Geothermal Wonders"),
        ("The capital city of Equatorial Guinea located on the island of Bioko rather than the mainland.", "Malabo", ["santa isabel"], "Wikipedia - Central Africa"),
        ("The narrow continental peninsula in northwestern Costa Rica that encloses the Gulf of Nicoya.", "Nicoya Peninsula", ["nicoya"], "Wikipedia - Central American Geography"),
        ("The capital city of the Federated States of Micronesia, situated on the island of Pohnpei.", "Palikir", ["pohnpei"], "Wikipedia - Micronesia"),
        ("The geographic point where the borders of Zimbabwe, Zambia, Botswana, and Namibia meet within a few hundred meters on the Zambezi River.", "Kazungula Quadripoint", ["kazungula", "zambezi quadripoint"], "Wikipedia - Border Tripoints"),
        ("The capital city of Sao Tome and Principe, situated on the northeastern coast of São Tomé Island in the Gulf of Guinea.", "Sao Tome", ["são tomé"], "Wikipedia - Island Nations"),
        ("The deep submarine canyon off the coast of Portugal that funnels massive swells, creating the world's largest rideable surf waves.", "Nazare Canyon", ["nazaré canyon", "nazare"], "Wikipedia - Oceanography"),
        ("The capital city of Saint Kitts and Nevis, located on the island of Saint Kitts.", "Basseterre", ["basseterre st kitts"], "Wikipedia - Caribbean Capitals"),
        ("The mountain range in northern Chad that is the highest massif in the Sahara Desert, home to Emi Koussi.", "Tibesti Mountains", ["tibesti massif"], "Wikipedia - Saharan Landforms"),
        ("The capital city of the Marshall Islands, an elongated coral atoll consisting of 64 islands.", "Majuro", ["majuro atoll"], "Wikipedia - Pacific Geography"),
        ("The narrow spit of sand that separates the Curonian Lagoon from the Baltic Sea, shared between Lithuania and Russia's Kaliningrad.", "Curonian Spit", ["kurshskaya kosa"], "Wikipedia - Coastal Geomorphology"),
        ("The capital city of Kiribati, an elongated atoll home to roughly half of the country's population.", "South Tarawa", ["tarawa", "teinainano"], "Wikipedia - Pacific Capitals"),
        ("The subglacial lake in Antarctica buried beneath four kilometers of ice, remaining isolated from the atmosphere for millions of years.", "Lake Vostok", ["vostok"], "Wikipedia - Subglacial Lakes"),
        ("The capital city of Nauru, although Nauru does not have an official designated capital, this district houses parliament.", "Yaren", ["yaren district"], "Wikipedia - Microstate Capitals"),
        ("The Spanish exclave city located on the Mediterranean coast of North Africa, bordered entirely by Morocco.", "Ceuta", ["ciudad autónoma de ceuta"], "Wikipedia - Exclaves"),
        ("The other Spanish exclave city located on the North African coast, situated 250 miles east of Ceuta.", "Melilla", ["ciudad autónoma de melilla"], "Wikipedia - Spanish Geography"),
        ("The high mountain pass in Ladakh, India that is historically celebrated as one of the world's highest motorable passes at 5,359 meters.", "Khardung La", ["khardung pass"], "Wikipedia - Himalayan Passes"),
        ("The volcanic island in the southern Indian Ocean that is an Australian external territory, home to Big Ben volcano.", "Heard Island", ["heard island and mcdonald islands"], "Wikipedia - Subantarctic Islands"),
        ("The archipelago in the Arctic Ocean that is the northernmost territory of Norway, governed under a unique 1920 treaty.", "Svalbard", ["spitsbergen"], "Wikipedia - Arctic Archipelagoes"),
        ("The shallow sea in northern Russia that is an arm of the Barents Sea, almost completely surrounded by Russian territory.", "White Sea", ["beloye more"], "Wikipedia - Arctic Seas"),
        ("The remote coral atoll that is an unincorporated unorganized territory of the US in the central Pacific, where Amelia Earhart planned to refuel.", "Howland Island", ["howland"], "Wikipedia - US Minor Outlying Islands"),
        ("The river that forms the entire border between the US states of Washington and Oregon before emptying into the Pacific.", "Columbia River", ["the columbia"], "Wikipedia - Pacific Northwest"),
        ("The highest mountain peak in the Arctic Circle, standing at 3,694 meters in the Watkins Range of Greenland.", "Gunnbjorn Fjeld", ["gunnbjørn fjeld", "gunnbjorn"], "Wikipedia - Arctic Peaks"),
    ]
    for clue, ans, acc, src in items_300:
        q.append({"value": 500, "clue": clue, "answer": ans, "accepted": acc, "source": src})

    return q

if __name__ == "__main__":
    q = get_questions()
    print("Geography questions count:", len(q))
    from collections import Counter
    print("Tier counts:", Counter(x["value"] for x in q))
