"""
Culinary World & Food - 200 Curated Trivia Questions
40 items per tier: $100, $200, $300, $400, $500
"""

def get_questions():
    q = []
    # $100 tier (40 items)
    items_100 = [
        ("The Italian dish consisting of a flat round base of dough topped with tomato sauce, mozzarella cheese, and toppings.", "Pizza", ["pizza pie", "neapolitan pizza"], "Wikipedia - Italian Cuisine"),
        ("The sweet confection made from roasted and ground cacao seeds, available in milk, dark, and white varieties.", "Chocolate", ["cocoa", "cacao"], "Wikipedia - Chocolate"),
        ("The traditional Mexican dip whose primary green ingredient is mashed ripe avocado.", "Guacamole", ["guac"], "Wikipedia - Mexican Cuisine"),
        ("The Italian dessert whose name translates as 'pick me up', made of espresso-soaked ladyfingers and mascarpone cream.", "Tiramisu", ["tiramisù"], "Wikipedia - Italian Desserts"),
        ("The Japanese dish consisting of vinegared rice served with raw seafood, vegetables, or rolled in nori seaweed.", "Sushi", ["maki", "nigiri"], "Wikipedia - Japanese Cuisine"),
        ("The breakfast staple produced by laying hens with a protective shell, yolk, and albumen.", "Eggs", ["egg", "chicken egg"], "Wikipedia - Eggs as Food"),
        ("The long, thin cylindrical pasta shape originating in Italy whose name means 'little strings'.", "Spaghetti", ["spaghetto"], "Wikipedia - Pasta"),
        ("The staple grain that is the primary food source for more than half of the world's human population, especially in Asia.", "Rice", ["oryza sativa"], "Wikipedia - Cereal Grains"),
        ("The dairy product produced by churning the cream from milk until fat separates from buttermilk.", "Butter", ["dairy butter"], "Wikipedia - Dairy Products"),
        ("The sweet, thick golden liquid produced by bees from floral nectar.", "Honey", ["bee honey"], "Wikipedia - Apiculture"),
        ("The French pastry shaped like a crescent moon, famous for its flaky, buttery layers.", "Croissant", ["croissants"], "Wikipedia - French Viennoiserie"),
        ("The root vegetable that is rich in beta-carotene, giving it its bright orange color.", "Carrot", ["carrots", "daucus carota"], "Wikipedia - Root Vegetables"),
        ("The red condiment traditionally made from tomatoes, vinegar, sugar, and seasonings.", "Ketchup", ["catsup", "tomato ketchup"], "Wikipedia - Condiments"),
        ("The caffeinated beverage brewed from the roasted seeds of Coffea plants.", "Coffee", ["espresso", "brewed coffee"], "Wikipedia - Coffee"),
        ("The frozen dairy dessert made of milk fat, sugar, and flavorings, churned slowly to incorporate air.", "Ice Cream", ["ice-cream"], "Wikipedia - Frozen Desserts"),
        ("The staple baked food prepared from a dough of flour and water, usually leavened with yeast.", "Bread", ["loaf of bread"], "Wikipedia - Baking"),
        ("The green fruit botanically classified as a berry that is sliced or squeezed to give a tart citrus flavor to drinks and guacamole.", "Lime", ["key lime", "citrus aurantiifolia"], "Wikipedia - Citrus Fruits"),
        ("The Mexican street food consisting of a folded corn or flour tortilla filled with seasoned meats and toppings.", "Tacos", ["taco"], "Wikipedia - Mexican Street Food"),
        ("The hot beverage brewed by steeping cured leaves of the Camellia sinensis plant in hot water.", "Tea", ["black tea", "green tea"], "Wikipedia - Tea Culture"),
        ("The yellow edible fruit that grows in hanging clusters, rich in potassium.", "Banana", ["cavendish banana"], "Wikipedia - Tropical Fruits"),
        ("The common seasoning mineral, sodium chloride, used for millennia to preserve and flavor food.", "Salt", ["table salt", "sea salt"], "Wikipedia - Salt"),
        ("The Italian pasta shape that resembles small rice grains, frequently used in soups.", "Orzo", ["risoni"], "Wikipedia - Pasta Varieties"),
        ("The spicy green wasabi paste served with sushi is traditionally made from this Japanese rhizome.", "Wasabi", ["japanese horseradish", "wasabia japonica"], "Wikipedia - Japanese Condiments"),
        ("The cured meat product typically prepared from pork belly that is fried into crispy strips.", "Bacon", ["streaky bacon"], "Wikipedia - Pork"),
        ("The yellow citrus fruit known for its acidic sour juice, rich in Vitamin C.", "Lemon", ["citrus limon"], "Wikipedia - Citrus"),
        ("The sweet treat made by boiling sugar and corn syrup, often eaten on a stick or in chewy morsels.", "Candy", ["lollipops", "hard candy"], "Wikipedia - Confectionery"),
        ("The Italian cheese made from the whey of cow, sheep, or water buffalo milk, commonly used in lasagna.", "Ricotta", ["ricotta cheese"], "Wikipedia - Italian Cheeses"),
        ("The fermented dairy beverage made from milk cultured with lactic acid bacteria, with a thick creamy texture.", "Yogurt", ["yoghurt"], "Wikipedia - Fermented Dairy"),
        ("The popular red fruit botanically classified as a berry that grows on low creeping plants with seeds on the outside.", "Strawberry", ["strawberries", "fragaria"], "Wikipedia - Berries"),
        ("The staple root vegetable native to the Americas that was domesticated in the Andes and is fried into French fries.", "Potato", ["solanum tuberosum", "potatoes"], "Wikipedia - Tubers"),
        ("The common baking ingredient, sodium bicarbonate, used as a leavening agent in quick breads and cookies.", "Baking Soda", ["sodium bicarbonate"], "Wikipedia - Leavening Agents"),
        ("The popular breakfast waffle topping made by boiling sap from the Acer saccharum tree.", "Maple Syrup", ["pure maple syrup"], "Wikipedia - Syrups"),
        ("The pungent bulb consisting of individual cloves covered in paper-like skin, used as a base in almost all cuisines.", "Garlic", ["allium sativum"], "Wikipedia - Allium"),
        ("The sweet red or green pome fruit associated with autumn harvest and Johnny Appleseed.", "Apple", ["malus domestica"], "Wikipedia - Fruit"),
        ("The Mexican spirit distilled from the fermented blue agave plant, native to the city of Tequila.", "Tequila", ["blue agave tequila"], "Wikipedia - Distilled Spirits"),
        ("The red Italian tomato sauce simmered with garlic, onions, and herbs, traditionally used on pizza and pasta.", "Marinara Sauce", ["marinara"], "Wikipedia - Italian Sauces"),
        ("The yellow culinary fat extracted from olives by mechanical pressing, celebrated in Mediterranean cuisine.", "Olive Oil", ["extra virgin olive oil", "evoo"], "Wikipedia - Cooking Oils"),
        ("The popular Asian stir-fry pan with a rounded spherical bottom, traditionally made of carbon steel.", "Wok", ["chinese wok"], "Wikipedia - Cookware"),
        ("The frozen fruit dessert made with fruit juice, sugar, and water, completely dairy-free.", "Sorbet", ["sorbetto"], "Wikipedia - Frozen Desserts"),
        ("The long French bread loaf characterized by a crisp crust and chewy interior, designated as intangible UNESCO heritage.", "Baguette", ["french baguette"], "Wikipedia - French Bread"),
    ]
    for clue, ans, acc, src in items_100:
        q.append({"value": 100, "clue": clue, "answer": ans, "accepted": acc, "source": src})

    # $200 tier (40 items)
    items_200 = [
        ("The traditional Korean fermented side dish made from salted Napa cabbage and Korean radishes with chili powder.", "Kimchi", ["gimchi", "kimchee"], "Wikipedia - Korean Cuisine"),
        ("The prized spice that is the most expensive in the world by weight, harvested from the purple stigmas of crocus flowers.", "Saffron", ["crocus sativus"], "Wikipedia - Spices"),
        ("The hard, granular Italian cow's milk cheese aged for years, known as the 'King of Cheeses' with protected PDO status.", "Parmigiano-Reggiano", ["parmesan", "parmigiano"], "Wikipedia - Italian Cheeses"),
        ("The classic French sauce made by emulsifying egg yolks and melted butter seasoned with fresh lemon juice.", "Hollandaise", ["hollandaise sauce"], "Wikipedia - French Mother Sauces"),
        ("The traditional Japanese soup made from fermented soybean paste dissolved in dashi stock with tofu and scallions.", "Miso Soup", ["misoshiru", "miso"], "Wikipedia - Japanese Soups"),
        ("The Greek brined white cheese curd made from sheep's milk or a blend of sheep and goat's milk.", "Feta", ["feta cheese"], "Wikipedia - Greek Cheeses"),
        ("The French culinary technique of cutting vegetables into long, thin matchstick-like strips.", "Julienne", ["julienning"], "Wikipedia - Knife Cuts"),
        ("The pungent, aromatic underground rhizome widely used in Asian cooking and ginger ale.", "Ginger", ["ginger root", "zingiber officinale"], "Wikipedia - Spices"),
        ("The fermented beverage made by fermenting sweetened black or green tea with a symbiotic culture of bacteria and yeast (SCOBY).", "Kombucha", ["kombucha tea"], "Wikipedia - Fermented Drinks"),
        ("The classic Spanish rice dish originating in Valencia cooked in a wide, shallow pan with saffron, rabbit, or seafood.", "Paella", ["valencian paella"], "Wikipedia - Spanish Cuisine"),
        ("The creamy Italian dessert made by heating sweetened cream with gelatin and letting it chill in molds, meaning 'cooked cream'.", "Panna Cotta", ["pannacotta"], "Wikipedia - Italian Desserts"),
        ("The French culinary term for chopping ingredients into tiny 1-to-2 millimeter cubes.", "Brunoise", ["brunoise cut"], "Wikipedia - Culinary Knife Cuts"),
        ("The spicy chili sauce made from chili pepper paste, vinegar, garlic, sugar, and salt, named after a Thai coastal city.", "Sriracha", ["sriracha sauce"], "Wikipedia - Hot Sauces"),
        ("The Italian pasta dish whose sauce is prepared with raw egg yolks, grated Pecorino Romano cheese, cured guanciale, and black pepper.", "Carbonara", ["spaghetti alla carbonara"], "Wikipedia - Roman Pasta"),
        ("The dark, savory umami condiment brewed from fermented soybeans, roasted grains, brine, and Aspergillus molds.", "Soy Sauce", ["shoyu"], "Wikipedia - Fermented Condiments"),
        ("The aromatic Indian basmati rice dish cooked with fragrant spices like cardamom, cloves, and marinated meat or vegetables.", "Biryani", ["dum biryani"], "Wikipedia - Indian Cuisine"),
        ("The culinary preparation method where food is placed in a plastic pouch and cooked in a temperature-controlled water bath, meaning 'under vacuum'.", "Sous-Vide", ["sous vide"], "Wikipedia - Modernist Cooking"),
        ("The creamy blue-veined cheese of northern Italy made from unskimmed cow's milk, produced in sweet (dolce) or aged (piccante) styles.", "Gorgonzola", ["gorgonzola cheese"], "Wikipedia - Blue Cheeses"),
        ("The Vietnamese noodle soup consisting of fragrant bone broth, rice noodles, herbs, and thinly sliced beef or chicken.", "Pho", ["phở"], "Wikipedia - Vietnamese Cuisine"),
        ("The green pesto sauce originating in Genoa, Italy is traditionally made of fresh basil, garlic, pine nuts, olive oil, and this hard cheese.", "Parmesan", ["parmigiano-reggiano", "pecorino sardo"], "Wikipedia - Ligurian Sauces"),
        ("The French stew of braised chicken cooked with red wine, lardons, mushrooms, and garlic.", "Coq au Vin", ["coq-au-vin"], "Wikipedia - French Classics"),
        ("The Indian flatbread cooked by slapping dough against the blazing clay walls of a cylindrical tandoor oven.", "Naan", ["naan bread", "tandoori naan"], "Wikipedia - Indian Breads"),
        ("The Japanese dish of lightly battered and deep-fried seafood and vegetables introduced by Portuguese missionaries in the 16th century.", "Tempura", ["tenpura"], "Wikipedia - Japanese Cooking"),
        ("The Mexican layered dip sauce made from chocolate, chilies, nuts, seeds, and spices, famously from Puebla and Oaxaca.", "Mole", ["mole poblano", "mole negro"], "Wikipedia - Mexican Sauces"),
        ("The Greek baked casserole dish made with layers of spiced ground lamb or beef, sliced eggplant, and creamy béchamel sauce.", "Moussaka", ["mousakas"], "Wikipedia - Greek Cuisine"),
        ("The French mother sauce made from white roux (butter and flour) whisked with heated whole milk.", "Bechamel", ["béchamel", "béchamel sauce"], "Wikipedia - Mother Sauces"),
        ("The Japanese savory skewered chicken dish grilled over hot binchotan charcoal and basted with sweet tare sauce.", "Yakitori", ["yakitori skewers"], "Wikipedia - Japanese Street Food"),
        ("The famous sweet pastry from Austria made of thin, unleavened dough wrapped around a spiced sliced apple and raisin filling.", "Apple Strudel", ["apfelstrudel"], "Wikipedia - Austrian Pastries"),
        ("The Latin American dish of raw fresh fish cured in freshly squeezed citrus juice (lime or lemon) seasoned with ají peppers and red onions.", "Ceviche", ["cebiche"], "Wikipedia - Peruvian Cuisine"),
        ("The French mother sauce made of a brown veal stock reduced with a dark brown roux and tomato purée.", "Espagnole", ["espagnole sauce", "brown sauce"], "Wikipedia - French Cuisine"),
        ("The Japanese noodle dish served in a rich meat or fish broth flavored with soy sauce or miso, topped with chashu pork and menma.", "Ramen", ["ramen noodles"], "Wikipedia - Japanese Noodles"),
        ("The green herb of the parsley family whose leaves are known as cilantro, while its dried aromatic seeds are called this.", "Coriander", ["coriander seeds"], "Wikipedia - Culinary Herbs"),
        ("The French stew from Provence made of simmered summer vegetables: eggplant, zucchini, bell peppers, onions, tomatoes, and herbs.", "Ratatouille", ["ratatouille niçoise"], "Wikipedia - Provencal Cuisine"),
        ("The Middle Eastern dip made of mashed chickpeas blended with tahini, lemon juice, garlic, and olive oil.", "Hummus", ["hommus"], "Wikipedia - Levantine Cuisine"),
        ("The North African cracked wheat pasta granules steamed in a perforated pot over boiling stew, a national dish of the Maghreb.", "Couscous", ["kuskus"], "Wikipedia - Maghrebi Cuisine"),
        ("The Spanish cold soup originating in Andalusia made of blended raw ripe tomatoes, cucumbers, bell peppers, garlic, and olive oil.", "Gazpacho", ["gazpacho andaluz"], "Wikipedia - Cold Soups"),
        ("The Swiss melted cheese dish served in a communal pot over a burner, into which diners dip cubes of crusty bread using long forks.", "Fondue", ["cheese fondue"], "Wikipedia - Swiss Cuisine"),
        ("The Thai soup famous for its hot and sour flavors, fragrant with lemongrass, kaffir lime leaves, galangal, lime juice, and chili.", "Tom Yum", ["tom yum goong"], "Wikipedia - Thai Soups"),
        ("The soft, fresh Italian cheese made from mozzarella and cream, whose outer shell conceals a creamy, buttery interior.", "Burrata", ["burrata cheese"], "Wikipedia - Fresh Cheeses"),
        ("The American chocolate layer cake containing cherries, whipped cream, and chocolate shavings, originating in Germany's Black Forest.", "Black Forest Cake", ["schwarzwälder kirschtorte"], "Wikipedia - German Cakes"),
    ]
    for clue, ans, acc, src in items_200:
        q.append({"value": 200, "clue": clue, "answer": ans, "accepted": acc, "source": src})

    # $300 tier (40 items)
    items_300 = [
        ("The rare subterranean fungus hunted with trained pigs or dogs in France and Italy, prized for its earthy aroma.", "Truffle", ["truffles", "tartufo", "black truffle", "white truffle"], "Wikipedia - Truffles"),
        ("The traditional Japanese delicacy prepared from poisonous pufferfish that can be fatal if the lethal tetrodotoxin is not removed.", "Fugu", ["pufferfish", "torafugu"], "Wikipedia - Japanese Delicacies"),
        ("The aromatic paste made of crushed toasted sesame seeds, fundamental to hummus and baba ghanoush.", "Tahini", ["tahina"], "Wikipedia - Middle Eastern Condiments"),
        ("The Spanish cured ham made from free-range acorn-fed black Iberian pigs, renowned as the pinnacle of cured charcuterie.", "Jamon Iberico", ["jamón ibérico de bellota", "jamon iberico"], "Wikipedia - Cured Meats"),
        ("The traditional French cooking base composed of two parts diced onions, one part carrots, and one part celery gently cooked in butter.", "Mirepoix", ["french mirepoix"], "Wikipedia - Culinary Bases"),
        ("The high-grade Japanese beef famed for its intense intramuscular fat marbling, originating from Tajima cattle in Hyogo Prefecture.", "Kobe Beef", ["wagyu", "kobe wagyu"], "Wikipedia - Wagyu"),
        ("The French technique of burning off alcohol in a pan by igniting spirits (like Cognac) to impart subtle flavor.", "Flambé", ["flambeing"], "Wikipedia - Cooking Techniques"),
        ("The French blue cheese aged in the natural Combalou limestone caves of southern France, made from raw sheep's milk.", "Roquefort", ["roquefort cheese"], "Wikipedia - French Cheeses"),
        ("The chemical reaction between amino acids and reducing sugars that produces the browned, savory crust on seared steaks and toasted bread.", "Maillard Reaction", ["the maillard reaction"], "Wikipedia - Food Chemistry"),
        ("The fermented soybean product originating in Indonesia formed into solid firm blocks, rich in plant protein and fiber.", "Tempeh", ["tempe"], "Wikipedia - Indonesian Cuisine"),
        ("The Mexican fresh cheese whose name translates as 'cheese of the town', commonly crumbled over refried beans and enchiladas.", "Cotija", ["queso cotija"], "Wikipedia - Mexican Cheeses"),
        ("The thin, delicate French pancake batter made of eggs, milk, and flour, cooked on a round cast-iron griddle (billig).", "Crepe", ["crêpe", "galette"], "Wikipedia - French Pastries"),
        ("The Italian dessert made by drowning a scoop of vanilla gelato or ice cream in a shot of hot, freshly brewed espresso.", "Affogato", ["affogato al caffe"], "Wikipedia - Italian Desserts"),
        ("The French term for the practice of measuring, preparing, and organizing all ingredients before cooking begins, meaning 'everything in its place'.", "Mise en Place", ["mise-en-place"], "Wikipedia - Professional Kitchens"),
        ("The Indian clarified butter cooked until milk solids caramelize and are strained out, leaving a nutty golden cooking fat.", "Ghee", ["clarified butter"], "Wikipedia - Indian Cooking"),
        ("The pungent, spiky Southeast Asian fruit known as the 'King of Fruits', so smelly it is banned on public transit in Singapore.", "Durian", ["durio zibethinus"], "Wikipedia - Tropical Fruits"),
        ("The traditional French mother sauce made by thickening a clear white stock (veal, chicken, or fish) with a blond roux.", "Velouté", ["velouté sauce"], "Wikipedia - Mother Sauces"),
        ("The spicy chili and garlic paste originating in Tunisia, widely used across North African and Middle Eastern cooking.", "Harissa", ["harissa paste"], "Wikipedia - North African Condiments"),
        ("The cured pork jowl used in authentic Roman recipes for spaghetti alla carbonara and bucatini all'amatriciana.", "Guanciale", ["pork jowl"], "Wikipedia - Italian Charcuterie"),
        ("The culinary technique of plunging vegetables into boiling water briefly and then immediately submerging them in ice water to stop cooking.", "Blanching", ["blanch and shock"], "Wikipedia - Cooking Techniques"),
        ("The French butter and flour mixture kneaded together into a paste (uncooked) and whisked into sauces at the end to thicken.", "Beurre Maniè", ["beurre manie"], "Wikipedia - Sauce Thickeners"),
        ("The Spanish sheep's milk cheese aged in the natural caves of La Mancha, identifiable by the herringbone pattern pressed into its rind.", "Manchego", ["queso manchego"], "Wikipedia - Spanish Cheeses"),
        ("The rich French bread dough enriched with a high proportion of butter and eggs, creating a golden, tender crumb.", "Brioche", ["pain brioché"], "Wikipedia - Enriched Breads"),
        ("The green, licorice-flavored alcoholic spirit distilled with anise and wormwood, famously nicknamed 'The Green Fairy'.", "Absinthe", ["la fée verte"], "Wikipedia - Distilled Spirits"),
        ("The Japanese condiment made from fermented grated daikon radish and red chili peppers, commonly served with hot pots.", "Momiji Oroshi", ["momiji-oroshi"], "Wikipedia - Japanese Condiments"),
        ("The process of gently heating wine, cream, or vinegar and whisking in cold butter cubes to form a glossy, emulsified pan sauce.", "Monte au Beurre", ["monter au beurre"], "Wikipedia - French Sauces"),
        ("The fermented Korean chili paste made from chili powder, glutinous rice, fermented soybeans, and salt, stored in earthenware onggi jars.", "Gochujang", ["gochu-jang"], "Wikipedia - Korean Ferments"),
        ("The classic French seafood stew originating from the port city of Marseille, prepared with at least three varieties of fresh Mediterranean rockfish.", "Bouillabaisse", ["bouillabaisse marseillaise"], "Wikipedia - Seafood Stews"),
        ("The Greek dip made of strained yogurt blended with grated cucumber, minced garlic, olive oil, and fresh dill.", "Tzatziki", ["tarator"], "Wikipedia - Greek Dips"),
        ("The English dessert consisting of bananas, whipped cream, and thick boiled caramel toffee on a buttery biscuit crumb base.", "Banoffee Pie", ["banoffee"], "Wikipedia - British Desserts"),
        ("The French technique of removing and dissolving browned food residue from the bottom of a hot pan with wine or stock to make pan sauce.", "Deglazing", ["deglaze"], "Wikipedia - Culinary Techniques"),
        ("The North African dish of poached eggs in a simmering spiced sauce of crushed tomatoes, bell peppers, onions, cumin, and harissa.", "Shakshuka", ["shakshouka"], "Wikipedia - Middle Eastern Breakfasts"),
        ("The classic French mother sauce made of clarified butter emulsified into warm egg yolks seasoned with tarragon and shallot reduction.", "Béarnaise Sauce", ["bearnaise", "sauce béarnaise"], "Wikipedia - French Sauces"),
        ("The traditional Polish soup made from fermented rye flour starter, served with boiled eggs, kielbasa sausage, and marjoram.", "Zurek", ["żurek", "white borscht"], "Wikipedia - Polish Soups"),
        ("The thin, delicate leaf pastry dough of Middle Eastern and Balkan origin used to prepare baklava and spanakopita.", "Phyllo", ["filo", "phyllo dough"], "Wikipedia - Pastry Dough"),
        ("The spicy, spreadable Calabrian pork salami made with shoulder meat, fatback, and fiery red Calabrian chili peppers.", "Nduja", ["'nduja"], "Wikipedia - Italian Charcuterie"),
        ("The Japanese grade of green tea made from shade-grown tea leaves that are stone-ground into a fine jade powder for tea ceremonies.", "Matcha", ["ceremonial matcha"], "Wikipedia - Green Tea"),
        ("The Peruvian purple corn beverage boiled with pineapple rinds, cinnamon, cloves, and sweetened with sugar and lime.", "Chicha Morada", ["chicha"], "Wikipedia - Peruvian Beverages"),
        ("The technique of wrapping lean cuts of meat (like venison or turkey) with strips of pork fat or bacon before roasting to prevent drying.", "Barding", ["barding meat"], "Wikipedia - Culinary Techniques"),
        ("The classic French dessert consisting of a rich vanilla custard base topped with a hard, brittle layer of caramelized sugar torched with heat.", "Crème Brûlée", ["creme brulee", "burnt cream"], "Wikipedia - Custard Desserts"),
    ]
    for clue, ans, acc, src in items_300:
        q.append({"value": 300, "clue": clue, "answer": ans, "accepted": acc, "source": src})

    # $400 tier (40 items)
    items_400 = [
        ("The traditional Italian sheep's milk cheese from Sardinia that is intentionally infested with live cheese fly larvae (Piophila casei).", "Casu Marzu", ["casu martzu", "maggot cheese"], "Wikipedia - Entomophagy"),
        ("The chemical alkaloid compound found in chili peppers that binds to TRPV1 thermal receptors, creating the sensation of heat.", "Capsaicin", ["8-methyl-N-vanillyl-6-nonenamide"], "Wikipedia - Spice Chemistry"),
        ("The scale created by an American pharmacist in 1912 that measures the piquancy (spiciness) of chili peppers in SHU units.", "Scoville Scale", ["scoville heat units", "wilbur scoville"], "Wikipedia - Chili Heat"),
        ("The traditional Japanese seasoning flakes made from dried, fermented, and smoked skipjack tuna shaved into micro-thin ribbons.", "Katsuobushi", ["bonito flakes"], "Wikipedia - Dashi Stock"),
        ("The French pastry cream made by folding whipped cream into pastry cream (crème pâtissière) stabilized with gelatin.", "Crème Diplomat", ["diplomat cream", "bavarian cream"], "Wikipedia - Pastry Creams"),
        ("The French culinary preparation of meat (traditionally duck or goose) salted and slow-cooked submerged in its own rendered fat for preservation.", "Confit", ["duck confit"], "Wikipedia - Confit"),
        ("The Mexican dried chili pepper that is simply the dried, wrinkled form of the fresh poblano pepper.", "Ancho Chili", ["ancho pepper"], "Wikipedia - Mexican Chilies"),
        ("The Mexican dried smoked chili pepper that is made by smoke-drying ripe red jalapeño peppers.", "Chipotle", ["chipotle pepper"], "Wikipedia - Smoked Chilies"),
        ("The dark, savory umami paste produced in the UK from leftover brewer's yeast extract with a famous 'Love It or Hate It' slogan.", "Marmite", ["marmite spread"], "Wikipedia - Yeast Extracts"),
        ("The French chemical culinary technique of combining oil and vinegar using an emulsifying surfactant like mustard or lecithin.", "Emulsification", ["colloidal emulsion"], "Wikipedia - Food Emulsions"),
        ("The Portuguese salt cod that has been dried and cured for months, famously said to have 365 recipes—one for each day of the year.", "Bacalhau", ["bacalao", "salt cod"], "Wikipedia - Portuguese Cuisine"),
        ("The aromatic wild root vegetable belonging to the onion genus harvested in Appalachian and eastern North American forests in early spring.", "Ramps", ["allium tricoccum", "wild leeks"], "Wikipedia - Foraged Foods"),
        ("The traditional French brown veal stock reduced to a glossy, gelatinous jelly glaze with intense concentrated beef flavor.", "Glace de Viande", ["meat glaze"], "Wikipedia - Stock Reductions"),
        ("The fermented fish sauce of the ancient Roman world produced by fermenting fish intestines in salt vats in the Mediterranean sun.", "Garum", ["liquamen"], "Wikipedia - Roman Condiments"),
        ("The prized and expensive white truffle that grows underground in the Piedmont region of northwest Italy around oak and hazelnut roots.", "Alba White Truffle", ["tuber magnatum pico", "white truffle of alba"], "Wikipedia - Truffle Foraging"),
        ("The traditional Greek and Turkish liquor flavored with anise seeds that turns milky white when water or ice is added (ouzo effect).", "Ouzo", ["raki", "arak"], "Wikipedia - Anise Spirits"),
        ("The classic French pastry dough used to make éclairs, cream puffs, and gougères, leavened solely by high moisture steam during baking.", "Choux Pastry", ["pâte à choux"], "Wikipedia - Pastry Doughs"),
        ("The dense, sweet Indian dessert made of reduced full-fat milk simmered in a wide pan for hours until solids form, used as the base for gulab jamun.", "Khoya", ["mawa", "khoa"], "Wikipedia - Indian Confectionery"),
        ("The traditional Mexican cooking technique of roasting chilies, tomatoes, and garlic on a dry cast-iron comal griddle until blackened and charred.", "Tatemar", ["tatemado"], "Wikipedia - Mexican Cooking Techniques"),
        ("The Italian pasta shape formed like small curled ears originating from the southern region of Puglia, traditionally served with cime di rapa.", "Orecchiette", ["orecchietta"], "Wikipedia - Apulian Pasta"),
        ("The complex process in bread baking where flour enzymes (amylase) break down starches into fermentable sugars during a rest period before kneading.", "Autolyse", ["autolysis"], "Wikipedia - Bread Science"),
        ("The traditional French fish stock made by simmering non-oily white fish bones with mirepoix, white wine, and aromatics for 30 minutes.", "Fumet", ["fish fumet"], "Wikipedia - French Stocks"),
        ("The dried, smoked pork sausage seasoned with paprika and garlic that is the culinary cornerstone of Portuguese and Spanish charcuterie.", "Chorizo", ["chouriço"], "Wikipedia - Iberian Sausages"),
        ("The Japanese culinary cutting technique used on sashimi to make fine decorative cross-hatch incisions on squid to tenderize and hold soy sauce.", "Matsukasa-giri", ["pinecone cut"], "Wikipedia - Japanese Knife Skills"),
        ("The ancient fermented Ethiopian sourdough flatbread with a spongy, bubbly texture made from teff flour, used to scoop up wats.", "Injera", ["enjera"], "Wikipedia - Ethiopian Cuisine"),
        ("The Italian dessert wine made by air-drying harvested grapes on straw mats for months to concentrate sugars before fermentation, aged in small caratelli casks.", "Vin Santo", ["holy wine"], "Wikipedia - Dessert Wines"),
        ("The French culinary technique of pressing liquid fat, juices, and flavor from roasted duck carcasses using a heavy silver press to make blood sauce.", "Canard à la Presse", ["pressed duck"], "Wikipedia - Haute Cuisine"),
        ("The traditional Japanese grill charcoal made from Ubame oak heated to over 1,000°C and smothered in ash, burning smokelessly with intense infrared heat.", "Binchotan", ["white charcoal"], "Wikipedia - Binchotan"),
        ("The French mother sauce that is a velouté enriched with egg yolks, heavy cream, and a squeeze of fresh lemon juice.", "Sauce Allemande", ["allemande sauce", "german sauce"], "Wikipedia - French Mother Sauces"),
        ("The traditional Mexican stone mortar and pestle carved from volcanic basalt used to crush spices and make authentic table salsas.", "Molcajete", ["molcajete y tejolote"], "Wikipedia - Mexican Cookware"),
        ("The enzyme extracted from the stomach lining of young unweaned ruminants (containing chymosin) used to curdle milk during cheesemaking.", "Rennet", ["animal rennet", "chymosin"], "Wikipedia - Cheesemaking"),
        ("The culinary technique in molecular gastronomy invented by Ferran Adrià where liquid sodium alginate is dropped into calcium lactate to form bursting pearls.", "Spherification", ["reverse spherification"], "Wikipedia - Molecular Gastronomy"),
        ("The ancient, unfermented Georgian wine-making technique where crushed grapes with skins and stems ferment underground in massive terracotta vessels.", "Qvevri", ["kvevri"], "Wikipedia - Georgian Wine"),
        ("The Italian cured meat made from whole pork neck or shoulder dry-cured with nutmeg, cinnamon, and red wine, wrapped in natural casing.", "Capocollo", ["coppa", "gabagool"], "Wikipedia - Italian Salumi"),
        ("The Japanese cooking mirin rice wine that has zero alcohol and high sugar content, distinct from pure fermented hon-mirin.", "Mirin-fu Chomiryo", ["mirin-like seasoning"], "Wikipedia - Japanese Condiments"),
        ("The French culinary term for clarified stock that has been refined using whipped egg whites to trap impurities, resulting in crystal-clear broth.", "Consommé", ["consomme"], "Wikipedia - French Soups"),
        ("The traditional Scottish pudding composed of minced sheep's liver, lungs, and heart mixed with oatmeal, suet, and spices encased in stomach.", "Haggis", ["scottish haggis"], "Wikipedia - Scottish Cuisine"),
        ("The chemical leavening reaction where yeast ferments glucose anaerobically to produce these two primary chemical byproducts.", "Carbon Dioxide and Ethanol", ["co2 and alcohol"], "Wikipedia - Fermentation"),
        ("The traditional Vietnamese dip sauce made of fermented fish sauce, lime juice, sugar, water, minced garlic, and bird's eye chilies.", "Nuoc Cham", ["nước chấm"], "Wikipedia - Vietnamese Sauces"),
        ("The pastry lamination technique where butter is folded into dough through successive 'letter turns' and 'book turns' to create hundreds of alternating layers.", "Lamination", ["laminated dough"], "Wikipedia - Pastry Techniques"),
    ]
    for clue, ans, acc, src in items_400:
        q.append({"value": 400, "clue": clue, "answer": ans, "accepted": acc, "source": src})

    # $500 tier (40 items)
    items_500 = [
        ("The obscure, historic Swedish fermented Baltic herring notorious for its overwhelming, pungent sulfuric stench, traditionally opened outdoors underwater.", "Surströmming", ["surstromming"], "Wikipedia - Fermented Seafood"),
        ("The rare, wild coffee beans collected from the feces of Asian palm civets in Indonesia that digest the coffee fruit pulp.", "Kopi Luwak", ["civet coffee"], "Wikipedia - Specialty Coffee"),
        ("The traditional Icelandic culinary dish consisting of Greenland shark that has been buried in gravel for months to ferment, then hung to dry.", "Hakarl", ["hákarl", "fermented shark"], "Wikipedia - Icelandic Cuisine"),
        ("The classical French sauce made by reducing dry red wine, shallots, beef marrow, and demi-glace, named after a famous French wine region.", "Sauce Bordelaise", ["bordelaise sauce"], "Wikipedia - Classic French Sauces"),
        ("The complex thermal process where tempered chocolate crystals are stabilized exclusively in this polymorphic form to achieve gloss and sharp snap.", "Form V Beta Crystals", ["beta crystals", "form v"], "Wikipedia - Chocolate Tempering"),
        ("The protected geographical designation for genuine balsamic vinegar of Modena produced exclusively from trebbiano grape must aged in wooden battery barrels for 12 to 25+ years.", "Aceto Balsamico Tradizionale", ["traditional balsamic vinegar"], "Wikipedia - Balsamic Vinegar"),
        ("The century-old Japanese master stock technique where a dashi or braising liquid is continuously boiled, strained, and refreshed daily for decades.", "Master Stock", ["lo mei stock", "tare mother pot"], "Wikipedia - Braising Stocks"),
        ("The ancient Mesoamerican process where dried field corn is soaked and cooked in an alkaline solution (slaked lime / calcium hydroxide) to release niacin.", "Nixtamalization", ["nixtamalisation"], "Wikipedia - Food Processing"),
        ("The traditional French preparation of the ortolan bunting bird, where the tiny songbird is fattened on millet, drowned in Armagnac, and eaten whole under a napkin.", "Ortolan Bunting", ["hortulanus"], "Wikipedia - French Gastronomic Traditions"),
        ("The French cold mother sauce derivative created by Auguste Escoffier combining mayonnaise with hard-boiled sieved egg yolks and fresh fines herbes.", "Sauce Gribiche", ["gribiche"], "Wikipedia - Cold Emulsions"),
        ("The ancient Roman fermented fish sauce factory ruins preserved on the Mediterranean coast of Spain and Morocco where tuna blood was fermented into this premium grade.", "Gari Flos", ["garum sociorum"], "Wikipedia - Classical Antiquity Cuisine"),
        ("The historic English cheese made in Gloucestershire with raw cow's milk colored with annatto, traditionally rolled down Cooper's Hill in annual races.", "Double Gloucester", ["single gloucester"], "Wikipedia - English Cheeses"),
        ("The rare culinary oil cold-pressed from the kernels of the endemic Moroccan argan tree, requiring hours of hand-cracking by Berber women.", "Argan Oil", ["argania spinosa"], "Wikipedia - Culinary Oils"),
        ("The Japanese knife blade profile where the blade is ground flat on one side and beveled on the other, allowing surgical precision cuts for sashimi.", "Single-Bevel", ["kataba", "chisel grind"], "Wikipedia - Japanese Kitchen Knives"),
        ("The specific cut of beef steak consisting of the subprimal cut from the short loin containing a T-shaped bone with the largest portion of tenderloin filet.", "Porterhouse Steak", ["porterhouse"], "Wikipedia - Beef Cuts"),
        ("The traditional Japanese dessert jelly made from agar-agar derived from red sea algae, sugar, and water, flavored with black sugar syrup (kuromitsu).", "Anmitsu", ["agar jelly", "kanten"], "Wikipedia - Wagashi"),
        ("The classical French technique of trussing a chicken or duck with butcher's twine using a needle passed through the carcass to ensure even roasting.", "Bridage", ["needle trussing"], "Wikipedia - Culinary Preparation"),
        ("The French AOC/AOP butter produced exclusively in Normandy from churned cream subjected to a 16-to-18 hour biological maturation.", "Beurre d'Isigny", ["isigny butter"], "Wikipedia - French Terroir"),
        ("The traditional Mexican cooking vessel made from a hollowed-out agave heart leaves or maguey pencas used to wrap meat during pit barbacoa.", "Pencas de Maguey", ["agave leaves"], "Wikipedia - Barbacoa"),
        ("The rare Italian pasta shape from Nuoro, Sardinia made by stretching dough into 256 hair-thin strands woven across a brass disc, 'threads of God'.", "Su Filindeu", ["filindeu"], "Wikipedia - Rare Pastas"),
        ("The fermentation mold species (Aspergillus oryzae) used in Japan to inoculate steamed rice or soybeans, foundational to sake, miso, and soy sauce.", "Koji", ["koji-kin", "aspergillus oryzae"], "Wikipedia - Koji Fermentation"),
        ("The traditional Greek and Turkish cured beef tenderloin or sirloin pressed under heavy weights, rubbed with fenugreek paste (çemen), and air-dried.", "Pastirma", ["pastourma", "basturma"], "Wikipedia - Cured Beef"),
        ("The classic French culinary preparation where raw minced lean beef or horse meat is bound with egg yolk, capers, onions, and Worcestershire sauce.", "Steak Tartare", ["tartare"], "Wikipedia - Raw Meat Dishes"),
        ("The traditional Swiss cow's milk cheese aged in mountain caves that is shaved using a circular scrap tool called a Girolle into delicate rosettes.", "Tête de Moine", ["tete de moine"], "Wikipedia - Swiss Cheeses"),
        ("The traditional Iranian dish consisting of crispy scorched golden rice formed at the bottom of the cooking pot, considered the prized portion.", "Tahdig", ["tah-deeg"], "Wikipedia - Persian Cuisine"),
        ("The complex enzymatic curing process in vanilla beans where glucovanillin is converted into aromatic vanillin through daily sun sweating and drying.", "Vanilla Curing", ["bourbon vanilla curing"], "Wikipedia - Spice Production"),
        ("The classical French mother sauce derivative of hollandaise made by adding blood orange juice and blanched orange zest.", "Sauce Maltoise", ["maltoise sauce"], "Wikipedia - Classical French Cooking"),
        ("The traditional Japanese ceremonial knife used solely by licensed Shinto imperial chefs to slice fish without ever touching the flesh with human hands.", "Hocho-shiki", ["hocho knife ceremony"], "Wikipedia - Shinto Culinary Rituals"),
        ("The Italian dessert wine produced in the Aeolian Islands of Sicily from sun-dried Malvasia delle Lipari grapes.", "Malvasia delle Lipari", ["lipari dessert wine"], "Wikipedia - Italian Viticulture"),
        ("The traditional Mexican alcoholic beverage made from the naturally fermented sap (aguamiel) of wild maguey agaves, viscous and probiotic.", "Pulque", ["octli"], "Wikipedia - Fermented Agave"),
        ("The French poultry breed from the historic province of Bresse with distinct bright blue feet and AOC status, regarded as the world's finest chicken.", "Poulet de Bresse", ["bresse chicken"], "Wikipedia - French Poultry"),
        ("The Japanese high-end dashi component made from the kelp Laminaria japonica harvested exclusively on the cold shores of Rebun Island in Hokkaido.", "Rishiri Kombu", ["kombu kelp"], "Wikipedia - Japanese Seaweed"),
        ("The ancient Spanish monastic sweet made by whipped egg yolks cooked in boiling sugar syrup formed into small golden spheres, from Ávila.", "Yemas de Santa Teresa", ["yemas de ávila"], "Wikipedia - Spanish Confectionery"),
        ("The traditional clay baking oven with three distinct heat chambers used in Morocco to slow-cook lamb méchoui underground for hours.", "Tandir Pit", ["mechoui oven"], "Wikipedia - Moroccan Culinary Arts"),
        ("The Italian sheep's milk cheese from Piacenza and Tuscany that was matured wrapped in walnut leaves or buried in ash inside sealed clay urns.", "Formaggio di Fossa", ["fossa cheese"], "Wikipedia - Cave-Aged Cheeses"),
        ("The French pastry chef who codified the five French mother sauces and created haute cuisine for European royalty, 'The Chef of Kings'.", "Marie-Antoine Careme", ["carême"], "Wikipedia - History of Haute Cuisine"),
        ("The wild mountain herb used in southern Italian cuisine (calamintha nepeta) that imparts a pungent mint-oregano flavor to artichokes alla romana.", "Mentuccia", ["nepitella"], "Wikipedia - Italian Herbs"),
        ("The traditional French cake from Brittany made with equal parts butter, sugar, and flour, folded like puff pastry to caramelize into a crisp crust.", "Kouign-Amann", ["kouign amann"], "Wikipedia - Breton Pastries"),
        ("The complex chemical process where wine aged in unsealed wooden barrels develops a protective layer of yeast film on the surface, creating oxidative flavors.", "Sous Voile", ["flor", "velum de flor"], "Wikipedia - Vin Jaune"),
        ("The traditional French sauce created for Escoffier's Peach Melba consisting of puréed fresh raspberries, confectioners' sugar, and lemon juice.", "Raspberry Coulis", ["sauce melba"], "Wikipedia - Dessert Sauces"),
    ]
    for clue, ans, acc, src in items_500:
        q.append({"value": 500, "clue": clue, "answer": ans, "accepted": acc, "source": src})

    return q

if __name__ == "__main__":
    q = get_questions()
    print("Food questions count:", len(q))
    from collections import Counter
    print("Tier counts:", Counter(x["value"] for x in q))
