"""
Animal Kingdom & Nature - 200 Curated Trivia Questions
40 items per tier: $100, $200, $300, $400, $500
"""

def get_questions():
    q = []
    # $100 tier (40 items)
    items_100 = [
        ("The largest living animal and mammal on Earth, whose heart alone can weigh as much as an automobile.", "Blue Whale", ["the blue whale", "balaenoptera musculus"], "Wikipedia - Marine Mammals"),
        ("The fastest land animal on Earth, capable of reaching speeds up to 70 mph in short bursts.", "Cheetah", ["acinonyx jubatus"], "Wikipedia - Big Cats"),
        ("The flightless bird native to Antarctica that withstands freezing temperatures by huddling in colonies.", "Emperor Penguin", ["penguin", "emperor penguins"], "Wikipedia - Seabirds"),
        ("The eucalyptus-eating marsupial native to Australia that sleeps up to 20 hours a day.", "Koala", ["koala bear"], "Wikipedia - Australian Wildlife"),
        ("The largest living bird in the world, which lays the largest eggs and can run at over 40 mph.", "Ostrich", ["common ostrich"], "Wikipedia - Ratites"),
        ("The only bird species capable of sustained backward flight and hovering in mid-air.", "Hummingbird", ["hummingbirds", "trochilidae"], "Wikipedia - Ornithology"),
        ("The black-and-white bear native to south-central China that feeds almost exclusively on bamboo.", "Giant Panda", ["panda", "ailuropoda melanoleuca"], "Wikipedia - Bears"),
        ("The apex ocean predator with distinctive black-and-white coloring, also known as the killer whale.", "Orca", ["killer whale", "orcinus orca"], "Wikipedia - Marine Apex Predators"),
        ("The tallest living land mammal, with an extraordinarily long neck and distinctive spotted coat pattern.", "Giraffe", ["giraffa"], "Wikipedia - African Mammals"),
        ("The semi-aquatic mammal native to eastern Australia with a duck-like bill, beaver-like tail, and venomous ankle spurs.", "Platypus", ["duck-billed platypus"], "Wikipedia - Monotremes"),
        ("The largest terrestrial animal alive today, equipped with a versatile trunk and large ears.", "Elephant", ["african elephant", "asian elephant"], "Wikipedia - Proboscidea"),
        ("The large marine reptile that returns to the exact beach where it was born to lay clutches of eggs in the sand.", "Sea Turtle", ["loggerhead", "green sea turtle"], "Wikipedia - Marine Reptiles"),
        ("The nocturnal mammal that is the only mammal capable of true, sustained flight.", "Bat", ["bats", "chiroptera"], "Wikipedia - Mammals"),
        ("The orange-and-black striped big cat that is the largest extant cat species, native to Asia.", "Tiger", ["panthera tigris"], "Wikipedia - Big Cats"),
        ("The ocean mollusk with eight sucker-lined tentacles, three hearts, blue blood, and remarkable camouflage skills.", "Octopus", ["octopuses", "octopi"], "Wikipedia - Cephalopods"),
        ("The massive predatory fish with rows of triangular serrated teeth made famous by the movie Jaws.", "Great White Shark", ["carcharodon carcharias"], "Wikipedia - Chondrichthyes"),
        ("The Australian pouched marsupial that hops on powerful hind legs and carries its joey in a pouch.", "Kangaroo", ["red kangaroo"], "Wikipedia - Marsupials"),
        ("The slow-moving South American arboreal mammal known for hanging upside down in trees and growing algae on its fur.", "Sloth", ["three-toed sloth", "two-toed sloth"], "Wikipedia - Xenarthra"),
        ("The collective noun for a group of lions consisting of several adult females, their cubs, and a coalition of males.", "A Pride", ["pride"], "Wikipedia - Collective Nouns"),
        ("The colorful tropical bird known for its oversized, rainbow-hued bill used for thermoregulation and reaching fruit.", "Toucan", ["ramphastidae"], "Wikipedia - Neotropical Birds"),
        ("The horned herbivore native to North America that once roamed the Great Plains in herds of millions.", "Bison", ["american bison", "buffalo"], "Wikipedia - Bovids"),
        ("The venomous arachnid with eight legs, pincers, and a segmented curved tail terminating in a venomous stinger.", "Scorpion", ["scorpions"], "Wikipedia - Arachnids"),
        ("The brightly colored amphibian of Central and South America whose toxic skin secretions were used on blowgun darts.", "Poison Dart Frog", ["poison frog", "dendrobatidae"], "Wikipedia - Amphibians"),
        ("The arctic marine mammal with two elongated ivory tusks that it uses to haul itself onto ice floes.", "Walrus", ["odobenus rosmarus"], "Wikipedia - Pinnipeds"),
        ("The predatory mammal of the Arctic with translucent hollow fur that appears white, blending into snowy ice packs.", "Polar Bear", ["ursus maritimus"], "Wikipedia - Arctic Fauna"),
        ("The aquatic bird with pink plumage derived from beta-carotene pigments in the algae and brine shrimp it consumes.", "Flamingo", ["greater flamingo"], "Wikipedia - Wading Birds"),
        ("The tree-dwelling lizard famous for its zygodactylous feet, independently mobile eyes, and ability to rapidly change color.", "Chameleon", ["chamaeleonidae"], "Wikipedia - Reptiles"),
        ("The tiny, industrious social insect that lives in complex underground colonies divided into queens, soldiers, and workers.", "Ant", ["ants", "formicidae"], "Wikipedia - Social Insects"),
        ("The prickly nocturnal mammal that curls into a tight spiny ball for defense when threatened.", "Hedgehog", ["erinaceinae"], "Wikipedia - Mammals"),
        ("The canine predator that hunts in coordinated packs with complex vocal howls and territory markings.", "Wolf", ["gray wolf", "canis lupus"], "Wikipedia - Canids"),
        ("The flightless bird native to New Zealand with nostrils at the tip of its long beak, also the national symbol of New Zealand.", "Kiwi", ["kiwi bird"], "Wikipedia - Ratites"),
        ("The massive semi-aquatic African mammal that spends days submerged in water and has deadly territorial canine tusks.", "Hippopotamus", ["hippo", "hippopotamus amphibius"], "Wikipedia - African Fauna"),
        ("The marine mammal with a single long, spiral ivory tusk projecting from its upper jaw, often called the 'unicorn of the sea'.", "Narwhal", ["monodon monoceros"], "Wikipedia - Cetaceans"),
        ("The microscopic ocean creatures whose calcium carbonate exoskeletons build up over thousands of years to create massive barrier reefs.", "Coral Polyps", ["coral", "corals"], "Wikipedia - Cnidaria"),
        ("The striped wild horse native to sub-Saharan Africa with distinctive black-and-white barcode-like camouflage stripes.", "Zebra", ["plains zebra"], "Wikipedia - Equids"),
        ("The bird of prey renowned for its incredible eyesight, soaring flight, and status as the national emblem of the United States.", "Bald Eagle", ["haliaeetus leucocephalus"], "Wikipedia - Birds of Prey"),
        ("The long-bodied aquatic mammal belonging to the weasel family known for sliding down muddy riverbanks and using tools.", "Otter", ["river otter", "sea otter"], "Wikipedia - Mustelids"),
        ("The small, bushy-tailed rodent that collects and buries nuts in the ground to prepare for winter hibernation.", "Squirrel", ["gray squirrel"], "Wikipedia - Rodents"),
        ("The armored mammal native to the Americas with a protective shell of bony plates that can curl into an armored ball.", "Armadillo", ["nine-banded armadillo"], "Wikipedia - Xenarthra"),
        ("The large marine mammal related to the manatee that grazes on underwater sea grasses in the Indo-Pacific.", "Dugong", ["dugong dugon"], "Wikipedia - Sirenia"),
    ]
    for clue, ans, acc, src in items_100:
        q.append({"value": 100, "clue": clue, "answer": ans, "accepted": acc, "source": src})

    # $200 tier (40 items)
    items_200 = [
        ("The world's largest living reptile, found in coastal mangrove swamps across Southeast Asia and northern Australia.", "Saltwater Crocodile", ["crocodylus porosus"], "Wikipedia - Crocodilians"),
        ("The micro-animal known as the 'water bear' that can survive outer space vacuum, extreme radiation, and near-absolute zero temperatures.", "Tardigrade", ["water bear", "moss piglet"], "Wikipedia - Extremophiles"),
        ("The term for egg-laying mammals, represented today only by the platypus and four species of echidna.", "Monotremes", ["monotremata"], "Wikipedia - Monotremes"),
        ("The large carnivorous monitor lizard native to Indonesian islands that hunts prey with venomous anticoagulant saliva.", "Komodo Dragon", ["varanus komodoensis"], "Wikipedia - Monitor Lizards"),
        ("The fastest diving bird and animal on the planet, reaching over 240 mph during its hunting stoop dive.", "Peregrine Falcon", ["falco peregrinus"], "Wikipedia - Birds of Prey"),
        ("The collective noun for a group of flamingos gathered together on a lake.", "A Flamboyance", ["flamboyance"], "Wikipedia - Collective Nouns"),
        ("The marine mammal that wraps itself in giant kelp forests while floating on its back to avoid drifting away while sleeping.", "Sea Otter", ["enhydra lutris"], "Wikipedia - Marine Mammals"),
        ("The deadly Australian jellyfish with cubic medusae whose potent cardiotoxic venom can kill an adult human in minutes.", "Box Jellyfish", ["sea wasp", "chironex fleckeri"], "Wikipedia - Venomous Marine Animals"),
        ("The Australian mammal with backward-facing pouches to prevent soil from entering while burrowing tunnels.", "Wombat", ["vombatidae"], "Wikipedia - Marsupials"),
        ("The bird with the longest wingspan of any living bird, measuring up to 11.5 feet (3.5 meters).", "Wandering Albatross", ["diomedea exulans", "albatross"], "Wikipedia - Seabirds"),
        ("The predatory mammal of Central and South America with a long tubular snout and a 2-foot sticky tongue for devouring termites.", "Giant Anteater", ["myrmecophaga tridactyla"], "Wikipedia - Xenarthra"),
        ("The deep-sea bioluminescent anglerfish uses this modified dorsal fin spine as a glowing fishing lure.", "Esca", ["illicium", "photophore lure"], "Wikipedia - Deep Sea Fish"),
        ("The collective noun for a group of crows gathered together.", "A Murder", ["murder of crows"], "Wikipedia - Corvids"),
        ("The large herbivorous African mammal whose horns are composed of keratin, the same protein found in human hair and fingernails.", "Rhinoceros", ["rhino"], "Wikipedia - Perissodactyla"),
        ("The flightless parrot native to New Zealand that is nocturnal, solitary, and the heaviest parrot in the world.", "Kakapo", ["kākāpō", "strigops habroptilus"], "Wikipedia - Endangered Birds"),
        ("The only known mammal completely covered in large, protective overlapping keratin scales, highly trafficked for traditional medicine.", "Pangolin", ["scaly anteater"], "Wikipedia - Pangolins"),
        ("The Australian elapid snake with the most toxic venom of any terrestrial reptile in the world.", "Inland Taipan", ["fierce snake", "oxyuranus microlepidotus"], "Wikipedia - Venomous Snakes"),
        ("The migratory North American butterfly renowned for its epic multi-generational 3,000-mile journey to Mexican fir forests.", "Monarch Butterfly", ["danaus plexippus"], "Wikipedia - Butterfly Migration"),
        ("The small, predatory deep-sea shark that bites circular, cookie-shaped plugs of flesh out of larger marine animals.", "Cookiecutter Shark", ["isistius brasiliensis"], "Wikipedia - Squaliformes"),
        ("The ape native to the rainforests of Sumatra and Borneo whose name translates from Malay as 'person of the forest'.", "Orangutan", ["pongo"], "Wikipedia - Great Apes"),
        ("The biological term for animals active primarily during twilight hours (dawn and dusk), such as deer and rabbits.", "Crepuscular", ["crepuscular animals"], "Wikipedia - Animal Behavior"),
        ("The marine crustacean with specialized club-like appendages that strike prey with the speed of a .22 caliber bullet.", "Mantis Shrimp", ["stomatopod", "peacock mantis shrimp"], "Wikipedia - Crustaceans"),
        ("The wild dog of Australia introduced thousands of years ago that is Australia's largest terrestrial predator.", "Dingo", ["canis dingo"], "Wikipedia - Australian Wildlife"),
        ("The North American ungulate that is the fastest land animal in the Western Hemisphere, capable of running 55 mph.", "Pronghorn", ["antilocapra americana", "pronghorn antelope"], "Wikipedia - North American Mammals"),
        ("The phenomenon where certain animal species, like fireflies and anglerfish, produce light through chemical reactions.", "Bioluminescence", ["bioluminescent"], "Wikipedia - Photobiology"),
        ("The African bird of prey with long legs resembling storks that hunts venomous snakes on foot by stomping them to death.", "Secretarybird", ["sagittarius serpentarius"], "Wikipedia - African Birds of Prey"),
        ("The venomous Australian cephalopod with iridescent blue rings that flash warning signals when agitated, carrying tetrodotoxin.", "Blue-Ringed Octopus", ["hapalochlaena"], "Wikipedia - Toxic Marine Life"),
        ("The Arctic cetacean known as the 'canary of the sea' due to its high-pitched vocal chirps and lack of a dorsal fin.", "Beluga Whale", ["white whale", "delphinapterus leucas"], "Wikipedia - Arctic Cetaceans"),
        ("The large South American rodent that is the largest living rodent species in the world, closely related to guinea pigs.", "Capybara", ["hydrochoerus hydrochaeris"], "Wikipedia - Rodents"),
        ("The North American salamander that retains its aquatic larval form with external feathery gills throughout adulthood.", "Axolotl", ["ambystoma mexicanum", "mexican walking fish"], "Wikipedia - Amphibians"),
        ("The collective noun for a group of owls resting together.", "A Parliament", ["parliament of owls"], "Wikipedia - Collective Nouns"),
        ("The predatory mammal that holds the Guinness World Record as the 'most fearless animal in the world', resistant to snake venom.", "Honey Badger", ["ratel", "mellivora capensis"], "Wikipedia - Mustelids"),
        ("The tiny Australian marsupial mouse-like creature whose males mate so furiously during a two-week frenzy that all males die of stress.", "Antechinus", ["brown antechinus"], "Wikipedia - Semelparity"),
        ("The large flightless bird native to the rainforests of New Guinea and northern Australia equipped with a deadly 4-inch dagger claw.", "Cassowary", ["southern cassowary", "casuarius"], "Wikipedia - Dangerous Birds"),
        ("The specialized organ found in pit vipers, boas, and pythons that allows them to detect infrared thermal radiation from prey.", "Pit Organ", ["loreal pit", "thermal pit"], "Wikipedia - Reptilian Senses"),
        ("The process by which organisms shed their outer exoskeleton or skin to accommodate biological growth, seen in reptiles and arthropods.", "Ecdysis", ["molting", "moulting"], "Wikipedia - Invertebrate Biology"),
        ("The subantarctic penguin species identifiable by its bright yellow crest feathers and red eyes, known for hopping over rocks.", "Rockhopper Penguin", ["southern rockhopper"], "Wikipedia - Penguins"),
        ("The large semi-aquatic rodent native to North America and Eurasia that alters ecosystems by felling trees to build complex dams and lodges.", "Beaver", ["castor canadensis"], "Wikipedia - Ecosystem Engineers"),
        ("The African primate of the baboon family recognizable by its striking olive-green fur and brilliantly colored red and blue muzzle.", "Mandrill", ["mandrillus sphinx"], "Wikipedia - Old World Monkeys"),
        ("The tiny Pacific crustacean that snaps its claws shut so rapidly that it creates a cavitation bubble exceeding 8,000°F.", "Pistol Shrimp", ["snapping shrimp", "alpheidae"], "Wikipedia - Marine Invertebrates"),
    ]
    for clue, ans, acc, src in items_200:
        q.append({"value": 200, "clue": clue, "answer": ans, "accepted": acc, "source": src})

    # $300 tier (40 items)
    items_300 = [
        ("The nocturnal burrowing mammal native to sub-Saharan Africa with a pig-like snout and rabbit-like ears whose name means 'earth pig' in Afrikaans.", "Aardvark", ["orycteropus afer"], "Wikipedia - Tubulidentata"),
        ("The biological term for animals whose body temperature is primarily regulated by external environmental temperatures (cold-blooded).", "Ectotherms", ["ectothermic", "poikilotherms"], "Wikipedia - Thermoregulation"),
        ("The giant cephalopod of the deep ocean whose eyes, measuring up to 10 inches across, are the largest of any living animal.", "Giant Squid", ["architeuthis dux", "colossal squid"], "Wikipedia - Deep-Sea Cephalopods"),
        ("The deep-sea shark species native to the North Atlantic that has the longest known lifespan of any vertebrate, estimated at over 400 years.", "Greenland Shark", ["somniosus microcephalus"], "Wikipedia - Longevity Records"),
        ("The predatory mammal of the Madagascan rainforest that looks like a cat but is more closely related to mongooses and civets.", "Fossa", ["cryptoprocta ferox"], "Wikipedia - Malagasy Carnivores"),
        ("The unique sensory system in fish and aquatic amphibians that detects mechanical vibrations and pressure gradients in the water.", "Lateral Line System", ["lateral line"], "Wikipedia - Ichthyology"),
        ("The deep-sea fish with dark gelatinous flesh that was voted the 'World's Ugliest Animal' due to decompression outside its deep ocean habitat.", "Blobfish", ["psychrolutes marcidus"], "Wikipedia - Deep-Sea Fauna"),
        ("The specialized organ in electric eels (composed of thousands of electrocytes) capable of discharging up to 860 volts of electricity.", "Electric Organ", ["hunter's organ", "sachs' organ"], "Wikipedia - Electrogenesis"),
        ("The defensive biological behavior where an animal pretends to be dead to deter predators, exemplified by the Virginia opossum.", "Thanatosis", ["playing possum", "apparent death"], "Wikipedia - Animal Defenses"),
        ("The flightless, nocturnal parrot of New Zealand that uses lek mating displays, booming low-frequency rumbles across valleys.", "Kakapo", ["kākāpō"], "Wikipedia - Avian Courtship"),
        ("The tiny parasitic insect order that includes wingless vectors of epidemic typhus, historically infesting soldiers' uniforms.", "Lice", ["pediculus humanus", "phthiraptera"], "Wikipedia - Medical Entomology"),
        ("The symbiotic relationship between clownfish and sea anemones where both species benefit from protection and nutrient exchange.", "Mutualism", ["symbiotic mutualism"], "Wikipedia - Ecological Interactions"),
        ("The large marine gastropod mollusk whose decorative, spiral mother-of-pearl shell contains multiple chambered gas septa for buoyancy.", "Nautilus", ["chambered nautilus"], "Wikipedia - Cephalopods"),
        ("The specialized cells in squid, cuttlefish, and octopuses that contain pigment sacs expanded by radial muscles to change skin patterns.", "Chromatophores", ["chromatophore"], "Wikipedia - Cephalopod Camouflage"),
        ("The African wild cat with extraordinarily long ears topped with black tufts, capable of leaping 10 feet into the air to catch birds.", "Caracal", ["caracal caracal"], "Wikipedia - Felidae"),
        ("The dense colonies of marine hydrozoans like the Portuguese man o' war that appear as a single animal but are colonial organisms.", "Siphonophores", ["siphonophore"], "Wikipedia - Hydrozoa"),
        ("The biological process in which an unfertilized egg develops into a viable embryo without fertilization by male sperm.", "Parthenogenesis", ["parthenogenetic reproduction"], "Wikipedia - Reproductive Biology"),
        ("The semi-aquatic carnivorous mammal native to South America that is the longest member of the weasel family, reaching 6 feet.", "Giant Otter", ["pteronura brasiliensis"], "Wikipedia - Mustelidae"),
        ("The rare phenomenon where birds migrate by using quantum mechanical entanglement in light-sensitive proteins in their eyes.", "Magnetoreception", ["cryptochromes"], "Wikipedia - Quantum Biology"),
        ("The arboreal marsupial native to eastern Australia with a feather-like tail and gliding membranes, feeding on sweet nectar and sap.", "Sugar Glider", ["petaurus breviceps"], "Wikipedia - Petauridae"),
        ("The deep-sea hydrothermal vent organism that has no digestive tract and relies on symbiotic chemosynthetic bacteria oxidizing hydrogen sulfide.", "Giant Tube Worm", ["riftia pachyptila"], "Wikipedia - Hydrothermal Vents"),
        ("The marine iguanas of this isolated archipelago are the only lizards on Earth that forage for algae in the cold ocean.", "Galapagos Islands", ["galápagos", "archipiélago de colón"], "Wikipedia - Island Endemism"),
        ("The venomous nocturnal primate native to Southeast Asia with a toxic bite produced by licking a brachial gland on its elbow.", "Slow Loris", ["nycticebus"], "Wikipedia - Strepsirrhini"),
        ("The biological rule stating that appendages and extremities of warm-blooded animals are shorter in colder climates to conserve heat.", "Allen's Rule", ["allens rule"], "Wikipedia - Ecogeographical Rules"),
        ("The biological rule stating that body size among related species increases in colder, higher-latitude climates.", "Bergmann's Rule", ["bergmanns rule"], "Wikipedia - Ecogeographical Rules"),
        ("The large flightless rail native to the South Island of New Zealand that was thought extinct for 50 years until rediscovered in 1948.", "Takahe", ["takahē", "porphyrio hochstetteri"], "Wikipedia - Lazarus Taxa"),
        ("The specialized third eyelid found in many birds, reptiles, and sharks that can sweep horizontally across the eye for protection.", "Nictitating Membrane", ["haw", "third eyelid"], "Wikipedia - Ocular Anatomy"),
        ("The African mammal related to the giraffe with zebra-like striped legs that lives in the dense rainforests of the DR Congo.", "Okapi", ["okapia johnstoni", "forest giraffe"], "Wikipedia - Giraffidae"),
        ("The sensory receptors located on the heads of sharks and rays that detect minute electrical fields emitted by the muscle contractions of prey.", "Ampullae of Lorenzini", ["ampullae"], "Wikipedia - Electroreception"),
        ("The large nocturnal flightless owl parrot native to New Zealand that is also one of the longest-living birds, surviving up to 90 years.", "Kakapo", ["kākāpō"], "Wikipedia - Parrots"),
        ("The Asian mammal with a prehensile tail and scent glands that produce a strong aroma famously compared to hot buttered popcorn.", "Binturong", ["bearcat", "arctictis binturong"], "Wikipedia - Viverridae"),
        ("The structural protein that forms the primary component of hair, feathers, claws, hooves, and horns across vertebrates.", "Keratin", ["alpha-keratin", "beta-keratin"], "Wikipedia - Biomaterials"),
        ("The bird species known to migrate the longest distance of any animal, traveling from the Arctic to Antarctica and back each year (~44,000 miles).", "Arctic Tern", ["sterna paradisaea"], "Wikipedia - Bird Migration"),
        ("The biological phenomenon where harmless organisms evolve to mimic the warning coloration or appearance of dangerous toxic models.", "Batesian Mimicry", ["batesian mimic"], "Wikipedia - Evolutionary Mimicry"),
        ("The second-largest living rodent species after the capybara, native to the wetlands and rivers of North America and Eurasia.", "Beaver", ["castor fiber", "castor canadensis"], "Wikipedia - Rodents"),
        ("The large flightless beetle that navigates at night using the polarization of moonlight and the Milky Way to roll dung balls in straight lines.", "Dung Beetle", ["scarabaeus zambesianus"], "Wikipedia - Insect Navigation"),
        ("The deep-sea cephalopod that can invert its webbed arms to display rows of fleshy, spine-like cirri, named after vampires.", "Vampire Squid", ["vampyroteuthis infernalis"], "Wikipedia - Cephalopods"),
        ("The predatory mammal of the Amazon basin with powerful jaws and a rosetted coat that has the strongest bite force relative to size among big cats.", "Jaguar", ["panthera onca"], "Wikipedia - Big Cats"),
        ("The flightless bird endemic to the isolated South Atlantic island of Inaccessible Island, the smallest extant flightless bird in the world.", "Inaccessible Island Rail", ["atlantisia rogersi"], "Wikipedia - Flightless Birds"),
        ("The structural adaptations on gecko toes consisting of millions of microscopic branched spatulae that stick via van der Waals forces.", "Setae", ["gecko setae", "spatulae"], "Wikipedia - Bio-Adhesion"),
    ]
    for clue, ans, acc, src in items_300:
        q.append({"value": 300, "clue": clue, "answer": ans, "accepted": acc, "source": src})

    # $400 tier (40 items)
    items_400 = [
        ("The endangered mammal of the northern Gulf of California that is the rarest marine mammal in the world, with fewer than 10 individuals remaining.", "Vaquita", ["vaquita porpoise", "phocoena sinus"], "Wikipedia - Critically Endangered Species"),
        ("The specialized digestive chamber in ruminants where microbial fermentation breaks down cellulose before regurgitation and chewing of cud.", "Rumen", ["reticulorumen"], "Wikipedia - Ruminant Digestion"),
        ("The order of aquatic carnivorous mammals consisting of true seals, eared seals (sea lions), and walruses.", "Pinnipeds", ["pinnipedia"], "Wikipedia - Marine Mammalogy"),
        ("The venomous, carnivorous mollusk of tropical coral reefs that uses a modified harpoon-like radula tooth to paralyze fish.", "Cone Snail", ["conus", "geography cone"], "Wikipedia - Toxic Marine Gastropods"),
        ("The unique evolutionary phenomenon where distantly related lineages independently evolve a crab-like body morphology.", "Carcinization", ["carcinisation"], "Wikipedia - Evolutionary Biology"),
        ("The marine mammal species that possesses the thickest and densest fur of any animal, with up to one million hairs per square inch.", "Sea Otter", ["enhydra lutris"], "Wikipedia - Fur Adaptations"),
        ("The small, armored deep-sea isopod that can roll into a sphere and scavenges whale falls and carrion on the ocean floor.", "Giant Isopod", ["bathynomus giganteus"], "Wikipedia - Deep-Sea Crustaceans"),
        ("The chemical compound secreted by the skunk's anal scent glands that produces its overpowering, sulfurous stench.", "Thiols", ["butyl mercaptan", "thioacetates"], "Wikipedia - Skunk Defenses"),
        ("The biological adaptation in sperm whales where a massive reservoir of waxy liquid in the forehead helps modulate buoyancy during deep dives.", "Spermaceti Organ", ["spermaceti"], "Wikipedia - Cetacean Anatomy"),
        ("The only known vertebrate that has a complete, natural three-chambered internal rotatory wheel joint in its flagellar drive motor.", "Bacterial Flagellum", ["flagellar motor"], "Wikipedia - Molecular Motors"),
        ("The African carnivore that lives in social packs where the breeding alpha female is larger and dominates males through a pseudo-penis.", "Spotted Hyena", ["crocuta crocuta", "laughing hyena"], "Wikipedia - Hyenidae"),
        ("The Australian lizard with a grotesque thorny exterior that drinks water by capillary action through microscopic skin grooves to its mouth.", "Thorny Devil", ["moloch horridus"], "Wikipedia - Desert Adaptations"),
        ("The venomous mammal native to Hispaniola that delivers neurotoxic saliva through grooved second lower incisors.", "Hispaniolan Solenodon", ["solenodon paradoxus"], "Wikipedia - Venomous Mammals"),
        ("The microscopic parasitic cnidarian that lives inside salmon muscle tissue and is the only known animal that does not possess a mitochondrial genome.", "Henneguya salminicola", ["henneguya"], "Wikipedia - Parasitic Cnidarians"),
        ("The biological rule that states two species competing for the exact same limiting resource cannot coexist at constant population values.", "Competitive Exclusion Principle", ["gause's law"], "Wikipedia - Ecological Principles"),
        ("The deep-sea bioluminescent siphonophore colony that can reach lengths of over 100 feet, longer than a blue whale.", "Praya dubia", ["giant siphonophore"], "Wikipedia - Hydrozoan Superorganisms"),
        ("The ant caste that acts as living storage vessels, swelling with liquid honeydew to feed the colony during dry seasons.", "Honeypot Ants", ["repletes"], "Wikipedia - Ant Castes"),
        ("The Australian burrowing frog that can remain dormant in an underground water-filled cocoon for up to five years during severe droughts.", "Water-Holding Frog", ["cyclorana platycephala"], "Wikipedia - Amphibian Estivation"),
        ("The order of placental mammals comprising armadillos, anteaters, and sloths, historically called Edentata.", "Xenarthra", ["xenarthrans"], "Wikipedia - Mammalian Evolution"),
        ("The unique avian adaptation where pigeons, flamingos, and male emperor penguins produce a protein-rich secretion in the esophagus to feed hatchlings.", "Crop Milk", ["pigeon milk"], "Wikipedia - Avian Physiology"),
        ("The deep-sea fish with tubular upward-pointing eyes enclosed within a completely transparent, fluid-filled dome on its head.", "Barreleye Fish", ["macropinna microstoma"], "Wikipedia - Deep Sea Adaptations"),
        ("The large extinct New Zealand flightless bird that was the primary prey of Haast's Eagle before being hunted to extinction by the Maori.", "Moa", ["dinornithiformes"], "Wikipedia - Extinct Avian Megafauna"),
        ("The Australian marsupial predator with a pouch that was the apex carnivore of Tasmania until the last captive specimen, Benjamin, died in 1936.", "Thylacine", ["tasmanian tiger", "tasmanian wolf"], "Wikipedia - Extinct Carnivores"),
        ("The biological organ in birds responsible for producing vocalizations, located at the base of the trachea rather than the larynx.", "Syrinx", ["avian syrinx"], "Wikipedia - Avian Vocalization"),
        ("The unusual reproductive mode in seahorses and pipefish where this sex carries the fertilized eggs inside a specialized brood pouch.", "Male", ["male seahorse", "father"], "Wikipedia - Syngnathidae"),
        ("The rare evolutionary phenomenon where an animal retains juvenile traits into sexually mature adulthood, as seen in the axolotl.", "Neoteny", ["paedomorphosis"], "Wikipedia - Developmental Biology"),
        ("The deep-sea shark species recognizable by its elongated flattened snout and protruding jaws that shoot forward to capture prey.", "Goblin Shark", ["mitsukurina owstoni"], "Wikipedia - Deep-Sea Lamniformes"),
        ("The flightless cormorant endemic to this isolated island chain has stunted wings and dense bones to dive for marine fish.", "Galapagos Islands", ["galapagos flightless cormorant"], "Wikipedia - Endemic Fauna"),
        ("The social insect phenomenon where sterile workers sacrifice their lives to protect the colony, explained by haplodiploid genetic relatedness.", "Kin Selection", ["hamilton's rule"], "Wikipedia - Sociobiology"),
        ("The venomous sea snail whose complex conotoxin peptide cocktails have yielded synthetic painkillers (ziconotide) hundreds of times more potent than morphine.", "Cone Snail", ["conus magus"], "Wikipedia - Marine Pharmacology"),
        ("The unique suborder of baleen whales characterized by ventral throat grooves that expand immensely during lunge feeding on krill.", "Rorquals", ["balaenopteridae"], "Wikipedia - Mysticeti"),
        ("The unique respiratory adaptation in birds where air flows continuously in a single direction through parabronchi using a system of air sacs.", "Unidirectional Airflow", ["avian respiration", "air sacs"], "Wikipedia - Avian Anatomy"),
        ("The African burrowing rodent that lives in subterranean eusocial colonies with a single breeding queen, showing extraordinary cancer resistance.", "Naked Mole-Rat", ["heterocephalus glaber"], "Wikipedia - Eusocial Mammals"),
        ("The unique organ in bats and toothed whales that focuses and projects high-frequency ultrasonic clicks used for echolocation.", "Melon", ["acoustic melon"], "Wikipedia - Echolocation"),
        ("The rare behavioral adaptation in butcherbirds and shrikes where prey items are impaled on thorns or barbed wire to store for later.", "Larder", ["impaling behavior"], "Wikipedia - Avian Predation"),
        ("The specialized claw on the second toe of many nocturnal strepsirrhine primates (like lemurs and galagos) used for fur grooming.", "Toilet-Claw", ["grooming claw"], "Wikipedia - Primate Morphology"),
        ("The deep-sea hydrothermal vent snail that incorporates iron sulfide minerals (greigite and pyrite) into its multilayered shell and foot scales.", "Scaly-Foot Snail", ["chrysomallon squamiferum", "scaly-foot gastropod"], "Wikipedia - Biomineralization"),
        ("The unique hunting mechanism in chameleon tongues involving an elastic collagen sleeve that accelerates the tongue like a catapult.", "Ballistic Projection", ["catapult mechanism"], "Wikipedia - Reptilian Mechanics"),
        ("The North American bird that can survive winter freezing temperatures by producing glycerol and glucose cryoprotectants to prevent cellular ice damage.", "Wood Frog", ["lithobates sylvaticus"], "Wikipedia - Cryobiology"),
        ("The marine polychaete worm that forms massive swarms in the South Pacific where the posterior reproductive segment (epitoke) detaches to spawn.", "Palolo Worm", ["palola viridis"], "Wikipedia - Polychaete Biology"),
    ]
    for clue, ans, acc, src in items_400:
        q.append({"value": 400, "clue": clue, "answer": ans, "accepted": acc, "source": src})

    # $500 tier (40 items)
    items_500 = [
        ("The obscure, primitive deep-sea echinoderm with a circular, disc-shaped body ringed with spines that lives exclusively on sunken wood.", "Sea Daisy", ["xyloplax", "concentricycloidea"], "Wikipedia - Echinoderm Taxonomy"),
        ("The unique cellular organelle found in the skin of cephalopods and peacock feathers that produces structural color through coherent light scattering.", "Iridophore", ["iridophores", "leucophores"], "Wikipedia - Structural Coloration"),
        ("The bizarre South American hoatzin bird is unique among all living birds for possessing this anatomical feature on its wings as a chick.", "Claws", ["wing claws", "functional claws"], "Wikipedia - Hoatzin"),
        ("The ancient lobe-finned fish thought to have gone extinct with the dinosaurs 66 million years ago until a living specimen was discovered off South Africa in 1938.", "Coelacanth", ["latimeria chalumnae"], "Wikipedia - Living Fossils"),
        ("The venomous Australian elapid snake that possesses the longest fangs relative to head size of any Australian venomous snake, the death adder.", "Death Adder", ["acanthophis"], "Wikipedia - Elapidae"),
        ("The unique deep-sea animal phylum discovered in 1995 living exclusively on the mouthparts of the Norway lobster, consisting of a single genus.", "Cycliophora", ["symbion pandora"], "Wikipedia - Animal Phyla"),
        ("The respiratory protein that uses copper rather than iron to bind oxygen, giving the blood of octopuses and horseshoe crabs its blue color.", "Hemocyanin", ["haemocyanin"], "Wikipedia - Respiratory Pigments"),
        ("The solitary deep-sea cephalopod that possesses thousands of bioluminescent photophores and can produce glowing bioluminescent mucus clouds to confuse predators.", "Vampire Squid", ["vampyroteuthis infernalis"], "Wikipedia - Deep-Sea Cephalopods"),
        ("The unique reproductive adaptation in kangaroos where a fertilized embryo halts cell division and remains in suspended development until a joey leaves the pouch.", "Embryonic Diapause", ["diapause"], "Wikipedia - Marsupial Reproduction"),
        ("The deep-sea hydrothermal vent decapod crustacean discovered in 2005 covered in dense silky setae containing chemosynthetic bacteria, nicknamed the 'yeti crab'.", "Kiwa hirsuta", ["yeti crab", "kiwa"], "Wikipedia - Decapod Crustaceans"),
        ("The structural organ in male sharks, rays, and chimaeras derived from the pelvic fins that transfers sperm during internal copulation.", "Clasper", ["myxopterygium", "pelvic claspers"], "Wikipedia - Elasmobranch Reproduction"),
        ("The marine worm belonging to the phylum Echiura that exhibits extreme environmental sex determination: larvae landing on a female become tiny parasitic dwarf males.", "Bonellia viridis", ["bonellia"], "Wikipedia - Sex Determination"),
        ("The only known spider species that is predominantly herbivorous, feeding on protein- and lipid-rich Beltian bodies of acacia plants in Central America.", "Bagheera kiplingi", ["kiplingi"], "Wikipedia - Jumping Spiders"),
        ("The primitive deep-sea worm-like mollusk lacking a shell that crawls on the ocean floor, belonging to this primitive aplacophoran class.", "Solenogastres", ["neomeniomorpha"], "Wikipedia - Basal Mollusks"),
        ("The anatomical sensory organ located in the pelvic area of male fireflies and cicadas that amplifies reproductive calls through resonant air cavities.", "Tymbal", ["timbal organ"], "Wikipedia - Bioacoustics"),
        ("The unique evolutionary structure in male anglerfish where dwarf males bite onto the female's body, fusing permanently into a parasitic sperm-producing appendage.", "Sexual Parasitism", ["parasitic males"], "Wikipedia - Anglerfish Reproduction"),
        ("The extinct flightless pigeon species endemic to the Mascarene island of Rodrigues that was closely related to the Dodo.", "Rodrigues Solitaire", ["pezophaps solitaria"], "Wikipedia - Extinct Island Columbids"),
        ("The deep-sea cnidarian that can revert its adult medusa stage back into an immature polyp colony through cellular transdifferentiation, dubbed the 'immortal jellyfish'.", "Turritopsis dohrnii", ["immortal jellyfish", "turritopsis nutricula"], "Wikipedia - Biological Immortality"),
        ("The extinct giant carnivore of South America belonging to Sparassodonta that evolved saber-teeth convergent with North American saber-toothed cats.", "Thylacosmilus", ["thylacosmilus atrox"], "Wikipedia - Convergent Evolution"),
        ("The sensory organ located in the head of birds and cetaceans containing cryptochrome-4 proteins that mediate quantum magnetoreception.", "Cryptochrome 4", ["cry4"], "Wikipedia - Quantum Magnetoreception"),
        ("The obscure marine micro-invertebrate phylum comprising worm-like organisms with a proboscis and wheel-like crown, discovered in Greenland springs in 2000.", "Micrognathozoa", ["limnognathia maerski"], "Wikipedia - Microscopic Phyla"),
        ("The unique physiological mechanism where desert camels produce specialized oval red blood cells that can swell to 240% without bursting during rapid rehydration.", "Elliptical Erythrocytes", ["oval red blood cells"], "Wikipedia - Camelid Physiology"),
        ("The primitive jawless fish that can excrete liters of fibrous defensive slime in seconds when bitten by predators, clogging the predator's gills.", "Hagfish", ["myxini", "slime eel"], "Wikipedia - Cyclostomes"),
        ("The unique behavioral phenomenon where male bowerbirds arrange colored objects by size to create forced perspective visual illusions for prospective mates.", "Forced Perspective", ["bowerbird illusion"], "Wikipedia - Sexual Selection"),
        ("The Australian burrowing crayfish species that can construct mud towers up to three feet high above waterlogged burrows.", "Engaeus", ["burrowing crayfish"], "Wikipedia - Parastacidae"),
        ("The venomous marine gastropod whose venom cocktail contains conorfamide peptides that specifically target nicotine acetylcholine receptor subtypes.", "Cone Snail", ["conus textile", "cloth of gold cone"], "Wikipedia - Venomous Mollusks"),
        ("The obscure phylum of microscopic aquatic parasites that infect the kidneys of benthic cephalopods, consisting of fewer than 30 total cells.", "Dicyemida", ["rhombozoa"], "Wikipedia - Basal Invertebrates"),
        ("The specialized organ in male platypuses on the calcaneus that delivers a venomous cocktail of defensin-like peptides during the breeding season.", "Crural Gland", ["calcaneal spur", "crural system"], "Wikipedia - Platypus Venom"),
        ("The extinct giant bird of prey that lived in the South Island of New Zealand with an 8-foot wingspan, capable of killing humans and moa.", "Haast's Eagle", ["hieraaetus moorei"], "Wikipedia - Apex Predators"),
        ("The microscopic, bottle-shaped freshwater and marine invertebrates belonging to this phylum that glide along surfaces using cilia.", "Gastrotricha", ["gastrotrichs", "hairybacks"], "Wikipedia - Invertebrate Phyla"),
        ("The primitive nocturnal mammal of the Caribbean that possesses a unique ball-and-socket joint in its snout allowing extreme snout flexibility.", "Solenodon", ["solenodontidae"], "Wikipedia - Eulipotyphla"),
        ("The deep-sea bioluminescent polychaete worm that drops glowing green bioluminescent 'bombs' from its gills to distract predators.", "Swima bombiviridis", ["green bomber worm"], "Wikipedia - Annelida"),
        ("The unique avian adaptation where emperor penguin plumage uses a gradient of micro-air pockets trapped against down feathers to achieve thermal resistance exceeding winter coats.", "Plumule Insulation", ["down feather air-trapping"], "Wikipedia - Antarctic Thermoregulation"),
        ("The strange Australian marsupial mole that spends its entire life swimming through sand dunes without eyes or external ears.", "Notoryctes", ["marsupial mole", "itjaritjari"], "Wikipedia - Notoryctidae"),
        ("The cellular mechanism where bioluminescent marine bacteria synchronize their light emission only after reaching a threshold population density.", "Quorum Sensing", ["autoinduction"], "Wikipedia - Bacterial Communication"),
        ("The deep-sea stalked barnacle whose long fleshy peduncle attaches to pelagic debris, historically believed in medieval Europe to hatch into geese.", "Goose Barnacle", ["lepadoidea", "lepas anatifera"], "Wikipedia - Cirripedia"),
        ("The specialized cells in the electric organ of the torpedo ray that stack like batteries in series to generate up to 220 volts.", "Electrocytes", ["electroplaques"], "Wikipedia - Electric Fish"),
        ("The extinct monotreme fossil discovered in Lightning Ridge, Australia that had opalized jaws dating to the Cretaceous period.", "Steropodon", ["steropodon galmani"], "Wikipedia - Early Monotremes"),
        ("The marine flatworm species that engages in 'penis fencing', a hermaphroditic battle where two worms duel to inseminate the other while avoiding being impregnated.", "Pseudobiceros", ["marine polyclads"], "Wikipedia - Hermaphroditic Mating"),
        ("The subterranean blind amphibian endemic to karst caves in the Dinaric Alps that can survive without food for up to ten years, historically called a 'baby dragon'.", "Olm", ["proteus anguinus"], "Wikipedia - Proteidae"),
    ]
    for clue, ans, acc, src in items_500:
        q.append({"value": 500, "clue": clue, "answer": ans, "accepted": acc, "source": src})

    return q

if __name__ == "__main__":
    q = get_questions()
    print("Nature questions count:", len(q))
    from collections import Counter
    print("Tier counts:", Counter(x["value"] for x in q))
