"""
Film & IMDb Legends - 200 Curated Trivia Questions
40 items per tier: $100, $200, $300, $400, $500
"""

def get_questions():
    q = []
    # $100 tier (40 items)
    items_100 = [
        ("He played Tony Stark across 10 films in the Marvel Cinematic Universe starting in 2008.", "Robert Downey Jr", ["robert downey jr.", "rdj", "robert downey"], "IMDb - Marvel Cinematic Universe"),
        ("In this 1994 Disney animated classic, Simba learns 'Hakuna Matata' from Timon and Pumbaa.", "The Lion King", ["lion king"], "IMDb - Walt Disney Animation"),
        ("The young wizard with a lightning bolt scar who attends Hogwarts School of Witchcraft and Wizardry.", "Harry Potter", ["potter"], "IMDb - Harry Potter Franchise"),
        ("The dinosaur theme park film directed by Steven Spielberg in 1993 based on Michael Crichton's novel.", "Jurassic Park", ["jurassic world"], "IMDb - Steven Spielberg"),
        ("The friendly red-and-blue superhero whose alter ego is high school student Peter Parker.", "Spider-Man", ["spiderman", "peter parker"], "IMDb - Marvel / Sony"),
        ("Dorothy follows the yellow brick road to the Emerald City in this 1939 musical classic.", "The Wizard of Oz", ["wizard of oz"], "IMDb - Classic Hollywood"),
        ("The 1995 Pixar film about Woody and Buzz Lightyear, the first feature-length computer-animated film.", "Toy Story", ["toy story 1"], "IMDb - Pixar Animation"),
        ("The clownfish father Marlin searches across the ocean for his missing son in this 2003 Pixar hit.", "Finding Nemo", ["nemo"], "IMDb - Pixar Animation"),
        ("Queen Elsa sings 'Let It Go' after fleeing her kingdom of Arendelle in this 2013 Disney smash hit.", "Frozen", ["disney frozen"], "IMDb - Walt Disney Animation"),
        ("Marty McFly travels back to 1955 in a plutonium-powered DeLorean in this 1985 time-travel adventure.", "Back to the Future", ["bttf"], "IMDb - 1980s Classics"),
        ("Christian Bale played this billionaire vigilante of Gotham City in Christopher Nolan's acclaimed trilogy.", "Batman", ["the dark knight", "bruce wayne"], "IMDb - Christopher Nolan"),
        ("Frodo Baggins must journey to Mount Doom to destroy the One Ring in this fantasy trilogy.", "The Lord of the Rings", ["lord of the rings", "lotr", "fellowship of the ring"], "IMDb - Peter Jackson"),
        ("The green ogre who lives in a swamp and journeys to rescue Princess Fiona with a talking Donkey.", "Shrek", ["shrek 1"], "IMDb - DreamWorks Animation"),
        ("Eight-year-old Kevin McCallister defends his Chicago home from the Wet Bandits in this 1990 comedy.", "Home Alone", ["home alone 1"], "IMDb - Holiday Classics"),
        ("Johnny Depp stars as the eccentric pirate Captain Jack Sparrow in this blockbuster franchise.", "Pirates of the Caribbean", ["pirates of the carribean", "curse of the black pearl"], "IMDb - Disney"),
        ("Tom Hanks won Best Actor for playing an Alabama man who witnesses historic events in this 1994 drama.", "Forrest Gump", ["gump"], "IMDb - Academy Award Winners"),
        ("Keanu Reeves plays Thomas Anderson, aka Neo, who chooses between the red pill and blue pill.", "The Matrix", ["matrix"], "IMDb - Wachowski Sisters"),
        ("Who you gonna call? Bill Murray, Dan Aykroyd, and Harold Ramis hunt spectral entities in NYC.", "Ghostbusters", ["ghost busters"], "IMDb - 1980s Sci-Fi"),
        ("Steven Spielberg's 1982 blockbuster about a gentle stranded alien who befriends young Elliott.", "E.T.", ["et", "e.t. the extra-terrestrial", "the extra terrestrial"], "IMDb - Blockbusters"),
        ("A giant great white shark terrorizes the summer resort town of Amity Island in this 1975 thriller.", "Jaws", ["jaws 1"], "IMDb - Blockbusters"),
        ("Leonardo DiCaprio leads a team of thieves who infiltrate people's subconscious dreams.", "Inception", ["inception 2010"], "IMDb - Christopher Nolan"),
        ("The 2009 sci-fi epic set on the moon Pandora that became the highest-grossing film of all time.", "Avatar", ["james cameron avatar"], "IMDb - Box Office Records"),
        ("Gene Wilder and later Johnny Depp portrayed this eccentric chocolatier who gave out five Golden Tickets.", "Willy Wonka", ["wonka"], "IMDb - Warner Bros"),
        ("Margot Robbie and Ryan Gosling starred in this 2023 Greta Gerwig comedy based on the iconic Mattel doll.", "Barbie", ["barbie movie"], "IMDb - 2023 Box Office"),
        ("Cillian Murphy starred as the father of the atomic bomb in this 2023 Christopher Nolan Oscar-winner.", "Oppenheimer", ["j. robert oppenheimer"], "IMDb - Academy Awards"),
        ("Harrison Ford wields a bullwhip and wears a fedora as this globe-trotting archaeologist.", "Indiana Jones", ["indy", "raiders of the lost ark"], "IMDb - Lucasfilm"),
        ("Arnold Schwarzenegger plays a cybernetic assassin sent back in time from 2029 to 1984.", "The Terminator", ["terminator", "t-800"], "IMDb - James Cameron"),
        ("Tom Cruise plays naval aviator Pete 'Maverick' Mitchell in this high-flying action franchise.", "Top Gun", ["top gun maverick"], "IMDb - Action Cinema"),
        ("Carl Fredricksen ties thousands of helium balloons to his house to fly to Paradise Falls in this Pixar film.", "Up", ["pixar up"], "IMDb - Pixar Animation"),
        ("Bob Parr and Helen Parr lead a family of undercover superheroes in this 2004 Brad Bird animated film.", "The Incredibles", ["incredibles"], "IMDb - Pixar Animation"),
        ("The fictional high-tech African nation ruled by King T'Challa in Marvel's Black Panther.", "Wakanda", ["kingdom of wakanda"], "IMDb - Marvel Studios"),
        ("The 2019 Marvel climax where the Avengers assemble against Thanos to reverse the Blip.", "Avengers: Endgame", ["avengers endgame", "endgame"], "IMDb - Marvel Cinematic Universe"),
        ("Robin Williams voiced the Genie who grants three wishes to a street urchin in this 1992 Disney classic.", "Aladdin", ["disney aladdin"], "IMDb - Disney Renaissance"),
        ("Belle offers herself as a captive to a cursed prince in this 1991 Disney classic.", "Beauty and the Beast", ["beauty & the beast"], "IMDb - Disney Renaissance"),
        ("Will Smith and Tommy Lee Jones wear black suits and use neuralyzers to monitor extraterrestrial life on Earth.", "Men in Black", ["mib"], "IMDb - Sony Pictures"),
        ("Sylvester Stallone wrote and starred as an underdog Philadelphia boxer who gets a title shot against Apollo Creed.", "Rocky", ["rocky balboa"], "IMDb - Sports Cinema"),
        ("Russell Crowe plays Roman general Maximus Decimus Meridius forced into the arena in this 2000 epic.", "Gladiator", ["gladiator 2000"], "IMDb - Ridley Scott"),
        ("Tom Hanks survives on an uninhabited South Pacific island with a Wilson volleyball as his companion.", "Cast Away", ["castaway"], "IMDb - Robert Zemeckis"),
        ("Mike Myers voiced this secret agent from the 1960s who battles Dr. Evil.", "Austin Powers", ["powers"], "IMDb - Comedy Cinema"),
        ("Viggo Mortensen played this noble ranger who ascends the throne of Gondor in Lord of the Rings.", "Aragorn", ["strider", "king elessar"], "IMDb - Peter Jackson"),
    ]
    for clue, ans, acc, src in items_100:
        q.append({"value": 100, "clue": clue, "answer": ans, "accepted": acc, "source": src})

    # $200 tier (40 items)
    items_200 = [
        ("Marlon Brando starred as Don Vito Corleone in this 1972 Francis Ford Coppola masterpiece.", "The Godfather", ["godfather", "godfather part i"], "IMDb - Top 250 Chart"),
        ("John Travolta and Samuel L. Jackson star as hitmen Vincent Vega and Jules Winnfield in this Tarantino film.", "Pulp Fiction", ["pulp fiction 1994"], "IMDb - Quentin Tarantino"),
        ("Ray Liotta, Robert De Niro, and Joe Pesci star in Martin Scorsese's 1990 mob masterpiece.", "Goodfellas", ["good fellas"], "IMDb - Martin Scorsese"),
        ("Anthony Hopkins won an Oscar for just 16 minutes of screen time playing cannibal psychiatrist Dr. Hannibal Lecter.", "The Silence of the Lambs", ["silence of the lambs"], "IMDb - Oscar Records"),
        ("Edward Norton and Brad Pitt establish an underground bare-knuckle brawl club in this David Fincher film.", "Fight Club", ["fight club 1999"], "IMDb - Cult Cinema"),
        ("Hayao Miyazaki directed this 2001 Studio Ghibli masterpiece about Chihiro wandering into a bathhouse for spirits.", "Spirited Away", ["sen to chihiro no kamikakushi"], "IMDb - Anime Masterpieces"),
        ("Humphrey Bogart tells Ingrid Bergman 'Here's looking at you, kid' in Rick's Café Américain.", "Casablanca", ["casablanca 1942"], "IMDb - Classic Cinema"),
        ("Alfred Hitchcock's 1960 horror classic featuring the infamous Bates Motel shower murder scene.", "Psycho", ["psycho 1960"], "IMDb - Alfred Hitchcock"),
        ("Liam Neeson portrays a German industrialist who saves over a thousand Jewish refugees during the Holocaust.", "Schindler's List", ["schindlers list"], "IMDb - Steven Spielberg"),
        ("Matthew McConaughey travels through a wormhole near Saturn in search of a habitable world in this Nolan sci-fi epic.", "Interstellar", ["interstellar 2014"], "IMDb - Christopher Nolan"),
        ("Jack Nicholson ax-chops through a bathroom door yelling 'Here's Johnny!' in this Stanley Kubrick horror film.", "The Shining", ["shining"], "IMDb - Stanley Kubrick"),
        ("Jim Carrey plays an insurance salesman who discovers his entire life is a live reality TV show broadcast 24/7.", "The Truman Show", ["truman show"], "IMDb - Comedy Drama"),
        ("A young Mexican boy named Miguel journeys to the Land of the Dead in this vibrant 2017 Pixar film.", "Coco", ["pixar coco"], "IMDb - Pixar Animation"),
        ("A rat named Remy dreams of becoming a master chef in Paris in this 2007 Brad Bird animated comedy.", "Ratatouille", ["pixar ratatouille"], "IMDb - Pixar Animation"),
        ("Sulley and Mike Wazowski collect children's screams to power their city in this 2001 Pixar film.", "Monsters, Inc.", ["monsters inc"], "IMDb - Pixar Animation"),
        ("A lone waste-collecting robot left on a deserted Earth falls in love with sleek probe EVE in this 2008 Pixar film.", "WALL-E", ["walle"], "IMDb - Pixar Animation"),
        ("Harrison Ford plays Rick Deckard, a blade runner who hunts synthetic humans called replicants in 2019 Los Angeles.", "Blade Runner", ["blade runner 1982"], "IMDb - Ridley Scott"),
        ("Stanley Kubrick's 1968 sci-fi masterpiece featuring the sentient supercomputer HAL 9000.", "2001: A Space Odyssey", ["2001 a space odyssey", "space odyssey"], "IMDb - Sci-Fi Classics"),
        ("Robert De Niro plays alienated veteran Travis Bickle driving through gritty 1970s New York City.", "Taxi Driver", ["taxi driver 1976"], "IMDb - Martin Scorsese"),
        ("Francis Ford Coppola's 1979 Vietnam War epic starring Marlon Brando as the rogue Colonel Walter E. Kurtz.", "Apocalypse Now", ["apocalypse now redux"], "IMDb - War Cinema"),
        ("Sigourney Weaver plays warrant officer Ellen Ripley battling an aggressive extraterrestrial aboard the Nostromo.", "Alien", ["alien 1979"], "IMDb - Ridley Scott"),
        ("Bruce Willis plays NYPD cop John McClane battling German terrorists inside Nakatomi Plaza on Christmas Eve.", "Die Hard", ["die hard 1"], "IMDb - Action Cinema"),
        ("J.K. Simmons plays an abusive jazz conservatory instructor pushing young drummer Miles Teller to the limit.", "Whiplash", ["whiplash 2014"], "IMDb - Independent Cinema"),
        ("Tom Hardy and Charlize Theron race across the post-apocalyptic wasteland in George Miller's 2015 action masterwork.", "Mad Max: Fury Road", ["fury road", "mad max"], "IMDb - George Miller"),
        ("Jamie Foxx plays a freed slave teaming up with German bounty hunter Dr. King Schultz in this 2012 Western.", "Django Unchained", ["django"], "IMDb - Quentin Tarantino"),
        ("Wes Anderson's pastel-hued 2014 comedy starring Ralph Fiennes as concierge Gustave H. in the Republic of Zubrowka.", "The Grand Budapest Hotel", ["grand budapest hotel"], "IMDb - Wes Anderson"),
        ("Javier Bardem portrays the psychopathic hitman Anton Chigurh who kills victims with a pneumatic cattle gun.", "No Country for Old Men", ["no country"], "IMDb - Coen Brothers"),
        ("Daniel Day-Lewis won Best Actor for playing ruthless oil prospector Daniel Plainview in this Paul Thomas Anderson epic.", "There Will Be Blood", ["there will be blood 2007"], "IMDb - Paul Thomas Anderson"),
        ("Jim Carrey and Kate Winslet undergo a medical procedure to erase memories of each other in this 2004 drama.", "Eternal Sunshine of the Spotless Mind", ["eternal sunshine"], "IMDb - Michel Gondry"),
        ("Guillermo del Toro directed this 2006 dark fantasy set in Francoist Spain about young Ofelia and a mysterious labyrinth.", "Pan's Labyrinth", ["el laberinto del fauno"], "IMDb - Guillermo del Toro"),
        ("Bong Joon-ho's 2019 black comedy about the poor Kim family infiltrating the wealthy Park household.", "Parasite", ["gisaengchung"], "IMDb - Academy Awards"),
        ("Brad Pitt and Morgan Freeman hunt a serial killer who uses the seven deadly sins as his motif in this 1995 thriller.", "Seven", ["se7en"], "IMDb - David Fincher"),
        ("Jeff Bridges stars as bowling-loving slacker 'The Dude' Jeffrey Lebowski in this Coen brothers cult comedy.", "The Big Lebowski", ["big lebowski"], "IMDb - Cult Cinema"),
        ("Frances McDormand won Best Actress as pregnant Minnesota police chief Marge Gunderson in this 1996 crime drama.", "Fargo", ["fargo 1996"], "IMDb - Coen Brothers"),
        ("Audrey Tautou stars as a whimsical Paris waitress who decides to orchestrate acts of kindness for strangers.", "Amélie", ["amelie", "le fabuleux destin d'amelie poulain"], "IMDb - French Cinema"),
        ("Emma Stone and Ryan Gosling sing and dance across Los Angeles in this 2016 Damien Chazelle musical.", "La La Land", ["lalaland"], "IMDb - Modern Musicals"),
        ("Rami Malek won Best Actor for portraying legendary Queen frontman Freddie Mercury in this 2018 biopic.", "Bohemian Rhapsody", ["bohemian rhapsody movie"], "IMDb - Music Biopics"),
        ("Sam Mendes filmed this 2019 WWI trench warfare epic to appear as one continuous, unbroken two-hour tracking shot.", "1917", ["1917 movie"], "IMDb - Cinematography"),
        ("Timothée Chalamet plays Paul Atreides battling for control of the desert planet Arrakis in Denis Villeneuve's epic.", "Dune", ["dune part one", "dune 2021"], "IMDb - Sci-Fi Epics"),
        ("Natalie Portman won Best Actress for playing an obsessed ballerina descending into madness in Darren Aronofsky's thriller.", "Black Swan", ["black swan 2010"], "IMDb - Psychological Thrillers"),
    ]
    for clue, ans, acc, src in items_200:
        q.append({"value": 200, "clue": clue, "answer": ans, "accepted": acc, "source": src})

    # $300 tier (40 items)
    items_300 = [
        ("The dying word of newspaper magnate Charles Foster Kane that reporter Jerry Thompson attempts to decipher.", "Rosebud", ["rosebud sled"], "IMDb - Classic Hollywood"),
        ("James Stewart plays an acrophobic ex-detective hired to follow Kim Novak in this Hitchcock masterpiece.", "Vertigo", ["vertigo 1958"], "IMDb - Alfred Hitchcock"),
        ("Henry Fonda plays Juror #8, the sole dissenter who argues for reasonable doubt in a murder trial.", "12 Angry Men", ["twelve angry men"], "IMDb - Top 250"),
        ("Gloria Swanson plays faded silent film star Norma Desmond who declares 'I am big! It's the pictures that got small!'", "Sunset Boulevard", ["sunset blvd"], "IMDb - Film Noir"),
        ("Marilyn Monroe, Tony Curtis, and Jack Lemmon star in this 1959 Billy Wilder cross-dressing comedy classic.", "Some Like It Hot", ["some like it hot 1959"], "IMDb - Classic Comedy"),
        ("James Stewart watches his Greenwich Village neighbors through a telephoto lens from a wheelchair in this 1954 thriller.", "Rear Window", ["rear window 1954"], "IMDb - Alfred Hitchcock"),
        ("Gene Kelly dances with an umbrella in a downpour in this joyful 1952 Hollywood musical.", "Singin' in the Rain", ["singing in the rain"], "IMDb - Golden Age Musicals"),
        ("Peter O'Toole made his star-making breakthrough as a British officer leading the Arab Revolt in David Lean's 1962 epic.", "Lawrence of Arabia", ["t.e. lawrence"], "IMDb - David Lean"),
        ("Alec Guinness stars as British Colonel Nicholson who oversees the construction of a railway bridge in Burma for his captors.", "The Bridge on the River Kwai", ["bridge on the river kwai"], "IMDb - War Epics"),
        ("Marlon Brando delivers the iconic 'I coulda had class. I coulda been a contender' speech as Terry Malloy in this 1954 drama.", "On the Waterfront", ["on the waterfront 1954"], "IMDb - Elia Kazan"),
        ("Jack Nicholson plays Randle McMurphy, who rebels against the tyrannical Nurse Ratched in an Oregon psychiatric hospital.", "One Flew Over the Cuckoo's Nest", ["cuckoo's nest"], "IMDb - 1970s Cinema"),
        ("Jack Nicholson plays private eye J.J. Gittes unraveling a corrupt Los Angeles water conspiracy in this 1974 Roman Polanski noir.", "Chinatown", ["chinatown 1974"], "IMDb - Neo-Noir"),
        ("A medieval knight plays chess against the Personification of Death on a rocky Swedish beach in this Ingmar Bergman classic.", "The Seventh Seal", ["det sjunde inseglet"], "IMDb - European Cinema"),
        ("Vittorio De Sica directed this 1948 Italian Neorealist drama about an impoverished father whose livelihood is stolen.", "Bicycle Thieves", ["ladri di biciclette", "the bicycle thief"], "IMDb - Italian Neorealism"),
        ("Akira Kurosawa's 1950 drama where four witnesses present contradictory accounts of the same forest murder.", "Rashomon", ["rashōmon"], "IMDb - Japanese Cinema"),
        ("Akira Kurosawa's 1954 epic where a poor farming village hires masterless samurai to defend against marauding bandits.", "Seven Samurai", ["shichinin no samurai"], "IMDb - Akira Kurosawa"),
        ("Giuseppe Tornatore's sentimental 1988 Italian ode to childhood movie-going and projectionist Alfredo.", "Cinema Paradiso", ["nuovo cinema paradiso"], "IMDb - Foreign Cinema"),
        ("Fernando Meirelles directed this frenetic 2002 crime epic chronicling youth gangs in a notorious Rio de Janeiro favela.", "City of God", ["cidade de deus"], "IMDb - International Cinema"),
        ("Roberto Benigni won Best Actor and Best Foreign Film for this 1997 comedy-drama set in a Nazi concentration camp.", "Life is Beautiful", ["la vita è bella"], "IMDb - Academy Awards"),
        ("F. Murray Abraham won Best Actor as jealous court composer Antonio Salieri envious of Mozart's divine talent in this 1984 film.", "Amadeus", ["amadeus 1984"], "IMDb - Milos Forman"),
        ("R. Lee Ermey gave an unforgettable performance as tyrannical drill instructor Gunnery Sergeant Hartman in this Kubrick film.", "Full Metal Jacket", ["fmj"], "IMDb - Stanley Kubrick"),
        ("Malcolm McDowell plays the ultraviolent Beethoven-loving delinquent Alex DeLarge in this 1971 Kubrick adaptation.", "A Clockwork Orange", ["clockwork orange"], "IMDb - Stanley Kubrick"),
        ("Robert De Niro, Christopher Walken, and John Cazale play Pennsylvania steelworkers traumatized by Russian roulette in Vietnam.", "The Deer Hunter", ["deer hunter"], "IMDb - Michael Cimino"),
        ("Charlie Sheen and Willem Dafoe star in Oliver Stone's visceral 1986 Vietnam War drama based on Stone's own combat tours.", "Platoon", ["platoon 1986"], "IMDb - War Drama"),
        ("Mel Gibson shouted 'Freedom!' as Scottish warrior William Wallace leading rebellions against King Edward I in this 1995 epic.", "Braveheart", ["braveheart 1995"], "IMDb - 1990s Epics"),
        ("Steven Spielberg's harrowing 1998 depiction of the D-Day Omaha Beach invasion starring Tom Hanks as Captain Miller.", "Saving Private Ryan", ["private ryan"], "IMDb - World War II"),
        ("Martin Scorsese finally won Best Director for this 2006 Boston mob thriller starring Leonardo DiCaprio and Matt Damon.", "The Departed", ["the departed 2006"], "IMDb - Martin Scorsese"),
        ("Al Pacino and Robert De Niro share a legendary, tense diner conversation scene in Michael Mann's 1995 heist masterpiece.", "Heat", ["heat 1995"], "IMDb - Michael Mann"),
        ("Guy Pearce plays an amnesiac with anterograde memory loss using polaroids and tattoos to find his wife's killer in this Nolan film.", "Memento", ["memento 2000"], "IMDb - Christopher Nolan"),
        ("Choi Min-sik wields a claw hammer through an unbroken hallway fight scene after 15 years of mysterious imprisonment in this thriller.", "Oldboy", ["oldboy 2003"], "IMDb - Korean Cinema"),
        ("Florian Henckel von Donnersmarck's 2006 drama about a Stasi officer bugging an East Berlin playwright and becoming touched by his life.", "The Lives of Others", ["das leben der anderen"], "IMDb - German Cinema"),
        ("Adrien Brody became the youngest Best Actor winner at age 29 for portraying Polish-Jewish musician Władysław Szpilman.", "The Pianist", ["the pianist 2002"], "IMDb - Roman Polanski"),
        ("Darren Aronofsky's harrowing 2000 addiction drama starring Ellen Burstyn, Jared Leto, and Jennifer Connelly.", "Requiem for a Dream", ["requiem for a dream 2000"], "IMDb - Cult Cinema"),
        ("Ewan McGregor stars as heroin addict Mark Renton in Danny Boyle's 1996 adaptation of Irvine Welsh's Edinburgh novel.", "Trainspotting", ["trainspotting 1996"], "IMDb - British Cinema"),
        ("Bill Murray and Scarlett Johansson form a poignant bond in a Tokyo luxury hotel in Sofia Coppola's 2003 drama.", "Lost in Translation", ["lost in translation 2003"], "IMDb - Independent Cinema"),
        ("Joaquin Phoenix falls deeply in love with an artificial intelligence operating system named Samantha in this Spike Jonze film.", "Her", ["her 2013"], "IMDb - Spike Jonze"),
        ("Amy Adams plays a linguist tasked with deciphering circular extraterrestrial logograms in Denis Villeneuve's 2016 sci-fi drama.", "Arrival", ["arrival 2016"], "IMDb - Denis Villeneuve"),
        ("Ryan Gosling stars as replicant blade runner Officer K uncovering a long-buried secret in this 2017 sci-fi sequel.", "Blade Runner 2049", ["bladerunner 2049"], "IMDb - Denis Villeneuve"),
        ("Michelle Yeoh travels across surreal alternate universes with hot dog fingers in this 2022 Daniels multiverse comedy-drama.", "Everything Everywhere All at Once", ["eeaoo"], "IMDb - Academy Awards"),
        ("Clint Eastwood directed and starred as William Munny, an aging outlaw taking one last bounty job in this 1992 revisionist Western.", "Unforgiven", ["unforgiven 1992"], "IMDb - Clint Eastwood"),
    ]
    for clue, ans, acc, src in items_300:
        q.append({"value": 300, "clue": clue, "answer": ans, "accepted": acc, "source": src})

    # $400 tier (40 items)
    items_400 = [
        ("The director of 1994's The Shawshank Redemption and The Green Mile who adapted multiple Stephen King works.", "Frank Darabont", ["darabont"], "IMDb - Directors"),
        ("The first movie to win the newly created Academy Award for Best Animated Feature in 2001.", "Shrek", ["dreamworks shrek"], "IMDb - Oscar History"),
        ("The Italian composer who wrote the iconic whistling and choral scores for Sergio Leone's Dollars Trilogy.", "Ennio Morricone", ["morricone"], "IMDb - Film Composers"),
        ("The legendary cinema pioneer who holds the all-time record for most Oscar wins with 22 competitive Academy Awards.", "Walt Disney", ["disney"], "IMDb - Oscar Records"),
        ("The actress who holds the record for the most Academy Awards for Best Actress, winning four times between 1933 and 1981.", "Katharine Hepburn", ["hepburn"], "IMDb - Oscar Records"),
        ("The British actor who is the only person to win the Academy Award for Best Actor three times (for My Left Foot, Blood, and Lincoln).", "Daniel Day-Lewis", ["day-lewis", "day lewis"], "IMDb - Oscar Records"),
        ("The actor who is the most nominated male performer in Oscar history with 12 total nominations.", "Jack Nicholson", ["nicholson"], "IMDb - Oscar Records"),
        ("The actress who holds the record for the most Oscar acting nominations in history with an astounding 21 nominations.", "Meryl Streep", ["streep"], "IMDb - Oscar Records"),
        ("In 2009, she became the first woman in history to win the Academy Award for Best Director for The Hurt Locker.", "Kathryn Bigelow", ["bigelow"], "IMDb - Oscar History"),
        ("The Chinese-born director who became the second woman to win Best Director for 2020's Nomadland.", "Chloé Zhao", ["zhao"], "IMDb - Oscar History"),
        ("The New Zealand filmmaker who won Best Director for 2021's The Power of the Dog, thirty years after The Piano.", "Jane Campion", ["campion"], "IMDb - Oscar History"),
        ("Fritz Lang's visionary 1927 German science-fiction masterpiece set in a dystopian futuristic city with robot Maria.", "Metropolis", ["metropolis 1927"], "IMDb - Silent Cinema"),
        ("Robert Wiene's 1920 horror film with painted jagged sets that stands as the definitive masterpiece of German Expressionism.", "The Cabinet of Dr. Caligari", ["dr caligari", "das cabinet des dr caligari"], "IMDb - German Expressionism"),
        ("Sergei Eisenstein's 1925 Soviet silent film famous for pioneering montage theory during the Odessa Steps massacre.", "Battleship Potemkin", ["bronenosets potemkin"], "IMDb - Film Theory"),
        ("Federico Fellini's 1963 semi-autobiographical masterpiece about a director suffering from creative block named Guido Anselmi.", "8½", ["8 1/2", "otto e mezzo"], "IMDb - Italian Cinema"),
        ("François Truffaut's 1959 semi-autobiographical debut about troubled Parisian youth Antoine Doinel that launched the French New Wave.", "The 400 Blows", ["les quatre cents coups"], "IMDb - French New Wave"),
        ("Jean-Luc Godard's revolutionary 1960 debut starring Jean-Paul Belmondo that pioneered innovative jump cuts.", "Breathless", ["à bout de souffle"], "IMDb - French New Wave"),
        ("Michelangelo Antonioni's 1966 mod London mystery thriller where a fashion photographer unwittingly captures a murder on film.", "Blow-Up", ["blowup"], "IMDb - European Cinema"),
        ("Andrei Tarkovsky's 1979 contemplative sci-fi masterpiece about an expedition into a mysterious hazardous area called 'The Zone'.", "Stalker", ["tarkovsky stalker"], "IMDb - Soviet Cinema"),
        ("Ingmar Bergman's 1966 psychological study about an actress who has stopped speaking and the nurse who cares for her.", "Persona", ["persona 1966"], "IMDb - Ingmar Bergman"),
        ("Yasujirō Ozu's 1953 Japanese masterpiece chronicling an elderly couple visiting their busy, indifferent adult children.", "Tokyo Story", ["tōkyō monogatari"], "IMDb - Japanese Cinema"),
        ("Werner Herzog's manic 1982 adventure where an opera-loving rubber baron attempts to haul a 320-ton steamship over a steep hill.", "Fitzcarraldo", ["fitzcarraldo 1982"], "IMDb - German Cinema"),
        ("Wim Wenders' 1987 poetic fantasy about invisible, benevolent angels listening to the thoughts of divided West Berlin citizens.", "Wings of Desire", ["der himmel über berlin"], "IMDb - German Cinema"),
        ("Pedro Almodóvar won the Best Original Screenplay Oscar for this 2002 Spanish drama about two men bonding over comatose women.", "Talk to Her", ["hable con ella"], "IMDb - Spanish Cinema"),
        ("Krzysztof Kieślowski's 1993–1994 film trilogy based on the political ideals of the French Republic: Blue, White, and Red.", "Three Colors Trilogy", ["three colors", "trois couleurs"], "IMDb - Polish Cinema"),
        ("Abbas Kiarostami won the Palme d'Or at Cannes for this 1997 Iranian film about a man driving around Tehran seeking an assistant to bury him.", "Taste of Cherry", ["ta'm-e gilās"], "IMDb - Iranian Cinema"),
        ("Wong Kar-wai's lush 2000 Hong Kong romantic drama starring Tony Leung and Maggie Cheung as neighbors who discover their spouses' affair.", "In the Mood for Love", ["fa yeung nin wah"], "IMDb - Hong Kong Cinema"),
        ("Satyajit Ray's celebrated 1955 debut film depicting rural Bengali life that forms the first installment of The Apu Trilogy.", "Pather Panchali", ["song of the little road"], "IMDb - Indian Cinema"),
        ("Asghar Farhadi's 2011 Iranian domestic and legal masterpiece that became the first Iranian film to win the Foreign Language Oscar.", "A Separation", ["jodái-e náder az simin"], "IMDb - International Cinema"),
        ("Alfonso Cuarón's intimate black-and-white 2018 semi-autobiographical drama depicting the life of a Mixtec live-in housekeeper in Mexico City.", "Roma", ["roma 2018"], "IMDb - Mexican Cinema"),
        ("Alejandro González Iñárritu won back-to-back Best Director Oscars for Birdman in 2014 and this Leonardo DiCaprio survival epic in 2015.", "The Revenant", ["revenant"], "IMDb - Oscar Records"),
        ("Ryusuke Hamaguchi directed this 3-hour 2021 Japanese drama based on a Haruki Murakami short story centered around a red Saab 900.", "Drive My Car", ["doraibu mai kā"], "IMDb - Japanese Cinema"),
        ("Jonathan Glazer's devastating 2023 Holocaust film focusing on Auschwitz commandant Rudolf Höss living idyllically next to the extermination camp.", "The Zone of Interest", ["zone of interest"], "IMDb - Contemporary Cinema"),
        ("The legendary cinematographer who received 14 Academy Award nominations before finally winning his first Oscar for Blade Runner 2049.", "Roger Deakins", ["deakins"], "IMDb - Cinematography"),
        ("The cinematographer known as the 'Prince of Darkness' for his revolutionary low-key, shadowy lighting in The Godfather and Manhattan.", "Gordon Willis", ["willis"], "IMDb - Cinematography"),
        ("The cinematographer who pioneered innovative deep-focus techniques, ceilings, and wide-angle lenses in Orson Welles's Citizen Kane.", "Gregg Toland", ["toland"], "IMDb - Cinematography"),
        ("Michael Powell and Emeric Pressburger's breathtaking 1948 Technicolor ballet tragedy starring real-life ballerina Moira Shearer.", "The Red Shoes", ["red shoes 1948"], "IMDb - British Cinema"),
        ("Carl Theodor Dreyer's 1928 silent masterpiece renowned for its extreme close-ups of Falconetti's emotional courtroom trial.", "The Passion of Joan of Arc", ["la passion de jeanne d'arc"], "IMDb - Silent Cinema"),
        ("Alain Resnais's surreal 1961 French Left Bank enigma set in a lavish European grand hotel where characters dispute past meetings.", "Last Year at Marienbad", ["l'année dernière à marienbad"], "IMDb - French Cinema"),
        ("Chris Marker's 1962 French post-nuclear sci-fi short film told almost entirely through a series of still black-and-white photographs.", "La Jetée", ["la jetee"], "IMDb - Short Cinema"),
    ]
    for clue, ans, acc, src in items_400:
        q.append({"value": 400, "clue": clue, "answer": ans, "accepted": acc, "source": src})

    # $500 tier (40 items)
    items_500 = [
        ("The only three films in history to sweep the 'Big Five' Academy Awards (Picture, Director, Actor, Actress, Screenplay).", "It Happened One Night, One Flew Over the Cuckoo's Nest, and The Silence of the Lambs", ["the big five winners", "silence of the lambs, cuckoo's nest, it happened one night"], "IMDb - Oscar Trivia"),
        ("The 1927 silent aerial combat drama that was the very first film to win the Academy Award for Best Picture.", "Wings", ["wings 1927"], "IMDb - Oscar History"),
        ("F.W. Murnau's 1927 lyrical silent masterpiece subtitled 'A Song of Two Humans' that won Unique and Artistic Picture at the 1st Oscars.", "Sunrise", ["sunrise a song of two humans"], "IMDb - 1st Academy Awards"),
        ("The gritty 1969 John Schlesinger drama starring Dustin Hoffman and Jon Voight that remains the only X-rated film to win Best Picture.", "Midnight Cowboy", ["midnight cowboy 1969"], "IMDb - Oscar Records"),
        ("The stock audio sound effect of a man screaming that has been inserted as an inside joke into over 400 films since 1951.", "Wilhelm Scream", ["the wilhelm scream"], "IMDb - Sound Design"),
        ("The Danish avant-garde film movement launched in 1995 by Lars von Trier and Thomas Vinterberg with a strict 'Vow of Chastity'.", "Dogme 95", ["dogma 95"], "IMDb - Film Movements"),
        ("Dziga Vertov's 1929 Soviet constructivist documentary showing urban life in Moscow and Kyiv without narrative titles or actors.", "Man with a Movie Camera", ["chelovek s kino-apparatom"], "IMDb - Sight & Sound Greatest"),
        ("F.W. Murnau's unauthorized 1922 German expressionist adaptation of Bram Stoker's Dracula starring Max Schreck as Count Orlok.", "Nosferatu", ["nosferatu eine symphonie des grauens"], "IMDb - Silent Horror"),
        ("Luis Buñuel and Salvador Dalí collaborated on this 1929 surrealist short film famous for slicing open an eyeball with a straight razor.", "Un Chien Andalou", ["an andalusian dog"], "IMDb - Surrealist Cinema"),
        ("Maya Deren and Alexander Hammid's influential 1943 14-minute American experimental film featuring recurring keys and knives.", "Meshes of the Afternoon", ["meshes of the afternoon 1943"], "IMDb - Avant-Garde Film"),
        ("Jacques Tati built a massive, exorbitantly expensive replica of modern Paris nicknamed 'Tativille' for this 70mm 1967 comedy.", "Playtime", ["play time"], "IMDb - French Cinema"),
        ("Chantal Akerman's 1975 3-hour feminist masterwork depicting a Brussels widow's daily chores that topped the 2022 Sight & Sound decennial poll.", "Jeanne Dielman", ["jeanne dielman 23 quai du commerce"], "IMDb - Sight & Sound Poll"),
        ("The Senegalese writer-director widely revered as the 'Father of African Cinema' who directed the 1966 landmark Black Girl.", "Ousmane Sembène", ["sembene"], "IMDb - African Cinema"),
        ("Djibril Diop Mambéty's 1973 Senegalese road movie masterpiece following young motorcyclist Mory and student Anta trying to reach Paris.", "Touki Bouki", ["touki bouki 1973"], "IMDb - World Cinema"),
        ("Apichatpong Weerasethakul's 2010 Thai spiritual fantasy that became the first Thai film to win the Palme d'Or at Cannes.", "Uncle Boonmee Who Can Recall His Past Lives", ["uncle boonmee"], "IMDb - Cannes Film Festival"),
        ("Edward Yang's 2000 Taiwanese family epic centered on the Jian family across generations in modern Taipei.", "Yi Yi", ["yi yi: a one and a two", "a one and a two"], "IMDb - Taiwanese New Wave"),
        ("Hou Hsiao-hsien's 1989 historical masterwork depicting the 228 Incident in Taiwan that won the Golden Lion at Venice.", "A City of Sadness", ["beiqing chengshi"], "IMDb - Taiwanese Cinema"),
        ("Béla Tarr's 1994 monochrome, apocalyptic 7-hour adaptation of László Krasznahorkai's novel depicting a decaying Hungarian farming collective.", "Sátántangó", ["satantango"], "IMDb - Slow Cinema"),
        ("Abbas Kiarostami's 1990 docufiction masterpiece about real-life cinephile Hossain Sabzian who impersonated director Mohsen Makhmalbaf.", "Close-Up", ["namay-e nazdik"], "IMDb - Iranian Cinema"),
        ("Jafar Panahi secretly shot this 2015 docufiction film inside a yellow cab while banned from filmmaking by the Iranian government.", "Taxi", ["taxi tehran"], "IMDb - Berlin Film Festival"),
        ("Claire Denis's hypnotic 1999 masterpiece set in Djibouti following French Foreign Legionnaires, inspired by Melville's Billy Budd.", "Beau Travail", ["beau travail 1999"], "IMDb - Sight & Sound Top 10"),
        ("Céline Sciamma's 2019 French historical romance set on an isolated Breton island between an aristocratic bride and her portrait painter.", "Portrait of a Lady on Fire", ["portrait de la jeune fille en feu"], "IMDb - Queer Cinema"),
        ("Lucrecia Martel's 2017 historical adaptation depicting an 18th-century Spanish colonial officer stagnating in a remote South American backwater.", "Zama", ["zama 2017"], "IMDb - Latin American Cinema"),
        ("Kelly Reichardt's 2019 contemplative frontier drama about two travelers who steal milk from the region's lone dairy cow to bake oily cakes.", "First Cow", ["first cow 2019"], "IMDb - American Independent"),
        ("Todd Field's 2022 psychological drama starring Cate Blanchett as a world-renowned, disgraced conductor of the Berlin Philharmonic.", "Tár", ["tar"], "IMDb - 2020s Cinema"),
        ("Jonathan Glazer's 2013 sci-fi film where Scarlett Johansson plays an alien harvesting solitary Scottish men across Glasgow.", "Under the Skin", ["under the skin 2013"], "IMDb - British Sci-Fi"),
        ("The Japanese director of Ugetsu and The Life of Oharu, celebrated alongside Kurosawa and Ozu as a golden age titan.", "Kenji Mizoguchi", ["mizoguchi"], "IMDb - Japanese Cinema"),
        ("The 1928 French silent surrealist landmark directed by Germaine Dulac and written by Antonin Artaud, considered the first surrealist film.", "The Seashell and the Clergyman", ["la coquille et le clergyman"], "IMDb - Avant-Garde"),
        ("The 1902 French silent trick film by Georges Méliès showing an umbrella-carrying astronomers' capsule shot into the Moon's eye.", "A Trip to the Moon", ["le voyage dans la lune"], "IMDb - Early Cinema"),
        ("The 1973 Victor Erice Spanish masterpiece about a young girl obsessed with James Whale's Frankenstein in rural Castile.", "The Spirit of the Beehive", ["el espíritu de la colmena"], "IMDb - Spanish Cinema"),
        ("The Soviet-Armenian director whose visually ravishing 1969 film The Color of Pomegranates chronicled the life of poet Sayat-Nova.", "Sergei Parajanov", ["parajanov"], "IMDb - Soviet Cinema"),
        ("The revolutionary 1970 French crime drama directed by Jean-Pierre Melville starring Alain Delon, Bourvil, and Gian Maria Volonté.", "Le Cercle Rouge", ["the red circle"], "IMDb - French Neo-Noir"),
        ("Jean Renoir's 1939 satirical masterpiece about French aristocratic hypocrisy on a weekend hunting estate, often ranked in all-time top tens.", "The Rules of the Game", ["la règle du jeu"], "IMDb - French Cinema"),
        ("Max Ophüls's 1953 tragic masterpiece starring Danielle Darrieux tracing the pawned journey of a set of heart-shaped diamond earrings.", "The Earrings of Madame de...", ["madame de..."], "IMDb - French Cinema"),
        ("The Mexican cinematographer who won three consecutive Oscars for Gravity, Birdman, and The Revenant.", "Emmanuel Lubezki", ["chivo lubezki", "lubezki"], "IMDb - Cinematography"),
        ("The Hungarian animator and experimental filmmaker who directed the mind-bending 1981 animated epic Son of the White Mare.", "Marcell Jankovics", ["jankovics"], "IMDb - Animation History"),
        ("The 1966 Gillo Pontecorvo battle film shot in gritty documentary newsreel style about the FLN insurgency against French paratroopers.", "The Battle of Algiers", ["la battaglia di algeri"], "IMDb - Political Cinema"),
        ("The French filmmaker whose 9-and-a-half-hour 1985 documentary Shoah recorded Holocaust survivor and perpetrator testimonies without archive footage.", "Claude Lanzmann", ["lanzmann"], "IMDb - Documentary Cinema"),
        ("The 1924 silent western epic directed by John Ford about the construction of the First Transcontinental Railroad.", "The Iron Horse", ["iron horse"], "IMDb - John Ford"),
        ("The 1985 Elem Klimov Soviet war masterpiece depicting the Nazi scorched-earth devastation of Belorussian villages through a boy's eyes.", "Come and See", ["idi i smotri"], "IMDb - Soviet Cinema"),
    ]
    for clue, ans, acc, src in items_500:
        q.append({"value": 500, "clue": clue, "answer": ans, "accepted": acc, "source": src})

    return q

if __name__ == "__main__":
    q = get_questions()
    print("Movies questions count:", len(q))
    from collections import Counter
    print("Tier counts:", Counter(x["value"] for x in q))
