"""
Sports & Champions - 200 Curated Trivia Questions
40 items per tier: $100, $200, $300, $400, $500
"""

def get_questions():
    q = []
    # $100 tier (40 items)
    items_100 = [
        ("The international men's soccer championship held every four years by FIFA, won by Argentina in 2022.", "FIFA World Cup", ["world cup", "fifa world cup"], "Wikipedia - Association Football"),
        ("The legendary Jamaican sprinter who holds world records in both the 100-meter and 200-meter sprints.", "Usain Bolt", ["bolt"], "Wikipedia - Olympic Athletics"),
        ("The American swimmer who holds the all-time record for Olympic gold medals with an astonishing 23 golds.", "Michael Phelps", ["phelps"], "Wikipedia - Olympic Swimming"),
        ("The sport where athletes attempt to shoot an orange ball through an elevated 10-foot hoop.", "Basketball", ["nba basketball"], "Wikipedia - Basketball"),
        ("The annual championship game of the National Football League (NFL).", "Super Bowl", ["the super bowl"], "Wikipedia - American Football"),
        ("The prestigious English grass-court tennis tournament played annually in London since 1877.", "Wimbledon", ["the championships wimbledon"], "Wikipedia - Grand Slam Tennis"),
        ("The Chicago Bulls legend who led his team to six NBA championships in the 1990s and wore jersey #23.", "Michael Jordan", ["jordan", "air jordan"], "Wikipedia - NBA Legends"),
        ("The four-year international multi-sport event featuring summer and winter editions inspired by ancient Greece.", "Olympic Games", ["the olympics", "olympic games"], "Wikipedia - Olympic Games"),
        ("The Brazilian soccer legend known as 'O Rei' (The King) who won three FIFA World Cup trophies (1958, 1962, 1970).", "Pele", ["pelé", "edson arantes do nascimento"], "Wikipedia - Football Legends"),
        ("The legendary heavyweight boxing champion who famously claimed to 'float like a butterfly, sting like a bee'.", "Muhammad Ali", ["ali", "cassius clay"], "Wikipedia - Boxing Legends"),
        ("The sport played on ice where two teams use sticks to shoot a vulcanized rubber puck into a net.", "Ice Hockey", ["hockey"], "Wikipedia - Ice Hockey"),
        ("The Argentine soccer icon who led his national team to glory in the 2022 World Cup and won 8 Ballon d'Or awards.", "Lionel Messi", ["messi"], "Wikipedia - Modern Football"),
        ("The Portuguese soccer star who has scored over 850 career goals and won five UEFA Champions League titles.", "Cristiano Ronaldo", ["cr7", "ronaldo"], "Wikipedia - Modern Football"),
        ("The New York Yankees icon nicknamed 'The Great Bambino' and 'The Sultan of Swat' who hit 714 career home runs.", "Babe Ruth", ["ruth", "george herman ruth"], "Wikipedia - Baseball Legends"),
        ("The NFL quarterback who won seven Super Bowl titles across 23 seasons with the Patriots and Buccaneers.", "Tom Brady", ["brady"], "Wikipedia - NFL History"),
        ("The exact length of an official marathon race in miles and yards (or miles to one decimal place).", "26.2 miles", ["26.2", "26 miles 385 yards", "42.195 km", "42.2 km"], "Wikipedia - Marathon"),
        ("The Canadian ice hockey superstar nicknamed 'The Great One' who holds the NHL scoring records.", "Wayne Gretzky", ["gretzky"], "Wikipedia - NHL Records"),
        ("The legendary golf icon who has won 15 major championships and 82 PGA Tour events, wearing red on Sundays.", "Tiger Woods", ["woods", "eldrick tont woods"], "Wikipedia - Golf Legends"),
        ("The American tennis champion who won 23 Grand Slam singles titles in the Open Era, sister to Venus.", "Serena Williams", ["serena"], "Wikipedia - Women's Tennis"),
        ("The traditional Japanese martial art and national sport where heavy wrestlers clash inside a circular ring (dohyo).", "Sumo", ["sumo wrestling"], "Wikipedia - Sumo"),
        ("The game played on a green felt table with six pockets, 15 colored balls, and a white cue ball.", "Billiards", ["pool", "eight-ball", "8-ball"], "Wikipedia - Cue Sports"),
        ("The sport where two or four players use lightweight stringed rackets to hit a feathered shuttlecock over a net.", "Badminton", ["shuttlecock"], "Wikipedia - Racquet Sports"),
        ("The French annual bicycle race that is the most prestigious cycling Grand Tour in the world, founded in 1903.", "Tour de France", ["le tour"], "Wikipedia - Cycling"),
        ("The iconic stadium in Rio de Janeiro that hosted the 1950 and 2014 FIFA World Cup finals.", "Maracana Stadium", ["estádio do maracanã", "maracana"], "Wikipedia - Football Stadiums"),
        ("The Los Angeles Lakers star who surpassed Kareem Abdul-Jabbar in 2023 to become the NBA's all-time scoring leader.", "LeBron James", ["king james", "lebron"], "Wikipedia - NBA Records"),
        ("The prestigious golf tournament played every April at Augusta National Golf Club, awarding a green jacket.", "The Masters", ["masters tournament"], "Wikipedia - Men's Major Golf"),
        ("The winter sport where participants glide downhill on two narrow planks of wood, metal, or plastic attached to boots.", "Skiing", ["alpine skiing"], "Wikipedia - Winter Sports"),
        ("The number of players on the field for one team during a regulation baseball game.", "9 players", ["9", "nine"], "Wikipedia - Baseball Rules"),
        ("The maximum score possible in a single ten-pin bowling game by rolling 12 consecutive strikes.", "300", ["perfect game 300", "300 points"], "Wikipedia - Ten-pin Bowling"),
        ("The international cricket trophy contested in a Test series between England and Australia, held in a tiny urn.", "The Ashes", ["ashes urn"], "Wikipedia - Test Cricket"),
        ("The famous car race held annually on Memorial Day weekend at the Indianapolis Motor Speedway.", "Indianapolis 500", ["indy 500"], "Wikipedia - Auto Racing"),
        ("The combat sport involving throws, joint locks, and chokeholds founded in Japan in 1882 by Jigoro Kano.", "Judo", ["kodokan judo"], "Wikipedia - Martial Arts"),
        ("The legendary New York Yankees shortstop known as 'The Captain' who wore jersey #2 and won 5 World Series rings.", "Derek Jeter", ["jeter"], "Wikipedia - Baseball"),
        ("The term for a score of one stroke under par on a single golf hole.", "Birdie", ["a birdie"], "Wikipedia - Golf Scoring"),
        ("The term for a score of two strokes under par on a single golf hole.", "Eagle", ["an eagle"], "Wikipedia - Golf Scoring"),
        ("The sport played on horseback where two teams use long mallets to drive a wooden ball into goals.", "Polo", ["horse polo"], "Wikipedia - Equestrian Sports"),
        ("The NBA player who scored 100 points in a single game for the Philadelphia Warriors on March 2, 1962.", "Wilt Chamberlain", ["chamberlain"], "Wikipedia - NBA Records"),
        ("The four Grand Slam tennis tournaments are the Australian Open, French Open, Wimbledon, and this final one in New York.", "US Open", ["u.s. open"], "Wikipedia - Grand Slam"),
        ("The British Formula 1 racing driver who holds the record for most career Grand Prix wins and 7 World Championships alongside Schumacher.", "Lewis Hamilton", ["hamilton", "sir lewis hamilton"], "Wikipedia - Formula One"),
        ("The track and field jumping event where athletes use a long, flexible fiberglass pole to clear an elevated bar.", "Pole Vault", ["pole vaulting"], "Wikipedia - Athletics"),
    ]
    for clue, ans, acc, src in items_100:
        q.append({"value": 100, "clue": clue, "answer": ans, "accepted": acc, "source": src})

    # $200 tier (40 items)
    items_200 = [
        ("The Swiss tennis maestro who won 20 Grand Slam singles titles and spent 310 weeks at World No. 1.", "Roger Federer", ["federer"], "Wikipedia - Men's Tennis"),
        ("The Spanish 'King of Clay' who has won a record 14 French Open men's singles titles at Roland Garros.", "Rafael Nadal", ["nadal"], "Wikipedia - Men's Tennis"),
        ("The Serbian tennis legend who holds the all-time men's record for most Grand Slam singles titles with 24.", "Novak Djokovic", ["djokovic"], "Wikipedia - Men's Tennis"),
        ("The Boston Celtics center who won 11 NBA championships in 13 seasons, the most in North American sports history.", "Bill Russell", ["russell"], "Wikipedia - NBA Legends"),
        ("The Argentine soccer icon famous for his 'Hand of God' goal and the 'Goal of the Century' against England in 1986.", "Diego Maradona", ["maradona"], "Wikipedia - FIFA World Cup"),
        ("The American gymnast who has won 37 combined Olympic and World Championship medals, the most decorated gymnast in history.", "Simone Biles", ["biles"], "Wikipedia - Artistic Gymnastics"),
        ("The German Formula One driving titan who won seven World Drivers' Championships, including five consecutive with Ferrari.", "Michael Schumacher", ["schumacher"], "Wikipedia - Formula 1"),
        ("In baseball, achieving a single, a double, a triple, and a home run all in the same game is called hitting for this.", "The Cycle", ["cycle", "hit for the cycle"], "Wikipedia - Baseball Records"),
        ("The Russian mixed martial artist who retired undefeated at 29-0 as UFC Lightweight Champion.", "Khabib Nurmagomedov", ["khabib"], "Wikipedia - Mixed Martial Arts"),
        ("The legendary golf champion known as 'The Golden Bear' who holds the record for most men's major championships with 18.", "Jack Nicklaus", ["nicklaus"], "Wikipedia - Golf History"),
        ("The African-American track star who won four gold medals at the 1936 Berlin Olympics, defying Adolf Hitler's Aryan supremacy propaganda.", "Jesse Owens", ["owens"], "Wikipedia - Olympic History"),
        ("The baseball pioneer who broke Major League Baseball's color barrier when he started at first base for the Brooklyn Dodgers in 1947.", "Jackie Robinson", ["robinson", "jack roosevelt robinson"], "Wikipedia - Baseball History"),
        ("The Olympic track and field event combining ten diverse events over two days, crowning the 'World's Greatest Athlete'.", "Decathlon", ["men's decathlon"], "Wikipedia - Athletics"),
        ("The Olympic women's track and field event consisting of seven combined running, jumping, and throwing disciplines.", "Heptathlon", ["women's heptathlon"], "Wikipedia - Athletics"),
        ("The iconic boxing match on October 30, 1974 in Zaire where Muhammad Ali defeated George Foreman using the rope-a-dope technique.", "The Rumble in the Jungle", ["rumble in the jungle"], "Wikipedia - Boxing History"),
        ("The second heavyweight title fight between Muhammad Ali and Joe Frazier in the Philippines in October 1975.", "Thrilla in Manila", ["thrilla in manila"], "Wikipedia - Boxing History"),
        ("The legendary Los Angeles Lakers shooting guard who scored 81 points in a game against Toronto in 2006, nicknamed 'The Black Mamba'.", "Kobe Bryant", ["bryant", "mamba"], "Wikipedia - NBA Legends"),
        ("The team with the most FIFA World Cup titles in men's tournament history, lifting the trophy five times.", "Brazil", ["brazilian national team", "seleção"], "Wikipedia - FIFA World Cup"),
        ("The English football club based at Old Trafford that won a historic treble (Premier League, FA Cup, Champions League) in 1999 under Alex Ferguson.", "Manchester United", ["man united", "man utd"], "Wikipedia - English Football"),
        ("The prestigious international yachting trophy first contested in 1851, the oldest international trophy in world sport.", "America's Cup", ["americas cup"], "Wikipedia - Sailing"),
        ("The legendary Romanian gymnast who became the first gymnast in Olympic history to score a perfect 10.0 at the 1976 Montreal Games.", "Nadia Comaneci", ["comaneci", "nadia comăneci"], "Wikipedia - Olympic Gymnastics"),
        ("The distance in yards from the pitcher's rubber to home plate in Major League Baseball.", "60 feet 6 inches", ["60'6\"", "60.5 feet"], "Wikipedia - Baseball Diamond"),
        ("The iconic Brazilian Formula One world champion who tragically died in a crash at the 1994 San Marino Grand Prix at Imola.", "Ayrton Senna", ["senna"], "Wikipedia - Formula 1"),
        ("The only NFL team to achieve a completely undefeated, untied season and win the Super Bowl, going 17-0 in 1972.", "Miami Dolphins", ["1972 dolphins"], "Wikipedia - NFL History"),
        ("The Japanese two-way MLB superstar who excels as both an elite starting pitcher and a designated hitter, signing with the Dodgers in 2023.", "Shohei Ohtani", ["ohtani"], "Wikipedia - MLB"),
        ("The prestigious cycle race through Italy that awards the overall general classification leader a distinctive pink jersey (Maglia Rosa).", "Giro d'Italia", ["giro d italia", "the giro"], "Wikipedia - Cycling Grand Tours"),
        ("The legendary San Francisco 49ers wide receiver who holds NFL career records for receptions (1,549), receiving yards (22,895), and touchdowns (208).", "Jerry Rice", ["rice"], "Wikipedia - NFL Records"),
        ("The combat sport where fighters wear gloves and can use punches, kicks, knees, and elbows, originating in Thailand as the 'Art of Eight Limbs'.", "Muay Thai", ["thai boxing"], "Wikipedia - Martial Arts"),
        ("The American swimmer who won seven gold medals and broke seven world records at the 1972 Munich Olympic Games.", "Mark Spitz", ["spitz"], "Wikipedia - Olympic Swimming"),
        ("The Scottish football manager who managed Manchester United from 1986 to 2013, winning 38 trophies including 13 Premier League titles.", "Sir Alex Ferguson", ["ferguson"], "Wikipedia - Premier League"),
        ("The traditional rowing race between the Oxford University Boat Club and Cambridge University Boat Club held annually on the River Thames.", "The Boat Race", ["oxford-cambridge boat race"], "Wikipedia - Rowing"),
        ("The iconic heavyweight boxer who bit off a portion of Evander Holyfield's ear during their 1997 WBA championship rematch.", "Mike Tyson", ["tyson", "iron mike"], "Wikipedia - Boxing"),
        ("The legendary Boston Bruins defenseman who revolutionized offensive play from the blue line in the 1970s and won two Stanley Cups.", "Bobby Orr", ["orr"], "Wikipedia - NHL Legends"),
        ("The legendary Czech distance runner who won the 5,000m, 10,000m, and the Marathon at the 1952 Helsinki Olympics, nicknamed the 'Czech Locomotive'.", "Emil Zatopek", ["zátopek"], "Wikipedia - Olympic Distance Running"),
        ("The prestigious steeplechase horse race held annually at Aintree Racecourse near Liverpool, England, famous for Becher's Brook.", "The Grand National", ["grand national"], "Wikipedia - Horse Racing"),
        ("The number of minutes in a standard regulation international soccer match, divided into two 45-minute halves.", "90 minutes", ["90"], "Wikipedia - Association Football"),
        ("The legendary West Indian cricket batsman who scored an unbeaten 400 runs in a single Test innings against England in 2004.", "Brian Lara", ["lara"], "Wikipedia - Cricket Records"),
        ("The team that has won the most UEFA Champions League / European Cup titles in history with 15 trophies.", "Real Madrid", ["real madrid cf", "los blancos"], "Wikipedia - UEFA Champions League"),
        ("The American tennis prodigy who won her first Grand Slam singles title at age 17 at the 1999 US Open.", "Serena Williams", ["serena"], "Wikipedia - Grand Slam Champions"),
        ("The sport where teams of four players slide heavy granite stones across a sheet of ice toward a target circular area known as the 'house'.", "Curling", ["curling on ice"], "Wikipedia - Winter Olympic Sports"),
    ]
    for clue, ans, acc, src in items_200:
        q.append({"value": 200, "clue": clue, "answer": ans, "accepted": acc, "source": src})

    # $300 tier (40 items)
    items_300 = [
        ("The Australian cricket batsman universally regarded as the greatest test batsman of all time, with an astonishing career batting average of 99.94.", "Sir Donald Bradman", ["don bradman", "the don"], "Wikipedia - Cricket Legends"),
        ("The Finnish middle- and long-distance runner known as the 'Flying Finn' who won nine Olympic gold medals in the 1920s.", "Paavo Nurmi", ["nurmi"], "Wikipedia - Olympic Distance Running"),
        ("The baseball pitcher who threw a perfect game in Game 5 of the 1956 World Series for the New York Yankees, the only one in World Series history.", "Don Larsen", ["larsen"], "Wikipedia - World Series Records"),
        ("The legendary Boston Red Sox left fielder who batted .406 in 1941, the last Major League Baseball player to hit over .400 in a season.", "Ted Williams", ["the splendid splinter"], "Wikipedia - MLB Records"),
        ("The Belgian cycling legend nicknamed 'The Cannibal' who won the Tour de France five times and the Giro d'Italia five times.", "Eddy Merckx", ["merckx"], "Wikipedia - Cycling Legends"),
        ("The 1980 US men's ice hockey team's stunning 4-3 Olympic victory over the heavily favored four-time defending gold medalist Soviet team.", "Miracle on Ice", ["the miracle on ice"], "Wikipedia - Winter Olympic History"),
        ("The American track star who set a long jump world record of 8.90 meters (29 feet 2.5 inches) at the 1968 Mexico City Olympics that stood for 23 years.", "Bob Beamon", ["beamon"], "Wikipedia - Long Jump Records"),
        ("The historic football play in 1972 where Pittsburgh Steelers fullback Franco Harris caught a ricocheted pass inches off the turf to beat the Raiders.", "Immaculate Reception", ["the immaculate reception"], "Wikipedia - NFL History"),
        ("The French soccer legend who scored twice with headers in the 1998 World Cup final and famously headbutted Marco Materazzi in the 2006 final.", "Zinedine Zidane", ["zidane", "zizou"], "Wikipedia - Football World Cup"),
        ("The Portuguese soccer club based in Lisbon that won back-to-back European Cups in 1961 and 1962 led by Mozambican superstar Eusébio.", "Benfica", ["s.l. benfica"], "Wikipedia - European Cup History"),
        ("The Italian motor racing circuit near Milan known as the 'Temple of Speed', home to the Formula 1 Italian Grand Prix since 1922.", "Monza", ["autodromo nazionale monza"], "Wikipedia - Formula One Circuits"),
        ("The only horse in British racing history to win the Triple Crown (2,000 Guineas, Derby, and St Leger) in the post-WWII era, achieving it in 1970.", "Nijinsky", ["nijinsky ii"], "Wikipedia - British Triple Crown"),
        ("The American Olympic high jumper who revolutionized the sport in 1968 by jumping backward headfirst over the bar.", "Dick Fosbury", ["fosbury", "the fosbury flop"], "Wikipedia - High Jump"),
        ("The legendary American distance runner from Oregon who inspired the modern running boom before his tragic death in a car accident at age 24 in 1975.", "Steve Prefontaine", ["prefontaine", "pre"], "Wikipedia - Track and Field"),
        ("The first thoroughbred racehorse to win the American Triple Crown in 25 years when he won the 1973 Belmont Stakes by a staggering 31 lengths.", "Secretariat", ["big red"], "Wikipedia - American Thoroughbred Racing"),
        ("The Dutch football philosopher and legend who pioneered 'Total Football' (Totaalvoetbal) with Ajax and Barcelona in the 1970s.", "Johan Cruyff", ["cruyff", "johan cruijff"], "Wikipedia - Total Football"),
        ("The English soccer forward who won the 1966 World Cup with England and survived the 1958 Munich air disaster with Manchester United.", "Bobby Charlton", ["sir bobby charlton"], "Wikipedia - English Football"),
        ("The Soviet gymnastics superstar who won four gold medals at the 1972 Munich Olympics, captivating the world with her backflip on the balance beam.", "Olga Korbut", ["korbut"], "Wikipedia - Olympic Gymnastics"),
        ("The iconic 1980 Wimbledon men's singles final where Björn Borg defeated John McEnroe featured a legendary 18-16 fourth-set tiebreaker.", "Borg-McEnroe Final", ["borg vs mcenroe 1980"], "Wikipedia - Wimbledon History"),
        ("The African-American tennis pioneer who became the first Black player selected to the US Davis Cup team and the first Black man to win Wimbledon.", "Arthur Ashe", ["ashe"], "Wikipedia - Tennis History"),
        ("The English cricket captain who orchestrated the controversial 'Bodyline' fast-leg-theory bowling tactics against Australia in the 1932–33 Ashes.", "Douglas Jardine", ["jardine"], "Wikipedia - Bodyline Series"),
        ("The American sprinter who set the 100-meter and 200-meter world records at the 1988 Seoul Olympics with fingernails painted in elaborate designs.", "Florence Griffith Joyner", ["flo jo", "flo-jo"], "Wikipedia - Women's Sprint Records"),
        ("The Czechoslovak-born American tennis titan who won a record 9 Wimbledon women's singles titles and 18 Grand Slam singles titles overall.", "Martina Navratilova", ["navratilova"], "Wikipedia - Women's Tennis"),
        ("The Scottish Formula 1 racing legend who won three World Championships (1969, 1971, 1973) and campaigned tirelessly for driver safety.", "Jackie Stewart", ["sir jackie stewart"], "Wikipedia - Formula One"),
        ("The American track star who won nine Olympic gold medals and one silver between 1984 and 1996, matching Jesse Owens's 1936 quadruple in 1984.", "Carl Lewis", ["lewis"], "Wikipedia - Olympic Legends"),
        ("The heavyweight boxing champion who retired undefeated with a record of 49-0 in 1956, winning 43 of his bouts by knockout.", "Rocky Marciano", ["marciano"], "Wikipedia - Boxing Records"),
        ("The Scottish football club that became the first British team to win the European Cup in 1967, nicknamed the 'Lisbon Lions'.", "Celtic", ["celtic fc", "the lisbon lions"], "Wikipedia - Scottish Football"),
        ("The legendary West German soccer sweeper nicknamed 'Der Kaiser' who captained Germany to the 1974 World Cup and managed them to the 1990 title.", "Franz Beckenbauer", ["beckenbauer", "der kaiser"], "Wikipedia - German Football"),
        ("The Austrian Formula 1 champion who survived a fiery, disfiguring crash at the Nürburgring in 1976 and returned to race just 40 days later.", "Niki Lauda", ["lauda"], "Wikipedia - Formula 1"),
        ("The Cuban middle-distance runner who achieved a historic double gold in the 400m and 800m at the 1976 Montreal Olympics, nicknamed 'El Caballo'.", "Alberto Juantorena", ["juantorena"], "Wikipedia - Olympic Athletics"),
        ("The legendary French distance runner of Algerian descent who won the marathon at the 1956 Melbourne Olympics after fighting in WWII.", "Alain Mimoun", ["mimoun"], "Wikipedia - Olympic Marathon"),
        ("The Spanish cyclist who won five consecutive Tour de France titles between 1991 and 1995, dominating long individual time trials.", "Miguel Indurain", ["indurain"], "Wikipedia - Tour de France"),
        ("The American baseball pitcher nicknamed 'The Left Arm of God' who threw four no-hitters including a perfect game for the Los Angeles Dodgers.", "Sandy Koufax", ["koufax"], "Wikipedia - Baseball Hall of Fame"),
        ("The British middle-distance runner who became the first human in history to run a sub-four-minute mile on May 6, 1954 at Iffley Road, Oxford.", "Roger Bannister", ["sir roger bannister"], "Wikipedia - Mile Run"),
        ("The heavyweight champion known as 'The Easton Assassin' who held the WBC title from 1978 to 1983 and defended it 20 consecutive times.", "Larry Holmes", ["holmes"], "Wikipedia - Boxing Champions"),
        ("The New York Mets manager who led the 'Miracle Mets' to a stunning 1969 World Series victory after decades of futility.", "Gil Hodges", ["hodges"], "Wikipedia - Miracle Mets"),
        ("The Soviet weightlifter who won consecutive super-heavyweight Olympic gold medals in 1972 and 1976, setting 80 world records.", "Vasily Alekseyev", ["alekseyev"], "Wikipedia - Olympic Weightlifting"),
        ("The Australian tennis player who achieved the rare calendar-year Grand Slam in men's singles twice: as an amateur in 1962 and as a professional in 1969.", "Rod Laver", ["laver", "the rocket"], "Wikipedia - Calendar Grand Slam"),
        ("The American football coach who led the Green Bay Packers to victory in the first two Super Bowls, whose name graces the Super Bowl trophy.", "Vince Lombardi", ["lombardi"], "Wikipedia - Lombardi Trophy"),
        ("The Swedish tennis star who won five consecutive Wimbledon men's singles titles (1976–1980) and six French Open titles with cool composure.", "Bjorn Borg", ["björn borg", "borg"], "Wikipedia - Tennis Legends"),
    ]
    for clue, ans, acc, src in items_300:
        q.append({"value": 300, "clue": clue, "answer": ans, "accepted": acc, "source": src})

    # $400 tier (40 items)
    items_400 = [
        ("The Olympic event that combines cross-country skiing and rifle shooting, originating from military patrol training.", "Biathlon", ["winter biathlon"], "Wikipedia - Winter Olympic Sports"),
        ("The French founder of the modern Olympic Games who revived the ancient games in Athens in 1896 and designed the Olympic rings.", "Pierre de Coubertin", ["coubertin", "baron pierre de coubertin"], "Wikipedia - Olympic Movement"),
        ("The English football stadium that featured the iconic 'Twin Towers' before being demolished and rebuilt with an arch in the 2000s.", "Wembley Stadium", ["old wembley"], "Wikipedia - British Stadiums"),
        ("The traditional Gaelic Irish team sport played with wooden sticks called hurleys and a small leather ball called a sliotar.", "Hurling", ["hurling sport"], "Wikipedia - Gaelic Games"),
        ("The only goalkeeper in association football history to win the prestigious Ballon d'Or, awarded to this Soviet 'Black Spider' in 1963.", "Lev Yashin", ["yashin", "the black spider"], "Wikipedia - Goalkeeping Legends"),
        ("The Italian road cycling classic nicknamed 'La Classicissima' that is the longest one-day professional cycling race in modern cycling (~300 km).", "Milan-San Remo", ["milano-sanremo"], "Wikipedia - Cycling Monuments"),
        ("The baseball pitcher who won 511 games in Major League Baseball, whose name is honored by the annual award given to the best pitchers.", "Cy Young", ["young", "denton true young"], "Wikipedia - Cy Young Award"),
        ("The Japanese martial art that translates as 'the way of the sword', practiced with bamboo shinai and protective bogu armor.", "Kendo", ["kendō"], "Wikipedia - Japanese Martial Arts"),
        ("The American tennis champion who famously defeated self-proclaimed male chauvinist Bobby Riggs in the 1973 'Battle of the Sexes' match.", "Billie Jean King", ["king", "billie jean moffitt"], "Wikipedia - Tennis History"),
        ("The South African rugby union national team nicknamed the Springboks that famously won the 1995 Rugby World Cup presented by Nelson Mandela.", "The Springboks", ["springboks", "south africa national rugby union team"], "Wikipedia - Rugby World Cup"),
        ("The British Formula 1 driver who is the only driver to win the 'Triple Crown of Motorsport' (Monaco GP, Indy 500, and 24 Hours of Le Mans).", "Graham Hill", ["hill"], "Wikipedia - Triple Crown of Motorsport"),
        ("The Italian cyclist who won the Giro d'Italia five times and the Tour de France twice, celebrated as 'Il Campionissimo' (Champion of Champions).", "Fausto Coppi", ["coppi"], "Wikipedia - Italian Cycling"),
        ("The New Zealand middle-distance runner who won three Olympic gold medals and set the 800m and 1,000m world records in the 1960s.", "Peter Snell", ["snell", "sir peter snell"], "Wikipedia - Middle Distance Running"),
        ("The Czech javelin thrower who won three Olympic gold medals and still holds the world record of 98.48 meters set in 1996.", "Jan Zelezny", ["železný", "jan železný"], "Wikipedia - Javelin Throw Records"),
        ("The prestigious English horse race run annually over a distance of one mile four furlongs at Epsom Downs since 1780.", "The Derby", ["epsom derby"], "Wikipedia - British Classics"),
        ("The only player to have scored a hat-trick in a FIFA World Cup final before Kylian Mbappé in 2022, achieving it for England in 1966.", "Geoff Hurst", ["sir geoff hurst"], "Wikipedia - FIFA World Cup Records"),
        ("The legendary Canadian driver who won six Grands Prix with Ferrari and whose son Jacques won the 1997 F1 World Championship.", "Gilles Villeneuve", ["villeneuve"], "Wikipedia - Formula 1"),
        ("The Russian pole vaulter who was the first woman to clear 5.00 meters and won two Olympic golds, breaking the world record 28 times.", "Yelena Isinbayeva", ["isinbayeva"], "Wikipedia - Pole Vault Records"),
        ("The 19th-century English cricketer who dominated the Victorian era with his massive beard and scored over 54,000 first-class runs.", "W.G. Grace", ["grace", "william gilbert grace"], "Wikipedia - Cricket History"),
        ("The Italian ski racer nicknamed 'La Bomba' who won three Olympic gold medals and dominated slalom and giant slalom in the late 1980s and 1990s.", "Alberto Tomba", ["tomba"], "Wikipedia - Alpine Skiing"),
        ("The famous cobbled one-day cycling classic in northern France nicknamed 'The Hell of the North' that finishes in a historic velodrome.", "Paris-Roubaix", ["paris roubaix", "hell of the north"], "Wikipedia - Cycling Monuments"),
        ("The Hungarian soccer team of the 1950s led by Ferenc Puskás that went 31 consecutive games undefeated and demolished England 6-3 at Wembley.", "The Golden Team", ["mighty magyars", "aranycsapat"], "Wikipedia - Football History"),
        ("The American swimmer who won four individual medley gold medals at four consecutive Olympic Games (2004–2016) in the 200m IM.", "Michael Phelps", ["phelps"], "Wikipedia - Olympic Swimming Records"),
        ("The legendary West Indian cricket captain who led the West Indies during their dominant 1970s and 1980s era without losing a Test series for 15 years.", "Clive Lloyd", ["lloyd"], "Wikipedia - West Indies Cricket"),
        ("The Scottish racing driver who won two Formula 1 World Championships for Lotus (1963, 1965) and the 1965 Indianapolis 500 before dying at Hockenheim in 1968.", "Jim Clark", ["clark"], "Wikipedia - Formula One"),
        ("The Mexican boxer who held world championships in three weight classes and went 89-0-1 before suffering his first professional defeat in 1993.", "Julio Cesar Chavez", ["chávez", "julio césar chávez"], "Wikipedia - Mexican Boxing"),
        ("The iconic 19th-century game played in Scotland on frozen lochs using granite stones with brass handles and brooms.", "Curling", ["the roaring game"], "Wikipedia - History of Curling"),
        ("The Cuban heavyweight boxer who won three consecutive Olympic gold medals in 1972, 1976, and 1980, famously turning down millions to defect.", "Teofilo Stevenson", ["stevenson"], "Wikipedia - Olympic Boxing"),
        ("The multi-sport winter discipline that combines ski jumping from a normal or large hill with a 10 km cross-country skiing pursuit race.", "Nordic Combined", ["nordic combined event"], "Wikipedia - Winter Olympics"),
        ("The Dutch speed skater who won five Olympic gold medals across four Winter Olympics, married to fellow champion Marrit Leenstra.", "Ireen Wust", ["ireen wüst", "wust"], "Wikipedia - Speed Skating"),
        ("The American distance runner who won the 1972 Olympic marathon in Munich, sparking the American recreational jogging boom of the 1970s.", "Frank Shorter", ["shorter"], "Wikipedia - Olympic Marathon"),
        ("The French tennis championship venue named after an aviator who was the first to fly non-stop across the Mediterranean Sea in 1913.", "Roland Garros", ["stade roland garros"], "Wikipedia - French Open"),
        ("The American figure skater who won back-to-back Olympic gold medals in 1948 and 1952, inventing the Button camel spin.", "Dick Button", ["button"], "Wikipedia - Figure Skating"),
        ("The Italian soccer club from Turin nicknamed 'The Old Lady' (La Vecchia Signora) that has won a record 36 Serie A titles.", "Juventus", ["juventus fc", "juve"], "Wikipedia - Italian Football"),
        ("The historic cricket ground in St John's Wood, London known as the 'Home of Cricket' and headquarters of the Marylebone Cricket Club (MCC).", "Lord's", ["lords cricket ground", "lords"], "Wikipedia - Cricket Grounds"),
        ("The American basketball coach who led the UCLA Bruins men's basketball team to 10 NCAA national championships in 12 years, the 'Wizard of Westwood'.", "John Wooden", ["wooden"], "Wikipedia - College Basketball"),
        ("The Austrian alpine ski racer who won the downhill, slalom, and giant slalom triple crown at the 1956 Cortina d'Ampezzo Winter Olympics.", "Toni Sailer", ["sailer"], "Wikipedia - Winter Olympics"),
        ("The traditional sailing race contested every Boxing Day from Sydney Harbour, Australia, to the capital of Tasmania across Bass Strait.", "Sydney to Hobart Yacht Race", ["sydney to hobart"], "Wikipedia - Yacht Racing"),
        ("The British heptathlete who won gold at the 2012 London Olympics in front of her home crowd on 'Super Saturday'.", "Jessica Ennis-Hill", ["ennis", "jessica ennis"], "Wikipedia - Olympic Heptathlon"),
        ("The Soviet hockey goaltender who was considered the best in the world, whose benching by Viktor Tikhonov after the 1st period helped trigger the 'Miracle on Ice'.", "Vladislav Tretiak", ["tretiak"], "Wikipedia - Ice Hockey Goaltenders"),
    ]
    for clue, ans, acc, src in items_400:
        q.append({"value": 400, "clue": clue, "answer": ans, "accepted": acc, "source": src})

    # $500 tier (40 items)
    items_500 = [
        ("The 18th-century French court tennis game that was the direct indoor precursor to modern lawn tennis, played with walls and roofs.", "Jeu de Paume", ["real tennis", "court tennis"], "Wikipedia - History of Tennis"),
        ("The Finnish javelin thrower who won three consecutive Olympic medals and whose father and two brothers also won Olympic gold medals.", "Tero Pitkamaki", ["matti järvinen", "järvinen brothers"], "Wikipedia - Finnish Javelin"),
        ("The only driver in Formula 1 history to win the World Drivers' Championship posthumously, after being killed during practice at Monza in 1970.", "Jochen Rindt", ["rindt"], "Wikipedia - Formula 1 Records"),
        ("The obscure equestrian event contested at the 1900 Paris Olympic Games that involved jumping over a series of wooden hacks and hurdles.", "Four-in-hand Carriage Driving", ["mail coach driving"], "Wikipedia - 1900 Olympics"),
        ("The Hungarian pistol shooter who won back-to-back Olympic rapid fire pistol golds in 1948 and 1952 after his right hand was destroyed by a grenade in 1938.", "Karoly Takacs", ["takács", "károly takács"], "Wikipedia - Paralympic/Olympic Feats"),
        ("The distance in nautical miles of the prestigious Fastnet Race from Cowes around Fastnet Rock to Plymouth/Cherbourg.", "608 nautical miles", ["605", "608 nm", "600 nautical miles"], "Wikipedia - Offshore Yacht Racing"),
        ("The ancient Olympic pentathlon consisted of five disciplines: the stadion sprint, wrestling, long jump, javelin throw, and this throwing event.", "Discus", ["discus throw"], "Wikipedia - Ancient Olympic Pentathlon"),
        ("The legendary Italian racing cyclist of the 1910s and 1920s nicknamed 'The Iron Man' who won the Giro d'Italia in 1920 while having only one leg.", "Carlo Oriani", ["enrico tonti", "ottavio bottecchia"], "Wikipedia - Giro d'Italia History"),
        ("The Japanese judoka who won the open-weight Olympic gold at the 1984 Los Angeles Games despite tearing his right calf muscle in the preliminary rounds.", "Yasuhiro Yamashita", ["yamashita"], "Wikipedia - Olympic Judo"),
        ("The only man to win Olympic gold medals in both the 100m sprint and the 400m hurdles at the same Olympic Games, achieved in 1900.", "Walter Tewksbury", ["tewksbury"], "Wikipedia - 1900 Paris Olympics"),
        ("The historic 19th-century Australian rules football pioneer who codified the original rules of the game in Melbourne in 1859 with William Hammersley.", "Tom Wills", ["wills"], "Wikipedia - Australian Rules Football"),
        ("The first cricketer in Test history to take all 10 wickets in a single innings, achieving it for England against Australia at Old Trafford in 1956.", "Jim Laker", ["laker"], "Wikipedia - Cricket Bowling Records"),
        ("The French alpine ski racer who won all three men's alpine skiing gold medals (downhill, giant slalom, slalom) at the 1968 Grenoble Winter Olympics.", "Jean-Claude Killy", ["killy"], "Wikipedia - 1968 Winter Olympics"),
        ("The German equestrian rider who won eight Olympic gold medals between 1992 and 2024, the most successful equestrian in Olympic history.", "Isabell Werth", ["werth"], "Wikipedia - Olympic Dressage"),
        ("The Swiss mountaineer who completed the first solo ascent of Mount Everest without supplemental oxygen during the post-monsoon season in 1980.", "Reinhold Messner", ["messner"], "Wikipedia - Mountaineering Feats"),
        ("The British rower who won gold medals at five consecutive Olympic Games from 1984 to 2000, knighted by Queen Elizabeth II.", "Sir Steve Redgrave", ["redgrave", "steve redgrave"], "Wikipedia - Olympic Rowing"),
        ("The 1932 Olympic 100m champion from Poland who was discovered upon autopsy in 1980 to have intersex chromosome characteristics.", "Stanislawa Walasiewicz", ["stella walsh", "walasiewicz"], "Wikipedia - Olympic Controversy"),
        ("The Scottish motorcycle racer who won 26 Isle of Man TT races, the all-time record until surpassed by his nephew Michael Dunlop in 2024.", "Joey Dunlop", ["dunlop"], "Wikipedia - Isle of Man TT"),
        ("The Basque pelota game played with a long, curved wicker basket strapped to the arm, considered one of the fastest ball sports in the world.", "Jai Alai", ["cesta punta"], "Wikipedia - Basque Pelota"),
        ("The American track athlete who won gold in both the 200m and 400m at the 1996 Atlanta Olympics wearing distinctive golden running spikes.", "Michael Johnson", ["johnson"], "Wikipedia - Sprinting Records"),
        ("The Italian motor racer who won the inaugural Formula 1 World Championship in 1950 driving an Alfa Romeo 158 Alfetta.", "Giuseppe Farina", ["nino farina"], "Wikipedia - 1950 Formula One"),
        ("The 19th-century bare-knuckle boxing champion who fought a legendary 75-round championship bout against Jake Kilrain in 1889 under London Prize Ring Rules.", "John L. Sullivan", ["sullivan"], "Wikipedia - Bare-knuckle Boxing"),
        ("The legendary Czech cross-country skier and cyclist who won the 30 km cross-country gold medal at the 1968 Grenoble Winter Olympics.", "Jiri Raska", ["jiří raška"], "Wikipedia - Ski Jumping"),
        ("The Scottish rally driver who became the youngest World Rally Champion in 1995 driving for the Subaru World Rally Team.", "Colin McRae", ["mcrae"], "Wikipedia - World Rally Championship"),
        ("The Dutch football striker who scored the impossible volley from an acute angle in the Euro 1988 final against the Soviet Union.", "Marco van Basten", ["van basten"], "Wikipedia - UEFA European Championship"),
        ("The American decathlete who was stripped of his 1912 Olympic gold medals because he had accepted money for playing semi-pro baseball, reinstated in 1982.", "Jim Thorpe", ["thorpe", "wa-tho-huk"], "Wikipedia - Jim Thorpe"),
        ("The ancient Olympic combat sport combining boxing and wrestling where virtually all strikes and holds were permitted except biting and eye-gouging.", "Pankration", ["pancratium"], "Wikipedia - Ancient Combat Sports"),
        ("The British racing driver who won back-to-back 24 Hours of Le Mans races for Bentley in 1929 and 1930, leader of the 'Bentley Boys'.", "Woolf Barnato", ["barnato"], "Wikipedia - 24 Hours of Le Mans"),
        ("The Ethiopian marathoner who won the 1960 Rome Olympic marathon running completely barefoot, the first sub-Saharan African to win Olympic gold.", "Abebe Bikila", ["bikila"], "Wikipedia - Olympic Marathon History"),
        ("The Swiss ski jumper nicknamed the 'Harry Potter of ski jumping' who won four individual Olympic gold medals across 2002 and 2010.", "Simon Ammann", ["ammann"], "Wikipedia - Ski Jumping"),
        ("The legendary Japanese marathon runner who withdrew from the 1912 Stockholm Olympic marathon, completing the race 54 years later in 1967 in 54:08:32.", "Shizo Kanakuri", ["kanakuri"], "Wikipedia - Olympic Curiosities"),
        ("The American long jumper who held the world record for 23 years until Mike Powell leaped 8.95 meters in Tokyo in 1991.", "Bob Beamon", ["beamon"], "Wikipedia - World Records in Athletics"),
        ("The 1954 FIFA World Cup final where West Germany miraculously defeated Hungary's 'Mighty Magyars' 3-2 in Bern, Switzerland.", "Miracle of Bern", ["das wunder von bern"], "Wikipedia - 1954 FIFA World Cup"),
        ("The French cyclist who finished on the podium of the Tour de France eight times without ever winning a single Tour, the 'Eternal Second'.", "Raymond Poulidor", ["poulidor"], "Wikipedia - Tour de France History"),
        ("The traditional Canadian lacrosse game originated by Indigenous peoples, historically called Tewaaraton by the Mohawk Nation.", "Lacrosse", ["tewaaraton", "baggataway"], "Wikipedia - Indigenous Sports"),
        ("The Italian racing driver who won back-to-back Formula 1 World Championships for Ferrari in 1952 and 1953.", "Alberto Ascari", ["ascari"], "Wikipedia - Scuderia Ferrari"),
        ("The South African cricket fast bowler who was banned alongside South Africa during apartheid after taking 89 wickets in just 16 Tests.", "Mike Procter", ["procter"], "Wikipedia - South African Cricket"),
        ("The Hungarian fencing master who won six consecutive Olympic gold medals in the team sabre event between 1932 and 1960.", "Aladar Gerevich", ["aladár gerevich"], "Wikipedia - Olympic Fencing"),
        ("The legendary 19th-century jockey who rode three Kentucky Derby winners and was an enslaved person until the Emancipation Proclamation.", "Isaac Murphy", ["murphy", "isaac burns murphy"], "Wikipedia - African American Jockeys"),
        ("The Soviet weightlifter who clean and jerked 266 kg (586.4 lbs) in 1988, the heaviest weight ever lifted in official competition history.", "Leonid Taranenko", ["taranenko"], "Wikipedia - Weightlifting World Records"),
    ]
    for clue, ans, acc, src in items_500:
        q.append({"value": 500, "clue": clue, "answer": ans, "accepted": acc, "source": src})

    return q

if __name__ == "__main__":
    q = get_questions()
    print("Sports questions count:", len(q))
    from collections import Counter
    print("Tier counts:", Counter(x["value"] for x in q))
