"""
Inventions & Tech - 200 Curated Trivia Questions
40 items per tier: $100, $200, $300, $400, $500
"""

def get_questions():
    q = []
    # $100 tier (40 items)
    items_100 = [
        ("The co-founder of Apple Inc. who famously unveiled the original iPhone at Macworld in January 2007.", "Steve Jobs", ["jobs", "steven jobs"], "Wikipedia - Consumer Electronics"),
        ("The worldwide computer network that allows information to be shared globally using TCP/IP.", "The Internet", ["internet"], "Wikipedia - Internet"),
        ("The search engine company founded in 1998 by Stanford PhD students Larry Page and Sergey Brin.", "Google", ["google search", "alphabet"], "Wikipedia - Tech Giants"),
        ("The universal abbreviation for 'HyperText Transfer Protocol' used to fetch web resources.", "HTTP", ["https"], "Wikipedia - Networking Protocols"),
        ("The company founded by Bill Gates and Paul Allen in 1975 that created the Windows operating system.", "Microsoft", ["msft"], "Wikipedia - Software History"),
        ("The British mathematician and codebreaker celebrated as the father of modern theoretical computer science.", "Alan Turing", ["turing"], "Wikipedia - Pioneers of Computing"),
        ("The device invented by Thomas Edison in 1879 that brought electric illumination into homes.", "Incandescent Light Bulb", ["light bulb", "lightbulb"], "Wikipedia - History of Inventions"),
        ("The popular smartphone operating system developed by Google, named after a human-like robot.", "Android", ["android os"], "Wikipedia - Mobile Operating Systems"),
        ("The social media network founded by Mark Zuckerberg in his Harvard dorm room in 2004.", "Facebook", ["meta"], "Wikipedia - Social Media"),
        ("The open-source operating system kernel created by Finnish student Linus Torvalds in 1991.", "Linux", ["linux kernel"], "Wikipedia - Operating Systems"),
        ("The microscopic silicon circuit containing millions or billions of transistors on a single chip.", "Microchip", ["integrated circuit", "cpu", "microprocessor"], "Wikipedia - Semiconductors"),
        ("The Scottish-born inventor who received the first US patent for the electrical telephone in 1876.", "Alexander Graham Bell", ["bell"], "Wikipedia - Telecommunications"),
        ("The American aircraft pioneers Orville and Wilbur who achieved the first controlled powered airplane flight in 1903.", "Wright Brothers", ["the wright brothers", "orville and wilbur wright"], "Wikipedia - Aviation History"),
        ("The short-range wireless communication technology named after a 10th-century Scandinavian Viking king.", "Bluetooth", ["harald bluetooth"], "Wikipedia - Wireless Tech"),
        ("The portable computing device released by Apple in 2010 that popularized the tablet category.", "iPad", ["apple ipad"], "Wikipedia - Tablets"),
        ("The global navigation system consisting of at least 24 satellites originally developed by the US military.", "GPS", ["global positioning system"], "Wikipedia - Satellite Navigation"),
        ("The physical computer component that serves as the short-term working memory for active programs.", "RAM", ["random access memory"], "Wikipedia - Computer Hardware"),
        ("The primary markup language used to structure content on web pages across the World Wide Web.", "HTML", ["hypertext markup language"], "Wikipedia - Web Development"),
        ("The multinational e-commerce company founded by Jeff Bezos in 1994, originally as an online bookstore.", "Amazon", ["amazon.com"], "Wikipedia - E-Commerce"),
        ("The battery-powered passenger vehicle company founded in 2003 and led by Elon Musk.", "Tesla", ["tesla motors"], "Wikipedia - Electric Vehicles"),
        ("The mechanical device with keys invented in the 19th century that introduced the QWERTY keyboard layout.", "Typewriter", ["the typewriter"], "Wikipedia - Office Inventions"),
        ("The hand-held pointing device invented by Douglas Engelbart in 1964 to interact with graphical computer screens.", "Computer Mouse", ["mouse"], "Wikipedia - Computer Interfaces"),
        ("The video sharing platform founded in 2005 by Chad Hurley, Steve Chen, and Jawed Karim, purchased by Google in 2006.", "YouTube", ["youtube.com"], "Wikipedia - Web Platforms"),
        ("The digital storage format introduced in 1982 by Philips and Sony that used optical lasers to read music tracks.", "Compact Disc", ["cd", "audio cd"], "Wikipedia - Optical Storage"),
        ("The electronic component that amplifies or switches electrical signals, replacing bulky vacuum tubes in the late 1940s.", "Transistor", ["the transistor"], "Wikipedia - Electronics"),
        ("The American inventor of the phonograph, motion picture camera, and practical long-lasting electric bulb.", "Thomas Edison", ["edison"], "Wikipedia - American Inventors"),
        ("The high-speed cellular networking standard that succeeded 4G LTE in the 2020s.", "5G", ["5g network", "fifth generation"], "Wikipedia - Telecommunications"),
        ("The portable personal stereo audio cassette player introduced by Sony in 1979.", "Walkman", ["sony walkman"], "Wikipedia - Consumer Electronics"),
        ("The British inventor of the steam locomotive rocket engine that pioneered passenger railway travel.", "George Stephenson", ["stephenson"], "Wikipedia - Railway History"),
        ("The electronic screen technology that uses tiny liquid crystals modulated by electrical current.", "LCD", ["liquid crystal display"], "Wikipedia - Display Tech"),
        ("The global computer network protocol that assigns numerical labels like 192.168.1.1 to devices.", "IP Address", ["internet protocol address", "ip"], "Wikipedia - Computer Networking"),
        ("The 3.5-inch magnetic storage medium with a sliding metal shutter common on computers in the 1990s.", "Floppy Disk", ["floppy diskette", "3.5 inch floppy"], "Wikipedia - Data Storage"),
        ("The technology company founded in 1968 by Robert Noyce and Gordon Moore that created the x86 microprocessor.", "Intel", ["intel corporation"], "Wikipedia - Microprocessors"),
        ("The high-definition multimedia cable interface standard used to connect TVs, monitors, and gaming consoles.", "HDMI", ["high-definition multimedia interface"], "Wikipedia - AV Cables"),
        ("The American automotive industrialist who revolutionized mass production with the moving assembly line for the Model T.", "Henry Ford", ["ford"], "Wikipedia - Automotive History"),
        ("The primary storage device in traditional computers that records data on rapidly spinning magnetic platters.", "Hard Drive", ["hdd", "hard disk drive"], "Wikipedia - Computer Storage"),
        ("The AI research laboratory that created ChatGPT and GPT-4.", "OpenAI", ["open ai"], "Wikipedia - Artificial Intelligence"),
        ("The computer peripheral used to convert physical paper documents or photos into digital image files.", "Scanner", ["document scanner", "flatbed scanner"], "Wikipedia - Computer Hardware"),
        ("The short video and photo-sharing application acquired by Meta in 2012 for $1 billion.", "Instagram", ["ig"], "Wikipedia - Social Media Platforms"),
        ("The high-efficiency light source that uses semiconductor electroluminescence, replacing incandescent bulbs.", "LED", ["light emitting diode"], "Wikipedia - Lighting Technology"),
    ]
    for clue, ans, acc, src in items_100:
        q.append({"value": 100, "clue": clue, "answer": ans, "accepted": acc, "source": src})

    # $200 tier (40 items)
    items_200 = [
        ("The British scientist who invented the World Wide Web in 1989 while working at CERN.", "Tim Berners-Lee", ["berners-lee", "tim berners lee"], "Wikipedia - World Wide Web"),
        ("The high-level programming language created by Guido van Rossum in 1991, named after a British comedy troupe.", "Python", ["python language", "monty python"], "Wikipedia - Programming Languages"),
        ("The observation made in 1965 stating that the number of transistors on a microchip doubles roughly every two years.", "Moore's Law", ["moores law", "gordon moore"], "Wikipedia - Semiconductor History"),
        ("The decentralized cryptocurrency launched in January 2009 based on a whitepaper by the pseudonymous Satoshi Nakamoto.", "Bitcoin", ["btc"], "Wikipedia - Cryptocurrencies"),
        ("The daughter of Lord Byron who wrote an algorithm for Babbage's Analytical Engine and is hailed as the first computer programmer.", "Ada Lovelace", ["lovelace", "augusta ada king"], "Wikipedia - Women in Computing"),
        ("The Serbian-American inventor who championed alternating current (AC) electricity over Edison's direct current (DC).", "Nikola Tesla", ["tesla"], "Wikipedia - War of the Currents"),
        ("The web browser released by Netscape Communications in 1994 that dominated the early World Wide Web.", "Netscape Navigator", ["netscape"], "Wikipedia - Browser Wars"),
        ("The optical disc format introduced in 2006 that won the high-definition optical disc format war against HD DVD.", "Blu-ray", ["blu ray", "bluray"], "Wikipedia - Optical Discs"),
        ("The mathematical notation and system using only zeroes and ones that forms the basis of all digital computing.", "Binary", ["binary code", "base-2"], "Wikipedia - Digital Logic"),
        ("The programming language created by James Gosling at Sun Microsystems in 1995 with the slogan 'Write Once, Run Anywhere'.", "Java", ["java language"], "Wikipedia - Software Engineering"),
        ("The mechanical general-purpose computer designed in the 1830s by English mathematician Charles Babbage.", "Analytical Engine", ["babbage analytical engine"], "Wikipedia - History of Computing"),
        ("The popular version control system created by Linus Torvalds in 2005 to manage Linux kernel development.", "Git", ["git vcs"], "Wikipedia - Software Tools"),
        ("The high-altitude research agency of the US Department of Defense that created ARPANET, the precursor to the Internet.", "DARPA", ["arpa"], "Wikipedia - Internet History"),
        ("The solid-state non-volatile storage technology used in USB flash drives and modern solid-state drives (SSDs).", "Flash Memory", ["nand flash", "flash"], "Wikipedia - Computer Memory"),
        ("The Swedish audio streaming platform founded in 2006 by Daniel Ek and Martin Lorentzon.", "Spotify", ["spotify ab"], "Wikipedia - Streaming Tech"),
        ("The English inventor who patented the first industrial automated programmable loom using punch cards in 1804.", "Joseph Marie Jacquard", ["jacquard", "jacquard loom"], "Wikipedia - Industrial Automation"),
        ("The programming language created by Brendan Eich in 1995 in just 10 days while working at Netscape.", "JavaScript", ["js"], "Wikipedia - Web Technologies"),
        ("The silicon valley research center where the graphical user interface (GUI), computer mouse, and Ethernet were invented.", "Xerox PARC", ["parc", "palo alto research center"], "Wikipedia - Computing History"),
        ("The first commercially successful personal computer with a mouse-driven graphical user interface, launched by Apple in 1984.", "Macintosh", ["apple macintosh", "mac 128k"], "Wikipedia - Apple Inc"),
        ("The computer architecture principle where data and program instructions share the same memory space, conceived by a Hungarian mathematician.", "Von Neumann Architecture", ["von neumann", "john von neumann"], "Wikipedia - Computer Architecture"),
        ("The world's first general-purpose electronic digital computer, completed in 1945 at the University of Pennsylvania.", "ENIAC", ["electronic numerical integrator and computer"], "Wikipedia - Early Computers"),
        ("The peer-to-peer file sharing protocol created by Bram Cohen in 2001 used to distribute large files over the internet.", "BitTorrent", ["torrent"], "Wikipedia - Peer-to-Peer"),
        ("The operating system developed in 1969 at Bell Labs by Ken Thompson, Dennis Ritchie, and others that influenced Linux and macOS.", "Unix", ["unix os"], "Wikipedia - Operating Systems"),
        ("The inventor of the World Wide Web's graphical browser Mosaic in 1993, who went on to co-found Netscape and Andreessen Horowitz.", "Marc Andreessen", ["andreessen"], "Wikipedia - Web History"),
        ("The standard markup sheet language used for describing the visual presentation and layout of HTML web pages.", "CSS", ["cascading style sheets"], "Wikipedia - Web Design"),
        ("The cryptographic cipher machine used by Nazi Germany to protect military communications, broken by Polish and British codebreakers at Bletchley Park.", "Enigma Machine", ["enigma"], "Wikipedia - Cryptography"),
        ("The Italian electrical engineer who shared the 1909 Nobel Prize in Physics for his development of practical wireless radiotelegraphy.", "Guglielmo Marconi", ["marconi"], "Wikipedia - Wireless Pioneers"),
        ("The open-source relational database management system originally developed by Michael Widenius, named after his daughter My.", "MySQL", ["my sql"], "Wikipedia - Database Tech"),
        ("The protocol suite standard that defines how data packets are formatted, addressed, transmitted, routed, and received on the Internet.", "TCP/IP", ["transmission control protocol / internet protocol"], "Wikipedia - Internet Protocol Suite"),
        ("The early electronic computing device constructed using 18,000 vacuum tubes, built for the US Army during WWII.", "ENIAC", ["eniac computer"], "Wikipedia - Historical Computers"),
        ("The microblogging social media platform launched in 2006 famous for its 140-character message limit, rebranded as X in 2023.", "Twitter", ["x", "twitter.com"], "Wikipedia - Social Media"),
        ("The technology used in touchscreens that detects touch by measuring changes in electrical capacitance from a finger.", "Capacitive Touchscreen", ["capacitive touch"], "Wikipedia - Touchscreens"),
        ("The video game company that launched Pong in 1972 and dominated early home console gaming with the Atari 2600.", "Atari", ["atari inc"], "Wikipedia - Video Game History"),
        ("The American computer scientist who developed the first compiler for a computer programming language and popularized machine-independent languages.", "Grace Hopper", ["hopper", "rear admiral grace hopper"], "Wikipedia - Women in Tech"),
        ("The high-speed networking cable made of glass or plastic strands that transmits information via pulses of light.", "Fiber Optic Cable", ["optical fiber", "fiber optics"], "Wikipedia - Telecommunications"),
        ("The standard character encoding scheme introduced in 1963 that assigns numbers from 0 to 127 to English letters and symbols.", "ASCII", ["american standard code for information interchange"], "Wikipedia - Character Encoding"),
        ("The portable electronic reader launched by Amazon in 2007 that used an E Ink electronic paper display.", "Kindle", ["amazon kindle"], "Wikipedia - E-Readers"),
        ("The American chemist and industrialist who invented dynamite in 1867 and endowed the Nobel Prizes.", "Alfred Nobel", ["nobel"], "Wikipedia - Explosives & Inventions"),
        ("The software licensing model where applications are hosted centrally in the cloud and accessed via subscription over the web.", "SaaS", ["software as a service"], "Wikipedia - Cloud Computing"),
        ("The computer peripheral introduced by Xerox in 1969 that uses a laser beam to project an image onto an electrically charged drum.", "Laser Printer", ["laser printing"], "Wikipedia - Office Tech"),
    ]
    for clue, ans, acc, src in items_200:
        q.append({"value": 200, "clue": clue, "answer": ans, "accepted": acc, "source": src})

    # $300 tier (40 items)
    items_300 = [
        ("The laboratory at AT&T where the transistor, the laser, Unix, C, and radio astronomy were invented.", "Bell Labs", ["bell laboratories", "nokia bell labs"], "Wikipedia - Industrial Research"),
        ("The programming language designed by Dennis Ritchie between 1972 and 1973 at Bell Labs, from which C++, Java, and C# descend.", "C", ["c language"], "Wikipedia - Programming Languages"),
        ("The public-key cryptosystem invented in 1977 by Ron Rivest, Adi Shamir, and Leonard Adleman based on the difficulty of factoring large prime products.", "RSA", ["rsa algorithm"], "Wikipedia - Cryptography"),
        ("The Polish mathematician who broke the German military Enigma cipher in 1932 before sharing his findings with Britain and France.", "Marian Rejewski", ["rejewski"], "Wikipedia - Codebreaking"),
        ("The mathematical concept in computer science defining problems whose solutions can be verified in polynomial time.", "NP", ["nondeterministic polynomial time", "np-complete"], "Wikipedia - Computational Complexity"),
        ("The electronic delay storage automatic calculator completed in Cambridge in 1949, one of the first practical stored-program computers.", "EDSAC", ["edsac computer"], "Wikipedia - Early Computers"),
        ("The computer pioneer who coined the term 'software engineering' while leading the MIT software team for the Apollo guidance computer.", "Margaret Hamilton", ["hamilton"], "Wikipedia - Apollo Program"),
        ("The universal character encoding standard that can represent text in over 150 modern and historic scripts, supporting over 149,000 characters.", "Unicode", ["utf-8", "utf8"], "Wikipedia - Character Standards"),
        ("The distributed version control protocol created in 2005 whose fundamental repository data structure is a directed acyclic graph (DAG) of commits.", "Git", ["git protocol"], "Wikipedia - Software Engineering"),
        ("The English inventor who built the first practical steam-powered atmospheric piston engine in 1712 to pump water out of mines.", "Thomas Newcomen", ["newcomen", "newcomen engine"], "Wikipedia - Steam Engines"),
        ("The database model proposed by Edgar F. Codd in 1970 that organizes data into tables (relations) of columns and rows.", "Relational Database", ["relational model", "rdbms"], "Wikipedia - Database Systems"),
        ("The British mathematician whose 1854 work 'An Investigation of the Laws of Thought' established the algebra that underlies all digital logic gates.", "George Boole", ["boole", "boolean algebra"], "Wikipedia - Mathematical Logic"),
        ("The mechanical calculator invented by French polymath Blaise Pascal in 1642 to help his father with tax calculations.", "Pascaline", ["pascal's calculator"], "Wikipedia - Calculating Machines"),
        ("The consensus algorithm created by Satoshi Nakamoto that uses computational hash solving to prevent double-spending in Bitcoin.", "Proof of Work", ["pow", "hashcash"], "Wikipedia - Blockchain Tech"),
        ("The first commercial handheld mobile phone released by Motorola in 1983, nicknamed 'The Brick'.", "DynaTAC 8000X", ["dynatac", "motorola dynatac"], "Wikipedia - Mobile Phones"),
        ("The German engineer who in 1941 built the Z3, the world's first working programmable, fully automatic digital computer.", "Konrad Zuse", ["zuse"], "Wikipedia - Computing Pioneers"),
        ("The open-source distributed container orchestration system originally designed by Google engineers and now maintained by the CNCF.", "Kubernetes", ["k8s"], "Wikipedia - DevOps"),
        ("The theoretical thought experiment proposed by Alan Turing in 1950 to evaluate whether a machine can exhibit human-equivalent intelligence.", "Turing Test", ["the turing test", "imitation game"], "Wikipedia - Artificial Intelligence"),
        ("The structural material invented in 1856 by Henry Bessemer that allowed mass manufacturing of inexpensive structural steel.", "Bessemer Process", ["bessemer steel"], "Wikipedia - Metallurgy"),
        ("The three-dimensional integrated circuit packaging technology where multiple dies are stacked vertically using through-silicon vias (TSVs).", "3D Packaging", ["3d ic", "chiplet"], "Wikipedia - Microelectronics"),
        ("The data transmission technique that divides a message into small blocks routed independently across network nodes.", "Packet Switching", ["packet switching network"], "Wikipedia - Computer Networking"),
        ("The object-oriented extension of the C programming language created in 1979 by Danish computer scientist Bjarne Stroustrup.", "C++", ["c plus plus"], "Wikipedia - Programming Languages"),
        ("The Scottish engineer whose improvements to the Newcomen steam engine in the 1760s sparked the Industrial Revolution, giving his name to the unit of power.", "James Watt", ["watt"], "Wikipedia - Industrial Revolution"),
        ("The first commercial spreadsheet program released for the Apple II computer in 1979 that made personal computers a business necessity.", "VisiCalc", ["visicalc spreadsheet"], "Wikipedia - Software History"),
        ("The network layer protocol that uses 128-bit addresses to solve the address exhaustion problem of 32-bit IPv4.", "IPv6", ["internet protocol version 6"], "Wikipedia - Internet Protocols"),
        ("The artificial intelligence system developed by Google DeepMind that defeated world champion Go player Lee Sedol in 2016.", "AlphaGo", ["alphago deepmind"], "Wikipedia - AI Milestones"),
        ("The light-emitting technology that uses organic thin films between electrodes, offering true black levels because pixels emit their own light.", "OLED", ["organic light-emitting diode"], "Wikipedia - Display Tech"),
        ("The Swedish inventor who patented the zipper in its modern interlocking teeth form in 1913.", "Gideon Sundback", ["sundback"], "Wikipedia - Inventions"),
        ("The asynchronous JavaScript and XML web development technique that allows web pages to update content without full page reload.", "AJAX", ["ajax technique"], "Wikipedia - Web Development"),
        ("The American computer engineer who created Ethernet in 1973 at Xerox PARC and co-founded 3Com.", "Robert Metcalfe", ["metcalfe"], "Wikipedia - Networking History"),
        ("The machine-readable two-dimensional matrix barcode invented in 1994 by Masahiro Hara for Japanese automotive company Denso Wave.", "QR Code", ["quick response code"], "Wikipedia - Barcodes"),
        ("The high-level programming language created in 1957 by John Backus at IBM, widely considered the first commercial high-level language.", "FORTRAN", ["formula translation"], "Wikipedia - Early Languages"),
        ("The lightweight data-interchange format derived from JavaScript object syntax popularized by Douglas Crockford in the early 2000s.", "JSON", ["javascript object notation"], "Wikipedia - Data Formats"),
        ("The microcomputer kit introduced on the cover of Popular Electronics in January 1975 that inspired Bill Gates and Paul Allen to write BASIC.", "Altair 8800", ["altair", "mits altair 8800"], "Wikipedia - Home Computer Revolution"),
        ("The wireless networking standard designated IEEE 802.11, commonly referred to by this consumer brand name.", "Wi-Fi", ["wifi"], "Wikipedia - Wireless Networking"),
        ("The American inventor who patented vulcanized rubber in 1844, giving his name to a famous tire company.", "Charles Goodyear", ["goodyear"], "Wikipedia - Polymer History"),
        ("The computational theorem proving that any classical computer with infinite memory can be simulated by a universal Turing machine.", "Church-Turing Thesis", ["turing-church thesis"], "Wikipedia - Computability Theory"),
        ("The American telephone company engineer who in 1948 published 'A Mathematical Theory of Communication', founding digital information theory.", "Claude Shannon", ["shannon"], "Wikipedia - Information Theory"),
        ("The fast-Fourier transform (FFT) algorithm published in 1965 by J.W. Cooley and John Tukey that revolutionized digital signal processing.", "Cooley-Tukey Algorithm", ["cooley-tukey fft", "fft algorithm"], "Wikipedia - Algorithms"),
        ("The space telescope launched in 1990 by NASA and ESA that orbits Earth outside the distorting atmosphere, capturing deep universe imagery.", "Hubble Space Telescope", ["hubble"], "Wikipedia - Space Telescopes"),
    ]
    for clue, ans, acc, src in items_300:
        q.append({"value": 300, "clue": clue, "answer": ans, "accepted": acc, "source": src})

    # $400 tier (40 items)
    items_400 = [
        ("The structural concept in deep learning introduced in 2017 in the landmark paper 'Attention Is All You Need'.", "Transformer", ["transformer architecture", "transformers"], "Wikipedia - Deep Learning"),
        ("The British inventor of the world's first commercial hovercraft, tested across the English Channel in 1959.", "Christopher Cockerell", ["cockerell"], "Wikipedia - Maritime Inventions"),
        ("The quantum computing pioneer who in 1994 devised an algorithm to factor integers in polynomial time on a quantum computer.", "Peter Shor", ["shor", "shor's algorithm"], "Wikipedia - Quantum Computing"),
        ("The open-source operating system created in 1987 by Andrew Tanenbaum for teaching purposes that inspired Linus Torvalds to write Linux.", "MINIX", ["minix os"], "Wikipedia - Operating Systems"),
        ("The early calculating machine demonstrated in 1673 by Gottfried Wilhelm Leibniz that could multiply and divide using a stepped drum.", "Stepped Reckoner", ["leibniz wheel", "stepped drum"], "Wikipedia - Mechanical Calculators"),
        ("The photolithographic technique using light at 13.5 nm wavelength, pioneered by Dutch firm ASML to etch cutting-edge microchips.", "EUV", ["extreme ultraviolet lithography", "euv lithography"], "Wikipedia - Semiconductor Fabrication"),
        ("The Hungarian-American computer scientist who designed the first spreadsheet compiler and created Microsoft Word and Excel.", "Charles Simonyi", ["simonyi"], "Wikipedia - Software History"),
        ("The formal verification and security protocol used in asymmetric cryptography where the secret key can prove knowledge without revealing it.", "Zero-Knowledge Proof", ["zk-proof", "zk-snark", "zero knowledge"], "Wikipedia - Cryptography"),
        ("The early electronic musical synthesizer invented in 1928 by a French cellist, controlled with a ring worn on the finger.", "Ondes Martenot", ["martenot"], "Wikipedia - Electronic Musical Instruments"),
        ("The inventor of the relational algebra and normal forms (1NF, 2NF, 3NF) for database normalization in the 1970s.", "Edgar F. Codd", ["e.f. codd", "ted codd"], "Wikipedia - Database Theory"),
        ("The deep neural network trained by DeepMind in 2020 that solved the 50-year-old biological challenge of predicting 3D protein structures.", "AlphaFold", ["alphafold 2"], "Wikipedia - Computational Biology"),
        ("The memory management hardware component inside modern microprocessors that translates virtual memory addresses to physical RAM addresses.", "MMU", ["memory management unit"], "Wikipedia - Computer Architecture"),
        ("The algorithm created by Whitfield Diffie and Martin Hellman in 1976 that allowed two parties to securely establish a shared secret key over an insecure channel.", "Diffie-Hellman Key Exchange", ["diffie-hellman"], "Wikipedia - Cryptography"),
        ("The 1968 landmark technology demonstration by Douglas Engelbart at Fall Joint Computer Conference showcasing mouse, hypertext, and video calling.", "The Mother of All Demos", ["mother of all demos"], "Wikipedia - Computing History"),
        ("The programming language developed by John McCarthy at MIT in 1958 characterized by extensive use of parenthesized prefix syntax.", "Lisp", ["lisp language"], "Wikipedia - Artificial Intelligence"),
        ("The British aerospace engineer who patented the turbojet aircraft engine in 1930, flying his first jet aircraft in 1941.", "Frank Whittle", ["sir frank whittle"], "Wikipedia - Jet Engines"),
        ("The cache coherence protocol widely used in multi-core processors named after its four states: Modified, Exclusive, Shared, Invalid.", "MESI Protocol", ["mesi"], "Wikipedia - Computer Architecture"),
        ("The deep learning optimization algorithm proposed in 2014 by Diederik Kingma and Jimmy Ba based on adaptive estimates of lower-order moments.", "Adam Optimizer", ["adam"], "Wikipedia - Machine Learning"),
        ("The distributed consensus algorithm published by Leslie Lamport in 1998, known for its Greek island parliament allegory.", "Paxos", ["paxos algorithm"], "Wikipedia - Distributed Systems"),
        ("The alternative, more understandable distributed consensus algorithm created by Diego Ongaro and John Ousterhout at Stanford in 2014.", "Raft", ["raft consensus"], "Wikipedia - Distributed Systems"),
        ("The 19th-century English mathematician whose Analytical Engine was designed to use punch cards adapted from Jacquard looms.", "Charles Babbage", ["babbage"], "Wikipedia - History of Computing"),
        ("The low-level systems programming language developed at Mozilla by Graydon Hoare, designed for memory safety without garbage collection.", "Rust", ["rust-lang"], "Wikipedia - Programming Languages"),
        ("The microkernel architecture that minimizes operating system core code in privileged mode, developed by Jochen Liedtke in the 1990s.", "L4 Microkernel", ["l4"], "Wikipedia - Operating Systems"),
        ("The quantum mechanical device that can measure extremely subtle magnetic fields using superconducting loops with Josephson junctions.", "SQUID", ["superconducting quantum interference device"], "Wikipedia - Superconductivity"),
        ("The electronic component fabricated with gallium nitride (GaN) that enables ultra-compact, high-efficiency smartphone and laptop fast chargers.", "GaN Semiconductor", ["gallium nitride", "gan"], "Wikipedia - Power Electronics"),
        ("The Dutch computer scientist who received the 1972 Turing Award for contributions to structured programming and created the shortest path graph algorithm.", "Edsger W. Dijkstra", ["dijkstra"], "Wikipedia - Algorithm Pioneers"),
        ("The high-speed interface developed by Intel and Apple that combines PCI Express and DisplayPort into a USB-C connector.", "Thunderbolt", ["thunderbolt 4", "thunderbolt 3"], "Wikipedia - Computer Buses"),
        ("The computer system developed by IBM that defeated world chess champion Garry Kasparov in a six-game match in 1997.", "Deep Blue", ["ibm deep blue"], "Wikipedia - Artificial Intelligence"),
        ("The computer networking routing protocol based on the Bellman-Ford algorithm that uses hop count as its routing metric.", "RIP", ["routing information protocol"], "Wikipedia - Network Protocols"),
        ("The American computer scientist who designed the relational query language SQL with Raymond Boyce at IBM in the 1970s.", "Donald D. Chamberlin", ["chamberlin"], "Wikipedia - SQL"),
        ("The French engineer who invented the daguerreotype photographic process announced to the world in 1839.", "Louis Daguerre", ["daguerre"], "Wikipedia - History of Photography"),
        ("The cryptographic hash function designed by the US National Security Agency (NSA) that produces a 256-bit digest, standard in Bitcoin.", "SHA-256", ["secure hash algorithm 256"], "Wikipedia - Cryptographic Hash"),
        ("The optical disc technology that uses phase-change alloy films to achieve rewritable storage capabilities.", "CD-RW", ["dvd-rw", "phase change optical storage"], "Wikipedia - Optical Storage"),
        ("The American inventor of the quadruplex telegraph and carbon microphone who established the Menlo Park research laboratory.", "Thomas Edison", ["edison"], "Wikipedia - Menlo Park"),
        ("The mathematical problem in cryptography that relies on the difficulty of finding the discrete logarithm in elliptic curve groups.", "ECDSA", ["elliptic curve cryptography", "ecc"], "Wikipedia - Cryptography"),
        ("The software virtualization technology that uses OS-level virtualization to deliver containerized environments, founded by Solomon Hykes in 2013.", "Docker", ["docker containers"], "Wikipedia - Containerization"),
        ("The 19th-century device invented by Samuel Morse and Alfred Vail that encoded text into electrical pulses of long and short duration.", "Electric Telegraph", ["morse telegraph"], "Wikipedia - Telecommunications"),
        ("The microarchitectural vulnerability discovered in 2018 in modern processors that exploits speculative execution and CPU caching.", "Spectre", ["spectre and meltdown", "meltdown"], "Wikipedia - Computer Security"),
        ("The American computer scientist who co-founded Sun Microsystems, wrote the vi text editor, and co-designed Java.", "Bill Joy", ["joy"], "Wikipedia - Software Pioneers"),
        ("The optical networking technique that multiplexes multiple optical carrier signals onto a single optical fiber using different wavelengths of laser light.", "WDM", ["dense wavelength division multiplexing", "dwdm"], "Wikipedia - Fiber Optics"),
    ]
    for clue, ans, acc, src in items_400:
        q.append({"value": 400, "clue": clue, "answer": ans, "accepted": acc, "source": src})

    # $500 tier (40 items)
    items_500 = [
        ("The first mechanical stored-program computer to execute a program, nicknamed 'Baby', built at Manchester University in June 1948.", "Manchester Baby", ["manchester mark 1", "small-scale experimental machine"], "Wikipedia - Early Computers"),
        ("The algorithm discovered by Lov Grover in 1996 that provides a quadratic speedup for searching unsorted databases on a quantum computer.", "Grover's Algorithm", ["grovers algorithm"], "Wikipedia - Quantum Algorithms"),
        ("The microcode instruction set concept developed by John Cocke at IBM in the 1970s that reduced instruction set complexity.", "RISC", ["reduced instruction set computer"], "Wikipedia - Processor Design"),
        ("The Dutch computer scientist who invented the semaphore synchronization primitive and the concept of structured programming without GOTO statements.", "Edsger W. Dijkstra", ["dijkstra"], "Wikipedia - Concurrency Theory"),
        ("The mathematical model of lambda calculus developed in the 1930s by this American logician, foundational to functional programming.", "Alonzo Church", ["church"], "Wikipedia - Lambda Calculus"),
        ("The first true high-level object-oriented programming language, developed in the 1960s at the Norwegian Computing Center by Ole-Johan Dahl and Kristen Nygaard.", "Simula", ["simula 67"], "Wikipedia - Object-Oriented Programming"),
        ("The cryptographic lattice-based mathematical problem that forms the backbone of post-quantum public-key encryption schemes like Kyber.", "Learning With Errors", ["lwe", "lattice cryptography"], "Wikipedia - Post-Quantum Cryptography"),
        ("The semiconductor manufacturing technology that replaced planar MOSFETs with 3D vertical fin gates starting at the 22nm node.", "FinFET", ["fin field-effect transistor"], "Wikipedia - Semiconductor Devices"),
        ("The English clockmaker who solved the longitude problem in 1759 by inventing the H4 marine chronometer.", "John Harrison", ["harrison"], "Wikipedia - Horology"),
        ("The computer storage subsystem concept published in 1988 by David Patterson, Garth Gibson, and Randy Katz that combines multiple physical hard disks into a logical array.", "RAID", ["redundant array of independent disks"], "Wikipedia - Storage Systems"),
        ("The functional programming language based on Hindley-Milner type inference developed in 1990, named after an American logician.", "Haskell", ["haskell brooks curry"], "Wikipedia - Functional Programming"),
        ("The 1936 paper 'On Computable Numbers' by Alan Turing introduced this imaginary machine with an infinite tape and a read/write head.", "Turing Machine", ["universal turing machine"], "Wikipedia - Theoretical Computer Science"),
        ("The quantum mechanical paradox in quantum computing where error correction thresholds require roughly 1,000 physical qubits to form one logical qubit.", "Fault-Tolerant Quantum Computing", ["quantum error correction", "surface codes"], "Wikipedia - Quantum Information"),
        ("The British inventor of the first practical electronic musical instrument played without physical contact, invented in 1920 by Lev Termen.", "Theremin", ["thereminvox", "etherphone"], "Wikipedia - Electronic Instruments"),
        ("The computer architecture pioneered by Seymour Cray in 1976 that featured vector registers and a distinctive horseshoe-shaped bench design.", "Cray-1", ["cray 1 supercomputer"], "Wikipedia - Supercomputing"),
        ("The distributed hash table (DHT) routing algorithm proposed in 2001 by Maymounkov and Mazières, widely used in IPFS, BitTorrent, and Ethereum.", "Kademlia", ["kademlia dht"], "Wikipedia - Distributed Hash Tables"),
        ("The 19th-century inventor who constructed the first practical underwater telegraph cable insulated with gutta-percha across the English Channel in 1851.", "John Watkins Brett", ["brett brothers"], "Wikipedia - Submarine Cables"),
        ("The computational complexity class comprising decision problems solvable by a deterministic Turing machine in polynomial space.", "PSPACE", ["pspace-complete"], "Wikipedia - Complexity Theory"),
        ("The pioneer of relational databases who proved that relational calculus and relational algebra have equivalent expressive power (Codd's Theorem).", "Edgar F. Codd", ["e.f. codd"], "Wikipedia - Relational Algebra"),
        ("The microarchitectural hardware technique where instructions are executed in parallel across multiple pipeline execution units within a single core.", "Superscalar Architecture", ["superscalar processor"], "Wikipedia - Processor Architecture"),
        ("The early optical computing device developed in 1960 by Theodore Maiman at Hughes Research Laboratories, emitting the world's first coherent laser beam from synthetic ruby.", "Ruby Laser", ["maiman ruby laser"], "Wikipedia - Laser History"),
        ("The formal proof language and interactive theorem prover based on the Calculus of Inductive Constructions developed at Inria in France.", "Coq", ["coq proof assistant", "rocq"], "Wikipedia - Formal Verification"),
        ("The 19th-century French inventor of the first practical pantograph telegraph system that could transmit handwriting and drawings over telegraph lines in 1860.", "Giovanni Caselli", ["caselli", "pantelegraph"], "Wikipedia - Early Telecommunications"),
        ("The non-blocking concurrent queue algorithm published in 1996 by Maged Michael and Michael Scott that uses compare-and-swap (CAS) primitives.", "Michael-Scott Queue", ["ms-queue"], "Wikipedia - Lock-Free Data Structures"),
        ("The Scottish engineer who in 1861 demonstrated the world's first permanent color photograph using red, green, and blue optical filters.", "James Clerk Maxwell", ["maxwell"], "Wikipedia - Color Photography"),
        ("The hardware translation lookaside buffer (TLB) miss handler algorithm implemented in hardware or software to accelerate page table traversals.", "Page Table Walker", ["hardware page walker"], "Wikipedia - Virtual Memory"),
        ("The zero-knowledge succinct non-interactive argument of knowledge cryptographic construction popularized in Zcash.", "ZK-SNARK", ["zk snark", "snark"], "Wikipedia - Cryptography"),
        ("The 1971 microprocessor created by Federico Faggin, Ted Hoff, and Stanley Mazor at Intel that was the first commercially produced single-chip CPU.", "Intel 4004", ["4004"], "Wikipedia - Microprocessor History"),
        ("The optical astronomical instrument invented in 1930 by Bernhard Schmidt that uses a spherical mirror and a thin aspheric corrector plate to capture wide-field views.", "Schmidt Camera", ["schmidt telescope"], "Wikipedia - Astronomical Optics"),
        ("The garbage collection algorithm introduced by John McCarthy in 1960 that traverses object references from root pointers and reclaims unreachable memory.", "Mark-and-Sweep", ["mark and sweep garbage collection"], "Wikipedia - Memory Management"),
        ("The English inventor who created the water frame spinning machine in 1769, establishing the modern factory system at Cromford Mill.", "Richard Arkwright", ["arkwright"], "Wikipedia - Industrial Revolution"),
        ("The formal language theory parsing algorithm for context-free grammars developed independently by Cocke, Younger, and Kasami.", "CYK Algorithm", ["cocke-younger-kasami"], "Wikipedia - Parsing Algorithms"),
        ("The French inventor who in 1888 patented and shot the earliest surviving motion picture footage in Leeds, England, before mysteriously vanishing from a train in 1890.", "Louis Le Prince", ["le prince"], "Wikipedia - History of Film"),
        ("The theoretical maximum data transmission rate over a noisy channel established in 1948 by Claude Shannon: C = B * log2(1 + S/N).", "Shannon-Hartley Theorem", ["shannon limit", "shannon capacity"], "Wikipedia - Information Theory"),
        ("The persistent key-value store developed by Google based on Log-Structured Merge-trees (LSM-trees), open-sourced in 2011.", "LevelDB", ["level db"], "Wikipedia - Storage Engines"),
        ("The pioneering American computer engineer who built the first electronic music synthesizer with digital oscillators at Bell Labs, known as MUSIC-N.", "Max Mathews", ["mathews"], "Wikipedia - Computer Music"),
        ("The semiconductor design company that pioneered the fabless business model in 1987, founded in Taiwan by Morris Chang.", "TSMC", ["taiwan semiconductor manufacturing company"], "Wikipedia - Foundry Model"),
        ("The mathematical problem in cryptographic zero-knowledge systems where proving polynomial relations requires pairing-friendly elliptic curves like BLS12-381.", "Bilinear Pairings", ["pairing-friendly curves"], "Wikipedia - Elliptic Curve Pairings"),
        ("The early electrostatic memory storage tube invented in 1946 by Freddie Williams and Tom Kilburn that served as the RAM of the Manchester Baby.", "Williams-Kilburn Tube", ["williams tube"], "Wikipedia - Computer Memory History"),
        ("The memory consistency model that guarantees all memory operations appear to all processors in a single global sequential order, formalized by Leslie Lamport in 1979.", "Sequential Consistency", ["lamport sequential consistency"], "Wikipedia - Memory Models"),
    ]
    for clue, ans, acc, src in items_500:
        q.append({"value": 500, "clue": clue, "answer": ans, "accepted": acc, "source": src})

    return q

if __name__ == "__main__":
    q = get_questions()
    print("Technology questions count:", len(q))
    from collections import Counter
    print("Tier counts:", Counter(x["value"] for x in q))
