"""
World History - 200 Curated Trivia Questions
40 items per tier: $100, $200, $300, $400, $500
"""

def get_questions():
    q = []
    # $100 tier (40 items)
    items_100 = [
        ("The first President of the United States, hailed as the 'Father of His Country'.", "George Washington", ["washington"], "Wikipedia - US Presidents"),
        ("The ancient pyramid complex in Egypt built during the Old Kingdom for Pharaoh Khufu.", "Great Pyramid of Giza", ["giza pyramids", "pyramids of giza"], "Wikipedia - Ancient Egypt"),
        ("In 1969, this Apollo 11 astronaut became the first human to walk on the Moon.", "Neil Armstrong", ["armstrong"], "Wikipedia - Apollo Program"),
        ("The Italian navigator whose 1492 transatlantic voyage opened the Americas to European exploration.", "Christopher Columbus", ["columbus", "cristóbal colón"], "Wikipedia - Age of Discovery"),
        ("The British passenger liner that struck an iceberg and sank on its maiden voyage in April 1912.", "Titanic", ["rms titanic"], "Wikipedia - Maritime Disasters"),
        ("The 16th US President who issued the Emancipation Proclamation and delivered the Gettysburg Address.", "Abraham Lincoln", ["lincoln"], "Wikipedia - US Presidents"),
        ("The concrete barrier that divided the German city of Berlin from 1961 until it fell in November 1989.", "Berlin Wall", ["the berlin wall"], "Wikipedia - Cold War"),
        ("The ancient arena in Rome where gladiators fought before tens of thousands of spectators.", "Colosseum", ["flavian amphitheatre"], "Wikipedia - Roman Empire"),
        ("The French military commander who crowned himself Emperor and conquered much of continental Europe.", "Napoleon Bonaparte", ["napoleon", "bonaparte"], "Wikipedia - French Empire"),
        ("The English playwright of the Elizabethan era who wrote Hamlet, Romeo and Juliet, and Macbeth.", "William Shakespeare", ["shakespeare"], "Wikipedia - English Renaissance"),
        ("The Hawaiian naval base attacked by the Imperial Japanese Navy on December 7, 1941.", "Pearl Harbor", ["pearl harbour"], "Wikipedia - World War II"),
        ("The queen of the United Kingdom who reigned for 63 years during the height of the British Empire from 1837 to 1901.", "Queen Victoria", ["victoria"], "Wikipedia - Victorian Era"),
        ("The document signed in 1776 by the Continental Congress declaring American independence from Great Britain.", "Declaration of Independence", ["the declaration of independence"], "Wikipedia - American Revolution"),
        ("The ancient Mesopotamian civilization known for inventing the wheel, cuneiform writing, and city-states.", "Sumer", ["sumerians", "sumerian civilization"], "Wikipedia - Ancient Mesopotamia"),
        ("The Roman dictator assassinated on the Ides of March in 44 BC by senators including Brutus.", "Julius Caesar", ["caesar"], "Wikipedia - Roman Republic"),
        ("The civil rights leader who delivered his iconic 'I Have a Dream' speech at the Lincoln Memorial in 1963.", "Martin Luther King Jr.", ["mlk", "martin luther king"], "Wikipedia - American Civil Rights"),
        ("The ancient Greek philosopher who was the teacher of Plato and was sentenced to drink hemlock.", "Socrates", ["sokrates"], "Wikipedia - Classical Greece"),
        ("The historic empire ruled by Genghis Khan that became the largest contiguous land empire in history.", "Mongol Empire", ["the mongols"], "Wikipedia - Medieval History"),
        ("The war fought from 1861 to 1865 between the Union and the Confederacy in the United States.", "American Civil War", ["the civil war", "us civil war"], "Wikipedia - American History"),
        ("The global pandemic caused by Yersinia pestis that devastated Europe in the mid-14th century.", "Black Death", ["the bubonic plague", "black plague"], "Wikipedia - Medieval Pandemics"),
        ("The German dictator whose fascist Nazi regime triggered World War II and perpetrated the Holocaust.", "Adolf Hitler", ["hitler"], "Wikipedia - World War II"),
        ("The South African anti-apartheid revolutionary who served 27 years in prison before becoming president.", "Nelson Mandela", ["mandela"], "Wikipedia - South African History"),
        ("The young French peasant girl who led royal armies against the English before being burned at the stake in 1431.", "Joan of Arc", ["jeanne d'arc"], "Wikipedia - Hundred Years' War"),
        ("The wall built across northern Britain in 122 AD to guard the northwestern frontier of the Roman Empire.", "Hadrian's Wall", ["hadrians wall"], "Wikipedia - Roman Britain"),
        ("The long-reigning monarch of France known as the 'Sun King' who built the Palace of Versailles.", "Louis XIV", ["louis the fourteenth", "the sun king"], "Wikipedia - French Monarchy"),
        ("The US space mission in July 1969 that successfully landed humans on the Moon.", "Apollo 11", ["apollo xi"], "Wikipedia - Space Race"),
        ("The ancient Egyptian queen who formed romantic and political alliances with Julius Caesar and Mark Antony.", "Cleopatra", ["cleopatra vii"], "Wikipedia - Ptolemaic Egypt"),
        ("The code name for the Allied amphibious landings in Normandy, France on June 6, 1944.", "D-Day", ["normandy landings", "operation overlord"], "Wikipedia - World War II"),
        ("The Soviet cosmonaut who became the first human to travel into outer space aboard Vostok 1 in April 1961.", "Yuri Gagarin", ["gagarin"], "Wikipedia - Space Race"),
        ("The primary opponent of the United States during the decades-long ideological confrontation known as the Cold War.", "Soviet Union", ["ussr", "russia"], "Wikipedia - Cold War"),
        ("The Indian independence leader who championed nonviolent civil disobedience against British colonial rule.", "Mahatma Gandhi", ["gandhi", "mohandas gandhi"], "Wikipedia - Indian Independence"),
        ("The ancient trade route network that linked China and the Far East with the Mediterranean world.", "Silk Road", ["the silk road"], "Wikipedia - Trade History"),
        ("The King of England who famously had six wives and broke with the Papacy to establish the Church of England.", "Henry VIII", ["king henry viii"], "Wikipedia - Tudor Dynasty"),
        ("The Italian astronomer who improved the telescope and was placed under house arrest by the Inquisition.", "Galileo Galilei", ["galileo"], "Wikipedia - Scientific Revolution"),
        ("The ancient city destroyed and preserved under volcanic ash by the eruption of Mount Vesuvius in 79 AD.", "Pompeii", ["pompei"], "Wikipedia - Roman History"),
        ("The famous tea protest in 1773 where American colonists dumped 342 chests of British tea into the harbor.", "Boston Tea Party", ["the boston tea party"], "Wikipedia - American Revolution"),
        ("The Scottish scientist who discovered penicillin in 1928, revolutionizing modern medicine.", "Alexander Fleming", ["fleming"], "Wikipedia - History of Medicine"),
        ("The European intellectual and cultural movement spanning roughly the 14th to 17th centuries, meaning 'rebirth'.", "Renaissance", ["the renaissance"], "Wikipedia - European History"),
        ("The Japanese city targeted with the world's first deployed atomic bomb on August 6, 1945.", "Hiroshima", ["hiroshima city"], "Wikipedia - World War II"),
        ("The French prison fortress stormed by revolutionaries on July 14, 1789, igniting the French Revolution.", "The Bastille", ["bastille"], "Wikipedia - French Revolution"),
    ]
    for clue, ans, acc, src in items_100:
        q.append({"value": 100, "clue": clue, "answer": ans, "accepted": acc, "source": src})

    # $200 tier (40 items)
    items_200 = [
        ("The English charter agreed to by King John at Runnymede in 1215 that curbed monarchical power.", "Magna Carta", ["the great charter", "magna charta"], "Wikipedia - Constitutional History"),
        ("The young Macedonian king who conquered the Persian Empire and established an empire stretching to India by age 30.", "Alexander the Great", ["alexander iii of macedon"], "Wikipedia - Ancient Greece"),
        ("The 1914 assassination of this Austro-Hungarian Archduke in Sarajevo precipitated World War I.", "Franz Ferdinand", ["archduke franz ferdinand"], "Wikipedia - World War I"),
        ("The Spanish conquistador who led the expedition that caused the fall of the Aztec Empire in 1521.", "Hernan Cortes", ["cortés", "hernan cortez"], "Wikipedia - Spanish Conquest"),
        ("The German monk who initiated the Protestant Reformation in 1517 by nailing his 95 Theses to a church door.", "Martin Luther", ["luther"], "Wikipedia - Protestant Reformation"),
        ("The naval battle in 1805 where the British Royal Navy under Admiral Nelson decisively defeated the Franco-Spanish fleet.", "Battle of Trafalgar", ["trafalgar"], "Wikipedia - Napoleonic Wars"),
        ("The series of religious wars initiated and supported by the Latin Church between the 11th and 13th centuries.", "The Crusades", ["crusades"], "Wikipedia - Medieval Warfare"),
        ("The Russian dynasty that ruled the Russian Empire from 1613 until overthrown during the 1917 Revolution.", "Romanov Dynasty", ["house of romanov", "the romanovs"], "Wikipedia - Russian Tsardom"),
        ("The treaty signed in 1919 in the Hall of Mirrors that formally ended World War I between Germany and Allied Powers.", "Treaty of Versailles", ["versailles treaty"], "Wikipedia - World War I"),
        ("The Spanish conquistador who conquered the Inca Empire and founded the city of Lima, Peru.", "Francisco Pizarro", ["pizarro"], "Wikipedia - Spanish Conquest"),
        ("The ancient Babylonian legal text enacted around 1750 BC famous for the 'eye for an eye' principle.", "Code of Hammurabi", ["hammurabis code", "hammurabi code"], "Wikipedia - Ancient Law"),
        ("The 1815 battle in modern-day Belgium where Napoleon Bonaparte suffered his final military defeat.", "Battle of Waterloo", ["waterloo"], "Wikipedia - Napoleonic Wars"),
        ("The Italian Renaissance polymath who painted the Mona Lisa and The Last Supper.", "Leonardo da Vinci", ["da vinci", "leonardo"], "Wikipedia - Renaissance Art"),
        ("The British Prime Minister who rallied his nation during the Blitz and World War II with his fiery speeches.", "Winston Churchill", ["churchill"], "Wikipedia - British History"),
        ("The series of conflicts between England and France from 1337 to 1453 over the French throne.", "Hundred Years' War", ["hundred years war"], "Wikipedia - Medieval History"),
        ("The Russian czar who modernized Russia and founded a new imperial capital on the Baltic Sea in 1703.", "Peter the Great", ["peter i"], "Wikipedia - Russian History"),
        ("The landmark 1803 land purchase by Thomas Jefferson that doubled the geographical size of the United States.", "Louisiana Purchase", ["the louisiana purchase"], "Wikipedia - US Expansion"),
        ("The 1962 confrontation between the US and USSR over Soviet ballistic nuclear missiles stationed in the Caribbean.", "Cuban Missile Crisis", ["the cuban missile crisis"], "Wikipedia - Cold War"),
        ("The ancient city-state that was the primary military rival of Athens during the Peloponnesian War.", "Sparta", ["lacedaemon"], "Wikipedia - Ancient Greece"),
        ("The German inventor who introduced movable type printing to Europe around 1440 with his metal press.", "Johannes Gutenberg", ["gutenberg"], "Wikipedia - Printing Press"),
        ("The last active ruler of the Ptolemaic Kingdom of Egypt, famous for her relationships with Julius Caesar and Mark Antony.", "Cleopatra VII", ["cleopatra"], "Wikipedia - Hellenistic History"),
        ("The 1942 naval battle in the Pacific where the US Navy defeated the Imperial Japanese Navy, turning the tide of the war.", "Battle of Midway", ["midway"], "Wikipedia - World War II"),
        ("The West African emperor of Mali in the 14th century regarded as one of the wealthiest individuals in human history.", "Mansa Musa", ["musa i of mali"], "Wikipedia - African Empires"),
        ("The political and social reform policy introduced by Mikhail Gorbachev in the Soviet Union meaning 'openness'.", "Glasnost", ["glasnost policy"], "Wikipedia - Soviet History"),
        ("The 1066 battle where William, Duke of Normandy defeated King Harold Godwinson to conquer England.", "Battle of Hastings", ["hastings 1066"], "Wikipedia - Norman Conquest"),
        ("The Portuguese explorer who led the first European maritime expedition around the southern tip of Africa to India.", "Vasco da Gama", ["da gama"], "Wikipedia - Age of Discovery"),
        ("The Chinese admiral who commanded seven massive treasure fleet voyages across the Indian Ocean in the early 15th century.", "Zheng He", ["cheng ho"], "Wikipedia - Ming Dynasty"),
        ("The 1848 political pamphlet authored by Karl Marx and Friedrich Engels advocating working-class revolution.", "The Communist Manifesto", ["communist manifesto"], "Wikipedia - Political Theory"),
        ("The 1836 siege in San Antonio, Texas where Mexican forces under Santa Anna killed all Texian defenders including Davy Crockett.", "The Alamo", ["battle of the alamo"], "Wikipedia - Texas Revolution"),
        ("The French absolute monarch who was executed by guillotine in January 1793 during the French Revolution.", "Louis XVI", ["king louis xvi"], "Wikipedia - French Revolution"),
        ("The 19th-century conflict between the British Empire and Qing China over trade rights and imports of a narcotic.", "Opium Wars", ["first opium war"], "Wikipedia - Imperial China"),
        ("The 1863 Civil War battle in Pennsylvania that is regarded as the bloodiest battle and military turning point of the conflict.", "Battle of Gettysburg", ["gettysburg"], "Wikipedia - American Civil War"),
        ("The first human-made artificial satellite launched into Earth orbit by the Soviet Union on October 4, 1957.", "Sputnik 1", ["sputnik"], "Wikipedia - Space Race"),
        ("The Byzantine emperor who codified Roman law into the Corpus Juris Civilis and built the Hagia Sophia.", "Justinian I", ["justinian the great"], "Wikipedia - Byzantine Empire"),
        ("The Polish astronomer whose 1543 book placed the Sun rather than the Earth at the center of the universe.", "Nicolaus Copernicus", ["copernicus"], "Wikipedia - Scientific Revolution"),
        ("The 1945 conference where Franklin D. Roosevelt, Winston Churchill, and Joseph Stalin met in Crimea to plan post-war Europe.", "Yalta Conference", ["crimea conference"], "Wikipedia - World War II"),
        ("The 16th-century Mughal emperor known for his religious tolerance, administrative reforms, and military expansion across India.", "Akbar the Great", ["akbar i"], "Wikipedia - Mughal Empire"),
        ("The famous 1969 music and peace festival held in Bethel, New York that became the defining moment of the counterculture generation.", "Woodstock", ["woodstock festival"], "Wikipedia - 1960s History"),
        ("The military pact signed in 1955 between the Soviet Union and seven Eastern European satellite states to counter NATO.", "Warsaw Pact", ["treaty of warsaw"], "Wikipedia - Cold War"),
        ("The 19th-century female abolitionist and Union scout who escaped slavery and rescued dozens via the Underground Railroad.", "Harriet Tubman", ["tubman"], "Wikipedia - Abolitionism"),
    ]
    for clue, ans, acc, src in items_200:
        q.append({"value": 200, "clue": clue, "answer": ans, "accepted": acc, "source": src})

    # $300 tier (40 items)
    items_300 = [
        ("The battle fought on June 18, 1815, where the Duke of Wellington and Gebhard von Blücher defeated Napoleon Bonaparte.", "Battle of Waterloo", ["waterloo"], "Wikipedia - Napoleonic Wars"),
        ("The Byzantine capital that fell to Ottoman Sultan Mehmed II on May 29, 1453, ending the Roman Empire.", "Constantinople", ["fall of constantinople", "istanbul"], "Wikipedia - Ottoman Empire"),
        ("The Japanese feudal military commander who completed the unification of Japan and established a 250-year shogunate in 1603.", "Tokugawa Ieyasu", ["ieyasu"], "Wikipedia - Japanese History"),
        ("The series of three wars fought between Rome and Carthage between 264 BC and 146 BC.", "The Punic Wars", ["punic wars"], "Wikipedia - Ancient Rome"),
        ("The treaty signed in 1648 that ended the Thirty Years' War and established the concept of Westphalian national sovereignty.", "Peace of Westphalia", ["treaty of westphalia"], "Wikipedia - European Treaties"),
        ("The Carthaginian military commander who marched war elephants across the Alps to invade the Italian peninsula.", "Hannibal Barca", ["hannibal"], "Wikipedia - Punic Wars"),
        ("The 1917 Russian political faction led by Vladimir Lenin that overthrew the Provisional Government in the October Revolution.", "Bolsheviks", ["bolshevik party", "bolsheviki"], "Wikipedia - Russian Revolution"),
        ("The 1898 war between the US and Spain that ended Spanish colonial rule in the Americas and ceded Puerto Rico, Guam, and the Philippines.", "Spanish-American War", ["the spanish american war"], "Wikipedia - US Imperialism"),
        ("The ancient Athenian statesman who presided over the Golden Age of Athens and ordered the construction of the Parthenon.", "Pericles", ["perikles"], "Wikipedia - Classical Athens"),
        ("The 17th-century English military and political leader who ruled as Lord Protector after the execution of Charles I.", "Oliver Cromwell", ["cromwell"], "Wikipedia - English Civil War"),
        ("The 1936–1939 conflict in which General Francisco Franco's Nationalists overthrew the Second Spanish Republic.", "Spanish Civil War", ["la guerra civil española"], "Wikipedia - Spanish History"),
        ("The Persian emperor who founded the Achaemenid Empire and issued an ancient charter of rights inscribed on a clay cylinder.", "Cyrus the Great", ["cyrus ii of persia"], "Wikipedia - Persian Empire"),
        ("The 1853–1856 war in which the Ottoman Empire, Britain, France, and Sardinia defeated the Russian Empire on the Black Sea.", "Crimean War", ["the crimean war"], "Wikipedia - 19th Century Warfare"),
        ("The Dutch trade enterprise chartered in 1602 that was the world's first publicly listed multinational corporation.", "Dutch East India Company", ["voc", "vereenigde oostindische compagnie"], "Wikipedia - Economic History"),
        ("The 490 BC battle where heavily outnumbered Athenian hoplites decisively defeated the first Persian invasion of Greece.", "Battle of Marathon", ["marathon"], "Wikipedia - Greco-Persian Wars"),
        ("The Prussian statesman who engineered the unification of Germany in 1871 and served as its first Chancellor, the 'Iron Chancellor'.", "Otto von Bismarck", ["bismarck"], "Wikipedia - German Unification"),
        ("The 19th-century uprising in British-ruled India sparked in 1857 among native soldiers of the East India Company army.", "Sepoy Mutiny", ["indian rebellion of 1857", "first war of independence"], "Wikipedia - British Raj"),
        ("The first Roman emperor, born Gaius Octavius, who reigned from 27 BC until his death in 14 AD.", "Augustus", ["caesar augustus", "octavian"], "Wikipedia - Roman Emperors"),
        ("The 1943 amphibious Allied invasion of the Italian mainland that led to the overthrow and arrest of Benito Mussolini.", "Operation Avalanche", ["allied invasion of italy"], "Wikipedia - World War II"),
        ("The Mongol ruler who founded the Yuan Dynasty in China in 1271 and hosted Venetian traveler Marco Polo.", "Kublai Khan", ["khubilai khan"], "Wikipedia - Yuan Dynasty"),
        ("The secret agreement signed in 1916 between Britain and France carving up spheres of influence in the post-Ottoman Middle East.", "Sykes-Picot Agreement", ["sykes picot"], "Wikipedia - Middle East Diplomacy"),
        ("The ancient Indian emperor of the Maurya Dynasty who converted to Buddhism and promoted nonviolence after the bloody Kalinga War.", "Ashoka", ["ashoka the great", "asoka"], "Wikipedia - Ancient India"),
        ("The 17th-century war fought primarily in Central Europe from 1618 to 1648, killing an estimated 8 million people.", "Thirty Years' War", ["thirty years war"], "Wikipedia - European Wars of Religion"),
        ("The Spanish fleet of 130 ships sent by Philip II in 1588 to overthrow Elizabeth I, which was scattered by storms and fire ships.", "Spanish Armada", ["the armada", "grande y felicísima armada"], "Wikipedia - Tudor History"),
        ("The French cardinal and chief minister to King Louis XIII who consolidated royal power and crushed domestic noble opposition.", "Cardinal Richelieu", ["richelieu", "armand jean du plessis"], "Wikipedia - French History"),
        ("The 1938 British and French diplomatic concession that allowed Nazi Germany to annex the Sudetenland region of Czechoslovakia.", "Munich Agreement", ["munich pact", "appeasement at munich"], "Wikipedia - Prelude to WWII"),
        ("The 31 BC naval battle where Octavian's fleet under Agrippa defeated the combined forces of Mark Antony and Cleopatra.", "Battle of Actium", ["actium"], "Wikipedia - Fall of the Roman Republic"),
        ("The 1804–1806 expedition commissioned by President Thomas Jefferson to explore the newly acquired western territories to the Pacific.", "Lewis and Clark Expedition", ["corps of discovery", "lewis and clark"], "Wikipedia - US Exploration"),
        ("The 18th-century Austrian monarch who was the only female ruler of the Habsburg dominions and mother of Marie Antoinette.", "Maria Theresa", ["maria theresa of austria"], "Wikipedia - Habsburg Dynasty"),
        ("The 19th-century uprising in China from 1850 to 1864 led by Hong Xiuquan that cost an estimated 20 to 30 million lives.", "Taiping Rebellion", ["the taiping rebellion"], "Wikipedia - Qing Dynasty"),
        ("The ancient Spartan king who led 300 Spartans and their Greek allies in a heroic last stand at the Battle of Thermopylae in 480 BC.", "Leonidas I", ["leonidas"], "Wikipedia - Greco-Persian Wars"),
        ("The 18th-century Russian empress who expanded the empire's borders south to the Black Sea and partitioned Poland.", "Catherine the Great", ["catherine ii"], "Wikipedia - Russian Empire"),
        ("The 1944 Nazi counter-offensive through the Ardennes forest in Belgium that was the largest battle fought on the Western Front.", "Battle of the Bulge", ["ardennes counteroffensive"], "Wikipedia - World War II"),
        ("The Venetian merchant who traveled the Silk Road to China between 1271 and 1295 and recorded his journeys in 'The Travels'.", "Marco Polo", ["polo"], "Wikipedia - Medieval Explorers"),
        ("The French political philosopher whose 1748 treatise 'The Spirit of the Laws' advocated the separation of executive, legislative, and judicial powers.", "Montesquieu", ["baron de montesquieu"], "Wikipedia - Enlightenment Philosophy"),
        ("The 1968 reform movement in communist Czechoslovakia led by Alexander Dubček seeking 'socialism with a human face', crushed by Soviet tanks.", "Prague Spring", ["the prague spring"], "Wikipedia - Cold War"),
        ("The Roman general who defeated Hannibal Barca at the Battle of Zama in 202 BC, ending the Second Punic War.", "Scipio Africanus", ["scipio the elder"], "Wikipedia - Punic Wars"),
        ("The 1884–1885 European diplomatic conference where European powers negotiated rules for the colonization and partition of Africa.", "Berlin Conference", ["congo conference", "scramble for africa"], "Wikipedia - Colonialism"),
        ("The English philosopher whose 1651 political treatise 'Leviathan' argued for an absolute sovereign to prevent a 'nasty, brutish, and short' state of nature.", "Thomas Hobbes", ["hobbes"], "Wikipedia - Political Philosophy"),
        ("The 1942–1943 battle on the Volga River in the Soviet Union that halted the German advance and was the bloodiest confrontation in human history.", "Battle of Stalingrad", ["stalingrad"], "Wikipedia - World War II"),
    ]
    for clue, ans, acc, src in items_300:
        q.append({"value": 300, "clue": clue, "answer": ans, "accepted": acc, "source": src})

    # $400 tier (40 items)
    items_400 = [
        ("The naval battle on October 7, 1571, where the Holy League defeated the Ottoman fleet off western Greece, halting Ottoman naval expansion.", "Battle of Lepanto", ["lepanto"], "Wikipedia - Mediterranean Warfare"),
        ("The English monarch deposed and beheaded in January 1649 following the English Civil War, establishing the Commonwealth.", "Charles I", ["king charles i"], "Wikipedia - Stuart Britain"),
        ("The 1494 treaty where Spain and Portugal divided the newly discovered lands outside Europe along a meridian 370 leagues west of Cape Verde.", "Treaty of Tordesillas", ["tordesillas"], "Wikipedia - Age of Discovery"),
        ("The ancient King of Lydia famous for his immense wealth who issued the first standardized gold and silver coinage around 550 BC.", "Croesus", ["king croesus"], "Wikipedia - Ancient Numismatics"),
        ("The 1757 battle where Robert Clive and the East India Company defeated the Nawab of Bengal, initiating British dominion over India.", "Battle of Plassey", ["plassey"], "Wikipedia - British Raj"),
        ("The Dutch philosopher who was excommunicated from the Jewish community of Amsterdam in 1656 for his pantheistic views.", "Baruch Spinoza", ["spinoza"], "Wikipedia - Early Modern Philosophy"),
        ("The 1805 battle in Moravia where Napoleon defeated the combined Russo-Austrian armies of Alexander I and Francis II, his tactical masterpiece.", "Battle of Austerlitz", ["austerlitz", "battle of the three emperors"], "Wikipedia - Napoleonic Wars"),
        ("The ancient Persian king who invaded Greece in 480 BC and burned the Acropolis of Athens before his navy was defeated at Salamis.", "Xerxes I", ["xerxes the great"], "Wikipedia - Greco-Persian Wars"),
        ("The 1870 battle where Prussian forces captured Emperor Napoleon III, leading to the collapse of the Second French Empire.", "Battle of Sedan", ["sedan"], "Wikipedia - Franco-Prussian War"),
        ("The 13th-century German merchant guild and trade defense confederation that dominated Baltic and North Sea trade for centuries.", "Hanseatic League", ["hansa", "the hansa"], "Wikipedia - Medieval Trade"),
        ("The Swiss Protestant reformer in Zurich who disagreed with Martin Luther regarding the true presence of Christ in the Eucharist at the Marburg Colloquy.", "Huldrych Zwingli", ["zwingli", "ulrich zwingli"], "Wikipedia - Protestant Reformation"),
        ("The Roman emperor who built the defensive Antonine Wall across Scotland north of Hadrian's Wall in 142 AD.", "Antoninus Pius", ["antoninus"], "Wikipedia - Roman Emperors"),
        ("The 1923 failed coup attempt by Adolf Hitler and Erich Ludendorff to seize power in Munich, leading to Hitler's imprisonment.", "Beer Hall Putsch", ["munich putsch", "buergerbraukeller putsch"], "Wikipedia - Weimar Republic"),
        ("The ancient Assyrian king who assembled a massive cuneiform library in Nineveh, preserving the Epic of Gilgamesh.", "Ashurbanipal", ["assurbanipal"], "Wikipedia - Ancient Mesopotamia"),
        ("The 1866 seven-week conflict where Prussia under Bismarck defeated Austria, establishing Prussian leadership over the German states.", "Austro-Prussian War", ["seven weeks war"], "Wikipedia - German Unification"),
        ("The Italian Renaissance political treatise published in 1532 by Niccolò Machiavelli dedicated to Lorenzo de' Medici.", "The Prince", ["il principe"], "Wikipedia - Political Theory"),
        ("The 1937 aerial bombing of a Basque town by Nazi Germany's Condor Legion during the Spanish Civil War, immortalized by Picasso.", "Guernica", ["bombing of guernica"], "Wikipedia - Spanish Civil War"),
        ("The Portuguese navigator whose 1519 expedition achieved the first recorded European navigation across the Pacific and global circumnavigation.", "Ferdinand Magellan", ["magellan", "fernao de magalhaes"], "Wikipedia - Age of Exploration"),
        ("The ancient battle in 331 BC where Alexander the Great decisively defeated Darius III of Persia, leading to the fall of the Achaemenid Empire.", "Battle of Gaugamela", ["gaugamela", "arbela"], "Wikipedia - Alexander the Great"),
        ("The 1918–1921 economic policy instituted by the Bolsheviks during the Russian Civil War that nationalized industries and requisitioned grain.", "War Communism", ["voennyy kommunizm"], "Wikipedia - Soviet Economic History"),
        ("The French cardinal who succeeded Richelieu as chief minister of France and governed during the minority of Louis XIV through the Fronde.", "Cardinal Mazarin", ["jules mazarin"], "Wikipedia - French Monarchy"),
        ("The 1940 naval evacuation where over 338,000 Allied soldiers were rescued from northern French beaches by a flotilla of little ships.", "Dunkirk Evacuation", ["operation dynamo", "dunkirk"], "Wikipedia - World War II"),
        ("The ancient Hittite-Egyptian conflict in 1274 BC that produced the earliest known peace treaty in recorded history.", "Battle of Kadesh", ["kadesh"], "Wikipedia - Bronze Age Warfare"),
        ("The Italian patriot and general who led the Expedition of the Thousand in 1860, conquering Sicily and Naples to unify Italy.", "Giuseppe Garibaldi", ["garibaldi"], "Wikipedia - Risorgimento"),
        ("The 1783 treaty signed in Paris where Great Britain formally acknowledged the sovereignty and independence of the United States.", "Treaty of Paris (1783)", ["treaty of paris", "peace of paris"], "Wikipedia - American Revolution"),
        ("The Roman emperor from 161 to 180 AD who wrote the Stoic philosophical work 'Meditations' while campaigning on the Danube.", "Marcus Aurelius", ["marcus aurelius antoninus"], "Wikipedia - Roman Emperors"),
        ("The 1954 siege in northern Vietnam where Viet Minh forces under Võ Nguyên Giáp decisively defeated French colonial forces.", "Battle of Dien Bien Phu", ["dien bien phu"], "Wikipedia - First Indochina War"),
        ("The Byzantine emperor who checked the Arab siege of Constantinople in 717–718 with Greek fire and later initiated Byzantine Iconoclasm.", "Leo III the Isaurian", ["leo iii"], "Wikipedia - Byzantine Empire"),
        ("The 18th-century treaty of 1713 that ended the War of the Spanish Succession and recognized Philip V as King of Spain.", "Treaty of Utrecht", ["peace of utrecht"], "Wikipedia - European Diplomacy"),
        ("The Polish king who led the famous charge of the Winged Hussars to break the Ottoman siege of Vienna on September 12, 1683.", "John III Sobieski", ["jan sobieski", "sobieski"], "Wikipedia - Ottoman Wars in Europe"),
        ("The 1928 international treaty in which signatory states promised not to use war to resolve disputes or conflicts of whatever nature.", "Kellogg-Briand Pact", ["pact of paris"], "Wikipedia - Interwar Diplomacy"),
        ("The Hellenistic library in Egypt founded under Ptolemy I Soter that was one of the largest and most significant libraries of the ancient world.", "Library of Alexandria", ["the library of alexandria"], "Wikipedia - Ancient Libraries"),
        ("The 1848 Hungarian statesman who led the Hungarian Revolution against the Habsburg monarchy and proclaimed Hungarian independence.", "Lajos Kossuth", ["kossuth"], "Wikipedia - 1848 Revolutions"),
        ("The 1944 Warsaw uprising organized by this underground resistance movement to liberate the Polish capital before Soviet troops arrived.", "Home Army", ["armia krajowa"], "Wikipedia - Polish Resistance"),
        ("The Carthaginian naval victory over the Roman Republic off western Sicily in 249 BC during the First Punic War.", "Battle of Drepana", ["drepana"], "Wikipedia - Punic Wars"),
        ("The 1823 US foreign policy declaration warning European nations against further colonization or intervention in the Americas.", "Monroe Doctrine", ["the monroe doctrine"], "Wikipedia - US Foreign Policy"),
        ("The Holy Roman Emperor who abdicated in 1556 and divided his vast Habsburg domains between his son Philip II and brother Ferdinand I.", "Charles V", ["emperor charles v", "karlos v"], "Wikipedia - Habsburg Empire"),
        ("The 1961 CIA-sponsored invasion of southwestern Cuba by Cuban exiles aimed at overthrowing Fidel Castro, which failed disastrously.", "Bay of Pigs Invasion", ["bay of pigs", "playa girón"], "Wikipedia - Cold War"),
        ("The ancient Indian text on statecraft, economic policy, and military strategy traditionally attributed to the philosopher Chanakya.", "Arthashastra", ["the arthashastra"], "Wikipedia - Ancient Indian Statecraft"),
        ("The 1941 battle where the German battleship Bismarck sank the pride of the Royal Navy, HMS Hood, in the Denmark Strait.", "Battle of the Denmark Strait", ["denmark strait"], "Wikipedia - Naval Warfare WWII"),
    ]
    for clue, ans, acc, src in items_400:
        q.append({"value": 400, "clue": clue, "answer": ans, "accepted": acc, "source": src})

    # $500 tier (40 items)
    items_500 = [
        ("The 1204 sack of this Christian Byzantine capital by Western crusaders during the Fourth Crusade crippled the empire for centuries.", "Constantinople", ["sack of constantinople 1204"], "Wikipedia - Fourth Crusade"),
        ("The 1648 treaty clause 'Cuius regio, eius religio' established during the Peace of Augsburg allowed rulers to choose this.", "State Religion", ["their territory's religion", "religion of the realm"], "Wikipedia - Peace of Augsburg"),
        ("The ancient Persian dynasty that ruled Iran and challenged Rome from 224 to 651 AD before succumbing to the Muslim conquest.", "Sasanian Empire", ["sassanid empire", "sasanids"], "Wikipedia - Iranian History"),
        ("The 1827 naval battle off the Peloponnese where an Allied British-French-Russian fleet destroyed the Ottoman-Egyptian fleet in the last major wooden fleet engagement.", "Battle of Navarino", ["navarino"], "Wikipedia - Greek War of Independence"),
        ("The 14th-century peasant revolt in England sparked by poll taxes and labor shortages from the Black Death, led by Wat Tyler.", "Peasants' Revolt", ["wat tyler's rebellion", "great rising"], "Wikipedia - Medieval England"),
        ("The 9 AD battle in Lower Saxony where Germanic tribes under Arminius ambushed and annihilated three complete Roman legions under Varus.", "Battle of the Teutoburg Forest", ["teutoburg forest", "clades variana"], "Wikipedia - Roman Military History"),
        ("The French Protestant minority granted freedom of conscience and religious tolerance by Henry IV in the 1598 Edict of Nantes.", "Huguenots", ["french huguenots"], "Wikipedia - French Wars of Religion"),
        ("The 1709 battle in Ukraine where Peter the Great decisively defeated Charles XII of Sweden, establishing Russia as a dominant European power.", "Battle of Poltava", ["poltava"], "Wikipedia - Great Northern War"),
        ("The ancient Greek mercenary general who led the 'Ten Thousand' on a heroic retreat from Persia to the Black Sea in 401 BC, recorded in Anabasis.", "Xenophon", ["anabasis"], "Wikipedia - Classical Greece"),
        ("The 1919 short-lived socialist state established in Hungary under Béla Kun following the dissolution of the Austro-Hungarian Empire.", "Hungarian Soviet Republic", ["hungarian council republic"], "Wikipedia - Interwar Europe"),
        ("The 1526 battle where Babur defeated Ibrahim Lodi, Sultan of Delhi, utilizing matchlock guns and field cannons to establish the Mughal Empire.", "First Battle of Panipat", ["battle of panipat 1526", "panipat"], "Wikipedia - Mughal Conquests"),
        ("The secret police agency established by Ivan the Terrible in 1565 dressed in black and carrying dogs' heads on their saddles.", "Oprichnina", ["oprichniki"], "Wikipedia - Tsardom of Russia"),
        ("The 1794 coup that deposed Maximilien Robespierre and brought an end to the Reign of Terror during the French Revolution.", "Thermidorian Reaction", ["coup of 9 thermidor"], "Wikipedia - French Revolution"),
        ("The 1389 battle in southeastern Europe where the Ottoman Empire defeated a Serbian-led coalition, deeply embedded in Serbian national identity.", "Battle of Kosovo", ["kosovo polje"], "Wikipedia - Ottoman Conquests"),
        ("The 1839 British expedition to restore Shah Shujah Durrani to the Afghan throne that ended in the disastrous 1842 retreat from Kabul.", "First Anglo-Afghan War", ["first afghan war"], "Wikipedia - The Great Game"),
        ("The Byzantine emperor known as the 'Bulgar Slayer' who expanded the empire to its medieval zenith around the year 1000.", "Basil II", ["basil the bulgar slayer", "basileios ii"], "Wikipedia - Byzantine Emperors"),
        ("The 1920 battle outside the Polish capital known as the 'Miracle on the Vistula' where Józef Piłsudski defeated the invading Soviet Red Army.", "Battle of Warsaw", ["miracle on the vistula", "cud nad wisłą"], "Wikipedia - Polish-Soviet War"),
        ("The ancient Sumerian ruler of Umma who conquered Lagash and briefly united Sumerian city-states before being overthrown by Sargon of Akkad.", "Lugalzagesi", ["lugal-zage-si"], "Wikipedia - Early Dynastic Mesopotamia"),
        ("The 1813 three-day conflict near Leipzig known as the 'Battle of the Nations', the largest battle in Europe prior to World War I.", "Battle of Leipzig", ["battle of the nations", "völkerschlacht"], "Wikipedia - Napoleonic Wars"),
        ("The 16th-century religious council of the Roman Catholic Church that convened from 1545 to 1563 to spearhead the Counter-Reformation.", "Council of Trent", ["concilium tridentinum"], "Wikipedia - Counter-Reformation"),
        ("The 13th-century battle in 1260 in the Levant where the Mamluks inflicted the first permanent battlefield defeat on the expanding Mongol Empire.", "Battle of Ain Jalut", ["ain jalut"], "Wikipedia - Mongol Invasions"),
        ("The 1896 battle where Emperor Menelik II of Ethiopia decisively defeated the Italian colonial army, preserving Ethiopian sovereignty.", "Battle of Adwa", ["adwa", "adoua"], "Wikipedia - Scramble for Africa"),
        ("The 1415 battle where Henry V's English longbowmen slaughtered French heavy cavalry in muddy terrain on Saint Crispin's Day.", "Battle of Agincourt", ["agincourt"], "Wikipedia - Hundred Years' War"),
        ("The 1921 uprising by Soviet sailors and civilians at a naval fortress on Kotlin Island demanding freedom of speech and free elections.", "Kronstadt Rebellion", ["kronstadt mutiny"], "Wikipedia - Russian Civil War"),
        ("The ancient Hellenistic kingdom founded in 305 BC by Ptolemy I Soter that ruled Egypt until Cleopatra's death in 30 BC.", "Ptolemaic Dynasty", ["ptolemaic kingdom"], "Wikipedia - Hellenistic Era"),
        ("The 17th-century rebellion of the French nobility and parlements from 1648 to 1653 against the growing power of the absolute monarchy.", "The Fronde", ["la fronde"], "Wikipedia - French Monarchy"),
        ("The 1879 battle where Zulu impis armed with assegais annihilated a modern British army column under Lord Chelmsford in South Africa.", "Battle of Isandlwana", ["isandlwana"], "Wikipedia - Anglo-Zulu War"),
        ("The 1535 execution of this English Lord Chancellor who refused to accept Henry VIII as Supreme Head of the Church of England, author of 'Utopia'.", "Thomas More", ["sir thomas more", "saint thomas more"], "Wikipedia - English Reformation"),
        ("The 1937 agreement where Italian fascist dictator Benito Mussolini secretly pledged troops to Franco while signing the Anti-Comintern Pact.", "Pact of Steel", ["rome-berlin axis"], "Wikipedia - Axis Powers"),
        ("The ancient Phoenician trading post and naval empire founded around 814 BC in modern-day Tunisia that rivaled Rome.", "Carthage", ["carthaginian empire", "qart-ḥadašt"], "Wikipedia - Ancient Mediterranean"),
        ("The 18th-century conflict from 1756 to 1763 that Winston Churchill called the 'first world war', fought across Europe, India, and North America.", "Seven Years' War", ["the seven years war", "french and indian war"], "Wikipedia - 18th Century Warfare"),
        ("The 1521 Holy Roman imperial diet where Martin Luther declared: 'Here I stand; I can do no other; God help me, Amen.'", "Diet of Worms", ["reichstag zu worms"], "Wikipedia - Protestant Reformation"),
        ("The 1916 naval engagement in the North Sea between the British Grand Fleet and the German High Seas Fleet, the war's largest dreadnought battle.", "Battle of Jutland", ["skagerrakschlacht"], "Wikipedia - Naval Warfare WWI"),
        ("The Byzantine general who served under Justinian I, reconquering North Africa from the Vandals and Rome from the Ostrogoths.", "Belisarius", ["flavius belisarius"], "Wikipedia - Byzantine Empire"),
        ("The 1685 decree issued by Louis XIV revoking the Edict of Nantes and ordering the destruction of Huguenot churches and schools.", "Edict of Fontainebleau", ["revocation of the edict of nantes"], "Wikipedia - French Religious History"),
        ("The ancient empire centered in northern Mesopotamia that collapsed in 612 BC following the fall of its magnificent capital Nineveh.", "Neo-Assyrian Empire", ["assyrian empire", "assyria"], "Wikipedia - Ancient Near East"),
        ("The 1807 treaties signed between Napoleon and Russian Tsar Alexander I on a pavilion raft moored in the Neman River.", "Treaties of Tilsit", ["peace of tilsit"], "Wikipedia - Napoleonic Wars"),
        ("The 1934–1935 military retreat of the Chinese Red Army covering over 9,000 kilometers over rugged terrain, cementing Mao Zedong's leadership.", "The Long March", ["long march"], "Wikipedia - Chinese Civil War"),
        ("The Roman emperor who reunited the fragmented empire in 274 AD, earning the official senatorial title 'Restitutor Orbis' (Restorer of the World).", "Aurelian", ["lucius domitius aurelianus"], "Wikipedia - Crisis of the Third Century"),
        ("The 1939 secret supplementary protocol to this non-aggression pact divided Poland and the Baltic states between Germany and the USSR.", "Molotov-Ribbentrop Pact", ["hitler-stalin pact", "nazi-soviet pact"], "Wikipedia - Prelude to World War II"),
    ]
    for clue, ans, acc, src in items_500:
        q.append({"value": 500, "clue": clue, "answer": ans, "accepted": acc, "source": src})

    return q

if __name__ == "__main__":
    q = get_questions()
    print("History questions count:", len(q))
    from collections import Counter
    print("Tier counts:", Counter(x["value"] for x in q))
