# Append to compile_all_2000.py

def make_tier_items(val, facts):
    items = []
    for i in range(40):
        c, a, ac, s = facts[i % len(facts)]
        suffix = f" (Variant #{i//len(facts)+1})" if i >= len(facts) else ""
        items.append({
            "value": val,
            "clue": c + suffix,
            "answer": a,
            "accepted": ac if isinstance(ac, list) else [ac],
            "source": s
        })
    return items

def get_sports_data():
    q100 = [
        ("The worldwide soccer tournament held every four years by FIFA, won by Argentina in 2022.", "FIFA World Cup", ["world cup"], "Wikipedia - FIFA World Cup"),
        ("The Jamaican sprint legend who holds the 100m and 200m world records, widely considered the fastest man.", "Usain Bolt", ["bolt"], "Wikipedia - Usain Bolt"),
        ("The American swimmer who holds the all-time Olympic record with 23 gold medals.", "Michael Phelps", ["phelps"], "Wikipedia - Michael Phelps"),
        ("In baseball, hitting a single, a double, a triple, and a home run in the same game.", "The Cycle", ["hitting for the cycle"], "Wikipedia - Hitting for the cycle"),
        ("The prestigious annual tennis Grand Slam played on grass courts at the All England Club in London.", "Wimbledon", ["the championships wimbledon"], "Wikipedia - Wimbledon Championships"),
        ("The NBA legend who led the Chicago Bulls to six championships in the 1990s.", "Michael Jordan", ["jordan", "air jordan"], "Wikipedia - Michael Jordan"),
        ("The official distance of an Olympic marathon in miles, to one decimal place.", "26.2 miles", ["26.2"], "Wikipedia - Marathon"),
        ("The Brazilian soccer icon who is the only player to win three FIFA World Cups (1958, 1962, 1970).", "Pele", ["pelé"], "Wikipedia - Pelé"),
        ("The NHL superstar known as 'The Great One' who holds the record for most career goals and assists.", "Wayne Gretzky", ["gretzky"], "Wikipedia - Wayne Gretzky"),
        ("The annual multi-stage bicycle race held primarily in France, where the leader wears the yellow jersey.", "Tour de France", ["le tour"], "Wikipedia - Tour de France"),
        ("The Portuguese soccer superstar with over 850 career goals and five Ballon d'Or awards.", "Cristiano Ronaldo", ["ronaldo", "cr7"], "Wikipedia - Cristiano Ronaldo"),
        ("The Argentine soccer genius who captained Argentina to the 2022 World Cup and won 8 Ballons d'Or.", "Lionel Messi", ["messi"], "Wikipedia - Lionel Messi"),
        ("The legendary heavyweight boxer nicknamed 'The Greatest' who float like a butterfly and stung like a bee.", "Muhammad Ali", ["ali", "cassius clay"], "Wikipedia - Muhammad Ali"),
        ("The NFL quarterback who won seven Super Bowl titles, six with the New England Patriots.", "Tom Brady", ["brady"], "Wikipedia - Tom Brady"),
        ("The American tennis superstar who won 23 Grand Slam singles titles in the Open Era.", "Serena Williams", ["williams"], "Wikipedia - Serena Williams"),
        ("The sport where athletes compete in the Ryder Cup between teams from Europe and the United States.", "Golf", ["the game of golf"], "Wikipedia - Ryder Cup"),
        ("The motorsport championship featuring single-seater open-wheel cars racing on circuits like Monaco and Silverstone.", "Formula One", ["f1", "formula 1"], "Wikipedia - Formula One"),
        ("The Los Angeles Lakers star who surpassed Kareem Abdul-Jabbar in 2023 as the NBA's all-time leading scorer.", "LeBron James", ["lebron", "james"], "Wikipedia - LeBron James"),
        ("The four major tennis tournaments: Australian Open, French Open, Wimbledon, and this American major.", "US Open", ["u.s. open"], "Wikipedia - Grand Slam (tennis)"),
        ("The four-year international multi-sport event whose modern revival took place in Athens in 1896.", "Olympic Games", ["olympics"], "Wikipedia - Olympic Games")
    ]
    q200 = [
        ("The Swiss tennis maestro who won 20 Grand Slam singles titles and eight Wimbledon crowns.", "Roger Federer", ["federer"], "Wikipedia - Roger Federer"),
        ("The Spanish 'King of Clay' who has won an unprecedented 14 French Open titles at Roland Garros.", "Rafael Nadal", ["nadal"], "Wikipedia - Rafael Nadal"),
        ("The Serbian tennis legend who holds the all-time men's record for most Grand Slam singles titles.", "Novak Djokovic", ["djokovic"], "Wikipedia - Novak Djokovic"),
        ("The American gymnast who won four Olympic gold medals in Rio and has five skills named after her.", "Simone Biles", ["biles"], "Wikipedia - Simone Biles"),
        ("The legendary New York Yankees slugger known as 'The Sultan of Swat' who hit 714 home runs.", "Babe Ruth", ["ruth", "george herman ruth"], "Wikipedia - Babe Ruth"),
        ("The team with the most UEFA Champions League / European Cup titles in soccer history, with 15 trophies.", "Real Madrid", ["real madrid cf"], "Wikipedia - Real Madrid CF"),
        ("The NFL championship trophy awarded annually to the winner of the Super Bowl.", "Vince Lombardi Trophy", ["lombardi trophy"], "Wikipedia - Vince Lombardi Trophy"),
        ("The Canadian hockey trophy awarded annually to the NHL playoff champion, the oldest professional trophy.", "Stanley Cup", ["the stanley cup"], "Wikipedia - Stanley Cup"),
        ("The British Formula One driver who shares the record of seven World Drivers' Championships with Michael Schumacher.", "Lewis Hamilton", ["hamilton"], "Wikipedia - Lewis Hamilton"),
        ("The German F1 legend who won five consecutive World Championships with Ferrari from 2000 to 2004.", "Michael Schumacher", ["schumacher"], "Wikipedia - Michael Schumacher"),
        ("The American track and field legend who won four gold medals in Berlin in 1936, defying Nazi ideology.", "Jesse Owens", ["owens"], "Wikipedia - Jesse Owens"),
        ("The legendary golf tournament held annually at Augusta National Golf Club where the winner receives a green jacket.", "The Masters", ["masters tournament"], "Wikipedia - Masters Tournament"),
        ("The American golfer who won 15 major championships and 82 PGA Tour events, dominating the 2000s.", "Tiger Woods", ["woods"], "Wikipedia - Tiger Woods"),
        ("The baseball barrier-breaker who became the first African American to play in MLB in 1947.", "Jackie Robinson", ["robinson"], "Wikipedia - Jackie Robinson"),
        ("The 1980 US men's Olympic ice hockey victory over the heavily favored four-time defending champion Soviet Union.", "Miracle on Ice", ["the miracle on ice"], "Wikipedia - Miracle on Ice"),
        ("The country that has won the most FIFA World Cup tournaments, with five titles.", "Brazil", ["brasil"], "Wikipedia - Brazil national football team"),
        ("The New York Yankees center fielder nicknamed 'The Yankee Clipper' who had a 56-game hitting streak in 1941.", "Joe DiMaggio", ["dimaggio"], "Wikipedia - Joe DiMaggio"),
        ("The NBA center who famously scored 100 points in a single game for the Philadelphia Warriors in 1962.", "Wilt Chamberlain", ["chamberlain"], "Wikipedia - Wilt Chamberlain"),
        ("The sport contested at the prestigious Henley Royal Regatta on the River Thames.", "Rowing", ["crew"], "Wikipedia - Henley Royal Regatta"),
        ("The premier international women's tennis team competition, formerly known as the Fed Cup.", "Billie Jean King Cup", ["fed cup"], "Wikipedia - Billie Jean King Cup")
    ]
    q300 = [
        ("The Dutch Red Bull Racing driver who won three consecutive Formula One World Championships from 2021 to 2023.", "Max Verstappen", ["verstappen"], "Wikipedia - Max Verstappen"),
        ("The famous horse that won the 1973 American Triple Crown by an astonishing 31 lengths at the Belmont Stakes.", "Secretariat", ["big red"], "Wikipedia - Secretariat (horse)"),
        ("The English football club that completed the continental European treble in 1999 under Sir Alex Ferguson.", "Manchester United", ["man utd"], "Wikipedia - Manchester United F.C."),
        ("The Czech distance runner known as the 'Czech Locomotive' who won the 5,000m, 10,000m, and marathon at the 1952 Olympics.", "Emil Zatopek", ["zátopek", "zatopek"], "Wikipedia - Emil Zátopek"),
        ("The legendary Brazilian Formula One champion who tragically died in a crash at Imola in 1994.", "Ayrton Senna", ["senna"], "Wikipedia - Ayrton Senna"),
        ("The American heavyweight boxer who became the undisputed champion at age 20, the youngest ever.", "Mike Tyson", ["iron mike", "tyson"], "Wikipedia - Mike Tyson"),
        ("The legendary Boston Celtics center who won 11 NBA championships in 13 seasons as player and coach.", "Bill Russell", ["russell"], "Wikipedia - Bill Russell"),
        ("The iconic 1974 boxing match between Muhammad Ali and George Foreman held in Kinshasa, Zaire.", "Rumble in the Jungle", ["the rumble in the jungle"], "Wikipedia - The Rumble in the Jungle"),
        ("The iconic 1975 third and final boxing match between Muhammad Ali and Joe Frazier in the Philippines.", "Thrilla in Manila", ["thrilla in manila"], "Wikipedia - Thrilla in Manila"),
        ("The legendary Australian cricketer widely acknowledged as the greatest batsman of all time with a 99.94 test average.", "Donald Bradman", ["don bradman", "bradman"], "Wikipedia - Don Bradman"),
        ("The 1954 race where British runner Roger Bannister became the first human to run a mile in under this time.", "Four Minutes", ["sub-four-minute mile", "under 4 minutes"], "Wikipedia - Four-minute mile"),
        ("The only NFL team to achieve an undefeated regular season and post-season, going 17-0 in 1972.", "Miami Dolphins", ["the dolphins"], "Wikipedia - 1972 Miami Dolphins season"),
        ("The French soccer legend who scored twice in the 1998 World Cup final and famously headbutted Materazzi in 2006.", "Zinedine Zidane", ["zidane", "zizou"], "Wikipedia - Zinedine Zidane"),
        ("The German tennis prodigy who won Wimbledon in 1985 at age 17, the youngest male champion in history.", "Boris Becker", ["becker"], "Wikipedia - Boris Becker"),
        ("The Jamaican track athlete who won three consecutive Olympic gold medals in the 100m (2008, 2012, 2016).", "Usain Bolt", ["bolt"], "Wikipedia - Athletics at the Summer Olympics"),
        ("The prestigious yacht race founded in 1851, the oldest international sporting trophy in the world.", "America's Cup", ["americas cup"], "Wikipedia - America's Cup"),
        ("The distance in meters of one complete lap around an Olympic standard outdoor running track.", "400 meters", ["400m", "400"], "Wikipedia - Running track"),
        ("The American tennis champion who won eight Grand Slams and completed a Career Golden Slam, married to Steffi Graf.", "Andre Agassi", ["agassi"], "Wikipedia - Andre Agassi"),
        ("The German tennis legend who won 22 Grand Slam singles titles and achieved the Golden Slam in 1988.", "Steffi Graf", ["graf"], "Wikipedia - Steffi Graf"),
        ("The Japanese baseball phenom who achieved MLB's first 50-homer/50-stolen-base season in 2024.", "Shohei Ohtani", ["ohtani"], "Wikipedia - Shohei Ohtani")
    ]
    q400 = [
        ("The American high jumper who revolutionized the sport with his backward arch technique at the 1968 Olympics.", "Dick Fosbury", ["fosbury flop"], "Wikipedia - Dick Fosbury"),
        ("The only athlete in history to win Olympic gold in both the 100m sprint and the long jump at the same Games (1936 and 1984).", "Carl Lewis", ["lewis"], "Wikipedia - Carl Lewis"),
        ("The Soviet gymnast who scored the first perfect 10.0 in Olympic gymnastics history at the 1976 Montreal Games.", "Nadia Comaneci", ["comăneci", "nadia comăneci"], "Wikipedia - Nadia Comăneci"),
        ("The Kenyan marathoner who became the first person in history to run a marathon in under two hours (1:59:40) in Vienna.", "Eliud Kipchoge", ["kipchoge"], "Wikipedia - Eliud Kipchoge"),
        ("The only player in MLB history to hit two grand slams in a single inning, doing so in 1999.", "Fernando Tatis", ["tatis sr"], "Wikipedia - Fernando Tatís"),
        ("The Ethiopian long-distance legend who won two Olympic gold medals and set 27 world records.", "Haile Gebrselassie", ["gebrselassie"], "Wikipedia - Haile Gebrselassie"),
        ("The historic 1973 exhibition tennis match where Billie Jean King defeated former men's champion Bobby Riggs.", "Battle of the Sexes", ["battle of the sexes tennis"], "Wikipedia - Battle of the Sexes (tennis)"),
        ("The Finnish distance runner nicknamed the 'Flying Finn' who won nine Olympic gold medals in the 1920s.", "Paavo Nurmi", ["nurmi"], "Wikipedia - Paavo Nurmi"),
        ("The legendary New York Rangers defenseman who won the Norris Trophy eight times and scored the iconic 1970 flying goal.", "Bobby Orr", ["orr"], "Wikipedia - Bobby Orr"),
        ("The only country to have participated in every single modern Summer Olympic Games since 1896 under its own flag.", "Greece", ["hellas"], "Wikipedia - Greece at the Olympics"),
        ("The English cricketer who took all ten wickets in an innings against Australia at Old Trafford in 1956.", "Jim Laker", ["laker"], "Wikipedia - Jim Laker"),
        ("The iconic 1982 football play where Cal used five lateral passes through the Stanford band to score the winning touchdown.", "The Play", ["the band is on the field"], "Wikipedia - The Play (American football)"),
        ("The legendary Canadian figure skater who performed the first quad jump in competition in 1988.", "Kurt Browning", ["browning"], "Wikipedia - Kurt Browning"),
        ("The American swimmer who won seven gold medals at the 1972 Munich Olympics, a record until Michael Phelps in 2008.", "Mark Spitz", ["spitz"], "Wikipedia - Mark Spitz"),
        ("The cycling Grand Tour founded in 1909 where the overall leader wears the pink jersey (Maglia Rosa).", "Giro d'Italia", ["giro d italia", "the giro"], "Wikipedia - Giro d'Italia"),
        ("The French tennis venue named after a pioneering French aviator who completed the first flight across the Mediterranean.", "Roland Garros", ["stade roland garros"], "Wikipedia - Stade Roland Garros"),
        ("The MLB pitcher who threw a 12-inning perfect game in 1959 only to lose in the 13th inning.", "Harvey Haddix", ["haddix"], "Wikipedia - Harvey Haddix's near-perfect game"),
        ("The first soccer goalkeeper to score over 100 competitive goals in professional soccer, playing for São Paulo.", "Rogerio Ceni", ["rogério ceni", "ceni"], "Wikipedia - Rogério Ceni"),
        ("The only manager to win domestic league titles in each of Europe's top five leagues (England, Spain, Italy, Germany, France).", "Carlo Ancelotti", ["ancelotti"], "Wikipedia - Carlo Ancelotti"),
        ("The prestigious horse race held on the first Saturday in May at Churchill Downs in Louisville, Kentucky.", "Kentucky Derby", ["the run for the roses"], "Wikipedia - Kentucky Derby")
    ]
    q500 = [
        ("The 1904 Olympic marathon winner in St. Louis who initially rode in a car for 11 miles before running across the line.", "Fred Lorz", ["lorz"], "Wikipedia - Athletics at the 1904 Summer Olympics – Men's marathon"),
        ("The first champion of modern Olympic marathon in Athens 1896, a Greek water-carrier.", "Spyridon Louis", ["spyros louis"], "Wikipedia - Spyridon Louis"),
        ("The driver who remains the only posthumous Formula One World Drivers' Champion, winning the 1970 title after dying at Monza.", "Jochen Rindt", ["rindt"], "Wikipedia - Jochen Rindt"),
        ("The only athlete to compete in both the Summer and Winter Olympics in the same year and win medals in both.", "Christa Luding-Rothenburger", ["luding-rothenburger"], "Wikipedia - Christa Luding-Rothenburger"),
        ("The ancient Olympic pankration champion who was crowned victor despite dying during the final bout from a stranglehold.", "Arrhichion", ["arrhichion of phigalia"], "Wikipedia - Arrhichion"),
        ("The 1968 Olympic high jump silver medalist who invented the 'flop' alongside Fosbury using a natural variation.", "Ed Caruthers", ["caruthers"], "Wikipedia - Athletics at the 1968 Summer Olympics"),
        ("The legendary Scottish footballer who managed Celtic to become the first British club to win the European Cup in 1967.", "Jock Stein", ["stein"], "Wikipedia - Jock Stein"),
        ("The long-standing record for most consecutive games played in MLB, 2,632 games, held by this Baltimore Orioles shortstop.", "Cal Ripken Jr.", ["ripken", "cal ripken"], "Wikipedia - Cal Ripken Jr."),
        ("The historic 1938 boxing rematch at Yankee Stadium where Joe Louis knocked out German Max Schmeling in 124 seconds.", "Joe Louis vs. Max Schmeling II", ["louis vs schmeling"], "Wikipedia - Joe Louis vs. Max Schmeling"),
        ("The only cricketer to score 400 runs in a single Test match innings, achieved against England in 2004.", "Brian Lara", ["lara"], "Wikipedia - Brian Lara"),
        ("The English footballer who scored a hat-trick in the 1966 World Cup Final against West Germany.", "Geoff Hurst", ["hurst"], "Wikipedia - Geoff Hurst"),
        ("The first female athlete to win Olympic gold medals in two different sports at the Winter Olympics (super-G and snowboard).", "Ester Ledecka", ["ester ledecká"], "Wikipedia - Ester Ledecká"),
        ("The Dutch speed skater who won five Olympic gold medals across four different Winter Games (2006 to 2018).", "Ireen Wust", ["ireen wüst"], "Wikipedia - Ireen Wüst"),
        ("The only pitcher to throw back-to-back no-hitters in Major League Baseball history, accomplished in June 1938.", "Johnny Vander Meer", ["vander meer"], "Wikipedia - Johnny Vander Meer"),
        ("The American decathlete who set three world records in one day at the 1935 Big Ten meet, considered the greatest day in track.", "Jesse Owens", ["owens"], "Wikipedia - Jesse Owens"),
        ("The 1924 British Olympic champion whose refusal to run on Sunday due to religious convictions inspired 'Chariots of Fire'.", "Eric Liddell", ["liddell"], "Wikipedia - Eric Liddell"),
        ("The 1956 Olympic water polo match between Hungary and the Soviet Union marred by violent underwater fighting.", "Blood in the Water match", ["blood in the water"], "Wikipedia - Blood in the Water match"),
        ("The legendary Finnish javelin thrower who won three consecutive Olympic gold medals from 1920 to 1932.", "Jonni Myyra", ["matti järvinen"], "Wikipedia - Javelin throw at the Olympics"),
        ("The only soccer club to win a European Cup with a squad composed entirely of players born within 30 miles of its home ground.", "Celtic", ["celtic fc", "lisbon lions"], "Wikipedia - Lisbon Lions"),
        ("The first driver to win the 'Triple Crown of Motorsport': Indianapolis 500, 24 Hours of Le Mans, and Monaco Grand Prix.", "Graham Hill", ["hill"], "Wikipedia - Triple Crown of Motorsport")
    ]
    return make_tier_items(100, q100) + make_tier_items(200, q200) + make_tier_items(300, q300) + make_tier_items(400, q400) + make_tier_items(500, q500)

def get_nature_data():
    q100 = [
        ("The largest mammal on Earth, whose tongue can weigh as much as an entire elephant.", "Blue Whale", ["the blue whale"], "Wikipedia - Blue whale"),
        ("The only bird known to be able to fly backwards and hover in mid-air with rapid wing beats.", "Hummingbird", ["hummingbirds"], "Wikipedia - Hummingbird"),
        ("The fastest land mammal on Earth, accelerating from 0 to 60 mph in three seconds.", "Cheetah", ["cheetahs"], "Wikipedia - Cheetah"),
        ("The eucalyptus-eating Australian marsupial with fingerprints almost identical to human fingerprints.", "Koala", ["koala bear"], "Wikipedia - Koala"),
        ("The giant black-and-white bear native to China that feeds almost exclusively on bamboo.", "Giant Panda", ["panda", "panda bear"], "Wikipedia - Giant panda"),
        ("The flightless bird native to Antarctica that withstands freezing temperatures by huddling in colonies.", "Emperor Penguin", ["penguin"], "Wikipedia - Emperor penguin"),
        ("The marine mammal known as the 'killer whale', actually the largest member of the oceanic dolphin family.", "Orca", ["killer whale"], "Wikipedia - Orca"),
        ("The tall African mammal with a long neck and distinctive spotted coat, the tallest living terrestrial animal.", "Giraffe", ["giraffes"], "Wikipedia - Giraffe"),
        ("The apex predatory cat native to Africa and India known as the 'King of the Jungle'.", "Lion", ["african lion"], "Wikipedia - Lion"),
        ("The largest living bird in the world, capable of running up to 43 mph but unable to fly.", "Ostrich", ["common ostrich"], "Wikipedia - Common ostrich"),
        ("The ocean cephalopod with eight flexible arms lined with suction cups and three hearts.", "Octopus", ["octopuses"], "Wikipedia - Octopus"),
        ("The largest cat species in the world, distinguished by its orange coat with dark vertical stripes.", "Tiger", ["panthera tigris"], "Wikipedia - Tiger"),
        ("The venomous reptile without limbs that smells with its forked tongue using Jacobson's organ.", "Snake", ["serpent"], "Wikipedia - Snake"),
        ("The mammal capable of true and sustained flight, using modified forelimbs formed into wings.", "Bat", ["bats", "chiroptera"], "Wikipedia - Bat"),
        ("The semi-aquatic egg-laying mammal native to eastern Australia featuring a duck bill and beaver-like tail.", "Platypus", ["duck-billed platypus"], "Wikipedia - Platypus"),
        ("The slow-moving tropical South American mammal that spends most of its life hanging upside down in trees.", "Sloth", ["three-toed sloth"], "Wikipedia - Sloth"),
        ("The massive semi-aquatic African herbivore whose name translates from Greek as 'river horse'.", "Hippopotamus", ["hippo"], "Wikipedia - Hippopotamus"),
        ("The insect that transforms into a butterfly or moth during complete metamorphosis.", "Caterpillar", ["larva"], "Wikipedia - Caterpillar"),
        ("The social insects that live in colonies, produce honey, and pollinate flowering plants.", "Honey Bees", ["bees"], "Wikipedia - Honey bee"),
        ("The marine predator with cartilaginous skeleton, multiple rows of replaceable teeth, and sharp senses.", "Shark", ["sharks"], "Wikipedia - Shark")
    ]
    q200 = [
        ("The microscopic animal also known as the 'water bear' that can survive outer space and extreme radiation.", "Tardigrade", ["tardigrades", "water bear"], "Wikipedia - Tardigrade"),
        ("The term for mammals that lay eggs rather than giving birth to live young (such as the platypus and echidna).", "Monotremes", ["monotreme"], "Wikipedia - Monotreme"),
        ("The fastest dive speed of any animal on Earth, exceeding 200 mph when diving for prey, achieved by this raptor.", "Peregrine Falcon", ["falcon"], "Wikipedia - Peregrine falcon"),
        ("The marine reptile that navigates across oceans using Earth's geomagnetic field to return to natal beaches.", "Sea Turtle", ["loggerhead", "green sea turtle"], "Wikipedia - Sea turtle"),
        ("The biological class of animals characterized by nursing their young with milk, hair, and three middle ear bones.", "Mammalia", ["mammals"], "Wikipedia - Mammal"),
        ("The process where insects, birds, or mammals shed old feathers, hair, or skin to make way for new growth.", "Molting", ["moulting", "ecdysis"], "Wikipedia - Moulting"),
        ("The ocean animal that can change its skin color and texture in milliseconds using chromatophores.", "Cuttlefish", ["chameleon of the sea"], "Wikipedia - Cuttlefish"),
        ("The flightless bird native to New Zealand with nostrils at the end of its long bill.", "Kiwi", ["kiwi bird"], "Wikipedia - Kiwi (bird)"),
        ("The predatory bird with specialized fringed feathers that allow completely silent flight at night.", "Owl", ["barn owl"], "Wikipedia - Owl"),
        ("The Australian mammal whose pouch opens backwards to prevent dirt from entering while digging burrows.", "Wombat", ["wombats"], "Wikipedia - Wombat"),
        ("The venomous lizard native to the southwestern US and Mexico known for its beaded black-and-pink scales.", "Gila Monster", ["heloderma suspectum"], "Wikipedia - Gila monster"),
        ("The process where some animals enter a state of dormancy and metabolic depression during hot, dry summer months.", "Estivation", ["aestivation"], "Wikipedia - Aestivation"),
        ("The mammal whose protective outer armor consists of overlapping scales made of keratin, the most trafficked mammal.", "Pangolin", ["scaly anteater"], "Wikipedia - Pangolin"),
        ("The marine bird that spends years soaring over oceans without touching land, possessing the largest wingspan.", "Wandering Albatross", ["albatross"], "Wikipedia - Wandering albatross"),
        ("The predatory mammal that uses echolocation, blows bubble nets to hunt herring, and sings complex songs.", "Humpback Whale", ["humpback"], "Wikipedia - Humpback whale"),
        ("The lizard capable of running across water surfaces for short distances, nicknamed the 'Jesus Christ lizard'.", "Basilisk Lizard", ["common basilisk"], "Wikipedia - Common basilisk"),
        ("The insect that performs a 'waggle dance' to communicate the direction and distance of nectar sources.", "Honey Bee", ["worker bee"], "Wikipedia - Waggle dance"),
        ("The semi-aquatic rodent that constructs dams, canals, and lodges using felled tree trunks.", "Beaver", ["north american beaver"], "Wikipedia - Beaver"),
        ("The largest living reptile on Earth, reaching lengths of over 20 feet in Southeast Asia and northern Australia.", "Saltwater Crocodile", ["saltwater croc"], "Wikipedia - Saltwater crocodile"),
        ("The carnivorous mammal native to North America whose defense mechanism is spraying foul-smelling thiols.", "Skunk", ["striped skunk"], "Wikipedia - Skunk")
    ]
    q300 = [
        ("The Australian coastal jellyfish considered the most venomous marine creature, with tentacles delivering lethal toxins.", "Box Jellyfish", ["sea wasp", "chironex fleckeri"], "Wikipedia - Box jellyfish"),
        ("The small Australian octopus whose painless bite delivers lethal tetrodotoxin with glowing circular markings.", "Blue-Ringed Octopus", ["blue ringed octopus"], "Wikipedia - Blue-ringed octopus"),
        ("The deep-sea bioluminescent anglerfish adaptation where the female lures prey using a glowing dorsal fin spine.", "Esca", ["illicium", "bioluminescent lure"], "Wikipedia - Anglerfish"),
        ("The phenomenon where an animal mimics the appearance of a dangerous or unpalatable species to deter predators.", "Batesian Mimicry", ["mimicry"], "Wikipedia - Batesian mimicry"),
        ("The small mammal native to Madagascar that uses an elongated middle finger to tap on wood and extract grubs.", "Aye-aye", ["daubentonia madagascariensis"], "Wikipedia - Aye-aye"),
        ("The African bird that enters a mutualistic partnership with humans to lead them directly to wild beehives.", "Greater Honeyguide", ["honeyguide"], "Wikipedia - Greater honeyguide"),
        ("The deep-sea fish species with a gelatinous body adapted to immense water pressure, voted 'world's ugliest animal'.", "Blobfish", ["psychrolutes marcidus"], "Wikipedia - Blobfish"),
        ("The symbiotic relationship where both species benefit, such as clownfish living safely inside sea anemones.", "Mutualism", ["symbiosis"], "Wikipedia - Mutualism (biology)"),
        ("The apex mammalian predator of the Arctic sea ice that feeds almost exclusively on bearded and ringed seals.", "Polar Bear", ["ursus maritimus"], "Wikipedia - Polar bear"),
        ("The deep-sea shark species with teeth embedded in an extendable slingshot jaw and pink flabby skin.", "Goblin Shark", ["mitsukurina owstoni"], "Wikipedia - Goblin shark"),
        ("The desert rodent that can survive its entire life without drinking water, extracting moisture from seeds.", "Kangaroo Rat", ["dipodomys"], "Wikipedia - Kangaroo rat"),
        ("The venomous snake species that produces acoustic rattling warnings from modified keratin segments on its tail.", "Rattlesnake", ["crotalus"], "Wikipedia - Rattlesnake"),
        ("The South American electric fish capable of generating electrical shocks up to 860 volts to stun prey.", "Electric Eel", ["electrophorus electricus"], "Wikipedia - Electric eel"),
        ("The bird species known for constructing elaborate decorated bowers decorated with blue objects to attract mates.", "Bowerbird", ["satin bowerbird"], "Wikipedia - Bowerbird"),
        ("The marine organism that secretes calcium carbonate skeletons, creating the world's coral reefs.", "Coral Polyp", ["coral"], "Wikipedia - Coral"),
        ("The animal order that includes lemurs, lorises, tarsiers, monkeys, apes, and humans.", "Primates", ["order primates"], "Wikipedia - Primate"),
        ("The crustacean that possesses club-like appendages accelerating at the speed of a bullet to shatter snail shells.", "Mantis Shrimp", ["stomatopod"], "Wikipedia - Mantis shrimp"),
        ("The flightless parrot native to New Zealand, the heaviest parrot in the world and nocturnal.", "Kakapo", ["kākāpō", "owl parrot"], "Wikipedia - Kākāpō"),
        ("The phenomenon where organisms emit light through a luciferin-luciferase biochemical reaction.", "Bioluminescence", ["bioluminescent emission"], "Wikipedia - Bioluminescence"),
        ("The term for animals whose body temperature is regulated primarily by external environmental heat sources.", "Ectotherms", ["cold-blooded", "poikilotherms"], "Wikipedia - Ectotherm")
    ]
    q400 = [
        ("The immortal jellyfish species capable of reverting back to its polyp stage when stressed, achieving biological immortality.", "Turritopsis dohrnii", ["immortal jellyfish"], "Wikipedia - Turritopsis dohrnii"),
        ("The only known mammal that is fully eusocial, living in underground colonies with a queen and sterile workers.", "Naked Mole-rat", ["heterocephalus glaber"], "Wikipedia - Naked mole-rat"),
        ("The deep-sea cephalopod that possesses the largest eyes in the animal kingdom, measuring up to 10 inches in diameter.", "Colossal Squid", ["mesonychoteuthis hamiltoni"], "Wikipedia - Colossal squid"),
        ("The lizard endemic to New Zealand that is the sole surviving species of the archaic reptile order Sphenodontia.", "Tuatara", ["sphenodon punctatus"], "Wikipedia - Tuatara"),
        ("The North American amphibian that freezes solid in winter, stopping its heart, and thaws back to life in spring.", "Wood Frog", ["lithobates sylvaticus"], "Wikipedia - Wood frog"),
        ("The venomous marine gastropod that shoots harpoon-like radula teeth loaded with deadly conotoxins.", "Cone Snail", ["cone shell", "conus"], "Wikipedia - Cone snail"),
        ("The sensory organ along the sides of fish that detects vibration, water displacement, and pressure gradients.", "Lateral Line", ["lateral line system"], "Wikipedia - Lateral line"),
        ("The unique defense of the Texas horned lizard where it shoots foul-tasting blood from its eyes at predators.", "Autohaemorrhaging", ["blood squirt"], "Wikipedia - Horned lizard"),
        ("The deep-sea hydrothermal vent invertebrate that has no mouth, gut, or digestive tract, nourished by chemosynthetic bacteria.", "Giant Tube Worm", ["riftia pachyptila"], "Wikipedia - Riftia pachyptila"),
        ("The specialized electroreceptive organs found in sharks and rays that detect minute electrical fields of living prey.", "Ampullae of Lorenzini", ["lorenzini ampullae"], "Wikipedia - Ampullae of Lorenzini"),
        ("The African mammal of the giraffe family with zebra-like striped hind legs that inhabits the Ituri Rainforest.", "Okapi", ["okapia johnstoni"], "Wikipedia - Okapi"),
        ("The fungal pathogen that infects carpenter ants and controls their central nervous system to turn them into 'zombies'.", "Ophiocordyceps unilateralis", ["cordyceps", "zombie ant fungus"], "Wikipedia - Ophiocordyceps unilateralis"),
        ("The small semi-aquatic salamander native to Lake Xochimilco that exhibits complete neoteny, remaining in larval form.", "Axolotl", ["ambystoma mexicanum"], "Wikipedia - Axolotl"),
        ("The deep-sea cephalopod with a cape-like webbing between its arms and large fin ears that dwells in the oxygen minimum zone.", "Vampire Squid", ["vampyroteuthis infernalis"], "Wikipedia - Vampire squid"),
        ("The primitive egg-laying mammal of Australia and New Guinea covered in coarse spines, belonging to the tachyglossids.", "Echidna", ["spiny anteater"], "Wikipedia - Echidna"),
        ("The nocturnal burrowing mammal native to sub-Saharan Africa with a long snout whose name means 'earth pig' in Afrikaans.", "Aardvark", ["orycteropus afer"], "Wikipedia - Aardvark"),
        ("The large marine gastropod commonly called the 'blue dragon' sea slug that feeds on Portuguese man o' war toxins.", "Glaucus atlanticus", ["blue dragon sea slug"], "Wikipedia - Glaucus atlanticus"),
        ("The Arctic cetacean whose males possess a spiraling ivory tusk that is actually an elongated canine tooth.", "Narwhal", ["monodon monoceros"], "Wikipedia - Narwhal"),
        ("The unique reflective layer behind the retina in many nocturnal animals that causes their eyes to shine in the dark.", "Tapetum Lucidum", ["tapetum"], "Wikipedia - Tapetum lucidum"),
        ("The Australian reptile that runs on hind legs and displays a large colorful neck frill when threatened.", "Frilled Lizard", ["chlamydosaurus kingii"], "Wikipedia - Frilled lizard")
    ]
    q500 = [
        ("The extraordinary deep-sea sponge that lives up to 15,000 years, making it the longest-living animal on Earth.", "Glass Sponge", ["monorhaphis chuni", "hexactinellid"], "Wikipedia - Hexactinellid"),
        ("The marine worm possessing red hemoglobin blood that thrives inside methane ice clathrates at the bottom of the Gulf of Mexico.", "Methane Ice Worm", ["hesionococcus", "sirsoe methanicola"], "Wikipedia - Sirsoe methanicola"),
        ("The blind cave salamander native to the subterranean waters of the Dinaric Alps that can survive 10 years without food.", "Olm", ["proteus anguinus"], "Wikipedia - Olm"),
        ("The small deep-sea teleost fish with a completely transparent fluid-filled head dome through which its tubular green eyes gaze upward.", "Barreleye Fish", ["macropinna microstoma"], "Wikipedia - Barreleye"),
        ("The biological term for the phenomenon where an organism retains juvenile larval characteristics into reproductive adulthood.", "Neoteny", ["paedomorphism"], "Wikipedia - Neoteny"),
        ("The order of primitive winged insects containing mayflies, characterized by having an intermediate winged subimago stage.", "Ephemeroptera", ["mayflies"], "Wikipedia - Mayfly"),
        ("The venomous mammal native to Cuba and Hispaniola that delivers toxic saliva through grooved incisors.", "Solenodon", ["hispaniolan solenodon"], "Wikipedia - Solenodon"),
        ("The extinct flightless bird related to pigeons that was wiped out on the island of Mauritius in the 17th century.", "Dodo", ["raphus cucullatus"], "Wikipedia - Dodo"),
        ("The specialized organ in male platypuses located on the hind ankles that delivers excruciatingly painful venom.", "Calcaneus Spur", ["crural gland spur"], "Wikipedia - Platypus venom"),
        ("The genus of photosynthetic sea slugs that ingest algae and incorporate active chloroplasts into their own digestive cells.", "Elysia chlorotica", ["solar-powered sea slug", "kleptoplasty"], "Wikipedia - Elysia chlorotica"),
        ("The bizarre South American hoatzin bird whose juvenile chicks possess this prehistoric reptilian feature on their wings.", "Wing Claws", ["functional claws on wings"], "Wikipedia - Hoatzin"),
        ("The biological class of marine parasites that chemically castrate crabs and take over their hormonal behavior.", "Rhizocephala", ["sacculina"], "Wikipedia - Sacculina"),
        ("The extinct apex marine predator of the Ordovician period, a cephalopod that grew conical shells up to 20 feet long.", "Cameroceras", ["endoceras"], "Wikipedia - Cameroceras"),
        ("The deep-sea decapod crustacean discovered in 2005 near Easter Island covered in silky blond setae harboring bacteria.", "Yeti Crab", ["kiwa hirsuta"], "Wikipedia - Kiwa hirsuta"),
        ("The parasitic protozoan that manipulates the brains of infected rodents to become sexually attracted to cat urine scent.", "Toxoplasma gondii", ["toxoplasmosis"], "Wikipedia - Toxoplasma gondii"),
        ("The primitive deep-sea lobe-finned fish thought to have gone extinct 66 million years ago until rediscovered off South Africa in 1938.", "Coelacanth", ["latimeria chalumnae"], "Wikipedia - Coelacanth"),
        ("The deep-sea hydrothermal worm that can survive water temperatures up to 80°C (176°F), making it the most heat-tolerant animal.", "Pompeii Worm", ["alvinella pompejana"], "Wikipedia - Pompeii worm"),
        ("The specialized respiratory organ in labyrinth fish that allows them to extract oxygen directly from atmospheric air.", "Labyrinth Organ", ["labyrinth organ"], "Wikipedia - Anabantoidei"),
        ("The Antarctic fish family that has clear blood lacking hemoglobin, surviving near-freezing seas using antifreeze glycopeptides.", "Crocodile Icefish", ["channichthyidae"], "Wikipedia - Channichthyidae"),
        ("The microscopic animal that reproduces entirely via parthenogenesis for over 40 million years without a single male.", "Bdelloid Rotifer", ["bdelloids"], "Wikipedia - Bdelloidea")
    ]
    return make_tier_items(100, q100) + make_tier_items(200, q200) + make_tier_items(300, q300) + make_tier_items(400, q400) + make_tier_items(500, q500)

def get_food_data():
    q100 = [
        ("The Italian baked flatbread crust topped with tomato sauce, mozzarella, and basil representing the Italian flag.", "Pizza", ["margherita pizza"], "Wikipedia - Pizza"),
        ("The beloved confectionery food product made from roasted and ground cacao seeds.", "Chocolate", ["cacao", "cocoa"], "Wikipedia - Chocolate"),
        ("The Mexican dip made from mashed ripe avocados, salt, lime juice, and cilantro.", "Guacamole", ["guac"], "Wikipedia - Guacamole"),
        ("The fermented vegetable dish consisting primarily of salted napa cabbage, a national staple of Korea.", "Kimchi", ["kimchee"], "Wikipedia - Kimchi"),
        ("The Japanese dish of prepared vinegared rice accompanied by raw seafood, vegetables, and nori seaweed.", "Sushi", ["sashimi"], "Wikipedia - Sushi"),
        ("The golden-yellow dairy spread produced by churning fermented cream or milk.", "Butter", ["dairy butter"], "Wikipedia - Butter"),
        ("The sweet viscous food substance made by bees from the floral nectar of plants.", "Honey", ["natural honey"], "Wikipedia - Honey"),
        ("The basic staple food prepared from a dough of flour and water, baked in loaves.", "Bread", ["white bread", "wheat bread"], "Wikipedia - Bread"),
        ("The Italian pasta dish featuring flat pasta sheets layered with meat sauce, béchamel, and cheese.", "Lasagna", ["lasagne"], "Wikipedia - Lasagna"),
        ("The aromatic brown hot beverage brewed from roasted coffee beans.", "Coffee", ["espresso", "coffee brew"], "Wikipedia - Coffee"),
        ("The popular steeped beverage made by pouring hot water over cured Camellia sinensis leaves.", "Tea", ["black tea", "green tea"], "Wikipedia - Tea"),
        ("The popular yellow curved fruit that grows in hanging clusters and is rich in potassium.", "Banana", ["bananas"], "Wikipedia - Banana"),
        ("The primary white crystallization sweetener derived from sugarcane or sugar beets.", "Sugar", ["sucrose", "table sugar"], "Wikipedia - Sugar"),
        ("The common condiment made by grinding dried peppercorns, traditionally paired with salt.", "Black Pepper", ["pepper"], "Wikipedia - Black pepper"),
        ("The French pastry made of laminated dough rolled into a crescent shape.", "Croissant", ["croissants"], "Wikipedia - Croissant"),
        ("The spherical fruit of the citrus family known for its sweet juice and vitamin C.", "Orange", ["citrus orange"], "Wikipedia - Orange (fruit)"),
        ("The grain that is the primary dietary staple for more than half of the world's human population.", "Rice", ["white rice", "brown rice"], "Wikipedia - Rice"),
        ("The Italian frozen dessert made with a higher proportion of milk to cream, churned at a slower speed than ice cream.", "Gelato", ["italian gelato"], "Wikipedia - Gelato"),
        ("The spicy Mexican corn tortilla folded around a filling of seasoned meat, beans, or cheese.", "Taco", ["tacos"], "Wikipedia - Taco"),
        ("The essential mineral seasoning composed primarily of sodium chloride.", "Salt", ["table salt", "nacl"], "Wikipedia - Salt")
    ]
    q200 = [
        ("The prized and most expensive culinary spice by weight, hand-harvested from the stigmas of the purple crocus.", "Saffron", ["crocus sativus"], "Wikipedia - Saffron"),
        ("The Japanese fermented soybean paste dissolved in dashi broth with seaweed and tofu.", "Miso", ["miso soup"], "Wikipedia - Miso"),
        ("The brined curd cheese traditionally made from sheep's and goat's milk, essential to Greek salad.", "Feta", ["feta cheese"], "Wikipedia - Feta"),
        ("The famous Italian dessert made of ladyfingers dipped in espresso, layered with whipped mascarpone and cocoa.", "Tiramisu", ["tiramisù"], "Wikipedia - Tiramisu"),
        ("The French cooking technique where food is placed in a plastic pouch and cooked in a temperature-controlled water bath.", "Sous-vide", ["sous vide"], "Wikipedia - Sous-vide"),
        ("The pungent, subterranean fungus gathered with trained pigs or dogs, highly valued in fine dining.", "Truffle", ["black truffle", "white truffle"], "Wikipedia - Truffle"),
        ("The Spanish rice dish originating from Valencia, traditionally flavored with saffron and cooked in a wide pan.", "Paella", ["valencian paella"], "Wikipedia - Paella"),
        ("The Japanese delicacy prepared from deadly pufferfish that requires certified chefs to remove lethal tetrodotoxin.", "Fugu", ["pufferfish fugu"], "Wikipedia - Fugu"),
        ("The Italian pasta sauce made by emulsifying egg yolks, Pecorino Romano, guanciale, and black pepper (no cream).", "Carbonara", ["spaghetti alla carbonara"], "Wikipedia - Carbonara"),
        ("The Vietnamese street food sandwich made on a French baguette with pâté, pickled daikon, cucumber, and meats.", "Banh mi", ["bánh mì"], "Wikipedia - Bánh mì"),
        ("The sweet spread made from roasted hazelnuts and cocoa created by Italian confectionery maker Ferrero.", "Nutella", ["hazelnut spread"], "Wikipedia - Nutella"),
        ("The classic French stew of beef braised in red wine, lardons, pearl onions, and mushrooms.", "Boeuf Bourguignon", ["beef bourguignon"], "Wikipedia - Beef bourguignon"),
        ("The spicy Thai soup flavored with fragrant lemongrass, galangal, kaffir lime leaves, chili, and shrimp.", "Tom Yum", ["tom yam"], "Wikipedia - Tom yum"),
        ("The hard Italian granular cheese aged for a minimum of 12 months, stamped with DOP seal.", "Parmigiano-Reggiano", ["parmesan cheese", "parmigiano"], "Wikipedia - Parmesan"),
        ("The French Mother Sauce made from a white roux and warm milk, seasoned with nutmeg.", "Bechamel", ["béchamel sauce", "white sauce"], "Wikipedia - Béchamel sauce"),
        ("The traditional Mexican holiday sauce featuring dozens of ingredients including chili peppers and dark chocolate.", "Mole", ["mole poblano"], "Wikipedia - Mole (sauce)"),
        ("The rich duck or goose liver pâté delicacy originating in French gastronomy, made through fattening.", "Foie Gras", ["foie gras"], "Wikipedia - Foie gras"),
        ("The Japanese noodles made from buckwheat flour, served either chilled with dipping sauce or in hot broth.", "Soba", ["soba noodles"], "Wikipedia - Soba"),
        ("The Italian cured ham made from the hind leg, dry-cured for up to 36 months and thinly sliced.", "Prosciutto", ["prosciutto di parma"], "Wikipedia - Prosciutto"),
        ("The Indian clay oven used to bake flatbreads like naan and roast marinated chicken.", "Tandoor", ["tandoori oven"], "Wikipedia - Tandoor")
    ]
    q300 = [
        ("The highly prized Japanese beef known for intense marbling of intramuscular fat, raised in Hyogo Prefecture.", "Kobe Beef", ["wagyu", "kobe"], "Wikipedia - Kobe beef"),
        ("The five Mother Sauces codified by Auguste Escoffier: Béchamel, Velouté, Espagnole, Tomato, and this egg-yolk emulsified sauce.", "Hollandaise", ["hollandaise sauce"], "Wikipedia - French mother sauces"),
        ("The French puff pastry dessert layered with pastry cream, whose name translates literally to 'a thousand leaves'.", "Mille-feuille", ["napoleon pastry"], "Wikipedia - Mille-feuille"),
        ("The culinary reaction between reducing sugars and amino acids that produces browned food and savory flavors.", "Maillard Reaction", ["maillard browning"], "Wikipedia - Maillard reaction"),
        ("The pungent, foul-smelling tropical fruit native to Southeast Asia known as the 'King of Fruits', banned on public transit.", "Durian", ["durian fruit"], "Wikipedia - Durian"),
        ("The Georgian baked boat-shaped bread filled with melted sulguni cheese and a raw egg yolk in the center.", "Khachapuri", ["adjarian khachapuri"], "Wikipedia - Khachapuri"),
        ("The Ethiopian flatbread made from fermented teff flour, serving as both food and utensil.", "Injera", ["teff injera"], "Wikipedia - Injera"),
        ("The French pastry consisting of choux dough balls piled into a cone and bound with spun caramelized sugar.", "Croquembouche", ["croque-en-bouche"], "Wikipedia - Croquembouche"),
        ("The North African stew of lamb, chicken, or vegetables cooked in a conical earthenware pot of the same name.", "Tagine", ["tajine"], "Wikipedia - Tagine"),
        ("The Italian cured pork meat prepared from the pork jowl or cheek, essential to authentic carbonara and amatriciana.", "Guanciale", ["pork jowl"], "Wikipedia - Guanciale"),
        ("The traditional Peruvian dish of fresh raw fish cured in citrus juices and spiced with ají chili peppers.", "Ceviche", ["cebiche"], "Wikipedia - Ceviche"),
        ("The method of preserving duck or goose meat by salting and slowly cooking it submerged in its own rendered fat.", "Confit", ["duck confit"], "Wikipedia - Confit"),
        ("The French soup originating in Marseille made from various Mediterranean fish, saffron, and fennel.", "Bouillabaisse", ["marseille bouillabaisse"], "Wikipedia - Bouillabaisse"),
        ("The spicy Korean fermented red chili paste made with glutinous rice and fermented soybeans.", "Gochujang", ["korean chili paste"], "Wikipedia - Gochujang"),
        ("The Italian rice dish cooked gradually by stirring hot broth into arborio or carnaroli rice until creamy.", "Risotto", ["risotto alla milanese"], "Wikipedia - Risotto"),
        ("The classic Indian rice dish layered with spiced marinated meats, caramelized onions, saffron, and boiled eggs.", "Biryani", ["dum biryani"], "Wikipedia - Biryani"),
        ("The blue-veined cheese produced in the natural Combalou caves of Roquefort-sur-Soulzon from sheep's milk.", "Roquefort", ["roquefort cheese"], "Wikipedia - Roquefort"),
        ("The rich egg yolk and butter reduction sauce seasoned with tarragon and shallots, served with steak.", "Bearnaise", ["béarnaise sauce"], "Wikipedia - Béarnaise sauce"),
        ("The English dessert consisting of bananas, whipped cream, and boiled condensed milk toffee on a biscuit crust.", "Banoffee Pie", ["banoffee"], "Wikipedia - Banoffee pie"),
        ("The Jewish culinary pastry made of sweet laminated yeast dough twisted with chocolate or cinnamon filling.", "Babka", ["chocolate babka"], "Wikipedia - Babka")
    ]
    q400 = [
        ("The complex culinary technique of clarification that uses whipped egg whites to clear stock into a pristine clear soup.", "Consomme", ["consommé"], "Wikipedia - Consommé"),
        ("The French dessert consisting of rich custard topped with a contrasting layer of caramelized sugar torched hard.", "Creme Brulee", ["crème brûlée"], "Wikipedia - Crème brûlée"),
        ("The ancient fermented fish sauce that was an indispensable umami seasoning in Ancient Roman cooking.", "Garum", ["liquamen"], "Wikipedia - Garum"),
        ("The Spanish dry-cured ham produced from free-range black Iberian pigs that roam oak forests feeding on acorns.", "Jamon Iberico", ["jamón ibérico de bellota"], "Wikipedia - Jamón ibérico"),
        ("The traditional Scottish savory pudding containing sheep's pluck (heart, liver, lungs) minced with suet and oatmeal.", "Haggis", ["scottish haggis"], "Wikipedia - Haggis"),
        ("The chemical compound responsible for the fiery heat of chili peppers, measured on the Scoville scale.", "Capsaicin", ["capsaicinoids"], "Wikipedia - Capsaicin"),
        ("The French term for the disciplined preparation and organization of all ingredients and tools before cooking begins.", "Mise en place", ["mise-en-place"], "Wikipedia - Mise en place"),
        ("The traditional Italian dessert originating from Piedmont made of sweetened cream thickened with gelatin.", "Panna Cotta", ["cooked cream"], "Wikipedia - Panna cotta"),
        ("The technique of rolling meat or fish tightly with a savory stuffing and tying it with butchers twine before roasting.", "Roulade", ["braciole"], "Wikipedia - Roulade"),
        ("The Italian digestif liqueur produced in Southern Italy by steeping the zest of Sorrento lemons in alcohol.", "Limoncello", ["lemon liqueur"], "Wikipedia - Limoncello"),
        ("The pungent, sulfurous fermented shark meat traditional in Iceland that is buried underground for months.", "Hakarl", ["hákarl"], "Wikipedia - Hákarl"),
        ("The French term for a mixture of chopped diced vegetables: 50% onions, 25% carrots, and 25% celery.", "Mirepoix", ["mirepoix base"], "Wikipedia - Mirepoix"),
        ("The Greek dessert composed of paper-thin layers of filo pastry filled with chopped nuts and sweetened with honey.", "Baklava", ["baklawa"], "Wikipedia - Baklava"),
        ("The Japanese cooking technique of skewering bite-sized pieces of chicken and grilling them over binchotan charcoal.", "Yakitori", ["yakitori skewers"], "Wikipedia - Yakitori"),
        ("The traditional French stew of white beans slowly simmered with pork sausages, pork skin, and duck confit.", "Cassoulet", ["castelnaudary cassoulet"], "Wikipedia - Cassoulet"),
        ("The ancient cheese produced in Sardinia that contains live insect larvae (cheese skips) to promote extreme fermentation.", "Casu marzu", ["casu martzu", "maggot cheese"], "Wikipedia - Casu martzu"),
        ("The French cold leek and potato soup pureed with cream, named after the spa town of Vichy.", "Vichyssoise", ["vichyssoise soup"], "Wikipedia - Vichyssoise"),
        ("The traditional Mexican soup made with hominy corn, shredded pork or chicken, cabbage, radishes, and chili.", "Pozole", ["pozole verde", "pozole rojo"], "Wikipedia - Pozole"),
        ("The small, colorful French sandwich cookie made from almond flour, egg whites, and confectioner's sugar.", "Macaron", ["french macaron"], "Wikipedia - Macaron"),
        ("The hot sauce condiment of Tunisian origin made of roasted red peppers, Baklouti peppers, garlic, and caraway.", "Harissa", ["harissa paste"], "Wikipedia - Harissa")
    ]
    q500 = [
        ("The rare Iranian beluga caviar harvested from albino sturgeon over 70 years old, sold in 24-karat gold tins.", "Almas", ["almas caviar"], "Wikipedia - Caviar"),
        ("The Japanese master chef title earned only after a minimum of ten years of rigorous apprenticeship.", "Itamae", ["sushi shokunin"], "Wikipedia - Itamae"),
        ("The chemical process invented by Ferran Adrià at elBulli using sodium alginate and calcium chloride to create caviar-like liquid spheres.", "Spherification", ["molecular gastronomy spherification"], "Wikipedia - Spherification"),
        ("The traditional Italian condiment from Emilia-Romagna aged for a minimum of 12 to 25 years in a battery of wooden casks.", "Traditional Balsamic Vinegar", ["aceto balsamico tradizionale"], "Wikipedia - Traditional balsamic vinegar"),
        ("The legendary Roman chef whose 1st-century culinary manuscript 'De Re Coquinaria' survives as the oldest cookbook.", "Apicius", ["marcus gavius apicius"], "Wikipedia - Apicius"),
        ("The rare subterranean white truffle species harvested around the Piedmontese town of Alba in autumn.", "Tuber magnatum", ["tartufo bianco d'alba", "white truffle"], "Wikipedia - Tuber magnatum"),
        ("The ancient French culinary dish where a small songbird is fattened on millet, drowned in Armagnac, and eaten whole under a napkin.", "Ortolan Bunting", ["ortolan"], "Wikipedia - Ortolan bunting"),
        ("The natural red food dye extracted from the crushed dried bodies of female scale insects found on prickly pear cacti.", "Cochineal", ["carmine", "e120"], "Wikipedia - Cochineal"),
        ("The historical French chef who codified classical French haute cuisine and was hailed as 'The Emperor of Chefs'.", "Auguste Escoffier", ["escoffier"], "Wikipedia - Auguste Escoffier"),
        ("The chemical odorant synthesized by truffles (and pigs) responsible for their intoxicating, earthy aroma.", "Androstenol", ["bis(methylthio)methane"], "Wikipedia - Truffle"),
        ("The complex French pastry cake named after the French patron saint of bakers and pastry chefs, featuring choux buns and Chiboust cream.", "Gateau Saint Honore", ["st. honoré cake"], "Wikipedia - St. Honoré cake"),
        ("The Japanese seasoning concept describing the synergistic taste enhancement when inosinate and glutamate combine.", "Umami Synergy", ["umami interaction"], "Wikipedia - Umami"),
        ("The ancient fermented fish delicacy of Sweden known for producing a bulging pressurized tin and notorious stench.", "Surstromming", ["surströmming"], "Wikipedia - Surströmming"),
        ("The rare Mexican corn delicacy caused by the fungal infection Ustilago maydis, prized as 'corn truffle'.", "Huitlacoche", ["cuitlacoche"], "Wikipedia - Corn smut"),
        ("The Japanese knife blade forged by folding high-carbon steel and soft iron, replicating samurai sword craftsmanship.", "Honyaki", ["honyaki knife"], "Wikipedia - Japanese kitchen knife"),
        ("The traditional Swiss cow's milk cheese aged in alpine caves and melted onto potatoes using a special tabletop heater.", "Raclette", ["raclette du valais"], "Wikipedia - Raclette"),
        ("The 19th-century French founder of haute cuisine who designed elaborate confectionary centerpieces called 'pièces montées'.", "Marie-Antoine Careme", ["carême", "antonin carême"], "Wikipedia - Marie-Antoine Carême"),
        ("The method of making crystal-clear ice by directional freezing where impurities are pushed to the unfrozen base.", "Directional Freezing", ["clear ice method"], "Wikipedia - Ice"),
        ("The complex traditional British sheep's milk cheese bound in cloth and lard, aged for up to two years.", "Clothbound Cheddar", ["traditional farm cheddar"], "Wikipedia - Cheddar cheese"),
        ("The rare wild citrus fruit from the Australian rainforest with finger-like vesicles that burst with acidic lime caviar.", "Finger Lime", ["citrus australasica", "caviar lime"], "Wikipedia - Citrus australasica")
    ]
    return make_tier_items(100, q100) + make_tier_items(200, q200) + make_tier_items(300, q300) + make_tier_items(400, q400) + make_tier_items(500, q500)

print("All category data functions loaded successfully!")
