# World History (200 questions: 40 per tier: 100, 200, 300, 400, 500)

def get_history_questions():
    items = []

    # --- $100: Novice / Iconic Moments & Figures (40 items) ---
    q100 = [
        ("The first President of the United States, hailed as the 'Father of His Country'.", "George Washington", ["washington"], "Wikipedia - George Washington"),
        ("The ancient wonder in Egypt built for Pharaoh Khufu around 2560 BC.", "Great Pyramid of Giza", ["pyramid of giza", "great pyramid"], "Wikipedia - Great Pyramid of Giza"),
        ("In 1969, this American Apollo 11 astronaut became the first person to step on the Moon.", "Neil Armstrong", ["armstrong"], "Wikipedia - Apollo 11"),
        ("The year Christopher Columbus made his first voyage across the Atlantic to the Americas.", "1492", ["year 1492"], "Wikipedia - Christopher Columbus"),
        ("The wall that divided East and West Berlin from 1961 until its historic fall in 1989.", "The Berlin Wall", ["berlin wall", "berliner mauer"], "Wikipedia - Berlin Wall"),
        ("The English king who broke with Rome to marry Anne Boleyn and had six wives.", "Henry VIII", ["henry the eighth", "king henry viii"], "Wikipedia - Henry VIII"),
        ("The Roman general and dictator assassinated on the Ides of March in 44 BC.", "Julius Caesar", ["caesar"], "Wikipedia - Julius Caesar"),
        ("The ship that carried the Pilgrims from England to Plymouth, Massachusetts in 1620.", "Mayflower", ["the mayflower"], "Wikipedia - Mayflower"),
        ("The French military leader who crowned himself Emperor and conquered much of Europe before Waterloo.", "Napoleon Bonaparte", ["napoleon", "bonaparte"], "Wikipedia - Napoleon"),
        ("The document adopted on July 4, 1776 declaring the thirteen American colonies free from Great Britain.", "Declaration of Independence", ["the declaration of independence"], "Wikipedia - Declaration of Independence"),
        ("The civilization that built Machu Picchu in the Andes mountains of Peru.", "Inca Empire", ["the incas", "inca"], "Wikipedia - Inca Empire"),
        ("The British passenger liner that sank on April 15, 1912 after striking an iceberg in the North Atlantic.", "Titanic", ["rms titanic"], "Wikipedia - Titanic"),
        ("The 16th US President who issued the Emancipation Proclamation and was assassinated by John Wilkes Booth.", "Abraham Lincoln", ["lincoln"], "Wikipedia - Abraham Lincoln"),
        ("The South African anti-apartheid leader who served 27 years in prison before becoming President in 1994.", "Nelson Mandela", ["mandela"], "Wikipedia - Nelson Mandela"),
        ("The ancient civilization centered along the Nile River known for pharaohs and hieroglyphics.", "Ancient Egypt", ["egyptians", "egypt"], "Wikipedia - Ancient Egypt"),
        ("The leader of the Indian independence movement who championed nonviolent civil disobedience.", "Mahatma Gandhi", ["gandhi", "mohandas gandhi"], "Wikipedia - Mahatma Gandhi"),
        ("The catastrophic pandemic caused by Yersinia pestis that swept Eurasia in the 1340s.", "The Black Death", ["black plague", "bubonic plague"], "Wikipedia - Black Death"),
        ("The German dictator who led the Nazi Party and initiated World War II and the Holocaust.", "Adolf Hitler", ["hitler"], "Wikipedia - Adolf Hitler"),
        ("The year the United States Constitution was signed in Philadelphia.", "1787", ["year 1787"], "Wikipedia - United States Constitution"),
        ("The queen of the United Kingdom who reigned for 63 years during the height of the British Empire.", "Queen Victoria", ["victoria"], "Wikipedia - Queen Victoria"),
        ("The ancient trade route network linking China and the Mediterranean.", "Silk Road", ["the silk road"], "Wikipedia - Silk Road"),
        ("The Japanese military attack on this US naval base on December 7, 1941 brought America into WWII.", "Pearl Harbor", ["pearl harbour"], "Wikipedia - Attack on Pearl Harbor"),
        ("The city destroyed alongside Herculaneum by the eruption of Mount Vesuvius in 79 AD.", "Pompeii", ["city of pompeii"], "Wikipedia - Pompeii"),
        ("The French heroine who led French troops during the Hundred Years' War and was burned at the stake.", "Joan of Arc", ["jeanne d'arc"], "Wikipedia - Joan of Arc"),
        ("The first civilization in Mesopotamia to develop cuneiform writing.", "Sumerians", ["sumer"], "Wikipedia - Sumer"),
        ("The year the Soviet Union officially dissolved, ending the Cold War.", "1991", ["year 1991"], "Wikipedia - Dissolution of the Soviet Union"),
        ("The war between the Union states of the North and the Confederacy of the South from 1861 to 1865.", "American Civil War", ["the civil war", "us civil war"], "Wikipedia - American Civil War"),
        ("The leader of the Bolshevik party who led the October Revolution of 1917 in Russia.", "Vladimir Lenin", ["lenin"], "Wikipedia - Vladimir Lenin"),
        ("The ancient city-state in Greece famous for its fierce militaristic warrior society.", "Sparta", ["spartans"], "Wikipedia - Sparta"),
        ("The naval battle in 1805 where Admiral Lord Nelson was killed while defeating the French and Spanish fleets.", "Battle of Trafalgar", ["trafalgar"], "Wikipedia - Battle of Trafalgar"),
        ("The year the First World War ended with the signing of the armistice on November 11.", "1918", ["year 1918"], "Wikipedia - Armistice of 11 November 1918"),
        ("The English queen who defeated the Spanish Armada in 1588, known as the 'Virgin Queen'.", "Elizabeth I", ["queen elizabeth i", "elizabeth 1"], "Wikipedia - Elizabeth I"),
        ("The medieval military expeditions undertaken by European Christians to recover the Holy Land from Muslim rule.", "The Crusades", ["crusades"], "Wikipedia - Crusades"),
        ("The Japanese city devastated by the first wartime atomic bomb, 'Little Boy', on August 6, 1945.", "Hiroshima", ["city of hiroshima"], "Wikipedia - Atomic bombings of Hiroshima and Nagasaki"),
        ("The treaty signed in 1919 in France that formally concluded World War I.", "Treaty of Versailles", ["versailles treaty"], "Wikipedia - Treaty of Versailles"),
        ("The code name for the June 6, 1944 Allied amphibious landings on the beaches of Normandy.", "D-Day", ["operation overlord", "normandy landings"], "Wikipedia - Normandy landings"),
        ("The explorer who led the first expedition that successfully circumnavigated the globe (1519-1522).", "Ferdinand Magellan", ["magellan"], "Wikipedia - Ferdinand Magellan"),
        ("The ancient wonder of Babylon famous for tiered terraced gardens planted by King Nebuchadnezzar II.", "Hanging Gardens of Babylon", ["hanging gardens"], "Wikipedia - Hanging Gardens of Babylon"),
        ("The first human in space, who orbited the Earth aboard Vostok 1 on April 12, 1961.", "Yuri Gagarin", ["gagarin"], "Wikipedia - Yuri Gagarin"),
        ("The prison fortress in Paris stormed by revolutionary crowds on July 14, 1789.", "The Bastille", ["bastille"], "Wikipedia - Storming of the Bastille")
    ]
    for c, a, ac, s in q100: items.append((100, c, a, ac, s))

    # --- $200: Moderate / Key Historical Milestones (40 items) ---
    q200 = [
        ("The charter granted by King John of England at Runnymede in 1215 establishing principles of liberty.", "Magna Carta", ["the great charter"], "Wikipedia - Magna Carta"),
        ("The conflict between the House of Lancaster and the House of York for the English throne.", "Wars of the Roses", ["war of the roses"], "Wikipedia - Wars of the Roses"),
        ("The Mongol chieftain who united the nomadic tribes to establish the Mongol Empire in 1206.", "Genghis Khan", ["chinggis khan", "temüjin"], "Wikipedia - Genghis Khan"),
        ("The decisive 1815 battle in modern Belgium where the Duke of Wellington defeated Napoleon.", "Battle of Waterloo", ["waterloo"], "Wikipedia - Battle of Waterloo"),
        ("The conflict between Athens and the Peloponnesian League led by Sparta (431-404 BC).", "Peloponnesian War", ["the peloponnesian war"], "Wikipedia - Peloponnesian War"),
        ("The German monk who initiated the Protestant Reformation by posting his 95 Theses in 1517.", "Martin Luther", ["luther"], "Wikipedia - Martin Luther"),
        ("The first European to discover and print with movable metal type in the 1450s.", "Johannes Gutenberg", ["gutenberg"], "Wikipedia - Johannes Gutenberg"),
        ("The series of three wars fought between Rome and Carthage from 264 BC to 146 BC.", "Punic Wars", ["the punic wars"], "Wikipedia - Punic Wars"),
        ("The Carthaginian general who led war elephants across the Alps into Italy during the Second Punic War.", "Hannibal", ["hannibal barca"], "Wikipedia - Hannibal"),
        ("The Mesozoic empire conquered by Spanish conquistador Hernán Cortés in 1521.", "Aztec Empire", ["aztecs", "mexica"], "Wikipedia - Spanish conquest of the Aztec Empire"),
        ("The Spanish conquistador who conquered the Inca Empire and captured Emperor Atahualpa.", "Francisco Pizarro", ["pizarro"], "Wikipedia - Francisco Pizarro"),
        ("The last reigning monarch of the Kingdom of Hawaii, overthrown in 1893.", "Queen Liliuokalani", ["liliuokalani"], "Wikipedia - Liliuokalani"),
        ("The Russian dynasty that ruled for three centuries from 1613 until the 1917 revolution.", "Romanov Dynasty", ["house of romanov", "the romanovs"], "Wikipedia - House of Romanov"),
        ("The 1863 battle in Pennsylvania considered the turning point of the American Civil War.", "Battle of Gettysburg", ["gettysburg"], "Wikipedia - Battle of Gettysburg"),
        ("The Roman Emperor who legalized Christianity across the empire with the Edict of Milan in 313 AD.", "Constantine the Great", ["constantine i", "constantine"], "Wikipedia - Constantine the Great"),
        ("The series of military conflicts fought between Britain and Qing-dynasty China over trade rights in the 19th century.", "The Opium Wars", ["opium wars"], "Wikipedia - Opium Wars"),
        ("The French king known as the 'Sun King' who ruled for 72 years and built the Palace of Versailles.", "Louis XIV", ["louis the fourteenth", "sun king"], "Wikipedia - Louis XIV"),
        ("The English philosopher whose Two Treatises of Government heavily influenced the American Founding Fathers.", "John Locke", ["locke"], "Wikipedia - John Locke"),
        ("The 1962 confrontation between the United States and the Soviet Union over nuclear missiles installed in Cuba.", "Cuban Missile Crisis", ["october crisis"], "Wikipedia - Cuban Missile Crisis"),
        ("The 1066 battle in England where William the Conqueror defeated King Harold Godwinson.", "Battle of Hastings", ["hastings"], "Wikipedia - Battle of Hastings"),
        ("The treaty signed in 1494 that divided the newly discovered lands outside Europe between Portugal and Spain.", "Treaty of Tordesillas", ["tordesillas"], "Wikipedia - Treaty of Tordesillas"),
        ("The 1942 naval battle in the Pacific where the US Navy destroyed four Japanese aircraft carriers, turning the war.", "Battle of Midway", ["midway"], "Wikipedia - Battle of Midway"),
        ("The Ottoman Sultan who conquered Constantinople in 1453, ending the Byzantine Empire.", "Mehmed II", ["mehmed the conqueror", "fatih sultan mehmed"], "Wikipedia - Mehmed II"),
        ("The secret project in Los Alamos that developed the first atomic weapons during World War II.", "The Manhattan Project", ["manhattan project"], "Wikipedia - Manhattan Project"),
        ("The Chinese dynasty that ruled from 1368 to 1644, renowned for porcelain and building much of the Great Wall.", "Ming Dynasty", ["ming"], "Wikipedia - Ming dynasty"),
        ("The 1930 civil disobedience march led by Mahatma Gandhi to protest the British monopoly on salt.", "Salt March", ["dandi march"], "Wikipedia - Salt March"),
        ("The battle in 732 AD where Charles Martel stopped the northward advance of the Umayyad Caliphate in France.", "Battle of Tours", ["battle of poitiers"], "Wikipedia - Battle of Tours"),
        ("The 1803 land purchase made by Thomas Jefferson from France that doubled the size of the United States.", "Louisiana Purchase", ["the louisiana purchase"], "Wikipedia - Louisiana Purchase"),
        ("The leader who unified Germany in 1871 and served as its first Imperial Chancellor, the 'Iron Chancellor'.", "Otto von Bismarck", ["bismarck"], "Wikipedia - Otto von Bismarck"),
        ("The 1968 Soviet military invasion that crushed the democratic reforms of the Prague Spring.", "Invasion of Czechoslovakia", ["warsaw pact invasion"], "Wikipedia - Warsaw Pact invasion of Czechoslovakia"),
        ("The Scottish king who defeated the English army at the Battle of Bannockburn in 1314.", "Robert the Bruce", ["robert i"], "Wikipedia - Robert the Bruce"),
        ("The French queen executed by guillotine during the French Revolution, wife of Louis XVI.", "Marie Antoinette", ["marie-antoinette"], "Wikipedia - Marie Antoinette"),
        ("The brutal campaign of political repression and mass executions initiated by Robespierre during the French Revolution.", "Reign of Terror", ["the terror", "la terreur"], "Wikipedia - Reign of Terror"),
        ("The military alliance formed in 1949 by Western nations to provide collective defense against Soviet expansion.", "NATO", ["north atlantic treaty organization"], "Wikipedia - NATO"),
        ("The counter-alliance created by the Soviet Union and Eastern European satellites in 1955.", "Warsaw Pact", ["treaty of warsaw"], "Wikipedia - Warsaw Pact"),
        ("The 1845-1852 mass starvation in Ireland caused by potato blight that killed approximately one million people.", "Irish Potato Famine", ["the great hunger", "an gorta mór"], "Wikipedia - Great Famine (Ireland)"),
        ("The year the Berlin Wall was erected by the German Democratic Republic.", "1961", ["year 1961"], "Wikipedia - Berlin Wall"),
        ("The code name for the 1941 German invasion of the Soviet Union, the largest land invasion in history.", "Operation Barbarossa", ["barbarossa"], "Wikipedia - Operation Barbarossa"),
        ("The 1812 battle near Moscow where Napoleon engaged Kutuzov, chronicled in War and Peace.", "Battle of Borodino", ["borodino"], "Wikipedia - Battle of Borodino"),
        ("The famous telegram sent in 1917 from Germany to Mexico proposing a military alliance, intercepting which brought the US into WWI.", "Zimmermann Telegram", ["zimmermann note"], "Wikipedia - Zimmermann Telegram")
    ]
    for c, a, ac, s in q200: items.append((200, c, a, ac, s))

    # --- $300: Intermediate / Treaties, Revolutions & Dynasties (40 items) ---
    q300 = [
        ("The 1648 peace treaties that ended the Thirty Years' War in the Holy Roman Empire, establishing modern sovereignty.", "Peace of Westphalia", ["treaty of westphalia"], "Wikipedia - Peace of Westphalia"),
        ("The Venetian merchant who traveled the Silk Road to China and served in the court of Kublai Khan.", "Marco Polo", ["polo"], "Wikipedia - Marco Polo"),
        ("The series of civil wars in England from 1642 to 1651 culminating in the trial and execution of King Charles I.", "English Civil War", ["the english civil war"], "Wikipedia - English Civil War"),
        ("The Lord Protector who ruled the Commonwealth of England, Scotland, and Ireland after the execution of Charles I.", "Oliver Cromwell", ["cromwell"], "Wikipedia - Oliver Cromwell"),
        ("The 1916 naval engagement between the British Grand Fleet and German High Seas Fleet, the largest battleship clash.", "Battle of Jutland", ["skagerrakschlacht"], "Wikipedia - Battle of Jutland"),
        ("The 1853-1856 conflict where Britain, France, and the Ottoman Empire fought the Russian Empire on the Black Sea.", "Crimean War", ["the crimean war"], "Wikipedia - Crimean War"),
        ("The British nurse whose pioneering work in the Crimean War established modern nursing.", "Florence Nightingale", ["nightingale", "lady with the lamp"], "Wikipedia - Florence Nightingale"),
        ("The 1937 aerial bombing of this Basque town by the German Luftwaffe during the Spanish Civil War inspired Picasso's painting.", "Guernica", ["town of guernica"], "Wikipedia - Bombing of Guernica"),
        ("The Austrian archduke whose assassination in Sarajevo on June 28, 1914 triggered World War I.", "Franz Ferdinand", ["archduke franz ferdinand"], "Wikipedia - Assassination of Archduke Franz Ferdinand"),
        ("The Bosnian-Serb nationalist who shot Archduke Franz Ferdinand and his wife Sophie.", "Gavrilo Princip", ["princip"], "Wikipedia - Gavrilo Princip"),
        ("The 1938 British Prime Minister who signed the Munich Agreement and proclaimed 'peace for our time'.", "Neville Chamberlain", ["chamberlain"], "Wikipedia - Neville Chamberlain"),
        ("The 1836 siege in San Antonio, Texas where 180 defenders including Davy Crockett fell to Mexican forces.", "The Alamo", ["battle of the alamo"], "Wikipedia - Battle of the Alamo"),
        ("The Mexican general and president who recaptured the Alamo in 1836.", "Antonio Lopez de Santa Anna", ["santa anna"], "Wikipedia - Antonio López de Santa Anna"),
        ("The 1805 battle where Napoleon defeated the combined Russo-Austrian armies, considered his tactical masterpiece.", "Battle of Austerlitz", ["battle of the three emperors", "austerlitz"], "Wikipedia - Battle of Austerlitz"),
        ("The 1879 conflict between the British Empire and the Zulu Kingdom made famous by the battles of Isandlwana and Rorke's Drift.", "Anglo-Zulu War", ["zulu war"], "Wikipedia - Anglo-Zulu War"),
        ("The Portuguese prince nicknamed 'The Navigator' who launched the Age of Discoveries.", "Prince Henry the Navigator", ["henry the navigator", "infante dom henrique"], "Wikipedia - Prince Henry the Navigator"),
        ("The 1943 naval-air battle in the Solomon Islands where American fighters ambushed and killed Admiral Isoroku Yamamoto.", "Operation Vengeance", ["death of yamamoto"], "Wikipedia - Operation Vengeance"),
        ("The Roman Emperor who constructed a 73-mile defensive stone wall across northern Britannia in 122 AD.", "Hadrian", ["emperor hadrian", "hadrians wall"], "Wikipedia - Hadrian's Wall"),
        ("The German field marshal known as the 'Desert Fox' who commanded the Afrika Korps.", "Erwin Rommel", ["rommel", "desert fox"], "Wikipedia - Erwin Rommel"),
        ("The 1942-1943 battle in southwestern Russia that resulted in the destruction of the German 6th Army, the turning point of WWII in Europe.", "Battle of Stalingrad", ["stalingrad"], "Wikipedia - Battle of Stalingrad"),
        ("The 1867 purchase engineered by Secretary of State William H. Seward that added 586,000 square miles to the US.", "Alaska Purchase", ["seward's folly", "alaska"], "Wikipedia - Alaska Purchase"),
        ("The 1839-1842 war that forced China to cede Hong Kong Island to Great Britain.", "First Opium War", ["first anglo-chinese war"], "Wikipedia - First Opium War"),
        ("The Florentine diplomat who wrote The Prince in 1513, advocating political realism and pragmatic power.", "Niccolo Machiavelli", ["machiavelli"], "Wikipedia - Niccolò Machiavelli"),
        ("The 1923 failed coup d'état carried out by Adolf Hitler and the Nazi Party in Munich.", "Beer Hall Putsch", ["munich putsch"], "Wikipedia - Beer Hall Putsch"),
        ("The ancient Persian king who founded the Achaemenid Empire and issued the Cyrus Cylinder on human rights.", "Cyrus the Great", ["cyrus ii"], "Wikipedia - Cyrus the Great"),
        ("The 1916 battle on the Western Front that saw the first operational use of tanks by the British Army.", "Battle of the Somme", ["the somme"], "Wikipedia - Battle of the Somme"),
        ("The 1868 political event in Japan that ended the Tokugawa shogunate and restored imperial rule.", "Meiji Restoration", ["meiji isshin"], "Wikipedia - Meiji Restoration"),
        ("The 1773 protest in Boston where the Sons of Liberty dumped 342 chests of British tea into the harbor.", "Boston Tea Party", ["the tea party"], "Wikipedia - Boston Tea Party"),
        ("The 1945 conference where Churchill, Roosevelt, and Stalin met in Crimea to plan post-WWII Europe.", "Yalta Conference", ["crimea conference"], "Wikipedia - Yalta Conference"),
        ("The final wartime Allied conference held in Germany in July-August 1945 attended by Truman, Attlee, and Stalin.", "Potsdam Conference", ["berlin conference of the three heads of government"], "Wikipedia - Potsdam Conference"),
        ("The South American revolutionary known as 'El Libertador' who led independence from Spain for six nations.", "Simon Bolivar", ["simón bolívar", "bolivar"], "Wikipedia - Simón Bolívar"),
        ("The Argentine general who liberated Chile alongside Bernardo O'Higgins and declared the independence of Peru.", "Jose de San Martin", ["josé de san martín", "san martin"], "Wikipedia - José de San Martín"),
        ("The 1936-1939 conflict between the Second Spanish Republic and Nationalist forces led by Francisco Franco.", "Spanish Civil War", ["guerra civil española"], "Wikipedia - Spanish Civil War"),
        ("The Spanish general who emerged victorious from the Civil War and ruled Spain as dictator until 1975.", "Francisco Franco", ["franco"], "Wikipedia - Francisco Franco"),
        ("The 1917 declaration by British Foreign Secretary Arthur Balfour expressing support for a national home for the Jewish people.", "Balfour Declaration", ["the balfour declaration"], "Wikipedia - Balfour Declaration"),
        ("The 1804 battle where the Haitian Revolution under Jean-Jacques Dessalines resulted in the first free Black republic.", "Battle of Vertieres", ["haitian independence", "vertières"], "Wikipedia - Haitian Revolution"),
        ("The leader of the Haitian Revolution formerly an enslaved man, known as the 'Black Napoleon'.", "Toussaint Louverture", ["louverture"], "Wikipedia - Toussaint Louverture"),
        ("The 1707 legislative acts that united the Kingdom of England and the Kingdom of Scotland into Great Britain.", "Acts of Union 1707", ["acts of union", "union with scotland act"], "Wikipedia - Acts of Union 1707"),
        ("The mass extermination of an estimated 800,000 Tutsis and moderate Hutus in 1994 over approximately 100 days.", "Rwandan Genocide", ["genocide against the tutsi"], "Wikipedia - Rwandan genocide"),
        ("The 1989 protests in Beijing that were violently crushed by the Chinese military on June 4.", "Tiananmen Square Protests", ["tiananmen square massacre", "june fourth incident"], "Wikipedia - 1989 Tiananmen Square protests and massacre")
    ]
    for c, a, ac, s in q300: items.append((300, c, a, ac, s))

    # --- $400: Advanced / Geopolitics & Epochal Turning Points (40 items) ---
    q400 = [
        ("The 1756-1763 global conflict often termed the true first world war, known in North America as the French and Indian War.", "Seven Years' War", ["seven years war"], "Wikipedia - Seven Years' War"),
        ("The Byzantine Emperor who codified Roman law in the Corpus Juris Civilis and commissioned the Hagia Sophia.", "Justinian I", ["justinian the great", "justinian"], "Wikipedia - Justinian I"),
        ("The 1933 arson fire at the German parliament building that Hitler used to suspend civil liberties.", "Reichstag Fire", ["der reichstagsbrand"], "Wikipedia - Reichstag fire"),
        ("The 1571 naval clash in the Gulf of Patras where the Holy League crushed the Ottoman fleet, halting Mediterranean expansion.", "Battle of Lepanto", ["lepanto"], "Wikipedia - Battle of Lepanto"),
        ("The long-running conflict between the British Empire and the Russian Empire for dominance in Central Asia during the 19th century.", "The Great Game", ["tournament of shadows"], "Wikipedia - The Great Game"),
        ("The 1943 tank clash in Russia involving over 6,000 armored vehicles, the largest tank battle in military history.", "Battle of Kursk", ["kursk"], "Wikipedia - Battle of Kursk"),
        ("The 1898 war that resulted in the US acquiring Puerto Rico, Guam, and the Philippines from Spain.", "Spanish-American War", ["spanish american war"], "Wikipedia - Spanish–American War"),
        ("The US battleship whose mysterious explosion in Havana Harbor on February 15, 1898 ignited the Spanish-American War.", "USS Maine", ["the maine"], "Wikipedia - USS Maine (1889)"),
        ("The 1956 military crisis where Britain, France, and Israel invaded Egypt after Gamal Abdel Nasser nationalized a vital canal.", "Suez Crisis", ["tripartite aggression"], "Wikipedia - Suez Crisis"),
        ("The secret agreement between Britain and France in 1916 that partitioned the Ottoman Empire's Arab provinces.", "Sykes-Picot Agreement", ["sykes picot"], "Wikipedia - Sykes–Picot Agreement"),
        ("The 1904-1905 conflict where an Asian power defeated a European imperial power for the first time in the modern era.", "Russo-Japanese War", ["russo japanese war"], "Wikipedia - Russo-Japanese War"),
        ("The 1905 naval battle in the Korea Strait where Admiral Togo annihilated the Russian Baltic Fleet.", "Battle of Tsushima", ["tsushima"], "Wikipedia - Battle of Tsushima"),
        ("The 1683 siege where King John III Sobieski of Poland led the largest cavalry charge in history to relieve this Austrian capital.", "Siege of Vienna", ["battle of vienna 1683"], "Wikipedia - Battle of Vienna"),
        ("The 1899-1902 war between the British Empire and the two Boer republics (Orange Free State and Transvaal).", "Second Boer War", ["boer war"], "Wikipedia - Second Boer War"),
        ("The 1857 rebellion of Indian soldiers serving under the British East India Company that ended company rule.", "Indian Rebellion of 1857", ["sepoy mutiny", "first war of indian independence"], "Wikipedia - Indian Rebellion of 1857"),
        ("The Swedish king and military genius nicknamed 'The Lion of the North' who revolutionized warfare during the Thirty Years' War.", "Gustavus Adolphus", ["gustav ii adolf"], "Wikipedia - Gustavus Adolphus"),
        ("The 1632 battle where Gustavus Adolphus was killed in combat against Wallenstein.", "Battle of Lutzen", ["battle of lützen"], "Wikipedia - Battle of Lützen (1632)"),
        ("The 1389 battle in Kosovo field where the Ottoman army under Murad I defeated the Serbian coalition under Prince Lazar.", "Battle of Kosovo", ["kosovo polje"], "Wikipedia - Battle of Kosovo"),
        ("The 1526 battle in Hungary where Ottoman Sultan Suleiman the Magnificent decisively defeated King Louis II.", "Battle of Mohacs", ["mohács"], "Wikipedia - Battle of Mohács"),
        ("The 1922 fascist march led by Benito Mussolini that forced King Victor Emmanuel III to appoint him Prime Minister.", "March on Rome", ["marcia su roma"], "Wikipedia - March on Rome"),
        ("The Chinese nationalist leader who retreated to Taiwan in 1949 after losing the civil war to Mao Zedong's Communists.", "Chiang Kai-shek", ["chiang", "jiang jieshi"], "Wikipedia - Chiang Kai-shek"),
        ("The 1866 Seven Weeks' War where Prussia under Moltke defeated Austria, ending Austrian influence in Germany.", "Austro-Prussian War", ["seven weeks war"], "Wikipedia - Austro-Prussian War"),
        ("The 1870-1871 conflict that led to the capture of Napoleon III at Sedan and the unification of Germany.", "Franco-Prussian War", ["franco german war"], "Wikipedia - Franco-Prussian War"),
        ("The 1961 failed CIA-sponsored invasion of Cuba by anti-Castro Cuban exiles.", "Bay of Pigs Invasion", ["playa girón", "bay of pigs"], "Wikipedia - Bay of Pigs Invasion"),
        ("The 1954 siege where Vietnamese forces under General Vo Nguyen Giap defeated the French colonial army, ending the Indochina War.", "Battle of Dien Bien Phu", ["điện biên phủ"], "Wikipedia - Battle of Dien Bien Phu"),
        ("The 1973 war launched on a Jewish holy day when Egypt and Syria attacked Israel in Sinai and the Golan.", "Yom Kippur War", ["october war", "ramadan war"], "Wikipedia - Yom Kippur War"),
        ("The 1967 war where Israel captured the Sinai Peninsula, Gaza Strip, West Bank, Old Jerusalem, and Golan Heights in six days.", "Six-Day War", ["six day war", "1967 war"], "Wikipedia - Six-Day War"),
        ("The 1982 conflict between the United Kingdom and Argentina over two British overseas territories in the South Atlantic.", "Falklands War", ["guerra de las malvinas"], "Wikipedia - Falklands War"),
        ("The 1934-1935 military retreat of the Chinese Red Army covering 5,600 miles over rugged terrain, elevating Mao Zedong.", "The Long March", ["long march"], "Wikipedia - Long March"),
        ("The 1898 confrontation between British and French expeditions at an outpost on the Upper Nile, bringing the two powers to the brink of war.", "Fashoda Incident", ["fashoda crisis"], "Wikipedia - Fashoda Incident"),
        ("The 1688 bloodless coup that deposed King James II of England and replaced him with William III and Mary II.", "Glorious Revolution", ["revolution of 1688"], "Wikipedia - Glorious Revolution"),
        ("The 1863 diplomatic proclamation by Abraham Lincoln that declared all slaves held within rebellious states 'forever free'.", "Emancipation Proclamation", ["the emancipation proclamation"], "Wikipedia - Emancipation Proclamation"),
        ("The 1945 secret operation that brought over 1,600 German scientists and engineers, including Wernher von Braun, to the United States.", "Operation Paperclip", ["project paperclip"], "Wikipedia - Operation Paperclip"),
        ("The 1928 international treaty in which signatory states promised not to use war to resolve disputes.", "Kellogg-Briand Pact", ["pact of paris"], "Wikipedia - Kellogg–Briand Pact"),
        ("The series of peace treaties signed between the Entente and the defeated Central Powers in 1919 and 1920: Versailles, Saint-Germain, Neuilly, Trianon, and this fifth.", "Treaty of Sevres", ["treaty of sèvres"], "Wikipedia - Treaty of Sèvres"),
        ("The 1978 peace accords brokered by Jimmy Carter between Egyptian President Anwar Sadat and Israeli PM Menachem Begin.", "Camp David Accords", ["camp david"], "Wikipedia - Camp David Accords"),
        ("The 1922 treaty that normalized diplomatic relations between the Weimar Republic of Germany and the Soviet Union.", "Treaty of Rapallo", ["rapallo treaty"], "Wikipedia - Treaty of Rapallo (1922)"),
        ("The 1598 edict issued by King Henry IV of France granting religious tolerance to French Calvinist Protestants (Huguenots).", "Edict of Nantes", ["nantes edict"], "Wikipedia - Edict of Nantes"),
        ("The 1685 edict issued by Louis XIV that revoked the Edict of Nantes, triggering a mass exodus of Huguenots.", "Edict of Fontainebleau", ["revocation of the edict of nantes"], "Wikipedia - Edict of Fontainebleau"),
        ("The 1935 legislation enacted by the Nazi regime in Germany that stripped German Jews of citizenship and civil rights.", "Nuremberg Laws", ["nürnberger gesetze"], "Wikipedia - Nuremberg Laws")
    ]
    for c, a, ac, s in q400: items.append((400, c, a, ac, s))

    # --- $500: Expert / Historiographical Precision & Deep Trivia (40 items) ---
    q500 = [
        ("The ancient peace treaty concluded around 1259 BC between Pharaoh Ramesses II and Hittite King Hattusili III, the oldest surviving international treaty.", "Treaty of Kadesh", ["silver treaty", "kadesh peace treaty"], "Wikipedia - Egyptian–Hittite peace treaty"),
        ("The decisive 1260 battle in the Galilee where the Mamluks handed the Mongol Empire its first permanent defeat in combat.", "Battle of Ain Jalut", ["ain jalut"], "Wikipedia - Battle of Ain Jalut"),
        ("The Venetian Doge who diverted the Fourth Crusade in 1204 to sack Christian Constantinople despite being blind and in his 90s.", "Enrico Dandolo", ["dandolo"], "Wikipedia - Enrico Dandolo"),
        ("The 1415 battle during the Hundred Years' War where King Henry V's English longbowmen decimated the French nobility in muddy terrain.", "Battle of Agincourt", ["agincourt"], "Wikipedia - Battle of Agincourt"),
        ("The final major battle of the War of the Spanish Succession in 1709, where Marlborough and Eugene defeated Villars with 30,000 casualties.", "Battle of Malplaquet", ["malplaquet"], "Wikipedia - Battle of Malplaquet"),
        ("The 1713-1714 series of peace treaties that concluded the War of the Spanish Succession, confirming Philip V as King of Spain.", "Peace of Utrecht", ["treaty of utrecht"], "Wikipedia - Treaty of Utrecht"),
        ("The 1645-1669 siege of Candia on Crete where the Republic of Venice defended against the Ottomans for 21 years, the second longest siege in history.", "Siege of Candia", ["siege of heraklion"], "Wikipedia - Siege of Candia"),
        ("The Byzantine general under Justinian I who reconquered Italy, North Africa, and Rome from the Ostrogoths and Vandals.", "Belisarius", ["flavius belisarius"], "Wikipedia - Belisarius"),
        ("The 1214 battle in Flanders where King Philip II Augustus of France defeated an allied Anglo-Flemish-German army, securing the French crown.", "Battle of Bouvines", ["bouvines"], "Wikipedia - Battle of Bouvines"),
        ("The 1689 English legal act that limited the powers of the monarch and set out the rights of Parliament, inspiring the US Bill of Rights.", "Bill of Rights 1689", ["english bill of rights"], "Wikipedia - Bill of Rights 1689"),
        ("The 1783 treaty that formally recognized the independence of the United States and ended the American Revolutionary War.", "Treaty of Paris 1783", ["peace of paris 1783"], "Wikipedia - Treaty of Paris (1783)"),
        ("The 1378-1417 division within the Catholic Church when multiple rival popes claimed the Papacy in Rome and Avignon simultaneously.", "Western Schism", ["papal schism", "great occidental schism"], "Wikipedia - Western Schism"),
        ("The ecumenical council held between 1414 and 1418 that resolved the Western Schism and condemned Jan Hus to death.", "Council of Constance", ["konstanz council"], "Wikipedia - Council of Constance"),
        ("The 1444 battle where the Ottoman army under Murad II crushed a European crusader army led by King Władysław III of Poland and Hungary.", "Battle of Varna", ["varna"], "Wikipedia - Battle of Varna"),
        ("The 1071 battle in eastern Anatolia where the Seljuk Turks under Alp Arslan defeated and captured Byzantine Emperor Romanos IV Diogenes.", "Battle of Manzikert", ["manzikert"], "Wikipedia - Battle of Manzikert"),
        ("The 1529 naval battle or land siege where the Ottoman army under Suleiman the Magnificent was halted at the gates of Austria for the first time.", "Siege of Vienna 1529", ["first siege of vienna"], "Wikipedia - Siege of Vienna (1529)"),
        ("The German statesman who drafted the Weimar Constitution in 1919 and was assassinated in 1922 for signing the Treaty of Rapallo.", "Walther Rathenau", ["rathenau"], "Wikipedia - Walther Rathenau"),
        ("The French Cardinal and chief minister to Louis XIII who centralized royal authority and curtailed the power of the nobility.", "Cardinal Richelieu", ["richelieu", "armand jean du plessis"], "Wikipedia - Cardinal Richelieu"),
        ("The successor to Cardinal Richelieu as chief minister of France who served during the minority of Louis XIV and negotiated Westphalia.", "Cardinal Mazarin", ["jules mazarin"], "Wikipedia - Cardinal Mazarin"),
        ("The rebellion in France from 1648 to 1653 by nobles and the Parlement of Paris against royal centralization under Cardinal Mazarin.", "The Fronde", ["la fronde"], "Wikipedia - The Fronde"),
        ("The 1774 British laws passed in response to the Boston Tea Party, known in Britain as the Coercive Acts.", "Intolerable Acts", ["coercive acts"], "Wikipedia - Intolerable Acts"),
        ("The 1797 naval mutiny in the British Royal Navy anchored off the Nore and Spithead during the French Revolutionary Wars.", "Spithead and Nore mutinies", ["nore mutiny", "spithead mutiny"], "Wikipedia - Spithead and Nore mutinies"),
        ("The 1825 failed military uprising in Saint Petersburg by Russian imperial officers seeking constitutional reform.", "Decembrist Revolt", ["decembrist uprising", "dekabristy"], "Wikipedia - Decembrist revolt"),
        ("The 1848-1849 political revolution in Hungary against Habsburg rule led by this national leader.", "Lajos Kossuth", ["kossuth"], "Wikipedia - Lajos Kossuth"),
        ("The 1908 political revolution in the Ottoman Empire that restored constitutional rule and deposed Sultan Abdul Hamid II.", "Young Turk Revolution", ["young turks"], "Wikipedia - Young Turk Revolution"),
        ("The secret intelligence operation during the 1953 Iranian coup that overthrew democratically elected Prime Minister Mohammad Mosaddegh.", "Operation Ajax", ["tp-ajax"], "Wikipedia - 1953 Iranian coup d'état"),
        ("The 1954 CIA-orchestrated covert operation that deposed the democratically elected President Jacobo Árbenz of Guatemala.", "Operation PBSUCCESS", ["pbsuccess"], "Wikipedia - 1954 Guatemalan coup d'état"),
        ("The 1381 uprising in England led by Wat Tyler and radical priest John Ball protesting poll taxes.", "Peasants' Revolt", ["wat tyler's rebellion"], "Wikipedia - Peasants' Revolt"),
        ("The 1282 rebellion in Palermo against the rule of the French Capetian House of Anjou, celebrated as an uprising.", "Sicilian Vespers", ["vespri siciliani"], "Wikipedia - Sicilian Vespers"),
        ("The treaty signed in 1920 between the Kingdom of Hungary and the Allied Powers that reduced Hungary's territory by 72%.", "Treaty of Trianon", ["trianon"], "Wikipedia - Treaty of Trianon"),
        ("The 1572 targeted assassinations and mob violence against French Huguenots in Paris, celebrated by Catholics.", "St. Bartholomew's Day massacre", ["massacre de la saint-barthélemy"], "Wikipedia - St. Bartholomew's Day massacre"),
        ("The 1878 congress of European powers that revised the Treaty of San Stefano and settled the Eastern Crisis.", "Congress of Berlin", ["berlin congress"], "Wikipedia - Congress of Berlin"),
        ("The 1605 conspiracy to blow up the House of Lords during the State Opening of Parliament, associated with Guy Fawkes.", "Gunpowder Plot", ["powder treason"], "Wikipedia - Gunpowder Plot"),
        ("The 1801 concordat between Napoleon Bonaparte and Pope Pius VII that restored civil relations between France and the Catholic Church.", "Concordat of 1801", ["the concordat"], "Wikipedia - Concordat of 1801"),
        ("The 1925 international treaty signed in Switzerland that guaranteed Germany's western borders with France and Belgium.", "Locarno Treaties", ["pact of locarno"], "Wikipedia - Locarno Treaties"),
        ("The 1794 reactionary coup during the French Revolution that overthrew Maximilien Robespierre on 9 Thermidor.", "Thermidorian Reaction", ["fall of robespierre"], "Wikipedia - Thermidorian Reaction"),
        ("The 1492 decree issued by Catholic Monarchs Isabella I of Castile and Ferdinand II of Aragon expelling all practicing Jews from Spain.", "Alhambra Decree", ["edict of expulsion"], "Wikipedia - Alhambra Decree"),
        ("The ancient law code inscribed on a basalt stele in Babylon around 1754 BC containing 282 edicts including 'an eye for an eye'.", "Code of Hammurabi", ["hammurabi's code"], "Wikipedia - Code of Hammurabi"),
        ("The 1555 peace agreement between Holy Roman Emperor Charles V and the Schmalkaldic League establishing 'cuius regio, eius religio'.", "Peace of Augsburg", ["augsburg settlement"], "Wikipedia - Peace of Augsburg"),
        ("The 1830 revolution in France that overthrew King Charles X and installed Louis-Philippe of the House of Orléans.", "July Revolution", ["les trois glorieuses"], "Wikipedia - July Revolution")
    ]
    for c, a, ac, s in q500: items.append((500, c, a, ac, s))

    return items

if __name__ == "__main__":
    qs = get_history_questions()
    print(f"Generated {len(qs)} history questions!")
