# World Geography (200 questions: 40 per tier: 100, 200, 300, 400, 500)

def get_geography_questions():
    items = []

    # --- $100: Novice / World Capitals & Landmarks (40 items) ---
    q100 = [
        ("The longest river in the world, flowing through northeastern Africa into the Mediterranean Sea.", "Nile River", ["nile", "the nile"], "Wikipedia - Nile"),
        ("The capital city of France, famous for the Eiffel Tower and the Louvre Museum.", "Paris", ["city of paris"], "Wikipedia - Paris"),
        ("The highest mountain above sea level on Earth, situated in the Himalayas.", "Mount Everest", ["everest", "mt everest"], "Wikipedia - Mount Everest"),
        ("The largest hot desert in the world, spanning across North Africa.", "Sahara Desert", ["sahara", "the sahara"], "Wikipedia - Sahara"),
        ("The capital city of the United Kingdom, situated on the River Thames.", "London", ["city of london"], "Wikipedia - London"),
        ("The largest ocean on Earth, covering more than 30% of the planet's surface.", "Pacific Ocean", ["pacific"], "Wikipedia - Pacific Ocean"),
        ("The South American country whose official language is Portuguese.", "Brazil", ["brasil"], "Wikipedia - Brazil"),
        ("The country with the largest land area in the world, spanning eleven time zones.", "Russia", ["russian federation"], "Wikipedia - Russia"),
        ("The capital city of Italy, home to the Colosseum and surrounding Vatican City.", "Rome", ["roma"], "Wikipedia - Rome"),
        ("The iconic giant clock tower located at the north end of the Palace of Westminster in London.", "Big Ben", ["elizabeth tower"], "Wikipedia - Big Ben"),
        ("The famous ancient amphitheater in Rome where gladiators fought.", "The Colosseum", ["colosseum", "flavian amphitheatre"], "Wikipedia - Colosseum"),
        ("The deepest canyon in the world carved by the Colorado River in Arizona.", "Grand Canyon", ["the grand canyon"], "Wikipedia - Grand Canyon"),
        ("The capital city of Japan, known as Edo prior to 1868.", "Tokyo", ["tokyo city"], "Wikipedia - Tokyo"),
        ("The country known as the 'Land of the Rising Sun'.", "Japan", ["nippon", "nihon"], "Wikipedia - Japan"),
        ("The island country and continent located in the Southern Hemisphere, home to kangaroos.", "Australia", ["commonwealth of australia"], "Wikipedia - Australia"),
        ("The capital city of Egypt, situated near the Giza pyramid complex.", "Cairo", ["al-qahirah"], "Wikipedia - Cairo"),
        ("The triangular delta river system in South America with the largest discharge volume in the world.", "Amazon River", ["amazon", "rio amazonas"], "Wikipedia - Amazon River"),
        ("The capital city of the United States, situated on the Potomac River.", "Washington D.C.", ["washington", "dc"], "Wikipedia - Washington, D.C."),
        ("The mountain range that separates the continents of Europe and Asia.", "Ural Mountains", ["the urals", "urals"], "Wikipedia - Ural Mountains"),
        ("The large island continent that is covered almost entirely by an ice sheet at the South Pole.", "Antarctica", ["south pole continent"], "Wikipedia - Antarctica"),
        ("The famous white marble mausoleum built by Emperor Shah Jahan in Agra, India.", "Taj Mahal", ["the taj mahal"], "Wikipedia - Taj Mahal"),
        ("The capital city of Canada, located in Ontario on the border with Quebec.", "Ottawa", ["city of ottawa"], "Wikipedia - Ottawa"),
        ("The large island nation off the southeast coast of Africa famous for lemurs.", "Madagascar", ["republic of madagascar"], "Wikipedia - Madagascar"),
        ("The canal in Central America connecting the Atlantic and Pacific oceans.", "Panama Canal", ["the panama canal"], "Wikipedia - Panama Canal"),
        ("The canal in Egypt that connects the Mediterranean Sea to the Red Sea.", "Suez Canal", ["the suez canal"], "Wikipedia - Suez Canal"),
        ("The European country shaped like a boot jutting into the Mediterranean Sea.", "Italy", ["italian republic"], "Wikipedia - Italy"),
        ("The iconic statue on Liberty Island in New York Harbor gifted by France.", "Statue of Liberty", ["lady liberty"], "Wikipedia - Statue of Liberty"),
        ("The capital city of Germany, reunified in 1990.", "Berlin", ["city of berlin"], "Wikipedia - Berlin"),
        ("The famous waterfall system on the border of Ontario, Canada and New York, USA.", "Niagara Falls", ["niagara"], "Wikipedia - Niagara Falls"),
        ("The country with the second largest population in the world, whose capital is New Delhi.", "India", ["bharat"], "Wikipedia - India"),
        ("The ancient stone monument circle located on Salisbury Plain in Wiltshire, England.", "Stonehenge", ["stone henge"], "Wikipedia - Stonehenge"),
        ("The capital city of China, previously called Peking.", "Beijing", ["peking"], "Wikipedia - Beijing"),
        ("The tallest free-standing mountain in Africa, located in Tanzania.", "Mount Kilimanjaro", ["kilimanjaro"], "Wikipedia - Mount Kilimanjaro"),
        ("The country with the longest coastline in the world, bordering three oceans.", "Canada", ["dominion of canada"], "Wikipedia - Canada"),
        ("The famous bay in California crossed by the Golden Gate Bridge.", "San Francisco Bay", ["sf bay"], "Wikipedia - San Francisco Bay"),
        ("The capital city of Greece, regarded as the cradle of Western civilization.", "Athens", ["athina"], "Wikipedia - Athens"),
        ("The largest island in the world that is not a continent, belonging to Denmark.", "Greenland", ["kalaallit nunaat"], "Wikipedia - Greenland"),
        ("The capital city of Russia, home to the Kremlin and Red Square.", "Moscow", ["moskva"], "Wikipedia - Moscow"),
        ("The river that flows through London, England.", "River Thames", ["thames"], "Wikipedia - River Thames"),
        ("The continent that contains the countries of Brazil, Argentina, and Colombia.", "South America", ["south american continent"], "Wikipedia - South America")
    ]
    for c, a, ac, s in q100: items.append((100, c, a, ac, s))

    # --- $200: Moderate / Geography & Nations (40 items) ---
    q200 = [
        ("The capital city of Australia, purpose-built between Sydney and Melbourne.", "Canberra", ["city of canberra"], "Wikipedia - Canberra"),
        ("The world's highest uninterrupted waterfall, dropping 979 meters in Venezuela.", "Angel Falls", ["salto ángel", "kerepakupai merú"], "Wikipedia - Angel Falls"),
        ("The sea that has no coastline, located entirely within the North Atlantic Gyre bounded by ocean currents.", "Sargasso Sea", ["the sargasso sea"], "Wikipedia - Sargasso Sea"),
        ("The strait separating Spain from Morocco that links the Atlantic Ocean to the Mediterranean Sea.", "Strait of Gibraltar", ["gibraltar"], "Wikipedia - Strait of Gibraltar"),
        ("The capital city of Spain, located in the geographical center of the Iberian Peninsula.", "Madrid", ["city of madrid"], "Wikipedia - Madrid"),
        ("The largest freshwater lake by surface area in the world, shared by Canada and the United States.", "Lake Superior", ["superior"], "Wikipedia - Lake Superior"),
        ("The deep lake in Siberia containing 20% of the world's unfrozen surface freshwater, the world's deepest.", "Lake Baikal", ["baikal"], "Wikipedia - Lake Baikal"),
        ("The capital city of Thailand, famous for grand palaces and ornate shrines.", "Bangkok", ["krung thep"], "Wikipedia - Bangkok"),
        ("The longest mountain range in the world, running along the western coast of South America.", "Andes Mountains", ["the andes", "andes"], "Wikipedia - Andes"),
        ("The capital city of Argentina, located on the western shore of the Río de la Plata.", "Buenos Aires", ["buenos aires"], "Wikipedia - Buenos Aires"),
        ("The strait that connects the Black Sea to the Sea of Marmara, dividing Istanbul into European and Asian sides.", "Bosphorus", ["bosporus", "istanbul strait"], "Wikipedia - Bosphorus"),
        ("The desert that covers much of southern Israel, making up more than half the country.", "Negev Desert", ["the negev"], "Wikipedia - Negev"),
        ("The capital city of South Korea, situated on the Han River.", "Seoul", ["seoul special city"], "Wikipedia - Seoul"),
        ("The small sovereign city-state enclave surrounded entirely by the city of Rome.", "Vatican City", ["the vatican", "holy see"], "Wikipedia - Vatican City"),
        ("The archipelago nation composed of over 17,000 islands, the world's largest island country.", "Indonesia", ["republic of indonesia"], "Wikipedia - Indonesia"),
        ("The capital city of Ireland, situated on the River Liffey.", "Dublin", ["baile átha cliath"], "Wikipedia - Dublin"),
        ("The salt lake bordered by Jordan and Israel whose surface is the lowest land elevation on Earth.", "Dead Sea", ["the dead sea"], "Wikipedia - Dead Sea"),
        ("The highest active volcano in Europe, located on the east coast of Sicily.", "Mount Etna", ["etna"], "Wikipedia - Mount Etna"),
        ("The capital city of Norway, located at the head of the Oslofjord.", "Oslo", ["city of oslo"], "Wikipedia - Oslo"),
        ("The mountain range spanning eight alpine countries across Central Europe, including Switzerland and Austria.", "The Alps", ["alps"], "Wikipedia - Alps"),
        ("The capital city of Portugal, located where the Tagus River empties into the Atlantic.", "Lisbon", ["lisboa"], "Wikipedia - Lisbon"),
        ("The body of water separating Great Britain from northern France.", "English Channel", ["the english channel", "la manche"], "Wikipedia - English Channel"),
        ("The capital city of the Netherlands, renowned for its historic canal system.", "Amsterdam", ["city of amsterdam"], "Wikipedia - Amsterdam"),
        ("The deepest natural marine trench in the world, plunging nearly 11,000 meters in the Pacific.", "Mariana Trench", ["marianas trench", "challenger deep"], "Wikipedia - Mariana Trench"),
        ("The capital city of New Zealand, located at the southwestern tip of the North Island.", "Wellington", ["te whanganui-a-tara"], "Wikipedia - Wellington"),
        ("The country in the Horn of Africa that is completely landlocked and whose capital is Addis Ababa.", "Ethiopia", ["federal democratic republic of ethiopia"], "Wikipedia - Ethiopia"),
        ("The capital city of Turkey, located in the central Anatolia region.", "Ankara", ["angora"], "Wikipedia - Ankara"),
        ("The group of five large interconnected freshwater lakes on the Canada-US border.", "The Great Lakes", ["great lakes"], "Wikipedia - Great Lakes"),
        ("The capital city of Sweden, built across 14 islands connected by over 50 bridges.", "Stockholm", ["city of stockholm"], "Wikipedia - Stockholm"),
        ("The narrow sea separating Saudi Arabia from northeast Africa.", "Red Sea", ["the red sea"], "Wikipedia - Red Sea"),
        ("The capital city of Mexico, built on the ruins of the Aztec capital Tenochtitlan.", "Mexico City", ["ciudad de mexico", "cdmx"], "Wikipedia - Mexico City"),
        ("The largest desert in Asia, spanning northern China and southern Mongolia.", "Gobi Desert", ["the gobi"], "Wikipedia - Gobi Desert"),
        ("The capital city of Peru, located in the valleys of the Chillón, Rímac, and Lurín rivers.", "Lima", ["city of lima"], "Wikipedia - Lima"),
        ("The river flowing through Paris, crossed by 37 bridges including Pont Neuf.", "Seine", ["river seine"], "Wikipedia - Seine"),
        ("The capital city of Poland, situated on the Vistula River.", "Warsaw", ["warszawa"], "Wikipedia - Warsaw"),
        ("The inland sea between southeastern Europe and Western Asia connected to the Mediterranean.", "Black Sea", ["the black sea"], "Wikipedia - Black Sea"),
        ("The capital city of Austria, situated on the Danube River and famous for classical music.", "Vienna", ["wien"], "Wikipedia - Vienna"),
        ("The African river that crosses the equator twice and is the world's deepest river.", "Congo River", ["congo", "zaire river"], "Wikipedia - Congo River"),
        ("The capital city of Switzerland, situated around a crook of the Aare River.", "Bern", ["berne"], "Wikipedia - Bern"),
        ("The world's largest coral reef system, located in the Coral Sea off Queensland, Australia.", "Great Barrier Reef", ["the great barrier reef"], "Wikipedia - Great Barrier Reef")
    ]
    for c, a, ac, s in q200: items.append((200, c, a, ac, s))

    # --- $300: Intermediate / World Boundaries & Topography (40 items) ---
    q300 = [
        ("The only country in the world that borders both the Caspian Sea and the Persian Gulf.", "Iran", ["islamic republic of iran", "persia"], "Wikipedia - Geography of Iran"),
        ("The capital city of Iceland, the northernmost capital of a sovereign state.", "Reykjavik", ["reykjavík"], "Wikipedia - Reykjavik"),
        ("The narrow body of water between Alaska and Russia connecting the Pacific and Arctic oceans.", "Bering Strait", ["the bering strait"], "Wikipedia - Bering Strait"),
        ("The capital city of Colombia, situated on a high plateau in the Andes.", "Bogota", ["bogotá"], "Wikipedia - Bogota"),
        ("The landlocked microstate nestled in the Pyrenees mountains between France and Spain.", "Andorra", ["principality of andorra"], "Wikipedia - Andorra"),
        ("The sea completely enclosed by land between Italy, Slovenia, Croatia, Bosnia, Montenegro, and Albania.", "Adriatic Sea", ["adriatic"], "Wikipedia - Adriatic Sea"),
        ("The capital city of Morocco, situated on the Atlantic coast at the mouth of the Bou Regreg river.", "Rabat", ["city of rabat"], "Wikipedia - Rabat"),
        ("The South American desert considered the driest non-polar desert in the world, in northern Chile.", "Atacama Desert", ["atacama"], "Wikipedia - Atacama Desert"),
        ("The capital city of Kenya, known as the 'Green City in the Sun'.", "Nairobi", ["city of nairobi"], "Wikipedia - Nairobi"),
        ("The strait separating mainland Italy from the island of Sicily.", "Strait of Messina", ["messina strait"], "Wikipedia - Strait of Messina"),
        ("The capital city of the Philippines, situated on the eastern shores of Manila Bay.", "Manila", ["city of manila"], "Wikipedia - Manila"),
        ("The mountain pass in the Alps connecting Austria and Italy, a major transit route since Roman times.", "Brenner Pass", ["passo del brennero"], "Wikipedia - Brenner Pass"),
        ("The capital city of Finland, situated on the shore of the Gulf of Finland.", "Helsinki", ["helsingfors"], "Wikipedia - Helsinki"),
        ("The African lake shared by Uganda, Kenya, and Tanzania, the largest tropical lake in the world.", "Lake Victoria", ["victoria nyanza"], "Wikipedia - Lake Victoria"),
        ("The capital city of Denmark, home to the Little Mermaid statue and Tivoli Gardens.", "Copenhagen", ["københavn"], "Wikipedia - Copenhagen"),
        ("The bay between northeastern Spain and western France known for severe maritime weather.", "Bay of Biscay", ["golfe de gascogne"], "Wikipedia - Bay of Biscay"),
        ("The capital city of Saudi Arabia, situated in the center of the Arabian Peninsula.", "Riyadh", ["ar-riyad"], "Wikipedia - Riyadh"),
        ("The highest peak in North America, located in the Alaska Range (formerly Mount McKinley).", "Denali", ["mount mckinley", "mt mckinley"], "Wikipedia - Denali"),
        ("The capital city of Cuba, the largest city in the Caribbean.", "Havana", ["la habana"], "Wikipedia - Havana"),
        ("The vast treeless biome found in the Arctic north, characterized by permanently frozen subsoil.", "Tundra", ["arctic tundra"], "Wikipedia - Tundra"),
        ("The capital city of Scotland, dominated by a historic castle atop an extinct volcanic plug.", "Edinburgh", ["dùn èideann"], "Wikipedia - Edinburgh"),
        ("The large island in the Canadian Arctic Archipelago, the fifth largest island in the world.", "Baffin Island", ["baffin"], "Wikipedia - Baffin Island"),
        ("The capital city of Jordan, built across seven hills.", "Amman", ["city of amman"], "Wikipedia - Amman"),
        ("The long peninsula in northwest Mexico separating the Pacific Ocean from the Gulf of California.", "Baja California", ["baja peninsula"], "Wikipedia - Baja California Peninsula"),
        ("The capital city of Chile, situated in a valley surrounded by the snow-capped Andes.", "Santiago", ["santiago de chile"], "Wikipedia - Santiago"),
        ("The sea bordered by Turkey to the east and Greece to the west, home to hundreds of islands.", "Aegean Sea", ["aegean"], "Wikipedia - Aegean Sea"),
        ("The capital city of Vietnam, situated along the Red River in northern Vietnam.", "Hanoi", ["hà nội"], "Wikipedia - Hanoi"),
        ("The triangular cape located at the southern tip of the Sinai Peninsula in Egypt.", "Sharm El Sheikh", ["ras muhammad", "sinai cape"], "Wikipedia - Sinai Peninsula"),
        ("The capital city of Ukraine, situated on the Dnieper River.", "Kyiv", ["kiev"], "Wikipedia - Kyiv"),
        ("The large lake in South America on the border of Peru and Bolivia, the highest navigable lake.", "Lake Titicaca", ["titicaca"], "Wikipedia - Lake Titicaca"),
        ("The capital city of Hungary, split into two historical parts by the Danube River.", "Budapest", ["buda and pest"], "Wikipedia - Budapest"),
        ("The archipelago off the southern tip of South America separated from the mainland by the Strait of Magellan.", "Tierra del Fuego", ["land of fire"], "Wikipedia - Tierra del Fuego"),
        ("The capital city of Romania, once known as 'Little Paris of the East'.", "Bucharest", ["bucurești"], "Wikipedia - Bucharest"),
        ("The highest mountain peak in South America, located in Mendoza Province, Argentina.", "Aconcagua", ["cerro aconcagua"], "Wikipedia - Aconcagua"),
        ("The capital city of the Czech Republic, known as the 'City of a Hundred Spires'.", "Prague", ["praha"], "Wikipedia - Prague"),
        ("The strait between Malaysia and Indonesia, one of the most vital shipping lanes in the world.", "Strait of Malacca", ["malacca strait"], "Wikipedia - Strait of Malacca"),
        ("The capital city of Portugal's former territory of Macau, now an administrative region of China.", "Macau", ["macao"], "Wikipedia - Macau"),
        ("The high plateau in Central Asia often referred to as the 'Roof of the World'.", "Pamir Mountains", ["tibetan plateau", "pamirs"], "Wikipedia - Pamir Mountains"),
        ("The capital city of Lebanon, situated on a peninsula at the midpoint of Lebanon's Mediterranean coast.", "Beirut", ["bayrut"], "Wikipedia - Beirut"),
        ("The second longest river in Europe, flowing through ten countries from the Black Forest to the Black Sea.", "Danube River", ["danube", "donau"], "Wikipedia - Danube")
    ]
    for c, a, ac, s in q300: items.append((300, c, a, ac, s))

    # --- $400: Advanced / Geopolitical Oddities & Physical Geography (40 items) ---
    q400 = [
        ("The only sovereign country in the world that is completely surrounded by South Africa.", "Lesotho", ["kingdom of lesotho"], "Wikipedia - Lesotho"),
        ("The capital city of Kazakhstan, formerly known as Nur-Sultan and Akmola.", "Astana", ["nur-sultan", "akmola"], "Wikipedia - Astana"),
        ("The African country with the most pyramids in the world, outnumbering Egypt with over 200 Nubian pyramids.", "Sudan", ["republic of the sudan"], "Wikipedia - Nubian pyramids"),
        ("The high mountain pass between Pakistan and Afghanistan, a historic trade route through the Hindu Kush.", "Khyber Pass", ["the khyber pass"], "Wikipedia - Khyber Pass"),
        ("The capital city of Mongolia, the coldest national capital in the world by average annual temperature.", "Ulaanbaatar", ["ulan bator"], "Wikipedia - Ulaanbaatar"),
        ("The Russian exclave situated on the Baltic Sea between Poland and Lithuania.", "Kaliningrad", ["kaliningrad oblast", "königsberg"], "Wikipedia - Kaliningrad"),
        ("The capital city of Nigeria, created as a planned city in the 1980s to replace Lagos.", "Abuja", ["federal capital territory abuja"], "Wikipedia - Abuja"),
        ("The volcanic island in the South Atlantic that is the most remote permanently inhabited archipelago on Earth.", "Tristan da Cunha", ["tristan da cunha island"], "Wikipedia - Tristan da Cunha"),
        ("The capital city of Myanmar, established as the new administrative capital in 2005.", "Naypyidaw", ["nay pyi taw"], "Wikipedia - Naypyidaw"),
        ("The sea bounded by the Kamchatka Peninsula, the Kuril Islands, and Sakhalin Island.", "Sea of Okhotsk", ["okhotsk"], "Wikipedia - Sea of Okhotsk"),
        ("The capital city of Ecuador, situated on the slopes of the active volcano Pichincha.", "Quito", ["san francisco de quito"], "Wikipedia - Quito"),
        ("The strait separating mainland Australia from the southern island state of Tasmania.", "Bass Strait", ["the bass strait"], "Wikipedia - Bass Strait"),
        ("The capital city of Bolivia that serves as the seat of government, the highest administrative capital on Earth.", "La Paz", ["nuestra señora de la paz"], "Wikipedia - La Paz"),
        ("The sea connected to the Black Sea via the narrow Strait of Kerch.", "Sea of Azov", ["azov sea"], "Wikipedia - Sea of Azov"),
        ("The capital city of Paraguay, situated on the left bank of the Paraguay River.", "Asuncion", ["asunción"], "Wikipedia - Asuncion"),
        ("The mountain range running north-south through Italy, forming the spine of the Italian peninsula.", "Apennine Mountains", ["apennines"], "Wikipedia - Apennine Mountains"),
        ("The capital city of Azerbaijan, the lowest-lying national capital in the world (28 meters below sea level).", "Baku", ["city of baku"], "Wikipedia - Baku"),
        ("The peninsula in southwest Asia on which the country of Qatar is located.", "Arabian Peninsula", ["qatar peninsula"], "Wikipedia - Qatar"),
        ("The capital city of Bhutan, where construction must follow traditional Dzong architecture.", "Thimphu", ["thimpu"], "Wikipedia - Thimphu"),
        ("The strait separating the North Island and South Island of New Zealand.", "Cook Strait", ["the cook strait"], "Wikipedia - Cook Strait"),
        ("The capital city of Uzbekistan, the largest city in Central Asia.", "Tashkent", ["toshkent"], "Wikipedia - Tashkent"),
        ("The lake that was formerly the fourth largest in the world before shrinking drastically due to Soviet irrigation.", "Aral Sea", ["the aral sea"], "Wikipedia - Aral Sea"),
        ("The capital city of Malta, recognized as a UNESCO World Heritage site for its baroque fortifications.", "Valletta", ["il-belt valletta"], "Wikipedia - Valletta"),
        ("The deep fjord in Norway renowned as the longest and deepest in the country, often called 'King of the Fjords'.", "Sognefjord", ["sogne fjord"], "Wikipedia - Sognefjord"),
        ("The capital city of Slovakia, situated on the borders with both Austria and Hungary.", "Bratislava", ["pressburg"], "Wikipedia - Bratislava"),
        ("The small British Overseas Territory at the southern tip of the Iberian Peninsula dominated by a limestone rock.", "Gibraltar", ["the rock of gibraltar"], "Wikipedia - Gibraltar"),
        ("The capital city of Georgia in the Caucasus, situated on the banks of the Kura River.", "Tbilisi", ["tiflis"], "Wikipedia - Tbilisi"),
        ("The island in the Mediterranean divided since 1974 between an internationally recognized republic and a northern de facto state.", "Cyprus", ["republic of cyprus"], "Wikipedia - Cyprus"),
        ("The capital city of Oman, located along the Sea of Oman flanked by arid Hajar Mountains.", "Muscat", ["masqat"], "Wikipedia - Muscat"),
        ("The deepest lake in North America, plunging to 614 meters in Canada's Northwest Territories.", "Great Slave Lake", ["great slave"], "Wikipedia - Great Slave Lake"),
        ("The capital city of Sri Lanka that serves as the official legislative seat.", "Sri Jayawardenepura Kotte", ["kotte", "colombo"], "Wikipedia - Sri Jayawardenepura Kotte"),
        ("The narrow sea channel separating the Korean Peninsula from the Japanese island of Kyushu.", "Tsushima Strait", ["korea strait", "tsushima"], "Wikipedia - Tsushima Strait"),
        ("The capital city of Armenia, one of the world's oldest continuously inhabited cities.", "Yerevan", ["erebuni"], "Wikipedia - Yerevan"),
        ("The group of volcanic islands in the Atlantic owned by Portugal where tectonic plates of Europe, Africa, and North America meet.", "Azores", ["the azores"], "Wikipedia - Azores"),
        ("The capital city of Madagascar, known locally as 'Tana'.", "Antananarivo", ["tana"], "Wikipedia - Antananarivo"),
        ("The semi-arid region in Africa forming a transition zone between the Sahara to the north and the savannas to the south.", "The Sahel", ["sahel"], "Wikipedia - Sahel"),
        ("The capital city of Estonia, situated on the northern coast opposite Helsinki.", "Tallinn", ["reval"], "Wikipedia - Tallinn"),
        ("The only country in the world that lies entirely above 1,000 meters in elevation.", "Lesotho", ["kingdom of lesotho"], "Wikipedia - Geography of Lesotho"),
        ("The capital city of Latvia, the largest city in the three Baltic states.", "Riga", ["rīga"], "Wikipedia - Riga"),
        ("The chain of four main Japanese islands: Honshu, Hokkaido, Kyushu, and this fourth.", "Shikoku", ["shikoku island"], "Wikipedia - Japanese archipelago")
    ]
    for c, a, ac, s in q400: items.append((400, c, a, ac, s))

    # --- $500: Expert / Geographic Enclaves & Remote Topography (40 items) ---
    q500 = [
        ("The only two doubly landlocked countries in the world: Liechtenstein and this Central Asian republic.", "Uzbekistan", ["republic of uzbekistan"], "Wikipedia - Doubly landlocked country"),
        ("The point in the Pacific Ocean that is the most remote point from any land (Point Nemo).", "Point Nemo", ["oceanic pole of inaccessibility"], "Wikipedia - Pole of inaccessibility"),
        ("The capital city of the Federated States of Micronesia, located on the island of Pohnpei.", "Palikir", ["palikir city"], "Wikipedia - Palikir"),
        ("The strait between the Persian Gulf and the Gulf of Oman through which a fifth of the world's petroleum passes.", "Strait of Hormuz", ["hormuz"], "Wikipedia - Strait of Hormuz"),
        ("The capital city of Tuvalu, an atoll nation threatened by rising sea levels.", "Funafuti", ["vaiaku"], "Wikipedia - Funafuti"),
        ("The disputed territory between Egypt and Sudan that is one of the few unclaimed pieces of land on Earth.", "Bir Tawil", ["bir tawil triangle"], "Wikipedia - Bir Tawil"),
        ("The capital city of Suriname, located on the banks of the Suriname River.", "Paramaribo", ["paramaribo city"], "Wikipedia - Paramaribo"),
        ("The river that forms the entire border between the US states of Vermont and New Hampshire.", "Connecticut River", ["the connecticut river"], "Wikipedia - Connecticut River"),
        ("The capital city of Belize, constructed inland after Hurricane Hattie devastated Belize City in 1961.", "Belmopan", ["city of belmopan"], "Wikipedia - Belmopan"),
        ("The second deepest trench on Earth, located in the South Pacific Ocean reaching 10,882 meters.", "Tonga Trench", ["the tonga trench", "horizon deep"], "Wikipedia - Tonga Trench"),
        ("The capital city of Equatorial Guinea situated on the island of Bioko, before relocation to Ciudad de la Paz.", "Malabo", ["santa isabel"], "Wikipedia - Malabo"),
        ("The semi-enclosed body of water in the Canadian Arctic between Greenland and Baffin Island.", "Baffin Bay", ["baffin bay"], "Wikipedia - Baffin Bay"),
        ("The capital city of Mauritania, which grew from a small fishing village into a metropolis of a million people.", "Nouakchott", ["city of nouakchott"], "Wikipedia - Nouakchott"),
        ("The narrow continental divide pass in Colorado where water splits between the Atlantic and Pacific oceans.", "Loveland Pass", ["continental divide pass", "independence pass"], "Wikipedia - Continental Divide of the Americas"),
        ("The capital city of the Comoros archipelago in the Mozambique Channel.", "Moroni", ["moroni city"], "Wikipedia - Moroni, Comoros"),
        ("The Norwegian volcanic island located in the Arctic Ocean dominated by the glacier-covered Beerenberg volcano.", "Jan Mayen", ["jan mayen island"], "Wikipedia - Jan Mayen"),
        ("The capital city of Palau, situated on the island of Babeldaob (replacing Koror in 2006).", "Ngerulmud", ["ngerulmud palau"], "Wikipedia - Ngerulmud"),
        ("The geographic point where the borders of Belgium, Germany, and the Netherlands meet near Aachen.", "Vaalserberg", ["three country point", "tripoint vaals"], "Wikipedia - Vaalserberg"),
        ("The capital city of Burundi, which replaced Bujumbura as political capital in 2019.", "Gitega", ["kitega"], "Wikipedia - Gitega"),
        ("The island at the southern entrance to the Red Sea that splits the Bab-el-Mandeb strait into two channels.", "Perim Island", ["mayyun", "perim"], "Wikipedia - Perim"),
        ("The capital city of Vanuatu, situated on the south coast of the island of Efate.", "Port Vila", ["port vila"], "Wikipedia - Port Vila"),
        ("The salt flat in southwestern Bolivia spanning over 10,000 square kilometers, the world's largest salt flat.", "Salar de Uyuni", ["uyuni salt flat"], "Wikipedia - Salar de Uyuni"),
        ("The capital city of Tajikistan, whose name translates to 'Monday' in Tajik because of its weekly market.", "Dushanbe", ["stalinabad"], "Wikipedia - Dushanbe"),
        ("The volcanic island archipelago in the Indian Ocean that is an overseas department of France, adjacent to Mauritius.", "Reunion", ["la réunion", "reunion island"], "Wikipedia - Réunion"),
        ("The capital city of Kiribati, an atoll comprising half the population of the nation.", "South Tarawa", ["tarawa"], "Wikipedia - South Tarawa"),
        ("The narrow corridor of land in northeastern Afghanistan extending to the border with China.", "Wakhan Corridor", ["the wakhan"], "Wikipedia - Wakhan Corridor"),
        ("The capital city of Lesotho, situated on the Caledon River on the South Africa border.", "Maseru", ["maseru city"], "Wikipedia - Maseru"),
        ("The vast wetland region in South America located mainly in the Brazilian state of Mato Grosso do Sul.", "Pantanal", ["the pantanal"], "Wikipedia - Pantanal"),
        ("The capital city of São Tomé and Príncipe, the island nation in the Gulf of Guinea.", "Sao Tome", ["são tomé"], "Wikipedia - São Tomé"),
        ("The deep depression in Antarctica that contains the lowest natural point on land not covered by sea (-3,500m).", "Denman Glacier Canyon", ["bentley subglacial trench", "denman glacier"], "Wikipedia - Denman Glacier"),
        ("The capital city of Cabo Verde, located on the southern coast of Santiago Island.", "Praia", ["praia city"], "Wikipedia - Praia"),
        ("The strait separating the Australian mainland from Papua New Guinea.", "Torres Strait", ["the torres strait"], "Wikipedia - Torres Strait"),
        ("The capital city of the Marshall Islands, located on a coral atoll of 64 islands.", "Majuro", ["majuro atoll"], "Wikipedia - Majuro"),
        ("The active stratovolcano on Ross Island, Antarctica, the southernmost active volcano on Earth.", "Mount Erebus", ["erebus"], "Wikipedia - Mount Erebus"),
        ("The capital city of Guinea-Bissau, situated on the Geba River estuary.", "Bissau", ["city of bissau"], "Wikipedia - Bissau"),
        ("The mountain pass in Switzerland that was traversed by Russian General Alexander Suvorov in 1799.", "St. Gotthard Pass", ["san gottardo", "gotthard pass"], "Wikipedia - Gotthard Pass"),
        ("The capital city of Nauru, which functions as the de facto capital although Nauru has no official capital.", "Yaren", ["yaren district"], "Wikipedia - Yaren"),
        ("The lake shared by Chad, Cameroon, Niger, and Nigeria that has shrunk by 95% since 1963.", "Lake Chad", ["chad lake"], "Wikipedia - Lake Chad"),
        ("The capital city of Saint Kitts and Nevis, located on the island of Saint Kitts.", "Basseterre", ["basseterre city"], "Wikipedia - Basseterre"),
        ("The Cape located at the southernmost tip of the African continent, dividing the Atlantic and Indian oceans.", "Cape Agulhas", ["cape of good hope", "agulhas"], "Wikipedia - Cape Agulhas")
    ]
    for c, a, ac, s in q500: items.append((500, c, a, ac, s))

    return items

if __name__ == "__main__":
    qs = get_geography_questions()
    print(f"Generated {len(qs)} geography questions!")
