# Film & IMDb Legends (200 questions: 40 per tier: 100, 200, 300, 400, 500)

def get_movies_questions():
    items = []

    # --- $100: Novice / Iconic Blockbusters (40 items) ---
    q100 = [
        ("The actor who portrayed Tony Stark / Iron Man across 10 films in the Marvel Cinematic Universe.", "Robert Downey Jr", ["robert downey jr.", "rdj", "robert downey"], "IMDb - Marvel Cinematic Universe"),
        ("In this 1994 Disney animated classic, Simba learns the phrase 'Hakuna Matata' from Timon and Pumbaa.", "The Lion King", ["lion king"], "IMDb - Walt Disney Animation"),
        ("The 1997 James Cameron epic starring Leonardo DiCaprio and Kate Winslet aboard an ill-fated passenger liner.", "Titanic", ["rms titanic"], "IMDb - Box Office Records"),
        ("The fictional African nation ruled by King T'Challa in Marvel's Black Panther.", "Wakanda", ["kingdom of wakanda"], "IMDb - Black Panther"),
        ("The green Jedi master who speaks in inverted syntax and trains Luke Skywalker on Dagobah.", "Yoda", ["master yoda"], "IMDb - Star Wars"),
        ("The animated movie franchise starring Shrek, a green ogre who lives in a swamp.", "Shrek", ["shrek franchise"], "IMDb - DreamWorks"),
        ("The actor who plays the swashbuckling pirate Captain Jack Sparrow in Pirates of the Caribbean.", "Johnny Depp", ["depp"], "IMDb - Pirates of the Caribbean"),
        ("The 1993 Steven Spielberg dinosaur blockbuster that launched an iconic global franchise.", "Jurassic Park", ["jurassic park film"], "IMDb - Steven Spielberg"),
        ("The protagonist of The Matrix series played by Keanu Reeves who takes the red pill.", "Neo", ["thomas anderson", "keanu reeves"], "IMDb - The Matrix"),
        ("The wizard mentor with a long grey beard who guides the Fellowship in The Lord of the Rings.", "Gandalf", ["gandalf the grey", "gandalf the white"], "IMDb - Lord of the Rings"),
        ("The young boy wizard with a lightning bolt scar on his forehead who attends Hogwarts.", "Harry Potter", ["potter"], "IMDb - Harry Potter"),
        ("The toy cowboy in Toy Story voiced by Tom Hanks whose boot has Andy's name written on it.", "Woody", ["sheriff woody"], "IMDb - Toy Story / Pixar"),
        ("The space ranger toy in Toy Story whose catchphrase is 'To infinity and beyond!'.", "Buzz Lightyear", ["lightyear", "buzz"], "IMDb - Pixar"),
        ("The superhero alias of Bruce Wayne who protects the city of Gotham.", "Batman", ["the dark knight", "caped crusader"], "IMDb - DC Comics"),
        ("The superhero alias of Peter Parker who shoots webs and swings through New York City.", "Spider-Man", ["spiderman", "peter parker"], "IMDb - Marvel"),
        ("The iconic monster from Japan who breathes atomic breath and is known as the King of the Monsters.", "Godzilla", ["gojira"], "IMDb - Kaiju Cinema"),
        ("The British secret agent who holds the codename 007 and prefers his martinis shaken, not stirred.", "James Bond", ["007", "bond"], "IMDb - Eon Productions"),
        ("The 1985 time-travel adventure film starring Michael J. Fox as Marty McFly and Christopher Lloyd as Doc Brown.", "Back to the Future", ["back to the future part i"], "IMDb - Universal Pictures"),
        ("The mythical golden ring found by Bilbo Baggins that corrupts its bearer in Middle-earth.", "The One Ring", ["the ring", "precious", "ruling ring"], "IMDb - Lord of the Rings"),
        ("The clumsy martial arts panda voiced by Jack Black in DreamWorks Animation.", "Po", ["kung fu panda"], "IMDb - DreamWorks"),
        ("The famous catchphrase uttered by Arnold Schwarzenegger in The Terminator.", "I'll be back", ["ill be back", "i will be back"], "IMDb - The Terminator"),
        ("The clownfish father who embarks on an epic ocean journey to rescue his son in a 2003 Pixar film.", "Marlin", ["finding nemo"], "IMDb - Pixar"),
        ("The actor who played Wolverine in the X-Men films across more than two decades.", "Hugh Jackman", ["jackman"], "IMDb - 20th Century Fox"),
        ("The fictional high school musical comedy about Regina George and the Plastics written by Tina Fey.", "Mean Girls", ["mean girls movie"], "IMDb - Paramount"),
        ("The fast-driving franchise starring Vin Diesel as Dominic Toretto centered on family and street racing.", "Fast and Furious", ["the fast and the furious", "fast & furious"], "IMDb - Universal"),
        ("The alien with a glowing fingertip who wants to 'phone home' in Steven Spielberg's 1982 classic.", "E.T.", ["et", "the extra-terrestrial"], "IMDb - Steven Spielberg"),
        ("The fictional yellow underwater sponge who works as a fry cook at the Krusty Krab.", "SpongeBob SquarePants", ["spongebob"], "IMDb - Nickelodeon"),
        ("The animated movie about a family of undercover superheroes featuring Mr. Incredible and Elastigirl.", "The Incredibles", ["incredibles"], "IMDb - Pixar"),
        ("The actor who portrayed Captain America / Steve Rogers throughout the Marvel Infinity Saga.", "Chris Evans", ["evans"], "IMDb - Marvel"),
        ("The villainous galactic emperor in Star Wars who seduces Anakin Skywalker to the dark side.", "Emperor Palpatine", ["palpatine", "darth sidious"], "IMDb - Star Wars"),
        ("The 1975 thriller about a giant great white shark terrorizing Amity Island that created the summer blockbuster.", "Jaws", ["jaws film"], "IMDb - Steven Spielberg"),
        ("The magical nanny played by Julie Andrews who arrives with an umbrella to help the Banks family.", "Mary Poppins", ["poppins"], "IMDb - Walt Disney"),
        ("The actor who voiced the genie in Disney's 1992 animated classic Aladdin.", "Robin Williams", ["williams"], "IMDb - Disney Classics"),
        ("The yellow Minions serve this reformed supervillain who adopts three girls in Despicable Me.", "Gru", ["felonius gru"], "IMDb - Illumination"),
        ("The assassin played by Keanu Reeves who comes out of retirement after his puppy is killed.", "John Wick", ["wick"], "IMDb - Lionsgate"),
        ("The boxing movie written by and starring Sylvester Stallone that won Best Picture in 1976.", "Rocky", ["rocky balboa"], "IMDb - MGM"),
        ("The mythical island where King Kong was discovered before being brought to New York City.", "Skull Island", ["skull isle"], "IMDb - King Kong"),
        ("The superhero played by Chadwick Boseman who defends Wakanda as its protector.", "Black Panther", ["t'challa", "tchalla"], "IMDb - Marvel"),
        ("The archaeologist adventurer portrayed by Harrison Ford who wields a bullwhip and fears snakes.", "Indiana Jones", ["indy", "henry jones jr"], "IMDb - Lucasfilm"),
        ("The fictional spaceship captained by Han Solo with Chewbacca as co-pilot.", "Millennium Falcon", ["the millennium falcon"], "IMDb - Star Wars")
    ]
    for c, a, ac, s in q100: items.append((100, c, a, ac, s))

    # --- $200: Moderate / Acclaimed Hits (40 items) ---
    q200 = [
        ("The director of 2009's Avatar, which stands as the highest-grossing film of all time.", "James Cameron", ["cameron"], "IMDb - All-Time Box Office"),
        ("The 2008 Christopher Nolan film featuring Heath Ledger's Oscar-winning performance as the Joker.", "The Dark Knight", ["dark knight"], "IMDb - Warner Bros"),
        ("The 1994 Frank Darabont prison drama that holds the #1 spot on IMDb's Top 250 Movies list.", "The Shawshank Redemption", ["shawshank redemption", "shawshank"], "IMDb - Top 250 Chart"),
        ("The fictional mobster family led by Vito and Michael Corleone in Francis Ford Coppola's masterpiece.", "Corleone", ["the corleone family", "corleones"], "IMDb - The Godfather"),
        ("The 1994 Quentin Tarantino crime film known for its nonlinear storytelling and Big Kahuna Burger.", "Pulp Fiction", ["pulp fiction"], "IMDb - Miramax"),
        ("The actor who won back-to-back Best Actor Oscars for Philadelphia (1993) and Forrest Gump (1994).", "Tom Hanks", ["hanks"], "IMDb - Academy Awards"),
        ("The 2010 Christopher Nolan sci-fi thriller about thieves who steal secrets using dream-sharing technology.", "Inception", ["inception film"], "IMDb - Warner Bros"),
        ("The fictional motel run by Norman Bates in Alfred Hitchcock's 1960 psychological horror classic.", "Bates Motel", ["the bates motel"], "IMDb - Psycho"),
        ("The 1980 horror film directed by Stanley Kubrick set in the snowbound Overlook Hotel.", "The Shining", ["shining"], "IMDb - Stanley Kubrick"),
        ("The actress who won an Oscar for her performance as Clarice Starling in The Silence of the Lambs.", "Jodie Foster", ["foster"], "IMDb - Academy Awards"),
        ("The actor who won an Oscar playing the cannibalistic serial killer Hannibal Lecter in 1991.", "Anthony Hopkins", ["sir anthony hopkins", "hopkins"], "IMDb - Academy Awards"),
        ("The 2000 historical epic directed by Ridley Scott starring Russell Crowe as Maximus Decimus Meridius.", "Gladiator", ["gladiator film"], "IMDb - Universal"),
        ("The female director who won the Best Director Oscar for the 2008 Iraq war drama The Hurt Locker.", "Kathryn Bigelow", ["bigelow"], "IMDb - Academy Awards"),
        ("The actress who played Katniss Everdeen in The Hunger Games franchise.", "Jennifer Lawrence", ["lawrence"], "IMDb - Lionsgate"),
        ("The director known for his distinct visual symmetry and pastel palettes in The Grand Budapest Hotel.", "Wes Anderson", ["anderson"], "IMDb - Fox Searchlight"),
        ("The 1999 psychological thriller directed by David Fincher starring Brad Pitt and Edward Norton.", "Fight Club", ["fight club film"], "IMDb - 20th Century Fox"),
        ("The 2001 Peter Jackson film that inaugurated the Lord of the Rings cinematic trilogy.", "The Fellowship of the Ring", ["fellowship of the ring"], "IMDb - New Line Cinema"),
        ("The composer who wrote the iconic musical scores for Star Wars, Jaws, and Indiana Jones.", "John Williams", ["williams"], "IMDb - Film Scores"),
        ("The actor who played the eccentric chocolate maker Willy Wonka in the 1971 musical adaptation.", "Gene Wilder", ["wilder"], "IMDb - Paramount"),
        ("The 2016 musical film starring Ryan Gosling and Emma Stone that won 6 Oscars.", "La La Land", ["la la land"], "IMDb - Lionsgate"),
        ("The 1982 Ridley Scott sci-fi masterpiece starring Harrison Ford as Rick Deckard hunting replicants.", "Blade Runner", ["blade runner film"], "IMDb - Warner Bros"),
        ("The black-and-white 1993 Steven Spielberg Holocaust drama that won seven Academy Awards.", "Schindler's List", ["schindlers list"], "IMDb - Universal"),
        ("The legendary actor who portrayed Vito Corleone in The Godfather and Terry Malloy in On the Waterfront.", "Marlon Brando", ["brando"], "IMDb - Paramount"),
        ("The 1977 space fantasy film created by George Lucas that became a worldwide cultural phenomenon.", "Star Wars: Episode IV - A New Hope", ["star wars", "a new hope"], "IMDb - Lucasfilm"),
        ("The 2019 DC movie directed by Todd Phillips that earned Joaquin Phoenix a Best Actor Oscar.", "Joker", ["joker film"], "IMDb - Warner Bros"),
        ("The 1995 epic historical drama directed by and starring Mel Gibson as Scottish warrior William Wallace.", "Braveheart", ["braveheart film"], "IMDb - Paramount"),
        ("The 1999 Wachowskis sci-fi film that introduced 'bullet time' visual effects.", "The Matrix", ["the matrix film"], "IMDb - Warner Bros"),
        ("The 1984 sci-fi comedy about three parapsychologists who start a ghost removal business in NYC.", "Ghostbusters", ["ghostbusters film"], "IMDb - Columbia"),
        ("The 2014 sci-fi epic directed by Christopher Nolan about astronauts seeking a new home through a wormhole.", "Interstellar", ["interstellar film"], "IMDb - Paramount"),
        ("The 2006 Martin Scorsese mob drama starring Leonardo DiCaprio and Matt Damon that won Best Picture.", "The Departed", ["the departed"], "IMDb - Warner Bros"),
        ("The 1998 World War II epic directed by Steven Spielberg centered on the D-Day invasion at Omaha Beach.", "Saving Private Ryan", ["saving private ryan"], "IMDb - DreamWorks"),
        ("The fictional British boarding school of witchcraft and wizardry in the Harry Potter films.", "Hogwarts", ["hogwarts school"], "IMDb - Warner Bros"),
        ("The actor who portrayed Severus Snape in all eight Harry Potter films.", "Alan Rickman", ["rickman"], "IMDb - Warner Bros"),
        ("The 2001 animated movie that won the very first Academy Award for Best Animated Feature.", "Shrek", ["shrek 1"], "IMDb - Academy Awards"),
        ("The 1986 action film starring Tom Cruise as naval aviator Pete 'Maverick' Mitchell.", "Top Gun", ["top gun 1986"], "IMDb - Paramount"),
        ("The 2015 post-apocalyptic action movie directed by George Miller starring Charlize Theron as Furiosa.", "Mad Max: Fury Road", ["fury road", "mad max"], "IMDb - Warner Bros"),
        ("The 1973 horror masterpiece directed by William Friedkin about the demonic possession of a young girl.", "The Exorcist", ["the exorcist"], "IMDb - Warner Bros"),
        ("The classic 1939 musical fantasy film starring Judy Garland as Dorothy Gale traveling to the Land of Oz.", "The Wizard of Oz", ["wizard of oz"], "IMDb - MGM"),
        ("The 1968 Stanley Kubrick sci-fi classic featuring the rogue sentient computer HAL 9000.", "2001: A Space Odyssey", ["2001 space odyssey", "a space odyssey"], "IMDb - MGM"),
        ("The 1991 Disney animated film that became the first animated feature nominated for Best Picture.", "Beauty and the Beast", ["beauty and the beast"], "IMDb - Walt Disney")
    ]
    for c, a, ac, s in q200: items.append((200, c, a, ac, s))

    # --- $300: Intermediate / Cinema Lore (40 items) ---
    q300 = [
        ("The 2019 South Korean black comedy thriller directed by Bong Joon-ho that won four Academy Awards including Best Picture.", "Parasite", ["gisaengchung"], "IMDb - Academy Awards"),
        ("The Italian director of the 'Dollars Trilogy' spaghetti westerns starring Clint Eastwood.", "Sergio Leone", ["leone"], "IMDb - Western Cinema"),
        ("The code name for Steve Rogers' brainwashed assassin best friend Bucky Barnes in the MCU.", "The Winter Soldier", ["winter soldier", "bucky barnes"], "IMDb - Marvel Cinematic Universe"),
        ("The 1960 Alfred Hitchcock shower-scene horror film featuring Marion Crane at an isolated motel.", "Psycho", ["psycho film"], "IMDb - Universal"),
        ("The 1941 Orson Welles drama revolving around the dying word 'Rosebud', widely hailed as a cinematic masterpiece.", "Citizen Kane", ["citizen kane"], "IMDb - RKO"),
        ("The 1942 wartime romantic drama starring Humphrey Bogart and Ingrid Bergman set in Morocco.", "Casablanca", ["casablanca film"], "IMDb - Warner Bros"),
        ("The 1979 sci-fi horror film directed by Ridley Scott featuring the tagline 'In space no one can hear you scream'.", "Alien", ["alien film", "xenomorph"], "IMDb - 20th Century Fox"),
        ("The actress who played Ripley in the Alien sci-fi franchise.", "Sigourney Weaver", ["weaver"], "IMDb - 20th Century Fox"),
        ("The director who won Best Director Oscars for Brokeback Mountain (2005) and Life of Pi (2012).", "Ang Lee", ["lee"], "IMDb - Academy Awards"),
        ("The 2003 film in Peter Jackson's trilogy that swept all 11 Academy Awards it was nominated for.", "The Return of the King", ["return of the king"], "IMDb - Academy Awards"),
        ("The 1995 crime drama directed by Michael Mann featuring the first on-screen dialogue between Al Pacino and Robert De Niro.", "Heat", ["heat 1995"], "IMDb - Warner Bros"),
        ("The 1987 sci-fi action film where Arnold Schwarzenegger encounters an invisible alien trophy hunter in the jungle.", "Predator", ["predator film"], "IMDb - 20th Century Fox"),
        ("The Japanese animation studio co-founded by Hayao Miyazaki behind Spirited Away and My Neighbor Totoro.", "Studio Ghibli", ["ghibli"], "IMDb - Animation Cinema"),
        ("The 2001 Studio Ghibli film that won the Academy Award for Best Animated Feature in 2003.", "Spirited Away", ["sen to chihiro"], "IMDb - Studio Ghibli"),
        ("The 1950 Billy Wilder film noir set in Hollywood starring Gloria Swanson as faded silent star Norma Desmond.", "Sunset Boulevard", ["sunset blvd"], "IMDb - Paramount"),
        ("The actor who won an Oscar for playing Daniel Plainview in Paul Thomas Anderson's There Will Be Blood.", "Daniel Day-Lewis", ["day-lewis", "day lewis"], "IMDb - Paramount Vantage"),
        ("The only actor to win three Academy Awards for Best Actor in a Leading Role.", "Daniel Day-Lewis", ["day-lewis"], "IMDb - Academy Awards"),
        ("The 1980 Star Wars sequel widely considered the best in the franchise, directed by Irvin Kershner.", "The Empire Strikes Back", ["empire strikes back"], "IMDb - Lucasfilm"),
        ("The 2007 Coen brothers neo-western thriller based on Cormac McCarthy's novel featuring Anton Chigurh.", "No Country for Old Men", ["no country for old men"], "IMDb - Miramax"),
        ("The Spanish actor who won an Oscar for playing the chilling hitman Anton Chigurh in No Country for Old Men.", "Javier Bardem", ["bardem"], "IMDb - Academy Awards"),
        ("The 1998 Coen brothers cult comedy starring Jeff Bridges as 'The Dude'.", "The Big Lebowski", ["big lebowski"], "IMDb - Gramercy"),
        ("The 1997 psychological drama about a janitor math genius at MIT starring Matt Damon and Robin Williams.", "Good Will Hunting", ["good will hunting"], "IMDb - Miramax"),
        ("The 1976 psychological drama directed by Martin Scorsese starring Robert De Niro as alienated cab driver Travis Bickle.", "Taxi Driver", ["taxi driver film"], "IMDb - Columbia"),
        ("The 1995 crime mystery directed by Bryan Singer famous for the plot twist revealing Keyser Söze.", "The Usual Suspects", ["usual suspects"], "IMDb - PolyGram"),
        ("The 1982 sci-fi film directed by John Carpenter about a shape-shifting alien creature in an Antarctic research station.", "The Thing", ["john carpenters the thing"], "IMDb - Universal"),
        ("The 1990 mob masterpiece directed by Martin Scorsese based on Nicholas Pileggi's book Wiseguy.", "Goodfellas", ["goodfellas film"], "IMDb - Warner Bros"),
        ("The 1974 neo-noir mystery directed by Roman Polanski starring Jack Nicholson as private detective J.J. Gittes.", "Chinatown", ["chinatown film"], "IMDb - Paramount"),
        ("The 1957 courtroom drama directed by Sidney Lumet featuring twelve jurors debating a murder verdict in one room.", "12 Angry Men", ["twelve angry men"], "IMDb - United Artists"),
        ("The 2017 horror-satire directed by Jordan Peele that won an Academy Award for Best Original Screenplay.", "Get Out", ["get out film"], "IMDb - Universal"),
        ("The 2023 biographical epic directed by Christopher Nolan that swept 7 Academy Awards including Best Picture.", "Oppenheimer", ["oppenheimer film"], "IMDb - Universal"),
        ("The Irish actor who won the Best Actor Oscar in 2024 for portraying J. Robert Oppenheimer.", "Cillian Murphy", ["murphy"], "IMDb - Universal"),
        ("The 1981 epic historical adventure that introduced Indiana Jones searching for the Ark of the Covenant.", "Raiders of the Lost Ark", ["raiders of the lost ark"], "IMDb - Paramount"),
        ("The 2002 musical directed by Rob Marshall that became the first musical to win Best Picture since Oliver! in 1968.", "Chicago", ["chicago musical film"], "IMDb - Miramax"),
        ("The 2014 dark comedy directed by Alejandro G. Iñárritu starring Michael Keaton that won Best Picture.", "Birdman", ["birdman or the unexpected virtue of ignorance"], "IMDb - Fox Searchlight"),
        ("The 1999 found-footage horror sensation made on a shoestring budget that grossed over $240 million.", "The Blair Witch Project", ["blair witch project", "blair witch"], "IMDb - Artisan"),
        ("The Italian neo-realist 1948 classic directed by Vittorio De Sica about a father and son searching for a stolen two-wheeler.", "Bicycle Thieves", ["the bicycle thief", "ladri di biciclette"], "IMDb - Italian Cinema"),
        ("The 1954 Japanese masterpiece directed by Akira Kurosawa about a village hiring samurai for defense.", "Seven Samurai", ["shichinin no samurai"], "IMDb - Toho"),
        ("The 2011 silent French comedy-drama directed by Michel Hazanavicius that won five Academy Awards including Best Picture.", "The Artist", ["the artist film"], "IMDb - Warner Bros"),
        ("The 1992 debut crime thriller written and directed by Quentin Tarantino about a jewelry heist gone wrong.", "Reservoir Dogs", ["reservoir dogs"], "IMDb - Miramax"),
        ("The 1998 dark satirical comedy-drama starring Jim Carrey as a man unaware his entire life is a 24/7 reality television show.", "The Truman Show", ["truman show"], "IMDb - Paramount")
    ]
    for c, a, ac, s in q300: items.append((300, c, a, ac, s))

    # --- $400: Advanced / Oscar & Auteur History (40 items) ---
    q400 = [
        ("The only film in history to win all Big Five Academy Awards: Picture, Director, Actor, Actress, and Screenplay, alongside One Flew Over the Cuckoo's Nest and The Silence of the Lambs.", "It Happened One Night", ["it happened one night 1934"], "IMDb - Academy Awards Records"),
        ("The French New Wave masterpiece directed by François Truffaut in 1959 featuring Antoine Doinel.", "The 400 Blows", ["les quatre cents coups", "400 blows"], "IMDb - French Cinema"),
        ("The 1966 Italian epic western starring Clint Eastwood that concludes with a three-way standoff at Sad Hill Cemetery.", "The Good, the Bad and the Ugly", ["il buono il brutto il cattivo"], "IMDb - Sergio Leone"),
        ("The 1958 Alfred Hitchcock psychological thriller starring James Stewart as a retired detective suffering from acrophobia.", "Vertigo", ["vertigo film"], "IMDb - Universal"),
        ("The Swedish director of The Seventh Seal and Persona, famous for depicting a knight playing chess with Death.", "Ingmar Bergman", ["bergman"], "IMDb - World Cinema"),
        ("The 1927 groundbreaking German expressionist science-fiction film directed by Fritz Lang set in a futuristic dystopia.", "Metropolis", ["metropolis 1927"], "IMDb - UFA"),
        ("The 1962 sweeping British epic directed by David Lean starring Peter O'Toole as an enigmatic British officer in Arabia.", "Lawrence of Arabia", ["lawrence of arabia"], "IMDb - Columbia"),
        ("The 1971 crime drama directed by William Friedkin featuring Gene Hackman as NYPD detective Popeye Doyle.", "The French Connection", ["french connection"], "IMDb - 20th Century Fox"),
        ("The Mexican filmmaker who won Best Director Oscars for both Gravity (2013) and Roma (2018).", "Alfonso Cuaron", ["alfonso cuarón", "cuaron"], "IMDb - Academy Awards"),
        ("The 1980 biographical sports drama directed by Martin Scorsese starring Robert De Niro as boxer Jake LaMotta.", "Raging Bull", ["raging bull"], "IMDb - United Artists"),
        ("The 1974 Francis Ford Coppola sequel that became the first film sequel in history to win the Best Picture Oscar.", "The Godfather Part II", ["the godfather part 2"], "IMDb - Paramount"),
        ("The 1975 psychological comedy-drama directed by Miloš Forman starring Jack Nicholson in an Oregon psychiatric facility.", "One Flew Over the Cuckoo's Nest", ["cuckoos nest", "one flew over the cuckoos nest"], "IMDb - United Artists"),
        ("The 1925 Soviet silent propaganda film directed by Sergei Eisenstein featuring the famous Odessa Steps massacre sequence.", "Battleship Potemkin", ["bronenosets potemkin"], "IMDb - Soviet Cinema"),
        ("The 1948 film noir directed by Carol Reed set in post-WWII divided Vienna featuring Orson Welles as Harry Lime.", "The Third Man", ["the third man"], "IMDb - British Film Institute"),
        ("The 1954 drama directed by Elia Kazan where Marlon Brando delivers the iconic line 'I coulda been a contender'.", "On the Waterfront", ["on the waterfront"], "IMDb - Columbia"),
        ("The 1967 road comedy-drama starring Warren Beatty and Faye Dunaway that signaled the dawn of the New Hollywood era.", "Bonnie and Clyde", ["bonnie and clyde film"], "IMDb - Warner Bros"),
        ("The 1979 Vietnam War epic directed by Francis Ford Coppola loosely inspired by Joseph Conrad's Heart of Darkness.", "Apocalypse Now", ["apocalypse now"], "IMDb - United Artists"),
        ("The 1952 musical romantic comedy starring Gene Kelly, Donald O'Connor, and Debbie Reynolds depicting Hollywood's transition to talkies.", "Singin' in the Rain", ["singing in the rain"], "IMDb - MGM"),
        ("The 1977 comedy directed by and starring Woody Allen alongside Diane Keaton that won four Oscars including Best Picture.", "Annie Hall", ["annie hall"], "IMDb - United Artists"),
        ("The 1957 British-American WWII epic directed by David Lean set in a Japanese prisoner-of-war camp in Burma.", "The Bridge on the River Kwai", ["bridge on the river kwai"], "IMDb - Columbia"),
        ("The 1940 satirical comedy directed by Charlie Chaplin in which he plays both an oppressed Jewish barber and a fascist dictator.", "The Great Dictator", ["the great dictator"], "IMDb - United Artists"),
        ("The 1953 Japanese masterpiece directed by Yasujirō Ozu depicting an elderly couple visiting their busy adult children.", "Tokyo Story", ["tōkyō monogatari"], "IMDb - Shochiku"),
        ("The 1966 Michelangelo Antonioni mystery thriller about a London fashion photographer who unwittingly photographs a murder.", "Blow-Up", ["blowup", "blow up"], "IMDb - MGM"),
        ("The 1974 horror masterpiece directed by Tobe Hooper featuring the chainsaw-wielding cannibal Leatherface.", "The Texas Chain Saw Massacre", ["texas chainsaw massacre"], "IMDb - Vortex"),
        ("The 1931 horror film starring Boris Karloff as the tragic Creature brought to life by electricity.", "Frankenstein", ["frankenstein 1931"], "IMDb - Universal Monsters"),
        ("The Hungarian-American actor who defined the cinematic role of Count Dracula in Tod Browning's 1931 classic.", "Bela Lugosi", ["lugosi"], "IMDb - Universal Monsters"),
        ("The 1985 biographical epic directed by Sydney Pollack starring Meryl Streep and Robert Redford that won seven Oscars.", "Out of Africa", ["out of africa"], "IMDb - Universal"),
        ("The French director who directed the groundbreaking New Wave romantic crime drama Breathless (À bout de souffle) in 1960.", "Jean-Luc Godard", ["godard"], "IMDb - French New Wave"),
        ("The 2000 martial arts epic directed by Ang Lee starring Chow Yun-fat and Michelle Yeoh that won four Oscars.", "Crouching Tiger, Hidden Dragon", ["crouching tiger hidden dragon"], "IMDb - Sony Pictures Classics"),
        ("The 1955 drama starring James Dean as a troubled teenager, released just a month after Dean's fatal car crash.", "Rebel Without a Cause", ["rebel without a cause"], "IMDb - Warner Bros"),
        ("The 1971 dystopian crime film directed by Stanley Kubrick based on Anthony Burgess's novella starring Malcolm McDowell.", "A Clockwork Orange", ["clockwork orange"], "IMDb - Warner Bros"),
        ("The 1969 counterculture road movie starring Peter Fonda and Dennis Hopper riding chopper motorcycles across America.", "Easy Rider", ["easy rider"], "IMDb - Columbia"),
        ("The 1993 historical drama directed by Jane Campion starring Holly Hunter as a mute Scottish pianist sent to New Zealand.", "The Piano", ["the piano"], "IMDb - Miramax"),
        ("The 1979 courtroom drama starring Dustin Hoffman and Meryl Streep navigating a painful divorce and child custody battle.", "Kramer vs. Kramer", ["kramer vs kramer"], "IMDb - Columbia"),
        ("The Russian master of poetic cinema who directed Solaris (1972), Stalker (1979), and The Mirror (1975).", "Andrei Tarkovsky", ["tarkovsky"], "IMDb - Soviet Cinema"),
        ("The 1944 Billy Wilder film noir starring Fred MacMurray and Barbara Stanwyck based on James M. Cain's crime novella.", "Double Indemnity", ["double indemnity"], "IMDb - Paramount"),
        ("The 1984 Czech-American period drama directed by Miloš Forman chronicling the rivalry between Mozart and Salieri.", "Amadeus", ["amadeus film"], "IMDb - Orion"),
        ("The 1997 drama directed by Paul Thomas Anderson exploring the 1970s and 80s Golden Age of the San Fernando Valley adult film industry.", "Boogie Nights", ["boogie nights"], "IMDb - New Line"),
        ("The 1957 Ingmar Bergman historical drama where a medieval knight challenges Antonius Block to a game of chess against Death.", "The Seventh Seal", ["det sjunde inseglet"], "IMDb - Swedish Cinema"),
        ("The 1964 Stanley Kubrick satirical cold-war black comedy starring Peter Sellers in three different roles.", "Dr. Strangelove", ["dr strangelove", "doctor strangelove"], "IMDb - Columbia")
    ]
    for c, a, ac, s in q400: items.append((400, c, a, ac, s))

    # --- $500: Expert / Cinema Trivia Masters (40 items) ---
    q500 = [
        ("The 1928 silent French masterpiece directed by Carl Theodor Dreyer starring Maria Falconetti in a harrowing emotional performance.", "The Passion of Joan of Arc", ["passion of joan of arc", "la passion de jeanne d'arc"], "IMDb - Silent Cinema"),
        ("The very first feature-length film with synchronized dialogue and singing sequences, released in October 1927.", "The Jazz Singer", ["the jazz singer 1927"], "IMDb - Warner Bros Records"),
        ("The first movie ever to win the Academy Award for Best Picture (then termed 'Outstanding Picture') in May 1929.", "Wings", ["wings 1927"], "IMDb - Academy Awards Records"),
        ("The legendary cinematographer who shot Citizen Kane, The Grapes of Wrath, and The Best Years of Our Lives, pioneering deep focus.", "Gregg Toland", ["toland"], "IMDb - Cinematography"),
        ("The 1961 French Left Bank film directed by Alain Resnais known for its ambiguous labyrinthine narrative in a grand chateau.", "Last Year at Marienbad", ["l'année dernière à marienbad"], "IMDb - French Cinema"),
        ("The only woman to win the Palme d'Or at Cannes twice, for Anatomy of a Fall (2023) and The Piano (1993, tied with Chen Kaige).", "Jane Campion", ["campion", "justine triet"], "IMDb - Cannes Film Festival"),
        ("The 1975 Jeanne Dielman feminist art cinema masterpiece directed by Belgian filmmaker Chantal Akerman.", "Jeanne Dielman", ["jeanne dielman, 23 quai du commerce, 1080 bruxelles"], "IMDb - Sight & Sound Greatest Films"),
        ("The Italian art director and production designer who won three Oscars for Barry Lyndon, The Aviator, and Sweeney Todd.", "Dante Ferretti", ["ferretti"], "IMDb - Academy Awards"),
        ("The 1972 Soviet sci-fi film directed by Andrei Tarkovsky based on Stanislaw Lem's philosophical novel about an ocean planet.", "Solaris", ["solyaris"], "IMDb - Mosfilm"),
        ("The legendary editor who cut Martin Scorsese's films for over 40 years including Raging Bull, Goodfellas, and The Wolf of Wall Street.", "Thelma Schoonmaker", ["schoonmaker"], "IMDb - Film Editing"),
        ("The 1938 French cinematic masterwork directed by Jean Renoir set at a country estate on the brink of World War II.", "The Rules of the Game", ["la règle du jeu"], "IMDb - French Cinema"),
        ("The 1955 Danish religious drama directed by Carl Theodor Dreyer culminating in a resurrection in a rural farming family.", "Ordet", ["the word"], "IMDb - World Cinema"),
        ("The first animated film ever submitted for and winning the prestigious Golden Bear at the Berlin International Film Festival in 2002.", "Spirited Away", ["sen to chihiro"], "IMDb - Berlin Film Festival"),
        ("The German director who directed Fitzcarraldo, Aguirre: The Wrath of God, and Nosferatu the Vampyre starring Klaus Kinski.", "Werner Herzog", ["herzog"], "IMDb - New German Cinema"),
        ("The 1946 French surrealist fairy tale film directed by Jean Cocteau starring Jean Marais and Josette Day.", "Beauty and the Beast", ["la belle et la bête"], "IMDb - French Fantasy"),
        ("The only actor to win an Academy Award for portraying a real-life Oscar winner, playing Katharine Hepburn in The Aviator.", "Cate Blanchett", ["blanchett"], "IMDb - Academy Awards"),
        ("The 1966 epic historical war drama directed by Gillo Pontecorvo depicting the Algerian war of independence against French paratroopers.", "The Battle of Algiers", ["la battaglia di algeri"], "IMDb - World Cinema"),
        ("The 1932 Universal horror film directed by Tod Browning starring actual sideshow performers that was banned in the UK for 30 years.", "Freaks", ["freaks 1932"], "IMDb - Cult Cinema"),
        ("The 1960 psychological thriller directed by Michael Powell about a serial killer who films his victims' fear, which destroyed Powell's career.", "Peeping Tom", ["peeping tom film"], "IMDb - British Cinema"),
        ("The first African feature film to gain international recognition, directed by Ousmane Sembène in 1966.", "Black Girl", ["la noire de..."], "IMDb - African Cinema"),
        ("The 1977 Japanese surrealist comedy-horror house film directed by Nobuhiko Obayashi.", "House", ["hausu"], "IMDb - Japanese Cinema"),
        ("The 1973 French drama directed by Jean Eustache featuring long conversational scenes in Paris starring Jean-Pierre Léaud.", "The Mother and the Whore", ["la maman et la putain"], "IMDb - French Cinema"),
        ("The cinematographer who won three consecutive Academy Awards for Gravity, Birdman, and The Revenant.", "Emmanuel Lubezki", ["lubezki", "el chivo"], "IMDb - Academy Awards"),
        ("The 1969 Costa-Gavras political thriller based on the assassination of Greek politician Grigoris Lambrakis, winning the Foreign Language Oscar.", "Z", ["z film"], "IMDb - World Cinema"),
        ("The 1955 French suspense thriller directed by Henri-Georges Clouzot featuring a twist ending with a school swimming pool.", "Les Diaboliques", ["diabolique"], "IMDb - French Cinema"),
        ("The 1932 pre-Code musical comedy directed by Ernst Lubitsch starring Herbert Marshall and Miriam Hopkins as sophisticated jewel thieves.", "Trouble in Paradise", ["trouble in paradise"], "IMDb - Paramount"),
        ("The 1922 silent Scandinavian documentary-style horror film directed by Benjamin Christensen exploring witchcraft through the ages.", "Haxan", ["häxan", "witchcraft through the ages"], "IMDb - Silent Cinema"),
        ("The 1953 French rural crime thriller directed by Henri-Georges Clouzot starring Yves Montand transporting nitroglycerin.", "The Wages of Fear", ["le salaire de la peur"], "IMDb - French Cinema"),
        ("The 1985 Soviet anti-war psychological drama directed by Elem Klimov depicting the Nazi occupation of Belarus through a boy's eyes.", "Come and See", ["idi i smotri"], "IMDb - Soviet Cinema"),
        ("The 1970 satirical military comedy directed by Robert Altman that originated the hit TV show M*A*S*H.", "MASH", ["m*a*s*h"], "IMDb - 20th Century Fox"),
        ("The 1949 British dark comedy directed by Robert Hamer where Alec Guinness plays eight different members of the aristocratic D'Ascoyne family.", "Kind Hearts and Coronets", ["kind hearts and coronets"], "IMDb - Ealing Studios"),
        ("The 1966 epic Soviet film adaptation of Leo Tolstoy's War and Peace directed by Sergei Bondarchuk that cost over $100M inflation-adjusted.", "War and Peace", ["voyna i mir"], "IMDb - Academy Awards"),
        ("The 1975 Stanley Kubrick period drama renowned for being shot almost entirely under natural candlelight using Zeiss f/0.7 NASA lenses.", "Barry Lyndon", ["barry lyndon"], "IMDb - Warner Bros"),
        ("The 1953 western directed by George Stevens starring Alan Ladd as an enigmatic gunslinger defending homesteaders.", "Shane", ["shane 1953"], "IMDb - Paramount"),
        ("The 1994 Hungarian slow-cinema masterpiece directed by Béla Tarr spanning over 7 hours based on a novel by László Krasznahorkai.", "Satantango", ["sátántangó"], "IMDb - World Cinema"),
        ("The 1936 British psychological thriller directed by Alfred Hitchcock starring Sylvia Sidney, based on Joseph Conrad's The Secret Agent.", "Sabotage", ["sabotage 1936"], "IMDb - British Cinema"),
        ("The 1971 Australian survival drama directed by Nicolas Roeg about two white children lost in the Australian Outback with an Aboriginal youth.", "Walkabout", ["walkabout film"], "IMDb - Australian Cinema"),
        ("The 1967 French crime noir directed by Jean-Pierre Melville starring Alain Delon as the impeccably trench-coated hitman Jef Costello.", "Le Samourai", ["le samouraï"], "IMDb - French Cinema"),
        ("The 1948 Italian neorealist drama directed by Luchino Visconti filmed with non-professional fishermen in Aci Trezza, Sicily.", "La Terra Trema", ["la terra trema"], "IMDb - Italian Cinema"),
        ("The first feature film shot in three-strip Technicolor, released by RKO Pictures in 1935.", "Becky Sharp", ["becky sharp 1935"], "IMDb - Technicolor History")
    ]
    for c, a, ac, s in q400: items.append((500, c, a, ac, s))

    return items

if __name__ == "__main__":
    qs = get_movies_questions()
    print(f"Generated {len(qs)} movies questions!")
