# Science & Cosmos (200 questions: 40 per tier: 100, 200, 300, 400, 500)

def get_science_questions():
    items = []
    
    # --- $100: Novice / Fundamental (40 items) ---
    q100 = [
        ("The closest star to Earth and the center of our solar system.", "The Sun", ["sun", "sol"], "Wikipedia - The Sun"),
        ("The chemical formula for water consisting of hydrogen and oxygen.", "H2O", ["water", "h 2 o"], "Wikipedia - Water"),
        ("The force that pulls objects toward the center of the Earth.", "Gravity", ["gravitational force"], "Wikipedia - Gravitation"),
        ("The planet known as the 'Red Planet' due to iron oxide on its surface.", "Mars", ["planet mars"], "Wikipedia - Mars"),
        ("The hardest known natural mineral on Mohs hardness scale.", "Diamond", ["diamonds"], "Wikipedia - Diamond"),
        ("The largest planet in our solar system, famous for its Great Red Spot.", "Jupiter", ["planet jupiter"], "Wikipedia - Jupiter"),
        ("The breathing gas essential for human life that makes up ~21% of air.", "Oxygen", ["o2", "oxygen gas"], "Wikipedia - Atmospheric Chemistry"),
        ("The boiling point of pure water at standard atmospheric pressure in Celsius.", "100 degrees", ["100", "100 c", "100 celsius"], "Wikipedia - Boiling Point"),
        ("The freezing point of water in Celsius.", "0 degrees", ["0", "0 c", "0 celsius"], "Wikipedia - Freezing Point"),
        ("The natural satellite that orbits the planet Earth.", "The Moon", ["moon", "luna"], "Wikipedia - Moon"),
        ("The organ in the human body responsible for pumping blood through the circulatory system.", "Heart", ["the heart", "human heart"], "Wikipedia - Heart"),
        ("The green pigment found in plants used to absorb energy from light.", "Chlorophyll", ["chlorophyl"], "Wikipedia - Chlorophyll"),
        ("The process plants use to convert sunlight, carbon dioxide, and water into glucose.", "Photosynthesis", ["photosynthesizing"], "Wikipedia - Photosynthesis"),
        ("The center of an atom consisting of protons and neutrons.", "Nucleus", ["atomic nucleus"], "Wikipedia - Atomic Nucleus"),
        ("The layer of gases surrounding the Earth that protects it from solar radiation.", "Atmosphere", ["the atmosphere", "earth atmosphere"], "Wikipedia - Atmosphere"),
        ("The bones that protect the human brain from injury.", "Skull", ["cranium", "the skull"], "Wikipedia - Skull"),
        ("The number of bones in an adult human skeleton.", "206", ["206 bones"], "Wikipedia - Human Skeleton"),
        ("The closest planet to the Sun in our solar system.", "Mercury", ["planet mercury"], "Wikipedia - Mercury"),
        ("The state of matter that has a definite volume but no fixed shape, taking the shape of its container.", "Liquid", ["liquids"], "Wikipedia - State of Matter"),
        ("The tiny organisms that can cause infectious diseases, often treated with antibiotics.", "Bacteria", ["bacterium"], "Wikipedia - Bacteria"),
        ("The planet famous for its prominent and extensive ring system.", "Saturn", ["planet saturn"], "Wikipedia - Saturn"),
        ("The sense detected by the olfactory receptors in the human nose.", "Smell", ["olfaction", "sense of smell"], "Wikipedia - Olfaction"),
        ("The unit used to measure electric potential difference, named after Alessandro Volta.", "Volt", ["volts", "voltage"], "Wikipedia - Volt"),
        ("The celestial body made of ice, dust, and rock that produces a glowing tail near the Sun.", "Comet", ["comets"], "Wikipedia - Comet"),
        ("The colored circle of tissue in the eye that regulates pupil size.", "Iris", ["the iris"], "Wikipedia - Iris"),
        ("The white blood cells' primary role in the human body.", "Fighting infection", ["immune system", "fighting disease", "defense"], "Wikipedia - White Blood Cells"),
        ("The fastest thing in the universe, traveling at ~300,000 km per second in a vacuum.", "Light", ["speed of light", "photons"], "Wikipedia - Speed of Light"),
        ("The chemical symbol for table salt is NaCl, sodium and this halogen.", "Chlorine", ["chloride"], "Wikipedia - Sodium Chloride"),
        ("The instrument used by astronomers to view distant stars and galaxies.", "Telescope", ["telescopes"], "Wikipedia - Telescope"),
        ("The molten rock beneath the Earth's surface before it erupts as lava.", "Magma", ["magma chamber"], "Wikipedia - Magma"),
        ("The galaxy that contains our solar system.", "Milky Way", ["the milky way", "milky way galaxy"], "Wikipedia - Milky Way"),
        ("The device used to measure atmospheric temperature.", "Thermometer", ["thermometers"], "Wikipedia - Thermometer"),
        ("The scientific study of living organisms.", "Biology", ["biological sciences"], "Wikipedia - Biology"),
        ("The common gas exhaled by humans and absorbed by trees.", "Carbon Dioxide", ["co2", "carbon dioxide gas"], "Wikipedia - Carbon Dioxide"),
        ("The human body's largest external organ.", "Skin", ["the skin", "epidermis"], "Wikipedia - Skin"),
        ("The dwarf planet in the Kuiper belt formerly classified as the ninth planet.", "Pluto", ["dwarf planet pluto"], "Wikipedia - Pluto"),
        ("The sound waves with frequencies higher than the upper audible limit of human hearing.", "Ultrasound", ["ultrasonic"], "Wikipedia - Ultrasound"),
        ("The flow of electrical charge through a conductor.", "Electric Current", ["current", "electricity"], "Wikipedia - Electric Current"),
        ("The substance formed when two or more chemical elements are chemically bonded together.", "Compound", ["chemical compound"], "Wikipedia - Chemical Compound"),
        ("The scientist famous for formulating the law of universal gravitation after seeing an apple fall.", "Isaac Newton", ["newton", "sir isaac newton"], "Wikipedia - Isaac Newton")
    ]
    for c, a, ac, s in q100: items.append((100, c, a, ac, s))

    # --- $200: Moderate / Core Concepts (40 items) ---
    q200 = [
        ("The subatomic particle that carries a negative electrical charge.", "Electron", ["electrons"], "Wikipedia - Electron"),
        ("The positively charged particle located in the nucleus of an atom.", "Proton", ["protons"], "Wikipedia - Proton"),
        ("The uncharged subatomic particle discovered by James Chadwick in 1932.", "Neutron", ["neutrons"], "Wikipedia - Neutron"),
        ("The molecule that carries genetic instructions for development and functioning in all known organisms.", "DNA", ["deoxyribonucleic acid"], "Wikipedia - DNA"),
        ("The scientist who proposed the theory of evolution by natural selection in 'On the Origin of Species'.", "Charles Darwin", ["darwin"], "Wikipedia - Charles Darwin"),
        ("The scale used to measure the acidity or basicity of an aqueous solution from 0 to 14.", "pH scale", ["ph"], "Wikipedia - pH"),
        ("The hottest planet in our solar system due to a runaway greenhouse effect.", "Venus", ["planet venus"], "Wikipedia - Venus"),
        ("The organelle known as the 'powerhouse of the cell' for producing ATP.", "Mitochondria", ["mitochondrion"], "Wikipedia - Mitochondrion"),
        ("The medical substance discovered by Alexander Fleming from Penicillium mold.", "Penicillin", ["antibiotic penicillin"], "Wikipedia - Penicillin"),
        ("The chemical element with atomic number 1, the most abundant element in the universe.", "Hydrogen", ["h", "hydrogen gas"], "Wikipedia - Hydrogen"),
        ("The transfer of heat through electromagnetic waves without needing a medium.", "Radiation", ["thermal radiation"], "Wikipedia - Thermal Radiation"),
        ("The geological fault line that runs ~800 miles through California.", "San Andreas Fault", ["san andreas"], "Wikipedia - San Andreas Fault"),
        ("The phenomenon where an electric current generates a magnetic field, and vice versa.", "Electromagnetism", ["electromagnetic induction"], "Wikipedia - Electromagnetism"),
        ("The boundary in the atmosphere that absorbs most of the Sun's harmful ultraviolet radiation.", "Ozone Layer", ["ozone", "o3 layer"], "Wikipedia - Ozone Layer"),
        ("The three bones in the human middle ear: malleus, incus, and this smallest bone.", "Stapes", ["stirrup", "stapes bone"], "Wikipedia - Stapes"),
        ("The scientist who formulated the three laws of planetary motion.", "Johannes Kepler", ["kepler"], "Wikipedia - Johannes Kepler"),
        ("The chemical element with symbol Fe, crucial for oxygen transport in hemoglobin.", "Iron", ["fe"], "Wikipedia - Iron"),
        ("The process by which a solid changes directly into a gas without becoming a liquid.", "Sublimation", ["sublimating"], "Wikipedia - Sublimation"),
        ("The SI unit of force, named after the formulator of classical mechanics.", "Newton", ["newtons", "n"], "Wikipedia - Newton"),
        ("The giant cloud of dust and gas in space where new stars are born.", "Nebula", ["nebulae"], "Wikipedia - Nebula"),
        ("The blood vessels that carry oxygenated blood away from the heart to the body.", "Arteries", ["artery"], "Wikipedia - Artery"),
        ("The process of cell division that produces four genetically diverse daughter cells with half the chromosomes.", "Meiosis", ["reduction division"], "Wikipedia - Meiosis"),
        ("The process of regular somatic cell division resulting in two identical daughter cells.", "Mitosis", ["mitotic division"], "Wikipedia - Mitosis"),
        ("The point in a lever system around which the lever pivots.", "Fulcrum", ["pivot"], "Wikipedia - Lever"),
        ("The SI unit of electrical resistance, named after Georg Ohm.", "Ohm", ["ohms"], "Wikipedia - Ohm"),
        ("The organ in the human body that produces insulin and digestive enzymes.", "Pancreas", ["the pancreas"], "Wikipedia - Pancreas"),
        ("The element with atomic number 6, forming the backbone of all organic molecules.", "Carbon", ["c"], "Wikipedia - Carbon"),
        ("The second most abundant gas in Earth's atmosphere after nitrogen.", "Oxygen", ["o2"], "Wikipedia - Atmosphere of Earth"),
        ("The bending of light as it passes from one medium into another of different density.", "Refraction", ["refracting"], "Wikipedia - Refraction"),
        ("The scientist who first observed cells under a microscope and coined the term 'cell'.", "Robert Hooke", ["hooke"], "Wikipedia - Robert Hooke"),
        ("The principle stating that an increase in the speed of a fluid occurs simultaneously with a decrease in pressure.", "Bernoulli's Principle", ["bernoulli", "bernoullis principle"], "Wikipedia - Bernoulli's Principle"),
        ("The temperature scale where 0 corresponds to absolute zero (-273.15 °C).", "Kelvin", ["kelvin scale", "k"], "Wikipedia - Kelvin"),
        ("The geological era known as the 'Age of Reptiles' and dinosaurs.", "Mesozoic Era", ["mesozoic"], "Wikipedia - Mesozoic"),
        ("The dense celestial remnant formed when a massive star collapses under gravity, with infinite density at its center.", "Black Hole", ["black holes"], "Wikipedia - Black Hole"),
        ("The organelle in plant cells where photosynthesis takes place.", "Chloroplast", ["chloroplasts"], "Wikipedia - Chloroplast"),
        ("The unit of frequency equal to one cycle per second, named after Heinrich Hertz.", "Hertz", ["hz"], "Wikipedia - Hertz"),
        ("The law stating that energy cannot be created or destroyed, only transformed.", "Conservation of Energy", ["first law of thermodynamics"], "Wikipedia - Conservation of Energy"),
        ("The branch of medicine that specializes in the diagnosis and treatment of cancer.", "Oncology", ["cancer medicine"], "Wikipedia - Oncology"),
        ("The rocky celestial bodies orbiting the Sun predominantly between Mars and Jupiter.", "Asteroids", ["asteroid belt"], "Wikipedia - Asteroid"),
        ("The Polish-French scientist who won Nobel Prizes in both Physics and Chemistry for work on radioactivity.", "Marie Curie", ["curie", "madame curie"], "Wikipedia - Marie Curie")
    ]
    for c, a, ac, s in q200: items.append((200, c, a, ac, s))

    # --- $300: Intermediate / Applied Science (40 items) ---
    q300 = [
        ("The letter representing the speed of light in Einstein's mass-energy equivalence equation E=mc².", "c", ["the letter c", "speed of light"], "Wikipedia - Mass-energy equivalence"),
        ("The elemental metal with the highest electrical conductivity of all metals.", "Silver", ["ag"], "Wikipedia - Silver"),
        ("The famous double-helix structure of DNA was modeled in 1953 by James Watson and this British scientist.", "Francis Crick", ["crick"], "Wikipedia - Francis Crick"),
        ("The female X-ray crystallographer whose Photo 51 was critical to deciphering DNA's structure.", "Rosalind Franklin", ["franklin"], "Wikipedia - Rosalind Franklin"),
        ("The element with atomic number 79, long prized as a precious malleable yellow metal.", "Gold", ["au"], "Wikipedia - Gold"),
        ("The boundary between Earth's crust and the underlying mantle.", "Mohorovicic discontinuity", ["moho", "mohorovičić"], "Wikipedia - Mohorovičić discontinuity"),
        ("The law stating that the current through a conductor between two points is directly proportional to voltage.", "Ohm's Law", ["ohms law"], "Wikipedia - Ohm's Law"),
        ("The radioactive gas with chemical symbol Rn, formed from the natural decay of uranium in soil.", "Radon", ["rn"], "Wikipedia - Radon"),
        ("The organ responsible for filtering blood, removing waste products, and producing urine.", "Kidney", ["kidneys"], "Wikipedia - Kidney"),
        ("The fundamental constant named after Max Planck, relating photon energy to frequency.", "Planck's Constant", ["planck constant", "h"], "Wikipedia - Planck constant"),
        ("The theory that Earth's outer shell is divided into large moving slabs that glide over the mantle.", "Plate Tectonics", ["continental drift"], "Wikipedia - Plate Tectonics"),
        ("The planet in our solar system with the shortest rotational period (fastest day, under 10 hours).", "Jupiter", ["planet jupiter"], "Wikipedia - Rotation of Jupiter"),
        ("The rare noble gas with atomic number 36 used in high-speed flash photography and lasers.", "Krypton", ["kr"], "Wikipedia - Krypton"),
        ("The blood protein responsible for carrying oxygen from the lungs to the tissues.", "Hemoglobin", ["haemoglobin"], "Wikipedia - Hemoglobin"),
        ("The principle stating that it is impossible to simultaneously know both the precise position and momentum of a subatomic particle.", "Heisenberg Uncertainty Principle", ["uncertainty principle", "heisenberg"], "Wikipedia - Uncertainty Principle"),
        ("The geological epoch that began approximately 11,700 years ago after the last glacial period.", "Holocene", ["holocene epoch"], "Wikipedia - Holocene"),
        ("The SI unit of magnetic flux density, named after the Serbian-American inventor of AC power.", "Tesla", ["t"], "Wikipedia - Tesla (unit)"),
        ("The hormone produced by the adrenal glands that triggers the 'fight-or-flight' response.", "Adrenaline", ["epinephrine"], "Wikipedia - Adrenaline"),
        ("The scientist who first stated that pressure exerted on an enclosed fluid is transmitted equally in all directions.", "Blaise Pascal", ["pascal"], "Wikipedia - Pascal's Law"),
        ("The bright explosion of a star that reaches the end of its life cycle, briefly outshining galaxies.", "Supernova", ["supernovae"], "Wikipedia - Supernova"),
        ("The only two chemical elements on the periodic table that are liquid at standard room temperature: bromine and this.", "Mercury", ["quicksilver", "hg"], "Wikipedia - Liquid elements"),
        ("The largest moon of Saturn, known to possess a dense nitrogen atmosphere and liquid methane lakes.", "Titan", ["moon titan"], "Wikipedia - Titan (moon)"),
        ("The genetic mutation in humans that causes red blood cells to assume a rigid, crescent shape.", "Sickle Cell Anemia", ["sickle cell disease", "sickle cell"], "Wikipedia - Sickle cell disease"),
        ("The measure of disorder or randomness in a thermodynamic system.", "Entropy", ["second law of thermodynamics"], "Wikipedia - Entropy"),
        ("The French chemist considered the father of modern chemistry who discovered the role of oxygen in combustion.", "Antoine Lavoisier", ["lavoisier"], "Wikipedia - Antoine Lavoisier"),
        ("The biological term for an organism's observable characteristics resulting from genetic makeup and environment.", "Phenotype", ["phenotypes"], "Wikipedia - Phenotype"),
        ("The biological term for the full genetic constitution of an individual organism.", "Genotype", ["genotypes"], "Wikipedia - Genotype"),
        ("The scientist who formulated the wave equation for quantum mechanical systems, sharing the 1933 Nobel Prize.", "Erwin Schrodinger", ["schrodinger", "schrödinger"], "Wikipedia - Erwin Schrödinger"),
        ("The primary greenhouse gas produced by livestock digestion and the decomposition of landfill waste.", "Methane", ["ch4"], "Wikipedia - Methane"),
        ("The distance light travels in one Julian year in a vacuum (~9.46 trillion kilometers).", "Light-year", ["light year"], "Wikipedia - Light-year"),
        ("The enzyme present in human saliva that begins the chemical breakdown of carbohydrates.", "Amylase", ["salivary amylase", "ptyalin"], "Wikipedia - Amylase"),
        ("The theoretical temperature at which all molecular motion ceases (0 K or -273.15 °C).", "Absolute Zero", ["0 kelvin"], "Wikipedia - Absolute Zero"),
        ("The organ in vertebrates that regulates blood sugar, detoxifies chemicals, and synthesizes proteins.", "Liver", ["the liver"], "Wikipedia - Liver"),
        ("The telescope launched by NASA in 1990 that provided unprecedented deep-field imagery of the universe.", "Hubble Space Telescope", ["hubble", "hst"], "Wikipedia - Hubble Space Telescope"),
        ("The newer space telescope launched on Christmas Day 2021 equipped with advanced infrared sensors.", "James Webb Space Telescope", ["jwst", "webb telescope", "james webb"], "Wikipedia - James Webb Space Telescope"),
        ("The SI unit of electric charge, equal to the charge of approximately 6.242 × 10^18 protons.", "Coulomb", ["coulombs", "c"], "Wikipedia - Coulomb"),
        ("The layer of the Earth located directly beneath the crust and above the outer core.", "Mantle", ["earth mantle"], "Wikipedia - Earth's mantle"),
        ("The phenomenon where two or more waves overlap to produce a new wave pattern.", "Interference", ["wave interference"], "Wikipedia - Wave interference"),
        ("The Russian chemist who created the first widely recognized version of the Periodic Table of Elements in 1869.", "Dmitri Mendeleev", ["mendeleev"], "Wikipedia - Dmitri Mendeleev"),
        ("The branch of science that studies fossils and ancient life forms.", "Paleontology", ["palaeontology"], "Wikipedia - Paleontology")
    ]
    for c, a, ac, s in q300: items.append((300, c, a, ac, s))

    # --- $400: Advanced / Technical (40 items) ---
    q400 = [
        ("The boundary around a black hole beyond which nothing, not even light, can escape.", "Event Horizon", ["the event horizon", "schwarzschild radius"], "Wikipedia - Event Horizon"),
        ("The non-metallic halogen element with atomic number 53, essential for thyroid hormone synthesis.", "Iodine", ["i"], "Wikipedia - Iodine"),
        ("The Austrian monk who pioneered the laws of genetic inheritance through experiments with pea plants.", "Gregor Mendel", ["mendel"], "Wikipedia - Gregor Mendel"),
        ("The subatomic particle predicted by Peter Higgs in 1964 and confirmed at CERN's LHC in 2012.", "Higgs Boson", ["higgs particle", "god particle"], "Wikipedia - Higgs Boson"),
        ("The process where unstable atomic nuclei lose energy by emitting ionizing particles.", "Radioactive Decay", ["radioactivity"], "Wikipedia - Radioactive Decay"),
        ("The law in fluid dynamics stating that the buoyant force on a submerged body equals the weight of displaced fluid.", "Archimedes' Principle", ["archimedes principle"], "Wikipedia - Archimedes' Principle"),
        ("The innermost layer of the Sun's atmosphere visible during a total solar eclipse as a pearly white halo.", "Corona", ["solar corona"], "Wikipedia - Solar Corona"),
        ("The transition metal with the highest melting point of all elements (3,422 °C), used in incandescent bulb filaments.", "Tungsten", ["wolfram", "w"], "Wikipedia - Tungsten"),
        ("The neurotransmitter primarily involved in reward, motivation, and motor control, depleted in Parkinson's disease.", "Dopamine", ["da"], "Wikipedia - Dopamine"),
        ("The mathematical constant 'e', approximately 2.71828, is named in honor of this Swiss mathematician.", "Leonhard Euler", ["euler"], "Wikipedia - e (mathematical constant)"),
        ("The phenomenon where light shifts toward longer wavelengths when an astronomical object moves away from the observer.", "Redshift", ["doppler redshift"], "Wikipedia - Redshift"),
        ("The SI unit of catalytic activity of enzymes, defining moles transformed per second.", "Katal", ["kat"], "Wikipedia - Katal"),
        ("The Danish physicist who introduced the model of the atom with quantized electron orbits in 1913.", "Niels Bohr", ["bohr"], "Wikipedia - Niels Bohr"),
        ("The four fundamental forces of nature: gravity, electromagnetism, weak nuclear force, and this force holding nuclei together.", "Strong Nuclear Force", ["strong force", "strong interaction"], "Wikipedia - Strong interaction"),
        ("The geological period between the Devonian and Permian famous for dense coal-forming swamp forests.", "Carboniferous", ["carboniferous period"], "Wikipedia - Carboniferous"),
        ("The cell organelle containing digestive enzymes that break down waste materials and cellular debris.", "Lysosome", ["lysosomes"], "Wikipedia - Lysosome"),
        ("The law stating that the volume of a given mass of gas is inversely proportional to its pressure at constant temperature.", "Boyle's Law", ["boyles law"], "Wikipedia - Boyle's Law"),
        ("The law stating that gas volume is directly proportional to absolute temperature at constant pressure.", "Charles's Law", ["charles law"], "Wikipedia - Charles's Law"),
        ("The rare earth element with symbol Nd, used to manufacture the strongest commercially available permanent magnets.", "Neodymium", ["nd"], "Wikipedia - Neodymium"),
        ("The theoretical point in space-time where gravitational forces cause matter to have infinite density.", "Gravitational Singularity", ["singularity"], "Wikipedia - Gravitational Singularity"),
        ("The process by which an organism maintains a stable internal environment despite external fluctuations.", "Homeostasis", ["homeostatic regulation"], "Wikipedia - Homeostasis"),
        ("The effect where an electric current flows across two junctions of dissimilar conductors kept at different temperatures.", "Seebeck Effect", ["thermoelectric effect"], "Wikipedia - Thermoelectric effect"),
        ("The moon of Jupiter that is the most volcanically active body in the solar system.", "Io", ["jupiter moon io"], "Wikipedia - Io (moon)"),
        ("The moon of Jupiter harboring a vast subsurface liquid water ocean beneath an icy crust.", "Europa", ["moon europa"], "Wikipedia - Europa (moon)"),
        ("The English physician who first correctly described systemic blood circulation pumped by the heart.", "William Harvey", ["harvey"], "Wikipedia - William Harvey"),
        ("The element with atomic number 92, the heaviest naturally occurring primordially stable actinide element.", "Uranium", ["u"], "Wikipedia - Uranium"),
        ("The quantum mechanical principle stating that no two identical fermions can occupy the same quantum state simultaneously.", "Pauli Exclusion Principle", ["pauli exclusion", "pauli"], "Wikipedia - Pauli Exclusion Principle"),
        ("The process where plants release water vapor into the atmosphere primarily through stomata.", "Transpiration", ["plant transpiration"], "Wikipedia - Transpiration"),
        ("The scientist who mathematically united electricity, magnetism, and light into classical electromagnetism in 1865.", "James Clerk Maxwell", ["maxwell"], "Wikipedia - James Clerk Maxwell"),
        ("The geological eon preceding the Phanerozoic, spanning from Earth's formation to 541 million years ago.", "Precambrian", ["precambrian supereon"], "Wikipedia - Precambrian"),
        ("The neurotransmitter primarily involved in regulating mood, sleep, appetite, and targeted by SSRIs.", "Serotonin", ["5-ht"], "Wikipedia - Serotonin"),
        ("The point in the orbit of a planet, asteroid, or comet at which it is closest to the Sun.", "Perihelion", ["perihelion point"], "Wikipedia - Perihelion"),
        ("The point in the orbit of an astronomical body furthest from the Sun.", "Aphelion", ["aphelion point"], "Wikipedia - Aphelion"),
        ("The dense stellar remnant that results when a massive star collapses with a mass insufficient to form a black hole.", "Neutron Star", ["pulsar"], "Wikipedia - Neutron Star"),
        ("The element named after the creator of the Nobel Prizes with atomic number 102.", "Nobelium", ["no"], "Wikipedia - Nobelium"),
        ("The biological class of warm-blooded egg-laying vertebrates that possess feathers and toothless beaked jaws.", "Aves", ["birds", "class aves"], "Wikipedia - Bird"),
        ("The SI unit of radiation absorbed dose, defined as absorption of one joule of radiation energy per kilogram.", "Gray", ["gy"], "Wikipedia - Gray (unit)"),
        ("The theorem stating that every continuous symmetry of the action of a physical system corresponds to a conservation law.", "Noether's Theorem", ["noether theorem", "emmy noether"], "Wikipedia - Noether's theorem"),
        ("The Italian scientist who discovered galvanism through electrical stimulation of dissected frog legs.", "Luigi Galvani", ["galvani"], "Wikipedia - Luigi Galvani"),
        ("The hormone produced by the beta cells of the islets of Langerhans in the pancreas.", "Insulin", ["human insulin"], "Wikipedia - Insulin")
    ]
    for c, a, ac, s in q400: items.append((400, c, a, ac, s))

    # --- $500: Expert / Trivia Master (40 items) ---
    q500 = [
        ("The hypothetical boundary located ~100,000 AU from the Sun marking the outer limit of our solar system's gravitational sphere.", "Oort Cloud", ["the oort cloud", "öpik-oort cloud"], "Wikipedia - Oort Cloud"),
        ("The constant ratio of a black hole's radius to its mass: R = 2GM/c², named after this German astronomer.", "Karl Schwarzschild", ["schwarzschild", "schwarzschild radius"], "Wikipedia - Karl Schwarzschild"),
        ("The organelle structure in prokaryotic and eukaryotic flagella exhibiting a characteristic '9+2' microtubule axoneme arrangement.", "Cilium", ["cilia", "axoneme"], "Wikipedia - Axoneme"),
        ("The chemical element with the highest density of all naturally occurring elements (22.59 g/cm³).", "Osmium", ["os"], "Wikipedia - Osmium"),
        ("The quantum mechanical paradox proposed in 1935 involving entanglement, abbreviated as EPR, proposed by Einstein, Podolsky, and him.", "Nathan Rosen", ["rosen", "epr paradox"], "Wikipedia - EPR paradox"),
        ("The theoretical particle that travels faster than the speed of light in hypothetical physics models.", "Tachyon", ["tachyons"], "Wikipedia - Tachyon"),
        ("The rare earth element with atomic number 61, the only promethium lanthanide with no stable isotopes.", "Promethium", ["pm"], "Wikipedia - Promethium"),
        ("The equation that estimates the number of active, communicative extraterrestrial civilizations in the Milky Way galaxy.", "Drake Equation", ["frank drake", "drake formula"], "Wikipedia - Drake Equation"),
        ("The only known living cephalopod species with an external coiled chambered shell that acts as a buoyancy organ.", "Nautilus", ["chambered nautilus"], "Wikipedia - Nautilus"),
        ("The enzyme that adds repetitive nucleotide sequences to the ends of chromosomes to prevent DNA degradation during replication.", "Telomerase", ["telomere terminal transferase"], "Wikipedia - Telomerase"),
        ("The process where a heavy unstable atomic nucleus splits spontaneously without external neutron absorption.", "Spontaneous Fission", ["spontaneous nuclear fission"], "Wikipedia - Spontaneous Fission"),
        ("The non-protein chemical compound or metallic ion required for an enzyme's biological activity as a catalyst.", "Cofactor", ["coenzyme"], "Wikipedia - Cofactor (biochemistry)"),
        ("The distance at which a celestial body held together only by its own gravity disintegrates due to a second body's tidal forces.", "Roche Limit", ["roche radius"], "Wikipedia - Roche limit"),
        ("The radioactive decay mode where an atomic nucleus emits an electron or positron, converting a neutron into a proton or vice versa.", "Beta Decay", ["beta radiation"], "Wikipedia - Beta decay"),
        ("The thermodynamic state where the liquid and gas phases of a substance become indistinguishable above a critical point.", "Supercritical Fluid", ["supercritical state"], "Wikipedia - Supercritical fluid"),
        ("The constant 6.022 × 10^23 defining the number of constituent particles in one mole of a substance.", "Avogadro's Number", ["avogadro constant", "amedeo avogadro"], "Wikipedia - Avogadro constant"),
        ("The mathematical theorem in quantum mechanics stating that identical quantum states cannot be cloned.", "No-cloning Theorem", ["no cloning"], "Wikipedia - No-cloning theorem"),
        ("The German physicist who discovered X-rays in 1895 and won the very first Nobel Prize in Physics in 1901.", "Wilhelm Rontgen", ["rontgen", "roentgen", "wilhelm röntgen"], "Wikipedia - Wilhelm Röntgen"),
        ("The chemical element named after the father of quantum theory Max Planck, with atomic number 106.", "Seaborgium", ["sg"], "Wikipedia - Seaborgium"),
        ("The layer of Earth's atmosphere between the stratosphere and thermosphere, where meteors burn upon entry.", "Mesosphere", ["the mesosphere"], "Wikipedia - Mesosphere"),
        ("The phase transition where a substance passes directly from the gas to solid state without liquid phase.", "Deposition", ["desublimation"], "Wikipedia - Deposition (phase transition)"),
        ("The deepest artificial borehole on Earth, reaching a depth of 12,262 meters in Russia's Kola Peninsula.", "Kola Superdeep Borehole", ["kola borehole", "kola superdeep"], "Wikipedia - Kola Superdeep Borehole"),
        ("The mathematical equation describing the relationship between standard reduction potential and ion activity, named after a German chemist.", "Nernst Equation", ["walther nernst"], "Wikipedia - Nernst equation"),
        ("The theoretical particle with mass and spin 2 predicted to mediate the force of gravitation in quantum field theory.", "Graviton", ["gravitons"], "Wikipedia - Graviton"),
        ("The moon of Neptune discovered in 1846 by William Lassell that features retrograde orbit and nitrogen cryovolcanoes.", "Triton", ["moon triton"], "Wikipedia - Triton (moon)"),
        ("The geological epoch that experienced the sudden global Paleocene-Eocene Thermal Maximum ~56 million years ago.", "Eocene", ["eocene epoch"], "Wikipedia - Eocene"),
        ("The biological class of jawless primitive fish that includes hagfishes and lampreys.", "Agnatha", ["agnathans", "jawless fish"], "Wikipedia - Agnatha"),
        ("The scientist who first demonstrated in 1801 the wave nature of light using the double-slit experiment.", "Thomas Young", ["young"], "Wikipedia - Double-slit experiment"),
        ("The hypothetical state of matter in quantum chromodynamics at ultra-high temperatures and densities where quarks are deconfined.", "Quark-Gluon Plasma", ["qgp"], "Wikipedia - Quark-gluon plasma"),
        ("The organic base in RNA that replaces thymine, pairing complementarily with adenine.", "Uracil", ["u"], "Wikipedia - Uracil"),
        ("The boundary surface within Earth separating the solid inner core from the liquid outer core.", "Lehmann Discontinuity", ["lehmann boundary", "inge lehmann"], "Wikipedia - Lehmann discontinuity"),
        ("The effect in quantum electrodynamics where an uncharged conducting plate pair in a vacuum experiences an attractive force.", "Casimir Effect", ["casimir force", "hendrik casimir"], "Wikipedia - Casimir effect"),
        ("The enzyme that catalyzes the transcription of RNA from a DNA template.", "RNA Polymerase", ["rna pol"], "Wikipedia - RNA polymerase"),
        ("The physical constant governing the strength of the electromagnetic interaction between elementary charged particles (~1/137).", "Fine-structure Constant", ["alpha", "fine structure constant"], "Wikipedia - Fine-structure constant"),
        ("The geological eon that saw the Great Oxidation Event and the emergence of the first multicellular life forms.", "Proterozoic", ["proterozoic eon"], "Wikipedia - Proterozoic"),
        ("The non-protein pigment component of hemoglobin that contains a central ferrous iron ion.", "Heme", ["haem", "heme group"], "Wikipedia - Heme"),
        ("The astronomer who observed the cosmic microwave background radiation in 1964 alongside Robert Wilson, winning the 1978 Nobel Prize.", "Arno Penzias", ["penzias"], "Wikipedia - Arno Penzias"),
        ("The theoretical temperature limit above which current models of physical theory break down (~1.417 × 10^32 K).", "Planck Temperature", ["planck scale"], "Wikipedia - Planck units"),
        ("The element with atomic number 118, the heaviest synthetic element on the modern periodic table, named after Yuri Oganessian.", "Oganesson", ["og"], "Wikipedia - Oganesson"),
        ("The process where electrons are ejected from a metal surface when irradiated by light of sufficient frequency.", "Photoelectric Effect", ["hertz effect"], "Wikipedia - Photoelectric effect")
    ]
    for c, a, ac, s in q500: items.append((500, c, a, ac, s))

    return items

if __name__ == "__main__":
    qs = get_science_questions()
    print(f"Generated {len(qs)} science questions!")
