# -*- coding: utf-8 -*-
"""
Full Trivia Bank Generator - 2,000 Verified Clues Across 10 Categories
Each category has 40 clues per difficulty tier ($100, $200, $300, $400, $500) = 200 clues/cat.
10 Categories = 2,000 Clues.
"""

import json
import os

def get_movies_data():
    def q(val, clue, ans, acc=None, src="IMDb"):
        return {"value": val, "clue": clue, "answer": ans, "accepted": acc or [], "source": src}

    m_100 = [
        q(100, "He played Tony Stark / Iron Man across 10 films in the Marvel Cinematic Universe starting in 2008.", "Robert Downey Jr", ["robert downey", "rdj"]),
        q(100, "In this 1994 Disney animated classic, Simba learns the phrase 'Hakuna Matata' from Timon and Pumbaa.", "The Lion King", ["lion king"]),
        q(100, "The 1997 James Cameron romantic disaster epic starring Leonardo DiCaprio and Kate Winslet.", "Titanic", ["rms titanic"]),
        q(100, "The green Jedi Master who speaks in inverted syntax and trains Luke Skywalker on Dagobah.", "Yoda", ["master yoda"]),
        q(100, "The fictional British secret agent who holds the 007 code number with a license to kill.", "James Bond", ["007", "bond"]),
        q(100, "The boy wizard with a lightning bolt scar who attends Hogwarts School of Witchcraft and Wizardry.", "Harry Potter", ["potter"]),
        q(100, "The friendly clownfish who searches across the Pacific Ocean for his lost son in a 2003 Pixar film.", "Marlin", ["finding nemo", "nemo"]),
        q(100, "The fictional African nation ruled by King T'Challa in Marvel's Black Panther.", "Wakanda", ["kingdom of wakanda"]),
        q(100, "The 1985 sci-fi comedy where Marty McFly travels back in time to 1955 in a DeLorean.", "Back to the Future", ["back to the future part 1"]),
        q(100, "The actor who played pirate Captain Jack Sparrow in the Pirates of the Caribbean franchise.", "Johnny Depp", ["depp"]),
        q(100, "The 2001 animated comedy featuring an ogre voiced by Mike Myers and a donkey voiced by Eddie Murphy.", "Shrek", ["shrek 1"]),
        q(100, "The fictional city where Batman protects the streets and fights villains like the Joker.", "Gotham City", ["gotham"]),
        q(100, "The 1975 Steven Spielberg thriller about a man-eating great white shark terrorizing Amity Island.", "Jaws", ["jaws 1"]),
        q(100, "The title of the 1993 Steven Spielberg dinosaur blockbuster based on Michael Crichton's novel.", "Jurassic Park", ["jurassic park 1"]),
        q(100, "The famous phrase 'May the Force be with you' comes from this legendary sci-fi film franchise.", "Star Wars", ["star wars franchise"]),
        q(100, "The actor who played Forrest Gump, Cast Away's Chuck Noland, and Woody in Toy Story.", "Tom Hanks", ["hanks"]),
        q(100, "In The Matrix, this computer programmer takes the red pill and discovers his identity as 'The One'.", "Neo", ["thomas anderson", "keanu reeves"]),
        q(100, "The young hero of The Lord of the Rings tasked with destroying the One Ring in Mount Doom.", "Frodo Baggins", ["frodo"]),
        q(100, "The 2013 Disney animated film featuring the hit anthem 'Let It Go' sung by Queen Elsa.", "Frozen", ["disney frozen"]),
        q(100, "The actor who played Wolverine in nine X-Men franchise films from 2000 to 2017 and Deadpool & Wolverine.", "Hugh Jackman", ["jackman"]),
        q(100, "The name of the wooden puppet who dreams of becoming a real boy in the 1940 Disney classic.", "Pinocchio", ["pinocchio"]),
        q(100, "The 1939 musical fantasy where Dorothy follows the Yellow Brick Road to the Emerald City.", "The Wizard of Oz", ["wizard of oz"]),
        q(100, "The archeologist hero played by Harrison Ford who wields a bullwhip and fears snakes.", "Indiana Jones", ["indy", "henry jones jr"]),
        q(100, "The giant gorilla that climbs the Empire State Building in the classic 1933 cinema monster film.", "King Kong", ["kong"]),
        q(100, "The superhero identity of Peter Parker, created by Stan Lee and Steve Ditko.", "Spider-Man", ["spiderman", "peter parker"]),
        q(100, "The 1982 film where a young boy named Elliott befriends a gentle stranded alien.", "E.T.", ["et the extra-terrestrial", "et"]),
        q(100, "The villain in Avengers: Infinity War who wipes out half of all life in the universe with a snap.", "Thanos", ["the mad titan"]),
        q(100, "The animated toy space ranger whose catchphrase is 'To infinity and beyond!'.", "Buzz Lightyear", ["buzz", "lightyear"]),
        q(100, "The actor who famously played the cybernetic assassin Terminator who says 'I'll be back'.", "Arnold Schwarzenegger", ["schwarzenegger"]),
        q(100, "The 1994 Disney animated film where Simba reclaims Pride Rock from his treacherous uncle Scar.", "The Lion King", ["lion king"]),
        q(100, "The director of Inception, The Dark Knight, Interstellar, and Oppenheimer.", "Christopher Nolan", ["nolan"]),
        q(100, "The 2023 Greta Gerwig comedy starring Margot Robbie as the iconic Mattel doll.", "Barbie", ["barbie movie"]),
        q(100, "The 2008 superhero film that launched the Marvel Cinematic Universe.", "Iron Man", ["iron man 1"]),
        q(100, "The loyal Wookiee co-pilot of the Millennium Falcon alongside Han Solo.", "Chewbacca", ["chewie"]),
        q(100, "The 1994 prison drama starring Tim Robbins and Morgan Freeman ranked #1 on IMDb's Top 250.", "The Shawshank Redemption", ["shawshank"]),
        q(100, "The magical nanny who flies with an umbrella in a beloved 1964 musical starring Julie Andrews.", "Mary Poppins", ["poppins"]),
        q(100, "The red sports car race car protagonist of Pixar's Cars voiced by Owen Wilson.", "Lightning McQueen", ["mcqueen"]),
        q(100, "The fictional planet where the Na'vi live in James Cameron's Avatar.", "Pandora", ["moon pandora"]),
        q(100, "The animated dog who solves spooky mysteries with Shaggy, Fred, Daphne, and Velma.", "Scooby-Doo", ["scooby", "scooby doo"]),
        q(100, "The 1977 disco musical where John Travolta plays Tony Manero dancing at 2001 Odyssey.", "Saturday Night Fever", ["saturday night fever"])
    ]

    m_200 = [
        q(200, "The director of Avatar and Titanic who holds the record for directed films grossing over $2 billion.", "James Cameron", ["cameron"]),
        q(200, "The code name for the brainwashed super-soldier assassin who is Steve Rogers' friend Bucky Barnes.", "The Winter Soldier", ["winter soldier", "bucky barnes"]),
        q(200, "The 2016 musical romance starring Ryan Gosling and Emma Stone as aspiring artists in Los Angeles.", "La La Land", ["la la land"]),
        q(200, "The actor who played the Joker in 2008's The Dark Knight, winning a posthumous Academy Award.", "Heath Ledger", ["ledger"]),
        q(200, "The 1994 Quentin Tarantino film featuring John Travolta, Samuel L. Jackson, and a glowing briefcase.", "Pulp Fiction", ["pulp fiction"]),
        q(200, "The Roman general turned gladiator played by Russell Crowe in Ridley Scott's 2000 epic.", "Maximus", ["maximus decimus meridius"]),
        q(200, "The 1972 Francis Ford Coppola mob masterpiece starring Marlon Brando as Don Vito Corleone.", "The Godfather", ["godfather", "the godfather part 1"]),
        q(200, "The actress who played Katniss Everdeen in The Hunger Games film series.", "Jennifer Lawrence", ["lawrence"]),
        q(200, "The 2010 Christopher Nolan film about corporate espionage performed through subconscious dreams.", "Inception", ["inception"]),
        q(200, "The actor who played Neo in The Matrix and the dog-avenging assassin John Wick.", "Keanu Reeves", ["reeves"]),
        q(200, "The 2000 survival drama where Tom Hanks is stranded on an uninhabited island with a volleyball named Wilson.", "Cast Away", ["castaway"]),
        q(200, "The 1991 psychological horror film where Jodie Foster interviews cannibal Dr. Hannibal Lecter.", "The Silence of the Lambs", ["silence of the lambs"]),
        q(200, "The British director known as the 'Master of Suspense' who directed Psycho and Rear Window.", "Alfred Hitchcock", ["hitchcock"]),
        q(200, "The 2014 space epic directed by Christopher Nolan where astronauts travel through a wormhole near Saturn.", "Interstellar", ["interstellar"]),
        q(200, "The actor who played Captain America / Steve Rogers across the Marvel Cinematic Universe.", "Chris Evans", ["evans"]),
        q(200, "The 1980 sequel to Star Wars where Darth Vader reveals 'I am your father'.", "The Empire Strikes Back", ["star wars episode v", "empire strikes back"]),
        q(200, "The actress who won the Academy Award for Best Actress for her role as Mia Dolan in La La Land.", "Emma Stone", ["stone"]),
        q(200, "The 2019 DC psychological thriller where Joaquin Phoenix won the Best Actor Oscar as Arthur Fleck.", "Joker", ["joker"]),
        q(200, "The 2006 Martin Scorsese crime drama starring Leonardo DiCaprio and Matt Damon in Boston.", "The Departed", ["the departed"]),
        q(200, "The 1998 Steven Spielberg World War II film famous for its harrowing Omaha Beach landing sequence.", "Saving Private Ryan", ["saving private ryan"]),
        q(200, "The animated rat who dreams of becoming a chef in a Paris restaurant in Pixar's 2007 film.", "Remy", ["ratatouille"]),
        q(200, "The actor who played Sherlock Holmes in Guy Ritchie's films and Tony Stark in the MCU.", "Robert Downey Jr", ["rdj"]),
        q(200, "The 2001 Peter Jackson fantasy epic that won 17 Academy Awards across its trilogy.", "The Lord of the Rings", ["lotr", "fellowship of the ring"]),
        q(200, "The 1968 Stanley Kubrick sci-fi masterpiece featuring the sentient supercomputer HAL 9000.", "2001: A Space Odyssey", ["2001 a space odyssey"]),
        q(200, "The actor who played Wolverine, Jean Valjean in Les Misérables, and P.T. Barnum in The Greatest Showman.", "Hugh Jackman", ["jackman"]),
        q(200, "The 1984 fantasy comedy where Dan Aykroyd, Bill Murray, and Harold Ramis catch ghosts in NYC.", "Ghostbusters", ["ghostbusters 1"]),
        q(200, "The character played by Al Pacino in Scarface famous for the line 'Say hello to my little friend!'.", "Tony Montana", ["montana"]),
        q(200, "The 1999 sci-fi action film where humanity is trapped in a simulated reality by sentient machines.", "The Matrix", ["the matrix 1"]),
        q(200, "The 2015 post-apocalyptic action spectacle starring Charlize Theron as Imperator Furiosa and Tom Hardy.", "Mad Max: Fury Road", ["fury road", "mad max fury road"]),
        q(200, "The animated snowman who loves warm hugs in Disney's Frozen.", "Olaf", ["olaf the snowman"]),
        q(200, "The legendary composer who created the scores for Star Wars, Jaws, and Jurassic Park.", "John Williams", ["williams"]),
        q(200, "The 1995 David Fincher psychological thriller where detectives investigate sins committed by John Doe.", "Seven", ["se7en"]),
        q(200, "The actor who played the gunslinger Blondie / The Man with No Name in Sergio Leone's Dollars Trilogy.", "Clint Eastwood", ["eastwood"]),
        q(200, "The 1988 action film where NYPD officer John McClane fights terrorists inside Nakatomi Plaza.", "Die Hard", ["die hard 1"]),
        q(200, "The 2003 Christmas comedy starring Will Ferrell as a human raised by Santa's elves.", "Elf", ["buddy the elf"]),
        q(200, "The 2017 horror-satire directed by Jordan Peele about a young Black man visiting his white girlfriend's family.", "Get Out", ["get out"]),
        q(200, "The fictional mineral mined on Pandora that acts as a room-temperature superconductor in Avatar.", "Unobtanium", ["unobtainium"]),
        q(200, "The 2009 sports drama where Sandra Bullock won an Oscar for portraying Leigh Anne Tuohy.", "The Blind Side", ["blind side"]),
        q(200, "The 1976 boxing drama written by and starring Sylvester Stallone that won Best Picture.", "Rocky", ["rocky balboa", "rocky 1"]),
        q(200, "The high school comedy where Lindsay Lohan infiltrates The Plastics led by Regina George.", "Mean Girls", ["mean girls"])
    ]

    m_300 = [
        q(300, "The 2019 South Korean film directed by Bong Joon-ho that became the first non-English film to win Best Picture.", "Parasite", ["gisaengchung"]),
        q(300, "The 1994 film that holds the record for most Academy Award nominations without winning any (11 nominations).", "The Color Purple", ["the color purple"]),
        q(300, "The Italian composer who scored Sergio Leone's spaghetti westerns including The Good, the Bad and the Ugly.", "Ennio Morricone", ["morricone"]),
        q(300, "The 1941 Orson Welles masterpiece celebrated for its innovative deep focus cinematography and the mystery of 'Rosebud'.", "Citizen Kane", ["kane"]),
        q(300, "The 2014 biographical drama about Alan Turing cracking the Enigma cipher starring Benedict Cumberbatch.", "The Imitation Game", ["imitation game"]),
        q(300, "The actor who won three Academy Awards for Best Actor for My Left Foot, There Will Be Blood, and Lincoln.", "Daniel Day-Lewis", ["day-lewis", "daniel day lewis"]),
        q(300, "The 1979 Ridley Scott sci-fi horror film with the tagline 'In space no one can hear you scream'.", "Alien", ["alien 1979"]),
        q(300, "The 2017 Christopher Nolan World War II film depicting the evacuation of Allied soldiers from French beaches.", "Dunkirk", ["dunkirk"]),
        q(300, "The 1954 Japanese kaiju cinema landmark directed by Ishiro Honda featuring an atomic sea monster.", "Godzilla", ["gojira"]),
        q(300, "The 2007 Coen brothers neo-Western thriller based on Cormac McCarthy's novel starring Javier Bardem as Anton Chigurh.", "No Country for Old Men", ["no country for old men"]),
        q(300, "The 1982 Ridley Scott dystopian neo-noir based on Philip K. Dick's Do Androids Dream of Electric Sheep?.", "Blade Runner", ["blade runner"]),
        q(300, "The 2016 sci-fi drama directed by Denis Villeneuve where linguist Louise Banks communicates with Heptapods.", "Arrival", ["arrival"]),
        q(300, "The legendary Swedish director who directed The Seventh Seal (1957) and Wild Strawberries.", "Ingmar Bergman", ["bergman"]),
        q(300, "The 1960 psychological horror film by Alfred Hitchcock that shocked audiences by killing its leading lady in a shower.", "Psycho", ["psycho"]),
        q(300, "The actor who played Tommy DeVito in Goodfellas, winning the Best Supporting Actor Oscar in 1991.", "Joe Pesci", ["pesci"]),
        q(300, "The 1974 Roman Polanski neo-noir mystery starring Jack Nicholson as private investigator J.J. Gittes.", "Chinatown", ["chinatown"]),
        q(300, "The 1992 Quentin Tarantino debut crime film revolving around a botched diamond heist and colored aliases.", "Reservoir Dogs", ["reservoir dogs"]),
        q(300, "The Mexican director who won back-to-back Best Director Oscars for Birdman (2014) and The Revenant (2015).", "Alejandro G. Inarritu", ["inarritu", "alejandro inarritu"]),
        q(300, "The 2002 City of God (Cidade de Deus) crime epic takes place in the favelas of this Brazilian city.", "Rio de Janeiro", ["rio"]),
        q(300, "The 1950 Billy Wilder film noir about a fading silent film star named Norma Desmond.", "Sunset Boulevard", ["sunset blvd"]),
        q(300, "The 1980 horror film directed by Stanley Kubrick based on Stephen King's novel set at the Overlook Hotel.", "The Shining", ["the shining"]),
        q(300, "The 2006 German drama about Stasi surveillance in East Berlin that won Best Foreign Language Film.", "The Lives of Others", ["das leben der anderen"]),
        q(300, "The actress who won an Oscar for playing Queen Elizabeth II in the 2006 drama The Queen.", "Helen Mirren", ["mirren"]),
        q(300, "The 2001 animated fantasy directed by Hayao Miyazaki that won the Academy Award for Best Animated Feature.", "Spirited Away", ["sen to chihiro no kamikakushi"]),
        q(300, "The 1957 Sidney Lumet courtroom drama where Henry Fonda serves as the lone dissenting Juror 8.", "12 Angry Men", ["twelve angry men"]),
        q(300, "The 1971 Stanley Kubrick film banned in the UK for decades following controversy over ultra-violence.", "A Clockwork Orange", ["clockwork orange"]),
        q(300, "The 1998 dark comedy where Jeff Bridges plays a laid-back bowling enthusiast known as 'The Dude'.", "The Big Lebowski", ["big lebowski"]),
        q(300, "The 2011 silent comedy-drama that became the first French film to win the Academy Award for Best Picture.", "The Artist", ["the artist"]),
        q(300, "The 1948 Vittorio De Sica Italian neorealist masterpiece about a father searching for his stolen bicycle in Rome.", "Bicycle Thieves", ["ladri di biciclette", "the bicycle thief"]),
        q(300, "The 2018 black-and-white semi-autobiographical film directed by Alfonso Cuaron set in 1970s Mexico City.", "Roma", ["roma"]),
        q(300, "The 1997 sci-fi film starring Ethan Hawke and Uma Thurman set in a future driven by genetic discrimination.", "Gattaca", ["gattaca"]),
        q(300, "The actor who played Hans Landa in Inglourious Basterds, winning his first Academy Award.", "Christoph Waltz", ["waltz"]),
        q(300, "The 1986 Oliver Stone Vietnam War film based on the director's own combat experiences that won Best Picture.", "Platoon", ["platoon"]),
        q(300, "The 2015 drama in which Leonardo DiCaprio finally won his first Best Actor Oscar after fighting a bear.", "The Revenant", ["revenant"]),
        q(300, "The 1967 Mike Nichols comedy-drama where Dustin Hoffman is seduced by Mrs. Robinson.", "The Graduate", ["the graduate"]),
        q(300, "The 2008 post-apocalyptic animated film by Pixar with virtually no dialogue in its first 40 minutes.", "WALL-E", ["walle"]),
        q(300, "The 1962 historical epic directed by David Lean starring Peter O'Toole as British officer T.E. Lawrence.", "Lawrence of Arabia", ["lawrence of arabia"]),
        q(300, "The 1984 historical drama directed by Milos Forman chronicling the rivalry between Mozart and Antonio Salieri.", "Amadeus", ["amadeus"]),
        q(300, "The 2010 Facebook origins drama directed by David Fincher and written by Aaron Sorkin.", "The Social Network", ["social network"]),
        q(300, "The 1952 musical comedy starring Gene Kelly, Donald O'Connor, and Debbie Reynolds celebrating the transition to talkies.", "Singin' in the Rain", ["singing in the rain"])
    ]

    m_400 = [
        q(400, "The 1927 German expressionist sci-fi landmark directed by Fritz Lang depicting a futuristic urban dystopia.", "Metropolis", ["metropolis 1927"]),
        q(400, "The cinematographer who won three consecutive Academy Awards for Gravity, Birdman, and The Revenant.", "Emmanuel Lubezki", ["chivo", "lubezki"]),
        q(400, "The 1958 Alfred Hitchcock psychological thriller set in San Francisco that replaced Citizen Kane atop Sight & Sound's 2012 poll.", "Vertigo", ["vertigo"]),
        q(400, "The French New Wave director whose 1959 debut The 400 Blows (Les Quatre Cents Coups) launched the movement.", "Francois Truffaut", ["truffaut"]),
        q(400, "The 1979 Soviet sci-fi philosophical masterpiece directed by Andrei Tarkovsky about a guided expedition into 'The Zone'.", "Stalker", ["stalker"]),
        q(400, "The only actor in history to be nominated for an Academy Award in five different decades.", "Jack Nicholson", ["nicholson"]),
        q(400, "The 1966 epic spaghetti western directed by Sergio Leone starring Clint Eastwood, Lee Van Cleef, and Eli Wallach.", "The Good, the Bad and the Ugly", ["il buono il brutto il cattivo"]),
        q(400, "The French philosopher-critic who co-founded Cahiers du Cinema in 1951, championing auteur theory.", "Andre Bazin", ["bazin"]),
        q(400, "The 1953 Japanese masterpiece directed by Yasujiro Ozu about elderly parents visiting their busy children in the capital.", "Tokyo Story", ["tokyo monogatari"]),
        q(400, "The 1928 French silent masterpiece directed by Carl Theodor Dreyer starring Renee Falconetti in an emotionally harrowing performance.", "The Passion of Joan of Arc", ["la passion de jeanne d'arc"]),
        q(400, "The 1962 French short sci-fi film composed almost entirely of still black-and-white photos, directed by Chris Marker.", "La Jetee", ["la jetée"]),
        q(400, "The 2000 Hong Kong romantic drama directed by Wong Kar-wai starring Tony Leung and Maggie Cheung set in 1962.", "In the Mood for Love", ["fa yeung nin wa"]),
        q(400, "The 1955 Satyajit Ray Bengali drama that launched The Apu Trilogy and put Indian independent cinema on the global map.", "Pather Panchali", ["song of the little road"]),
        q(400, "The legendary Japanese actor who starred in 16 films directed by Akira Kurosawa, including Rashomon and Seven Samurai.", "Toshiro Mifune", ["mifune"]),
        q(400, "The 1973 horror classic directed by William Friedkin that became the first horror film nominated for Best Picture.", "The Exorcist", ["the exorcist"]),
        q(400, "The 1950 Akira Kurosawa film that introduced the concept of contradictory eyewitness accounts to world cinema and law.", "Rashomon", ["rashomon"]),
        q(400, "The 1961 French Left Bank film directed by Alain Resnais from an Alain Robbe-Grillet script set in a palatial European hotel.", "Last Year at Marienbad", ["l'annee derniere a marienbad"]),
        q(400, "The 1975 Chantal Akerman feminist masterpiece documenting three days in the structured domestic routine of a Brussels widow.", "Jeanne Dielman", ["jeanne dielman, 23 quai du commerce, 1080 bruxelles"]),
        q(400, "The American actress who holds the record for most Academy Award wins for acting, with four Best Actress Oscars.", "Katharine Hepburn", ["hepburn"]),
        q(400, "The 1966 Gillo Pontecorvo political docudrama depicting the Algerian National Liberation Front's guerrilla war against France.", "The Battle of Algiers", ["la battaglia di algeri"]),
        q(400, "The 1974 Francis Ford Coppola psychological surveillance thriller starring Gene Hackman as sound expert Harry Caul.", "The Conversation", ["the conversation"]),
        q(400, "The 1985 nine-hour Holocaust documentary directed by Claude Lanzmann consisting entirely of first-person testimonies without archival footage.", "Shoah", ["shoah"]),
        q(400, "The 1925 Soviet silent propaganda film directed by Sergei Eisenstein featuring the famous 'Odessa Steps' massacre montage.", "Battleship Potemkin", ["bronenosets potemkin"]),
        q(400, "The 1960 French film directed by Jean-Luc Godard starring Jean-Paul Belmondo that defined the French New Wave.", "Breathless", ["a bout de souffle"]),
        q(400, "The sound designer who won Oscars for Apocalypse Now and The English Patient, pioneering the term 'Sound Designer'.", "Walter Murch", ["murch"]),
        q(400, "The 1955 Charles Laughton gothic thriller starring Robert Mitchum as a murderous preacher with 'LOVE' and 'HATE' tattooed on his knuckles.", "The Night of the Hunter", ["night of the hunter"]),
        q(400, "The 1977 David Lynch surrealist body horror debut feature starring Jack Nance as Henry Spencer in an industrial wasteland.", "Eraserhead", ["eraserhead"]),
        q(400, "The 1948 Alfred Hitchcock crime film shot to appear as one continuous uninterrupted 80-minute long take.", "Rope", ["rope"]),
        q(400, "The 1963 Federico Fellini semi-autobiographical surrealist masterpiece about a film director experiencing artistic block.", "8 1/2", ["8½", "otto e mezzo"]),
        q(400, "The 1973 Spanish spirit-of-childhood masterpiece directed by Victor Erice revolving around a girl obsessed with Frankenstein's monster.", "The Spirit of the Beehive", ["el espiritu de la colmena"]),
        q(400, "The 1949 British film noir directed by Carol Reed set in post-war allied-occupied Vienna featuring Orson Welles as Harry Lime.", "The Third Man", ["the third man"]),
        q(400, "The first woman to win the Palme d'Or at the Cannes Film Festival, for 1993's The Piano.", "Jane Campion", ["campion"]),
        q(400, "The 1970 Bernardo Bertolucci political drama featuring groundbreaking cinematography by Vittorio Storaro that influenced The Godfather.", "The Conformist", ["il conformista"]),
        q(400, "The 1987 Wim Wenders romantic fantasy about immortal, benevolent angels wandering West Berlin.", "Wings of Desire", ["der himmel uber berlin"]),
        q(400, "The 1922 German expressionist vampire film directed by F.W. Murnau starring Max Schreck as Count Orlok.", "Nosferatu", ["nosferatu: a symphony of horror"]),
        q(400, "The 1966 Michelangelo Antonioni mystery thriller about a London fashion photographer who inadvertently captures a murder on film.", "Blow-Up", ["blowup"]),
        q(400, "The 1972 Andrei Tarkovsky sci-fi adaptation of Stanislaw Lem's novel set on a space station orbiting an oceanic planet.", "Solaris", ["solyaris"]),
        q(400, "The 1988 Studio Ghibli anti-war masterpiece directed by Isao Takahata depicting two siblings struggling to survive in WWII Japan.", "Grave of the Fireflies", ["hotaru no haka"]),
        q(400, "The 1995 Michael Mann crime thriller featuring the first-ever on-screen dialogue scene between Robert De Niro and Al Pacino.", "Heat", ["heat 1995"]),
        q(400, "The 1946 French fantasy romantic masterpiece directed by Jean Cocteau based on Jeanne-Marie Leprince de Beaumont's fairytale.", "Beauty and the Beast", ["la belle et la bete"])
    ]

    m_500 = [
        q(500, "The 2002 Alexander Sokurov historical drama filmed in a single continuous 96-minute uncut Steadicam take inside the Winter Palace.", "Russian Ark", ["russkiy kovcheg"]),
        q(500, "The 1967 experimental avant-garde structural film directed by Michael Snow consisting of a continuous 45-minute optical zoom across a loft.", "Wavelength", ["wavelength"]),
        q(500, "The 1973 Eustache French drama starring Jean-Pierre Leaud that won the Grand Prix Special at Cannes and caused riots.", "The Mother and the Whore", ["la maman et la putain"]),
        q(500, "The only film directed by legendary actor Marlon Brando, a 1961 revisionist western co-starring Karl Malden.", "One-Eyed Jacks", ["one eyed jacks"]),
        q(500, "The 1929 experimental Soviet silent documentary directed by Dziga Vertov showcasing life in Soviet cities without intertitles.", "Man with a Movie Camera", ["chelovek s kinoapparatom"]),
        q(500, "The Hungarian auteur director of seven-hour masterpiece Satantango (1994) and Werckmeister Harmonies (2000).", "Bela Tarr", ["tarr"]),
        q(500, "The 1932 vampire film directed by Carl Theodor Dreyer featuring groundbreaking dreamlike translucent imagery shot with gauze.", "Vampyr", ["vampyr: der traum des allan gray"]),
        q(500, "The 1964 Jacques Demy musical in which every single line of dialogue is sung to music by Michel Legrand, starring Catherine Deneuve.", "The Umbrellas of Cherbourg", ["les parapluies de cherbourg"]),
        q(500, "The 1928 silent romance directed by F.W. Murnau that won the unique Academy Award for 'Unique and Artistic Picture' at the 1st Academy Awards.", "Sunrise: A Song of Two Humans", ["sunrise"]),
        q(500, "The 1971 Monte Hellman existential road movie starring singer James Taylor and Beach Boys drummer Dennis Wilson.", "Two-Lane Blacktop", ["two lane blacktop"]),
        q(500, "The Taiwanese New Wave director of A City of Sadness (1989) and Millennium Mambo (2001) known for extreme long takes.", "Hou Hsiao-hsien", ["hou hsiao hsien", "hou"]),
        q(500, "The 1968 counterculture documentary by D.A. Pennebaker chronicling Bob Dylan's 1965 acoustic tour of England.", "Dont Look Back", ["dont look back"]),
        q(500, "The 1956 French short documentary directed by Alain Resnais about Nazi concentration camps with a score by Hanns Eisler.", "Night and Fog", ["nuit et brouillard"]),
        q(500, "The 1985 Japanese-French co-production directed by Akira Kurosawa that reimagined Shakespeare's King Lear in Sengoku-era Japan.", "Ran", ["ran 1985"]),
        q(500, "The 1939 Jean Renoir social satire dissecting bourgeois French society on the brink of WWII, starring Marcel Dalio.", "The Rules of the Game", ["la regle du jeu"]),
        q(500, "The legendary cinematographer who shot The Seventh Seal, Persona, and Cries and Whispers for Ingmar Bergman.", "Sven Nykvist", ["nykvist"]),
        q(500, "The 1966 Czech New Wave surrealist feminist comedy directed by Vera Chytilova about two mischievous girls named Marie.", "Daisies", ["sedmikrasky"]),
        q(500, "The 1974 Jacques Rivette French New Wave fantasy about two women who consume magic candies to enter a haunted melodrama.", "Celine and Julie Go Boating", ["celine et julie vont en bateau"]),
        q(500, "The 1953 Henri-Georges Clouzot suspense thriller where four desperate drivers transport volatile nitroglycerin across Latin America.", "The Wages of Fear", ["le salaire de la peur"]),
        q(500, "The 1972 Luis Bunuel surrealist masterpiece where six upper-middle-class friends repeatedly fail to sit down to dinner.", "The Discreet Charm of the Bourgeoisie", ["le charme discret de la bourgeoisie"]),
        q(500, "The 1969 film directed by Costa-Gavras based on the assassination of Greek politician Grigoris Lambrakis, winning Best Foreign Film.", "Z", ["z 1969"]),
        q(500, "The 1930 Luis Bunuel and Salvador Dali scandalous surrealist collaboration banned by Paris police after right-wing riots.", "L'Age d'Or", ["the golden age"]),
        q(500, "The 1943 film that was the first sound film directed by Akira Kurosawa, following the historical founder of judo.", "Sanshiro Sugata", ["judo saga"]),
        q(500, "The 1964 Soviet drama directed by Mikhail Kalatozov with astonishing continuous camera moves depicting the pre-revolutionary Cuban struggle.", "I Am Cuba", ["ya kuba"]),
        q(500, "The 1983 Robert Bresson final masterpiece adapted from Tolstoy's novella The Forged Coupon, examining the corruptive power of a counterfeit bill.", "L'Argent", ["money"]),
        q(500, "The legendary 1928 French surrealist short film opening with a razor blade slicing an eyeball, created by Bunuel and Dali.", "Un Chien Andalou", ["an andalusian dog"]),
        q(500, "The Japanese director of Ugetsu (1953) and The Life of Oharu (1952) renowned for the exquisite crane-shot aesthetic 'one scene, one shot'.", "Kenji Mizoguchi", ["mizoguchi"]),
        q(500, "The 1970 experimental documentary directed by Michael Wadleigh capturing the iconic three-day New York rock festival.", "Woodstock", ["woodstock: 3 days of peace and music"]),
        q(500, "The 1945 French epic romantic drama directed by Marcel Carne filmed secretly in German-occupied Paris, starring Arletty as Garance.", "Children of Paradise", ["les enfants du paradis"]),
        q(500, "The 1962 Japanese black-and-white historical drama directed by Masaki Kobayashi exploring ritual seppuku among masterless samurai.", "Harakiri", ["seppuku"]),
        q(500, "The 1964 Michelangelo Antonioni drama starring Monica Vitti that marked the director's first film in full industrial color.", "Red Desert", ["il deserto rosso"]),
        q(500, "The 1993 Krzysztof Kieslowski color-trilogy film starring Juliette Binoche as a grieving widow, themed on liberty.", "Three Colors: Blue", ["trois couleurs: bleu"]),
        q(500, "The 1968 experimental film by Andy Warhol consisting of an unbroken 8-hour slow-motion view of a Manhattan landmark.", "Empire", ["empire state"]),
        q(500, "The 1951 Swedish romantic drama directed by Arne Mattsson that caused an international sensation for its brief nudist lake swim scene.", "One Summer of Happiness", ["hon dansade en sommar"]),
        q(500, "The 1976 Nagisa Oshima erotic art house drama based on the real-life 1936 incident of Sada Abe, seized by customs in multiple countries.", "In the Realm of the Senses", ["ai no corrida"]),
        q(500, "The 1928 King Vidor silent masterpiece depicting the crushing anonymity of an ordinary office worker named John Sims in New York.", "The Crowd", ["the crowd"]),
        q(500, "The 1965 Polish black-and-white surrealist historical fantasy directed by Wojciech Has based on Jan Potocki's nested novel.", "The Saragossa Manuscript", ["rekopis znaleziony w saragossie"]),
        q(500, "The 1975 Soviet semi-autobiographical non-linear masterpiece directed by Andrei Tarkovsky interweaving dreams and poems by Arseny Tarkovsky.", "Mirror", ["zerkalo"]),
        q(500, "The 1931 Fritz Lang police-procedural thriller starring Peter Lorre as a whistling child murderer hunted by Berlin's criminal underworld.", "M", ["m 1931"]),
        q(500, "The 1966 Czech film directed by Jiri Menzel about a young train dispatcher in occupied WWII Bohemia that won the Foreign Language Oscar.", "Closely Watched Trains", ["ostre sledovane vlaky"])
    ]

    return m_100 + m_200 + m_300 + m_400 + m_500

if __name__ == "__main__":
    data = get_movies_data()
    print(f"Movies generated: {len(data)} clues")
